### ISSUE TITLE
Interpolate builder type, and only run provisioner when matched

### ISSUE THREAD

**Issue by bleloch** [hashicorp/packer#5696] opened 2017-12-12 11:52 UTC
We currently have a template to provision a base image for our applications, which I'd like to run a specific provisioner for based on the builder type. This would allow us to have to run multiple 'configurations' into the same template and build one version of the image with Enhanced Networking and one without.

I'd like to be able to pass the $PROVISIONER variable containing 'Amazon-Machine-Base-Image' or 'Amazon-Machine-Enhanced-Networking-Image' to Packer, so that only the provisioner that matches the "name" variable is run. Here's the template I'm working with:

```
{
	"variables":
		{
			"ami_id_source": "{{env `BASE_IMAGE`}}",
			"aws_access_key_id": "{{env `AWS_ACCESS_KEY_ID`}}",
			"aws_secret_access_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
			"region": "{{env `AWS_REGION`}}",
			"provisioner_name": "{{env `PROVISIONER`}}",
			"sriov_enabled": "{{env `SRIOV_ENABLED`}}"
		},
	"builders": [
				{
					"name": "{{user `provisioner_name`}}",
					"type": "amazon-ebs",
					"access_key": "{{user `aws_access_key_id`}}",
					"secret_key": "{{user `aws_secret_access_key`}}",
					"region": "{{user `region`}}",
					"ami_regions": "{{user `region`}}",
					"source_ami_filter": {
    						"filters": {
      							"virtualization-type": "hvm",
							"name": "CentOS Linux 7 x86_64 HVM EBS*",
      							"root-device-type": "ebs"
    						},
    						"owners": ["410186602215"],
    						"most_recent": true
					},
					"instance_type": "t2.small",
					"sriov_support": "{{user `sriov_enabled`}}",
					"ami_block_device_mappings": [ {
						"device_name": "/dev/sda1",
						"volume_size": 8,
						"delete_on_termination": true
					} ],
					"launch_block_device_mappings": [ {
						"device_name": "/dev/sda1",
						"volume_size": 8,
						"delete_on_termination": true
					} ]
				}
				],
	"provisioners": [
		{
		  "only": ["Amazon-Machine-Base-Image"],
		  "type": "shell",
		  "inline": [
			"sleep 30",
			"sudo yum install epel-release -y; sudo yum update -y; sudo yum install ansible python-setuptools python-dateutil python-pip python-devel -y"
		  ]
		},
		{
	 	  "only": ["Amazon-Machine-Enhanced-Networking-Base-Image"],
	          "type": "shell",
		  "script": "Scripts/Shell/enhanced_networking.sh"		
		}
	]
}
```

I have verified that the `provisioner_name` variable is being populated properly and being passed to Packer. It would seem that Packer isn't aware of the contents of this variable when it parses the provisioners, as it throws this error:

```
* provisioner 1: 'only' specified builder 'Amazon-Machine-Base-Image' not found
* provisioner 2: 'only' specified builder 'Amazon-Machine-Enhanced-Networking-Base-Image' not found
```

Could someone confirm that it is expected behaviour for the builder type to be constant, and if so, is there a solution for this where we can keep just one template for both enhanced and non-enhanced networking images? 

I am running Packer 1.1.0 on Amazon Linux 2017.03.

**Comment by rickard-von-essen** [comment] 2017-12-12 12:45
Thanks for reporting this. This is a duplicate of #2651.

**Closed by rickard-von-essen** 2017-12-12 12:45 UTC
Labels: bug, core, duplicate
