### ISSUE TITLE
Can't use Chef-Solo with WinRM

### ISSUE THREAD

**Issue by Thumpermat** [hashicorp/packer#5726] opened 2017-12-21 12:17 UTC
Packer version: 1.1.2 and 1.1.3
Host platform: OSX El Capitan
Log Build with SSH: https://gist.github.com/Thumpermat/acd2de26f5c8b14b4bca5e5e62bea1df
Log Build with WinRM: https://gist.github.com/Thumpermat/78ef2e8b802e1c349e393c2c204a9143

I want to build a Windows 2012 R2 vagrant box with packer, using Chef-Solo as provisioner.

When I use SSH as communicator, it works without an itch. When I use Winrm, it hangs after trying to upload the Chef cookbooks.

I have created a repository, where you can find the json files, the scripts, the logs, etc. . You can find it here:

https://gitlab.ratti.io/Thumpermat/win12-packer-chef

Thank you very much in advance for your help.

Sincerely,
Mathias Woringer

**Comment by Thumpermat** [comment] 2018-01-04 10:50
Bump.

Is there anything you would like me to do?

**Comment by SwampDragons** [comment] 2018-01-04 19:18
Hey @Thumpermat, thanks for reporting and sorry for the delayed response; you managed to file this issue right as Hashicorp closed for a company-wide break.  I think this is a duplicate of https://github.com/hashicorp/packer/issues/5220, so I am going to close it here and continue to track the issue there.

**Comment by SwampDragons** [comment] 2018-01-04 19:20
oh, oops -- not the same issue, since that one's to do with a chef install.

**Comment by SwampDragons** [comment] 2018-01-04 19:26
hmmm maybe it's to do with this!  https://github.com/hashicorp/packer/issues/5752 . I'll have to do that vendor update and see if it fixes this too.

**Comment by SwampDragons** [comment] 2018-01-04 21:06
Hey -- I'm gonna try to get a repro case set up when I get the chance, but if you have time and the inclination you can probably cut down on the amount of time it takes to resolve this if you can help me out testing.  I have a suspicion that a change to a third party library that I just integrated onto our master branch might fix this.  You can either download a freshly-built binary attached to this comment, or you can build packer yourself from master. [packer.zip](https://github.com/hashicorp/packer/files/1604709/packer.zip)

**Comment by Thumpermat** [comment] 2018-01-05 09:46
Unfortunately, the zip file contains an .exe and I am on MacOS.

Will try to build it from master, but I'm not an expert.

**Comment by Thumpermat** [comment] 2018-01-05 11:12
It still doesn't work, but now it is not with Chef-Solo, but with shell scripts afterwards.

A script should have started, but after 10 minutes I interrupted the process as nothing was happening.

You can find the log here:

https://gist.github.com/Thumpermat/4e07b6fd4f8bdc54ec251620511666a1

There is another issue with Chef-Solo when a recipe is empty (works with SSH but not with WinRM) and I'm going to open a new issue for that.

One point I would like to mention is that the uploading of files from packer to the guest with WinRM is very slow. For instance the upload of VBoxGuestAdditions.iso took 3min 56s with WinRM and only 4s with SSH.

**Comment by Thumpermat** [comment] 2018-01-05 16:28
Let me check the issue with the scripts again, it might be my mistake here.

**Comment by SwampDragons** [comment] 2018-01-05 22:27
oh, sorry -- somehow I thought you were on windows. I can build you an osx executable if that will help you out.  

Let me know whether this was user error or you're confident the issue is replicable.

**Comment by SwampDragons** [comment] 2018-01-05 22:29
BTW the WinRM slowness is definitely a known problem. See https://github.com/hashicorp/packer/issues/4806#issuecomment-295373294 for a bit of context.

**Comment by SwampDragons** [comment] 2018-01-05 22:37
Here's a darwin build of the master branch of packer: 
[packer.zip](https://github.com/hashicorp/packer/files/1608114/packer.zip)

**Comment by Thumpermat** [comment] 2018-01-05 23:09
Forget the shell scrips. That was me using the type "shelll" instead of "windows-shell"

Now it works fine. 

I opened another issue with having an empty recipe in Chef-Solo, but otherwise we're good. 

I have a question for you which doesn't belong here. You can contact me at thumpermat at g mail dot com

**Comment by SwampDragons** [comment] 2018-01-05 23:35
I'm glad the shell scripts aren't a problem. I'm going to mark this ticket resolved. If you have a packer question that isn't specific to an issue, the mailing list is the best place for it -- https://groups.google.com/forum/#!forum/packer-tool

**Closed by SwampDragons** 2018-01-05 23:35 UTC
Labels: communicator/winrm, provisioner/chef, windows-guest
