### ISSUE TITLE
Hyper-v Ubuntu 16.04.2 Issue with SSH

### ISSUE THREAD

**Issue by MariuszHxGNMIN** [hashicorp/packer#4706] opened 2017-03-24 13:08 UTC
Describe the problem and include the following information:
packer 0.12.3
Windows 10 + Hyper-V

https://gist.github.com/MariuszHxGNMIN/7a265aa773cc10a8652b6425832f09d2

With Ubuntu 16.04.2 ther is a problem after restart to get SSH connection on Hyper-V with message `packer.exe: YYYY/MM/DD HH:Min:SS [DEBUG] Error getting SSH address: No ip address.`

**Comment by evancox10** [comment] 2017-03-24 18:32
Hyper-V uses the KVP (Key-Value Pair) daemon to exchange information with the guest OS, including the guest IP address Double check that you're installing this properly as part of the initial OS install. For Ubuntu 16.04 follow the instructions here:
https://technet.microsoft.com/en-us/windows-server-docs/compute/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v

> `apt-get install linux-tools-virtual-lts-xenial linux-cloud-tools-virtual-lts-xenial`

This would need to be part of the initial install process, so the preseed file needs to do this. See an example here:
https://github.com/taliesins/packer-baseboxes/blob/master/linux/ubuntu/http/preseed.cfg

> `d-i pkgsel/include string openssh-server ntp linux-tools-$(uname -r) linux-cloud-tools-$(uname -r) linux-cloud-tools-common`

Could also do this in a postinstall script, since with this method you are limited to what is included on the install DVD (I think). The packages here are hard-coded to a specific kernel version, it's better to use the metapackages mentioned on Microsoft's best practices page instead. But this will get things going, and your provisioning scripts can remove the hard-coded packages and install the metapackages.

**Comment by MariuszHxGNMIN** [comment] 2017-03-25 07:06
Evan
The problem is that I have thoes packages included in preseed file.. and it worked with 16.04.1 iso but don't work with new 16.04.iso
Regards


Od: Evan Cox
Wysłano: piątek, 24 marca, 22:32
Temat: Re: [mitchellh/packer] Hyper-v Ubuntu 16.04.2 Issue with SSH (#4706)
Do: mitchellh/packer
DW: Koprowski, Mariusz, Author

Hyper-V uses the KVP (Key-Value Pair) daemon to exchange information with the guest OS, including the guest IP address Double check that you're installing this properly as part of the initial OS install. For Ubuntu 16.04 follow the instructions here:
https://technet.microsoft.com/en-us/windows-server-docs/compute/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v

apt-get install linux-tools-virtual-lts-xenial linux-cloud-tools-virtual-lts-xenial

This would need to be part of the initial install process, so the preseed file needs to do this. See an example here:
https://github.com/taliesins/packer-baseboxes/blob/master/linux/ubuntu/http/preseed.cfg

d-i pkgsel/include string openssh-server ntp linux-tools-$(uname -r) linux-cloud-tools-$(uname -r) linux-cloud-tools-common

Could also do this in a postinstall script, since with this method you are limited to what is included on the install DVD (I think). The packages here are hard-coded to a specific kernel version, it's better to use the metapackages mentioned on Microsoft's best practices page instead. But this will get things going, and your provisioning scripts can remove the hard-coded packages and install the metapackages.

**Comment by mwhooker** [comment] 2017-03-25 08:38
please post The _simplest example template and scripts_ needed to reproduce the bug.

**Comment by MariuszHxGNMIN** [comment] 2017-03-26 16:46
@mwhooker added to this Gist <script src="https://gist.github.com/MariuszHxGNMIN/85ed44867c5fd046853642fd635d8020.js"></script>

**Comment by MariuszHxGNMIN** [comment] 2017-03-26 21:13
The problem with something around a reboot of the VM. When I have reset the VM manually (full power off and power on) packer found ssh and start provisioning. But using standard Ubuntu restart don't do that... any thoughts around that ?

**Comment by spmiller** [comment] 2017-04-02 21:58
Hi @MariuszHxGNMIN,

We've found the KVP daemon doesn't play nicely with the kernel in 16.04.2. We actually have a service that restarts the kvp daemon repeatedly to prod it into working -- it can sometimes take 5 or 6 times to start.

[This issue](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1664663) in Launchpad seems to cover the problem, and we've commented on it there.

**Comment by kwilczynski** [comment] 2017-04-02 22:51
@MariuszHxGNMIN @spmiller have a look at this issue https://github.com/mitchellh/packer/issues/3487, perhapst here is something that that could help

**Comment by spmiller** [comment] 2017-04-25 22:40
Hi @kwilczynski, thanks for the pointer. I'm able to reproduce this outside of Packer -- ie plain Hyper-V and Ubuntu 16.04.2 -- so I'm pretty sure this isn't a Packer issue. 16.04.1 works fine.

**Comment by taliesins** [comment] 2017-07-01 06:23
I think this is an OS specific issue and is not related to Packer, so closing for now

**Closed by taliesins** 2017-07-01 06:23 UTC
Labels: builder/hyperv
