### ISSUE TITLE
oracle-oci builder not recognized after packer version 1.8.4-1

### ISSUE THREAD

**Issue by exolain** [hashicorp/packer#12170] opened 2022-12-19 21:35 UTC
Hi All,

On packer version 1.8.4-1 and 1.8.5-1 we are getting the error:
`error initializing builder 'oracle-oci': Unknown builder oracle-oci`

After removing the latest version and using the 1.8.3-1 it works again.

**Comment by nywilken** [comment] 2022-12-21 17:23
Hi @exolain thanks for reaching out. The Oracle OCI builder is no longer being bundled with Packer. It was removed in Packer 1.8.4 - [CHANGELOG](https://github.com/hashicorp/packer/blob/main/CHANGELOG.md#184-october-28-2022)

In order to use the external plugin you can install it using either `packer init` or the `packer plugins install` command. 

If you are using HCL templates the preferred method would be to use the `packer init` with the required_plugins block. 
Adding the following to the top of your HCL template file will be enough for Packer init to know what version of the builder to install. 

```hcl
packer {
    required_plugins {
      oracle = {
        source = "github.com/hashicorp/oracle"
        version = ">= 1.0.3"
      }
    }
}
```

If you are using JSON templates, which doesn't support the required plugins block, you can install using the plugins command. 

```shell
packer plugins install github.com/hashicorp/oracle
```

I'm going to close this issue since it is not a bug. But if you run into problems installing the external plugin please feel free to ping the thread and I will gladly reopen. Cheers!

**Closed by nywilken** 2022-12-21 17:23 UTC
