### ISSUE TITLE
Download issues from RHEL Packer repo

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#10131] opened 2020-10-20 16:46 UTC
User can't download Packer from RPM repos. Relevant bits copied from mailing list:

_________________
I've just been tasked with an installation that utilises Packer.

When I went to add the repos to our Satellite installation for distribution to our servers, I
noted that there aren't any RHEL repos that seem to be working atm?

EG:  https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable

This was taken from the hashicorp.repo file available here https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

As advertised here
https://learn.hashicorp.com/tutorials/packer/getting-started-install

> The team can't reproduce -- can you file a bug report with exact steps to reproduce?

Doesn't take much - go to the URL in my original email for instance. Screen shot attached.

I'm using up to date Firefox on Ubuntu 20.04.1

> But did you actually try to install via the directions given or just go to that url?

I just went to the URL because I'm not installing directly - I'll be recreating the repo in a Satellite instance for our local servers.

**Comment by kpenfound** [comment] 2020-10-20 17:54
The problem is that the repos don't support index listing yet, so there's no folder navigation via browser.  This is in our backlog but not implemented yet.

RHEL is supported, and a package can be downloaded directly by specifying a specific product/version following the above link, such as:
[https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable/packer-1.6.4-1.x86_64.rpm](https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable/packer-1.6.4-1.x86_64.rpm)

Package managers know how to navigate this standardized repository structure, so following the instructions on the linked tutorial will result in a successful installation.

To recreate the repo for local use, you can use `dnf reposync`, for example:
`dnf reposync --repoid=hashicorp -p ./`

**Comment by nywilken** [comment] 2021-02-19 01:58
@SwampDragons seeing as there are ways to grab the RPMs directly I feel safe closing this issue. But if you think otherwise please let me know and I'll gladly reopen.

**Closed** 2021-02-19 01:58 UTC
Labels: upstream-bug
