### ISSUE TITLE
Packer v0.12.2  file upload via "provisioners"

### ISSUE THREAD

**Issue by ssk199441** [hashicorp/packer#9165] opened 2020-05-05 06:07 UTC
Hi

We will create AWS create instance and move files into it and for last two months it working fine,now i am getting the following error

**"Upload failed: Process exited with status 1"
"errored: Process exited with status 1"**

**Comment by sylviamoss** [comment] 2020-05-05 09:31
Hey there, thanks for reaching out! In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration, scripts needed to reproduce the bug, and the Packer version you're using.

**Comment by ssk199441** [comment] 2020-05-05 10:47
{
  "variables": {
      Confidential
  },
  "builders": [{
	 Confidential
  }],
  "provisioners": [
  {
    "type": "file",
    "source": "../test",
    "destination": "/tmp/test"
  }
 ]
}

packer version - 0.12.2 and 1.5.6

Steps to reproduce
1. packer build with PACKER_LOG=1

**Comment by ssk199441** [comment] 2020-05-05 10:49
Errors in log

2020/05/05 09:56:11 packer-builder-amazon-ebs plugin: [DEBUG] Started SCP session, beginning transfers...
2020/05/05 09:56:11 packer-builder-amazon-ebs plugin: [DEBUG] scp: Uploading test: perms=C0777 size=538
2020/05/05 09:56:11 packer-builder-amazon-ebs plugin: [DEBUG] SCP session complete, closing stdin pipe.
2020/05/05 09:56:11 packer-builder-amazon-ebs plugin: [DEBUG] Waiting for SSH session to complete.
2020/05/05 09:56:11 packer-builder-amazon-ebs plugin: [DEBUG] non-zero exit status: 1
2020/05/05 09:56:11 packer-builder-amazon-ebs plugin: [DEBUG] scp output:
2020/05/05 09:56:11 packer-provisioner-file plugin: closing

**Comment by ssk199441** [comment] 2020-05-05 13:02
We cannot post the full source code it containing confidential data and against the company policies. so I provided the sample

**Comment by ssk199441** [comment] 2020-05-05 13:10
https://github.com/hashicorp/packer/issues/7878

Same like this issue , it worked till last week

**Comment by SwampDragons** [comment] 2020-05-05 16:05
If your code worked til last week, and you haven't updated Packer, then this is probably either an issue with your code or a change to AWS. You're using a version of Packer that is a few years old. I'd suggest upgrading your Packer to the latest version, and the problem may go away. Outside of that recommendation, this doesn't seem like a Packer issue to me since the same version of the tool worked for you before, I'm going to close this issue. 

If you think I'm wrong and this is a Packer issue, we can reopen but in order to investigate we really do need an actual repro case including a working template. Doesn't need to include confidential company information -- we want the simplest possible Packer template that still reproduces the issue. Thanks!

**Closed by SwampDragons** 2020-05-05 16:05 UTC
Labels: need-more-info, provisioner/file

**Comment by ssk199441** [comment] 2020-05-13 05:40
{
  
  "variables": {
    "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "us-east-1",
      "source_ami": "ami-fce3c696",
      "instance_type": "t2.micro",
      "ssh_username": "ubuntu",
      "ami_name": "packer_AWS {{timestamp}}"
    }
  ]

  "provisioners": [
  {
    "type": "file",
    "source": "../test",
    "destination": "/tmp/test"
  }
 ]
}

////////////////////////////////////////////////////////////////////////////////////////////////////
output log
2020/05/13 10:58:38 packer: 2020/05/13 10:58:38 [INFO] 530 bytes written for 'uploadData'
2020/05/13 10:58:38 packer: 2020/05/13 10:58:38 opening new ssh session
2020/05/13 10:58:38 [INFO] 530 bytes written for 'uploadData'
2020/05/13 10:58:38 packer: 2020/05/13 10:58:38 Starting remote scp process:  scp -vt /tmp
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 Started SCP session, beginning transfers...
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 [DEBUG] scp: Uploading artifactory.repo: perms=C0644 size=530
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 SCP session complete, closing stdin pipe.
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 Waiting for SSH session to complete.
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 non-zero exit status: 1
==>  Upload failed: Process exited with status 1
2020/05/13 10:58:39 ui error: Upload failed: Process exited with status 1

when we try to upload the file by provisioner still getting same problems with the packer version 1.5.6

**Comment by sylviamoss** [comment] 2020-05-13 09:08
@ssk199441 I tried the example template you gave and it worked fine here, it copied all the files inside the dir to the instance.

```
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: Running the provision hook
2020/05/13 10:56:50 [INFO] (telemetry) Starting provisioner file
==> amazon-ebs: Uploading ../ftest => /tmp/test
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] Upload dir '../ftest' to '/tmp/test'
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] Opening new ssh session
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] Starting remote scp process:  scp -rvt /tmp/test
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] Started SCP session, beginning transfers...
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] No trailing slash, creating the source directory name
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] SCP: starting directory upload: ftest
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] scp: Uploading file3: perms=C0644 size=0
2020/05/13 10:56:50 packer-builder-amazon-ebs plugin: [DEBUG] scp: Uploading file2: perms=C0644 size=0
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: [DEBUG] scp: Uploading file: perms=C0644 size=0
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: [DEBUG] SCP session complete, closing stdin pipe.
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: [DEBUG] Waiting for SSH session to complete.
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: [DEBUG] scp stderr (length 87): Sink: D0755 0 ftest
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: Sink: C0644 0 file3
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: Sink: C0644 0 file2
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: Sink: C0644 0 file
2020/05/13 10:56:51 packer-builder-amazon-ebs plugin: Sink: E
2020/05/13 10:56:51 [INFO] (telemetry) ending file
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating AMI packer_AWS 1589360159 from instance i-013bf126a11fb858c
    amazon-ebs: AMI: ami-032c54fb934fddfc7
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.
```
Are sure nothing has changed at the AWS configuration, permissions? Your logs don't log that the ssh is connected.
