### ISSUE TITLE
azure-arm builder hangs forever for long running provisioners

### ISSUE THREAD

**Issue by aminjam** [hashicorp/packer#4848] opened 2017-04-28 12:07 UTC
Azure builder hangs forever when running long running provisioners. Here is a sample `template.json` that tries to emulate long running tasks by sleep. We have noticed that the timeout happens sometime between 11-15 minutes. We use the same long running tasks for vmware_vmx, GCP, and AWS, but we don't see this behavior. It's worth noting that Azure is the only IaaS that uses WinRM with SSL. Has anyone seen this behavior? We would be happy to send a PR if someone in the community knows where the bug is coming from. 
 
```
{
  "builders": [
    {
      "type": "azure-arm",
      "client_id": "{{REPLACE_ME}}",
      "client_secret": "{{REPLACE_ME}}",
      "tenant_id": "{{REPLACE_ME}}",
      "subscription_id": "{{REPLACE_ME}}",
      "object_id": "{{REPLACE_ME}}",
      "resource_group_name": "{{REPLACE_ME}}",
      "storage_account": "{{REPLACE_ME}}",
      "capture_container_name": "some-name",
      "capture_name_prefix": "some-name",
      "image_publisher": "MicrosoftWindowsServer",
      "image_offer": "WindowsServer",
      "image_sku": "2012-R2-Datacenter",
      "location": "East US",
      "vm_size": "Standard_DS2_v2",
      "os_type": "Windows",
      "communicator": "winrm",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "winrm_timeout": "1h",
      "winrm_username": "packer"
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 11 minutes'",
        "Start-Sleep -s (60*11)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 12 minutes'",
        "Start-Sleep -s (60*12)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 13 minutes'",
        "Start-Sleep -s (60*13)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 14 minutes'",
        "Start-Sleep -s (60*14)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 15 minutes'",
        "Start-Sleep -s (60*15)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 16 minutes'",
        "Start-Sleep -s (60*16)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Sleeping for 31 minutes'",
        "Start-Sleep -s (60*31)",
        "Write-Host 'Finished Sleeping'"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Next provisioner'"
      ]
    }
  ]
}
```

**Comment by boumenot** [comment] 2017-04-28 16:01
Thank you for logging an issue, and including a detailed repro!  I don't know what the issue is, so I will try to reproduce it.  My initial WAG is Windows WinRM timeout is too short, but that's just a guess.

/cc @paulmey

**Comment by aminjam** [comment] 2017-05-10 20:27
@boumenot @paulmey Were you able to reproduce this bug? We've increased the timeout but still seeing the same issue. Are there other potential causes we should be looking for?

**Comment by boumenot** [comment] 2017-05-11 04:58
Sorry, but I have not had a chance to work on this issue, and I do not have an ETA to share at this time.

**Comment by sandersaares** [comment] 2017-05-29 06:01
I am hitting the same issue - WinRM connections just hang for long-running provisioners.

Hypothesis: the Azure network infrastructure imposes time limits on idle connections (by default 4 minutes). If there is no WinRM traffic in this duration (e.g. no stdout/stderr is printed) then the connection is silently dropped. The WinRM client still thinks it is waiting for output but none will ever come.

It is possible to increase the idle timeout to 30 minutes but even better would be to ensure that the WinRM connection does not go idle (do not poll for more than 30 seconds with each connection?).

**Comment by sandersaares** [comment] 2017-05-29 07:43
Experiment results:

Idle timeout 4 minutes; sleep 4 minutes success, sleep 5 minutes fail.
Idle timeout 10 minutes: sleep 9 minutes success, sleep 11 minutes fail.

Hypothesis confirmed. I will try to work around it by having my scripts just spam pointless "Still doing stuff, please wait" messages to keep the connection alive but this should really be addressed in Packer somehow, as it seems a fairly critical piece of functionality where such arbitrary timeouts are not a happy thing.

**Comment by sandersaares** [comment] 2017-05-29 08:40
My workaround:

```powershell
[CmdletBinding()]
param(
    # Path to the script to execute.
    [Parameter(Mandatory = $true)]
    [string]$scriptPath,

    # Timeout in seconds.
    [Parameter(Mandatory = $false)]
    [int]$timeout = 0
)

$ErrorActionPreference = "Stop"

if (!(Test-Path -PathType Leaf $scriptPath)) {
    Write-Error "Target script not found."
    return
}

$job = Start-Job -FilePath $scriptPath
$stopwatch = [Diagnostics.Stopwatch]::StartNew()

while ($true) {
    $job | Receive-Job

    if (($job | Wait-Job -Timeout 60) -eq $null) {
        # Job is still running - print some placeholder text to avoid idle timeout.
        Write-Host "Waiting for script to finish."
    }
    else {
        # Job has finished. It may still have some unwritten output, so drain it.
        $job | Receive-Job
		Write-Host "Script execution completed successfully."
        return
    }

    if ($timeout -ne 0 -and $stopwatch.Elapsed.TotalSeconds -ge $timeout) {
        Remove-Job $job -Force
        Write-Error "Script timeout exceeded."
    }
}
```

Used as follows:

```
"provisioners": [
        {
            "type": "file",
            "sources": [
                "Sleep5.ps1",
                "Sleep50.ps1",
                "Wrap-RemoteScript.ps1"
            ],
            "destination": "C:/"
        },
        {
            "type": "powershell",
            "inline": [
                "$ErrorActionPreference = 'Stop'",
                "& C:/Wrap-RemoteScript.ps1 -ScriptPath C:/Sleep5.ps1"
            ]
        },
        {
            "type": "powershell",
            "inline": [
                "$ErrorActionPreference = 'Stop'",
                "& C:/Wrap-RemoteScript.ps1 -ScriptPath C:/Sleep50.ps1"
            ]
        }
    ]
```

**Comment by mwhooker** [comment] 2017-05-30 17:57
@sandersaares I'm thinking setting a `KeepAlive` in the winrm transport might fix this. Would you be willing to test a patch for me? I could send you the branch and have you compile, or if you tell me your OS, I can upload a binary

**Comment by boumenot** [comment] 2017-05-31 00:16
@mwhooker - send me the patch, and I will test it. The community has graciously provided a repro, so it should be easy to verify the fix.

**Comment by mwhooker** [comment] 2017-05-31 01:44
@boumenot thanks! Here's my patch https://github.com/hashicorp/packer/compare/fix4848

Since this is an upstream change, you'll have to build without using the makefile. On osx I build with `XC_ARCH=amd64 XC_OS=darwin ./scripts/build.sh`, but I can't say for certain what the build command would look like on windows. I think `XC_ARCH=amd64 XC_OS=darwin ./scripts/build.ps1` should work

**Comment by sandersaares** [comment] 2017-05-31 05:07
I can test the patch if you can provide a Windows binary - I am not sufficiently familiar with Packer to know how to build it, I fear.

**Comment by mwhooker** [comment] 2017-05-31 07:07
@sandersaares here's windows binary for amd64
[packer_windows_amd64.zip](https://github.com/hashicorp/packer/files/1040513/packer_windows_amd64.zip)

**Comment by sandersaares** [comment] 2017-05-31 12:36
I confirm that with this build the issue no longer occurs.

**Comment by boumenot** [comment] 2017-05-31 19:38
Ditto.  It failed with v1.0.0, but applying this patch to master allowed it to run until completion.

**Closed** 2017-06-01 22:18 UTC
Labels: builder/azure, communicator/winrm

**Comment by davidobrien1985** [comment] 2018-11-20 10:32
Hi, @boumenot has this issue been re-introduced in packer 1.3.2?
I am experiencing the exact same behaviour (was just about to create a new issue) with this packer version with the `azure-arm` builder and a long running task on the Windows Server 2016 Azure VM (instaling Visual Studio).

Any tips?

Thanks!

**Comment by boumenot** [comment] 2018-11-20 18:57
I don't know.  If you think you have a new issue, I would open it up with the details.

I don't have any tips other than the one in this thread.  The OP fixed the issue by sending messages to STDOUT. Does that help in this case?
