### ISSUE TITLE
Unable to bake an Azure W2K19/16/12 image with Packer 1.4.2

### ISSUE THREAD

**Issue by antgoodes** [hashicorp/packer#7850] opened 2019-07-08 03:40 UTC
Packer Version 1.4.2 attempting to bake an Azure W2K12/16/19 image, however am unable to due to 

'Packer crashed! This is always indicative of a bug within Packer. '

No problems experienced when using Packer V 1.4.1 for these same builds. Attached are the logs and the JSON for the build. 

[plan-41615490-PAC-3.log](https://github.com/hashicorp/packer/files/3366574/plan-41615490-PAC-3.log)

[windows-2019-base-json.docx](https://github.com/hashicorp/packer/files/3366589/windows-2019-base-json.docx)

**Comment by SwampDragons** [comment] 2019-07-08 17:08
I think this is probably a duplicate of #7816, fixed in #7837. Binaries of the patch can be found here: https://circleci.com/gh/hashicorp/packer/6821#artifacts/containers/0

**Closed by SwampDragons** 2019-07-08 17:08 UTC
Labels: builder/azure, duplicate, regression
