### ISSUE TITLE
amazon: Custom kms key is not applied in other regions

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#4249] opened 2016-12-04 20:54 UTC
The implementation #4023 is a bit naïve and don't correctly handle multiple regions. ~I'll try to fix it tomorrow.~ This seems to take me a bit longer.

@mwhooker ~If you are doing a release please revert  #4023 first unless I have a fix for this since it will require different options in the template.~ See comment bellow.

**Comment by rickard-von-essen** [comment] 2016-12-06 09:15
I'll just updated the docs a bit. To point out that `kms_key_id` is only applied on `region` and the default kms key will be used on all `ami_regions`

**Comment by mwhooker** [comment] 2016-12-06 23:43
sounds good. I'll let you close this or keep it open if you think it's something we should support, but going to untarget it from 0.12.1 since it sounds like we have a workable solution

**Comment by rickard-von-essen** [comment] 2016-12-07 05:08
:+1:

**Comment by gupta-abhishek** [comment] 2016-12-22 06:58
Any update on when will this feature be deployed in master?

**Comment by rickard-von-essen** [comment] 2016-12-22 16:42
Most likely during the holidays.

**Comment by mwhooker** [comment] 2017-04-18 01:34
@rickard-von-essen I'm going to work on this for next release. Do you have any thoughts on where I should look next? After I read the docs I'm sure I'll see what's needed

**Comment by rickard-von-essen** [comment] 2017-04-18 07:46
I started but gut stuck because I couldn't decide on the UX, feel free to do a PR for it.

The implementation is rather straight forward, we have to add a new configuration option, say:
`region_kms_key_ids` which is a map of `region` -> `kms_id`.

The hard part is how to ensure that the user gets what he/she wants. Things we have to consider/decide:

1) What happens if a _region_ is specified in `ami_regions` but not in `region_kms_key_ids`, will it get the default key? Or is it an error?

2) Should additional regions in `region_kms_key_ids` (not in `ami_regions`) be silently ignored, warned, or result in an error.

3) How should `snapshot_users` be handled in conjunction with 1)? Encrypted snapshots can be shared with other accounts _if and only if_ they are encrypted with a custom (i.e. non default) KMS key. If `snapshot_users` is defined and a `region_kms_key_ids` mapping does not exist for a region should the snapshot in that region just not be applied or should it result in an error?

Hope this gives you a quick start.

**Comment by SwampDragons** [comment] 2017-05-24 23:55
My instinct is that requiring a 1:1 mapping of regions to keys would be the cleanest.  It would have the least unexpected behavior and seems like it would be the easiest to document.  It would also provide a consistent answer to all of your edge case questions:
1) If a region is specified in `ami_regions` but not in `region_kms_key_ids`, throw an error. If the user wants to use the default key then they should specify that in `region_kms_key_ids` 
2) Additional regions in `region_kms_key_ids` should result in a validation error.
3) if snapshot_users is defined and a `region_kms_key_ids` mapping does not exist, this should result in a validation error.

I can see another edge case arising from 1) and 3), though.  What happens if someone uses the default key in the `region_kms_key_ids` mapping?  I don't suppose that Packer can tell whether a key is custom or default?

**Closed** 2017-06-01 20:30 UTC
Labels: bug, builder/amazon
