### ISSUE TITLE
Amazon EBS + Ansible Regression in 1.0.3

### ISSUE THREAD

**Issue by SomeoneWeird** [hashicorp/packer#5169] opened 2017-07-25 14:33 UTC
There is a regression in 1.0.3 from 1.0.2.

Debug log: https://gist.githubusercontent.com/SomeoneWeird/0d7946bf36ffb315b5cfd6ae6bad00ad/raw/d5224814008fd697721264f3dbb54e5783933ea3/gistfile1.txt

Host platform: OSX 10.12.6

Repro repo: https://github.com/SomeoneWeird/packer-ansible-1.0.3-repro

**Comment by rickard-von-essen** [comment] 2017-07-25 16:06
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Closed by rickard-von-essen** 2017-07-25 16:06 UTC

**Comment by SomeoneWeird** [comment] 2017-07-26 01:05
Ah - failed at searching, thanks!
