### ISSUE TITLE
packer winrm fails

### ISSUE THREAD

**Issue by riponbanik** [hashicorp/packer#5629] opened 2017-11-23 00:09 UTC
Packer WinRM on http fails with error http response error: 403 - invalid content type, with https it shows
connection error: unknown error Post https://xxxx:5986/wsman: Forbidden

- Packer version from `packer version` - 1.1.1
- Host platform - Linux
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/riponbanik/a2897334eb4b83c01c4090518cd75975

- The _simplest example template and scripts_ needed to reproduce the bug.
```
{
  "builders": [{
    "type": "amazon-ebs",
    "region": "ap-southeast-2",
    "source_ami": "ami-2013f142",
    "instance_type": "t2.small",
    "ami_name": "windows-ami {{timestamp}} ",
    "user_data_file":"non-prod/window-iis/script/ec2-userdata.ps1",
    "communicator": "winrm",
    "winrm_username": "Administrator",   
    "winrm_timeout": "30m",   
    "security_group_ids": ["sg-xxx"],    
    "subnet_id": "subnet-xxxx",
    "ssh_private_ip": "true",
    "ssh_keypair_name": "xxxx",
    "ssh_private_key_file": "xxxx"
  }]
}
```

**Comment by riponbanik** [comment] 2017-11-27 02:45
Issue is not fixed on 1.1.2

**Comment by SwampDragons** [comment] 2017-11-27 18:26
Normally I see this kind of issue when the user data file isn't doing everything it needs to.  Can you provide me with that script so I can see what your build is actually trying to do on the vm?

**Comment by riponbanik** [comment] 2017-11-28 02:59
@SwampDragons There is no issue with user data. The same thing works with packer version 0.9.0. I have also verified using Ansible to remote into the machine.

However I have added it below for your reference -

https://gist.github.com/riponbanik/319f8b1ffa760bd723723874fa6d43bc

**Comment by soner89** [comment] 2017-11-29 15:54
I'm having the same issue with Packer 1.1.2

Packer just doesn't seem to get a winrm connection to the Windows 2012 R2 builder instance on AWS. 

Another issue is, that I can't get a winrm-connection with the Packer-generated Security Groups either.
I know, you shouldn't do this but for debugging purposes I opened up All traffic to 0.0.0.0/0 and could connect to winrm on the ec2-instance from my local computer. Packer still couldn't get a working connection.

I would love to see a working example with Packer successfully building a Windows instance on AWS.

**Comment by SwampDragons** [comment] 2017-11-29 17:25
@soner89 here's a working example of a windows 2012R2 build that successfully runs, using the same image that @riponbanik is trying to get working: https://gist.github.com/SwampDragons/a9f32e3852e08a6fa113fa927b53f1de

Still looking into this.  I have no definitive answer as to why @riponbanik is not able to get their build working, but I think it may have to do with setting ssh_private_ip, since adding that line to  my working packer config causes things to break.  I haven't played much with the networking options here though so I need to make sure I'm using the feature correctly before coming to any conclusions.

**Comment by SwampDragons** [comment] 2017-11-29 19:16
@riponbanik Can you please try to boot the vm using the user-data provided in the above gist?  I can't seem to get your user-data script to work. Just for my sanity's sake.  Thanks.

**Comment by SwampDragons** [comment] 2017-11-29 19:22
Hmm I think this might actually be a dupe of https://github.com/hashicorp/packer/issues/4857

**Comment by riponbanik** [comment] 2017-12-01 06:06
@SwampDragons I use EC2 with user data  inside <powershell> </powershell> and do not have any issue with booting the vm.

**Comment by riponbanik** [comment] 2017-12-04 01:02
@SwampDragons it is reaming on "Waiting for WinRM to become available..." without any further progress - tested version 1.1.2

I have tested with Test-WSMan and telnet to make sure I can winrm is configured correctly and it gives the result back

Test-Wsman  _ip_address_

smid           : http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd
rotocolVersion : http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
roductVendor   : Microsoft Corporation
roductVersion  : OS: 0.0.0 SP: 0.0 Stack: 3.0

amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: default-packer1512348758
    amazon-ebs: Found Image ID: ami-2013f142
==> amazon-ebs: Creating temporary keypair: packer_5a249c56-cf8a-aaf9-6680-e85c36a96e90
==> amazon-ebs: Creating temporary security group for this instance: packer_5a249c57-f21d-3c8d-c7bf-1e56d4e7d591
==> amazon-ebs: Authorizing access to port 5985 from 0.0.0.0/0 in the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-xxxx
==> amazon-ebs: Waiting for instance (i-xxxxx) to become ready...
==> amazon-ebs: Skipping waiting for password since WinRM password set...
==> amazon-ebs: Waiting for WinRM to become available...

**Comment by SNikalaichyk** [comment] 2017-12-06 21:23
Try to use Ansible's WinRM configuration script in your user data:
```
<powershell>

$ScriptUrl  = 'https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'
$TempPath   = [Environment]::GetEnvironmentVariable('TEMP', [EnvironmentVariableTarget]::Machine)
$ScriptPath = Join-Path -Path $TempPath -ChildPath (Split-Path -Path $ScriptUrl -Leaf)

Invoke-WebRequest -Uri $ScriptUrl -OutFile $ScriptPath -UseBasicParsing

& $ScriptPath -ForceNewSSLCert -SkipNetworkProfileCheck

</powershell>
```

**Comment by tjnicholas** [comment] 2017-12-08 00:11
@riponbanik If you are running behind a proxy @SwampDragons is probably right that this is a duplicate of #4857. If so #5630 has now been merged so in the next release you will be able to set `"ssh_interface": "private_dns"` to make winRM work. 

Note that you'll also have to ensure `<region>.compute.internal` is in your `no_proxy` list. 

On the other hand if you aren't behind a proxy, that isn't an issue and you can ignore this message :)

**Comment by riponbanik** [comment] 2017-12-11 22:50
@tjnicholas Thanks, the question is when the instance is launched in vpc where aws provided dns is not used instead own dns is configured, how the name will be resolved? It is better to allow private_ip along with name.

**Comment by SwampDragons** [comment] 2017-12-16 00:11
@riponbanik I'm not sure I totally follow this.  It sounds like you found a workaround (yay!) but I'm not 100% clear on what your solution was or what you want the packer project to do to automate it.

**Comment by mwhooker** [comment] 2017-12-18 23:48
Sounds like this is working now. If you've got some concrete ways for us to improve packer, please open a new issue. We'd love to hear your idea, but need some clarification

**Closed by mwhooker** 2017-12-18 23:48 UTC
Labels: builder/amazon, windows-guest

**Comment by riponbanik** [comment] 2017-12-20 22:16
@mwhooker and @SwampDragons - it is not working. This is not a solution. Packer is meant to be automation - it is not supposed to be working from AWS only where AWS provided dns is being set, needs to work with ip as well. As a user I am loosing trust with tool which I am using for long - new version should not break basic functionality.

**Comment by mwhooker** [comment] 2017-12-20 23:05
@riponbanik to reiterate what I've said in the other ticket, I'm sorry you're having problems but we don't understand what your issue is. We closed this because from your responses we assumed it had been fixed, but maybe we misunderstood. This issue was also opened before #5630 was merged.

To get the help you need, please open a new ticket with clear information about how to reproduce the issue, what you've tried, and how you'd like to see it resolved (if you know how).

We can't do much until we understand what the problem is.

**Comment by mwhooker** [comment] 2017-12-21 00:06
going to track in #5725. Let me know if that's not the same issue
