### ISSUE TITLE
Packer tells you to inspect folder but immediately deletes it

### ISSUE THREAD

**Issue by goldstar611** [hashicorp/packer#8647] opened 2020-01-23 20:03 UTC
#### Overview of the Issue

Packer tells you to inspect the folder containing the VMX file then immediately proceeds to delete the folder containing the VMX file.

Shouldn't packer abort clean up in this case or at least ask the user if they'd like to preserve the intermediate artifacts?

#### Reproduction Steps

1. Do weird stuff until packer gives you this message (I actually can't get this particular message to reappear at this moment in time)

### Packer version

1.5.1 linux amd64

### Simplified Packer Buildfile

Not relevant

### Operating system and Environment details

Ubuntu 18.04.3 LTS 64 bit
Packer 1.5.1 linux amd64
VMWare Workstation Pro 15.5.1

### Log Fragments and crash.log files

https://github.com/hashicorp/packer/blob/8567be43d952d4cbe2bc0ec3f3a20ec10b910d02/builder/vmware/common/driver.go#L186
```
Packer detected a VMware 'Unknown Error'. 
Unfortunately VMware often has extremely vague error messages such as this and Packer itself can't do much about that. 
Please check the vmware.log files created by VMware 
when a VM is started (in the directory of the vmx file), which often contains more detailed error information.
```

**Comment by SwampDragons** [comment] 2020-01-23 21:15
Hi, thanks for reaching out. Because Packer often runs in a CI system, we try not to drop into an interactive "ask" mode unless explicitly told to do so ahead of time. You can add the command line flag `--on-error=ask` to your build call to get Packer to ask you whether to clean up vs abort the build. If you want to always abort, you can set `--on-error=abort`. 

You're right that it is a little weird to have this error message when you haven't also set "on-error" flags.  What would you think about adding a note about the on-error flags into this message?

**Comment by goldstar611** [comment] 2020-01-24 13:28
> Because Packer often runs in a CI system, we try not to drop into an interactive "ask" mode

This is exactly my use case. You are correct, asking isn't the best first choice here

> What would you think about adding a note about the on-error flags into this message?

I think that would be great, I honestly didn't think about setting the `on-error` parameter.

**Comment by goldstar611** [comment] 2020-01-27 15:07
Hello, I'd like to  reopen this because adding `-on-error=abort` did not prevent clean up.

Here's the command I'm using
```
PACKER_LOG=1 ./packer build -on-error=abort my_packer_file.json | tee packer.log
```
The output-vmware-iso folder has been removed but the packer_cache folder (which is not helpful) remains

**Comment by goldstar611** [comment] 2020-01-27 15:17
The built-in documentation (`./packer build --help`) suggests that only a single dash is necessary but looking at https://github.com/hashicorp/packer/pull/8649 it seems that double dashes were added into that message.

`-on-error`
vs
`--on-error`

**Comment by SwampDragons** [comment] 2020-01-27 18:36
do double versus single dashes make a difference for you?

**Comment by goldstar611** [comment] 2020-01-27 20:39
> do double versus single dashes make a difference for you?

No.

However I have noticed that if a **provisioner** (bash, windows-shell, windows-restart, etc) fails, the intermediate files are preserved.
But in my case, a **post-processor** is failing (vsphere) and the intermediate files are being removed. 

This is really annoying because running `ovftool` requires an hour or so of "hand holding" (aka passing the `-debug` flag and pushing enter just before the post-processor runs). :(

**Comment by SwampDragons** [comment] 2020-01-27 21:36
Hmm. I'll have to take a look at how that's architected but in the meantime you may find that setting "keep_input_artifact" prevents the cleanup.

**Comment by goldstar611** [comment] 2020-02-20 20:38
I forgot to circle back around but `keep_input_artifact` did not prevent clean up either.

**Comment by SwampDragons** [comment] 2020-02-20 23:57
Thanks for checking back in with me. Can you gather a Packer template and logs from a build run with the env var PACKER_LOG=1? Without those, pinpointing this issue is going to be a lot harder.

**Comment by goldstar611** [comment] 2020-02-21 00:13
The issue I was having (not described in this GitHub issue) has been resolved -- everything is working great now, yay! To directly answer your question, this message about inspecting VMware files that are removed only happened 2 or 3 times.

**Comment by SwampDragons** [comment] 2020-02-21 19:34
okay, then I'm going to close this issue since I'm having trouble reproducing. If you mange to make it happen again and get logs, I'll try to investigate further.

**Closed by SwampDragons** 2020-02-21 19:34 UTC
Labels: bug
