### ISSUE TITLE
Packer 1.1.2 with virtualbox-ovf cannot file virtualbox guest additions all of a sudden on Windows

### ISSUE THREAD

**Issue by breisig** [hashicorp/packer#5597] opened 2017-11-17 16:11 UTC
I just upgraded to packer 1.1.2 and when building new images with the virtualbox-ovf builder (for Virtualbox 5.1.30) under Windows 10, it seems to fail to find the VBoxGuestAdditions.iso file even thought it exists. If I go back to packer 1.1.1, it works without issue.

packer 1.1.2 output
--------------
==> virtualbox-ovf: Downloading or copying Guest additions
    virtualbox-ovf: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-ovf: Error downloading: CreateFile Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system cannot find the path specified.
==> virtualbox-ovf: Guest additions download failed.
==> virtualbox-ovf: Deleting output directory...
Build 'virtualbox-ovf' errored: Guest additions download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-ovf: Guest additions download failed.

packer 1.1.1 output (works)
---------------------------------
==> virtualbox-ovf: Downloading or copying Guest additions
    virtualbox-ovf: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: Downloading or copying OVF/OVA

It looks like the only difference is with packer 1.1.1, the file copying starts with 3 slashes "file:///C" versus packer 1.1.2 only has 2 slashes "file://C" which most likely makes the difference why it's not working on windows.

**Comment by SwampDragons** [comment] 2017-11-17 16:22
Thanks for reporting!  This seems to be a duplicate of https://github.com/hashicorp/packer/issues/5589 and it's been fixed on master; if you want to use the dev binary provided on the other ticket, you can, or else you can downgrade until we can release the next version.  Apologies for the regression.

**Closed** 2017-11-17 16:22 UTC
Labels: duplicate, regression, windows-host
