### ISSUE TITLE
".SSHHostPort" is not populated in shell-local provisioner

### ISSUE THREAD

**Issue by ruzickap** [hashicorp/packer#6264] opened 2018-05-11 11:22 UTC
I'm would like to use Ansible + WinRM + Qemu + shell-local provisioner to build Windows.

Here is the snippet from my packer template:

```
{
  "builders":
  [
    {
...
      "qemuargs": [
        [ "-display", "gtk" ],
        [ "-m", "4G" ],
        [ "-smp", "2" ],
        [ "-netdev", "user,hostfwd=tcp::{{ .SSHHostPort }}-:5986,id=forward,ipv4" ],
        [ "-device", "e1000,netdev=forward,id=net0"]
      ],
...
    }
  ],
  "provisioners": [
    {
      "type": "shell-local",
      "command": "ansible-playbook -vv --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port={{ .SSHHostPort }}' -i 127.0.0.1, win.yml"
    }
  ],
...
}
```

I'm trying to use the `{{ .SSHHostPort }}` inside the `shell-local` provisioner, but it's not working like expected. Here is the log, where you can see the .SSHHostPort is only used in `qemuargs` section and not in `shell-local`:

```
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Looking for available communicator (SSH, WinRM, etc) port between 2222 and 4444
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Trying port: 2640
2018/05/11 10:11:29 ui: ==> windows-enterprise-eval: Found port for communicator (SSH, WinRM, etc): 2640.
==> windows-enterprise-eval: Found port for communicator (SSH, WinRM, etc): 2640.
==> windows-enterprise-eval: Looking for available port between 5900 and 6000 on 127.0.0.1
2018/05/11 10:11:29 ui: ==> windows-enterprise-eval: Looking for available port between 5900 and 6000 on 127.0.0.1
==> windows-enterprise-eval: Starting VM, booting from CD-ROM
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Looking for available port between 5900 and 6000 on 127.0.0.1
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Trying port: 5923
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Found available VNC port: 5923 on IP: 127.0.0.1
2018/05/11 10:11:29 ui: ==> windows-enterprise-eval: Starting VM, booting from CD-ROM
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Qemu --version output: QEMU emulator version 2.10.1(qemu-2.10.1-3.fc27)
2018/05/11 10:11:29 packer: Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Qemu version: 2.10.1
2018/05/11 10:11:29 ui: ==> windows-enterprise-eval: Overriding defaults Qemu arguments with QemuArgs...
==> windows-enterprise-eval: Overriding defaults Qemu arguments with QemuArgs...
2018/05/11 10:11:29 packer: 2018/05/11 10:11:29 Executing /usr/bin/qemu-system-x86_64: []string{"-m", "4G", "-device", "e1000,netdev=forward,id=net0", "-drive", "file=output-windows-enterprise-eval/packer-windows-enterprise-eval,if=ide,cache=writeback,discard=ignore,format=qcow2", "-machine", "type=pc,accel=kvm", "-fda", "/var/tmp/packer374234636", "-name", "packer-windows-enterprise-eval", "-cdrom", "/home/pruzicka/data/github/packer_shell-local_ansible_winrm/test/packer_cache/49f719e23c56a779a991c4b4ad1680b8363918cd0bfd9ac6b52697d78a309855.iso", "-display", "gtk", "-smp", "2", "-netdev", "user,hostfwd=tcp::2640-:5986,id=forward,ipv4", "-boot", "once=d", "-vnc", "127.0.0.1:23"}
.
.
.
==> windows-enterprise-eval: Connected to WinRM!
2018/05/11 10:22:37 packer: 2018/05/11 10:22:37 Connected to machine
2018/05/11 10:22:37 ui: ==> windows-enterprise-eval: Connected to WinRM!
2018/05/11 10:22:37 packer: 2018/05/11 10:22:37 Running the provision hook
2018/05/11 10:22:37 [INFO] (telemetry) Starting provisioner shell-local
==> windows-enterprise-eval: Executing local command: ansible-playbook -vv --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port=<no value>' -i 127.0.0.1, win.yml
2018/05/11 10:22:37 ui: ==> windows-enterprise-eval: Executing local command: ansible-playbook -vv --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port=<no value>' -i 127.0.0.1, win.yml
.
.
.
2018/05/11 10:22:40 ui:     windows-enterprise-eval: fatal: [127.0.0.1]: FAILED! => {"msg": "the field 'port' has an invalid value (<no), and could not be converted to an int.The error was: invalid literal for int() with base 10: '<no'"}
```

As you can see the .SSHHostPort is not properly populated in in `shell-local`: `ansible_port={{ .SSHHostPort }}  --->  ansible_port=<no value>`
On the other hand it's working fine in case of `qemu` builder: `[ "-netdev", "user,hostfwd=tcp::{{ .SSHHostPort }}-:5986,id=forward,ipv4" ]  --->  "-netdev", "user,hostfwd=tcp::2640-:5986,id=forward,ipv4"`

Full log is here: https://pastebin.com/9FND7W7N
Template can be found here: https://github.com/ruzickap/packer_shell-local_ansible_winrm/blob/master/windows-enterprise-eval.json

- Packer version from `packer version`: 1.2.3
- Host platform: Fedora 27
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://pastebin.com/9FND7W7N
- The _simplest example template and scripts_ needed to reproduce the bug.
See above + look at this repository: https://github.com/ruzickap/packer_shell-local_ansible_winrm

**Comment by rickard-von-essen** [comment] 2018-05-11 14:38
This works as intended. `.SSHPort` is only available in the builder.

**Comment by ruzickap** [comment] 2018-05-11 17:53
Thank you for the explanation...

Would it be possible to use `{{ .SSHHostPort }}` also in `shell-local` in the future (maybe feature request) ?

**Comment by SwampDragons** [comment] 2018-08-17 22:59
We recently merged a PR with this information, I think. This should be closed by #6503

**Comment by ruzickap** [comment] 2018-08-18 08:58
I believe `{{ .SSHHostPort }}` in `shell-local` still not working. But as @rickard-von-essen mentioned above - it works only inside builder.

* Template snippet:
```
"command": "ansible-playbook --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user=vagrant ansible_ssh_pass=vag
rant ansible_port={{ .SSHHostPort }}' -i 127.0.0.1, ansible/site.yml"
```

* Log:
```
2018/08/18 10:54:55 Loading builder: qemu
2018/08/18 10:54:55 Plugin could not be found. Checking same directory as executable.
2018/08/18 10:54:55 Current exe path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Creating plugin client for path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Starting plugin: /home/pruzicka/bin/packerio []string{"/home/pruzicka/bin/packerio", "plugin", "packer-builder-qemu"}
2018/08/18 10:54:55 Waiting for RPC address for: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [INFO] Packer version: 1.2.5
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer Target OS/Arch: linux amd64
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Built with Go Version: go1.10.3
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Attempting to open config file: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [WARN] Config file doesn't exist: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Setting cache directory: /home/pruzicka/data/github/packer-templates/packer_cache
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 args: []string{"packer-builder-qemu"}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin minimum port: 10000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin maximum port: 25000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin address: unix /tmp/packer-plugin368491485
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Waiting for connection...
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Serving a plugin connection...
2018/08/18 10:54:55 Loading provisioner: shell-local
2018/08/18 10:54:55 Plugin could not be found. Checking same directory as executable.
2018/08/18 10:54:55 Current exe path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Creating plugin client for path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Starting plugin: /home/pruzicka/bin/packerio []string{"/home/pruzicka/bin/packerio", "plugin", "packer-provisioner-shell-local"}
2018/08/18 10:54:55 Waiting for RPC address for: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [INFO] Packer version: 1.2.5
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer Target OS/Arch: linux amd64
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Built with Go Version: go1.10.3
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Attempting to open config file: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [WARN] Config file doesn't exist: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Setting cache directory: /home/pruzicka/data/github/packer-templates/packer_cache
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 args: []string{"packer-provisioner-shell-local"}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin minimum port: 10000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin maximum port: 25000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin address: unix /tmp/packer-plugin499159847
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Waiting for connection...
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Serving a plugin connection...
2018/08/18 10:54:55 Loading provisioner: windows-restart
2018/08/18 10:54:55 Plugin could not be found. Checking same directory as executable.
2018/08/18 10:54:55 Current exe path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Creating plugin client for path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Starting plugin: /home/pruzicka/bin/packerio []string{"/home/pruzicka/bin/packerio", "plugin", "packer-provisioner-windows-restart"}
2018/08/18 10:54:55 Waiting for RPC address for: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [INFO] Packer version: 1.2.5
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer Target OS/Arch: linux amd64
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Built with Go Version: go1.10.3
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Attempting to open config file: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [WARN] Config file doesn't exist: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Setting cache directory: /home/pruzicka/data/github/packer-templates/packer_cache
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 args: []string{"packer-provisioner-windows-restart"}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin minimum port: 10000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin maximum port: 25000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin address: unix /tmp/packer-plugin345481767
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Waiting for connection...
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Serving a plugin connection...
2018/08/18 10:54:55 Loading provisioner: windows-shell
2018/08/18 10:54:55 Plugin could not be found. Checking same directory as executable.
2018/08/18 10:54:55 Current exe path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Creating plugin client for path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Starting plugin: /home/pruzicka/bin/packerio []string{"/home/pruzicka/bin/packerio", "plugin", "packer-provisioner-windows-shell"}
2018/08/18 10:54:55 Waiting for RPC address for: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [INFO] Packer version: 1.2.5
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer Target OS/Arch: linux amd64
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Built with Go Version: go1.10.3
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Attempting to open config file: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [WARN] Config file doesn't exist: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Setting cache directory: /home/pruzicka/data/github/packer-templates/packer_cache
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 args: []string{"packer-provisioner-windows-shell"}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin minimum port: 10000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin maximum port: 25000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin address: unix /tmp/packer-plugin733088608
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Waiting for connection...
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Serving a plugin connection...
2018/08/18 10:54:55 Loading post-processor: vagrant
2018/08/18 10:54:55 Plugin could not be found. Checking same directory as executable.
2018/08/18 10:54:55 Current exe path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Creating plugin client for path: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 Starting plugin: /home/pruzicka/bin/packerio []string{"/home/pruzicka/bin/packerio", "plugin", "packer-post-processor-vagrant"}
2018/08/18 10:54:55 Waiting for RPC address for: /home/pruzicka/bin/packerio
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [INFO] Packer version: 1.2.5
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer Target OS/Arch: linux amd64
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Built with Go Version: go1.10.3
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Attempting to open config file: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 [WARN] Config file doesn't exist: /home/pruzicka/.packerconfig
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Setting cache directory: /home/pruzicka/data/github/packer-templates/packer_cache
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 args: []string{"packer-post-processor-vagrant"}
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Detected home directory from env var: /home/pruzicka
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin minimum port: 10000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin maximum port: 25000
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Plugin address: unix /tmp/packer-plugin940583172
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Waiting for connection...
2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 Serving a plugin connection...
2018/08/18 10:54:55 ui: qemu output will be in this color.
2018/08/18 10:54:55 ui:
2018/08/18 10:54:55 Build debug mode: false
2018/08/18 10:54:55 Force build: false
2018/08/18 10:54:55 On error:
2018/08/18 10:54:55 Preparing build: qemu
qemu output will be in this color.

2018/08/18 10:54:55 packerio: 2018/08/18 10:54:55 use detected accelerator: kvm
2018/08/18 10:54:55 ui error: Error decoding config: render 'command': template: root:1:192: executing "root" at <.SSHHostPort>: can't evaluate field SSHHostPort in type *shell_local.EnvVarsTemplate in:

ansible-playbook --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port={{ .SSHHostPort }}' -i 127.0.0.1, ansible/site.yml, config is &shell_local.Config{PackerConfig:common.PackerConfig{PackerBuildName:"", PackerBuilderType:"", PackerDebug:false, PackerForce:false, PackerOnError:"", PackerUserVars:map[string]string(nil)}, Command:"", Inline:[]string(nil), InlineShebang:"", TempfileExtension:"", Script:"", Scripts:[]string(nil), Vars:[]string(nil), EnvVarFormat:"", ExecuteCommand:[]string(nil), UseLinuxPathing:false, Ctx:interpolate.Context{Data:(*shell_local.EnvVarsTemplate)(0xc4201bcc60), Funcs:map[string]interface {}(nil), UserVariables:map[string]string{"windows_version":"10", "name":"my_windows-10-enterprise-x64-eval", "disk_size":"51200", "cpus":"2", "virtio_win_iso":"./packer_cache/virtio-win.iso", "winrm_username":"vagrant", "headless":"false", "winrm_password":"vagrant", "memory":"4096", "iso_checksum":"27e4feb9102f7f2b21ebdb364587902a70842fb550204019d1a14b120918e455", "vnc_vrdp_host_port":"5999", "iso_url":"https://software-download.microsoft.com/download/pr/17134.1.180410-1804.rs4_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso", "autounattend":"http/windows-10/Autounattend.xml"}, EnableEnv:false, BuildName:"qemu", BuildType:"qemu", TemplatePath:"/home/pruzicka/data/github/packer-templates/my_windows.json"}}, and raws is []interface {}{map[interface {}]interface {}{"command":"ansible-playbook --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port={{ .SSHHostPort }}' -i 127.0.0.1, ansible/site.yml"}, map[interface {}]interface {}{"packer_template_path":"/home/pruzicka/Error decoding config: render 'command': template: root:1:192: executing "root" at <.SSHHostPort>: can't evaluate field SSHHostPort in type *shell_local.EnvVarsTemplate in:

data/github/packer-templates/my_windows.json", "packer_user_variables":map[interface {}]interface {}{"name":"my_windows-10-enterprise-x64-eval", "memory":"4096", "winrm_password":"vagrant", "windows_version":"10", "autounattend":"http/windows-10/Autounattend.xml", "headless":"false", "vnc_vrdp_host_port":"5999", "iso_url":"https://software-download.microsoft.com/download/pr/17134.1.180410-1804.rs4_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso", "disk_size":"51200", "cpus":"2", "virtio_win_iso":"./packer_cache/virtio-win.iso", "iso_checksum":"27e4feb9102f7f2b21ebdb364587902a70842fb550204019d1a14b120918e455", "winrm_username":"vagrant"}, "packer_build_name":"qemu", "packer_builder_type":"qemu", "packer_debug":false, "packer_force":false, "packer_on_error":""}}
2018/08/18 10:54:55 [INFO] (telemetry) Finalizing.
ansible-playbook --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port={{ .SSHHostPort }}' -i 127.0.0.1, ansible/site.yml, config is &shell_local.Config{PackerConfig:common.PackerConfig{PackerBuildName:"", PackerBuilderType:"", PackerDebug:false, PackerForce:false, PackerOnError:"", PackerUserVars:map[string]string(nil)}, Command:"", Inline:[]string(nil), InlineShebang:"", TempfileExtension:"", Script:"", Scripts:[]string(nil), Vars:[]string(nil), EnvVarFormat:"", ExecuteCommand:[]string(nil), UseLinuxPathing:false, Ctx:interpolate.Context{Data:(*shell_local.EnvVarsTemplate)(0xc4201bcc60), Funcs:map[string]interface {}(nil), UserVariables:map[string]string{"windows_version":"10", "name":"my_windows-10-enterprise-x64-eval", "disk_size":"51200", "cpus":"2", "virtio_win_iso":"./packer_cache/virtio-win.iso", "winrm_username":"vagrant", "headless":"false", "winrm_password":"vagrant", "memory":"4096", "iso_checksum":"27e4feb9102f7f2b21ebdb364587902a70842fb550204019d1a14b120918e455", "vnc_vrdp_host_port":"5999", "iso_url":"https://software-download.microsoft.com/download/pr/17134.1.180410-1804.rs4_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso", "autounattend":"http/windows-10/Autounattend.xml"}, EnableEnv:false, BuildName:"qemu", BuildType:"qemu", TemplatePath:"/home/pruzicka/data/github/packer-templates/my_windows.json"}}, and raws is []interface {}{map[interface {}]interface {}{"command":"ansible-playbook --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user=vagrant ansible_ssh_pass=vagrant ansible_port={{ .SSHHostPort }}' -i 127.0.0.1, ansible/site.yml"}, map[interface {}]interface {}{"packer_template_path":"/home/pruzicka/data/github/packer-templates/my_windows.json", "packer_user_variables":map[interface {}]interface {}{"name":"my_windows-10-enterprise-x64-eval", "memory":"4096", "winrm_password":"vagrant", "windows_version":"10", "autounattend":"http/windows-10/Autounattend.xml", "headless":"false", "vnc_vrdp_host_port":"5999", "iso_url":"https://software-download.microsoft.com/download/pr/17134.1.180410-1804.rs4_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso", "disk_size":"51200", "cpus":"2", "virtio_win_iso":"./packer_cache/virtio-win.iso", "iso_checksum":"27e4feb9102f7f2b21ebdb364587902a70842fb550204019d1a14b120918e455", "winrm_username":"vagrant"}, "packer_build_name":"qemu", "packer_builder_type":"qemu", "packer_debug":false, "packer_force":false, "packer_on_error":""}}
2018/08/18 10:54:56 waiting for all plugin processes to complete...
2018/08/18 10:54:56 /home/pruzicka/bin/packerio: plugin process exited
2018/08/18 10:54:56 /home/pruzicka/bin/packerio: plugin process exited
2018/08/18 10:54:56 /home/pruzicka/bin/packerio: plugin process exited
2018/08/18 10:54:56 /home/pruzicka/bin/packerio: plugin process exited
2018/08/18 10:54:56 /home/pruzicka/bin/packerio: plugin process exited
```

**Comment by rickard-von-essen** [comment] 2018-08-20 09:15
In `shell-local` you can use qemu to find the IP address. Please ask on the mailing list if you need further help.

**Comment by rickard-von-essen** [comment] 2018-08-20 09:15
[mailing list](https://groups.google.com/group/packer-tool)

See https://www.packer.io/community/

**Comment by SwampDragons** [comment] 2018-08-20 16:36
Did you look at the PR I linked? The information is not in a template variable, but as an environment variable.  https://github.com/hashicorp/packer/pull/6503 adds an environment variable to the shell-local provisioner, PACKER_HTTP_ADDR. 

This is available if you build from the master branch, and will be available in the next Packer release.

**Comment by rickard-von-essen** [comment] 2018-08-20 20:46
@SwampDragons I think there is some confusion about what `.SSHHostPort` is used for, it's a port forwarding port so that the host can reach the VM with SSH, see https://www.packer.io/docs/builders/qemu.html#qemuargs.

**Comment by SwampDragons** [comment] 2018-08-20 20:52
Ah, you're right. I was mixing up two different things.

**Comment by ruzickap** [comment] 2018-08-24 13:58
That's right @rickard-von-essen. 
`.SSHHostPort` should have different values especially when doing paralel builds.
Then I can use Ansible inside `shell-local / command` with parameter `ansible_port={{ .SSHHostPort }}` to provision the right "packer build session".

**Comment by SwampDragons** [comment] 2018-12-06 19:44
I've created a meta ticket that covers the idea of sharing template engine variables with provisioners and post-processors.  I'm closing this ticket and adding the relevant information there, to help aggregate information.

**Comment by SwampDragons** [comment] 2018-12-06 19:44
(to follow progress on this, see #7079)

**Closed by SwampDragons** 2018-12-06 19:44 UTC
Labels: enhancement, provisioner/shell-local, thinking
