### ISSUE TITLE
BUG - shell script provisioner not working with amazon-ebs builder

### ISSUE THREAD

**Issue by justinkarabegovic** [hashicorp/packer#6126] opened 2018-04-10 18:55 UTC
Shell script provisioner keeps erroring out when attempting to upload and run script for amazon-ebs builder

Works, on Packer 1.2.1 but breaks on 1.2.2

    {
      "type": "shell",
      "script": "test.sh"
    }

Have tried this with a simple shell script that simply echos a couple of strings to console.

Tried this on two separate Windows 10 64 bit systems, both with Packer 1.2.2. Both fail with the same log file entries.

- Packer version from: 1.2.2 - Windows 64 bit
- Host platform: Windows 10 - 64 bit

[Files to reproduce (in Gist)](https://gist.github.com/justinkarabegovic/4cf9c135c2578bf41dde7df6ad425c7a)

[Debug Log (in Gist)](https://gist.github.com/justinkarabegovic/ec060d12473ebf895971a361a071af64)

**Comment by SwampDragons** [comment] 2018-04-10 20:43
Sorry about this. it's a duplicate of #6122 so I'm going to close it, but rest assured it'll be fixed in 1.2.3

**Closed by SwampDragons** 2018-04-10 20:43 UTC
