### ISSUE TITLE
Vagrant Post Processor Failed: unexpected EOF / interface {} is string, not uint64

### ISSUE THREAD

**Issue by 3lpsy** [hashicorp/packer#8545] opened 2019-12-30 01:49 UTC
#### Overview of the Issue

When building a qemu vm with the vagrant post-processor, the build fails when converting qcow2 file to vagrant box. The project is open source and I've linked to the full config.json and last few hundred lines of the crash log below. I'm not sure why it's failing at the end.  The two most interesting errors are:

```
... bunch of stuff
2019/12/29 19:01:55 ui error: Build 'qemu' errored: 1 error(s) occurred:

* Post-processor failed: unexpected EOF
```

```
2019/12/29 19:01:00 ui: ==> qemu (vagrant): Creating Vagrant box for 'libvirt' provider
2019/12/29 19:01:00 ui:   qemu (vagrant): Copying from artifact: output/bugmenace-0.0.3.qcow2
2019/12/29 19:01:55 packer-post-processor-vagrant plugin: panic: interface conversion: interface {} is string, not uint64
2019/12/29 19:01:55 packer-post-processor-vagrant plugin: 
2019/12/29 19:01:55 packer-post-processor-vagrant plugin: goroutine 309 [running]:
2019/12/29 19:01:55 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/post-processor/vagrant.(*LibVirtProvider).Process(0x55c851d460d0, 0x55c84f6bc6e0, 0xc000200300, 0x55c84f6bc740, 0xc000422160, 0xc000428060, 0x14, 0x0, 0xc00002b858, 0x55c84ac38003, ...)
...
```

#### Reproduction Steps

1) Attempt to build qemu/qcow2 vm via packer for the config.json linked below via packer build -only=qemu config.json
2) Include post-processor for vagrant and it fails

### Packer version

Packer v1.5.1

### Simplified Packer Buildfile

https://github.com/3lpsy/bugmenace/blob/master/config.json

### Operating system and Environment details

Arch Linux

### Log Fragments and crash.log files

https://gist.github.com/3lpsy/1d50bd8408f8d1ce1df34db2e2cef4f7

**Comment by 3lpsy** [comment] 2020-01-04 04:17
I can confirm that I do not get this error with version 1.4.5

**Comment by rgl** [comment] 2020-01-05 12:17
This is also happening here with a ubuntu 18.04 host.

**Comment by SwampDragons** [comment] 2020-01-06 20:09
Looks like this is a duplicate of #8533, so I'm closing this and will track the bug in #8533.

**Closed by SwampDragons** 2020-01-06 20:09 UTC
Labels: bug
