### ISSUE TITLE
File provisioner handles SSH connection failure differently to Shell provisioner

### ISSUE THREAD

**Issue by andywirv** [hashicorp/packer#4237] opened 2016-12-01 15:19 UTC
Packer v0.12.0
Packer Target OS/Arch: darwin amd64

Templates and log output
https://gist.github.com/andywirv/347aa7f1f372c0f2d13430be838603a5

The Shell provisioner treats the SSH response from this Ubuntu AWS AMI as a "retryable error"
https://gist.github.com/andywirv/347aa7f1f372c0f2d13430be838603a5#file-log2-L164

whereas the File provisioner will immediately exit with a failure
https://gist.github.com/andywirv/347aa7f1f372c0f2d13430be838603a5#file-log-L181

Why does this matter?
If building both a Docker image and AWS AMI based on Ubuntu (ubuntu:latest on Docker and eu-west AMI ami-ed82e39e) then they have different configuration for 
allowing the root user to login over SSH. An EC2 User Data script can be executed to allow root to login over SSH on the EC2 instance but this *may* not have executed before the first SSH attempt is made.

Fix?
Alter the File provisioner to retry in the same way that Shell provisioner does or allow an additonal delay to be added between the EC2 instance being in a 'ready' state and the first SSH attempt. I took the second approach with this https://github.com/andywirv/packer/commit/a2e24e7ca74257663d5ebac4aeee3a23b514085f but that would introduce the delay to SSH connections regardless of the builder (plus first time writing Go so no idea if this approach is ok or using an env variable is favoured approach with Packer)

**Comment by mwhooker** [comment] 2016-12-01 20:35
hmm, using the retry logic from the shell provisioner could work. It's a bit tricky though, since we don't expect the file upload to fail ever, whereas we expect the shell provisioner to trigger reboots or that kind of thing.

I want to avoid time-based approaches if possible. 


In the mean time I wonder if just putting a single no-op shell provisioner at the top of your provisioner list would accomplish the same goal

**Comment by andywirv** [comment] 2016-12-02 12:17
I tried out your idea of adding a Shell provisioner at the start. It triggers the retry loop as would be expected. However, what I then discovered is that the loop continues until the default 5min timeout is reached.

This looks to be a lower level issue whereby the TCP connection is not actually being terminated between attempts. In debug mode I was able to use the packer generated SSH key to login as root to the EC2 instance while the packer build was still looping with the same error. This proves the script in user data had run OK.

The way SSH is blocked for the root user on Ubuntu is not actually an SSH connection error ( so not an error at https://github.com/mitchellh/packer/blob/d310de8cf5871354bd1d12996a87020803d373ea/helper/communicator/step_connect_ssh.go#L169) . That makes this quite tricky to handle on the Packer side. Would mean detecting this particular error in scp process and forcing the connection to be re-established.  Adding the wait step is crude I agree but so far is the only way I have got this to work. Should I close this issue as it is a different beast now that I have better understood what is happening?

Logs below from the loop show a new session but not a new TCP connection/SSH handshake
```
2016/12/02 11:18:20 packer: 2016/12/02 11:18:20 opening new ssh session
2016/12/02 11:18:20 packer: 2016/12/02 11:18:20 Starting remote scp process:  scp -vt /tmp
2016/12/02 11:18:20 packer: 2016/12/02 11:18:20 Started SCP session, beginning transfers...
2016/12/02 11:18:20 packer: 2016/12/02 11:18:20 Copying input data into temporary file so we can read the length
2016/12/02 11:18:20 packer: 2016/12/02 11:18:20 [DEBUG] scp: Uploading script_7561.sh: perms=C0644 size=104
2016/12/02 11:18:20 packer: 2016/12/02 11:18:20 Retryable error: Error uploading script: lease login as the user "ubuntu" rather than the user "root".
2016/12/02 11:18:22 packer: 2016/12/02 11:18:22 [INFO] 104 bytes written for 'uploadData'
2016/12/02 11:18:22 [INFO] 104 bytes written for 'uploadData'
>>>> No new connection here
2016/12/02 11:18:22 packer: 2016/12/02 11:18:22 opening new ssh session
2016/12/02 11:18:22 packer: 2016/12/02 11:18:22 Starting remote scp process:  scp -vt /tmp
```

New Connection 
```
[INFO] Attempting SSH connection...
2016/12/02 11:54:49 packer: 2016/12/02 11:54:49 reconnecting to TCP connection for SSH
2016/12/02 11:54:49 packer: 2016/12/02 11:54:49 handshaking with SSH
2016/12/02 11:54:49 packer: 2016/12/02 11:54:49 handshake complete!
2016/12/02 11:54:49 packer: 2016/12/02 11:54:49 opening new ssh session
```

**Comment by danowar2k** [comment] 2019-01-17 16:55
This seems (!) to be my current problem. I build a Solaris VirtualBox OVA image. After installing the OS and rebooting the system for the first time, Solaris uses a SMF service to install a provided system configuration profile (via a profile.xml). The profile contains the info that lets the system create the vagrant user on first boot.

The problem is, the SSH server on Solaris is also managed via a SMF service. And sometimes, it seems that the SSH user isn't created yet when the SSH service is already up and running.

Packer tries to connect to the VM using SSH and the not yet created SSH user credentials and fails.
```
==> virtualbox-iso: Using ssh communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.2.24)
==> virtualbox-iso: Error uploading VirtualBox version: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
==> virtualbox-iso: Step "StepUploadVersion" failed
==> virtualbox-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
```
Even if I press "r" for retry, the packer image is marked as having an error and automatically cleans up at the end.

If there could be an additional "ssh_delay_until_connect" or something like it, I could set the delay so that I am sure the user has been created.

**Comment by danowar2k** [comment] 2019-01-28 23:34
Sorry, maybe my problem has another origin. I'm working from Windows and use git bash with mintty and have an SSH agent running. My problem may be caused by one of these issues:

https://github.com/hashicorp/packer/issues/5823

https://github.com/hashicorp/packer/issues/3670

**Closed** 2019-02-21 19:59 UTC
Labels: enhancement, post-1.0, provisioner/file
