### ISSUE TITLE
Unencrypted -> Encrypted AMI Copy Step No Longer Works (or is necessary)

### ISSUE THREAD

**Issue by farvour** [hashicorp/packer#6762] opened 2018-09-24 22:34 UTC
Packer seems to want to use the unencrypted -> encrypted snapshot methodology to create an encrypted AMI.

According to amazon now, it can be specified at launch.
https://aws.amazon.com/blogs/security/create-encrypted-amazon-ebs-volumes-custom-encryption-keys-launch-amazon-ec2-instance-2/

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`: v1.3.1 (issue was seen in 1.2.x, which is why I upgraded)
- macOS High Sierra 10.13.6
- Debug log output from `PACKER_LOG=1 https://gist.github.com/farvour/84c21d6dffceac65b8da619921f7bd53

**Comment by azr** [comment] 2018-09-25 09:57
Hello @farvour, 🙂 

thanks for reporting this, fixing it ASAP.

**Comment by farvour** [comment] 2018-09-25 16:04
Awesome. I worked around it by removing the encrypted true from my AMI block device mapping’s directive for sda1 but I think maybe packer should sanity check and not attempt to create the unencrypted AMI snapshot first if encrypt_root is true.

I ended up with the same end result as before so maybe the docs just need some clearer indication or packer just auto corrects itself.

**Comment by nullify005** [comment] 2018-10-02 01:48
👍 when the source volume is already encrypted the 'assume unencrypted to encrypted copy step' basically just adds time to the build & is entirely unnecessary

I'd love to disable encrypt_root, however it appears that when you set it to false & if the source volume is encrypted then things like AMI copy of the resulting encrypted AMI to another region fails since the flag is required in the go code to determine whether the destination AMI needs to be encrypted rather than looking at the AMI it's trying to copy & working it out that way.

https://github.com/hashicorp/packer/issues/6778

Is there a possibility of making packer a little more aware of whether the source volume is encrypted or not & then make the appropriate choices?

* if source is encrypted then the destination basically has to be encrypted regardless of whatever the user wants, therefore we can skip the additional copy unencrypted to encrypted step
* if the source is not encrypted then using the encrypt_boot flag is appropriate to allow the user to control whether the output should be encrypted
* if the output was encrypted (either because the source was encrypted or the encrypt_boot was true) then ALWAYS mark the destination for a region copy to be encrypted, rather than requiring encrypt_boot to be true as the marker for whether it needs to or not

**Comment by azr** [comment] 2018-10-02 10:00
Hello, I will try first to see if we can omit passing the encryption parameter to preserve the current ami setting, otherwise since it's a bool and golang's default value for a bool is false, it will pass false when we try to get the 'default' behaviour.

AWS' doc says: 

> By default, CopyImage preserves the encryption status of source snapshots when creating destination copies. However, you can configure the parameters of the copy process to also encrypt the destination snapshots.

**Comment by farvour** [comment] 2018-10-03 16:45
I am currently out of town for a week and a half yet but I'll give this a shot when I return. This PR may end up in the main line by then, but I'll try the point release here too.

**Comment by SwampDragons** [comment] 2018-10-12 18:32
Bumped this to the 1.4.0 milestone because the solution could be backwards-incompatible in certain edge cases.

**Comment by aplsms** [comment] 2019-02-11 21:52
Hello guys,
Any updates on it?

**Comment by rickard-von-essen** [comment] 2019-02-12 05:49
When dealing with this also consider https://groups.google.com/d/msgid/packer-tool/ee19e981-65b7-4df8-9c99-8be1012d53ee%40googlegroups.com?utm_medium=email&utm_source=footer

If the boot is encrypted, all regions should default to the default EBS KMS key.

**Comment by azr** [comment] 2019-02-19 13:11
@rickard-von-essen, the issue you linked should also be fixed by #6787, when copying to region(s), if you don't specify a key: a default one is picked.

**Comment by azr** [comment] 2019-02-19 13:13
@aplsms or @farvour could you please tell me if the binary in #6787 fixes your issue ?

**Comment by azr** [comment] 2019-02-27 10:18
Confirmed: https://github.com/hashicorp/packer/pull/6787#issuecomment-466531888 👍

**Closed** 2019-02-28 23:29 UTC
Labels: bug, builder/amazon, enhancement
