### ISSUE TITLE
Proxmox builder hits open files limit on macOS while waiting for ssh

### ISSUE THREAD

**Issue by gerardkok** [hashicorp/packer#8601] opened 2020-01-13 18:35 UTC
#### Overview of the Issue

After a number of minutes in the 'Waiting for SSH to become available' step, the proxmox builder starts throwing errors that prevent it from making an SSH connection to the proxmox VM. After reaching the ssh_timeout, the build fails. I believe this is caused by the rather low default open files limit (256) on macOS, which I'm using to run packer on. If I increase the open files limit, packer builds a proxmox template correctly.

#### Reproduction Steps

On a mac (10.14+) with the default open files limit (256), build a proxmox VM that takes a few minutes to get SSH running. For example, build Ubuntu 18.04 from the cdimage. In my situation building such a VM takes ~9 minutes, while packer hits the open files limit in about ~5 minutes.

### Packer version

Packer v1.5.1

### Simplified Packer Buildfile

[Packer build file](https://gist.github.com/gerardkok/08f4fac853b3d36173587702649d788f)

### Operating system and Environment details

macOS 10.14.6, 10.15.2
proxmox 5.4

### Log Fragments and crash.log files

Log file of my first attempt, where I referenced the proxmox api using its hostname: https://gist.github.com/gerardkok/f3f4309111a8cce39e5dbc361e693d03.

At some point the log lines changed from
```2020/01/12 20:49:08 packer-builder-proxmox plugin: [DEBUG] Error getting SSH address: 500 QEMU guest agent is not running```
to
```2020/01/12 20:49:13 packer-builder-proxmox plugin: [DEBUG] Error getting SSH address: Get https://<sensitive>:8006/api2/json/nodes/<sensitive>/qemu/109/agent/network-get-interfaces: dial tcp: lookup <sensitive>: no such host```

Assuming this might be caused by a DNS issue, I then referenced the proxmox api by ip address: https://gist.github.com/gerardkok/054ca2d47acd2b03cb6c662582e946aa

This changed the relevant log lines:
```2020/01/12 21:11:58 packer-builder-proxmox plugin: [DEBUG] Error getting SSH address: 500 QEMU guest agent is not running```
to
```2020/01/12 21:12:03 packer-builder-proxmox plugin: [DEBUG] Error getting SSH address: Get https://<sensitive>:8006/api2/json/nodes/<sensitive>/qemu/109/agent/network-get-interfaces: dial tcp <sensitive>:8006: socket: too many open files```

This gave me the idea to increase the open file limit (using `ulimit -n 524288` in the terminal I ran packer). Now the VM builds correctly: https://gist.github.com/gerardkok/8e61df7bbb132522b8232fb3841ae3b4

**Comment by jfpanisset** [comment] 2020-01-13 20:19
I can confirm that I've run into this problem on macOS 10.14.6 with the Proxmox builder, had to move to a Linux host to run packer.

**Comment by SwampDragons** [comment] 2020-01-15 21:31
Looking at those logs I'd guess it's happening in here somewhere: or in the upstream library being referenced here:

https://github.com/hashicorp/packer/blob/master/builder/proxmox/builder.go#L127-L147

**Comment by carlpett** [comment] 2020-02-22 21:24
Finally had some time to look at this today. Indeed looks like a leak in the upstream library. I'll track it down and submit a PR there.

**Comment by carlpett** [comment] 2020-02-22 21:55
Found it, waiting for PR to be merged :tada:

**Comment by jfpanisset** [comment] 2020-02-22 22:50
Thank you! Looking at the PR against the upstream library at https://github.com/Telmate/proxmox-api-go/pull/74
the fix does not appear to be platform specific. So is it a fair assumption that the problem can happen on any platform, it is just more likely to happen on macOS with a default open file limit of 256 vs 1024 on Linux for instance?

**Comment by carlpett** [comment] 2020-02-23 09:12
Yep, it happens on Linux too, if we retry long enough. Seems like most calls leak two fds (there's a pre-check that the VM exists which makes a request which leaks, and then the request we're actually doing which leaks another), so the "budget" was ~128 requests on Mac and 512 on Linux.

**Closed** 2020-02-28 18:19 UTC
Labels: bug, builder/proxmox, upstream-bug
