### ISSUE TITLE
SSH handshake Failure 

### ISSUE THREAD

**Issue by msuzoagu** [hashicorp/packer#12416] opened 2023-05-12 20:03 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue
When attempting to build ami, temporary ssh-keys generated by Packer fails ssh handshake. 

Similar issues : 
1. https://github.com/hashicorp/packer/issues/12338
2. https://github.com/hashicorp/packer-plugin-amazon/issues/336
3. https://github.com/hashicorp/packer-plugin-ansible/issues/140

- 
#### Reproduction Steps

- PACKER_LOG=1 packer build[simple packer template](https://gist.github.com/msuzoagu/ba79fc355190b5793a27c8a472093976)  

### Packer version
both`Packer v1.8.6` and `Packer v1.8.7`

### Simplified Packer Template

[simple playbook](https://gist.github.com/msuzoagu/ba79fc355190b5793a27c8a472093976)

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment:

Local Machine: macOS Ventura

Remote:
  - `aws_name = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230325"`
  - `ami_id              = "ami-0a695f0d95cefc163"`
  - `ami_owners          = ["099720109477"]`
  - `ssh_username        = "ubuntu"`

### Log Fragments and crash.log files
[crash log](https://gist.github.com/msuzoagu/01f9158f6beb2518385bbab9987a8839)

**Comment by lbajolet-hashicorp** [comment] 2023-10-13 19:53
Hi @msuzoagu,

This issue looks like a duplicate of https://github.com/hashicorp/packer-plugin-amazon/issues/336, as such, since the Ansible issue with SSH RSA keys has been taken care of, this should fix your problem if you upgrade to the latest version of the plugin.

As such, I will close this issue now since it should be fixed, if you still encounter the problem, feel free to reopen.

Thanks

**Closed by lbajolet-hashicorp** 2023-10-13 19:53 UTC
Labels: bug
