### ISSUE TITLE
VMWare: Packer fails to detect device name for 'nat' connection type when connecting

### ISSUE THREAD

**Issue by lucasyvas** [hashicorp/packer#6325] opened 2018-05-30 16:46 UTC
Packer: `1.2.4`
Host: `CentOS 7.3`
Builder: `vmware-vmx`
VMWare: `Workstation 12`

We are hoping to upgrade Packer to get around a bug that's supposed to be fixed (non-VMWare related), but we are now hitting a hard blocker with newer Packer versions (1.2.0+):

**Error detecting host IP: Unable to determine the device name for the connection type : nat**

```
vmware-vmx: Cloning source VM...[0m
[1;32m==> vmware-vmx: Starting virtual machine...[0m
[0;32m    vmware-vmx: The VM will be run headless, without a GUI. If you want to
    vmware-vmx: view the screen of the VM, connect via VNC with the password "c1W9YH0w" to
    vmware-vmx: vnc://127.0.0.1:5955[0m
[1;32m==> vmware-vmx: Waiting 10s for boot...[0m
[1;32m==> vmware-vmx: Connecting to VM via VNC (127.0.0.1:5955)[0m
[1;31m==> vmware-vmx: Error detecting host IP: Unable to determine the device name for the connection type : nat[0m
[1;32m==> vmware-vmx: Stopping virtual machine...[0m
[1;32m==> vmware-vmx: Deleting output directory...[0m
[1;31mBuild 'vmware-vmx' errored: Error detecting host IP: Unable to determine the device name for the connection type : nat[0m

==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Error detecting host IP: Unable to determine the device name for the connection type : nat
```

I haven't been able to find any information when searching about what the problem might be. All I was able to find is that there seem to have been a lot of issues resolved in the last few versions for VMWare in this area.

Our previous Packer version was quite old, but works fine for building: **0.12.0**

**Gist for build:**

https://gist.github.com/lucasyvas/26897e7a949bee0943c529f4c8a591c2

**Gist for template (ssh user and pass removed):**

https://gist.github.com/lucasyvas/7f6876f98559a5f502554b619ca463df

**Comment by SwampDragons** [comment] 2018-05-30 17:07
@arizvisa Do you have the bandwidth to take this one on?

**Comment by rickard-von-essen** [comment] 2018-05-30 17:13
Please supply the information requested in the issue template:
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by lucasyvas** [comment] 2018-05-30 18:42
Sorry about that. Updated the original post with the two gists (at the bottom)

**Comment by rickard-von-essen** [comment] 2018-05-30 19:05
Thanks, it would also be great if you could share the source vmx file.

**Comment by arizvisa** [comment] 2018-05-30 19:18
@SwampDragons, yea sure. I can make some time.

@lucasyvas, since this is using the vmware-vmx builder can you share your .vmx, and also the contents of `/etc/vmware/netmap.conf`?

**Comment by lucasyvas** [comment] 2018-05-30 20:22
@arizvisa 

VMX:

https://gist.github.com/lucasyvas/b5d50e1e94b54cb7ac465b5a409f5b84

/etc/vmware/netmap.conf

https://gist.github.com/lucasyvas/2fe0876072e08569d10d421803ef2208

**Comment by arizvisa** [comment] 2018-05-30 21:29
@lucasyvas, can you check if your virtual network editor has a nat and host-only interface configured?

Your netmap.conf only lists a bridging interface:
```
#This file is automatically generated.
# Hand-editing this file is not recommended.

network0.name = "Bridged"
network0.device = "vmnet0"
```

Where it should look something like the following depending on what you have specified in your virtual network editor.
```
#This file is automatically generated.
# Hand-editing this file is not recommended.

network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network2.name = "NAT"
network2.device = "vmnet8"
```

**Comment by arizvisa** [comment] 2018-05-30 21:32
It also looks like according to this blog-post (https://alexbelle.wordpress.com/2017/04/10/how-to-manually-configure-vmware-networking-on-linux-command-line/) you can run `vmware-networks -status` as root to see the state of vmware's networking.

So if the output of that is different from netmap.conf, then there's some detachment between those 2 states that will need some figuring out.

**Comment by lucasyvas** [comment] 2018-05-30 21:39
```
[root@ccsp-jenkins ~]# vmware-networks --status
Bridge networking on vmnet0 is running
DHCP service on vmnet1 is running
Hostonly virtual adapter on vmnet1 is enabled
DHCP service on vmnet8 is running
NAT service on vmnet8 is running
Hostonly virtual adapter on vmnet8 is enabled
All the services configured on all the networks are running
```

Interesting... it would appear the command reveals the truth and NAT is available? This was a pretty standard install at the time. It was probably the first time I ever installed it so everything is pretty close to default.

Packer 0.12.0 is very old at this point, but it manages to reconcile this somehow. I'm not surprised things have changed - as they should over time :)

Doesn't seem like VMWare is throwing much of a bone here when it comes to consistency. I've found a work around for our original issue so we can make due with the older Packer, but let me know if I can be of continued help

**Comment by arizvisa** [comment] 2018-05-31 06:55
Yea. The previous packer didn't have support for changing networks between nat, bridged, or host-only and just assumes that vmnet8 will always be nat regardless of what vmware has it configured as..

Do all your Linux VMWare systems have a netmap.conf that's different from vmware-networks -status, or is this the only particular one? On Windows, the netmap.conf appears to be honored as there's no other tool except the gui interface for vnetcfg.exe for interfacing with it.

There's really two fixes to this: one is to fix up netmap.conf to include vmnet8 so it matches your configuration for "nat". The other and probably proper fix would be to modify the linux workstation driver in packer to parse the output of vmware-networks -status (assuming you can query it as an unprivileged user) instead of parsing netmap.conf.

**Comment by arizvisa** [comment] 2018-05-31 06:59
Sorry, was thinking out loud, but the two questions:

Despite the latest being 14.0, do all of your linux systems running VMWare Workstation 12.0 have a netmap.conf that's desynchronized from vmware-networks -status?

And then, does vmware-networks -status still work when running as an unprivileged user?

**Comment by arizvisa** [comment] 2018-05-31 07:03
Oh another thing. That blogpost actually mentions there's an /etc/vmware/networking file. Does Linux's version of WS include a file at that path that matches vmware-networks -status?

**Comment by lucasyvas** [comment] 2018-05-31 17:03
@arizvisa 

To answer your question about desynchronized systems, we just have the one system on Workstation 12 so I don't think I can help verify beyond that. We currently lack the time resources to have someone set up a duplicate system as it was not one created immutably. I'm not sure my organization is yet providing licenses for 14 and they're pretty sticky about trial licenses, so comparing may be off the cards for that as well.

As for /etc/vmware/networking, that did bear a little fruit:

```
[root@ccsp-jenkins ~]# cat /etc/vmware/networking
VERSION=1,0
answer VNET_1_DHCP yes
answer VNET_1_DHCP_CFG_HASH 5E407EA3144C77054848F23EBACF43AB7D77D2D5
answer VNET_1_HOSTONLY_NETMASK 255.255.255.0
answer VNET_1_HOSTONLY_SUBNET 192.168.146.0
answer VNET_1_VIRTUAL_ADAPTER yes
answer VNET_8_DHCP yes
answer VNET_8_DHCP_CFG_HASH 7F3C421E5577572DEC6E04F35CAFBD72E39077A4
answer VNET_8_HOSTONLY_NETMASK 255.255.255.0
answer VNET_8_HOSTONLY_SUBNET 172.16.156.0
answer VNET_8_NAT yes
answer VNET_8_VIRTUAL_ADAPTER yes
```

This appears to more closely resemble the output of `vmware-networks --status` in our case at least.

**Comment by arizvisa** [comment] 2018-05-31 23:11
@rickard-von-essen, @SwampDragons: How do you guys want to proceed with this? It might take me some time to get back into developing (maybe a week to finish up what I'm currently working on), plus I don't have any Linux systems handy to test the reproduction of this specific situation.

- There's DanHam's suggestion, which could be fixed probably by adding documentation.
- There's the choice of deprecating the parsing of netmap.conf on Linux WS and use the parser for VMWare fusion against workstation's networking file.
- If we can provably run vmware-networks -status as a regular user, we can write a parser for it's output. (I might need that binary, though, to reverse-engineer what it's capable of emitting so that we can catch all the cases).
- Or we can test to see if the netmap.conf is missing entries for nat or hostonly, and then fall back to the networking file assuming it has the same format (which it looks like it does).

**Comment by lucasyvas** [comment] 2018-06-01 00:45
@DanHam The system is rebooted on a semi-regular basis, but your tip on trying the GUI is interesting. I'll see if I have some time to try to forward it to my display and check the result. We've definitely used the GUI before, but not for a while and not after reboots.

**Comment by DanHam** [comment] 2018-06-04 12:59
Apologies for the tl;dr comment! However...

@arizvisa Looks like `vmware-networks --status` needs to be run as a privileged user.

```
$ vmware-networks --status
Failed to initialize

$ sudo vmware-networks --status
Bridge networking on vmnet0 is running
DHCP service on vmnet1 is running
Hostonly virtual adapter on vmnet1 is enabled
DHCP service on vmnet8 is running
NAT service on vmnet8 is running
Hostonly virtual adapter on vmnet8 is enabled
All the services configured on all the networks are running
```

> do all of your linux systems running VMWare Workstation 12.0 have a netmap.conf that's desynchronized from vmware-networks -status?

I'm pretty sure we shouldn't be seeing any discrepancies here. While we're looking for problems with Packer, this suggests it could be Workstation that's having the issue. On a fresh install, `netmap.conf` and `sudo vmware-networks --status` are fully synchronised.

Additionally, I've been unable to reproduce this problem using an almost identical setup:

VMware Workstation: 12.5.9 build-7535481
OS: CentOS Linux release 7.5.1804 (Core)
Packer: Packer v1.2.4

@lucasyvas Do you have `vmnet1` and `vmnet8` folders under `/etc/vmware`? If everything else under `/etc/vmware` is seemingly OK, it could be that it's just `netmap.conf` that's been corrupted somehow. The file is automatically created for you when you click 'Save' on the Virtual Network Editor GUI so you could try something like:

1. Backup the existing `netmap.conf` file: `$ sudo mv /etc/vmware/netmap.conf{,.SAVEME}`
2. Start up the Virtual Network Editor GUI: `$ vmware-netcfg &`; You'll need X11 forwarding for this to work if you've logged in via ssh.
3. Ensure you have the required entries for your vmnet1 and vmnet8 networks. The configuration for each should correspond to the information you have in your `/etc/vmware/networking` file e.g. vmnet1: 192.168.146.0 and vmnet8: 172.16.156.0.
4. Click on 'Save' when done.
5. Confirm your /etc/vmware/netmap.conf file has been restored correctly.

I've tested that on my own system and this works OK, but just for completeness, `/etc/vmware/netmap.conf` should now look like:

```
# This file is automatically generated.
# Hand-editing this file is not recommended.
network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network8.name = "NAT"
network8.device = "vmnet8"
```

After this Packer should be able to pick up the required info it needs from that file so you shouldn't see further errors. If this is the case and everything is working well again, don't forget to remove the `/etc/vmware/netmap.conf.SAVEME` file!

If you do still see errors, it could be that VMware has really got itself in a pickle. In this case we could try completely removing and recreating all of the network config under /etc/vmware... but hopefully that won't be necessary.

**Comment by SwampDragons** [comment] 2018-08-10 20:48
@lucasyvas Was Dan's comment above enough to help you? Wondering if I should close this ticket.

**Comment by lucasyvas** [comment] 2018-08-10 21:34
@SwampDragons I've passed the information off to those this issue may concern moving forward. I think there's plenty of detail to work with here to get around the issue; I have no further comments or information to share at this time. I believe you can probably close this as the troubleshooting steps seem to be adequate to pursue a resolution outside of Packer.

**Comment by SwampDragons** [comment] 2018-08-10 21:35
Thanks for following up!  Have an awesome day.

**Closed by SwampDragons** 2018-08-10 21:35 UTC
Labels: bug, builder/vmware
