### ISSUE TITLE
Ansible provisioner hangs again

### ISSUE THREAD

**Issue by fred-gb** [hashicorp/packer#9723] opened 2020-08-06 15:59 UTC
Hi,

I’m sorry but I have problem from long time with packer.
Provisionning hangs, I have to “ctrl+c” to exit.

Today, I try on fresh Ubuntu Focal install, but same problem.

#### Reproduction Steps

Nothing special. Clean install of Ansible by pip in virtual-env and packer latest version

### Packer version

1.6.1

### Simplified Packer Buildfile

```
{
    "variables": {
    },
    "builders": [
        {
          "type": "lxd",
          "name": "ubuntu-2004-qw",
          "image": "ubuntu-minimal:focal",
          "output_image": "ubuntu-2004-qw",
          "publish_properties": {
            "description": "Image LXD ubuntu bionic ansible ready"
          }
      }
    ],
    "provisioners": [
      {
        "type": "ansible",
        "user": "root",
        "playbook_file": "config.yml",
        "extra_arguments": ["-vvvv"]
      }
    ]
}
```

### Operating system and Environment details

Ubuntu 20.04
LXD Snap 4.4

### Log Fragments and crash.log files

`PACKER_DEBUG=1 packer build ansible.json`

```
PACKER_DEBUG=1 packer build ansible.json
ubuntu-2004-qw: output will be in this color.

==> ubuntu-2004-qw: Creating container...
==> ubuntu-2004-qw: Provisioning with Ansible...
    ubuntu-2004-qw: Setting up proxy adapter for Ansible....
==> ubuntu-2004-qw: Executing Ansible: ansible-playbook -e packer_build_name="ubuntu-2004-qw" -e packer_builder_type=lxd -vvvv -e ansible_ssh_private_key_file=/tmp/ansible-key338046142 -i /tmp/packer-provisioner-ansible602967813 /labo/devopsotheque/packer/config.yml
    ubuntu-2004-qw: ansible-playbook 2.9.11
    ubuntu-2004-qw:   config file = /etc/ansible/ansible.cfg
    ubuntu-2004-qw:   configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    ubuntu-2004-qw:   ansible python module location = /home/ansible/devops/lib/python3.6/site-packages/ansible
    ubuntu-2004-qw:   executable location = /home/ansible/devops/bin/ansible-playbook
    ubuntu-2004-qw:   python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
    ubuntu-2004-qw: Using /etc/ansible/ansible.cfg as config file
    ubuntu-2004-qw: setting up inventory plugins
    ubuntu-2004-qw: host_list declined parsing /tmp/packer-provisioner-ansible602967813 as it did not pass its verify_file() method
    ubuntu-2004-qw: script declined parsing /tmp/packer-provisioner-ansible602967813 as it did not pass its verify_file() method
    ubuntu-2004-qw: auto declined parsing /tmp/packer-provisioner-ansible602967813 as it did not pass its verify_file() method
    ubuntu-2004-qw: Parsed /tmp/packer-provisioner-ansible602967813 inventory source with ini plugin
    ubuntu-2004-qw: Loading callback plugin default of type stdout, v2.0 from /home/ansible/devops/lib/python3.6/site-packages/ansible/plugins/callback/default.py
    ubuntu-2004-qw:
    ubuntu-2004-qw: PLAYBOOK: config.yml ***********************************************************
    ubuntu-2004-qw: Positional arguments: /labo/devopsotheque/packer/config.yml
    ubuntu-2004-qw: verbosity: 4
    ubuntu-2004-qw: connection: smart
    ubuntu-2004-qw: timeout: 10
    ubuntu-2004-qw: become_method: sudo
    ubuntu-2004-qw: tags: ('all',)
    ubuntu-2004-qw: inventory: ('/tmp/packer-provisioner-ansible602967813',)
    ubuntu-2004-qw: extra_vars: ('packer_build_name="ubuntu-2004-qw"', 'packer_builder_type=lxd', 'ansible_ssh_private_key_file=/tmp/ansible-key338046142')
    ubuntu-2004-qw: forks: 5
    ubuntu-2004-qw: 1 plays in /labo/devopsotheque/packer/config.yml
    ubuntu-2004-qw:
    ubuntu-2004-qw: PLAY [default] *****************************************************************
    ubuntu-2004-qw: META: ran handlers
    ubuntu-2004-qw:
    ubuntu-2004-qw: TASK [Ajout user ansible avec cle ssh] *****************************************
    ubuntu-2004-qw: task path: /labo/devopsotheque/packer/config.yml:7
    ubuntu-2004-qw: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root
    ubuntu-2004-qw: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=38715 -o 'IdentityFile="/tmp/ansible-key338046142"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/7b4eb3a240 127.0.0.1 '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
```

**Comment by SwampDragons** [comment] 2020-08-06 20:03
Hi, thanks for reaching out. 

I believe this is a duplicate of #9034, so I am going to close this to keep the issue tracked in one place.

**Closed by SwampDragons** 2020-08-06 20:03 UTC
Labels: bug, builder/lxc, duplicate, provisioner/ansible-remote
