### ISSUE TITLE
azure-arm builder fails to delete additional disks

### ISSUE THREAD

**Issue by svdaddio** [hashicorp/packer#10070] opened 2020-10-08 21:02 UTC
### Overview of the Issue

Using packer v1.6.2 and later, packer tries to delete the additional disks when they are still attached to the VM. This causes the build to fail.

#### Reproduction Steps

Build an azure-arm image with the disk_additional_size argument set with at least one integer value on packer v1.6.2 or later. When deleting resources, azure will fail to delete the additional disk.

### Packer version

From 1.6.2 to latest (currently 1.6.4)

### Simplified Packer Buildfile

```
  "builders": [
    {
      "type": "azure-arm",
      "subscription_id": "{{user `subscription_id`}}",
      "tenant_id": "{{user `tenant_id`}}",
      "client_id": "{{user `client_id`}}",
      "client_secret": "{{user `client_secret`}}",
      "managed_image_name": "{{user `image_name`}}-{{isotime \"2006-01-02-150405\"}}",
      "managed_image_resource_group_name": "{{user `resource_group_name`}}",
      "temp_compute_name": "{{user `temp_name`}}",
      "custom_resource_build_prefix": "{{user `prefix`}}",
      "os_type": "{{user `os_type`}}",
      "os_disk_size_gb": "{{user `os_disk_size`}}",
      "disk_additional_size": "{{user `disk_additional_size`}}",
      "disk_caching_type": "{{user `disk_caching_type`}}",
      "managed_image_storage_account_type": "{{user `managed_image_storage_account_type`}}",
      "image_publisher": "{{user `image_publisher`}}",
      "image_offer": "{{user `image_offer`}}",
      "image_sku": "{{user `image_sku`}}",
      "image_version": "{{user `image_version`}}",
      "build_resource_group_name": "fzeu2-packer-li-{{user `environment`}}-rgp-01",
      "virtual_network_name": "fzeu2-sec-li-{{user `environment`}}-vnet-01",
      "virtual_network_subnet_name": "fzeu2-packer-{{user `environment`}}-trusted-00",
      "virtual_network_resource_group_name": "fzeu2-secvnet-li-{{user `environment`}}-rgp-01",
      "private_virtual_network_with_public_ip": false,
      "vm_size": "{{user `vm_size`}}",
      "azure_tags": {
        "product": "{{user `product`}}",
        "applicationName": "{{user `application_name`}}",
        "environment": "{{user `environment`}}",
        "version": "{{user `version`}}",
        "department": "Information Security"
      }
    }
  ],
```
### Operating system and Environment details

Built on azure DevOps pipeline. Build server is running Ubuntu 18
Packer image is building an Ubuntu 18 server.

### Log Fragments and crash.log files
```
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm:  -> Additional Disk 1: '/subscriptions/GUID/resourceGroups/FZEU2-PACKER-LI-TST-RGP-01/providers/Microsoft.Compute/disks/3080ddlv6g3-1'
==> azure-arm: Failed to delete the managed Additional Disk!
==> azure-arm: compute.DisksClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Disk 3080ddlv6g3-1 is attached to VM /subscriptions/GUID/resourceGroups/fzeu2-packer-li-tst-rgp-01/providers/Microsoft.Compute/virtualMachines/lgstshtst3080."
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...
==> azure-arm:  -> Deployment Resources within: 3080dplv6g3
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'lgstshtst3080'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : '3080nilv6g3'
==> azure-arm:  -> Microsoft.Compute/disks : '/subscriptions/GUID/resourceGroups/FZEU2-PACKER-LI-TST-RGP-01/providers/Microsoft.Compute/disks/3080oslv6g3'
==> azure-arm: Removing the created Deployment object: '3080dplv6g3'
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, not deleting ...
Build 'azure-arm' errored after 9 minutes 45 seconds: compute.DisksClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Disk 3080ddlv6g3-1 is attached to VM /subscriptions/GUID/resourceGroups/fzeu2-packer-li-tst-rgp-01/providers/Microsoft.Compute/virtualMachines/lgstshtst3080."

==> Wait completed after 9 minutes 45 seconds

==> Some builds didn't complete successfully and had errors:
--> azure-arm: compute.DisksClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Disk 3080ddlv6g3-1 is attached to VM /subscriptions/GUID/resourceGroups/fzeu2-packer-li-tst-rgp-01/providers/Microsoft.Compute/virtualMachines/lgstshtst3080."
```

**Comment by SwampDragons** [comment] 2020-10-08 22:19
Hi, thanks for reaching out. @nywilken I suspect this has to do with https://github.com/hashicorp/packer/pull/9559 -- can you take a look when you have the bandwidth?

**Comment by nywilken** [comment] 2020-10-09 15:00
Hi @SwampDragons I can take a look for sure. Quickly looking at the logs I suspect that previously the vm was being destroyed before trying to delete the attached disks so this wasn't an issue.

**Comment by svdaddio** [comment] 2020-10-11 13:20
> Hi @SwampDragons I can take a look for sure. Quickly looking at the logs I suspect that previously the vm was being destroyed before trying to delete the attached disks so this wasn't an issue.

I can post destroy logs from a run with Packer v1.6.1 if that would be helpful?

**Comment by nywilken** [comment] 2020-10-13 19:08
Hi there @svdaddio @jmservianri thanks for the followup. In v1.6.2 there was a refactor in the Azure builder to fix an issue where there were duplicate calls to delete resources that had already been deleted. In that refactor we fixed a similar issue for VHD builds but it looks like we need to do the same for managed disk when using an existing resource group via `"build_resource_group_name"`. 

@svdaddio I can reproduce this issue so no need for the build logs prior to 1.6.2. But thank you. 

@jmservianri is your configuration using `"build_resource_group_name"` as well? 

I can't reproduce this issue when using a Packer created resource group, "build_resource_group_name" is not defined, so I want to make sure that I am not missing anything.

**Comment by jmservianri** [comment] 2020-10-14 08:35
Hi @nywilken, yes i'm using build_resource_group_name because i have policies that blocks dynamic public IPs (Packer doesn't have the possibility to use static IPs) and this policy is disabled in the resource group that i need to use by packer.

**Comment by nywilken** [comment] 2020-10-23 20:03
Hello again @svdaddio  and @jmservianri!  I think I have found a fix for this. The issue as mentioned above was due to the order of the destruction. Previously the Azure builder would delete all deployment items before trying to removed the additional disk so they were esstentially unattached and ready for deletion. In v1.6.2 we consolidated the deletion steps but missed this issue because our test case was not using an exiting resource group. The fix reorders the destruction steps and includes a test to prevent this issue in the future. 

You can find test binaries for the patch [here](https://app.circleci.com/pipelines/github/hashicorp/packer/7692/workflows/c75c8356-b102-42de-9c8c-2da6dabc56d3/jobs/88530/artifacts).  Could you please tell me if the fix works for you? :D
Thank you!

**Closed** 2020-10-23 22:19 UTC
Labels: builder/azure, regression, track-internal
