### ISSUE TITLE
Windows reporting Packer 1.2.2 contains a trojan

### ISSUE THREAD

**Issue by btm** [hashicorp/packer#6093] opened 2018-04-01 17:35 UTC
I recently downloaded Packer 1.2.2 for Windows. It appears that Windows Defender updated its definitions today and it is now quarantining the packer binary as containing 'TrojanSpy:Win32/Rebhip.H'. I downloaded the archive again today from https://www.packer.io/downloads.html and now it is quarantined immediately on download by Windows. 

The copy of the archive that I still have on disk is `packer_1.2.2_windows_amd64.zip` with a sha256sum of `9c066bbe463376f9e7991326ecba09672b121776a0f2566c2d8e6ef72d52106e`.

**Comment by MattFenner** [comment] 2018-04-01 23:34
Yes. I am getting the same problem

**Comment by btm** [comment] 2018-04-02 00:52
[packer_1.2.1_windows_amd64.zip](https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_windows_amd64.zip) seems to be fine though, sha256sum `4690199d4be73b7e928ade026451d0a163b6df100f1ba5eaab44cb55fd538230`.

**Comment by lestephane** [comment] 2018-04-02 13:37
Is there any inkling as to whether this is a false positive?

**Comment by btm** [comment] 2018-04-02 14:58
I looked through the binary for strings matching the markers on https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=TrojanSpy:Win32/Rebhip.H and couldn't find anything. I would guess so though.

**Comment by mwhooker** [comment] 2018-04-02 16:26
Thanks for the report. I'm almost certain this is a false positive. There is a similar issue on github for terraform, with lots of information there that I think also applies to packer: https://github.com/hashicorp/terraform/issues/16539. I've also verified that the checksum of the file you linked matches the contents of the signed shasum file.

I will try to reproduce and submit it for malware analysis to Windows Defender Security Intelligence. I will report back if it finds anything.

**Comment by mwhooker** [comment] 2018-04-02 16:54
We've submitted to Windows Defender Security Intelligence and will update when we hear back

**Comment by Godunder** [comment] 2018-04-03 17:30
I'm also receiving this from Symantec as Tojan.Gen.6 :
![virus_packer1_2_2](https://user-images.githubusercontent.com/23055674/38265216-2dbfd196-3743-11e8-9c28-04c428c236ef.PNG)

**Comment by mwhooker** [comment] 2018-04-04 18:56
Hi All,

We've heard back from Microsoft regarding the `TrojanSpy:Win32/Rebhip.H` detection. They have confirmed that packer does not contain malware. Upgrading the definitions to at least version `1.265.51.0` should fix this. If you continue to receive malware detection notices, please open a new issue with:

* definition version
* malware detected name
* packer version
* packer architecture (amd64/32)

**Comment by jefferai** [comment] 2018-04-04 19:46
Still finding it with 1.265.51.0.

**Comment by mwhooker** [comment] 2018-04-04 21:17
Looks like the 64 bit is still triggering the alert. I've rescanned it with Windows Defender and as of `1.265.62.0` it's still triggering, though still no malware detected. 
<img width="1110" alt="screen shot 2018-04-04 at 2 15 40 pm" src="https://user-images.githubusercontent.com/15618/38335305-bca8b042-3812-11e8-8468-aaf17b5fe669.png">


I think eventually it will get added to the definition, but as there's nothing more for us to do, I'm going to close this. My recommendation would be to use an earlier version of Packer if you're worried about this, or wait for the definitions to be updated. You can also submit the file yourself to see the analysis.

**Closed by mwhooker** 2018-04-04 21:17 UTC
Labels: build, upstream-bug

**Comment by mwhooker** [comment] 2018-04-05 02:47
64 bit windows passing on WDSI with definition `1.265.74.0`.
<img width="1116" alt="screen shot 2018-04-04 at 7 46 43 pm" src="https://user-images.githubusercontent.com/15618/38344913-fcf5e13c-3840-11e8-96e5-853838d579d9.png">
