### ISSUE TITLE
packer with vmware-clone fails

### ISSUE THREAD

**Issue by zerr0s** [hashicorp/packer#10411] opened 2020-12-21 08:28 UTC
Hi, forgive me for my bad english.

I'm trying to use packer to automate the creation of templates based on linux (ubuntu 20.04).
Actually I have a problem when packer clones the existing template to create the new VM: The nic is not connected at startup.

I have verified the existence of "ethernet0.startConnected = TRUE" if the vmtx file, and when I created a new vm using the template directly from the vsphere web interface, the option "Connected at startup" is correctly checked.

When the vm is created by packer, I have to check the option from vmware web to connet the nic. After that all provisionners can run correctrly.

What am I doing wrong ??

vmware version: 6.5
packer version: 1.6.5

```
{
  "builders": [
    {
      "type": "vsphere-clone",
      "vcenter_server": "xxxxx",
      "datacenter": "xxxxx",
      "username": "xxxx",
      "password": "xxxxx",
      "insecure_connection": "true",

      "template": "ubuntu_server_20.04",

      "communicator": "ssh",
      "ssh_username": "auto",
      "ssh_private_key_file": "./sshkey",
      "boot_wait": "30s",
      "host": "vmwarehost.local",
      "vm_name": "newvm",
      "datastore": "myds",
      "folder": "packer-test",
      "CPUs": 2,
      "CPU_hot_plug": true,
      "RAM": 2048,
      "RAM_hot_plug": true,
      "RAM_reserve_all": false,
      "firmware": "bios",

      "network": "LAN",
      "customize": {
        "linux_options": {
          "host_name": "packer-test",
          "domain": "mydomain.local",
          "time_zone": "UTC"
        },
        "network_interface": {
          "ipv4_address": "192.168.0.5",
          "ipv4_netmask": "24"
        },
        "ipv4_gateway": "192.168.0.1",
        "dns_server_list": ["192.168.0.1"]
      }

    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "ls -lrth /",
        "echo done"
      ]
    }
  ]
}
```

Thanks.

**Comment by SwampDragons** [comment] 2021-01-04 18:50
Hi, thanks for reaching out! This github issue tracker is mostly used for bug reports; you may have better luck getting community help from the [community forum](https://discuss.hashicorp.com/c/packer).

**Comment by SwampDragons** [comment] 2021-02-18 17:58
Since this is a question and not a bug, it isn't super actionable, but I can give some advice before closing. 

The first thing I'd suggest is to check that you're able to manually connect via winrm after the hardening; e.g. after the hardening has run and while Packer is confused, can you actually connect to the instance outside of Packer?  You can use the --debug flag when calling Packer to cause it to freeze between steps, the --on-error=ask flag to cause it to pause when the connection fails, or the [breakpoint](https://www.packer.io/docs/provisioners/breakpoint) provisioner to freeze between provisioners, any one of which should prevent Packer from timing out and cleaning up the instance.

If you can't connect via WinRM manually, this is a configuration/hardening issue, not a Packer issue, and you need to figure out how to open you VM back up so you can still connect to it. Maybe save the hardening until the very last step in the Packer build so you don't have to reconnect to the VM. 

But if you can connect manually, then maybe something has changed about _how_ you need to connect to winrm. For example, domain joins often mess the Packer communicator up. See if you can shut down the VM and save it there, then launch a new packer build. These multi-stage builds can help work around connectivity changes. We have a little guide with a basic walkthrough of the concept of pipelining builds [here](https://www.packer.io/guides/packer-on-cicd/pipelineing-builds)

Anyway, that's my thoughts. I'm going to close this since I think this is Packer working as designed, and CIS hardening also working as designed.

**Comment by SwampDragons** [comment] 2021-02-18 18:14
wrong tab, sorry! Moved my comment to the correct issue.

**Closed** 2021-04-15 15:22 UTC
Labels: builder/vsphere, question, remote-plugin/vsphere
