### ISSUE TITLE
Packer darwin/arm64 support

### ISSUE THREAD

**Issue by sylviamoss** [hashicorp/packer#10708] opened 2021-03-01 15:23 UTC
Apple has recently announced and begun shipping hardware including the M1 chip, also known as Apple "silicon". As of Go 1.16, support for this new hardware in the Go language is via a new darwin/arm64 platform.

Packer should start supporting darwin/arm64 via both https://www.packer.io/downloads and homebrew tap.

**Comment by evertiro** [comment] 2021-04-03 01:13
So... I have an M1, and this fails currently. I've been trying to sort through an issue over on [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2385) to add M1 support, which led to an issue on [bento](https://github.com/chef/bento/issues/1344), which led here. Currently, trying to build the box results in the following:

```
packer build -only=parallels-iso ubuntu-20.04-arm64.json
parallels-iso: output will be in this color.

==> parallels-iso: Retrieving ISO
==> parallels-iso: Trying http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-live-server-arm64.iso
==> parallels-iso: Trying http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-live-server-arm64.iso?checksum=sha256%3A69460b49c6781a845ca561263af3850e107814ffb9c08a19555e819d49feef4c
==> parallels-iso: http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-live-server-arm64.iso?checksum=sha256%3A69460b49c6781a845ca561263af3850e107814ffb9c08a19555e819d49feef4c => /Users/dgriffiths/Work/Vagrant/bento/packer_templates/ubuntu/packer_cache/a06a0437be2ba6315867ed8c431f8fb1a95c27cf.iso
==> parallels-iso: Starting HTTP server on port 8147
==> parallels-iso: Creating virtual machine...
==> parallels-iso: Applying default settings...
==> parallels-iso: Creating hard drive...
==> parallels-iso: Setting the boot order...
==> parallels-iso: Attaching ISO to the default CD/DVD ROM device...
==> parallels-iso: Starting the virtual machine...
==> parallels-iso: Error starting VM: prlctl error: Failed to start the VM: Unable to start "ubuntu-20.04-arm64" because your Mac is equipped with the Apple M1 chip that does not support Intel-based operating systems. To create a compatible virtual machine, use an ISO or VHDX image file with an ARM-based operating system.
==> parallels-iso: Unregistering virtual machine...
==> parallels-iso: Deleting output directory...
Build 'parallels-iso' errored after 15 seconds 631 milliseconds: Error starting VM: prlctl error: Failed to start the VM: Unable to start "ubuntu-20.04-arm64" because your Mac is equipped with the Apple M1 chip that does not support Intel-based operating systems. To create a compatible virtual machine, use an ISO or VHDX image file with an ARM-based operating system.

==> Wait completed after 15 seconds 632 milliseconds

==> Some builds didn't complete successfully and had errors:
--> parallels-iso: Error starting VM: prlctl error: Failed to start the VM: Unable to start "ubuntu-20.04-arm64" because your Mac is equipped with the Apple M1 chip that does not support Intel-based operating systems. To create a compatible virtual machine, use an ISO or VHDX image file with an ARM-based operating system.

==> Builds finished but no artifacts were created.
```

The message is a bit nonsensical because the same image works fine when downloaded and loaded in Parallels manually. I suspect this is because while software installed on the M1 itself needs to be compiled for `amd64`, anything installed in the virtualized environment (starting with Parallels Tools) needs to be `aarch64`.

**Comment by sylviamoss** [comment] 2021-04-06 08:51
Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by gwaaf** [comment] 2021-04-17 12:59
I cannot reproduce the **prlctl** error @evertiro is getting but nonetheless the VM cannot be created because typing the boot command does not work and the build fails after the SSH connection timeout. (see log below)
Packer uses the Python script in `builder/parallels/common/prltype.go` and the [The Parallels Virtualization SDK for Mac](https://www.parallels.com/download/pvsdk/) to type the boot command.
Unfortunately the shared library that the SDK uses is compiled for x86 and therefore the Python script fails:
```
/Library/Frameworks/ParallelsVirtualizationSDK.framework/Versions/8/Libraries/Python/2.7/prlsdkapi/prlsdk.so: Mach-O 64-bit dynamically linked shared library x86_64
```


That means we have to wait for Parallels to fix their SDK.

Build log:
```
packer build -only=parallels-iso ubuntu-20.04-live-arm64.json 
parallels-iso: output will be in this color.

==> parallels-iso: Retrieving ISO
==> parallels-iso: Trying http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-live-server-arm64.iso
==> parallels-iso: Trying http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-live-server-arm64.iso?checksum=sha256%3A69460b49c6781a845ca561263af3850e107814ffb9c08a19555e819d49feef4c
==> parallels-iso: http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.2-live-server-arm64.iso?checksum=sha256%3A69460b49c6781a845ca561263af3850e107814ffb9c08a19555e819d49feef4c => /Users/gwaaf/bento/packer_templates/ubuntu/packer_cache/a06a0437be2ba6315867ed8c431f8fb1a95c27cf.iso
==> parallels-iso: Starting HTTP server on port 8755
==> parallels-iso: Creating virtual machine...
==> parallels-iso: Applying default settings...
==> parallels-iso: Creating hard drive...
==> parallels-iso: Setting the boot order...
==> parallels-iso: Attaching ISO to the default CD/DVD ROM device...
==> parallels-iso: Starting the virtual machine...
==> parallels-iso: Waiting 5s for boot...
==> parallels-iso: Host IP for the Parallels machine: 192.168.1.36
==> parallels-iso: Typing the boot command...
==> parallels-iso: Using ssh communicator to connect: 10.211.55.6
==> parallels-iso: Waiting for SSH to become available...
==> parallels-iso: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
==> parallels-iso: Unregistering virtual machine...
==> parallels-iso: Deleting output directory...
Build 'parallels-iso' errored after 2 minutes 41 seconds: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

**Comment by m-emelchenkov** [comment] 2021-04-17 19:06
It's a super-important issue, because Bento boxes are work horses for many people. I do not have M1 (yet) so cannot test, but there is a new SDK optimized for M1 and Parallels 16.5: https://www.parallels.com/download/pvsdk/m1/. It has prlsdk.so compiled for arm64, I checked.

**Comment by evertiro** [comment] 2021-04-17 19:57
> It's a super-important issue, because Bento boxes are work horses for many people. I do not have M1 (yet) so cannot test, but there is a new SDK optimized for M1 and Parallels 16.5: https://www.parallels.com/download/pvsdk/m1/. It has prlsdk.so compiled for arm64, I checked.

Yes. Including me. I don't know much about how Vagrant works behind the scenes (although I recently joined the VVV team, so I'm learning quickly), but it's a pretty crucial part of my daily workflow.

I now have issues on several different repos relevant, in some way, to this issue. Since this specific issue seems to be the lynchpin, I'm going to do a little bit of a data dump and put as much information as I can here. Hopefully, either it'll give someone else inspiration on how to fix this, or can serve as a starting point for me figuring it out. If you know more about what's going on here than I do but don't have an M1, please feel free to reach out. I'm more than happy to be the resident guinea pig in any way necessary.

My journey here started over on the [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2385) repo. In my "day job" I do custom WordPress work, and VVV is central to that process. My main work laptop recently fell prey to a poorly timed power spike and I was forced to buy a new laptop. I bought an M1 because cross-compatibility is important for my "night job" and I hadn't been able to do proper testing on a Mac in ages. Besides, I like tinkering and figured the challenge of getting everything working on a new chip would be fun. Well, it's been interesting. While all of the individual pieces of VVV work on the M1 chip, VVV itself didn't because it's still running Ubuntu 18.x boxes. I spent years as a core dev for Arch Linux... can't be that hard to upgrade, right? (It isn't... unless you're on M1).

There's no 20.x bento box that works on M1, but there _is_ an alternative box that (used to) work. Version 1.0.0 of [rueian/ubuntu20-m1](https://app.vagrantup.com/rueian/boxes/ubuntu20-m1) worked until yesterdays Vagrant update. Version 2.0.0 doesn't work, don't bother trying it. While the image provided by rueian does work, it doesn't work perfectly. Something in how it was built resulted in a permissions issue; PHP can't actually write to its own webroot. So at this point, I have issues open on VVV for [fixing Parallels with VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2385), [updating VVV to 20.04](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2386), and [the permissions issue](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2398). Since I'm now using VVV with three major deviations from what's officially supported, it's hard to tell what the root of any problem is. The permissions issue could easily be caused by a configuration issue with Parallels or the M1 itself, since I'm the first person officially supporting them (I'm now on the VVV team for specifically that purpose). But... it could just as easily be a result of a misconfiguration in the box I'm using. Logically, the next step is trying to add an M1 build for bento itself. Which I tried, and failed, and is documented on the bento repo [here](https://github.com/chef/bento/issues/1344).

That failure led to the realization that the problem wasn't actually with bento, but with the cross-compilation issue in packer which I mentioned above. So here I am. I'm willing to help however I can, so let me know what I can do. That said... as of yesterday, I've been thrown another hurdle. Since the Vagrant update yesterday, I'm now getting the following:

```
==> default: Mounting shared folders...
    default: /srv/www => /Users/dgriffiths/Work/Vagrant/clients/www
    default: /srv/config => /Users/dgriffiths/Work/Vagrant/clients/config
    default: /var/log/php => /Users/dgriffiths/Work/Vagrant/clients/log/php
    default: /srv/database => /Users/dgriffiths/Work/Vagrant/clients/database/sql
    default: /var/log/nginx => /Users/dgriffiths/Work/Vagrant/clients/log/nginx
    default: /srv/provision => /Users/dgriffiths/Work/Vagrant/clients/provision
    default: /srv/certificates => /Users/dgriffiths/Work/Vagrant/clients/certificates
    default: /var/log/memcached => /Users/dgriffiths/Work/Vagrant/clients/log/memcached
    default: /var/log/provisioners => /Users/dgriffiths/Work/Vagrant/clients/log/provisioners
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Destroying unused networking interface...
Traceback (most recent call last):
	112: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	111: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `action'
	110: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `call'
	109: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:614:in `lock'
	108: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:215:in `block in action'
	107: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:246:in `action_raw'
	106: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	105: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	104: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	103: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	102: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	101: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	100: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 99: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 98: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 97: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 96: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 95: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 94: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 93: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 92: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 91: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	 90: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 89: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 88: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 87: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 86: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 85: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 84: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 83: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 82: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 81: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 80: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 79: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 78: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 77: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/customize.rb:39:in `call'
	 76: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 75: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/box_register.rb:36:in `call'
	 74: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 73: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	 72: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 71: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/prepare_clone_snapshot.rb:36:in `call'
	 70: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 69: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/import.rb:66:in `call'
	 68: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 67: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/box_unregister.rb:32:in `call'
	 66: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 65: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/sane_defaults.rb:24:in `call'
	 64: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 63: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/customize.rb:39:in `call'
	 62: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 61: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 60: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 59: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
	 58: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 57: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 56: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 55: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 54: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 53: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 52: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 51: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 50: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 49: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 48: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 47: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 46: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 45: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 44: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 43: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 42: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 41: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 40: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 39: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 38: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 37: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 36: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 35: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 34: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 33: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/check_shared_interface.rb:13:in `call'
	 32: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 31: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/set_name.rb:48:in `call'
	 30: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 29: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/clear_forwarded_ports.rb:16:in `call'
	 28: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 27: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/provision.rb:80:in `call'
	 26: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 25: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/prepare_forwarded_port_collision_params.rb:35:in `call'
	 24: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 23: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:52:in `call'
	 22: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 21: from /Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/action/prepare_nfs_valid_ids.rb:12:in `call'
	 20: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 19: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	 18: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 17: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	 16: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 15: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	 14: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 13: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/synced_folders.rb:145:in `call'
	 12: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/guest.rb:43:in `capability'
	 11: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:111:in `capability'
	 10: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:111:in `call'
	  9: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:27:in `persist_mount_shared_folder'
	  8: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:27:in `map'
	  7: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:27:in `each'
	  6: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:28:in `block in persist_mount_shared_folder'
	  5: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:28:in `map'
	  4: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:28:in `each'
	  3: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/linux/cap/persist_mount_shared_folder.rb:37:in `block (2 levels) in persist_mount_shared_folder'
	  2: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:111:in `capability'
	  1: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:111:in `call'
/Users/dgriffiths/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.2.0/lib/vagrant-parallels/cap/mount_options.rb:33:in `mount_name': wrong number of arguments (given 3, expected 2) (ArgumentError)
```

**Comment by m-emelchenkov** [comment] 2021-04-18 09:25
Mount problem reminds me this bug: https://github.com/hashicorp/vagrant/issues/12277

**Comment by evertiro** [comment] 2021-04-19 23:50
All right, @benlumia007 figured the permissions issue on our end. For anyone else who makes it this far trying to figure out Vagrant permissions issues with Parallels, adding `mount_options: [ 'share' ]` fixes them.

This means that the [rueian/ubuntu20-m1](https://app.vagrantup.com/rueian/boxes/ubuntu20-m1) box is a workable solution until we can get an official bento release for M1. I'm still more than happy to help work through the issues here if anyone can point me in the right direction.

**Comment by SwampDragons** [comment] 2021-04-21 15:46
We added this support in release 1.7.2; it sounds like the remaining issues are bento-specific, so I'm going to close this, but if you think this is wrong and this is actually a Packer issue we can reopen and debug together.

**Comment by evertiro** [comment] 2021-04-21 16:21
> We added this support in release 1.7.2; it sounds like the remaining issues are bento-specific, so I'm going to close this, but if you think this is wrong and this is actually a Packer issue we can reopen and debug together.

As far as I can tell, the problem is with Packer. That's why I reopened this in the first place. All known issues on the VVV/Parallels fronts have been resolved. The bento image should work, the same steps run manually work, but one of the Packer dependencies is the being pulled in for the wrong architecture.

**Comment by evertiro** [comment] 2021-04-21 16:21
@SwampDragons It seems that I don't have permissions to actually re-open?

**Closed** 2021-09-16 20:33 UTC
Labels: enhancement, help wanted, track-internal
