### ISSUE TITLE
vmware-vmx does not detect vmplayer version and refuses to clone #972

### ISSUE THREAD

**Issue by rupamkhaitan** [hashicorp/packer#9044] opened 2020-04-10 19:32 UTC
user@ubuntu:~/code/$ vmware-installer -l
Product Name         Product Version
==================== ====================
vmware-player        14.1.1.7528167
vmware-vix           1.17.0.6661328

Packer v1.5.5

#### Overview of the Issue
vmware-vmx option complains about the vmware player

### Operating system and Environment details

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

### Log Fragments and crash.log files

https://gist.github.com/rupamkhaitan/ab1d5e28a7596ea266e4c5337a38ec57

**Comment by nywilken** [comment] 2020-04-14 18:37
Hi @rupamkhaitan thanks for reaching out. It looks like the Driver 6 check is failing before it has a chance to check the actual version of the vmplayer. Can you please provide a redacted build configuration template for reproducing the problem please.

In the meantime, I just pushed up a small PR that has an extra bit of logging that might help point out what the issue might be https://github.com/hashicorp/packer/pull/9064. You can download some test binaries at https://app.circleci.com/pipelines/github/hashicorp/packer/4596/workflows/c3916256-4f55-48a3-9560-eaef6a284f5c/jobs/45508/artifacts

**Comment by rupamkhaitan** [comment] 2020-04-14 21:20
I have downloaded the dev build and using that i ran with PACKER_LOG=1

2020/04/14 16:17:29 [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-builder-vmware-vmx"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-builder-vmware-vmx"}
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin507282454
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin507282454
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-shell"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-shell"}
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin852645418
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin852645418
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-salt-masterless"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-salt-masterless"}
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin953499547
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin953499547
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-file"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-file"}
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin549909686
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin549909686
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-file"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-file"}
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin941956089
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin941956089
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-file"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-file"}
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin193616502
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin193616502
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-file"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-file"}
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin957084257
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin957084257
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Creating plugin client for path: /tmp/packer_linux_amd64
2020/04/14 16:17:29 Starting plugin: /tmp/packer_linux_amd64 []string{"/tmp/packer_linux_amd64", "plugin", "packer-provisioner-shell"}
2020/04/14 16:17:29 Waiting for RPC address for: /tmp/packer_linux_amd64
2020/04/14 16:17:29 packer_linux_amd64 plugin: [INFO] Packer version: 1.5.6-dev (d865bef2034e1cc536a9103624dc2e2b400a87ce) [go1.13.10 linux amd64]
2020/04/14 16:17:29 packer_linux_amd64 plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 16:17:29 packer_linux_amd64 plugin: Attempting to open config file: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: [WARN] Config file doesn't exist: /home/ubuntu/.packerconfig
2020/04/14 16:17:29 packer_linux_amd64 plugin: Setting cache directory: /home/ubuntu/code/cnssops/packer/packer_cache
2020/04/14 16:17:29 packer_linux_amd64 plugin: args: []string{"packer-provisioner-shell"}
2020/04/14 16:17:29 packer_linux_amd64 plugin: Plugin address: unix /tmp/packer-plugin044185971
2020/04/14 16:17:29 Received unix RPC address for /tmp/packer_linux_amd64: addr is /tmp/packer-plugin044185971
2020/04/14 16:17:29 packer_linux_amd64 plugin: Waiting for connection...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Serving a plugin connection...
2020/04/14 16:17:29 Build debug mode: false
2020/04/14 16:17:29 Force build: false
2020/04/14 16:17:29 On error: 
2020/04/14 16:17:29 Preparing build: vmware-vmx
vmware-vmx: output will be in this color.

2020/04/14 16:17:29 Waiting on builds to complete...
2020/04/14 16:17:29 Starting build run: vmware-vmx
2020/04/14 16:17:29 Running builder: vmware-vmx
2020/04/14 16:17:29 [INFO] (telemetry) Starting builder vmware-vmx
2020/04/14 16:17:29 packer_linux_amd64 plugin: Testing against vmware driver *common.Workstation10Driver, Success: false
2020/04/14 16:17:29 packer_linux_amd64 plugin: skipping *common.Workstation10Driver because it failed with the following error exec: "vmware": executable file not found in $PATH
2020/04/14 16:17:29 packer_linux_amd64 plugin: Testing against vmware driver *common.Workstation9Driver, Success: false
2020/04/14 16:17:29 packer_linux_amd64 plugin: skipping *common.Workstation9Driver because it failed with the following error exec: "vmware": executable file not found in $PATH
2020/04/14 16:17:29 packer_linux_amd64 plugin: VMware app path: /usr/bin/vmplayer
2020/04/14 16:17:29 packer_linux_amd64 plugin: vmrun path: /usr/bin/vmrun
2020/04/14 16:17:29 packer_linux_amd64 plugin: vdisk-manager path:
2020/04/14 16:17:29 packer_linux_amd64 plugin: qemu-img path: /usr/bin/qemu-img
2020/04/14 16:17:29 packer_linux_amd64 plugin: Testing against vmware driver *common.Player6Driver, Success: false
2020/04/14 16:17:29 packer_linux_amd64 plugin: skipping *common.Player6Driver because it failed with the following error Could not find VMWare Player version in output:
2020/04/14 16:17:29 packer_linux_amd64 plugin: VMware Workstation Information:
2020/04/14 16:17:29 packer_linux_amd64 plugin: VMware Workstation 14.1.1 build-7528167 Release
2020/04/14 16:17:29 packer_linux_amd64 plugin: 
2020/04/14 16:17:29 packer_linux_amd64 plugin: VMware app path: /usr/bin/vmplayer
2020/04/14 16:17:29 packer_linux_amd64 plugin: vmrun path: /usr/bin/vmrun
2020/04/14 16:17:29 packer_linux_amd64 plugin: vdisk-manager path:
2020/04/14 16:17:29 packer_linux_amd64 plugin: qemu-img path: /usr/bin/qemu-img
2020/04/14 16:17:29 packer_linux_amd64 plugin: Testing against vmware driver *common.Player5Driver, Success: true
2020/04/14 16:17:29 packer_linux_amd64 plugin: No floppy files specified. Floppy disk will not be made.
==> vmware-vmx: Cloning source VM...
2020/04/14 16:17:29 packer_linux_amd64 plugin: Cloning from: /tmp/noc_2.4.0-r1/on-premises_2.4.0-r1_amd64.vmx
2020/04/14 16:17:29 packer_linux_amd64 plugin: Cloning to: /tmp/noc_2.4.0-r1/vmx/on-premises_2.4.0-r1_amd64.vmx
==> vmware-vmx: Deleting output directory...
2020/04/14 16:17:29 [INFO] (telemetry) ending vmware-vmx
Build 'vmware-vmx' errored: Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater.

2020/04/14 16:17:29 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/04/14 16:17:29 machine readable: vmware-vmx,error []string{"Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater."}
==> Some builds didn't complete successfully and had errors:
==> Builds finished but no artifacts were created.
--> vmware-vmx: Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater.

==> Builds finished but no artifacts were created.
2020/04/14 16:17:29 [INFO] (telemetry) Finalizing.
2020/04/14 16:17:29 waiting for all plugin processes to complete...
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited
2020/04/14 16:17:29 /tmp/packer_linux_amd64: plugin process exited

**Comment by nywilken** [comment] 2020-04-14 22:07
This is great thanks for trying out the dev build. Looking at the logs I see Packer Is having issues extracting the version information. 

```
skipping *common.Player6Driver because it failed with the following error Could not find VMWare Player version in output:
```

What information do you get when you run `/use/bin/vmplayer -v`?

**Comment by rupamkhaitan** [comment] 2020-04-14 23:12
`$ /usr/bin/vmplayer -v

(vmplayer:66148): Gtk-WARNING **: cannot open display:`

But when i run

`vmware-installer -l
Product Name         Product Version
==================== ====================
vmware-player        14.1.1.7528167
vmware-vix           1.17.0.6661328`

**Comment by nywilken** [comment] 2020-04-15 10:40
> `$ /usr/bin/vmplayer -v`
> `(vmplayer:66148): Gtk-WARNING **: cannot open display:`
> 
Ah okay, this is the issue. Packer expects to see a valid version string for vmplayer. Since it can't find a valid version it defaults to using the older version 5 driver which does not support cloning. Please ensure vmplayer is functioning properly before you try running the build again. Your output should something like the following

```
⇶  /usr/bin/vmplayer -v 
VMware Player 15.5.0 build-14665864
```

Are you running your Packer builds and vmware as root? 

The error (`(vmplayer:66148): Gtk-WARNING **: cannot open display:`) when calling `/usr/bin/vmplayer -v` occurs when you try to execute the command as the root user. If you are using the root user please try running your builds as a non-root user. 

Seeing as this is not an issue with Packer I am going to remove the bug label and mark it as a question for now.

**Comment by rupamkhaitan** [comment] 2020-04-15 14:51
On the same machine I use `vmware-iso` builder option and it works fine 

So here is my steps

Initially we were using only **vmware-iso** builder to generate vmx and then were running our custom script to convert vmx to ova (using ovftool)

But during the vmware-iso in the salt provisioner step if the salt state fails for bad code we had to start from fresh by loading the iso again from stratch.

So i thought instead of keeping one single template vmware-iso, I broke that into two template
the first vmware-iso does very basic takes the raw ubuntu iso and downloads latest kernel and outputs a vmx_file

Now next packe build with builder vmware-vmx will use the above vmx_file (this will have only salt provisioner to run highstate) and thats where it fails complaining about vmplayer version.

So my question is does vmware-iso doesnt look for vmplayer version?

**Comment by rupamkhaitan** [comment] 2020-04-15 15:05
If i login to my ubuntu machine where i am running vmware-vmx it displays the version clearly
VMware Player 14.1.1 build-7528167

Only when i ssh from outside it doesnt display so the old post you can ignore.. i am running packer from inside the box

**Comment by nywilken** [comment] 2020-04-15 17:57
Thanks for the quick response @rupamkhaitan I'm having a hard time following with out a build configuration and clear reproducible steps. But I will say that chaining builds is a good strategy for your use case. As to your question "does vmware-iso doesnt look for vmplayer version?" Yes, they both check the version if you run the `vmware-iso` build with the debug logs you should be able to see what driver version it is using. The vmware-iso builder does not execute the clone operation so you will not get the "cloning requires a version 6 or greater error". 

> Only when i ssh from outside it doesnt display so the old post you can ignore.. i am running packer from inside the box

Okay, just in case, if you try to run the build via an ssh session then you will also need to set up the proper display settings via X forwarding.  

I'm going to close this issue as I don't suspect it to be an issue with Packer but more an issue with the vmware system configuration.

 If you end up needing more help with this kind of initial configuration, the mailing list or community forum are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

Cheers!

**Closed by nywilken** 2020-04-15 17:57 UTC
Labels: builder/vmware, question
