### ISSUE TITLE
ResourceNotReady: failed waiting for successful resource state

### ISSUE THREAD

**Issue by rephric** [hashicorp/packer#7954] opened 2019-08-06 21:05 UTC
Hello,
I have tried Packer version 1.3, 1.4, 1.4.1, 1.4.2, and the current nightly build.
Unfortunately, I am still running into the same error I have reported before.

`
==> ami: Copying/Encrypting AMI (ami-) to other regions...
    ami: Copying to: us-east-1
    ami: Waiting for all copies to complete...
==> ami: 1 error(s) occurred:
==> ami: 
==> ami: * Error waiting for AMI (ami-) in region (us-east-1): ResourceNotReady: failed waiting for successful resource state
`
I have set these variables prior to running the packer build.

- export AWS_POLL_DELAY_SECONDS=30
- export AWS_MAX_ATTEMPTS=3000
- export AWS_TIMEOUT_SECONDS=3000
- export TMPDIR=/home/$USER/tmp

And I ensured my user has kms:* permissions and I am using the right KMS key ID and not the ARN.

Any help would be much appreciated.

**Comment by rickard-von-essen** [comment] 2019-08-06 21:36
Does the AMI ever show up in us-east-1? Or is there any error message in
the copy job?

**Comment by rephric** [comment] 2019-08-06 21:50
The AMI does show up in us-east-1. When it fails it actually registers in the AWS frontend with the status as failed and it does not have the right name. Is this a known issue?

**Comment by asherkhb** [comment] 2019-08-08 17:18
I was running into the same problem, and it ended up being due to a combination of 1) needing to use the ARN since it was copying across accounts and 2) requiring kms:CreateGrant permissions

**Comment by vvucetic** [comment] 2019-08-14 18:30
We started seeing this problem today on configuration that hasn’t been touched for months and we were using it every couple of days.

**Comment by SwampDragons** [comment] 2019-08-14 19:28
@vvucetic that sounds a lot like your kms key just expired.

**Comment by vvucetic** [comment] 2019-08-14 21:00
> @vvucetic that sounds a lot like your kms key just expired.

But I’m not copying encrypted AMI. I don’t think KMS key is in use at all here.

**Comment by vvucetic** [comment] 2019-08-15 08:05
So, today it went fine. Copying to 3 regions took 10m, while yesterday was running out of attempts after 30m. I'm closing my case as AWS performance related issue. Thanks for help!

**Comment by SwampDragons** [comment] 2019-09-27 20:23
I think in order to keep this issue open and investigate further we need an example of a Packer template that you're having trouble with; we need the simplest possible template that reproduces the issue, so that I can narrow it down to specific kinds of region copies, or copies across users, or whatever. Obviously you can remove any credentials and I'll generate my own to try to replicate. If you can provide that I'll try to take a closer look at this issue.

**Comment by vvucetic** [comment] 2019-10-01 08:03
> I think in order to keep this issue open and investigate further we need an example of a Packer template that you're having trouble with; we need the simplest possible template that reproduces the issue, so that I can narrow it down to specific kinds of region copies, or copies across users, or whatever. Obviously you can remove any credentials and I'll generate my own to try to replicate. If you can provide that I'll try to take a closer look at this issue.

In my case the problem went away the next day so I assume it was due to performance issues on AWS side that day.

**Comment by SwampDragons** [comment] 2019-10-01 16:38
👍 Thanks @vvucetic. I'll leave open another week or so to give the OP a chance to update the ticket, then I'll close and assume they, too, had a transient server-side error.

**Closed** 2019-10-17 23:35 UTC
Labels: bug, builder/amazon
