### ISSUE TITLE
VNC viewer not launching alongside qemu builds

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7441] opened 2019-03-28 00:22 UTC
Hi, I am used to packer showing a helpful GUI monitor during builds, which really assists well with debugging. This happens for VirtualBox and VMware builds, for example. And in the past, I would watch the VNC viewer come up for qemu builds as well.

However, on my new Ubuntu host, I noticed that packer is not launching a VNC viewer for qemu anymore. Packer's flags to qemu are correctly creating a VNC server port; I can manually connect with Remmina, for example. But I want packer to launch it for me!

Say, is there a configuration key in the packer JSON for specifying the VNC viewer command? I wonder if packer is just not aware that Remmina is a VNC application.

Using Packer 1.4.0 on Ubuntu 18.10 Cosmic Cuttlefish on System76 Galaga Pro.

**Comment by rickard-von-essen** [comment] 2019-03-28 08:33
Packer never launched a VNC viewer for you. But if you have qemu with SDL support and `headless: false` it will launch a _display_.

**Comment by rickard-von-essen** [comment] 2019-03-28 08:34
Please supply the information requested in the issue template:
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by nywilken** [comment] 2020-05-05 15:41
Hi there, I'm going to close this issue since there hasn't been any activity on it. If you are still running into issues please try running against the latest Packer release v1.5.6 as there have been a few changes to the qemu builder before opening a new bug report with the requested template information. Thanks!

**Closed by nywilken** 2020-05-05 15:41 UTC
Labels: builder/qemu, community-supported plugin, question
