### ISSUE TITLE
Packer + Ansible + Windows: Script modules not working

### ISSUE THREAD

**Issue by rickhlx** [hashicorp/packer#5327] opened 2017-09-11 20:19 UTC
Packer version: 1.0.4
Ubuntu 16.04

Script module is being ran with command starting with '&'. The command is not being ran from PowerShell so command fails with `& was unexpected at this time`

```
 amazon-ebs: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=34986 -o 'IdentityFile="/tmp/ansible-key233736332"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ricardo -o ConnectTimeout=10 -o ControlPath=/home/ricardo/.ansible/cp/7f110993c8 -tt 127.0.0.1
 '&  '"'"'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1505160219.56-220966551686553\Add_Default_IIS_Headers.ps1'"'"' '

    amazon-ebs: <127.0.0.1> (1, '', '& was unexpected at this time.\r\nShared connection to 127.0.0.1 closed.\r\n')
```

**Comment by SwampDragons** [comment] 2017-09-11 21:37
Thanks for submitting the issue!  So that I can replicate efficiently, can you please provide me with:

- Debug log output from `PACKER_LOG=1 packer build template.json`. (the logs of the WHOLE run in a gist)
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by rickhlx** [comment] 2017-09-12 14:31
Here are the requested files. https://gist.github.com/rickhlx/bcdb40ffd68ab743d3173e4e04b44a54

**Comment by mwhooker** [comment] 2017-09-13 21:09
looks related to #5338 which I believe has the cause identified

**Comment by rickhlx** [comment] 2017-09-13 21:15
I don't think this is related. The problem for this specific issue is that the script command is being ran in a windows `cmd shell` while the command was written for a `powershell` the `&` at the beginning is syntax that cannot be used in windows shell only powershell

**Comment by mwhooker** [comment] 2017-09-13 21:16
agreed, deleted my last comment because it was unrelated

is ssh available on your machine? I'm not sure how well tested ansible is over ssh. See https://www.packer.io/docs/provisioners/ansible.html#winrm-communicator for information about running over winrm.

**Comment by rickhlx** [comment] 2017-09-13 21:26
I used the updated plugins here https://github.com/hashicorp/packer/pull/5162.

I'm running these scripts from a linux machine with ansible 2.4 + packer 1.04. When running just ansible the scripts and playbooks work fine. Only breaks when using packer. 

As you pointed out @mwhooker, I suspect it's the proxying of winrm through ssh that breaks this, since winrm uses powershell ansible must default to "regular" shell when going through ssh which would be `cmd`

**Comment by mwhooker** [comment] 2017-09-13 21:29
so sounds like #5162 isn't ready yet

**Comment by rickhlx** [comment] 2017-09-13 21:30
Not sure, all the other modules seem to work fine, it's just the `script` ansible module that's acting up.

**Comment by mwhooker** [comment] 2017-09-13 21:36
If this bug isn't reproducible against master, let's close it, especially if it works with the winrm proxy. A better bet would be to record your experience on the PR that you're using.

**Comment by SwampDragons** [comment] 2017-09-27 16:57
Okay yeah reading through this description more, it sounds like you're trying to do something that is unsupported in _ansible_, not in packer.  Going to close, but if you think we've misunderstood feel free to reopen with more detail.

**Closed by SwampDragons** 2017-09-27 16:57 UTC
Labels: bug, provisioner/ansible-remote, windows-guest
