### ISSUE TITLE
packer execution failed while destroying the VM

### ISSUE THREAD

**Issue by vinodhkumart** [hashicorp/packer#10616] opened 2021-02-11 19:16 UTC
Hi , 

I am executing a build with packer and it executes successfully. But when it destroys the vm ,it is failed with below error and whole build was getting failed due to this.. Could someone let me know what causing this.

==> vsphere-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vsphere-iso: Clear boot order...
==> vsphere-iso: Power off VM...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored after 27 minutes 41 seconds: Cannot shut down VM: ServerFaultCode: Cannot complete operation because VMware Tools is not running in this virtual machine.

**Comment by sylviamoss** [comment] 2021-02-12 10:27
Hello! Because of the first line of the logs you shared, I'm not quite sure Packer executed successfully. 
`==> vsphere-iso: Provisioning step had errors: Running the cleanup provisioner, if present...`
The error happened before destroying the VM.

**Comment by SwampDragons** [comment] 2021-02-17 22:28
I'm closing since we don't have the details we need to reproduce. If this is still a problem and Moss's comment wasn't enough, please share the smallest possible Packer template needed to reproduce and we can take a look.

**Closed by SwampDragons** 2021-02-17 22:28 UTC
Labels: builder/vsphere, waiting-reply
