### ISSUE TITLE
VirtualBox: failed to unlock port lockfile: close tcp 127.0.0.1:2861: use of closed network connection

### ISSUE THREAD

**Issue by boeboe** [hashicorp/packer#8641] opened 2020-01-22 20:40 UTC
Packer version: 1.5.1
VirtualBox version: 6.0.15r135660
OS: macOS v10.14.6

Packer traces:

    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] handshake complete!
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] Opening new ssh session
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [INFO] agent forwarding enabled
    ==> BIGIP-14.0.0.5-0.0.3: Connected to SSH!
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: VBoxManage --version output: 6.0.15r135660
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: VirtualBox version: 6.0.15
    ==> BIGIP-14.0.0.5-0.0.3: Uploading VirtualBox version info (6.0.15)
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] Opening new ssh session
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] Starting remote scp process:  scp -vt .
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] Started SCP session, beginning transfers...
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] Copying input data into temporary file so we can read the length
    2020/01/22 21:34:32 packer_darwin_amd64 plugin: [DEBUG] scp: Uploading .vbox_version: perms=C0644 size=6
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: Executing VBoxManage: []string{"controlvm", "BIGIP-14.0.0.5-0.0.3", "poweroff"}
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: stdout:
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: failed to unlock port lockfile: close tcp 127.0.0.1:2861: use of closed network connection
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5924: use of closed network connection
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: Executing VBoxManage: []string{"storageattach", "BIGIP-14.0.0.5-0.0.3", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: stdout:
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: stderr:
    ==> BIGIP-14.0.0.5-0.0.3: Deregistering and deleting VM...
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: Executing VBoxManage: []string{"unregistervm", "BIGIP-14.0.0.5-0.0.3", "--delete"}
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: stdout:
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: stderr: VBoxManage: error: Cannot unregister the machine 'BIGIP-14.0.0.5-0.0.3' while it is locked
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: Retryable error: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'BIGIP-14.0.0.5-0.0.3' while it is locked
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
    2020/01/22 21:34:33 packer_darwin_amd64 plugin: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
    2020/01/22 21:36:33 packer_darwin_amd64 plugin: Executing VBoxManage: []string{"unregistervm", "BIGIP-14.0.0.5-0.0.3", "--delete"}
    2020/01/22 21:36:34 packer_darwin_amd64 plugin: stdout:
    2020/01/22 21:36:34 packer_darwin_amd64 plugin: stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    ==> BIGIP-14.0.0.5-0.0.3: Deleting output directory...
    2020/01/22 21:36:34 [INFO] (telemetry) ending virtualbox-iso
    2020/01/22 21:36:34 machine readable: error-count []string{"1"}
    ==> Some builds didn't complete successfully and had errors:
    2020/01/22 21:36:34 machine readable: BIGIP-14.0.0.5-0.0.3,error []string{"Error uploading VirtualBox version: elative addresses not allowed"}
    ==> Builds finished but no artifacts were created.
    Build 'BIGIP-14.0.0.5-0.0.3' errored: Error uploading VirtualBox version: elative addresses not allowed

    2020/01/22 21:36:34 [INFO] (telemetry) Finalizing.
    ==> Some builds didn't complete successfully and had errors:
    --> BIGIP-14.0.0.5-0.0.3: Error uploading VirtualBox version: elative addresses not allowed

    ==> Builds finished but no artifacts were created.
    2020/01/22 21:36:34 waiting for all plugin processes to complete...
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited
    2020/01/22 21:36:34 /Users/vanbos/Desktop/packer_darwin_amd64: plugin process exited

Packer.json file:

    {
      "variables": {
        "F5_NAME": "BIGIP-14.0.0.5-0.0.3"
      },
      "builders": [
        {
          "name": "{{ user `F5_NAME` }}",
          "type": "virtualbox-iso",
          "format": "ovf",
          "iso_url": "software/{{ user `F5_NAME` }}.iso",
          "iso_checksum": "88a2bbf0c5e31f1985f0aec5e11ebd0a",
          "iso_checksum_type": "md5",
          "ssh_username": "root",
          "ssh_password": "vagrant",
          "ssh_timeout": "30000s",
          "ssh_handshake_attempts": "1000",
          "ssh_keep_alive_interval": "10s",
          "headless": "false",
          "shutdown_command": "shutdown -h now",
          "guest_additions_mode": "disable",
          "guest_os_type": "Linux_64",
          "vm_name": "{{ user `F5_NAME` }}",
          "boot_wait": "60s",
          "boot_command": [
            "<enter><wait5>",
            "<enter><wait5>",
            "<enter>"
          ],
          "cpus":  "2",
          "disk_size": "160000",
          "memory": "4096",
          "vboxmanage": [
            ["modifyvm","{{.Name}}","--memory","8192"],
            ["modifyvm","{{.Name}}","--cpus","4"],
            ["modifyvm","{{.Name}}","--nic1","NAT"],
            ["modifyvm","{{.Name}}","--boot1","disk"]
          ]
        }
      ],
      "post-processors": [
        {
          "type": "vagrant",
          "compression_level": 9,
          "output": "{{ build_name }}-virtualbox.box"
        }
      ],
      "provisioners": [
        {
          "type": "shell",
          "inline": [
            "mkdir /shared/vagrant",
            "exit 0"
          ],
          "pause_before": "60s"
        },
        {
          "type": "file",
          "source": "files",
          "destination": "/shared/vagrant"
        },
        {
          "type": "shell",
          "scripts": [
            "scripts/filesystem-rw.sh",
            "scripts/sudo.sh"
          ]
        },
        {
          "type": "shell",
          "inline": [
            "tmsh modify /sys db users.strictpasswords value disable",
            "exit 0"
          ]
        },
        {
          "type": "shell",
          "inline": [
            "tmsh save /sys config",
            "exit 0"
          ]
        },
        {
          "type": "shell",
          "inline": [
            "tmsh create auth user vagrant password vagrant partition-access add { all-partitions { role admin } } shell bash",
            "exit 0"
          ]
        },
        {
          "type": "shell",
          "scripts": [
            "scripts/vagrant.sh"
          ]
        },
        {
          "type": "shell",
          "inline": [
            "tmsh save /sys config",
            "exit 0"
          ]
        },
        {
          "type": "shell",
          "scripts": [
            "scripts/cleanup.sh",
            "scripts/wait-for-bigip.sh"
          ],
          "start_retry_timeout": "30m",
          "pause_before": "120s"
        }
      ]
    }

packer_cache after crash:

    # tree packer_cache
    packer_cache
    ├── a050868ece85c5b3a04c1ccbe7ade7d05bb01c29.iso -> /Users/vanbos/Documents/Git/f5/f5-packer-templates/bigip-14.0.0-x86_64-box/software/BIGIP-14.0.0.5-0.0.3.iso
    ├── a050868ece85c5b3a04c1ccbe7ade7d05bb01c29.iso.lock
    └── port
        ├── 2861
        ├── 3297
        ├── 5908
        └── 5924

**Comment by nywilken** [comment] 2020-01-22 21:56
Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by nywilken** [comment] 2020-01-22 22:01
Possibly related #8637

**Comment by SwampDragons** [comment] 2020-01-23 23:02
Yes, I think the closed port error is a red herring, and that this is a duplicate of #8637.

**Comment by sylviamoss** [comment] 2020-01-31 16:00
I'm closing this issue because this seems to be a duplicate of https://github.com/hashicorp/packer/issues/8637 we can see the same error in the logs 
```
 errored: Error uploading VirtualBox version: elative addresses not allowed
```
We can reopen it later otherwise.

**Closed by sylviamoss** 2020-01-31 16:00 UTC
Labels: bug, builder/virtualbox
