### ISSUE TITLE
Need to escape # character as part of builder.iso_url for hyperv packer

### ISSUE THREAD

**Issue by MagNgo** [hashicorp/packer#11995] opened 2022-09-14 23:00 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

When using hyper v packer to build a windows image, if the builder.iso_url path contains a #, the path cuts short and causes a failure as the .iso file cannot be found.

#### Reproduction Steps

Run hyperv packer using a builder.iso_url path that contains a # key somewhere.
If the # character is anywhere in the full path this will cause an issue, even if the relative path provided does not contain a the # character.

### Packer version

1.7.10

### Simplified Packer Template

  "builders": [
    {
      "communicator": "winrm",
      "configuration_version": "9.0",
      "cpus": "4",
      "disk_size": "61440",
      "enable_dynamic_memory": true,
      "enable_mac_spoofing": false,
      "enable_secure_boot": true,
      "enable_virtualization_extensions": false,
      "generation": 2,
      "guest_additions_mode": "none",
      "headless": true,
      "memory": "4096",
      "shutdown_command": "e:/shutdown-audit.bat",
      "shutdown_timeout": "30m",
      "vm_name": "Packer-f9053a47-9320-4622-89bc-adf5349c0dc3",
      "winrm_password": "!",
      "winrm_timeout": "1h",
      "winrm_username": "administrator",
      "output_directory": ".\\HyperV\\Output",
      "type": "hyperv-iso",
      "iso_checksum": "none",
      "iso_url": ".\\WIM\\Output \\packer#.iso"
    }
  ],

### Operating system and Environment details

Windows 11 Test environment

### Log Fragments and crash.log files

==> hyperv-iso: Download failed source path error: CreateFile C:/Users/Admin1/Desktop/testImage/2022-09-07T16_20_09.367-07_00/Build/WIM/Output/packer: The system cannot find the path specified.
==> hyperv-iso: error downloading ISO: [source path error: CreateFile C:/Users/Admin1/Desktop/testImage/2022-09-07T16_20_09.367-07_00/Build/WIM/Output/packer: The system cannot find the path specified.]
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored after 803 milliseconds 867 microseconds: error downloading ISO: [source path error: CreateFile C:/Users/Admin1/Desktop/testImage/2022-09-07T16_20_09.367-07_00/Build/WIM/Output/packer: The system cannot find the path specified.]

**Comment by lbajolet-hashicorp** [comment] 2022-09-29 18:44
Hi @MagNgo,

Regarding your problem, this is an expected behaviour of the URLs, the `#` character is used to specify that what follows is the fragment identifier part of the URL (as described in RFC 2396), which is not part of the URL itself, but is generally used for anchors.
The Go stdlib's url parsing function trims voluntarily the URL at that point, which is the cause of the behaviour you're experiencing.

Now, to fix your problem, there are two ways:

1. Remove the `#` from the URI: this is the obvious solution here, and if you it's a possibility, I would suggest doing this, it's the easiest fix you can apply to get the code to behave as you would expect.

2. URL-encode the problematic character: since the `iso_url` is a valid URL, you may URL-encode the `#` with `%23`, which will explicitely not be considered a separator between the base URL and the eventual fragment identifier. If you can't rename the ISO, this would be the next best thing to try.

Hopefully these suggestions will help you fix your issue!

Thanks for submitting this issue.

**Comment by nywilken** [comment] 2022-10-19 00:34
@MagNgo it looks like @lbajolet-hashicorp provided a few suggestions to resolve your reported issue. The handling of `#` in file URLs are behaving as expected. So I am going to close this issue. If you find that you are still running into issues after making the suggested changes drop a comment on the issue and we will gladly review. Cheers!

**Closed by nywilken** 2022-10-19 00:34 UTC
Labels: invalid
