### ISSUE TITLE
Packer with Vagrant ssh error

### ISSUE THREAD

**Issue by ralucas** [hashicorp/packer#8853] opened 2020-03-08 19:15 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
Cannot get packer to create vagrant machine

#### Reproduction Steps
Run `packer build basic.json`

### Packer version
1.5.4

### Simplified Packer Buildfile
```
{
    "builders": [{
        "communicator": "ssh",
        "source_path": "hashicorp/precise64",
        "provider": "virtualbox",
        "add_force": true,
        "type": "vagrant"
    }],
    "provisioners": [{
        "type": "shell",
        "inline": [
            "echo working"
        ]
    }]
}
```

### Operating system and Environment details
MacOSX, Vagrant 2.2.4

### Log Fragments and crash.log files
```
==> vagrant: Waiting for SSH to become available...
2020/03/08 13:14:29 packer-builder-vagrant plugin: [INFO] Attempting SSH connection to 127.0.0.1:2222...
2020/03/08 13:14:29 packer-builder-vagrant plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/03/08 13:14:29 packer-builder-vagrant plugin: [DEBUG] handshaking with SSH
2020/03/08 13:14:29 packer-builder-vagrant plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
2020/03/08 13:14:29 packer-builder-vagrant plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
==> vagrant: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
==> vagrant: destroying Vagrant box...
```

**Comment by sylviamoss** [comment] 2020-03-09 10:36
Hello there, thanks for reaching out! 
This seems to be the same issue as https://github.com/hashicorp/packer/issues/8818 which was fixed by https://github.com/hashicorp/packer/pull/8826

To be sure, you can use these binaries https://circleci.com/gh/hashicorp/packer/36144#artifacts/containers/0 to test the solution. Let us know if it works for you so we can close this issue.

**Comment by sylviamoss** [comment] 2020-03-17 17:25
I've tested locally with and without the #8826 changes and I can confirm it was fixed. I'm closing this one. 
Feel free to make us any question :)

**Closed by sylviamoss** 2020-03-17 17:25 UTC
Labels: bug, builder/vagrant, communicator/ssh
