### ISSUE TITLE
[vmware-vmx] vm_name setting gets ignored

### ISSUE THREAD

**Issue by 7085** [hashicorp/packer#7026] opened 2018-11-20 13:07 UTC
When using the `vmware-vmx` builder and using a vm image that was built by a `vmware-iso` builder before, the `vm_name` option in the `vmware-vmx` builder gets ignored. The `displayname` in the resulting .vmx file will become `Clone of {{vm_name_in_vmware-iso_builder}}` .

As a workaround I am currently additionally setting the `displayname` via the `vmx_data` setting to get the correct name in the `vmware-vmx` builder.

Since there is an option of `vm_name` on the documentation page for the  `vmware-vmx` builder I thought this would be the correct option to set the name there like it is the case for the `vmware-iso` builder.

The builders are not located in the same packer.json file but have separate json files and are built one after another.

I have seen that there is a commit which seems to adress some similar things so this might be solved already?
https://github.com/hashicorp/packer/commit/68c9e34bfeb96e29f25cffac99c0e68e9e8e2a7e#diff-edcb5e1e47607c9371b9c97e47850f00
Since this introduces a new property for setting the `displayname` instead of using the `vm_name` I opened this issue.
If this is the intended behavior of not using the `vm_name` in the `vmware-vmx` builder I think this should be clarified somewhere in the docs.

Packer version: Packer v1.3.2
Host platform: Windows 10

**Comment by SwampDragons** [comment] 2018-11-20 17:03
I believe this is the intended behavior. The `vm_name` only describes the name for the output file; it's probably not a well-named option, but it's unfortunately going to have to stay how it is for backwards-compatibility.

Currently our docs for this option read 

```
vm_name (string) - This is the name of the VMX file for the new virtual machine, without the file extension. By default this is packer-BUILDNAME, where "BUILDNAME" is the name of the build.
```

but it sounds like this isn't clear enough; do you have a recommendation for a better way to document this behavior?

**Comment by 7085** [comment] 2018-11-21 07:33
I expected this to be consistent, when the `displayname` is set to the `vm_name` in `vmware-iso` builder that it would be also set to the `vm_name` in the "derived" `vmware-vmx` builder.

Since there will be a separate `displayname` in the future this might be more clear.

Otherwise I would suggest a note that the actual name of the VM is controlled by the `displayname` property and/or a note that `The vmware-vmx builder will use the displayname of the base VM if it is not explicitly specified via the vmx_data section or the displayname property.`

Thx for clarifying.

**Comment by SwampDragons** [comment] 2018-11-26 23:34
Cool, thanks. I'll make your docs note and then close this.

**Closed** 2018-11-27 10:57 UTC
Labels: builder/vmware, docs
