### ISSUE TITLE
Build 'vmware-iso' errored: Error starting VM: VMware error: Error: The operation was canceled

### ISSUE THREAD

**Issue by basictheprogram** [hashicorp/packer#5754] opened 2018-01-02 00:38 UTC
- Packer version from `packer version`
```shell
$ packer --version
1.1.3
```
- Host platform
```shell
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

$ uname -a
Linux uart 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com

https://gist.github.com/basictheprogram/a2f157ad7fcedfe768f8a374dc614e23

**Comment by SwampDragons** [comment] 2018-01-04 19:14
Thanks for reporting an issue; do you have simple steps to reproduce?  Does this happen every time or only occasionally?

**Comment by basictheprogram** [comment] 2018-01-04 19:17
```yaml
{
  "builders": [
    {
      "boot_wait": "0s",
      "communicator": "winrm",
      "cpu": 2,
      "disk_size": "{{user `disk_size`}}",
      "enable_secure_boot": true,
      "floppy_files": [
        "{{user `autounattend`}}",
        "./scripts/disable-winrm.ps1",
        "./scripts/enable-winrm.ps1",
        "./scripts/microsoft-updates.bat",
        "./scripts/win-updates.ps1"
      ],
      "guest_additions_mode": "disable",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `iso_url`}}",
      "ram_size": 2048,
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "switch_name": "{{user `hyperv_switchname`}}",
      "type": "hyperv-iso",
      "vm_name": "HyperVServer2016",
      "winrm_password": "vagrant",
      "winrm_timeout": "{{user `winrm_timeout`}}",
      "winrm_username": "vagrant"
    },
    {
      "boot_wait": "2m",
      "communicator": "winrm",
      "disk_size": "{{user `disk_size`}}",
      "disk_type_id": "{{user `disk_type_id`}}",
      "floppy_files": [
        "{{user `autounattend`}}",
        "./scripts/disable-winrm.ps1",
        "./scripts/enable-winrm.ps1",
        "./scripts/microsoft-updates.bat",
        "./scripts/win-updates.ps1"
      ],
      "guest_os_type": "windows9srv-64",
      "headless": "{{user `headless`}}",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `iso_url`}}",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "type": "vmware-iso",
      "vmx_data": {
        "RemoteDisplay.vnc.enabled": "false",
        "RemoteDisplay.vnc.port": "5900",
        "memsize": "2048",
        "numvcpus": "2",
        "scsi0.virtualDev": "lsisas1068"
      },
      "vmx_remove_ethernet_interfaces": true,
      "vnc_port_max": 5980,
      "vnc_port_min": 5900,
      "winrm_password": "vagrant",
      "winrm_timeout": "{{user `winrm_timeout`}}",
      "winrm_username": "vagrant"
    },
    {
      "boot_wait": "2m",
      "communicator": "winrm",
      "disk_size": "{{user `disk_size`}}",
      "floppy_files": [
        "{{user `autounattend`}}",
        "./scripts/disable-winrm.ps1",
        "./scripts/enable-winrm.ps1",
        "./scripts/microsoft-updates.bat",
        "./scripts/win-updates.ps1"
      ],
      "guest_additions_mode": "disable",
      "guest_os_type": "Windows2012_64",
      "headless": "{{user `headless`}}",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `iso_url`}}",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "type": "virtualbox-iso",
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "2048"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "2"
        ]
      ],
      "winrm_password": "vagrant",
      "winrm_timeout": "{{user `winrm_timeout`}}",
      "winrm_username": "vagrant"
    }
  ],
  "post-processors": [
    {
      "keep_input_artifact": false,
      "output": "windows_2016_hyperv_{{.Provider}}.box",
      "type": "vagrant",
      "vagrantfile_template": "vagrantfile-windows_2016.template"
    }
  ],
  "provisioners": [
    {
      "scripts": [
        "./scripts/vm-guest-tools.bat",
        "./scripts/enable-rdp.bat"
      ],
      "type": "windows-shell"
    },
    {
      "scripts": [
        "./scripts/debloat-windows.ps1"
      ],
      "type": "powershell"
    },
    {
      "scripts": [
        "./scripts/set-winrm-automatic.bat",
        "./scripts/uac-enable.bat",
        "./scripts/compile-dotnet-assemblies.bat",
        "./scripts/dis-updates.bat",
        "./scripts/compact.bat"
      ],
      "type": "windows-shell"
    }
  ],
  "variables": {
    "autounattend": "./answer_files/2016_hyperv/Autounattend.xml",
    "disk_size": "61440",
    "disk_type_id": "1",
    "headless": "false",
    "iso_checksum": "53e2f01dc4077192a85f60f8d2ffb02189074e19b25f990cbe9eb767328d3fb6",
    "iso_checksum_type": "sha256",
    "iso_url": "http://care.dlservice.microsoft.com/dl/download/8/8/6/886DAAEF-81A7-4418-82D5-07D33B816962/14393.0.161119-1705.RS1_REFRESH_SERVERHYPERCORE_OEM_X64FRE_EN-US.ISO",
    "winrm_timeout": "6h"
  }
}

````

**Comment by arizvisa** [comment] 2018-01-23 22:31
@basictheprogram, I'm doing a little bit of work on the vmware-iso builder. Do you have the `.vmx` for this build available, and what version of VMware Player are you using?

This'd probably be in `output-vmware-iso/WindowsServer2016.vmx` according to your log. If it gets deleted (which'd be surprising because packer has issues w/ cleanup during errors in VMware as a result of a handle leak), you can run packer with the `-on-error=abort` parameter and I think that should leave the file so you can snag it.

That .vmx will be key in reproducing the VMware issue that you're having.

**Comment by basictheprogram** [comment] 2018-01-24 21:44
VMware Workstation 14.1.1 Player for Linux 

$ ls -ld output*
ls: cannot access 'output*': No such file or directory

Attempting a build with the -on-error=abort

**Comment by arizvisa** [comment] 2018-01-25 02:27
Hmm...you're using VMware workstation?

So, the issue is that packer's VMware driver is detecting your VMware instance as VMware player which means you probably have both installed. Is that the case? If you want to avoid rebuilding packer, you can uninstall vmware player and then things should work out.

```
2018/01/01 18:33:23 packer: 2018/01/01 18:33:23 Executing: /usr/bin/vmrun -T player start output-vmware-iso/WindowsServer2016.vmx nogui
...
2018/01/01 18:33:28 packer: 2018/01/01 18:33:28 Executing: /usr/bin/vmrun -T player list
```

I'm pretty certain that's what's causing the issue, but for the sake of completion, can you run `/usr/bin/vmrun -T ws start output-vmware-iso/WindowsServer2016.vmx nogui` instead of the one with `-T player`? If that works then the driver detection on linux can probably be tightened a bit..

**Comment by arizvisa** [comment] 2018-01-25 02:30
Oh duh. Sorry, I failed at reading. I read "VMware Workstation" and read that you were using VMware Workstation and not "VMware Workstation Player"..

**Comment by basictheprogram** [comment] 2018-01-25 02:51
So packer and "Player" are not a supported configuration?

```shell
$ /usr/bin/vmrun -T player start output-vmware-iso/WindowsServer2016.vmx nogui
Error: The operation was canceled
```
```shell
$ /usr/bin/vmrun -T ws start output-vmware-iso/WindowsServer2016.vmx nogui
Error: The operation was canceled
```

**Comment by arizvisa** [comment] 2018-01-25 02:52
Ok. So packer is pretty much doing everything as intended, and so...assuming you're on a box that supports more than 2 cpus, the issue is likely within VMware. Inside the `output-vmware-iso/` directory should be a `vmware.log` file that gives more info.

**Comment by arizvisa** [comment] 2018-01-25 02:55
In response to your comment, nah. They're supported. I just misread your prior comment where you mentioned "VMware Workstation Player" and interpreted that was "VMware Workstation" which is where my statement about that the difference between player and workstation came from.

I'm just never heard anybody refer to VMware player as "VMware Workstation Player". But it's all good..

You can post or review that .log file if you want me to still help tho. That should give insight into why vmrun is throwing that error.

**Comment by basictheprogram** [comment] 2018-01-25 03:00
> In response to your comment, nah. They're supported. I just misread your prior comment where you mentioned "VMware Workstation Player" and interpreted that was "VMware Workstation" which is where my statement about that the difference between player and workstation came from.
> 
> I'm just never heard anybody refer to VMware player as "VMware Workstation Player". But it's all good..
> 
> 

Cut-n-paste from my.vmware.com <http://my.vmware.com/> download area.

> You can post or review that .log file if you want me to still help tho. That should give insight into why vmrun is throwing that error.
> 

2018-01-24T20:55:40.222-06:00| vmx| I125: Msg_Post: Error
2018-01-24T20:55:40.222-06:00| vmx| I125: [msg.cpuid.legacyCPU.nohwmmu.intel] This host does not support "Intel EPT" hardware assisted MMU virtualization.
2018-01-24T20:55:40.222-06:00| vmx| I125: [msg.cpuid.legacyCPU.noRealModeHV] This host does not support virtualizing real mode. The Intel "VMX Unrestricted Guest" feature is necessary to run this virtual machine on an Intel processor.
2018-01-24T20:55:40.222-06:00| vmx| I125: [msg.moduletable.powerOnFailed] Module 'CPUIDEarly' power on failed.
2018-01-24T20:55:40.222-06:00| vmx| I125: [msg.vmx.poweron.failed] Failed to start the virtual machine

Interesting! Virtualbox on the same computer works as expected.



---
Bob Tanner <tanner@real-time.com>           | Phone : 952-943-8700
http://www.real-time.com, Linux, macOS      | Fax   : 952-943-8500
Key fingerprint = F785 DDFC CF94 7CE8 AA87 3A9D 3895 26F1 0DDB E378

**Comment by arizvisa** [comment] 2018-01-25 03:06
So, docs and things suggest that you can specify `monitor.allowLegacyCPU = "true"` in the .vmx (I think there's some packer option that lets you manually add things to your .vmx).

This will drastically hit you performance-wise, as VMware will emulate all privileged instructions that get executed and be forced to use software for doing address translations (MMU), but if you're just building templates with packer you're probably just going to set-it-and-forget it so time shouldn't be too important..

Just make sure that you remove that option before you deploy them so none of your users have to suffer the perf hit. ;)

**Comment by basictheprogram** [comment] 2018-01-25 03:28
Computer is remote, I'll check the BIOS tomorrow to make sure this isn't something I can turn on. If not, look for an appropriate computer. :-)

**Comment by arizvisa** [comment] 2018-01-25 03:31
Apparently you can also downgrade VMware back to 12 as well according to this awesome guy, continuum: https://communities.vmware.com/thread/572961

np.

**Comment by arizvisa** [comment] 2018-06-14 22:30
@swampdragons, this issue looks like it can be closed as it was resolved to being a VMware issue with virtualization on the reporter's system.

**Closed** 2018-06-15 16:05 UTC
Labels: bug, builder/vmware
