### ISSUE TITLE
HyperV builds fail if switch_name has a space in it

### ISSUE THREAD

**Issue by testworksau** [hashicorp/packer#7277] opened 2019-02-05 04:22 UTC
Our HyperV builds are failing in Packer 1.3.4 with the following traceback:

```
[Step 7/8] ==> hyperv-iso: Creating switch 'External LAN' if required...
[Step 7/8] ==> hyperv-iso:     switch 'External LAN' already exists. Will not delete on cleanup...
[Step 7/8] ==> hyperv-iso: Creating virtual machine...
[Step 7/8] ==> hyperv-iso: Error creating virtual machine: PowerShell error: New-VM : Cannot bind parameter 'Generation'. Cannot convert value "LAN" to 
[Step 7/8] ==> hyperv-iso: type "System.Int16". Error: "Input string was not in a correct format."
[Step 7/8] ==> hyperv-iso: At D:\BuildAgent\temp\buildTmp\powershell338582443.ps1:3 char:157
[Step 7/8] ==> hyperv-iso: + ... oryStartupBytes 8589934592 -VHDPath $vhdPath -SwitchName External LAN
[Step 7/8] ==> hyperv-iso: +                                                                       ~~~
[Step 7/8] ==> hyperv-iso:     + CategoryInfo          : InvalidArgument: (:) [New-VM], ParameterBindingE 
[Step 7/8] ==> hyperv-iso:    xception
[Step 7/8] ==> hyperv-iso:     + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.HyperV. 
[Step 7/8] ==> hyperv-iso:    PowerShell.Commands.NewVM
```

The changes in https://github.com/hashicorp/packer/issues/7136 might have caused the issue with our build. We are using a `switch_name` with a space in it:

`"switch_name" : "External LAN",`

Judging by the above traceback, it appears that this string is not being quoted properly in the powershell command, so the switch name is interpreted as two separate parameters.

Our platform is:
- Packer v1.3.4
- Windows x64

**Comment by SwampDragons** [comment] 2019-02-05 05:50
Sorry about this! It's a duplicate of #7259 which has already been closed because it was fixed in #7266.  If you go to issue #7259 you'll find a zipfile of the patched build, which should hold you over until we can release the fix in v 1.3.5 .

**Comment by SwampDragons** [comment] 2019-02-05 05:50
I'll leave this open for now so that the issue is easy to find for other people who've been affected.

**Comment by testworksau** [comment] 2019-02-05 09:17
No worries - I searched on keywords of the trace back but came up short!

**Comment by SwampDragons** [comment] 2019-02-28 18:20
Closing this since the release is tomorrow.

**Closed by SwampDragons** 2019-02-28 18:20 UTC
Labels: builder/hyperv, duplicate, regression
