### ISSUE TITLE
 Elevated privilege for windows server 2016

### ISSUE THREAD

**Issue by aidda** [hashicorp/packer#5166] opened 2017-07-24 16:33 UTC
I want ro run a cookbook with chef-solo porovisioner, but I recieved this error:
```
    amazon-ebs: Ran C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart  /All returned 5
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In c:/windows/temp/local-mode-cache/cache/cookbooks/windows/resources/feature.rb
    amazon-ebs:
    amazon-ebs: 60:       windows_feature_dism new_resource.name do
    amazon-ebs: 61:         action desired_action
    amazon-ebs: 62:         feature_name new_resource.feature_name
    amazon-ebs: 63:         source new_resource.source if new_resource.source
    amazon-ebs: 64:         all new_resource.all
    amazon-ebs: 65:       end
    amazon-ebs: 66:     when :windows_feature_servermanagercmd
    amazon-ebs:
    amazon-ebs: Compiled Resource:
    amazon-ebs: ------------------
    amazon-ebs: # Declared in c:/windows/temp/local-mode-cache/cache/cookbooks/windows/resources/feature.rb:60:in `run_default_provider'
    amazon-ebs:
    amazon-ebs: windows_feature_dism("NetFx3") do
    amazon-ebs: action [:install]
    amazon-ebs: updated true
    amazon-ebs: updated_by_last_action true
    amazon-ebs: default_guard_interpreter :default
    amazon-ebs: declared_type :windows_feature_dism
    amazon-ebs: cookbook_name "ff_dotnet"
    amazon-ebs: feature_name "NetFx3"
    amazon-ebs: all true
    amazon-ebs: end
    amazon-ebs:
    amazon-ebs: System Info:
    amazon-ebs: ------------
    amazon-ebs: chef_version=13.2.20
    amazon-ebs: platform=windows
    amazon-ebs: platform_version=10.0.14393
    amazon-ebs: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
    amazon-ebs: program_name=c:/opscode/chef/bin/chef-solo
    amazon-ebs: executable=c:/opscode/chef/bin/chef-solo
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Error executing action `install` on resource 'windows_feature[NetFx3]'
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
    amazon-ebs: ------------------------------------
    amazon-ebs: windows_feature_dism[NetFx3] (c:/windows/temp/local-mode-cache/cache/cookbooks/windows/resources/feature.rb line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127, 3010], but received '5'
```
which means that, it does not run with elevated privileges. I`m using ec2 builder, I clouldnt define a password, because it will generate password everytime that I run Packer!
So , any suggestion? how can I run the cookbook through chef- solo with elevated privilege?

**Comment by mwhooker** [comment] 2017-07-24 20:34
hi @aidda 

thanks for the report. I would suggest posting this to the mailing list (https://groups.google.com/forum/#!forum/packer-tool), since more users visit there than here, and they might be able to help you better than I can.

**Comment by aidda** [comment] 2017-07-25 13:10
@mwhooker Thanks! I`ll do that

**Comment by jugatsu** [comment] 2017-10-06 13:09
https://github.com/hashicorp/packer/issues/3117

**Comment by SwampDragons** [comment] 2018-12-13 00:43
Closing this as a duplicate of #4661

**Closed by SwampDragons** 2018-12-13 00:43 UTC
Labels: community-supported plugin, duplicate, provisioner/chef, question, windows-guest
