### ISSUE TITLE
Handle reboots between provisioning scripts

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5712] opened 2017-12-16 15:40 UTC
Ideally, most installation steps are performed via provisioning scripts which are very fast to execute. However, some installation steps like loading kernel extensions for VMware tools in darwin guests, require rebooting, which breaks provisioning scripts if the reboot is attempted during provisioning.

As a workaround, I'm running the reboot for darwin VMware tools during `boot_command`, however this results in a much slower build.

**Comment by rickard-von-essen** [comment] 2017-12-16 20:18
There is no problem with rebooting during provisioning.

Just issue a reboot in a shell script with [expect_disconnect](https://www.packer.io/docs/provisioners/shell.html#expect_disconnect) and in the following provisioner use [pause_before](https://www.packer.io/docs/templates/provisioners.html#pausing-before-running) to ensure that it don't start until the reboot have started.

**Comment by SwampDragons** [comment] 2017-12-18 19:13
Closing since it looks like this was more of a question than an issue -- Please reopen with steps to reproduce if `expect_disconnect=true` does not solve your issue.

**Closed by SwampDragons** 2017-12-18 19:14 UTC
Labels: question
