### ISSUE TITLE
Packer will download again the iso if the checksum failed and then replace by correct one

### ISSUE THREAD

**Issue by bastianb** [hashicorp/packer#10661] opened 2021-02-19 09:51 UTC
#### Overview of the Issue

If an ISO download is started with a wrong SHA checksum then when it finishes to download the launch fails, but, if you change the SHA to the correct one and then relaunch the build, it starts to download the ISO again instead of using the one in cache.

#### Reproduction Steps

set `iso_url` with a wrong `iso_checksum` 
start a build wait for download and failure
set proper sha in `iso_checksum`
start build again
-> packer redownload the ISO

### Packer version

From `1.7.0`

### Log Fragments and crash.log files

```
$ packer build template.json
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso
==> virtualbox-iso: Trying http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
    virtualbox-iso: CentOS-7-x86_64-NetInstall-2009.iso 575.00 MiB / 575.00 MiB [=================================================================================================] 100.00% 3m45s
==> virtualbox-iso: Checksum did not match, removing REDACTED/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso
==> virtualbox-iso: error downloading ISO: [Checksums did not match for REDACTED/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso.
==> virtualbox-iso: Expected: 07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
==> virtualbox-iso: Got: b79079ad71cc3c5ceb3561fff348a1b67ee37f71f4cddfec09480d4589c191d6
==> virtualbox-iso: *sha256.digest]
Build 'virtualbox-iso' errored after 3 minutes 47 seconds: error downloading ISO: [Checksums did not match for REDACTED/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso.
Expected: 07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
Got: b79079ad71cc3c5ceb3561fff348a1b67ee37f71f4cddfec09480d4589c191d6
*sha256.digest]

==> Wait completed after 3 minutes 47 seconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: error downloading ISO: [Checksums did not match for REDACTED/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso.
Expected: 07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
Got: b79079ad71cc3c5ceb3561fff348a1b67ee37f71f4cddfec09480d4589c191d6
*sha256.digest]

==> Builds finished but no artifacts were created.
```
Changing checksum in the template
```
$ packer build template.json
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso
==> virtualbox-iso: Trying http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso?checksum=sha256%3Ab79079ad71cc3c5ceb3561fff348a1b67ee37f71f4cddfec09480d4589c191d6
    virtualbox-iso: CentOS-7-x86_64-NetInstall-2009.iso 575.00 MiB / 575.00 MiB [=================================================================================================] 100.00% 3m58s
==> virtualbox-iso: http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso?checksum=sha256%3Ab79079ad71cc3c5ceb3561fff348a1b67ee37f71f4cddfec09480d4589c191d6 => REDACTED/packer_cache/fa66676a0cae1de79d03c97423c2624780bea13a.iso
==> virtualbox-iso: Starting HTTP server on port 8983
```

**Comment by azr** [comment] 2021-02-19 12:49
Hello @bastianb, thanks for opening ! I think that this is the intended behaviour, this is to make sure you run the ISO that was just downloaded was not tinkered with.

Have you tried manually downloading the ISO ? What was the correct checksum ?

**Comment by azr** [comment] 2021-02-19 12:52
When I run it :

```shellsession
> wget http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso
--2021-02-19 13:49:48--  http://ftp.wcss.pl/pub/linux/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso
Resolving ftp.wcss.pl (ftp.wcss.pl)... 156.17.193.34
Connecting to ftp.wcss.pl (ftp.wcss.pl)|156.17.193.34|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 602931200 (575M) [application/octet-stream]
Saving to: ‘CentOS-7-x86_64-NetInstall-2009.iso’

CentOS-7-x86_64-NetInstall-20 100%[===============================================>] 575.00M  34.3MB/s    in 19s     

2021-02-19 13:50:07 (30.7 MB/s) - ‘CentOS-7-x86_64-NetInstall-2009.iso’ saved [602931200/602931200]

❯ sha256sum CentOS-7-x86_64-NetInstall-2009.iso              
b79079ad71cc3c5ceb3561fff348a1b67ee37f71f4cddfec09480d4589c191d6  CentOS-7-x86_64-NetInstall-2009.iso
```

This looks like the correct behaviour to me. Closing this issue for now; please tell us if you think there's something we can do to help here :)

**Comment by bastianb** [comment] 2021-02-19 15:01
You have both invalid and valid checksum in the log in the issue, first run with invalid and second with correct one. 

The behavior doesn't make sense to me, if a cached file exist for the download, why doesn't it compare the checksum of that file before even assuming it has to download it again?

I also did not consider downloading it manually first, because it is an extra step that packer do well. 

I do not see how a file could be tinkered and still have same checksum.

**Comment by SwampDragons** [comment] 2021-02-19 18:14
I think the confusion here is that Packer does not save a file it downloads if it has an invalid checksum -- it deletes the file as part of cleaning up after itself rather than keeping it in the file cache. So there is no local file for Packer to find in the cache when you perform your second download. This is intentional behavior, to prevent bad or corrupted files from polluting your storage.

**Closed** 2021-02-19 18:51 UTC
Labels: bug, wontfix
