### ISSUE TITLE
shell provisioner stuck at "starting remote command: test -d"... (openwrt chaos calmer guest)

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#6118] opened 2018-04-08 14:50 UTC
Packer is able to generate Vagrant boxes for OpenWrt v17 LEDE, however when I try to generate a Vagrant box for an earlier version of OpenWrt, v15 Chaos Calmer, packer somehow gets stuck at `starting remote command: test -d`, the first shell provisioning step.

- Packer version from `packer version`: Packer v1.2.3-dev
- Host platform: macOS 10.13 High Sierra

Packer configuration:

https://github.com/mcandre/packer-templates/tree/4aaedc83af87623233234d12a9deaa12fc584df6/openwrt

For what it's worth, when I manually SSH into the guest VM during packing, `test -d /tmp/script_7446.sh` quickly completes with the expected `1` exit status.

I'm not sure how `test -d` is apparently blocking in OpenWrt chaos calmer for several hours (!), but I wish packer could specify a timeout so that the build can fail, rather than freeze there indefinitely.

**Update**

After tinkering with the packer source code, I think it's safe to conclude that OpenWrt v15 Chaos Calmer has some ssh oddities, that are causing the Go ssh client to never receive the signal that the connection should close.

I tried working around this strangeness by selecting the `sftp` uploader in my packer configuration, but that triggers `EOF` errors that retry forever.

**Comment by SwampDragons** [comment] 2018-04-10 20:49
Sorry about this. It's a known regression and duplicate of #5994 This should be fixed by https://github.com/hashicorp/packer/pull/6124 and is at the top of my priority list. It'll be fixed in the 1.2.3 release.

**Closed by SwampDragons** 2018-04-10 20:49 UTC
