### ISSUE TITLE
Packer running under Jenkins - Provisioner script stops execution on Import-Module AWSPowershell

### ISSUE THREAD

**Issue by baldwinjim** [hashicorp/packer#4155] opened 2016-11-10 22:47 UTC
FOR BUGS:
Packer version 0.11.0
Host Platform:  Ubuntu 14.04 running Jenkins v2.19.2 
Situation:  using Jenkins to create a nuget build artifact, upload that artifact to Artifactory, then use packer to create application ami with that nuget install

I am using the windows-shell provisioner to run a powershell script.

"provisioners": [
     {
         "type": "windows-shell",
         "script": "src/app/SharedServices/scripts/import.ps1",
         "remote_path": "c:/temp/import.ps1",
         "execute_command": "powershell c:/temp/import.ps1"
      }
    ]

the contents of import.ps1 are as follows:
Write-Output "Importing AWS PowerShell Module"
Import-Module AWSPowerShell
Write-Output "Finished Importing"
....   do other stuff install application

Packer executes this script but when it hits the Import-Module step, it somehow thinks that the script is finished and begins to create the AMI.

Originally, I had 3 scripts to run as part of the packer process, and the script continually fails on the Import-Module AWSPowerShell command which is contained in the first script in the provisioner.  It will then continue with the next 2 scripts with no issues.  

The Import-Module script seems to take some time to execute, but it it doesn't seem like it is long enough to cause a time-out. <10 seconds

Here is the Jenkins output for the packer step:

[1;32m==> amazon-ebs: Prevalidating AMI Name...[0m
[1;32m==> amazon-ebs: Inspecting the source AMI (ami-30540427)...[0m
[1;32m==> amazon-ebs: Creating temporary keypair: packer_5824f3ea-ae47-0a9f-bb4a-d350477277ca[0m
[1;32m==> amazon-ebs: Launching a source AWS instance...[0m
[0;32m    amazon-ebs: Instance ID: i-d22c40dc[0m
[1;32m==> amazon-ebs: Waiting for instance (i-d22c40dc) to become ready...[0m
[1;32m==> amazon-ebs: Waiting for auto-generated password for instance...[0m
[0;32m    amazon-ebs: It is normal for this process to take up to 15 minutes,
    amazon-ebs: but it usually takes around 5. Please wait.[0m
[0;32m    amazon-ebs:  
    amazon-ebs: Password retrieved![0m
[1;32m==> amazon-ebs: Waiting for WinRM to become available...[0m
[1;32m==> amazon-ebs: Connected to WinRM![0m
[1;32m==> amazon-ebs: Provisioning with windows-shell...[0m
[1;32m==> amazon-ebs: Provisioning with shell script: src/app/SharedServices/scripts/import.ps1[0m
[0;32m    amazon-ebs: Importing AWS PowerShell Module[0m
[1;32m==> amazon-ebs: Stopping the source instance...[0m
[1;32m==> amazon-ebs: Waiting for the instance to stop...[0m
[1;32m==> amazon-ebs: Creating the AMI: LandingPageSvc-1.0.0.144[0m
[0;32m    amazon-ebs: AMI: ami-117e5206[0m
[1;32m==> amazon-ebs: Waiting for AMI to become ready...[0m
[1;32m==> amazon-ebs: Terminating the source AWS instance...[0m
[1;32m==> amazon-ebs: Cleaning up any extra volumes...[0m
[1;32m==> amazon-ebs: No volumes to clean up, skipping[0m
[1;32mBuild 'amazon-ebs' finished.[0m

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

**Comment by mwhooker** [comment] 2016-11-10 22:54
I wonder if this is a duplicate of #4150

seems like it might be

**Comment by mwhooker** [comment] 2016-11-10 23:00
@baldwinjim could you try rewriting your provisioner to use the powershell provisioner and let me know if you've still got the issue? https://www.packer.io/docs/provisioners/powershell.html

**Comment by baldwinjim** [comment] 2016-11-11 02:14
I have tried with the Powershell provisioner, but I am  experiencing errors similar to 4044 so this was my attempt to work-around this issue

**Comment by baldwinjim** [comment] 2016-11-14 17:09
```
"provisioners": [
    {
        "type": "windows-shell",
        "script": "src/app/SharedServices/scripts/init.ps1",
        "remote_path": "c:/temp/init.ps1",
        "execute_command": "powershell c:/temp/init.ps1"
     },
     {
         "type": "windows-shell",
         "script": "src/app/SharedServices/scripts/windowsBase.ps1",
         "remote_path": "c:/temp/windowsBase.ps1",
         "execute_command": "powershell c:/temp/windowsBase.ps1"
      },
      {
          "type": "windows-shell",
          "environment_vars": ["appVersion={{user `appVersion`}}"],
          "script": "src/app/SharedServices/scripts/webss.ps1",
          "remote_path": "c:/temp/webss.ps1",
          "execute_command": "{{.Vars}} powershell c:/temp/webss.ps1"
       },
       {
           "type": "windows-shell",
           "script": "src/app/SharedServices/scripts/ec2prep.ps1",
           "remote_path": "c:/temp/ec2prep.ps1",
           "execute_command": "powershell c:/temp/ec2prep.ps1"
        }
    ]

```


So, what I found was that the first script will typically fail with no error and the following provisioner scripts  will run without incident.  So, wrote my script to not use the AWSPoweshell module and created a dummy script called init.ps1 that does one thing:  Impport-Module AWSPowershell.   So, now I don't care if init.ps1 fails, I don't need it.  So far, initial testing looks good.

**Comment by SwampDragons** [comment] 2017-09-29 17:07
>  what I found was that the first script will typically fail with no error and the following provisioner scripts will run without incident

Based on this I think the error is actually a duplicate of https://github.com/hashicorp/packer/issues/5064 and was fixed by https://github.com/hashicorp/packer/pull/5272.  If I'm wrong and this problem still exists in Packer 1.0.4, please reopen!

**Closed by SwampDragons** 2017-09-29 17:07 UTC
Labels: bug, provisioner/windows-shell, windows-guest
