### ISSUE TITLE
vsphere-iso Ubuntu 18.04 "purple screen"

### ISSUE THREAD

**Issue by FF186** [hashicorp/packer#9970] opened 2020-09-21 10:15 UTC
(Not sure if this is a Packer problem)

Hi,

when I try to create a Ubuntu 18.04.5 Server using the `vsphere-iso` builder, I get stuck at blank purple screen. 
Everything seems to work fine in the beginning:

- I boot into text mode.
- Packer inserts my `boot_command`.
- Component is being loaded.
- After networks component are being initialized (link-local, ipv6, DHCP) I get the purple screen.
- Stuck at purple screen until Packer timeout.

I know my setup have worked earlier this year...

I'm using a custom preseed and the newest version of Ubuntu 18.04.5

`Packer 1.5.6`

Thanks.

**Comment by nywilken** [comment] 2020-09-21 14:27
Hey there, thanks for reaching out. Hanging on the purple screen usually implies some boot config related issue.  

> I'm using a custom preseed and the newest version of Ubuntu 18.04.5

Was your configuration working with an earlier version of Ubuntu? 

If so you may want to check the preseed for any configs that are no longer relevant or need to be updated to work with 18.04; especially for any additional drivers that may be needed.

If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer/23) for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum. 

Also, we've made some improvements to the Vsphere-iso builder since v1.5.6, and I strongly suggest you update the version of Packer, even if it doesn't fix your problem for now.

**Comment by FF186** [comment] 2020-09-22 05:25
> Hey there, thanks for reaching out. Hanging on the purple screen usually implies some boot config related issue.
> 
> > I'm using a custom preseed and the newest version of Ubuntu 18.04.5
> 
> Was your configuration working with an earlier version of Ubuntu?
> 
> If so you may want to check the preseed for any configs that are no longer relevant or need to be updated to work with 18.04; especially for any additional drivers that may be needed.
> 
> If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer/23) for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum.
> 
> Also, we've made some improvements to the Vsphere-iso builder since v1.5.6, and I strongly suggest you update the version of Packer, even if it doesn't fix your problem for now.

Yes, it was working earlier with 18.04.4, then I updated to 18.04.5 couple of weeks ago and tested my packer template with the new version, and it worked using `vsphere-iso`. 

Now (some weeks later) the same template and the same version does not longer "work" when using `vsphere-iso`...

I tried version `1.6.1`, same issue.

Thanks.

**Comment by SwampDragons** [comment] 2020-09-23 21:25
Thanks for the clarification. Since the image and version of Packer haven't changed since it last worked, this probably isn't a Packer bug.

Here are a couple of troubleshooting thoughts to rule out: 
- timing issues (boot_command getting typed too soon before guest is fully up?)
- connectivity issues (new proxy, new vsphere host IP, etc)
- preseed attach/upload issues (are you using floppy_files or the http_directory server? Did the preseed get moved? Are you pointing at an empty directory?

Also: make sure that your 18.04.5 server image isn't the "live" one containing the new and totally different "autoinstall" installer, or your preseed file won't work. See https://ubuntu.com/server/docs/install/autoinstall-reference for more details on the new autoinstall format. I know they switched to defaulting to this new installer for ubuntu 20.04, and you need to download a [special legacy image](http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/) if you want to still use preseeds. Looking at the 18.04.5 downloads page it looks like they use the "live" server as well, which could definitely explain your issue. The only confusing part there is that you say you tested it and it worked before. 

Since this seems more like a question than a Packer bug given the current information, I'm going to close this issue. If you need further help getting started, reach out to the community forum like Wilken mentioned and make sure to share your packer config, what iso you're using, and your preseeds.  And if you think we're wrong and it's a bug, we can reopen but we also need steps to reproduce including full config and preseed files and logs.  Thanks!

**Closed by SwampDragons** 2020-09-23 21:25 UTC
Labels: builder/vsphere, question, waiting-reply
