### ISSUE TITLE
amazon-chroot mount_partition option does not allow to mount entire device 

### ISSUE THREAD

**Issue by pa-yourserveradmin-com** [hashicorp/packer#6176] opened 2018-04-23 20:00 UTC
The [amazon-chroot](https://www.packer.io/docs/builders/amazon-chroot.html) builder works incorrectly with EBS volumes on HVM instances: the builder, relaying on [mount_partition](https://www.packer.io/docs/builders/amazon-chroot.html#mount_partition) option default behavior introduced in 460e2da2485d1392b6a28103e37f98331d85e625 and patched in 09543fc4e7de662488974178d8979083ec99bc04, attempts to mount `/dev/xvdf1` while there is no such partition and entire `/dev/xvdf` must be mounted.

Problem lines:
- https://github.com/hashicorp/packer/blob/master/builder/amazon/chroot/builder.go#L115 (there is no way to tell Packer to skip mount partition number);
- https://github.com/hashicorp/packer/blob/master/builder/amazon/chroot/step_mount_device.go#L79 (`deviceMount` for `HVM` instances always has numeric mount partition appended to device name).

It will be fine to have an ability to manage this out by using template variables, for example, by changing default behavior for `mount_partition` option as described in this [patch](https://gist.github.com/pa-yourserveradmin-com/d4366fb7037cda25b94db2bee05697ef#file-mount_partition-diff).

Environment, logs and how to reproduce:
- Packer version: 1.2.2
- Host platform: AWS Debian 7 Wheezy (source AMI ID: `ami-61e56916`)
- Debug log output is [here](https://gist.github.com/pa-yourserveradmin-com/d4366fb7037cda25b94db2bee05697ef#file-amazon-chroot-test-log)
- The example template and scripts needed to reproduce the bug can be found [here](https://gist.github.com/pa-yourserveradmin-com/d4366fb7037cda25b94db2bee05697ef#file-howtoreproduce-md)

**Comment by SwampDragons** [comment] 2018-04-24 18:14
I believe this is a duplicate of #5848; your patch might be useful in addressing these. I'm closing this as a duplicate and copying @mwhooker who was looking into the original issue.

**Comment by SwampDragons** [comment] 2018-04-25 17:18
By the way -- this issue and repro case are probably the most beautiful issue I've ever seen. Thank you for doing such a thorough job of making it easy for me to reproduce.

**Comment by SwampDragons** [comment] 2018-04-25 18:05
This wasn't a duplicate of 5848 after all, but I was able to fix it pretty easily thanks to your investigation; it'll be closed by #6194

**Closed** 2018-05-21 22:28 UTC
Labels: bug, builder/amazon
