### ISSUE TITLE
Impossible to pass -var-file to packer build

### ISSUE THREAD

**Issue by stackthecat** [hashicorp/packer#11949] opened 2022-08-18 14:57 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When trying to build an image packer with -var-file on the command line, locals or variables blocks are not allowed . withtout -var-file option it works great. It seems impossible to use -var-file options with packer build

#### Reproduction Steps

 packer build -var-file="variables.pkr.hcl" .

### Packer version

1.8.1 & 1.8.3 with vsphere plugins 1.7

### Simplified Packer Template

Packer template:

```
source "vsphere-iso" "epac_template" {
  CPUs                 = var.num_cpus
  RAM                  = var.memory
  RAM_reserve_all      = true
  boot_wait            = "2s"
  boot_command         = [  "<enter><wait2><enter><wait><f6><esc><wait>",
                            " autoinstall<wait2> net.ifnames=0 biosdevname=0 ip=dhcp ipv6.disable=1 ds=nocloud;",
                            "<wait><enter>"
                         ]
  disk_controller_type = ["pvscsi"]
  guest_os_type        = "ubuntu64Guest"
  host                 = var.vsphere_host
  insecure_connection  = true
  iso_paths            = ["[${var.Datastore}] ISO/ubuntu-20.04.4-live-server-amd64.iso"]
  cd_files = ["meta-data", "user-data"]
  cd_label = "cidata"
  network_adapters {
    network_card = "vmxnet3"
    network = var.vsphere_network
  }
  datastore    = var.Datastore
  ssh_password = local.epac_password
  ssh_username = local.epac_username
  ssh_timeout  = "180m"
  shutdown_timeout = "180m"
  storage {
    disk_size             = 150000
    disk_thin_provisioned = true
  }
  username            = local.vsphere_user
  vcenter_server      = var.vsphere_vcenter
  password            = local.vsphere_password
  vm_name             = "epac_template"
  convert_to_template = true
  export {
    force = true
    output_directory = "${var.export_ovf}"
    image_files = true
    images = true
  }

}

build {
  sources = ["source.vsphere-iso.epac_template"]

  provisioner "shell" {
    inline = ["sudo apt-get update && sudo apt-get upgrade -y",
              "sudo systemctl stop multipathd.service && sudo systemctl disable multipathd.service"]
}

  provisioner "file" {
    source = "fix_bash_epac_P1.sh"
    destination = "/tmp/fix_bash_epac_P1.sh"
}

  provisioner "file" {
    source = "remediation.sh"
    destination = "/tmp/remediation.sh"
}

  provisioner "shell" {
    inline =  ["sudo bash /tmp/fix_bash_epac_P1.sh",
               "sudo bash /tmp/remediation.sh"]

}

  provisioner "shell" {
    inline =  ["sudo rm -rf /tmp/*.sh",
               "sudo apt-get install syslog-ng -y"]
}

  post-processors {
    post-processor "artifice" {
      files = ["${var.export_ovf}/*"]
    }
    post-processor "shell-local" {
      inline = [ "for i in $(ls ${var.export_ovf}) ; do curl -v --user '${local.nexus_user}:${local.nexus_password}' --upload-file  ${var.export_ovf}/$i  http://${var.nexus_ip}/repository/${var.repo_name}/; done " ]
    }
}
```

variable file:
```
local "vsphere_user" {
    expression = vault("epac/data/ESX_EPAC/vsphere_as_deploy/", "user")
}

local "vsphere_password" {
    expression = vault("epac/data/ESX_EPAC/vsphere_as_deploy/", "password")
}

local "epac_username" {
    expression = vault("epac/data/server/epac-template/", "user")
}

local "epac_password" {
    expression = vault("epac/data/server/epac-template/", "password")
}

local "nexus_user" {
    expression = vault ("epac/data/server/nexus/", "user")
}

local "nexus_password" {
    expression = vault ("epac/data/server/nexus/", "password")
}

variables {
   vsphere_vcenter = "vct01.epac.lan"
   vsphere_host = "hyp01.epac.lan"
   vsphere_network = "ADMIN"
   Datastore = "vsanDatastore"
   num_cpus = "4"
   memory = "8192"
   export_ovf = "export_ovf"
   nexus_ip = "10.0.20.69"
   repo_name = "epac"
}
```

### Operating system and Environment details

Ubuntu 20.04 amd64

### Log Fragments and crash.log files

```
packer build -var-file="variables.pkr.hcl" .
2022/08/18 14:52:23 [INFO] Packer version: 1.8.3 [go1.17.11 linux amd64]
2022/08/18 14:52:23 [TRACE] discovering plugins in /usr/local/bin
2022/08/18 14:52:23 [TRACE] discovering plugins in /home/stackthecat/.config/packer/plugins
2022/08/18 14:52:23 [TRACE] discovering plugins in .
2022/08/18 14:52:23 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/08/18 14:52:23 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/stackthecat/.packerconfig
2022/08/18 14:52:23 [WARN] Config file doesn't exist: /home/stackthecat/.packerconfig
2022/08/18 14:52:23 [INFO] Setting cache directory: /home/stackthecat/.cache/packer
Error: Unexpected "local" block

  on variables.pkr.hcl line 1, in local "vsphere_user":
   1: local "vsphere_user" {

Blocks are not allowed here.


  on variables.pkr.hcl line 1, in local "vsphere_user":
   1: local "vsphere_user" {

Blocks are not allowed here.
```

**Comment by ChrisDek** [comment] 2022-08-24 05:29
I have a similar issue documented in #11659

**Comment by nywilken** [comment] 2022-09-21 19:00
This PR is related to this issue https://github.com/hashicorp/packer/pull/11996 there are few suggestions to improve the documentation that may help clear things. Please feel free to share any thoughts as you are not the first person to find this confusing.

**Comment by nywilken** [comment] 2022-09-21 19:00
Related to #11659

**Comment by nywilken** [comment] 2022-09-30 14:48
Going to mark this as a duplicate of #11659 so that it can be tracked and planned for in one single issue. Please feel free to add any new comments to the issue captured in 11659.

**Closed by nywilken** 2022-09-30 14:48 UTC
Labels: bug, duplicate, hcl2
