### ISSUE TITLE
Powershell provisioner randomly skipping inline commands but runs everytime in debug mode

### ISSUE THREAD

**Issue by going2thecloud** [hashicorp/packer#10473] opened 2021-01-13 01:19 UTC
Packer v1.6.6 running on AMazon Lnux (amazon/amzn2-ami-hvm-2.0.20180622.1-x86_64-gp2)

Building Windows 2016  Standard image on AWS

List of provisioners begin with inline commands followed by scripts one.
However packer randomly skipping this inline commands and start with script one. When run in debug mode it does execute inline every time. As per the template I should be able to see line `Starting build...` when provisioner begin to execute.

```
"provisioners": [
    {
      "type": "powershell",
      "inline": [
        "Write-Host 'Starting build...'",
        "\"Starting build $(Get-Date)\" | Out-File 'C:\\Windows\\Temp\\packer.txt'",
        "[system.io.directory]::CreateDirectory(\"C:\\Program Files\\GTS-SharedServices\")",
        "Write-Host 'Disabling defender..'",
        "Set-MpPreference -DisableRealtimeMonitoring $true",
        "Write-Host 'Installing required modules..'",
        "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12",
        "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted",
        "Install-Module -Name 'NetworkingDsc','AuditPolicyDsc','SecurityPolicyDsc','PoshSpec' -Force -SkipPublisherCheck -Verbose -ErrorAction Stop",
        "Uninstall-Module -Name 'Pester' -Force",
        "Install-Module -Name 'Pester' -Force -SkipPublisherCheck -Verbose -ErrorAction Stop -RequiredVersion 4.10.1"
      ]
    },
    {
      "type": "powershell",
      "environment_vars": [
        "GIT_BRANCH={{user `GIT_BRANCH`}}",
        "ARTIFACTORY_URL={{user `art_url`}}",
        "ARTIFACTORY_USER={{user `art_user`}}",
        "ARTIFACTORY_PASSWORD={{user `art_pass`}}"
      ],
      "scripts": [
        "scripts/windows/download_binary.ps1"
      ]
    },
    {
      "type": "file",
      "source": "build_files/win2016_baseline/files/",
      "destination": "C:\\"
    }, ...
```

Here is snippet of output (without debug):
```
10:00:56 ==> win2016_baseline: Waiting for auto-generated password for instance...
10:00:56     win2016_baseline: It is normal for this process to take up to 15 minutes,
10:00:56     win2016_baseline: but it usually takes around 5. Please wait.
10:01:47     win2016_baseline:  
10:01:47     win2016_baseline: Password retrieved!
10:01:47 ==> win2016_baseline: Using winrm communicator to connect: 10.13.28.30
10:01:47 ==> win2016_baseline: Waiting for WinRM to become available...
10:01:53     win2016_baseline: WinRM connected.
10:01:53 ==> win2016_baseline: #< CLIXML
10:01:53 ==> win2016_baseline: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
10:01:53 ==> win2016_baseline: Connected to WinRM!
10:01:53 ==> win2016_baseline: Provisioning with Powershell...
10:01:53 ==> win2016_baseline: Provisioning with powershell script: /tmp/powershell-provisioner982908749
10:01:59 ==> win2016_baseline: Provisioning with Powershell...
10:01:59 ==> win2016_baseline: Provisioning with powershell script: scripts/windows/download_binary.ps1
10:02:05     win2016_baseline: Downloading Binaries from Artifactory..
10:03:03 ==> win2016_baseline: Uploading build_files/win2016_baseline/files/ => C:\
10:03:25 ==> win2016_baseline: Uploading build_files/win2016_baseline/template/ => C:\Windows\Temp\baseline\template
10:03:30 ==> win2016_baseline: Uploading build_files/win2016_baseline/build_tests/ => C:\Windows\Temp\
```

Snippet of output (with debug):
```
10:16:56 ==> win2016_baseline: Waiting for instance (i-0b44a63ce46bf6b5d) to become ready...
10:17:26     win2016_baseline: Public IP: 54.184.225.227
10:17:26     win2016_baseline: Private IP: 10.13.28.36
10:17:26 2021/01/12 18:17:25 packer-builder-amazon-ebs plugin: Error asking for input: no available tty
10:17:26 ==> win2016_baseline: Waiting for auto-generated password for instance...
10:17:26     win2016_baseline: but it usually takes around 5. Please wait.
10:17:26     win2016_baseline: It is normal for this process to take up to 15 minutes,
10:17:26     win2016_baseline: but it usually takes around 5. Please wait.
10:17:31 2021/01/12 18:17:30 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:17:31 2021/01/12 18:17:30 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:17:36 2021/01/12 18:17:35 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:17:36 2021/01/12 18:17:35 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:17:41 2021/01/12 18:17:40 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:17:41 2021/01/12 18:17:41 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:17:46 2021/01/12 18:17:46 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:17:46 2021/01/12 18:17:46 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:17:51 2021/01/12 18:17:51 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:17:51 2021/01/12 18:17:51 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:17:56 2021/01/12 18:17:56 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:17:57 2021/01/12 18:17:56 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:18:02 2021/01/12 18:18:01 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:18:02 2021/01/12 18:18:01 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:18:07 2021/01/12 18:18:06 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:18:07 2021/01/12 18:18:06 packer-builder-amazon-ebs plugin: [DEBUG] Password is blank, will retry...
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: Retrieving auto-generated instance password...
10:18:12     win2016_baseline: Password retrieved!
10:18:12     win2016_baseline:  
10:18:12     win2016_baseline: Password retrieved!
10:18:12     win2016_baseline: Password (since debug is enabled): gp9MPCN5U-7UhP-DkATMRwDKB=S2(GIR
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: Error asking for input: no available tty
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: Error asking for input: no available tty
10:18:12 ==> win2016_baseline: Using winrm communicator to connect: 10.13.28.36
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: Waiting for WinRM, up to timeout: 15m0s
10:18:12 ==> win2016_baseline: Waiting for WinRM to become available...
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: Using host value: 10.13.28.36
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: [INFO] Attempting WinRM connection...
10:18:12 2021/01/12 18:18:11 packer-builder-amazon-ebs plugin: [DEBUG] connecting to remote shell using WinRM
10:18:17 2021/01/12 18:18:16 packer-builder-amazon-ebs plugin: Checking that WinRM is connected with: 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA'
10:18:17 2021/01/12 18:18:16 packer-builder-amazon-ebs plugin: [INFO] starting remote command: powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: [INFO] command 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA' exited with code: 0
10:18:18     win2016_baseline: WinRM connected.
10:18:18 ==> win2016_baseline: #< CLIXML
10:18:18 ==> win2016_baseline: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: Connected to machine
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: Error asking for input: no available tty
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: Error asking for input: no available tty
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: Running the provision hook
10:18:18 2021/01/12 18:18:17 [INFO] (telemetry) Starting provisioner powershell
10:18:18 2021/01/12 18:18:17 Error asking for input: no available tty
10:18:18 ==> win2016_baseline: Connected to WinRM!
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Write-Host 'Starting build...'
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: "Starting build $(Get-Date)" | Out-File 'C:\Windows\Temp\packer.txt'
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: [system.io.directory]::CreateDirectory("C:\Program Files\GTS-SharedServices")
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Write-Host 'Disabling defender..'
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Set-MpPreference -DisableRealtimeMonitoring $true
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Write-Host 'Installing required modules..'
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Install-Module -Name 'NetworkingDsc','AuditPolicyDsc','SecurityPolicyDsc','PoshSpec' -Force -SkipPublisherCheck -Verbose -ErrorAction Stop
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Uninstall-Module -Name 'Pester' -Force
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Found command: Install-Module -Name 'Pester' -Force -SkipPublisherCheck -Verbose -ErrorAction Stop -RequiredVersion 4.10.1
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Opening /tmp/powershell-provisioner779573040 for reading
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5ffde795-0745-8a4f-3ca5-c05c852dc5c5.ps1
10:18:18 2021/01/12 18:18:17 packer-provisioner-powershell plugin: [INFO] 82 bytes written for 'uploadData'
10:18:18 2021/01/12 18:18:17 [INFO] 82 bytes written for 'uploadData'
10:18:18 ==> win2016_baseline: Provisioning with Powershell...
10:18:18 ==> win2016_baseline: Provisioning with powershell script: /tmp/powershell-provisioner779573040
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5ffde795-0745-8a4f-3ca5-c05c852dc5c5.ps1'
10:18:18 2021/01/12 18:18:17 packer-builder-amazon-ebs plugin: #< CLIXML
10:18:18 2021/01/12 18:18:18 packer-builder-amazon-ebs plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
10:18:18 2021/01/12 18:18:18 packer-provisioner-powershell plugin: [INFO] 732 bytes written for 'uploadData'
10:18:18 2021/01/12 18:18:18 [INFO] 732 bytes written for 'uploadData'
```

**Comment by SwampDragons** [comment] 2021-01-13 19:30
Hi, thanks for reaching out. I think this is a duplicate of https://github.com/hashicorp/packer/issues/9757 -- take a look at that issue for debugging steps and workarounds. I'm going to close this to keep related issues in the same place, so please comment there if you have anything to add. Thanks!!

**Closed by SwampDragons** 2021-01-13 19:30 UTC
