### ISSUE TITLE
Provisioner ansible-local not working in 1.2

### ISSUE THREAD

**Issue by geertn** [hashicorp/packer#5908] opened 2018-02-15 14:01 UTC
- Packer version from `packer version`
packer 1.2.0
- Host platform
CentoOS latest official AWS image (ami-337be65c)

- Debug log output from `PACKER_LOG=1 packer build template.json`.

Debug log:
https://gist.github.com/geertn/266e3cba10bf9c930f65a9695b26d6de

- The _simplest example template and scripts_ needed to reproduce the bug.

Packer json:
https://gist.github.com/geertn/3c6c71b36b951c253b8f3eb98690e620

idp-baseline.yml:

```
---
- name: Baseline
  hosts: all
  vars:
    ansible_pipelining: yes
  pre_tasks:
    - fail: msg="Legacy system, exiting"
      when: legacy is defined
      tags: always

```

packer consistently fails with:
`
ERROR! the playbook: packer_builder_type=amazon-ebs could not be found
`

When SSH into the machine I can make it work by removing the escapes for extra-vars:

> [centos@ip-172-31-38-55 tmp]$ cd /tmp/packer-provisioner-ansible-local/5a858d38-360a-e8de-4c07-f8f8250281d7 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/5a858d38-360a-e8de-4c07-f8f8250281d7/idp-baseline.yml --extra-vars \"packer_build_name=amazon-ebs packer_builder_type=amazon-ebs packer_http_addr=\" --extra-vars "Region=test" -c local -i /tmp/packer-provisioner-ansible-local/5a858d38-360a-e8de-4c07-f8f8250281d7/packer-provisioner-ansible-local644862448
> ERROR! the playbook: packer_builder_type=amazon-ebs could not be found
> 

Executing the following works:

> [centos@ip-172-31-38-55 tmp]$ cd /tmp/packer-provisioner-ansible-local/5a858d38-360a-e8de-4c07-f8f8250281d7 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/5a858d38-360a-e8de-4c07-f8f8250281d7/idp-baseline.yml --extra-vars "packer_build_name=amazon-ebs packer_builder_type=amazon-ebs packer_http_addr=" --extra-vars "Region=test" -c local -i /tmp/packer-provisioner-ansible-local/5a858d38-360a-e8de-4c07-f8f8250281d7/packer-provisioner-ansible-local644862448

When downgrading to 1.1.3 everything works.

**Comment by SwampDragons** [comment] 2018-02-15 19:05
I think this is a duplicate of https://github.com/hashicorp/packer/issues/5885 and already fixed on master. I'm going to leave this issue open for now because it's the second duplicate we've had on this issue, probably because we closed the original one when we merged the fix -- I want people to be able to find this one and know we're already on it :) . Meanwhile, here's a linux build of the master branch which should include the fix.
[packer.zip](https://github.com/hashicorp/packer/files/1729031/packer.zip)

**Comment by geertn** [comment] 2018-02-15 22:29
The linked packer.zip doesn't seem to be a valid zip archive:

> Archive:  packer.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
>

**Comment by SwampDragons** [comment] 2018-02-15 22:40
I guess technically it was a tarball that I just threw a .zip extension onto so it must have given `unzip` some issues. I used zip for this so hopefully it'll work.
[packer.zip](https://github.com/hashicorp/packer/files/1729632/packer.zip)

**Comment by SwampDragons** [comment] 2018-02-22 22:34
Closing since we intend to release the patch tomorrow.

**Closed by SwampDragons** 2018-02-22 22:34 UTC
Labels: duplicate, provisioner/ansible-local, regression
