### ISSUE TITLE
Windows guests failing to build on Linux hosts. 

### ISSUE THREAD

**Issue by idoru78** [hashicorp/packer#4150] opened 2016-11-10 14:44 UTC
BUG:

Packer seems to be assuming that a powershell script has completed with exit code 0 when it is still running. This has happened is a couple of differant places but the uploaded gist shows it happening mid puppet run. It then moves onto the next post provision step where it hangs until we abort the build. We can see from the puppet master logs that the puppet run is not complete. This only seems to happen on our Red Hat hosts and not on our windows hosts. We have yet to complete a build on RHEL and have had multiple attempts. 

- Packer version = 0.11.1 dev
- Builder = vmware-iso (workstation)
- Host platform = RHEL 7.2
- Debug log output = https://gist.github.com/idoru78/dcf53b62855a4493fda5430af113b1dd

**Comment by idoru78** [comment] 2016-11-10 14:45
Note that we have the same issue on Packer 0.10 and 0.11 as well.

**Comment by rickard-von-essen** [comment] 2016-11-10 15:27
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by idoru78** [comment] 2016-11-10 15:42
Template - https://gist.github.com/idoru78/d87b740fad87410d06b88859ca1573d4

puppet.bat - https://gist.github.com/idoru78/b4027e7e72c964c444db241889c020af

**Comment by SwampDragons** [comment] 2017-09-29 17:15
If this truly was a duplicate of #4155 then it will have been fixed by #5272.  Please reopen if this hasn't been resolved, with everything I need to reproduce (the provided template contains a bunch of answer files that didn't make it into the gist, and I've failed to reproduce with my own windows instance)

**Closed by SwampDragons** 2017-09-29 17:15 UTC
Labels: bug, provisioner/powershell, windows-guest
