### ISSUE TITLE
Versions above 0.11.0 fail reproducably when provisioning Windows AMIs in AWS

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/packer#4994] opened 2017-06-09 11:37 UTC
After upgrading Packer from 0.11.0 to any newer version (incl. 1.0.0), it starts to fail reproducably when creating Windows Server 2008R2 AMIs from Amazon base AMIs in AWS. Windows Server 2012R2 AMIs are still provisioned fine. The last bits of log output are:
```
[2017-06-09T12:43:01] INFO  -- axc : ==> amazon-ebs: Restarting Machine
[2017-06-09T12:43:01] INFO  -- axc : ==> amazon-ebs: Waiting for machine to restart...
[2017-06-09T12:43:01] INFO  -- axc :     amazon-ebs: A system shutdown is in progress.(1115)
[2017-06-09T12:43:53] INFO  -- axc :     amazon-ebs: WIN-2E19G4EGGMK restarted.
[2017-06-09T12:43:53] INFO  -- axc : ==> amazon-ebs: Machine successfully restarted, moving on
[2017-06-09T12:43:53] INFO  -- axc : ==> amazon-ebs: Provisioning with Powershell...
[2017-06-09T12:43:53] INFO  -- axc : ==> amazon-ebs: Provisioning with shell script: /path/to/install_puppet.ps1
[2017-06-09T12:44:24] INFO  -- axc : ==> amazon-ebs: Terminating the source AWS instance...
[2017-06-09T12:44:55] INFO  -- axc : ==> amazon-ebs: Cleaning up any extra volumes...
[2017-06-09T12:44:55] INFO  -- axc : ==> amazon-ebs: No volumes to clean up, skipping
[2017-06-09T12:44:55] INFO  -- axc : ==> amazon-ebs: Deleting temporary keypair...
[2017-06-09T12:44:55] INFO  -- axc : Build 'amazon-ebs' errored: Script exited with non-zero exit status: 2147942487. Allowed exit codes are: [0]
[2017-06-09T12:44:55] INFO  -- axc :
[2017-06-09T12:44:55] INFO  -- axc : ==> Some builds didn't complete successfully and had errors:
[2017-06-09T12:44:55] INFO  -- axc : --> amazon-ebs: Script exited with non-zero exit status: 2147942487. Allowed exit codes are: [0]
[2017-06-09T12:44:55] INFO  -- axc :
[2017-06-09T12:44:55] INFO  -- axc : ==> Builds finished but no artifacts were created.
```

- Versions: 0.12.x, 1.0.0
- Ubuntu Linux
- https://gist.github.com/dhs-rec/a5cf71c78ba7f8a832ab0fcb8d49483e

**Comment by rickard-von-essen** [comment] 2017-06-09 11:46
Please supply the information requested in the issue template:
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by dhs-rec** [comment] 2017-06-09 11:50
Will see what I can do...

**Comment by dhs-rec** [comment] 2017-06-09 12:26
https://gist.github.com/dhs-rec/064327e8d1123fd210d98cf5d7383813

**Comment by SwampDragons** [comment] 2017-08-10 17:48
okay, might have repro'd.  I get 
```==> amazon-ebs: Provisioning with shell script: ./install_windows_patches.ps1
2017/08/10 10:37:58 packer: 2017/08/10 10:37:58 Opening ./install_windows_patches.ps1 for reading
2017/08/10 10:37:58 packer: 2017/08/10 10:37:58 Building elevated command wrapper for: if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};$env:PACKER_BUILDER_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="amazon-ebs"; &'c:/Windows/Temp/script.ps1';exit $LastExitCode
2017/08/10 10:37:58 packer: 2017/08/10 10:37:58 Uploading elevated shell wrapper for command [if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};$env:PACKER_BUILDER_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="amazon-ebs"; &'c:/Windows/Temp/script.ps1';exit $LastExitCode] to [${env:TEMP}\packer-elevated-shell-598c99f6-38e5-18fb-2bd8-34f65c549323.ps1] from [/var/folders/8t/0yb5q0_x6mb2jldqq_vjn3lr0000gn/T/packer-elevated-shell.ps1979210624]
2017/08/10 10:37:58 packer: 2017/08/10 10:37:58 Uploading file to '${env:TEMP}\packer-elevated-shell-598c99f6-38e5-18fb-2bd8-34f65c549323.ps1'
2017/08/10 10:37:58 packer: 2017/08/10 10:37:58 [INFO] 2957 bytes written for 'uploadData'
2017/08/10 10:37:58 [INFO] 2957 bytes written for 'uploadData'
2017/08/10 10:38:01 packer: Windows PowerShell terminated with the following error:
2017/08/10 10:38:01 packer:  Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
2017/08/10 10:38:02 [INFO] (telemetry) ending powershell
2017/08/10 10:38:02 [INFO] (telemetry) found error: Error processing command: Error generating elevated runner: Error preparing elevated shell script: Error restoring file from $env:TEMP\winrmcp-6e28ec0f-1b35-4436-66d3-ced0c72366a8.tmp to ${env:TEMP}\packer-elevated-shell-598c99f6-38e5-18fb-2bd8-34f65c549323.ps1: restore operation returned code=4294901760```

**Comment by SwampDragons** [comment] 2017-08-10 20:30
Based on the exit codes I'm getting and the changelog entry here `provisioner/powershell: Reverted [GH-3371] fixes quoting issue. [GH-4069]` I think powershell quoting is biting us once again here.  Time to tinker.

**Comment by dhs-rec** [comment] 2017-08-22 08:25
BTW: Did a quick check with 1.0.4, still shows the same behaviour on Win Server 2008R2.

**Comment by SwampDragons** [comment] 2017-08-24 22:16
I got the "Error generating elevated runner" using the repro case provided.  It is fixed by https://github.com/hashicorp/packer/pull/5272; it should be released in Packer 1.1.0 next week.

**Comment by dhs-rec** [comment] 2017-09-13 13:29
Tried 1.1.0, problem still persists. Please re-open.

**Comment by SwampDragons** [comment] 2017-09-13 19:23
Shoot, you're right.  And you're only seeing this for win2008r2?  I was able to work around the failure by adding a 30s sleep post-restart, but I'll reopen until I can figure out a way to fix this other than just shoehorning a sleep into the restart provisioner.

**Comment by SwampDragons** [comment] 2017-09-13 19:48
Okay, turns out this isn't related to the linked issue (5272) after all -- I only thought it was because I happened to run into _that_ issue when trying to reproduce _this_ one.  This issue doesn't need nearly as complex of a provisioning setup in the config -- I was able to get a much faster test case by changing the provisioners in your repro case to 

```  
"provisioners": [
    {
      "type": "powershell",
      "environment_vars": [
        "DEBUG=false",
        "HOSTNAME=packertest.eu-central-1.compute.internal",
        "MASTER_HOSTNAME=puppetmaster.eu-central-1.compute.internal",
        "PUPPETENV=aws",
        "PUPPETVERSION=1.2.2"
      ],
      "elevated_user": "Administrator",
      "elevated_password": "SuperS3cr3t!",
      "script": "./install_puppet.ps1"
    }
  ]```

I suspect this is related to issues we've seen with environment variables not getting set correctly in the powershell provisoner.

**Comment by SwampDragons** [comment] 2017-09-14 00:38
I can consistently get this error even when I replace `install_puppet.ps1` with a dead simple powershell script that just writes the environment variables:

```
Write-Output("Debug is " + $Env:DEBUG )
Write-Output("Hostname is " + $Env:HOSTNAME )
Write-Output("PUPPETENV is " + $Env:PUPPETENV )
Write-Output("PUPPETVERSION is " + $Env:PUPPETVERSION )
```

In fact, tinkering with this script and more generic variable names, I figured out that it has to do with the length of the variables. Because this works: 

```
      "environment_vars": [
        "VAR1=debug",
        "VAR2=debug",
        "VAR3=debug",
        "VAR4=debug"
      ],
```

but this does not: 

```
      "environment_vars": [
        "VAR1=debug",
        "VAR2=var2isreallylonglikethelongesteverwoooow",
        "VAR3=var3isalsoreallyheckinlongsuchlengthwow",
        "VAR4=not"
      ],
```

It looks like it's the combined variable length that's the problem, not individual length. I'm assuming we've exceed some max allowable length for encoding, and we're being truncated.   83 characters was the longest "$VAR=$VALUE" I could get to work.  

Also worth noting that this only occurs for elevated scripts. Non-elevated scripts handle dozens of variables fine.

**Comment by dhs-rec** [comment] 2017-09-14 06:30
Thanks for investigating. I'd use command line parameters in the script if at all possible...

**Comment by SwampDragons** [comment] 2017-09-14 17:41
Found the root cause I think. In version 0.12.2 we changed the default execute_command, making it much longer.  This would never have worked for as many variables as you wanted, but it is just enough to have made your script stop working based on the length of the variables you had.

The workaround I'd normally recommend (adding `"elevated_execute_command": "{{ .Vars }}{{ .Path }}",` to the provisioner where you install puppet) won't work because of another issue that means the provisioner fails to interpolate the config option correctly.  The good news is that this bug is easy to fix and I've already got it working in my test branch.  So I'll make sure the workaround gets fixed in the next release.

For now, I'm going to look into whether I can figure out how to make the elevated provisioner's variable handling behave as well by default as the non-elevated provisioner.

**Closed** 2017-09-15 16:12 UTC
Labels: bug, builder/amazon, windows-guest
