### ISSUE TITLE
Virtualbox 'Retryable error' not handled

### ISSUE THREAD

**Issue by ciarancourtney** [hashicorp/packer#8296] opened 2019-10-31 10:27 UTC
#### Overview of the Issue

VirtualBox has certain errors that don't appear in packer output unless you set `PACKER_LOG=1`, incl:

    Retryable error: port 3389 cannot be opened: listen tcp 0.0.0.0:3389: bind: address already in use

resulting in packer output stalling without any indication of whats at fault.

#### Reproduction Steps

Start a VM with a conflicting param like RDP port above, and start a packer build with the same. Packer output will stall at import step indefinitely.

In my case the running VM is a vagrant machine built from the same packer build.

Feel free to mark as duplicate or retitle issue if there are many more hidden errors that packer is not handling.

### Packer version

v1.4.4

**Comment by ciarancourtney** [comment] 2019-10-31 10:42
Also I checked my `Vagrantfile` as I assumed I had port 3389 set in there, but it isn't. I assume this is inherited from the packer build config, so this may be a common gothca worth pointing out.

My config:

```json
      "vrdp_bind_address": "0.0.0.0",
      "vrdp_port_min": 3389,
      "vrdp_port_max": 3389,
```

Should this be a post-processor setting to disable RDP?

**Comment by SwampDragons** [comment] 2019-11-04 23:08
Can you provide a full (minimal) template for reproducing this?

**Comment by SwampDragons** [comment] 2019-11-04 23:37
Also, are you using the virtualbox builder, or the vagrant builder?

**Comment by SwampDragons** [comment] 2020-03-18 23:00
Closing because I never heard back.

**Closed by SwampDragons** 2020-03-18 23:00 UTC
Labels: bug, builder/virtualbox, waiting-reply

**Comment by ciarancourtney** [comment] 2020-03-19 07:48
Sorry couldn't repro specific RDP issue in latest packer/vbox, may have been fixed
