### ISSUE TITLE
MSI - fails to login due to tenant ID missing from header. 

### ISSUE THREAD

**Issue by ashleyhull-versent** [hashicorp/packer#7301] opened 2019-02-11 09:49 UTC
https://github.com/hashicorp/packer/blob/0c47092ec92c78584ea8218ad62f97a9cd9adaa6/builder/azure/arm/authenticate_msi.go#L22

The current path is not correct for MSI token with the tentantID.

I don't believe the getServicePrincipalTokenWithResource path is correct as documented here.

The path/header should include similar to this `curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s`

EDIT: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-go

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17537000/52555427-a7c64500-2e24-11e9-92c5-c7ccac9291be.png">

**Comment by boumenot** [comment] 2019-02-11 17:18
@paulmey - looks like another dupe of #7267.

**Comment by paulmey** [comment] 2019-02-11 17:57
This looks more like it's trying to do client-id based login while it whould be using MSI. @ashleyhull-versent, can you tell me which authentication options you specified?

**Comment by ashleyhull-versent** [comment] 2019-02-12 01:34
@paulmey none. 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/17537000/52605300-2f559780-2ea9-11e9-81f9-68412ccc697b.png">

**Comment by ashleyhull-versent** [comment] 2019-02-12 02:19
Looking at the code.. FindTenantID seems to be function erroring out...

**Comment by paulmey** [comment] 2019-02-12 08:49
Sounds like we need another fix. I'll take a look tomorrow.

**Comment by ashleyhull-versent** [comment] 2019-02-18 07:37
@paulmey Harder problem than expected?

**Closed** 2019-02-25 16:25 UTC
Labels: bug, builder/azure
