### ISSUE TITLE
Latest packer can't find a free vnc port and fails

### ISSUE THREAD

**Issue by casualjim** [hashicorp/packer#5109] opened 2017-07-08 00:24 UTC
Packer can't find a free vnc port and fails, downgrading to 1.0.0 makes it work (haven't tried 1.0.1)

packer version: 1.0.2
ESXi 6.5 (fully patched)
debug log: https://gist.github.com/casualjim/e5045cc09ca23a288d646da1afc9a383
image.json: https://gist.github.com/casualjim/ccc267bbcf144b38489658d4df97abf2

**Comment by rickard-von-essen** [comment] 2017-07-08 06:53
Thanks for reporting this. This is a duplicate of #5055, which have been fixed on master. The fix will be included in the next release.

**Comment by rickard-von-essen** [comment] 2017-07-08 06:54
There is a simple workaround in there.

**Closed by rickard-von-essen** 2017-07-08 06:53 UTC

**Comment by ilamurugu** [comment] 2017-10-26 12:55
Can you please let me know the work around for this issue? I am still facing the issue with ver 1.1.0

**Comment by mwhooker** [comment] 2017-10-26 16:13
You can fix this by setting the env var PACKER_ESXI_VNC_PROBE_TIMEOUT to 30s
