### ISSUE TITLE
Ubuntu 18.04 HVM AMI with instance root won't boot 

### ISSUE THREAD

**Issue by kvz** [hashicorp/packer#6974] opened 2018-11-08 14:30 UTC
I got it to work with older Ubuntu versions (14.04 and 16.04). Through no fault of Packer's it's a bit of a hacky process (having to modify the bundler command to use `-P mbr` and modifying the `/boot/grub/menu.lst` to match `/proc/cmdline`)--but it works.

As reported in <https://github.com/hashicorp/packer/issues/2948> however it seems the ec2 ami tools rely on Grub 1. Grub 1 can still be installed on Trusty and Xenial, but it is not available in Bionic's Apt repositories.

Quite desperate, I removed Grub 2 and installed Grub 1 on Bionic via:

```bash
sudo -HE env PATH=${PATH} apt-get --option Dpkg::Options::="--force-confdef" --option Dpkg::Options::="--force-confnew" -q -y --allow-downgrades --allow-remove-essential --allow-change-held-packages remove grub-legacy-ec2 grub-pc grub2-common grub2

cd /tmp
wget http://archive.ubuntu.com/ubuntu/pool/main/g/grub/grub_0.97-29ubuntu66_amd64.deb
sudo -HE env PATH=${PATH} dpkg -i grub_0.97-29ubuntu66_amd64.deb 
```

.. and that _seemed_ to work (all the expected packer command output), but resulted in an unbootable AMI. I would be very interested to learn if/how anybody got building an HVM AMI with instanceroot on Ubuntu Bionic to work.

**Comment by rickard-von-essen** [comment] 2018-12-05 08:10
Probably related to [this discussion on the mailing list](https://groups.google.com/d/msg/packer-tool/6W9ugH-CVOU/2qKi-qP7BwAJ) (that doesn't contain any resolution).

**Comment by rickard-von-essen** [comment] 2018-12-05 08:12
I'll close this since this is most likely not a bug in packer but rather a usage issue. We can reopen this if the are evidence of the contrary.

**Closed by rickard-von-essen** 2018-12-05 08:12 UTC
Labels: builder/amazon, need-more-info, question

**Comment by kvz** [comment] 2018-12-05 08:55
You might be right and I am fine with this issue closed to reduce chatter for you all. It would be nice if someone ran into this, they'd share the solution here though :) Packer is unusable for ubuntu 18 i think. That mailing list issue seems unrelated to me tho, was that a paste error?

**Comment by ScottBrenner** [comment] 2018-12-05 20:09
@kvz Have you tried the [`grub-legacy-ec2`](https://packages.ubuntu.com/bionic/grub-legacy-ec2) package?

**Comment by kvz** [comment] 2018-12-05 22:41
indeed yes

**Comment by ScottBrenner** [comment] 2018-12-05 23:34
I'm not sure that `grub` 2 is at fault here, I was able to build a _paravirtual_ 16.04 image with
```
$ grub version
grub-install (GRUB) 2.02~beta2-36ubuntu3.19
```
so I think it's an HVM issue. Unfortunately, all base 18.04 AMIs are HVM..

**Comment by ScottBrenner** [comment] 2018-12-07 00:45
@kvz I was able to create a bootable 18.04 HVM AMI that is EBS-backed (https://www.packer.io/docs/builders/amazon-ebs.html).

**Comment by kvz** [comment] 2018-12-07 06:52
Correct same here but not for instance store

**Comment by adamgit** [comment] 2020-02-08 23:32
Over a year later ... and Amazon's official docs still demand the impossible for current Ubuntu - "install grub legacy" (which doesn't exist any more).

Did anyone find a workaround for this in the end?
