### ISSUE TITLE
Build 'vsphere-iso.aus_centos7_template' errored after 1 minute 52 seconds: Error running boot command: error typing a boot command (code, down) `82, false`: ServerFaultCode: Permission to perform this operation was denied.

### ISSUE THREAD

**Issue by olivedevelop** [hashicorp/packer#10769] opened 2021-03-16 19:34 UTC
Hello Hashicorp,
I am trying to build a centos7 vm on vSphere and packer is returning the following error: Error running boot command: error typing a boot command (code, down) `82, false`: ServerFaultCode: Permission to perform this operation was denied.

I am using vSphere Client version 6.7.0.46000 and packer 1.6.6 on macos.

Could you please help me to troubleshoot this ?
Best Regards,

**Comment by sylviamoss** [comment] 2021-03-17 10:30
Hello @olivedevelop. Can you provide more details to help us reproduce the issue? The template you're using and also the detailed output logs.
The output logs you can get by setting PACKER_LOG=1.

**Comment by olivedevelop** [comment] 2021-03-17 16:12
Sorry, I am not allowed to do that

**Comment by sylviamoss** [comment] 2021-03-19 10:07
I saw you open a topic in our discuss forum and I think you did right. This seems to be some permissions problem and not Packer one. I'll close the issue and follow up at https://discuss.hashicorp.com/t/packer-centos-vm-for-vsphere-build-returns-error/22219/2.

**Closed by sylviamoss** 2021-03-19 10:07 UTC
Labels: builder/vsphere
