### ISSUE TITLE
packer build returns non-zero exit code when build sets required source attributes

### ISSUE THREAD

**Issue by otyaglo** [hashicorp/packer#11040] opened 2021-05-24 05:32 UTC
### Scenario
- common source template (e.g. `amazon-ebs`)
- multiple builds with the same source
- source template limited to common attributes only
- build section specifies remaining source template attributes

### Expected results
- packer build returns exit code `0`
- no source errors shown

### Actual Results
- packer throws error message on missing required source template attribute(s)
- packer successfully produces all required artifacts (works as expected)
- packer returns non-zero exit code

### Error Details
```
$ ./packer init ./pkr
# ./packer build -var security_group_id=${AWS_SECURITY_GROUP_ID} -var subnet_id=${AWS_SUBNET_ID} -var version=${VERSION} ./pkr
Error: 5 error(s) occurred:
* ami_name must be specified
* ami_name must be between 3 and 128 characters long
* An ssh_username must be specified
  Note: some builders used to default ssh_username to "root".
* A source_ami or source_ami_filter must be specified
* For security reasons, your source AMI filter must declare an owner.
  on pkr/source.pkr.hcl line 5:
  (source code not available)
amazon-ebs.amzn2: output will be in this color.
amazon-ebs.ubuntu-18.04: output will be in this color.
amazon-ebs.ubuntu-20.04: output will be in this color.

... skip irrelevant packer and its provisioner output

==> Wait completed after 18 minutes 18 seconds
==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs.amzn2: AMIs were created:
us-west-2: ami-0cbd420dcd880d868
--> amazon-ebs.ubuntu-18.04: AMIs were created:
us-west-2: ami-0c4b8de836cf13a12
--> amazon-ebs.ubuntu-20.04: AMIs were created:
us-west-2: ami-0467675198d13ca55
```

### Environment
- packer version: 1.7.2
- OS: linux & macos

#### pkr/source.pkr.hcl
```
source amazon-ebs ami {
  ami_description = var.recipe
  ami_regions = var.ami_regions
  ami_users = var.account_ids
  block_duration_minutes = 60
  encrypt_boot = true
  instance_type = var.instance_type
  kms_key_id = var.kms_key
  security_group_id = var.security_group_id
  spot_price = var.spot_price
  ssh_interface = "public_ip"
  subnet_id = var.subnet_id
}
```

#### `pkr/build.pkr.hcl`
```
build {
  sources = ["source.amazon-ebs.ami"]

  source "amazon-ebs.ami" {
    ami_name = "hardening/${var.recipe}/${var.version}/amzn2"
    name = "amzn2"
    run_tags = merge(local.run_tags, { Platform = "amazon", Release = "2" })
    source_ami = data.amazon-ami.amzn2.id
    ssh_username = "ec2-user"
    tags = merge(local.tags, {
      Platform = "amazon"
      Release = "2"
      SourceAMI = "{{ .SourceAMI }}"
      SourceAMIName = "{{ .SourceAMIName }}"
      SourceAMICreationDate = "{{ .SourceAMICreationDate }}"
    })
  }

  source "amazon-ebs.ami" {
    ami_name = "hardening/${var.recipe}/${var.version}/ubuntu-bionic-18.04-amd64"
    name = "ubuntu-18.04"
    run_tags = merge(local.run_tags, { Platform = "ubuntu", Release = "18.04" })
    source_ami = data.amazon-ami.ubuntu18.id
    ssh_username = "ubuntu"
    tags = merge(local.tags, {
      Platform = "ubuntu"
      Release = "18.04"
      SourceAMI = "{{ .SourceAMI }}"
      SourceAMIName = "{{ .SourceAMIName }}"
      SourceAMICreationDate = "{{ .SourceAMICreationDate }}"
    })
  }

  source "amazon-ebs.ami" {
    ami_name = "hardening/${var.recipe}/${var.version}/ubuntu-focal-20.04-amd64"
    name = "ubuntu-20.04"
    run_tags = merge(local.run_tags, { Platform = "ubuntu", Release = "20.04" })
    source_ami = data.amazon-ami.ubuntu20.id
    ssh_username = "ubuntu"
    tags = merge(local.tags, {
      Platform = "ubuntu"
      Release = "20.04"
      SourceAMI = "{{ .SourceAMI }}"
      SourceAMIName = "{{ .SourceAMIName }}"
      SourceAMICreationDate = "{{ .SourceAMICreationDate }}"
    })
  }

  provisioner "chef-solo" {
    cookbook_paths  = ["cookbooks"]
    install_command = "curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v ${var.chef_version}"
    json_string = jsonencode({
      hardening = {
        cis = {
          level = 1
        }
      }
    })
    run_list          = [ "${var.cookbook}::${var.recipe}" ]
    staging_directory = "/var/chef"
  }
}
```

**Comment by nywilken** [comment] 2021-05-24 13:43
Hi @otyaglo thanks for reaching out. Looking at the provided build bock in `build.pkr.hcl` I see that you've included the common source template `sources = ["source.amazon-ebs.ami"]` as part of the build. This is the reason for the error messages. Packer will try to build every source defined within the build block and will only return a non-zero exit code if all builds complete without error. What you are seeing is the expected behavior as the common source template does not define all of the required attributes. 

If you remove `sources = ["source.amazon-ebs.ami"]` from your build block do you still encounter issues? 

When using a common source template each occurrence of it within the build block must contain different attributes and must contain all required attributes for the said source type. 

I'm going to close this issue because I believe it to be a configuration issue. If however I've made a mistake and you suspect that this is a bug or that we can improve the experience please feel free to follow up on the issue and I will gladly reopen.

**Closed by nywilken** 2021-05-24 13:43 UTC

**Comment by otyaglo** [comment] 2021-05-25 06:13
@nywilken - thank you!

"Failed to understand the Manual" on my side, "works on my machine" now ;)
