### ISSUE TITLE
Timeout for ec2 amazon-ebs 

### ISSUE THREAD

**Issue by PCSshell** [hashicorp/packer#6305] opened 2018-05-24 19:36 UTC
I am trying to build a custom AMI using the amazon-ebs builder. I am running into a timeout issue when building a Windows ec2 instance. I am configuring everything I need for the ec2 instance via the user_data_file including the sysprep of the instance and do not need to configure any communicators. The user data will configure the box and sysprep it, in addition it will shut down the instance. The issue I am running into is that there appears to be a hard timeout at 10 minutes for the build process, even if I specify the disable_stop_instance flag. I have had situations where the ec2 instance isn't even ready to retrieve the Windows password and it is being automatically terminated. I have successfully tested this exact setup using the -debug in the command and waiting for the instance to properly finish building with automatic shut down. Upon continuing the debug Packer will prepare the AMI successfully.

I have tried setting my AWS_TIMEOUT_SECONDS environment variable, but that does not seem to effect the timeout for this scenario.

Here is the output from running my build. 
[1;32m==> amazon-ebs: Waiting for instance (i-0f91949bf7f60cb8c) to become ready...[0m
[1;32m==> amazon-ebs: Automatic instance stop disabled. Please stop instance manually.[0m
[1;32m==> amazon-ebs: Waiting for the instance to stop...[0m
[1;31m==> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts[0m
[1;32m==> amazon-ebs: Terminating the source AWS instance...
[1;32m==> amazon-ebs: Cleaning up any extra volumes...[0m
[1;32m==> amazon-ebs: No volumes to clean up, skipping[0m
[1;32m==> amazon-ebs: Deleting temporary security group...[0m
[1;32m==> amazon-ebs: Deleting temporary keypair...[0m
[1;31mBuild 'amazon-ebs' errored: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts[0m
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
==> Builds finished but no artifacts were created.

here is my builder information to reproduce this issue.
"builders": [
      {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "root-device-type": "ebs",
          "name": "Windows_Server-2016-English-Full-Base*"
        },
        "owners": ["801119661308"],
        "most_recent": true
      },
      "instance_type": "t2.micro",
      "communicator": "none",
      "disable_stop_instance":"true",
      "ami_name": "AMI-test-{{isotime \"2006.01.02\"}}",
      "force_deregister": true,
      "force_delete_snapshot": true,
      "user_data_file": "./powershell.ps1",
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "delete_on_termination": true
        }
      ]

Windows 10 version 1803
Packer version 1.2.3

**Comment by mwhooker** [comment] 2018-05-24 22:41
Thanks very much for the report. I believe this is a duplicate of #6289, so going to track there

**Closed by mwhooker** 2018-05-24 22:41 UTC
