### ISSUE TITLE
docker-tag post-processor "only" not working

### ISSUE THREAD

**Issue by ximon18** [hashicorp/packer#7335] opened 2019-02-22 10:59 UTC
**Supporting data:**
- Packer version: 1.3.4
- Host platform: Ubunt 18.10
- Debug logs, packer templates and packer shell invocations used: https://gist.github.com/ximon18/2367ad3ee4fc988eceb88f32a5602bf1

**Issue summary:**
docker-tag post-processor is NOT invoked if "only" is used, but is invoked if "except" is used.
Per https://www.packer.io/docs/templates/post-processors.html#run-on-specific-builds I would expect it to work.
The gist shows nameless builders, but I also tried with named builders and the result was the same.

**Comment by azr** [comment] 2019-02-22 11:04
Hello, thanks for reporting and sorry for the inconvenience, this is a duplicate of #7285 and #7257. Everything should be fixed in #7330. Closing this issue for now as it is a duplicate.

**Closed by azr** 2019-02-22 11:04 UTC

**Comment by ximon18** [comment] 2019-02-22 11:07
Thanks for the prompt response. Apologies for the duplicate report. I saw #7330 but thought it wasn't applicable as it concerned unnamed post-processors.

**Comment by azr** [comment] 2019-02-22 11:17
No worries 🙂, #7257 was closed too soon.
