### ISSUE TITLE
Hyper-V: Virtual hard disk files must be uncompressed and unencrypted and must not be sparse. (0xC03A001A)

### ISSUE THREAD

**Issue by lovilak** [hashicorp/packer#9922] opened 2020-09-10 14:03 UTC
Hyper-V: Virtual hard disk files must be uncompressed and unencrypted and must not be sparse. (0xC03A001A)

With packer Hyperv-iso when i create a new VM which crash during the building with the above error.

Step to reproduce :
- windows2016 / ReFS  File System / Bit Integrity set to True for the all volume where Packer Build and push the vhdx.
- packer version : 1.6.2

**Comment by nywilken** [comment] 2020-09-10 17:35
Thanks for opening an issue -- In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and scripts needed to reproduce the bug.

Full debug log output from `PACKER_LOG=1 packer build template.json`.
Please paste this in a gist https://gist.github.com
The simplest complete example template and scripts needed to reproduce the bug.
Include these in your gist https://gist.github.com

Is the host running with ReFS with a compressed disk? If compressed, if you try building from a volume that is not compressed does it work differently? 

With that said, this error seems to becoming from Hyper-V and not Packer itself per-say. I found an old issue on Vagrant that might help https://github.com/hashicorp/vagrant/issues/11118. I also found an issue on technet https://social.technet.microsoft.com/Forums/en-US/757c76ba-a772-4dde-8baa-4db6de1016ce/vhd-must-be-uncompressed-and-unencrypted?forum=winserverhyperv

**Comment by lovilak** [comment] 2020-09-11 07:52
With some logs :
 error: ==> hyperv-iso: Error starting vm: PowerShell error: Hyper-V\Start-VM : echec du demarrage de 'new_vm.mydomain'.
==> hyperv-iso: Synthetic SCSI Controller (ID d'instance D0026033-B374-463E-A646-032FD72EB9F2): echec de la mise sous tension avec 
==> hyperv-iso: l'erreur Impossible d'effectuer l'operation demandee en raison d'une limitation du systeme de disque virtuel. Les 
==> hyperv-iso: fichiers de disque dur virtuel doivent etre non compresses et non chiffres, et ne doivent pas etre fragmentes.¯.
==> hyperv-iso: Impossible d'ouvrir la connexion \\mydomain\share\win2016.iso en 
==> hyperv-iso: raison de l'erreur suivante: Impossible d'effectuer l'operation demandee en raison d'une limitation du systeme de 
==> hyperv-iso: disque virtuel. Les fichiers de disque dur virtuel doivent etre non compresses et non chiffres, et ne doivent pas etre 
==> hyperv-iso: fragmentes..
==> hyperv-iso: echec du demarrage de new_vm.mydomain¯. (ID d'ordinateur virtuel 
==> hyperv-iso: 1FC0B495-AB11-4F7F-A49E-F54D19482DD8)
==> hyperv-iso: ®new_vm.mydomain¯ Synthetic SCSI Controller (ID d'instance 
==> hyperv-iso: D0026033-B374-463E-A646-032FD72EB9F2): echec de la mise sous tension avec l'erreur ®Impossible d'effectuer l'operation 
==> hyperv-iso: demand‚e en raison d'une limitation du systeme de disque virtuel. Les fichiers de disque dur virtuel doivent etre non 
==> hyperv-iso: compress‚s et non chiffres, et ne doivent pas etre fragment‚s.¯ (0xC03A001A). (ID d'ordinateur virtuel 
==> hyperv-iso: 1FC0B495-AB11-4F7F-A49E-F54D19482DD8)
==> hyperv-iso: new_vm.mydomain: impossible d'ouvrir la connexion 
==> hyperv-iso: \\mydomain\share\win2016.iso en raison de l'erreur suivante: 
==> hyperv-iso: Impossible d'effectuer l'operation demandee en raison d'une limitation du systeme de disque virtuel. Les fichiers de 
==> hyperv-iso: disque dur virtuel doivent etre non compresses et non chiffres, et ne doivent pas etre fragment‚s. (0xC03A001A). (ID 
==> hyperv-iso: d'ordinateur virtuel 1FC0B495-AB11-4F7F-A49E-F54D19482DD8)

**Comment by nywilken** [comment] 2020-09-11 20:23
Hi @lovilak thanks for the logs. I was hoping to see some addition Packer information that would hint at a Packer config related issue. But the provided logs, along with your comment about not having trouble on other host running running ReFS, seem to confirm that this is a hyper-v issue and not a Packer issue. So I'm not sure if I can reproduce without  setting up similar environment. 

I think checking for differences between the host is good way to go. 

I recommend reaching out to the [mailing list ](https://groups.google.com/g/packer-tool)or [community forum](https://discuss.hashicorp.com/c/packer/23). Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

I'll keep this open for now in case someone else can provide some guidance. Cheers!

**Comment by lovilak** [comment] 2020-09-21 07:37
Hello,
After some new tests it  seems that it wasn't a vhdx file disk file pb, but the  \\mydomain\share\win2016.iso file which pass the cksum step but I noticed that the packer_cache folder is empty on nodes where I have failure and not empty where the build succeed. So There is maybe a missconf on my side that I havn't found yet, or an issue between packer and the network share.

**Comment by nywilken** [comment] 2021-02-18 19:11
Hi there, @lovilak I'm going to close this issue, because it looks more like a Hyper-V bug than a Packer bug. If I've made a mistake and you have more evidence that this a Packer issue please reach out with the new details and we will gladly reopen.

**Closed by nywilken** 2021-02-18 19:11 UTC
Labels: bug, builder/hyperv
