### ISSUE TITLE
Packer not uploading Ansible scripts sporadically

### ISSUE THREAD

**Issue by TrentScholl** [hashicorp/packer#4607] opened 2017-02-28 00:15 UTC
I'm using Ansible remote with packer to build an EBS backed Windows AMI. Seemingly randomly, packer does not always successfully upload the Ansible Powershell scripts which causes errors such as "The term 'win_file.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

It is not specific to any Ansible module or playbook. Every second or third execution, it all goes through completely fine and the AMI is created successfully.

On a successful execution, the log shows the following:

```
2017/02/27 23:56:48 packer: 2017/02/27 23:56:48 Uploading file to ''C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1488239807.84-59106906656116\win_get_url.ps1''
2017/02/27 23:56:49 packer: 2017/02/27 23:56:49 rejecting auth-agent-req@openssh.com request
```

On a failed upload, it shows this:

```
2017/02/27 23:59:58 packer: 2017/02/27 23:59:58 Uploading file to ''win_file.ps1''
2017/02/27 23:59:59 packer: 2017/02/27 23:59:59 rejecting auth-agent-req@openssh.com request
```

It seems that for some reason it's not putting the path in?

Packer version: 0.12.2
Host: Amazon Linux
Guest: Windows 2008 R2
Ansible version: 2.2.0.0

Packer Template and snippet of failure log: https://gist.github.com/TrentScholl/4df076b1ed6d8c5e4e466c0f8aa8290d

**Comment by TrentScholl** [comment] 2017-02-28 22:37
I've been having much better luck with ansible_env_vars -o ControlMaster=No -o ControlPersist=0s 

It seems that maybe Ansible is expecting the scp session to be copying files to a certain directory based on a previous upload and forcing it to reconnect each time makes sure the full path is specified every time.

**Comment by SwampDragons** [comment] 2017-09-11 21:41
I've seen this error message when troubleshooting other powershell bugs recently.  I'd be curious to know if this problem still exists in the 1.1.0 release, because I've added some checking to make sure we don't try to run scripts before winrm is fully connected and functioning.

**Comment by SwampDragons** [comment] 2018-12-13 00:31
Closing because I think this is a duplicate of #7039 and the mechanism isn't ansible-specific; I think the information in that ticket is more useful for debugging.

**Closed by SwampDragons** 2018-12-13 00:31 UTC
Labels: bug, duplicate, provisioner/ansible-remote
