### ISSUE TITLE
can't interpolate variables into build.source attribute

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/packer#11193] opened 2021-08-06 19:45 UTC
This seems like an obvious thing to do?  It works in one location but not in the other?
```
build {
  source "source.amazon-ebs.amzn2_${local.machine_name}" {}  # this breaks
  provisioner "shell" {
    script = "./packer/${local.machine_name}/scripts/setup.sh"  # but this works just fine?
  }
}
```

```
Error: Invalid string literal

  on packer/machines/redis.pkr.hcl line 22, in build:
  22:   source "source.amazon-ebs.amzn2_${local.machine_name}" {}

Template sequences are not allowed in this string. To include a literal "$",
double it (as "$$") to escape it.
```

**Comment by azr** [comment] 2021-12-03 16:36
Hello there, this is the case by design on the HCL2 library, arguably, labels are here to label blocks and make them easy to find and relate to, so if their name was variable-able this could make things quite confusing.

I'd recommend opening an issue over in github.com/hashicorp/hcl if you really think this is a good idea.
Closing for now.

**Closed by azr** 2021-12-03 16:36 UTC
Labels: bug, track-internal
