### ISSUE TITLE
var-file path is being ignored from the dot ahead

### ISSUE THREAD

**Issue by felixep** [hashicorp/packer#5809] opened 2018-01-22 20:38 UTC
I tried to pass a file to packer with my variables and I figured packer is ignoring everything from the dot (".") ahead.

Here you have an example, I set the path as jenkins/packer/variables.json and packer is giving me the following error

```
invalid value "jenkins/packer/variables" for flag -var-file: open 
jenkins/packer/variables: The system cannot find the file specified. Usage: 
packer validate [options] TEMPLATE    Checks the template is valid by parsing 
the template and also   checking the configuration with the various builders, 
provisioners, etc.    If it is not valid, the errors will be shown and the 
command will exit   with a non-zero exit status. If it is valid, it will exit 
with a zero   exit status.  Options:    -syntax-only           Only check 
syntax. Do not verify config of the template.   -except=foo,bar,baz    
Validate all builds other than these   -only=foo,bar,baz      Validate only 
these builds   -var 'key=value'       Variable for templates, can be used 
multiple times.   -var-file=path         JSON file containing user variables.
```

I removed the extension of the file and it worked OK.

Note, I'm using packer in windows and executing it from powershell. The version I'm using is 
> packer -version
1.1.3

**Comment by mwhooker** [comment] 2018-01-23 00:41
will investigate when I have access to a windows machine

**Comment by mwhooker** [comment] 2018-01-25 21:22
not able to reproduce this. Can you post the command you use to invoke packer?

**Comment by SwampDragons** [comment] 2019-08-12 21:30
Closing because user never responded.

**Closed by SwampDragons** 2019-08-12 21:30 UTC
Labels: core, need-repro, question, windows-host
