### ISSUE TITLE
ERROR! the playbook: packer_builder_type=vmware-iso could not be found

### ISSUE THREAD

**Issue by ChrisMcKee** [hashicorp/packer#5894] opened 2018-02-13 17:08 UTC
##Playbook

```
{
    "builders": [
      {
        "name": "ubuntu16-consul",
        "vm_name": "ubuntu16-consul-{{timestamp}}",
        "vmdk_name": "ubuntu16-consul",
        "type": "vmware-iso",
        "guest_os_type": "ubuntu-64",
        "tools_upload_flavor": "linux",
        "headless": true,
        "iso_url": "http://releases.ubuntu.com/xenial/ubuntu-16.04.3-server-amd64.iso",
        "iso_checksum": "a06cd926f5855d4f21fb4bc9978a35312f815fbda0d0ef7fdc846861f4fc4600",
        "iso_checksum_type": "sha256",
        "ssh_username": "ubuntu",
        "ssh_password": "ubuntu",
        "ssh_timeout": "15m",
        "vnc_port_min": "5900",
        "vnc_port_max": "5911",
        "vnc_bind_address": "0.0.0.0",
        "vnc_disable_password": "true",
        "floppy_files": [
          "preseed/ubuntu.cfg"
        ],
        "boot_command": [
          "<enter><wait><f6><esc><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
          "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
          "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
          "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
          "/install/vmlinuz noapic ",
          "preseed/file=/floppy/ubuntu.cfg ",
          "debian-installer=en_GB auto locale=en_GB.UTF-8 kbd-chooser/method=gb ",
          "hostname={{ .Name }} ",
          "fb=false debconf/frontend=noninteractive ",
          "keyboard-configuration/modelcode=SKIP FUSA ",
          "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
          "grub-installer/bootdev=/dev/sda ",
          "initrd=/install/initrd.gz -- <enter>"
        ],
        "shutdown_command": "echo 'shutdown -P now' > shutdown.sh; echo 'ubuntu'|sudo -S sh 'shutdown.sh'",
        "vmx_data": {
          "cpuid.coresPerSocket": "2",
          "memsize": "2048",
          "numvcpus": "1"
        },
        "keep_registered": true
      }
    ],
    "provisioners": [
      {
        "type": "shell",
        "inline": [
          "sudo apt-get update -qy",
          "sudo apt-get upgrade -qy",
          "sudo apt-get dist-upgrade -qy",
          "sudo apt-get autoremove -qy",
          "sudo usermod -G sudo ubuntu",
          "sudo apt-get install -y python-pip libssl-dev",
          "sudo sed -i 's/^#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/' /etc/ssh/sshd_config",
          "echo 'net.ipv6.conf.all.disable_ipv6 = 1' | sudo tee -a /etc/sysctl.d/10-disable-ipv6.conf",
          "echo 'net.ipv6.conf.default.disable_ipv6 = 1' | sudo tee -a /etc/sysctl.d/10-disable-ipv6.conf",
          "echo 'net.ipv6.conf.lo.disable_ipv6 = 1' | sudo tee -a /etc/sysctl.d/10-disable-ipv6.conf"
        ]
      },
      
      {
        "type": "shell",
        "inline": [
          "sudo apt-add-repository ppa:ansible/ansible",
          "sudo apt-get update && sudo apt-get install -y ansible",
          "sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y",
          "sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
        ],
        "environment_vars": [
          "DEBIAN_FRONTEND=noninteractive"
        ]
      },
      {
        "type": "ansible-local",
        "playbook_file": "consulcluster-playbook.yml",
        "role_paths": [
          "../roles/ansible-consul"
        ],
        "inventory_groups":"consul_instances"
      }
    ]
  }
```

##Preseed file

```
#
# Based upon: https://help.ubuntu.com/lts/installation-guide/example-preseed.txt
#

#### Contents of the preconfiguration file (for xenial)
### localization
# Preseeding only locale sets language, country and locale.
d-i debian-installer/locale string en_US.UTF-8
d-i console-setup/ask_detect boolean false
d-i keyboard-configuration/layoutcode string gb

# networking
d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string ubuntu16
d-i netcfg/get_domain string internal
d-i netcfg/wireless_wep string

# IPv4
# d-i netcfg/disable_autoconfig boolean true
# d-i netcfg/get_ipaddress string 192.168.1.126
# d-i netcfg/get_netmask string 255.255.255.0
# d-i netcfg/get_gateway string 192.168.1.1
# d-i netcfg/get_nameservers string 192.168.1.1
# d-i netcfg/confirm_static boolean true

# apt mirrors
d-i mirror/country string manual
d-i mirror/http/hostname string archive.ubuntu.com
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string

# clock and time zone
d-i clock-setup/utc boolean true
d-i time/zone string UTC
#d-i time/zone string GMT
d-i clock-setup/ntp boolean true

# partitioning
# regular
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true

# lvm
#d-i partman-auto/method string lvm
#d-i partman-lvm/device_remove_lvm boolean true
#d-i partman-md/device_remove_md boolean true
#d-i partman-lvm/confirm boolean true
#d-i partman-lvm/confirm_nooverwrite boolean true
#d-i partman-auto-lvm/guided_size string max
#d-i partman-auto/choose_recipe select atomic
#d-i partman-partitioning/confirm_write_new_label boolean true
#d-i partman/choose_partition select finish
#d-i partman/confirm boolean true
#d-i partman/confirm_nooverwrite boolean true

# users
d-i passwd/user-fullname string ubuntu
d-i passwd/username string ubuntu
d-i passwd/user-password password ubuntu
d-i passwd/user-password-again password ubuntu
d-i user-setup/allow-password-weak boolean true
d-i user-setup/encrypt-home boolean false

# packages
tasksel tasksel/first multiselect standard
d-i pkgsel/install-language-support boolean false
d-i pkgsel/include string openssh-server htop curl unzip vim zsh zip jq tmux libterm-readline-gnu-perl open-vm-tools software-properties-common python-software-properties
d-i pkgsel/upgrade select full-upgrade

# Policy for applying updates. May be:
# "none" (no automatic updates),
# "unattended-upgrades" (install security updates automatically), or
# "landscape" (manage system with Landscape).
d-i pkgsel/update-policy select unattended-upgrades

# boot loader
d-i grub-installer/only_debian boolean true

# hide the shutdown notice
d-i finish-install/reboot_in_progress note

# allow passwordless sudo
d-i preseed/late_command string \
    echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' > /target/etc/sudoers.d/ubuntu ; \
    in-target chmod 440 /etc/sudoers.d/ubuntu ;
``` 

##Error 

```
    ubuntu16-consul: Creating directory: /tmp/packer-provisioner-ansible-local/5a8314f9-1b5a-788f-8a84-a7f5f7f32283/roles/ansible-consul
    ubuntu16-consul: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/5a8314f9-1b5a-788f-8a84-a7f5f7f32283 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/5a8314f9-1b5a-788f-8a84-a7f5f7f32283/consulcluster-playbook.yml --extra-vars \"packer_build_name=ubuntu16-consul packer_builder_type=vmware-iso packer_http_addr=\"  -c local -i /tmp/packer-provisioner-ansible-local/5a8314f9-1b5a-788f-8a84-a7f5f7f32283/packer-provisioner-ansible-local399435279
    ubuntu16-consul: ?[0;31mERROR! the playbook: packer_builder_type=vmware-iso could not be found?[0m
==> ubuntu16-consul: Step "StepProvision" failed, aborting...
Build 'ubuntu16-consul' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> ubuntu16-consul: unexpected EOF

==> Builds finished but no artifacts were created.
```

Is there anyway of not passing the noise that packer passes to Ansible on extra-vars as it breaks Ansible and serves no visible purpose?

Running without the vmware-iso etal bit runs fine.

![image](https://user-images.githubusercontent.com/83597/36163059-1c5538da-10e0-11e8-9468-2e3f8659b5d7.png)

**Comment by SwampDragons** [comment] 2018-02-13 17:15
I think this is a dupe of https://github.com/hashicorp/packer/issues/5885 and should already have been fixed on master.  Sorry for the regression -- if you'd like, I can upload a binary containing the patch (I need to know your host architecture though).

**Closed by SwampDragons** 2018-02-13 17:15 UTC

**Comment by ChrisMcKee** [comment] 2018-02-13 17:17
@SwampDragons that would be great; windows 10 please 👍 
I did check that issue but it was closed and I could see the revert after the fix.

**Comment by SwampDragons** [comment] 2018-02-13 17:22
[packer.zip](https://github.com/hashicorp/packer/files/1720901/packer.zip)
Here it is in a zip file since github won't let us upload .exe files.  Just unzip and you should be good to go.  Let me know if this build doesn't solve your issue; I'll reopen the ticket.

**Comment by ChrisMcKee** [comment] 2018-02-13 17:27
💥 `Program 'packer.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1`

**Comment by ChrisMcKee** [comment] 2018-02-13 17:35
[packer.zip](https://github.com/hashicorp/packer/files/1720953/packer.zip)

If anyone needs it; I'll run it through now check for anything fresh

**Comment by SwampDragons** [comment] 2018-02-13 17:46
That's really really odd -- it works on my windows 10 vm...

**Comment by ChrisMcKee** [comment] 2018-02-13 17:50
I just repacked it and attached above; all good 👍 seems to work fine (as in it bailed on my mistake rather than something weird) 😆

**Comment by SwampDragons** [comment] 2018-02-13 17:55
aha cool!  Glad it's working now.  Let us know if you find any more problems in your 1.2.1-dev build.
