### ISSUE TITLE
Error running boot command: error typing a boot command (code, down) `43, false`: ServerFaultCode: Permission to perform this operation was denied

### ISSUE THREAD

**Issue by lnbnatera** [hashicorp/packer#10159] opened 2020-10-23 10:13 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I've been using packer 1.5.6 with vcenter 6.5 and boot_command works well.  After upgrading to vcenter 6.7, the error started to come out.  I tried to use an updated packer, 1.6.4 and the issue remains the same

#### Reproduction Steps

Deploy a Linux VM (Ubuntu, Centos, RedHat) in vcenter 6.7

### Packer version

From `packer version`
1.5.6 and 1.6.4

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment] 2020-10-23 13:38
Hi there @lnbnatera thanks for reaching out. There have been a few changes to the boot command for vsphere since 1.5.6, but the error message seems to imply some sort of permission issue. In order for us to best help can you please provide the debug logs `PACKER_LOG=1 packer build <template>` along with a copy of a template that we can use to try and reproduce the issue. 

With that said, have you seen issue https://github.com/jetbrains-infra/packer-builder-vsphere/issues/126#issuecomment-573264499? It may be related.

**Comment by lnbnatera** [comment] 2020-10-24 04:00
On that link, I did try to use the older version of packer along with the corresponding vsphere-iso plugin and it has resulted to the same error.
I don't think this is a permission issue.  If the same user is logged in to vsphere via browser, that user can type in the guest console, but packer cannot.

**Comment by vheon** [comment] 2020-11-02 13:53
@lnbnatera you should check the link for the permission and check that you have "Inject USB HID scan codes" permission. The fact that the user can type in the guest console is not relevant because when using packer you're using the APIs to simulate the typing by injecting usb HID scan codes so if you don't have the right permission to do it the `boot_command` will not work. I've experience this as well so I know it for a fact 😜

**Comment by tsia** [comment] 2020-12-04 15:31
i'm having the same issue.

i have 2 vSphere Instances. One (6.7.0.44000) is working fine, the other (6.7.0.46000) isn't.

i have double-checked the permissions on both.

when i use a different user that has no "Inject USB HID scan codes" permission i get a different error (which makes sense):
```
==> vsphere-iso: Error running boot command: error typing a boot command (code, down) `82, false`: ServerFaultCode: Permission to perform this operation was denied.
```

**Comment by tsia** [comment] 2021-01-07 13:50
i did some more research.
this is the Request that is sent to vSphere:
```xml
Host:               <redacted>
User-Agent:         Go-http-client/1.1
Transfer-Encoding:  chunked
Content-Type:       text/xml; charset="utf-8"
Cookie:             vmware_soap_session=<redacted>
Soapaction:         urn:vim25/7.0
Accept-Encoding:    gzip

<?xml version="1.0" encoding="UTF-8"?>
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
  <Body>
    <PutUsbScanCodes xmlns="urn:vim25">
      <_this type="VirtualMachine">vm-37930</_this>
      <spec>
        <keyEvents>
          <usbHidCode>5373959</usbHidCode>
          <modifiers>
            <leftControl>false</leftControl>
            <leftShift>false</leftShift>
            <leftAlt>false</leftAlt>
          </modifiers>
        </keyEvents>
      </spec>
    </PutUsbScanCodes>
  </Body>
</Envelope>
```
it is the same in both cases. The only differences are the `Host` header, the `vmware_soap_session` Cookie and the `VirtualMachine` number

the looks like this:
```xml
Date:            Thu, 7 Jan 2021 13:24:48 GMT
Cache-Control:   no-cache
Connection:      Keep-Alive
Content-Type:    text/xml; charset=utf-8
Content-Length:  599

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <soapenv:Fault>
      <faultcode>ServerFaultCode</faultcode>
      <faultstring>Cannot complete the operation due to an incorrect request to the server.</faultstring>
      <detail>
        <InvalidRequestFault xmlns="urn:vim25" xsi:type="InvalidRequest"></InvalidRequestFault>
      </detail>
    </soapenv:Fault>
  </soapenv:Body>
</soapenv:Envelope>
```

on the vSphere instance where it's working it looks like this:
```xml
Date:            Thu, 7 Jan 2021 13:30:38 GMT
Cache-Control:   no-cache
Connection:      Keep-Alive
Content-Type:    text/xml; charset=utf-8
Content-Length:  420

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <PutUsbScanCodesResponse xmlns="urn:vim25">
      <returnval>1</returnval>
    </PutUsbScanCodesResponse>
  </soapenv:Body>
</soapenv:Envelope>
```

**Comment by tsia** [comment] 2021-01-11 11:15
Guys, i think i figured it out!
I'm still waiting for confirmation from our VMware People but it looks like this:
the slightly different vSphere Version doesn't seem to make any difference.
vSphere is on 6.7 but (some) ESX Hosts are still running on 6.0. if the VM is on one of those, PutUsbScanCodes() doesn't work. obviosly.

**Comment by sylviamoss** [comment] 2021-03-30 10:11
I'm closing this issue. This seems to be not Packer related. If you still have this issue after the purposed solutions in this thread, I suggest you reach out to the community at our [discuss forum](https://discuss.hashicorp.com/c/packer/23)

**Closed by sylviamoss** 2021-03-30 10:11 UTC
Labels: bug, builder/vsphere, need-more-info
