### ISSUE TITLE
Instance metadata lookup failure when run in ECS

### ISSUE THREAD

**Issue by schmiddy** [hashicorp/packer#7133] opened 2018-12-19 22:28 UTC
I discovered that `packer build ...` fails while running under a Docker container (an AWS-provided image for CodeBuild), with an error about:
```
Could not get region, probably because it's not set or we're not running on AWS. RequestError: send request failed
 caused by: Get http://169.254.169.254/latest/meta-data/placement/availability-zone: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)·[0m
```

I suppose the instance metadata URL (`http://169.254.169.254`) doesn't exist for docker containers in ECR, but I don't understand why this is a fatal error in this case. Is there some workaround?

- Host platform: ECS container running under CodeBuild, using Amazon's provided [aws/codebuild/python:3.7.1](https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/python/3.7.1) image which is an option for CodeBuild.
- packer version: 1.3.3
- How to reproduce: install packer 1.3.3 on the `python:3.7.1` ECS container, and run a packer build for the `amazon-ebs` builder like so:

```
AWS_DEFAULT_REGION=us-west-2 PACKER_LOG=1 packer build -var 'source_ami_id=ami-xxxx' -var 'manifest_file=/tmp/tmpq1e8zdhm' ./packer/instancetype/instancetype.json
```

- Debug log output from `PACKER_LOG=1 packer build template.json`: [here](https://gist.github.com/schmiddy/ee6832f982f18b7a58189452a064f38c#file-packer-build-ecs-error)

**Comment by ephemeralsnow** [comment] 2018-12-20 04:08
I have a similar problem.
I think that this fix was not good.
https://github.com/hashicorp/packer/pull/6931/files

**Comment by ephemeralsnow** [comment] 2018-12-20 04:21
It now worked by specifying `region` explicitly.
reference
https://github.com/hashicorp/packer/issues/7053

**Comment by schmiddy** [comment] 2018-12-21 15:49
Thanks for the workaround @ephemeralsnow , that seems to work.

**Comment by rickard-von-essen** [comment] 2018-12-22 13:09
Closing this as a duplicate of #6919

**Closed by rickard-von-essen** 2018-12-22 13:09 UTC
Labels: bug, builder/amazon, duplicate
