### ISSUE TITLE
iso_checksum_type: none causing "416 Requested Range Not Satisfiable"

### ISSUE THREAD

**Issue by bissli82** [hashicorp/packer#6634] opened 2018-08-27 06:51 UTC
Hey, I'm trying to ignore iso checksum while packering a box, 
and getting download iso errors (working just fine with md5 checksum enabled)

- Packer version:
Packer v1.2.5
- Host platform:
CentOS Linux release 7.5.1804

- Debug log output from `PACKER_LOG=1 packer build template.json`: 
https://gist.github.com/bissli82/a6c061f9f44c33f6e851d90cc7bdf5e2

- The _simplest example template and scripts_ needed to reproduce the bug:
https://gist.github.com/bissli82/ab2baac485c0bae6290c9bcbf22a9f58

Output above is *with* options enabled:
"iso_checksum": "{{ user `rh_7.5_x86_iso_checksum` }}",
 "iso_checksum_type": "md5",

**Comment by rickard-von-essen** [comment] 2018-09-14 06:17
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by sbocinec** [comment] 2019-05-03 13:58
I experience the same issue using virtualbox-ovf builder with `"checksum_type": "none"`.

### System
* Packer version: v1.3.5
* Host platform: Ubuntu 18.04.2 LTS

### Steps to reproduce
1. Run packer `packer build -var 'output_directory=/srv/devel/jenkins/vm/vbox/packer/demo/' -var 'source_vm_image=http://dl.example.org/demo-base.ova' -force -on-error=ask -timestamp-ui demo_vm.json` (packer_cache dir is being created, containing the source OVA image)
2. Run packer again. The build fails with following error: 
```
2019-05-03T13:33:27Z: ==> virtualbox-ovf: Retrieving OVF/OVA
2019-05-03T13:33:27Z:     virtualbox-ovf: Error downloading: Error making HTTP GET request: 416 Requested Range Not Satisfiable
2019-05-03T13:33:27Z: ==> virtualbox-ovf: OVF/OVA download failed.
2019-05-03T13:33:27Z: ==> virtualbox-ovf: OVF/OVA download failed.
2019-05-03T13:33:27Z: ==> virtualbox-ovf: Step "StepDownload" failed
```

### Other info
* source OVA file size: 547264512
* tcpdump output 
  * https://gist.github.com/sbocinec/bba17b1cc0407bd31b052037fd78e9ea
  * here we can see Packer requests bytes outside of the existing file range and does not handle the returned 416 
```
Host: dl.example.org
User-Agent: Packer/1.3.5 (+https://www.packer.io/; go1.12; linux/amd64)
Range: bytes=547264512-
```
* packer log output https://gist.github.com/sbocinec/97015865ab91e803219761d3564a3305
* using `checksum_type` and `checksum` works, however, for my use case i have to proceed with `"checksum_type": "none"` 

If you need any other details, let me know please.
Thanks!
I can not try packer v1.4.0 as i'm afected by #7533

**Comment by azr** [comment] 2019-05-03 17:22
Hello there @sbocinec, here's a linux build of master, can you please tell me wether you have the same issue :
[packer_linux_amd64.zip](https://github.com/hashicorp/packer/files/3142911/packer_linux_amd64.zip)

PS: about that url: `http://dl.example.org/demo-base.ova` it works for you right ? You simply replaced it ?

**Comment by sbocinec** [comment] 2019-05-06 07:07
I tried, now receiving:
```
1 error(s) occurred:

* Source file 'http://dl.example.org/demo-base.ova' needs to exist at time of config validation! stat http://dl.example.org/demo-base.ova: no such file or directory
2019/05/06 07:00:39 Build 'virtualbox-ovf' prepare failure: 1 error(s) occurred:

* Source file 'http://dl.example.org/demo-base.ova' needs to exist at time of config validation! stat http://dl.example.org/demo-base.ova: no such file or directory
2019/05/06 07:00:39 ui error: 1 error(s) occurred:

* Source file 'http://dl.example.org/demo-base.ova' needs to exist at time of config validation! stat http://dl.example.org/demo-base.ova: no such file or directory
```
Full log available at https://gist.github.com/sbocinec/d05e5d8cb9d010756270227af2bf4872

> PS: about that url: http://dl.example.org/demo-base.ova it works for you right ? You simply replaced it ?
right, the URL is sanitized when attaching it here in public

**Comment by azr** [comment] 2019-05-06 09:56
Oh, right, this is expected behaviour; the ova file cannot be downloaded because the `virtualbox-ovf` builder will also need the `vmdk` file that is located next to it. This is a different issue so I think in can close this one as you problem seems fixed.

Please open a new issue ! 🙂

**Closed by azr** 2019-05-06 09:56 UTC
Labels: core, need-more-info, waiting-reply

**Comment by sbocinec** [comment] 2019-05-06 10:23
Hello @azr , i'm pretty confused now:
* the [virtualbox-ovf builder documentation](https://www.packer.io/docs/builders/virtualbox-ovf.html) says following: 
  * `source_path (string) - The path to an OVF or OVA file that acts as the source of this build. It can also be a URL.`
  * `checksum_type (string) - The type of the checksum specified in checksum. Valid values are none, md5, sha1, sha256, or sha512. Although the checksum will not be verified when checksum_type is set to "none", this is not recommended since OVA files can be very large and corruption does happen from time to time.`. 

In my packer config file i use:
```
...
"source_path": "http://dl.example.org/demo-base.ova",
...
"checksum_type": "none",
...
```
  * source path URL http://dl.example.org/demo-base.ova is valid and is an OVA file
  * packer returns `Source file 'http://dl.example.org/demo-base.ova' needs to exist at time of config validation! stat http://dl.example.org/demo-base.ova: no such file or directory`

Do you think, returning 'Source file 'http://dl.example.org/demo-base.ova' needs to exist at time of config validation!` error is a proper output? It's definitely not informing what's the issue and is both confusing and misleading, as the source path does exist...

**Comment by azr** [comment] 2019-05-06 14:42
You are right, the doc is missleading ! I recently refactored it so we wouldn't have to apply edits everywhere everytime we changed it but everything is a bit special for OVAs, I went over that a bit too quickly.

**Comment by azr** [comment] 2019-05-06 14:46
Anyways, this is still a different issue ! 🙂

**Comment by azr** [comment] 2019-05-06 15:09
There, we have https://github.com/hashicorp/packer/pull/7610 and https://github.com/hashicorp/packer/issues/7609 to deal with this ! 🙂  I hope this makes sense !
