### ISSUE TITLE
azure-arm:  HDD not SSD when EVERYTHING I specify say SSD

### ISSUE THREAD

**Issue by lrosenman** [hashicorp/packer#7852] opened 2019-07-08 19:25 UTC
packer version: 1.4.1 (due to the azure-arm bug )
I've put an (encrypted) copy of the full config here:
https://gist.github.com/lrosenman/28d45fcf3be08fa59dca2bcfb495687e

the storage account is Premium LRS, and the captured image is HDD.

WHY?

**Comment by lrosenman** [comment] 2019-07-08 19:35
<img width="1476" alt="Screen Shot 2019-07-08 at 2 35 12 PM" src="https://user-images.githubusercontent.com/2868525/60837364-9f80f480-a18d-11e9-9809-faad111955ac.png">

**Comment by lrosenman** [comment] 2019-07-08 21:05
What's interesting is if I specify Premium_LRS and the disk sizes in the Terraform azurerm_virtual_machine_scale_set (see https://github.com/terraform-providers/terraform-provider-azurerm/issues/3808 for a bug there), it winds up on SSD. 

But this is still confusing.  

I'm not sure what the intended operation here is.

**Comment by SwampDragons** [comment] 2019-07-09 23:01
Normally someone over at Microsoft handles these kinds of Azure tickets; I'm sure it would be helpful for them if you shared your unencrypted builder config with the sensitive information sanitized so they can reproduce.

**Comment by lrosenman** [comment] 2019-07-10 00:02
[osrm.packer.json.txt](https://github.com/hashicorp/packer/files/3375199/osrm.packer.json.txt)

**Comment by lrosenman** [comment] 2019-07-10 00:02
removed the account-specific stuff from that json.

**Comment by SwampDragons** [comment] 2019-07-17 21:52
@paulmey or @amydutta do you have any thoughts on this one?

**Comment by paulmey** [comment] 2019-07-17 23:27
There is a bug in the Azure compute resource provider (the Azure service that does the capture). See #7304. I'm inquiring again what the timeline is on fixing this bug.

**Comment by SwampDragons** [comment] 2019-07-18 16:28
oh, thanks Paul. I'll close this one as a dupe of #7304 so that they can be tracked together.

**Closed by SwampDragons** 2019-07-18 16:28 UTC
Labels: bug, builder/azure
