### ISSUE TITLE
Packer Builder Proxmox .HTTPPort is strange functionality

### ISSUE THREAD

**Issue by coltonhughes** [hashicorp/packer#9567] opened 2020-07-13 02:06 UTC
#### Overview of the Issue

I have a build.json file to build an ubuntu-18.04 box on Proxmox using packer (tried both 1.5.6 and 1.6.0) and the .HTTPPort value in the boot_command is being replaced by the special characters matched with their numbers.
To explain: if the random port that is chosen is 3424 this gets 'typed' in the boot command as #$@$ (basically like holding shift and using the number row).

I have tried forcing the keyboard locale back to en_US still to no avail.  I have also tried manually setting the port and the same behavior occurs.

#### Reproduction Steps

Provide a url using standard preseed format:
"preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{ user `preseed.cfg` }}"

### Packer version
Both 1.5.6 and 1.6.0

### Simplified Packer Buildfile

https://gist.github.com/coltonhughes/86648d447fc3ef493ec3f554717b4b03

### Operating system and Environment details

VM on Proxmox 
Ubuntu 18.04

### Log Fragments and crash.log files

https://gist.github.com/coltonhughes/f0714d8507d815672e4fb9af538e70f0

NOTE: I did manually kill the process as the install fails since the preseed file cannot be found and will sit there until Packer times it out.

### Pictures for explanation if not clear
![packer_error](https://user-images.githubusercontent.com/38597291/87263867-fe093e80-c483-11ea-82d9-226a1239bc11.png)
![packer_error2](https://user-images.githubusercontent.com/38597291/87263870-fe093e80-c483-11ea-889d-07f018ed929e.png)

**Comment by carlpett** [comment] 2020-07-13 10:36
Hm, that is odd. I would wager that the VM is doing the interpretation wrong, but to validate, could you try changing the boot command so it ends after typing in the IP? Ie instead of
```
        "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{ user `preseed.cfg` }} ",
        "-- <enter>"
```
Change it to
```
        "preseed/url=http://{{ .HTTPIP }}:"
```

This will leave the VM waiting for more input. Now go to the Proxmox UI and open a Console in a separate window, then go to the "Monitor" tab and enter `sendkey 3` for example. This will do the exact same thing as Packer is doing. Does it type as a 3 or #?

**Comment by coltonhughes** [comment] 2020-07-13 13:58
I did as you said and indeed it does send # instead of 3.
I'll do some searching to see whats causing this.  If you have any ideas feel free to comment, but Im confident in saying this is not a packer issue.

**Comment by coltonhughes** [comment] 2020-07-13 14:26
I have done some more testing and finding more weird things....
I created a var in my vars file and call in using the standard {{ user `var_name`}} and it is interpreted correctly.  But it seems like there is more weirdness happening since I call the same variable again later, it does not type correctly even though it is the exact same implementation.  See updated build file, vars file, and screenshot to hopefully help explain.

### Build file
https://gist.github.com/coltonhughes/eb3f85319cede4ba0e7c27d83b048ba5

### Vars file
https://gist.github.com/coltonhughes/0bd7ff7bd849b0e9f42acfeab2bee1bb

### Screenshot of Proxmox UI
![image](https://user-images.githubusercontent.com/38597291/87316059-db5e4080-c4ea-11ea-9dfa-ff94ef7ca43e.png)


Finally I have also set and reset the locale and keyboard settings on the proxmox host as well as at the DataCenter level.

**Comment by carlpett** [comment] 2020-07-13 15:06
Interesting! Two ideas to test:
1. Try removing all the keyboard-related things typed out - locale, kbd-chooser, .... The idea (which seems like a long shot) is that the installer would immediately process those directives as they are typed in and would change the processing afterwards.
2. Try just having many copies of `TEST_VAR={{user `test_var`}}` in the boot_command. The idea would be that after some number of characters "something" happens.

Both of these seem a bit far-fetched, but I can't come up with anything simpler...

**Comment by coltonhughes** [comment] 2020-07-13 15:21
More interesting data.
So while testing your first suggestion. I removed the following:

- kbd-chooser
- d-i/locale
- keyboard-configuration/modelcode
And we have success!

To continue troubleshooting to try and narrow it down I removed one at a time, but no success.

I then removed 2 at a time, specifically d-i/locale and keyboard-configuration/modelcode and I almost had success, but you can see in the picture the first instance of test_var was correct and the port was correct, but the final instance of test_var was incorrect and reverted back to the strange substitution of the equivalent of holding shift and hitting the number row.

Photo of this: 
![image](https://user-images.githubusercontent.com/38597291/87321428-d486fc00-c4f1-11ea-8b6d-23502daca0cd.png)

So far it seems like you need to remove all 3 of those parameters for it to correctly enter the data.

##Idea 2
I did as you said and created a boot command full of test vars (20 to be exact) and this is the output.
FYI test_var is set as the string "3324" in the vars file. (see previous post)

Keep in mind my new build.json file [here](https://gist.github.com/coltonhughes/97b2d65fd3f3731aa8f3e1c2ebaa8feb)
and this is the photo results....
![image](https://user-images.githubusercontent.com/38597291/87321979-7e668880-c4f2-11ea-992b-115433896f3b.png)

Im genuinely confused at this point.

**Comment by carlpett** [comment] 2020-07-13 16:48
Yeah, this is weird... I just tried on my environment to just loop the sendkey call, and I cannot reproduce your second screenshot where it seems to flip after 12 repetitions of 13 chars? Weird how `TEST_VAR` gets mangled into `E+` on the first, then just `+` on the later ones too.
What is your Proxmox version?

**Comment by coltonhughes** [comment] 2020-07-13 17:58
Proxmox 6.2-6

**Comment by coltonhughes** [comment] 2020-07-15 19:43
Do we think this is a packer issue or something I need to bring up with ProxMox?

**Comment by carlpett** [comment] 2020-07-16 17:21
I believe this is likely to be a bug in Proxmox, since we're just calling the API with the same parameters but getting different results.

**Comment by azr** [comment] 2020-07-20 15:09
Hello there, not sure if this is helpful but we have recently found out that some "build values" were lost, and HCL2 is pretty verbose about those things. This is not 100% sure but trying this setup with HCL2 could uncover the bug more easily.

**Comment by kwilczynski** [comment] 2020-08-01 18:20
Hi @coltonhughes,

I am using Proxmox builder with latest version and it work fine for me. Also latest Proxmox. Not sure if this is going to be of any help to you, but have a look at my template (especially the boot command), perhaps it will work for you?

Here it is: [ubuntu-20.04-amd64.json#L198-L223](https://github.com/kwilczynski/packer-templates/blob/master/ubuntu-20.04-amd64.json#L198-L223)

**Comment by SwampDragons** [comment] 2020-08-13 19:55
Sounds like this was a proxmox bug, so I'm closing the issue here.

**Closed by SwampDragons** 2020-08-13 19:55 UTC
Labels: bug, builder/proxmox
