### ISSUE TITLE
PACKER_HTTP_ADDR is not available for use by the PowerShell provider

### ISSUE THREAD

**Issue by erikgraa** [hashicorp/packer#9114] opened 2020-04-24 16:28 UTC
#### Overview of the Issue

PACKER_HTTP_ADDR environment variable is not available for use by the PowerShell provider.

The only three variables I could enumerate that start with packer (using gci env: and piping it to a file to look at post-deploy) are these:

![image](https://user-images.githubusercontent.com/20067955/80234735-f2fafb00-8658-11ea-88a2-9f7d9afb9d5a.png)

#### Reproduction Steps

Create a machine with vsphere-iso using the http_directory, and http_min_port and http_max_port. The port is set to 9000 for both directives, and http_directory points to a "http" folder.

I have tried both "inline" and "scripts" options for the provider.

### Packer version

1.5.5

### Simplified Packer Buildfile

![image](https://user-images.githubusercontent.com/20067955/80234853-1faf1280-8659-11ea-88d6-b594ce91e9d9.png)

![image](https://user-images.githubusercontent.com/20067955/80234944-40776800-8659-11ea-8f67-82d3b5775f10.png)

### Operating system and Environment details

Windows Server 2019 Standard

**Comment by nywilken** [comment] 2020-04-24 17:59
Hi @erikgraa thanks for reaching out. The issue is actually with the `vsphere-iso` builder as it is not properly setting the `PACKER_HTTP_ADDR` variable. I'm able to reproduce this issue using the `shell` provisioner. I don't know if we will be able to make this fix immediately but will see if we can get to it by the 1.5.7 release if not sooner.

**Comment by erikgraa** [comment] 2020-04-24 18:56
Thank you for clarifying. I will continue to send in the Packer host's IP by other means until such time as `vsphere-iso` makes available `PACKER_HTTP_ADDR` to providers. :)

**Comment by razaborg** [comment] 2020-04-30 08:33
I seem to have the exact same issue with the vmware-iso provisionner.

**Comment by erikgraa** [comment] 2020-04-30 09:11
> I seem to have the exact same issue with the vmware-iso provisionner.

I circumvent it until fixed by sending in the packer host's IP as an environment variable.

**Comment by sylviamoss** [comment] 2020-05-18 13:06
hello there! Could you please test your templates with these binaries https://circleci.com/gh/hashicorp/packer/52124#artifacts/containers/0 ?
This changes the way we save HTTP information and I wonder if it would solve the issue.

**Comment by SwampDragons** [comment] 2020-05-20 18:46
Related to https://github.com/hashicorp/packer/pull/9238

**Comment by SwampDragons** [comment] 2020-05-20 18:49
The PR linked above solves this issue, and it will be part of the v1.6.0 release. Let us know if you find any more problems!

**Closed by SwampDragons** 2020-05-20 18:49 UTC
Labels: bug, builder/vsphere, good first issue, waiting-reply
