### ISSUE TITLE
Packer Virtualbox WSL Symlink issues.

### ISSUE THREAD

**Issue by daemenseth** [hashicorp/packer#8298] opened 2019-10-31 12:44 UTC
I use packer in Debian under Windows subsystem for Linux.
Virtualbox is installed under windows 10.
My builder config. VM is created but the iso is not correctly mounted

> "builders": [
> 
>     {
> 
>       "type": "virtualbox-iso",
>       "virtualbox_version_file": ".vbox_version",
>       "guest_os_type": "Windows10_64",
>       "guest_additions_mode": "disable",
>       "guest_additions_url": "VBoxGuestAdditions_6.1.0_BETA2.iso",
>       "guest_additions_sha256": "35ce5ef27e82dbf707ba4209e1901fbd3a0ad1b00bf946b462211b64dce50e4b",
>       "headless": true,
>       "output_directory": "c:/build/",
> 
>       "cpus": 2,
>       "memory": 4096,
>       "vboxmanage": [
>         ["modifyvm", "{{.Name}}", "--vram", "64"],
>         ["modifyvm", "{{.Name}}", "--audio", "none"],
>         ["modifyvm", "{{.Name}}", "--nictype1", "82540EM"],
>         ["modifyvm", "{{.Name}}", "--nictype2", "82540EM"],
>         ["modifyvm", "{{.Name}}", "--nictype3", "82540EM"],
>         ["modifyvm", "{{.Name}}", "--nictype4", "82540EM"]
>       ],
>       "disk_size": "{{user `disk_size`}}",
>       "hard_drive_interface": "sata",
>       "iso_url": "291d907ff9fd85db9051a222ce56bdabc897c94e.iso",
>       "iso_checksum": "{{user `iso_checksum`}}",
>       "iso_checksum_type": "{{user `iso_checksum_type`}}",
>       "communicator": "winrm",
>       "winrm_username": "vagrant",
>       "winrm_password": "vagrant",
>       "winrm_timeout": "4h",
> 
>       "shutdown_command": "shutdown /s /t 0 /f /d p:4:1 /c \"Packer Shutdown\"",
>       "floppy_files": [
>         "windows-2019/autounattend.xml"
>       ],
>       "vboxmanage": [
>         [ "modifyvm", "{{.Name}}", "--natpf1", "winrm,tcp,,444,,5985" ]
>       ]
>     }
>   ],

> 2019/10/31 13:35:02 packer: 2019/10/31 13:35:02 Executing VBoxManage: []string{"storageattach", "packer-virtualbox-iso-1572525286", "--storagectl", "SATA Controller", "--port", "0", "--device", "0", "--type", "hdd", "--medium", "c:/build/packer-virtualbox-iso-1572525286.vdi", "--nonrotational", "off", "--discard", "off"}
2019/10/31 13:35:02 packer: 2019/10/31 13:35:02 stdout:
==> virtualbox-iso: Error resolving symlink for ISO: lstat /home/adm_seth/test/c:/build/291d907ff9fd85db9051a222ce56bdabc897c94e.iso: no such file or directory
2019/10/31 13:35:02 packer: 2019/10/31 13:35:02 stderr:
==> virtualbox-iso: Error resolving symlink for ISO: lstat /home/adm_seth/test/c:/build/291d907ff9fd85db9051a222ce56bdabc897c94e.iso: no such file or directory
==> virtualbox-iso: Step "stepAttachISO" failed, aborting...
==> virtualbox-iso: aborted: skipping cleanup of step "stepCreateDisk"
==> virtualbox-iso: aborted: skipping cleanup of step "stepCreateVM"
==> virtualbox-iso: aborted: skipping cleanup of step "StepSuppressMessages"
==> virtualbox-iso: aborted: skipping cleanup of step "StepSshKeyPair"
==> virtualbox-iso: aborted: skipping cleanup of step "StepHTTPServer"
==> virtualbox-iso: aborted: skipping cleanup of step "StepCreateFloppy"
==> virtualbox-iso: aborted: skipping cleanup of step "StepOutputDir"
2019/10/31 13:35:02 [INFO] (telemetry) ending virtualbox-iso
==> virtualbox-iso: aborted: skipping cleanup of step "StepDownload"
2019/10/31 13:35:02 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
==> virtualbox-iso: aborted: skipping cleanup of step "StepDownloadGuestAdditions"
2019/10/31 13:35:02 machine readable: virtualbox-iso,error []string{"Error resolving symlink for ISO: lstat /home/adm_seth/test/c:/build/291d907ff9fd85db9051a222ce56bdabc897c94e.iso: no such file or directory"}
Build 'virtualbox-iso' errored: Error resolving symlink for ISO: lstat /home/adm_seth/test/c:/build/291d907ff9fd85db9051a222ce56bdabc897c94e.iso: no such file or directory
==> Builds finished but no artifacts were created.

2019/10/31 13:35:02 [INFO] (telemetry) Finalizing.
==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error resolving symlink for ISO: lstat /home/adm_seth/test/c:/build/291d907ff9fd85db9051a222ce56bdabc897c94e.iso: no such file or 

> directory

**Comment by SwampDragons** [comment] 2019-10-31 20:47
What version of packer are you using? is /home/adm_seth/test/c:/build/291d907ff9fd85db9051a222ce56bdabc897c94e.iso a real path that Packer isn't seeing, or is the path being mangled? What is the actual appropriate path to the file?

**Comment by daemenseth** [comment] 2019-10-31 21:05
Packer version1.4.4
I have tried with a path and url location
The iso is dowloaded in the packer_cache folder nut the vboxmanage does strange symlinking

**Comment by SwampDragons** [comment] 2019-10-31 22:27
We had some issues with windows and symlinking a few versions ago; do you mind trying to delete your cached version and re-download it?

**Comment by daemenseth** [comment] 2019-11-01 14:21
I have deleted the cache and now the issue with the iso is resolved.
But now I have a new issue the floppy disk is not correctly linked

Build 'virtualbox-iso' errored: Error attaching floppy: VBoxManage error: VBoxManage.exe: error: Could not find file for the medium 'C:\tmp\virtualbox531530584\floppy.vfd' (VERR_PATH_NOT_FOUND)

I have tried to set the tmpdir to the packer cache dir but this does not work

**Comment by SwampDragons** [comment] 2019-11-01 16:28
Is the floppy file also a symlink?

**Comment by daemenseth** [comment] 2019-11-01 17:09
No. IT is generated by packer in the virtual box builder packer saves it in /tmp/virtualbox...
But it is not passthrough to Windows as the iso file.

**Comment by SwampDragons** [comment] 2019-11-01 17:19
Okay, I'll try to take a look.

**Comment by SwampDragons** [comment] 2019-11-21 22:20
@daemenseth I just got a chance to look at this code. I think what's happening here is that when we copy the file into the temp dir, the directory returned has the windows format rather than the wsl one.  The call ultimately being made here is https://golang.org/pkg/os/#TempDir.  From the docs: 

> On Windows, it uses GetTempPath, returning the first non-empty value from %TMP%, %TEMP%, %USERPROFILE%

Are any of these set in your system, and are they set to point to the wsl versions of the file?  

WSL has definitely presented a bit of a challenge for Packer's windows compatibility. Long-term, it may make sense for us to have a `PACKER_WSL` env var that we check to figure out how we should treat the pathing, but if setting one of the above variables to linux-style pathing solves this issue for you, that is at least a reasonable workaround.

**Comment by SwampDragons** [comment] 2020-03-18 23:04
Did my above comment provide a workaround?

**Comment by SwampDragons** [comment] 2020-10-07 23:21
Closing because we never heard back on this one. I think the issue is that the windows-style env vars need to be set.

**Closed by SwampDragons** 2020-10-07 23:21 UTC
Labels: bug, builder/virtualbox, waiting-reply, windows-host
