### ISSUE TITLE
SSH error while creating AMI in AWS

### ISSUE THREAD

**Issue by gagan-bhullar-tech** [hashicorp/packer#13137] opened 2024-08-08 01:26 UTC
#### Overview of the Issue

Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by lbajolet-hashicorp** [comment] 2024-08-12 18:40
As with #13143, this error alone is not enough for us to troubleshoot the cause of the problem. Assuming these are the same template that causes the error, I'll close this issue so we can center the discussion around the other issue.

Please feel free to reopen if I missed something, thanks!

**Closed by lbajolet-hashicorp** 2024-08-12 18:40 UTC
Labels: bug
