### ISSUE TITLE
Packer will delete VMs with the same name when ran. HyperV

### ISSUE THREAD

**Issue by shogerr** [hashicorp/packer#7671] opened 2019-05-21 16:54 UTC
Packer will delete VMs with the same name when ran.

Just had packer delete a working VM with the same name as the json file that was being built.

**Comment by SwampDragons** [comment] 2019-05-21 17:15
Sorry to hear it. It's never fun losing work. 

Do you have logs from the Packer run that deleted this previously existing VM?

In the amazon builder we default to failing on validation if there's a name conflict, and you have to explicitly set `"force_deregister": true` to override that behavior. It sounds like we need to implement a similar safety check for hyper-v

**Comment by shogerr** [comment] 2019-05-21 20:43
Unfortunately, I do not have a log of the event.

The only other information I can provide is that the VM that end up deleted was running and 'connected to' at the time Packer was ran.

**Comment by marcinbojko** [comment] 2019-05-28 16:29
Hi @SwampDragons  - I can confirm this behaviour.
I've created VM called "packer-centos76-g2" and rerun packer templat using this as vmname:
used template:
https://github.com/marcinbojko/hv-packer/blob/master/templates/hv_centos76_g2.json

Logs included
[packer.zip](https://github.com/hashicorp/packer/files/3228717/packer.zip)

**Comment by SwampDragons** [comment] 2019-06-13 18:17
I've started investigating this. It looks like this is a duplicate of #4573

**Closed** 2019-06-14 17:58 UTC
Labels: builder/hyperv, enhancement
