### ISSUE TITLE
v1.0.3 ansible provisioner no longer works (worked in v.1.0.2)

### ISSUE THREAD

**Issue by mazubieta** [hashicorp/packer#5193] opened 2017-07-29 18:06 UTC
**Packer version**  `v1.0.3`
**Host platform** `mac osx sierra`
**debug output of v1.0.2 that works** https://gist.github.com/mazubieta/5fff7ff4057e4cb1df96887b439a17b5
**debug output of v1.0.3 that hangs** https://gist.github.com/mazubieta/34c2602d98419b17be730aa90dcf1dcc
**simplest example**
 https://github.com/mazubieta/packer_v1.0.3_ansible_bug
  
I upgraded to v1.0.3 and the ansible provisioner no longer works.

**Comment by rickard-von-essen** [comment] 2017-07-29 18:25
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Closed** 2017-07-29 18:26 UTC
Labels: bug, duplicate, provisioner/ansible-remote

**Comment by mazubieta** [comment] 2017-07-29 19:46
Thank you, @rickard-von-essen.  Sorry I didn't search the closed issues first; I only looked at the open ones!
