### ISSUE TITLE
amazon-ebs builder not attaching the specified iam_instance_profile into the instance

### ISSUE THREAD

**Issue by SantiMunoz** [hashicorp/packer#9512] opened 2020-07-01 07:49 UTC
#### Overview of the Issue

When using the amazon-ebs builder and specifying the iam_instance_profile, it is ignored and the ec2 instance created doesn't have any IAM role. Tried with an instance profile name and the full arn. 

### Packer version

Packer 1.6.0

### Simplified Packer Buildfile

```json
{
      "type": "amazon-ebs",
      "ami_name": "{{user `service_name`}}-{{timestamp}}",
      "ami_description": "{{user `description`}}",
      "region": "{{user `aws_region`}}",
      "vpc_id": "{{user `vpc_id`}}",
      "subnet_id": "{{user `subnet_id`}}",
      "instance_type": "{{user `instance_type`}}",
      "iam_instance_profile": "example_of_role_name",
      "source_ami": "{{user `source_ami`}}",
      "ami_virtualization_type": "hvm",
      "associate_public_ip_address": "false",
      "ssh_username": "ubuntu",
      "tags": {
        "name": "{{user `service_name`}}-{{timestamp}}",
        "created_by": "packer"
      }
    }
```

### Operating system and Environment details

MacOS 10.15.5

### Log Fragments and crash.log files

```
2020/07/01 09:39:31 [INFO] (telemetry) Starting builder amazon-ebs
amazon-ebs: output will be in this color.

2020/07/01 09:39:31 packer-builder-amazon-ebs plugin: Found region eu-central-1
2020/07/01 09:39:31 packer-builder-amazon-ebs plugin: [INFO] AWS Auth provider used: "SharedConfigCredentials: /Users/santimunoz/.aws/credentials"
2020/07/01 09:39:31 packer-builder-amazon-ebs plugin: [INFO] (aws): No AWS timeout and polling overrides have been set. Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS to your desired values.
==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: vpn-base-1593589171
2020/07/01 09:39:32 packer-builder-amazon-ebs plugin: Using AMI Filters {
2020/07/01 09:39:32 packer-builder-amazon-ebs plugin:   ImageIds: ["ami-086a09d5b9fa35dc7"]
2020/07/01 09:39:32 packer-builder-amazon-ebs plugin: }
    amazon-ebs: Found Image ID: ami-086a09d5b9fa35dc7
2020/07/01 09:39:32 packer-builder-amazon-ebs plugin: [INFO] Finding AZ and VpcId for the given subnet 'subnet-014a0d6f39243eec0'
2020/07/01 09:39:33 packer-builder-amazon-ebs plugin: [INFO] AvailabilityZone found: 'eu-central-1a'
==> amazon-ebs: Creating temporary keypair: packer_5efc3db3-02cb-6073-026d-c5500e861d96
==> amazon-ebs: Creating temporary security group for this instance: packer_5efc3db5-e51c-bb05-c403-4528ddbaa949
2020/07/01 09:39:33 packer-builder-amazon-ebs plugin: [DEBUG] Waiting for temporary security group: sg-06e1506e1848ae8db
2020/07/01 09:39:33 packer-builder-amazon-ebs plugin: [DEBUG] Found security group sg-06e1506e1848ae8db
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-0004dec2ecfa5fa4b
==> amazon-ebs: Waiting for instance (i-0004dec2ecfa5fa4b) to become ready...
2020/07/01 09:39:51 packer-builder-amazon-ebs plugin: [INFO] Not using winrm communicator, skipping get password...
==> amazon-ebs: Using ssh communicator to connect: 10.104.11.221
2020/07/01 09:39:51 packer-builder-amazon-ebs plugin: [INFO] Waiting for SSH, up to timeout: 5m0s
==> amazon-ebs: Waiting for SSH to become available...
2020/07/01 09:39:51 packer-builder-amazon-ebs plugin: Using host value: 10.104.11.221
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: [INFO] Attempting SSH connection to 10.104.11.221:22...
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: [DEBUG] handshaking with SSH
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: [DEBUG] handshake complete!
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: [DEBUG] Opening new ssh session
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: [INFO] agent forwarding enabled
2020/07/01 09:39:58 packer-builder-amazon-ebs plugin: Running the provision hook
==> amazon-ebs: Connected to SSH!
2020/07/01 09:39:58 [INFO] (telemetry) Starting provisioner salt-masterless
==> amazon-ebs: Provisioning with Salt...
```

**Comment by nywilken** [comment] 2020-07-01 10:43
Hello @SantiMunoz thanks for reaching out. I can't reproduce this issue using the example configuration above or with any of my existing templates. When specifying an IAM role to attach to an instance you just need to specify its name, not the arn. For example given the role arn `arn:aws:iam::000000000000:role/TestProfile` you would just set 

```json 
"iam_instance_profile": "TestProfile"
```

Your example configuration has a hard coded value, but is there any chance you are using a user variable to set `iam_instance_profile`? 

If so I would check that the value is being set properly. When `iam_instance_profile` is non-empty `"TestProfile"` you will normally see a log entry like "**Using specified instance profile: TestProfile**" in the logs. If the value of `iam_instance_profile` is empty `""` then the instance profile attachment step will get skipped and nothing will be outputted to the logs. I should also add that if the profile name is non-empty Packer will verify the existence of the IAM role before creating the instance and error if the role is invalid.

**Comment by SantiMunoz** [comment] 2020-07-01 13:43
Hi @nywilken thanks for the replay! I've tried to set the instance profile name directly without a variable and it worked as expected, the problem shows up when using a variable, looks like is not getting any value.

I'm currently using this statement: ``"iam_instance_profile": "{{user  `instance_role`}}",`` and I have a variables file with `"instance_role ": "machine-strongswan-dev-fra",` and the command I use to build: `packer build -var-file=variables.json  vpn-goldenV3.json`

In order to reproduce it could you try using a variable from another file?

**Comment by sylviamoss** [comment] 2020-07-01 15:02
@SantiMunoz I don't if you copied and pasted the variable that it's inside your `variables.json` file, but if you did there's a space after `instance_role` and before `"`, see: 
```
"instance_role ": "machine-strongswan-dev-fra", // with space
"instance_role": "machine-strongswan-dev-fra", // without space
```
If the blank space is really there, could you remove it and try again, please?

**Comment by nywilken** [comment] 2020-07-01 17:26
@SantiMunoz glad we were able to help out; good catch @sylviamoss! 

I'm going to close this issue seeing as it's not a bug in Packer. If you run into another problem that you think may be a bug feel free to open a new issue and we'll try our best to help. Cheers!

**Closed by nywilken** 2020-07-01 17:26 UTC
Labels: bug, builder/amazon
