### ISSUE TITLE
Publish Image to Azure Shared Image Gallery - Image location issue

### ISSUE THREAD

**Issue by itzikbekel** [hashicorp/packer#8895] opened 2020-03-15 19:37 UTC
## Overview of the Issue

SIG = Shared Image Gallery

I have an issue when trying to push Image generated by packer at North Europe to Azure Image Gallery definition which located at North Europe as well.

1. Source image in packer build is an image which generated from previsions packer build and published to SIG on East US with North Europe as additional replica region.

2. This packer build is creating an image on North Europe (using the previous image located on Azure SIG which has two replica regions <East US and North Europe>)

3. When trying to push this generated image to SIG into Image definition located on North Europe I'm receiving an error that the source image is not exist, while i'm able to find it on Azure Portal and using Azure command line. 

#### Reproduction Steps

I tried push it to SIG using packer with "shared_image_gallery_destination" and also via command line - same error.
I also tried to create a image version manually from the packer image and received an error as well.

when I tried to create image manually (using Azure Portal) on North Europe and publish it to SIG It worked, so I suspect it something that related to packer.

I found out something weird on the packer output, the "location" variable is 'North Europe' but packer build output shows the Image Location is 'East US' while the Compute location is 'North Europe', in Azure Portal it's looks like the image at 'North Europe' but I assume something is tag this VM on 'East US' and that's why the push image to SIG not working:

```
21:32:32  [1;32m==> azure-arm:  -> Compute ResourceGroupName : 'packer-Resource-Group-uytr9e2p2o'[0m
21:32:32  [1;32m==> azure-arm:  -> Compute Name              : 'pkrvmuytr9e2p2o'[0m
21:32:32  [1;32m==> azure-arm:  -> Compute Location          : '**North Europe**'[0m
21:32:32  [1;32m==> azure-arm:  -> Image ResourceGroupName   : 'cam-image-gallery-vmss-rg'[0m
21:32:32  [1;32m==> azure-arm:  -> Image Name                : 'TWELVEHANDZ-128.0.0'[0m
21:32:32  [1;32m==> azure-arm:  -> Image Location            : '**eastus**'[0m
```

### Packer version
1.5.4

### Simplified Packer Buildfile

```
"builders": [
    {
      "type": "azure-arm",
      "client_id": "{{user `client_id`}}",
      "client_secret": "{{user `client_secret`}}",
      "tenant_id": "{{user `tenant_id`}}",
      "subscription_id": "{{user `subscription_id`}}",
      "os_type": "Windows",
      "managed_image_resource_group_name": "image-gallery-vmss-rg",
      "managed_image_name": "{{user `imageName`}}",
      "communicator": "winrm",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "winrm_timeout": "5m",
      "winrm_username": "packer",
      "location": "{{user `imageLocation`}}",
      "vm_size": "Standard_DS2_v2",
      "async_resourcegroup_delete": true,
      "shared_image_gallery": {
        "subscription": "{{user `subscription_id`}}",
        "resource_group": "SIG RG",
        "gallery_name": "SIG Name",
        "image_name": "Image Definition Name",
        "image_version": "{{user `sourceImageVersion`}}"
      }
    }
  ],
```

**Comment by nywilken** [comment] 2020-03-16 18:59
Hi @itzikbekel thanks for reaching out. Can you please confirm my understanding of the issue. You are running into issues when trying to create a new image version for some SIG in the North Europe region, using a source image that is part of a SIG in the US East region; essentially, using a different target region from the source region. Is my understanding correct? 

If so, could you please provide a bit more details around the SIG in North Europe: Same OS, different version, any information that would be helpful in reproducing this issue, along with a gist of your full Packer build log `PACKER_LOG=1 packer build template.json`. 


 In looking at the Azure FAQ I found 
"_While creating an image version, you can use the --location tag in CLI and the -Location tag in PowerShell to specify the source region. Please ensure the managed image that you are using as the base image to create the image version is in the same location as the location in which you intend to create the image version. Also, make sure that you pass the source region location as one of the target regions when you create an image version._" https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries#how-do-i-specify-the-source-region-while-creating-the-image-version 

I also found the following statement in the same Azure FAQs, which makes me wonder if it is a supported use case.  

_"Can I create the shared image gallery in a different location than the one for the image definition and image version?
Yes, it is possible. But, as a best practice, we encourage you to keep the resource group, shared image gallery, image definition, and image version in the same location._"


> I tried push it to SIG using packer with "shared_image_gallery_destination" and also via command line - same error.

By CLI do you mean the Azure CLI?

**Comment by itzikbekel** [comment] 2020-03-16 20:09
> Hi @itzikbekel thanks for reaching out. Can you please confirm my understanding of the issue. You are running into issues when trying to create a new image version for some SIG in the North Europe region, using a source image that is part of a SIG in the US East region; essentially, using a different target region from the source region. Is my understanding correct?
> 
> If so, could you please provide a bit more details around the SIG in North Europe: Same OS, different version, any information that would be helpful in reproducing this issue, along with a gist of your full Packer build log `PACKER_LOG=1 packer build template.json`.
> 
> In looking at the Azure FAQ I found
> "_While creating an image version, you can use the --location tag in CLI and the -Location tag in PowerShell to specify the source region. Please ensure the managed image that you are using as the base image to create the image version is in the same location as the location in which you intend to create the image version. Also, make sure that you pass the source region location as one of the target regions when you create an image version._" https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries#how-do-i-specify-the-source-region-while-creating-the-image-version
> 
> I also found the following statement in the same Azure FAQs, which makes me wonder if it is a supported use case.
> 
> _"Can I create the shared image gallery in a different location than the one for the image definition and image version? Yes, it is possible. But, as a best practice, we encourage you to keep the resource group, shared image gallery, image definition, and image version in the same location._"
> 
> > I tried push it to SIG using packer with "shared_image_gallery_destination" and also via command line - same error.
> 
> By CLI do you mean the Azure CLI?

Hi and thanks for the reply!

let me clarify: 

1. Shared Image Gallery located at East US (I have only one Shared Image Gallery resource)
2. 1st image definition and Image version located at East US and has a replica region to North Europe (this image built with packer)
3. 2nd image (the problematic one) is using 1st image from North Europe to create a new image at North Europe, when the packer build finish, and the new managed image is ready at North Europe, I'm trying to push this image to a different Shared Image Definition which located on North Europe, under my SIG.

I've read also the FAQ and my scenario should be supported (maybe not Microsoft best practice but it supported.

however, as I mentioned in the issue details, when I'm creating a VM manually on North Europe (using Azure Portal) from the 1st image , capture it and taking an image, then using Azure Portal I managed to push it to the image definition on North Europe (what I did not managed using the 2nd Packer image) so I suspect it something with the 2nd packer image.

in addition, when I tried manually (using azure portal) push the 2nd packer image to the image definition on North Europe it not worked and returned an error.

as for your questions :By CLI do you mean the Azure CLI? , the answer is yes.

1st. packer image is built from:
        "image_publisher": "MicrosoftWindowsServer",
        "image_offer": "WindowsServer",
        "image_sku": "2019-Datacenter",

2nd packer image is built from 1st packer output:
      "shared_image_gallery": {
        "subscription": "{{user `subscription_id`}}",
        "resource_group": "cam-image-gallery-vmss-rg",
        "gallery_name": "camimagegalleryvmss",
        "image_name": "CAM-WEB-SHARED",
        "image_version": "{{user `sourceImageVersion`}}"
      }

i've also managed to "solve" the issue I saw when I build packer on North Europe and packer build output showed the image was built on East US (but actually the image exist in North Europe)

I found here - https://github.com/hashicorp/packer/blob/master/builder/azure/arm/builder.go 
(b.config.manageImageLocation = *group.Location) that packer using the region of the managed image resource group location parameter (managed_image_resource_group_name) so I passed a resource group name that located on North Europe and I was able to get the following output:

15:53:06  [1;32m==> azure-arm:  -> Compute ResourceGroupName : 'packer-Resource-Group-joso7tpoib'[0m
15:53:06  [1;32m==> azure-arm:  -> Compute Name              : 'pkrvmjoso7tpoib'[0m
15:53:06  [1;32m==> azure-arm:  -> Compute Location          : '**North Europe'**[0m
15:53:06  [1;32m==> azure-arm:  -> Image ResourceGroupName   : 'cam-image-gallery-vmss-ne-rg'[0m
15:53:06  [1;32m==> azure-arm:  -> Image Name                : 'TWELVEHANDZ-131.0.0'[0m
15:53:06  [1;32m==> azure-arm:  -> Image Location            : '**northeurope**'[0m

after taking this image and try push it to the image definition on North Europe (using Azure CLI) I got the following error message : 
15:55:34  ERROR: Gallery image version publishing profile regions 'northeurope' must contain the location of image version 'East US'. 

when using Azure CLI (with --location parameter as well) : 
az sig image-version create --resource-group cam-image-gallery-vmss-rg --gallery-name camimagegalleryvmss --gallery-image-definition CAM-WEB-12 --gallery-image-version 137.0.0 --target-regions "northeurope" --managed-image /subscriptions/YYYYYYYYYYY/resourceGroups/cam-image-gallery-vmss-ne-rg/providers/Microsoft.Compute/images/TWELVEHANDZ-131.0.0 --location "North Europe"

Deployment failed. Correlation ID: 412dbb64-f9e2-4075-88d5-f5c2a2bd8eda. [northeurope] Failed to call pir.PutGalleryImage

I have also opened a case to Microsoft and they was not able to reproduce the issue without packer

I hope it's clear, let me know if you need additional details

**Comment by itzikbekel** [comment] 2020-04-02 07:00
Hi any update here?

**Comment by itzikbekel** [comment] 2020-04-14 11:42
Hi, following up again, still waiting for update
@nywilken 
@SwampDragons

**Comment by nywilken** [comment] 2020-04-14 16:39
Hi @itzikbekei apologies for the delayed response here. We haven't had a chance to look into this further since the issue was opened. I'm including @paulmey on the issue to see if maybe he can provide some insight for the moment. Once we get a chance to look into this issue I will make sure to update the ticket with any findings. Cheers :smile:

**Comment by paulmey** [comment] 2020-04-14 21:17
Hi @itzikbekel (Thanks @nywilken),

Ok, so the current build going SIG -> MI (Managed Image). I think you've uncovered a bug where the build assumes that the location of the Managed Image will [match that of the containing resource group](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/builder.go#L119). That doesn't make any sense to me, because the managed image will always need to be created in the same location as the VM (North Europe in your case). I'll prepare a PR to fix that.

I think you can work around this by creating a resource group with Location="North Europe" and put the managed image in there. Please try that out and let us know how that goes.

**Comment by nywilken** [comment] 2020-04-15 11:16
@paulmey thanks for the assist on this issue - the changes look good!

@itzikbekel, the PR #9068 has a fix for this issue. Could you test the binaries and let us know if the changes work for you? Here the binaries
https://app.circleci.com/pipelines/github/hashicorp/packer/4608/workflows/157d27f6-72cb-464c-a911-d9a3269de85b/jobs/45675/artifacts

**Comment by itzikbekel** [comment] 2020-04-16 07:44
Hi @nyetwurk  @paulmey many thanks !
I will check the binaries and will let you know.

but, I'm not sure it will solve the issue as I've already tried the workaround and the managed image was created on 'North Europe', however when I tried to push it to SIG (located in East US) to Image Definition in 'North Europe' I still got the error:

 ERROR: Gallery image version publishing profile regions 'northeurope' must contain the location of image version 'East US'.

**Comment by itzikbekel** [comment] 2020-04-17 06:49
Hi @nyetwurk  @paulmey 
great news! it worked! now I'm able to publish image version with diffrent location to SIG :-) 

seems the 'workaround' with setting RG with the same location as the target image location didn't worked but your fixes does worked 

many thanks, you can merge the PR

**Comment by nywilken** [comment] 2020-04-17 09:42
Awesome! Thanks for testing :tada:

**Closed** 2020-04-17 09:43 UTC
Labels: bug, builder/azure
