### ISSUE TITLE
Powershell provisioner broken by default. "'=SilentlyContinue' is not recognized"

### ISSUE THREAD

**Issue by Delpire** [hashicorp/packer#6828] opened 2018-10-10 16:29 UTC
Packer version: v1.3.1
Host Machine: Windows 7 64-bit

I am running Packer using the VirtualBox builder to try and build a Windows 10 box from an ISO. I am using the latest Windows 10 build (1809).

I have tried running both a Powershell script and an inline Powershell command using the default Powershell provisioner. Both return an error about SilentlyContinue not being recognized.

Example:
```
{
    "type": "powershell",
    "inline": ["Import-StartLayout -LayoutPath C:/Windows/Temp/layoutModification.xml -MountPath C:\\"]
},
```

Output:
```
==> virtualbox-iso: Provisioning with Powershell...
==> virtualbox-iso: Provisioning with powershell script: E:\TEMP\packer-powershell-provisioner453446655
    virtualbox-iso: =SilentlyContinue : The term '=SilentlyContinue' is not recognized as the name of a cmdlet, function, script file, or
    virtualbox-iso: operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
    virtualbox-iso: again.
    virtualbox-iso: At line:1 char:55
    virtualbox-iso: + ... -Path variable:global:ProgressPreference){='SilentlyContinue'};. c:/W ...
    virtualbox-iso: +                                               ~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : ObjectNotFound: (=SilentlyContinue:String) [], CommandNotFoundException
    virtualbox-iso:     + FullyQualifiedErrorId : CommandNotFoundException
    virtualbox-iso:
```

**Comment by SwampDragons** [comment] 2018-10-10 23:39
I think this is a duplicate of 5772 but I'm not convinced the answer I gave there is correct.

**Comment by SwampDragons** [comment] 2018-10-10 23:45
However, if the issue is that the system hasn't fully finished sysprepping, you can figure that out by adding a `pause_before` of 30s or a minute to your template, just to see if the problem goes away when that's been done.

**Comment by SwampDragons** [comment] 2018-10-11 18:55
Makes sense. Worth ruling out, but I am not surprised it wasn't the answer. Now to figure out why that preference variable isn't set correctly for you. Maybe if it's set to an empty string it passes the check but fails being written to?

**Comment by SwampDragons** [comment] 2018-10-11 23:50
Okay, I'm struggling to reproduce so if you're okay with it I'd like you to test something for me.  

What happens if you run this with the custom 
`"execute_command": "powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){ if (variable:global:ProgressPreference -ne \'' -and variable:global:ProgressPreference -ne $null) {$ProgressPreference='SilentlyContinue'}};. {{.Vars}}; &'{{.Path}}';exit $LastExitCode }\""`?

**Comment by SwampDragons** [comment] 2018-10-11 23:58
Actually that one won't work-- I'll update in a minute with a better one.

**Comment by SwampDragons** [comment] 2018-10-12 00:00
Okay, try this: `powershell -executionpolicy bypass \"& { if (Test-Path variable:global:ProgressPreference){ $val=(gi "variable:global:ProgressPreference").value; if ($val -ne '' -and $val -ne $null) {$ProgressPreference='SilentlyContinue'}};. {{.Vars}}; &'{{.Path}}';exit $LastExitCode }\"`

**Comment by SwampDragons** [comment] 2018-10-12 00:12
And actually, maybe this is better:
`powershell -executionpolicy bypass \"& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. {{.Vars}}; &'{{.Path}}';exit $LastExitCode }\"`

**Comment by Delpire** [comment] 2018-10-12 15:41
It looks like that worked!!

```
{
      "type": "powershell",
      "execute_command": "powershell -executionpolicy bypass \"& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. {{.Vars}}; &'{{.Path}}';exit $LastExitCode }\"",
      "scripts": [
        "./scripts/remove-windows-features.ps1",
        "./scripts/install-vs2017.ps1"
      ],
      "pause_before": "2m"
    }
```

(I had tried using pause_before previously and it had no effect.

```
==> virtualbox-iso: Provisioning with powershell script: ./scripts/install-vs2017.ps1
         virtualbox-iso: The command completed successfully.
```

Looks like that command solved the problem. 👍

**Comment by SwampDragons** [comment] 2018-10-12 16:11
Awesome! I'll change the defaults in the provisioner and make a PR.

**Closed** 2018-10-12 18:08 UTC
Labels: bug, provisioner/powershell
