### ISSUE TITLE
Ansible provisioner output has five star characters after every character

### ISSUE THREAD

**Issue by nhooey** [hashicorp/packer#8558] opened 2020-01-02 16:59 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Executing Ansible prints the following:

```
==> docker: Executing Ansible: *****a*****n*****s*****i*****b*****l*****e*****-*****p*****l*****a*****y*****b*****o***
**o*****k***** *****-*****- ...
```
And a lot more, where every character has 5 `*` characters after it.

This is what is supposed to print:

```
==> docker: Executing Ansible: ansible-playbook --extra-vars packer_build_name=docker ...
```

#### Reproduction Steps

Run a Packer template with an Ansible provisioner and observe the output.

### Packer version

The bug exists in at least Packer 1.5.1 from Homebrew.
The bug did not occur in Packer 1.4.5 from Homebrew.

### Simplified Packer Buildfile

Let me know if you can't reproduce with any of your build files and actually need this.

### Operating system and Environment details

Mac OS 10.14.6 (18G87) with Packer 1.5.1 installed with Homebrew.

### Log Fragments and crash.log files

Ansible output looks like this:
```
==> docker: Executing Ansible: *****a*****n*****s*****i*****b*****l*****e*****-*****p*****l*****a*****y*****b*****o***
**o*****k***** *****-*****- ...
```

**Comment by coolbry95** [comment] 2020-01-03 18:11
It looks like `p.generatedData["WinRMPassword"]` is empty thus it puts the stars after every rune. This also makes sense becuase the Ansible command output when when adding the extra arguments `-vvvv` and `--extra-var ansible_password{{.WinRMPassword}}` the WinRMPassword is blank in the command output.

https://github.com/hashicorp/packer/blob/0649c3f7dca9aabc2b8603cfa723a41a78fe9d30/provisioner/ansible/provisioner.go#L497-L501

**Comment by nywilken** [comment] 2020-01-06 17:37
@nhooey @coolbry95 thanks for opening up this issue and for taking a look at the possible culprit. It looks like it is a duplicate of  https://github.com/hashicorp/packer/issues/8537 so I am going to close this one and ask that all future comments be tracked on the original issue.

**Closed by nywilken** 2020-01-06 17:37 UTC
Labels: bug
