### ISSUE TITLE
Build 'vmware-iso' errored: unexpected EOF

### ISSUE THREAD

**Issue by gstorme** [hashicorp/packer#5405] opened 2017-09-28 21:28 UTC
I'm trying to create a template from a Debian 9 ISO, using the vmware-iso builder.

packer 1.1.0 running on Debian 9
ESXi 5.5.0

Creating the VM works fine, but when I add the "format": "ovf" parameter to end up with an OVF, it fails with the following error:
```
Build 'vmware-iso' errored: unexpected EOF
```

The build file: https://gist.github.com/gstorme/f0802f78fb823e86f7400a0477e56ae1
The packer debug log: https://gist.github.com/gstorme/2bd2a4e6a9852fb26fcab35296c72729

**Comment by mwhooker** [comment] 2017-09-29 04:21
Going to mark this as a duplicate of #4214

**Closed by mwhooker** 2017-09-29 04:21 UTC
