### ISSUE TITLE
PACKER_CACHE_DIR is ignored

### ISSUE THREAD

**Issue by spencer-cdw** [hashicorp/packer#12195] opened 2023-01-13 20:59 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

The `PACKER_CACHE_DIR` is ignored on packer 1.8.5

#### Reproduction Steps

1. Install packer 1.8.5 (I've installed using the official github actions step)
2. Set environment variable `PACKER_CACHE_DIR=/tmp/foobar`
3. Run `packer init` or similar command, observer that the cache is installed in the wrong location 

Expected = /tmp/packer
Actual = /home/githubrunner/.config/packer/plugins/*

```
PACKER_CACHE_DIR=/tmp/packer packer init aws-ubuntu-1804-base.pkr.hcl 
Installed plugin github.com/hashicorp/ansible v1.0.3 in "/home/githubrunner/.config/packer/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.0.3_x5.0_linux_amd64"
Installed plugin github.com/hashicorp/inspec v1.0.0 in "/home/githubrunner/.config/packer/plugins/github.com/hashicorp/inspec/packer-plugin-inspec_v1.0.0_x5.0_linux_amd64"
Installed plugin github.com/hashicorp/amazon v1.1.6 in "/home/githubrunner/.config/packer/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.1.6_x5.0_linux_amd64"
```

### Packer version

1.8.5

### Simplified Packer Template

```
packer {
  required_plugins {
    amazon = {
      version = ">= 1.1.1"
      source  = "github.com/hashicorp/amazon"
    }
    ansible = {
      version = ">= 1.0.2"
      source  = "github.com/hashicorp/ansible"
    }
    inspec = {
      version = ">= 0.0.1"
      source  = "github.com/hashicorp/inspec"
    }
  }
}
```

### Operating system and Environment details

Ubuntu github runner running github actions. This is reproducable locally inside of a ubuntu 22.04 docker container

Here I'm setting PACKER_CACHE_DIR to /tmp, but it is still installing to `/root/.config/packer`
```
docker run -it -v $PWD:/data -e PACKER_LOG=1 -e PACKER_CACHE_DIR=/tmp hashicorp/packer:1.8.5 init /data/aws-ubuntu-1804-base.pkr.hcl
Installed plugin github.com/hashicorp/ansible v1.0.3 in "/root/.config/packer/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.0.3_x5.0_linux_arm64"
```

### Logs

Notice the line 
```
2023/01/13 20:58:30 [INFO] Setting cache directory: /tmp
```
yet the last log line shows
```
Installed plugin github.com/hashicorp/amazon v1.1.6 in "/root/.config/packer/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.1.6_x5.0_linux_arm64"
```
```
2023/01/13 20:58:30 [INFO] Packer version: 1.8.5 [go1.18.9 linux arm64]
2023/01/13 20:58:30 [TRACE] discovering plugins in /bin
2023/01/13 20:58:30 [TRACE] discovering plugins in /root/.config/packer/plugins
2023/01/13 20:58:30 [TRACE] discovering plugins in .
2023/01/13 20:58:30 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/01/13 20:58:30 [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/01/13 20:58:30 [WARN] Config file doesn't exist: /root/.packerconfig
2023/01/13 20:58:30 [INFO] Setting cache directory: /tmp
2023/01/13 20:58:30 [TRACE] init: plugingetter.ListInstallationsOptions{FromFolders:[]string{"/bin/packer", ".", "/root/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"arm64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0x400042e780)}}}}
2023/01/13 20:58:30 [TRACE] listing potential installations for "github.com/hashicorp/amazon" that match ">= 1.1.1". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/bin/packer", ".", "/root/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"arm64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0x400042e780)}}}}
2023/01/13 20:58:30 [TRACE] for plugin github.com/hashicorp/amazon found 0 matching installation(s)
2023/01/13 20:58:30 [TRACE] getting available versions for the github.com/hashicorp/amazon plugin
2023/01/13 20:58:30 [WARNING] github-getter: no GitHub token set, if you intend to install plugins often, please set the PACKER_GITHUB_API_TOKEN env var
2023/01/13 20:58:30 [DEBUG] github-getter: getting "https://api.github.com/repos/hashicorp/packer-plugin-amazon/git/matching-refs/tags"
2023/01/13 20:58:31 [DEBUG] will try to install: [1.1.6 1.1.5 1.1.4 1.1.3 1.1.2 1.1.1]
2023/01/13 20:58:31 [TRACE] fetching checksums file for the "1.1.6" version of the github.com/hashicorp/amazon plugin in "/root/.config/packer/plugins/github.com/hashicorp/amazon"...
2023/01/13 20:58:31 [DEBUG] github-getter: getting "https://github.com/hashicorp/packer-plugin-amazon/releases/download/v1.1.6/packer-plugin-amazon_v1.1.6_SHA256SUMS"
2023/01/13 20:58:32 [TRACE] ignoring invalid remote binary packer-plugin-amazon_v1.1.6_x5.0_linux_386.zip: wrong system, expected linux_arm64
2023/01/13 20:58:32 [TRACE] ignoring invalid remote binary packer-plugin-amazon_v1.1.6_x5.0_openbsd_386.zip: wrong system, expected linux_arm64
2023/01/13 20:58:32 [TRACE] ignoring invalid remote binary packer-plugin-amazon_v1.1.6_x5.0_netbsd_386.zip: wrong system, expected linux_arm64
2023/01/13 20:58:32 [TRACE] ignoring invalid remote binary packer-plugin-amazon_v1.1.6_x5.0_netbsd_arm.zip: wrong system, expected linux_arm64
2023/01/13 20:58:32 [TRACE] ignoring invalid remote binary packer-plugin-amazon_v1.1.6_x5.0_windows_386.zip: wrong system, expected linux_arm64
2023/01/13 20:58:32 [TRACE] About to get: packer-plugin-amazon_v1.1.6_x5.0_linux_arm64.zip
2023/01/13 20:58:32 [DEBUG] github-getter: getting "https://github.com/hashicorp/packer-plugin-amazon/releases/download/v1.1.6/packer-plugin-amazon_v1.1.6_x5.0_linux_arm64.zip"
2023/01/13 20:58:45 [TRACE] listing potential installations for "github.com/hashicorp/ansible" that match ">= 1.0.2". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/bin/packer", ".", "/root/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"arm64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0x400042e780)}}}}
Installed plugin github.com/hashicorp/amazon v1.1.6 in "/root/.config/packer/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.1.6_x5.0_linux_arm64"
```

**Comment by AvoidMe** [comment] 2023-01-24 21:12
I believe you should be using `PACKER_CONFIG_DIR` if caching plugins is your intention, for more info please refer to: https://developer.hashicorp.com/packer/docs/configure#packer-s-plugin-directory

```
➜ PACKER_CONFIG_DIR=/tmp/packer packer init .
Installed plugin github.com/hashicorp/ansible v1.0.3 in "/tmp/packer/.packer.d/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.0.3_x5.0_linux_amd64"
Installed plugin github.com/hashicorp/inspec v1.0.0 in "/tmp/packer/.packer.d/plugins/github.com/hashicorp/inspec/packer-plugin-inspec_v1.0.0_x5.0_linux_amd64"
Installed plugin github.com/hashicorp/amazon v1.2.0 in "/tmp/packer/.packer.d/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.2.0_x5.0_linux_amd64"
```

`PACKER_CACHE_DIR` is using for caching large files (like iso) and is actually working. https://developer.hashicorp.com/packer/docs/configure#packer-s-cache-directory

**Comment by nywilken** [comment] 2023-04-12 19:58
Hi @spencer-cdw thanks for reaching out. The Packer cache directory controlled by `PACKER_CACHE_DIR` is used for storing files such as checksum or ISO files that are downloaded when running `packer build`. As mentioned by @AvoidMe 

The Packer plugins are installed into the default Packer configuration directory, which you can override by setting `PACKER_CONFIG_DIR`. Alternatively, if you just want to set the path for plugin installs you can set `PACKER_PLUGIN_PATH`, which is what we recommend when using the [Packer docker container](https://hub.docker.com/r/hashicorp/packer).  


I'm going to close this issue as this is not a bug. But if you think there is something we can do to improve this experience please feel free to drop us a comment.

**Closed by nywilken** 2023-04-12 19:58 UTC
