### ISSUE TITLE
packer 1.2.0+ doesnt work with vmware esxi anymore

### ISSUE THREAD

**Issue by roguetech** [hashicorp/packer#6624] opened 2018-08-24 12:26 UTC
I am using ESXi 6.7.0 and using packer 1.2.0 + results in the iso not booting. I just get a VMware bios message that no boot device found. If I revert back to packer version 1.1.3 it all works fine. I have tried multiple version of 1.2 but none work

Can you help, please

**Comment by SwampDragons** [comment] 2018-08-24 16:35
Hi, thanks for reaching out. We need some more info from you in order to figure this out:

1) Full debug logs with PACKER_LOG=1 set in your environemnt
2) A minimal Packer template that reproduces the issue.
3) Your host and guest architectures

**Comment by roguetech** [comment] 2018-08-24 17:12
Thanks alot for the reply. Below is the packer.json file i am running, it work file with 1.1.3. Log file attached. the iso is the latest centos7.5.1804 and building it on esxi 6.7.0 standalone hose using its datastore.

Is there anything else you need that will help resolve this?
`
{                                                                                                                      
                                                                                                                       
  "builders":[{                                                                                                        
    "type": "vmware-iso",                                                                                              
    "guest_os_type": "centos-64",                                                                                      
    "tools_upload_flavor": "linux",                                                                                    
    "headless": true,                                                                                                  
    "http_directory": "http",                                                                                          
    "vnc_disable_password": true,                                                                                      
                                                                                                                       
    "boot_command": "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>",                          
    "boot_wait": "1m",                                                                                                 
                                                                                                                       
    "disk_size" : 25000,                                                                                               
    "disk_type_id": "thin",                                                                                            
                                                                                                                       
    "vmx_data": {                                                                                                      
      "ethernet0.networkName": "{{user `esxi_network_name`}}",                                                         
      "config.version": 8,                                                                                             
      "virtualHW.version": 8,                                                                                          
      "ethernet0.present": "true",                                                                                     
      "ethernet0.virtualDev": "vmxnet3",                                                                               
      "ethernet0.startConnected": "true",                                                                              
      "ethernet0.addressType": "generated",                                                                            
      "memsize": "4096",                                                                                               
      "numvcpus": "2",                                                                                                 
      "cpuid.coresPerSocket": "1",                                                                                     
      "ide0:0.fileName": "disk.vmdk",                                                                                  
      "ide0:0.present": "TRUE",                                                                                        
      "ide0:0.redo": "",                                                                                               
      "scsi0:0.present": "FALSE",                                                                                      
      "RemoteDisplay.vnc.enabled": "TRUE",                                                                             
      "RemoteDisplay.vnc.port":  "5900"                                                                                
    },                                                                                                                 
                                                                                                                       
                                                                                                                       
    "iso_url": "{{user `iso_url`}}",                                                                                   
    "iso_checksum": "{{user `iso_checksum`}}",                                                                         
    "iso_checksum_type": "{{user `iso_checksum_type`}}",                                                               
                                                                                                                       
    "ssh_username": "{{user `ssh_username`}}",                                                                         
    "ssh_password": "{{user `ssh_password`}}",                                                                         
    "ssh_timeout" : "1000s",                                                                                           
    "shutdown_command": "shutdown -P now",                                                                             
                                                                                                                       
    "remote_type": "esx5",                                                                                             
    "remote_host": "{{user `esxi_host`}}",                                                                             
    "remote_datastore": "{{user `esxi_datastore`}}",                                                                   
    "remote_username": "{{user `esxi_username`}}",                                                                     
    "remote_password": "{{user `esxi_password`}}",                                                                     
    "keep_registered": true                                                                                            
                                                                                                                       
    }],                                                                                                                
                                                                                                                       
    "provisioners": [                                                                                                  
      {                                                                                                                
        "type": "shell",                                                                                               
        "scripts": [                                                                                                   
          "scripts/C7_build.sh",                                                                                       
          "scripts/C7_sec.sh",                                                                                         
          "scripts/C7_clean.sh"                                                                                        
        ]                                                                                                              
   }                                                                                                                   
  ]                                                                                                                    
}          
'
[packer log.txt](https://github.com/hashicorp/packer/files/2319245/packer.log.txt)

**Comment by SwampDragons** [comment] 2018-08-24 22:50
Hmm. I wonder if this is fixed by #6204...

**Comment by SwampDragons** [comment] 2018-08-24 22:51
I can build the master branch for you if you'd like to test it out; what's the architecture of the system running packer? (windows/linux/darwin)

**Comment by roguetech** [comment] 2018-08-25 10:31
I am running it from centos7.5 aswell

**Comment by DanHam** [comment] 2018-08-25 13:46
@SwampDragons 

#6204 fixed an issue with the boot order in the *resultant* VM. If I'm reading this correctly, this issue is occurring at the very beginning of the build so I don't think #6204 would help.

From what's been described, this looks as though the VM is not finding the ISO that it needs to boot from...

Unfortunately, Master currently has an issue that's preventing builds from even getting to this stage. This will need fixing first I guess... see #6631

**Comment by arizvisa** [comment] 2018-08-26 06:12
#roguetech, typically with vmware issues it's also helpful to provide the generated .vmx.

In that specific instance that you ran, the `packer.log.txt` specifies it's in `/tmp/packer-vmx598489028/packer-vmware-iso.vmx`. If you run another test or anything, check out the packer logfile for what it's at.

Anyways, with this .vmx it should be possible to repro the issue.

**Comment by roguetech** [comment] 2018-08-27 07:42
Thanks for the reply, here is the .vmx file (in the zip) for this and some screenshots to show the directories that are created 
![packer1](https://user-images.githubusercontent.com/1923916/44647045-de261a00-a9d4-11e8-9679-487875c8d1fa.PNG)
![packer2](https://user-images.githubusercontent.com/1923916/44647046-de261a00-a9d4-11e8-9213-088ee9229d24.PNG)


[packer-vmware-iso.zip](https://github.com/hashicorp/packer/files/2322885/packer-vmware-iso.zip)

**Comment by roguetech** [comment] 2018-08-27 08:06
i have compare the a 1.2.5 and 1.1.3 vmx file and have noticed that the 1.2.5 is missing reference to the cdrom device

`
ide1:0.devicetype = "cdrom-image"
ide1:0.filename = "/vmfs/volumes/datastore1/packer_cache/a9ad504d4571614d97a2ff712de7356f6821a0e8f08457643409e58b4b1c4920.iso"
ide1:0.present = "TRUE"
`

**Comment by DanHam** [comment] 2018-08-27 11:02
@roguetech Yep... that'll be the reason the VM isn't finding the ISO to boot from!

**Comment by roguetech** [comment] 2018-08-27 12:51
Cool, So my question is. Is this something that has changed in the code, so the configuration needs to change? or it something that is broken since version 1.1.3?

**Comment by DanHam** [comment] 2018-08-27 13:14
@roguetech 

Try removing the following lines from the `vmx_data` section of your template to see if that helps.

```
      "ide0:0.fileName": "disk.vmdk",                                                                                  
      "ide0:0.present": "TRUE",                                                                                        
      "ide0:0.redo": "",                                                                                               
      "scsi0:0.present": "FALSE",
```

**Comment by arizvisa** [comment] 2018-08-28 04:38
@roguetech, also if you need to force a specific disk type, you can try specifying the `disk_adapter_type` option via https://www.packer.io/docs/builders/vmware-iso.html#disk_adapter_type instead of hardcoding it with `vmx_data`.

Although detection of the disk adapter type for adding the iso should work regardless of what you hardcode in `vmx_data`, chances are that this is probably a regression when trying to interpret `vmx_data` that I might've introduced in my PR that exposes this stuff the user for `vmware-iso` builders. :-/

**Comment by SwampDragons** [comment] 2018-08-28 16:38
@arizvisa should I leave this open until we get a chance to investigate whether it's a regression that can be fixed?

**Comment by AndrewSav** [comment] 2018-10-05 10:06
@arizvisa hey, just wanted to touch base re: investigating if it's a regression that can be fixed. Thanks!

**Comment by SwampDragons** [comment] 2018-11-09 20:15
I think the best way to do this would be to check for fields in vmx_data that Packer overrides, and error during validation with a useful error message if both a packer template level override and a vmx_data value are set.

**Comment by SwampDragons** [comment] 2018-11-09 23:54
I've opened a PR that might have helped prevent this by making sure that users know when they're overriding Packer-templated vmx data

**Closed** 2018-11-12 14:31 UTC
Labels: builder/vmware-esxi, need-more-info, regression
