### ISSUE TITLE
packer build time out on provisioner

### ISSUE THREAD

**Issue by fmontaldo** [hashicorp/packer#7068] opened 2018-12-04 20:21 UTC
Hi folks,

I got a packer build that works in another mac there I got but now they gave an older one with less ram. 

When I try to run a packer build it hungs in the provisioners phase. 

packer version 

Packer v1.3.2

this is the log file

https://gist.github.com/fmontaldo/fcb0b86252a9cc20f4ccfbd0924be320

this is the packer.json

https://gist.github.com/fmontaldo/e0e4644df1b69234a8083c265327eeeb

Please let me know why is not running propertly. Maybe I need to dowgrade the version of virtualbox and packer?.

This is the specs off my machine.

MacBook Pro (13-inch, Mid 2012)
Processor 2,5 GHz Intel Core i5
RAM 8 GB 1600 MHz DDR3

Thanks in advance

Federico

**Comment by SwampDragons** [comment] 2018-12-04 21:32
Thanks for reaching out! It looks like it's hanging in the windows-restart provisioner, which means Packer told the machine to reboot and Packer never saw it come back up. I'd recommend running this again and actually watching the build in the vnc window to see whether it comes back up from the restart. There's a good chance that if your computer doesn't have much RAM you'll have to increase the timeout using the `restart_timeout` option; see https://www.packer.io/docs/provisioners/windows-restart.html for details.  

Sine this is a general question and not a bug report or feature request, I'm going to close this github issue. If you have further questions, please use the [mailing list](https://groups.google.com/forum/#!forum/packer-tool), which is better for these kinds of discussions.

**Closed by SwampDragons** 2018-12-04 21:32 UTC
