### ISSUE TITLE
Guest image fails to restart after preseed

### ISSUE THREAD

**Issue by technokhan13** [hashicorp/packer#9252] opened 2020-05-18 20:25 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
I would like to apologize if this is not the proper place for this sort of issue. I am using Packer to build both Ubuntu 16.04 and Ubuntu 18.04 qcow2 images from base ISOs. Ubuntu 16.04 fails to reboot properly once the preseed portion is finished but before any provisioner can kick off. Ubuntu 18.04 does not experience this problem at all. 

#### Reproduction Steps

To reproduce, use the Packer and Qemu version listed below and use the config file pasted below. I can provide the preseed file if needed. Both Ubuntu 16 and 18 use the same preseed file, however Ubuntu 16 is the only one that fails to reboot properly and become available to the provisioner. 

### Other Info

I am not 100% sure this is a Packer issue, however, as it functions as expected with Ubuntu 18 but not Ubuntu 16 I feel this a worth while place to start. I can provide any information required and I likely did not include something that is of importance. Please let me know. Thank you for any help!

### Packer Version
1.5.6

### Simplified Packer Buildfile
```
{
    "builders": [
        {
        "boot_command": [
            "OMMITED BOOT KEYSTROKES"
            "/install/vmlinuz ",
            "initrd=/install/initrd.gz ",
            "net.ifnames=0 ",
            "auto-install/enable=true ",
            "debconf/priority=critical ",
            "reboot=pci ",
            "preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/ub16-tst.cfg",
            "<enter>"
        ], 
        "boot_wait": "10s",
        "type": "qemu",
        "iso_url": "file:///home/technokhan/Labs/workspaces/packer/iso/ubuntu-16.04.6-server-amd64.iso",
        "iso_checksum": "ac8a79a86a905ebdc3ef3f5dd16b7360",
        "iso_checksum_type": "md5",
        "output_directory": "output_ubuntu16_test",
        "shutdown_command": "sudo shutdown -P now",
        "disk_size": "25000M",
        "format": "qcow2",
        "accelerator": "kvm",
        "http_directory": "http",
        "ssh_username": "ubuntu",
        "ssh_password": "thePassword",
        "ssh_timeout": "20m",
        "vm_name": "ub16test.qcow2",
        "net_device": "virtio-net",
        "disk_interface": "virtio"
        }
    ],
    "provisioners": [
        {
            "type": "ansible",
            "playbook_file": "./ansible/prep_work.yml",
            "user": "ubuntu",
            "ssh_authorized_key_file": "./keys/id_rsa.pub",
            "roles_path": "./roles/",
            "extra_arguments": [
                "--private-key", "/home/technokhan/Labs/workspaces/packer/keys/id_rsa",
                "-e", "ansible_python_interpreter=/usr/bin/python3"
            ]
        }
    ]
}
```

### Operating system and Environment details

Fedora 31
QEMU as the builder: version 4.1.1 (qemu-4.1.1-1.fc31)
KVM as the accelerator

### Log Fragments and crash.log files

<details>
 <summary>PACKER_LOG=1 Info</summary>

```
2020/05/18 16:09:09 packer-builder-qemu plugin: Attempting to open config file: /home/technokhan/.packerconfig
2020/05/18 16:09:09 packer-builder-qemu plugin: [WARN] Config file doesn't exist: /home/technokhan/.packerconfig
2020/05/18 16:09:09 packer-builder-qemu plugin: Setting cache directory: /home/technokhan/Labs/workspaces/packer/packer_cache
2020/05/18 16:09:09 packer-builder-qemu plugin: args: []string{"packer-builder-qemu"}
2020/05/18 16:09:09 packer-builder-qemu plugin: Plugin address: unix /tmp/packer-plugin293846698
2020/05/18 16:09:09 packer-builder-qemu plugin: Waiting for connection...
2020/05/18 16:09:09 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin293846698
2020/05/18 16:09:09 packer-builder-qemu plugin: Serving a plugin connection...
2020/05/18 16:09:09 Creating plugin client for path: /usr/bin/packer
2020/05/18 16:09:09 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-ansible"}
2020/05/18 16:09:09 Waiting for RPC address for: /usr/bin/packer
2020/05/18 16:09:09 packer-provisioner-ansible plugin: [INFO] Packer version: 1.5.6 [go1.14.2 linux amd64]
2020/05/18 16:09:09 packer-provisioner-ansible plugin: Checking 'PACKER_CONFIG' for a config file path
2020/05/18 16:09:09 packer-provisioner-ansible plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/05/18 16:09:09 packer-provisioner-ansible plugin: Attempting to open config file: /home/technokhan/.packerconfig
2020/05/18 16:09:09 packer-provisioner-ansible plugin: [WARN] Config file doesn't exist: /home/technokhan/.packerconfig
2020/05/18 16:09:09 packer-provisioner-ansible plugin: Setting cache directory: /home/technokhan/Labs/workspaces/packer/packer_cache
2020/05/18 16:09:09 packer-provisioner-ansible plugin: args: []string{"packer-provisioner-ansible"}
2020/05/18 16:09:09 packer-provisioner-ansible plugin: Plugin address: unix /tmp/packer-plugin179401683
2020/05/18 16:09:09 packer-provisioner-ansible plugin: Waiting for connection...
2020/05/18 16:09:09 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin179401683
2020/05/18 16:09:09 packer-provisioner-ansible plugin: Serving a plugin connection...
2020/05/18 16:09:09 Build debug mode: false
2020/05/18 16:09:09 Force build: false
2020/05/18 16:09:09 On error: 
2020/05/18 16:09:09 Preparing build: qemu
2020/05/18 16:09:09 packer-builder-qemu plugin: use specified accelerator: kvm
2020/05/18 16:09:09 packer-builder-qemu plugin: MemorySize 0 is too small, using default: 512
2020/05/18 16:09:09 packer-builder-qemu plugin: CpuCount 0 too small, using default: 1
2020/05/18 16:09:09 packer-provisioner-ansible plugin: ansible-playbook version: 2.9.6
2020/05/18 16:09:09 Waiting on builds to complete...
2020/05/18 16:09:09 Starting build run: qemu
2020/05/18 16:09:09 Running builder: qemu
2020/05/18 16:09:09 [INFO] (telemetry) Starting builder qemu
2020/05/18 16:09:09 packer-builder-qemu plugin: Qemu path: /usr/bin/qemu-system-x86_64, Qemu Image page: /usr/bin/qemu-img
2020/05/18 16:09:09 packer-builder-qemu plugin: Acquiring lock for: file:///home/technokhan/Labs/workspaces/packer/iso/ubuntu-16.04.6-server-amd64.iso?checksum=md5%3Aac8a79a86a905ebdc3ef3f5dd16b7360 (/home/technokhan/Labs/workspaces/packer/packer_cache/03fbc619c10aa1efeebbc88e7810e46599c8c225.iso.lock)
2020/05/18 16:09:11 packer-builder-qemu plugin: Leaving retrieve loop for ISO
2020/05/18 16:09:11 packer-builder-qemu plugin: No floppy files specified. Floppy disk will not be made.
2020/05/18 16:09:11 packer-builder-qemu plugin: [INFO] Creating disk with Path: output_ubuntu16_test/ub16test.qcow2 and Size: 25000M
2020/05/18 16:09:11 packer-builder-qemu plugin: Executing qemu-img: []string{"create", "-f", "qcow2", "output_ubuntu16_test/ub16test.qcow2", "25000M"}
2020/05/18 16:09:11 packer-builder-qemu plugin: stdout: Formatting 'output_ubuntu16_test/ub16test.qcow2', fmt=qcow2 size=26214400000 cluster_size=65536 lazy_refcounts=off refcount_bits=16
2020/05/18 16:09:11 packer-builder-qemu plugin: stderr:
2020/05/18 16:09:11 packer-builder-qemu plugin: Found available port: 8620 on IP: 0.0.0.0
2020/05/18 16:09:11 packer-builder-qemu plugin: Looking for available communicator (SSH, WinRM, etc) port between 2222 and 4444
2020/05/18 16:09:11 packer-builder-qemu plugin: Found available port: 2660 on IP: 127.0.0.1
2020/05/18 16:09:11 packer-builder-qemu plugin: Looking for available port between 5900 and 6000 on 127.0.0.1
2020/05/18 16:09:11 packer-builder-qemu plugin: Found available port: 5983 on IP: 127.0.0.1
2020/05/18 16:09:11 packer-builder-qemu plugin: Found available VNC port: 5983 on IP: 127.0.0.1
2020/05/18 16:09:11 packer-builder-qemu plugin: Qemu --version output: QEMU emulator version 4.1.1 (qemu-4.1.1-1.fc31)
2020/05/18 16:09:11 packer-builder-qemu plugin: Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
2020/05/18 16:09:11 packer-builder-qemu plugin: Qemu version: 4.1.1
2020/05/18 16:09:11 packer-builder-qemu plugin: Qemu Builder has no floppy files, not attaching a floppy.
2020/05/18 16:09:11 packer-builder-qemu plugin: Executing /usr/bin/qemu-system-x86_64: []string{"-name", "ub16test.qcow2", "-machine", "type=pc,accel=kvm", "-netdev", "user,id=user.0,hostfwd=tcp::2660-:22", "-drive", "file=output_ubuntu16_test/ub16test.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-cdrom", "/home/technokhan/Labs/workspaces/packer/iso/ubuntu-16.04.6-server-amd64.iso", "-device", "virtio-net,netdev=user.0", "-boot", "once=d", "-vnc", "127.0.0.1:83", "-display", "gtk", "-m", "512M"}
2020/05/18 16:09:11 packer-builder-qemu plugin: Started Qemu. Pid: 310097
2020/05/18 16:09:23 packer-builder-qemu plugin: Connected to VNC desktop: QEMU (ub16test.qcow2)
2020/05/18 16:09:23 packer-builder-qemu plugin: Special code '<enter>' found, replacing with: 0xFF0D
2020/05/18 16:09:23 packer-builder-qemu plugin: [INFO] Waiting 1s
2020/05/18 16:09:24 packer-builder-qemu plugin: Special code '<f6>' found, replacing with: 0xFFC3
Bunch more input data 
2020/05/18 16:10:14 packer-builder-qemu plugin: Special code '<enter>' found, replacing with: 0xFF0D
2020/05/18 16:10:15 packer-builder-qemu plugin: [INFO] Waiting for SSH, up to timeout: 20m0s
2020/05/18 16:10:15 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2660...
2020/05/18 16:10:15 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/05/18 16:10:15 packer-builder-qemu plugin: [DEBUG] handshaking with SSH
2020/05/18 16:10:45 packer-builder-qemu plugin: [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:38990->127.0.0.1:2660: read: connection reset by peer
2020/05/18 16:10:52 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2660...
```

It just continues endlessly until the timeout limit hits. To be clear the Preseed does finish and attempts to reboot. It just never comes up.
</details>

**Comment by nywilken** [comment] 2020-05-19 11:38
Hi @technokhan13 I updated your description to format the sample build configuration and logs. This does sound like a configuration issue more than a Packer issue. So I will see if I can help out a bit. You mention that the preseed file completes for the 16.04 build and attempts to reboot. Is it stuck trying to reboot? Or does it reboot and doesn't come back online ("It just never comes up")? 

Have you checked the preseed file to ensure there are no statements that may only work with the 18.04? 

Sharing the pressed file is helpful in trying to reproduce your issue. With that said, the bento boxes have preseed files that work for both 16.04 and 18.04 which could be a good reference point https://github.com/chef/bento/blob/master/packer_templates/ubuntu/http/preseed.cfg

**Comment by technokhan13** [comment] 2020-05-19 21:00
Hello @nywilken! Thank you for fixing the formatting for me. This is my first time trying to submit something like this. I was somewhat afraid that it just might be a configuration problem. To try and remove this possibility I pulled other preseeds from various online sources tailored for Ubuntu 16.04 and had the same result.

I have not combed through the entire preseed line by line just yet and to be honest it would be fairly easy to over look something I think. Though I am just about ready to start at the end and work my way backwards with it line by line. That said I will include the preseed I have been working with the most and is indeed the same used for Ubuntu 18. So it seems a logical place to look.

Back to your question regarding it getting stuck during the reboot or otherwise. I am not 100% sure on this. All goes wrong at the same point the Ubuntu 18.04 restarts and then becomes available to SSH and the Ansible provisoner I have set up. The Ubuntu 16.04 image just never comes back up after the screen goes black. All attempts to interact with it fail. If you know a solid way I can verify this portion I would love to test it for you.


[ubuntu16-preseed.txt](https://github.com/hashicorp/packer/files/4653074/ubuntu16-preseed.txt)

I am up for any ideas. I greatly appreciate it!

**Comment by SwampDragons** [comment] 2020-09-09 21:22
My recommendation is to try to run the image using the command logged here: 
```
Executing /usr/bin/qemu-system-x86_64: []string{"-name", "ub16test.qcow2", "-machine", "type=pc,accel=kvm", "-netdev", "user,id=user.0,hostfwd=tcp::2660-:22", "-drive", "file=output_ubuntu16_test/ub16test.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-cdrom", "/home/technokhan/Labs/workspaces/packer/iso/ubuntu-16.04.6-server-amd64.iso", "-device", "virtio-net,netdev=user.0", "-boot", "once=d", "-vnc", "127.0.0.1:83", "-display", "gtk", "-m", "512M"}
``` 

which cleaned up into a command-line-worthy command is 

```/usr/bin/qemu-system-x86_64 -name ub16test.qcow2 -machine type=pc,accel=kvm -netdev user,id=user.0,hostfwd=tcp::2660-:22 -drive file=output_ubuntu16_test/ub16test.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2 -cdrom /home/technokhan/Labs/workspaces/packer/iso/ubuntu-16.04.6-server-amd64.iso -device virtio-net,netdev=user.0 -boot once=d -vnc 127.0.0.1:83 -display gtk -m 512M```

Then connect to the vnc port (5983) via a vnc viewer and manually enter your boot command. See where the preseed gets stuck. 

You'll need to serve the preseed via your own webserver, or grab it from s3 or something instead of depending on the Packer one. But doing this will help you determine whether it's a packer issue or not -- if it isn't, the image will still fail to come up. If it is, the preseed will run successfully.

**Comment by SwampDragons** [comment] 2020-09-16 17:20
@technokhan13 Were you able to figure this out?

**Comment by SwampDragons** [comment] 2020-10-07 23:22
Closing because we never heard back. We can reopen if this is still a problem.

**Closed by SwampDragons** 2020-10-07 23:22 UTC
Labels: builder/qemu, question, waiting-reply
