### ISSUE TITLE
Packer v1.6.3 - Error loading credentials for AWS Provider

### ISSUE THREAD

**Issue by Manojvnair1** [hashicorp/packer#10000] opened 2020-09-27 05:13 UTC
Packer v1.6.3 giving error while fetching loading credentials from IAM instance role.

Please find log extract:
packer-builder-amazon-ebs plugin: [INFO] Attempting to use session-derived credentials
Build 'amazon-ebs' errored after 3 seconds 133 milliseconds: Error loading credentials for AWS Provider: %!w(<nil>)
==> Wait completed after 3 seconds 133 milliseconds
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error loading credentials for AWS Provider: %!w(<nil>)

**Comment by nywilken** [comment] 2020-09-27 11:42
Hi there thanks for reaching out. It looks like the AWS builder is running into issues displaying the error being returned when loading credentials. 


Can you please share your build template (stripped of any sensitive information) along with a copy the debug logs `PACKER_LOG=1 packer build <template>`. Cheers.

**Comment by chillosu** [comment] 2020-09-27 19:21
This was working on the previous version and just started breaking with the new version.

We inherit the IAM role from the underlying ec2 instance it's running on to AMI building.

**Comment by bretmartin** [comment] 2020-09-28 00:41
This is definitely a regression in 1.6.3 over 1.6.2 (I downgraded to confirm). I suspect this is caused by #9981 but I ran out of time last night (well, early this morning) trying to understand how and confirm that.

**Comment by William-Luo0** [comment] 2020-09-28 13:12
Not sure if this is helpful or not since I believe the AWS Go SDK is meant to handle auth; but this was not working for me in Codebuild which utilises ECS under the hood.
The special url for ECS differs from EC2 in that it uses `169.254.170.2` as the endpoint rather than the typical `169.254.169.254`.

The full credentials can be retrieved from the url `169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` while in an ECS container.

**Comment by nywilken** [comment] 2020-09-28 14:19
Hello again, thanks for the additional information - super helpful. I thought it might've been a regression but realize now that I failed to ask, apologies. There looks to be two issues: one being the auth regression, the second being the error logging. We'll work on getting this fixed for the next release if not sooner.

**Comment by nywilken** [comment] 2020-09-28 14:30
Hi @William-Luo0 thanks for the added context. When you say this was not working for me in Codebuild. 

Are you taking about Packer or the use of session credentials within Codebuild? If Packer related was it working in v1.6.2? 

I'm having a little difficulty making the connection so want to make sure I get the full picture. Thanks!

**Comment by bretmartin** [comment] 2020-09-28 15:42
@nywilken For the error logging, I think the problem is that `err` is overwritten in [this section of code](https://github.com/hashicorp/packer/pull/9981/files#diff-b1f7b5360d00f691959daf559397cd03R346-R357). Working on this...

**Comment by nywilken** [comment] 2020-09-28 16:33
> @nywilken For the error logging, I think the problem is that `err` is overwritten in [this section of code](https://github.com/hashicorp/packer/pull/9981/files#diff-b1f7b5360d00f691959daf559397cd03R346-R357). Working on this...

@bretmartin that's correct. The error is actually nil there as GetCredentialsFromSession() returns back successfully. The code should not actually error there. Which is most likely the regression as well - it is returning an error when there is no error. I have a WIP branch created if you want to give it a look over/test. Happy to  work with you on the pushing forward a fix if you're interested in working on it.

**Comment by bretmartin** [comment] 2020-09-28 16:38
@nywilken This is literally my first time touching Go code so you're gonna beat me to this for sure! I'm building your WIP right now to give it a shot, though.

**Comment by bretmartin** [comment] 2020-09-28 16:43
Presuming #10007 is a complete fix, is there a test coverage issue here? If so, is it HC practice to handle that with the bug fix or separately?

**Comment by nywilken** [comment] 2020-09-28 17:31
> Presuming #10007 is a complete fix, is there a test coverage issue here? If so, is it HC practice to handle that with the bug fix or separately?

Great question, tests should accompany the fix when possible. The exception being the reported bug involves an intricate infrastructure setup that we can not mimic. In those cases we try to add as much test coverage as possible and ask the community for help in testing against some of the more advance setups. The practice behind testing is best captured by Terraform [here](https://www.terraform.io/docs/extend/best-practices/testing.html#regression-tests), which we at Packer follow. 

The PR is currently listed as a WIP to see what is missing and to identify if there are any other issues not accounted for. 

With that said, I'm going to drop a link to the test binaries [here](https://app.circleci.com/pipelines/github/hashicorp/packer/7350/workflows/e33286a2-9467-430b-916c-a1c07dbd459b/jobs/83745/artifacts) in case others who may be running into this issue can test against.

**Comment by William-Luo0** [comment] 2020-09-29 10:33
> Hi @William-Luo0 thanks for the added context. When you say this was not working for me in Codebuild.
> 
> Are you taking about Packer or the use of session credentials within Codebuild? If Packer related was it working in v1.6.2?
> 
> I'm having a little difficulty making the connection so want to make sure I get the full picture. Thanks!

Sorry, just had a chance to do another review of my repo, there were other changes causing the failure. Ignore me 😅

**Comment by genvidkyle** [comment] 2020-09-29 14:28
Just ran into this as well

**Comment by SwampDragons** [comment] 2020-09-29 16:56
Sorry about this, all -- This is my fault. I'll make sure that we have better testing around this authentication code using the Amazon mocks before the next release so this won't happen again. 

This is definitely gonna be a wider-spread regression than most, so @nywilken I think we should leave the issue open even when we merge the fix, until Packer 1.6.4 is released, so people can find it easily. 

We should also push a "nightly" build as soon as we merge the fix in 10007 so that users have a workaround right away instead of waiting for next Tuesday's "nightly" release.

**Comment by Porkepix** [comment] 2020-09-29 17:01
> Sorry about this, all -- This is my fault. I'll make sure that we have better testing around this authentication code using the Amazon mocks before the next release so this won't happen again.
> 
> This is definitely gonna be a wider-spread regression than most, so @nywilken I think we should leave the issue open even when we merge the fix, until Packer 1.6.4 is released, so people can find it easily.
> 
> We should also push a "nightly" build as soon as we merge the fix in 10007 so that users have a workaround right away instead of waiting for next Tuesday's "nightly" release.

Maybe when regression result in complete breakage is it possible to have a dot release with just this fix? I guess some use cases can become quite painful when it comes to downgrade versions.

**Comment by SwampDragons** [comment] 2020-09-29 17:22
Yes, I'm weighing right now whether this regression merits a fast-follow release. Either way we need to get the patch reviewed and tested before the release can go out so it'll be a day or two.

**Comment by SwampDragons** [comment] 2020-09-29 23:08
We've merged a patch for this and will do a fast-follow release tomorrow to fix this. Sorry again, everyone.

**Comment by SwampDragons** [comment] 2020-09-30 19:39
1.6.4 has been released.

**Closed by SwampDragons** 2020-09-30 19:39 UTC
Labels: bug, builder/amazon, regression, track-internal
