### ISSUE TITLE
Hyperv-iso with ssh communicator ignores ssh_host, and the default can not properly determine the IP

### ISSUE THREAD

**Issue by digitalirony** [hashicorp/packer#4825] opened 2017-04-24 11:59 UTC
Using packer 0.12.1
Running scripts via Jenkins on a windows slave(via cygwin to interpret bash/use ssh).
Also running it manually to debug with PACKER_LOG=1

Packer config: https://gist.github.com/anonymous/ccf2517937033699d76fc61655c1283d

I will try and get a PACKER_LOG=1 output, but it is hard to capture due to the automation we are using. 

The gist(no pun intended, but certainly appreciated) of the error output is:
[DEBUG] Error getting SSH address: No ip address.

It just streams the above error message over and over until ssh timeout is reached, at which point it tears down the build and exits. 

I have tested ssh into the machine manually from inside of cygwin once the machine is installed and up. Manual ssh works correctly without issue. 

I am no good at all with 'go' so I am unable to debug the code myself. However the error appears to be here:
https://github.com/hashicorp/packer/blob/master/builder/hyperv/iso/builder.go#L381

The line does not in any way account for ssh_host configuration option for the ssh communicator. Not only this, but it is unable to properly determine the IP address of the VM, so, unless I am missing something that isn't obvious(at least to me), this means building a linux  hyperv-iso using packer is impossible?

**Comment by mwhooker** [comment] 2017-04-24 19:05
Thanks for the report. Can you verify that this is still an issue with the latest release of packer?

**Comment by invisibleaxm** [comment] 2017-05-01 14:17
Hello,

I am using packer v1.0.0 on windows and I can confirm that I am experiencing the same issue while trying to build a linux (CentOS 7) vm. The VM builds fine but packer times out waiting for SSH.

I enabled the PACKER_LOG=1 and I get the same issue:
[DEBUG] Error getting SSH address: No ip address.

I confirmed that I could login (via the console) to the Centos7 VM created by packer and the VM had an internal IP with external network access, SSH was up and running and listening on port 22 with firewall down, etc and still no luck (tcpdump showed no traffic to port 22).

For what it's worth, my get-vm powershell commandlet shows a null/empty string for the IPAddress field for all of my (linux) vms. I believe this is the "normal" scenario for Linux guests unless you manually install the Linux Integration Services on the guest: https://www.microsoft.com/en-us/download/details.aspx?id=51612 

```
> get-vm | select -ExpandProperty NetworkAdapters | select VMName,IPAddresses

VMName                     IPAddresses
------                            -----------
centos7-invisibleaxm   {}
MobyLinuxVM             {}
precise64                     {}
```
Can you confirm if somehow having the LIS is a requirement?

**Comment by invisibleaxm** [comment] 2017-05-01 16:11
I can confirm that after manually installing the Linux Integration Services, my get-vm commandlet returned and IP address and packer was able to continue the installation

```
VMName               IPAddresses
------               -----------
centos7-invisibleaxm {192.168.1.95}
MobyLinuxVM          {}
precise64            {}

```

Here are the logs after the change:

```
2017/05/01 11:06:28 packer.exe: 2017/05/01 11:06:28 [DEBUG] Error getting SSH address: No ip address.
2017/05/01 11:06:38 packer.exe: 2017/05/01 11:06:38 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 192.168.1.95:22: connectex: No connection could be made because the target machine actively refused it.
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 [INFO] Attempting SSH connection...
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 reconnecting to TCP connection for SSH
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 handshaking with SSH
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 handshake complete!
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 [INFO] no local agent socket, will not connect agent
==> hyperv-iso: Connected to SSH!
2017/05/01 11:06:48 ui: ==> hyperv-iso: Connected to SSH!
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 Running the provision hook
2017/05/01 11:06:48 ui: ==> hyperv-iso: Gracefully halting virtual machine...
==> hyperv-iso: Gracefully halting virtual machine...
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 Executing shutdown command: /sbin/halt -p
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 opening new ssh session
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 starting remote command: /sbin/halt -p
2017/05/01 11:06:48 packer.exe: 2017/05/01 11:06:48 Waiting max 5m0s for shutdown to complete
```

Any suggestions ? Does this mean I will have to make sure to install the LIS driver's to get packer to work?

**Comment by digitalirony** [comment] 2017-05-01 17:24
Well, I am using the "ssh_host" : <insert IP> option in the build config.
Also, supposedly, since centos 6.5, LIS should be installed(not the case
for me either with 7). However, using the ssh_host option in the config,
the build doesn't read it, and still fails. So I ended up modifying the
code, and compiling manually to force it always 'require/read' the ssh_host
option, and this worked for me.

**Comment by wickedviking** [comment] 2017-05-04 17:33
LIS is installed, what you need are the daemons. Add the following to the %post section of your ks.cfg:

```
#hyperv support
if [ $(virt-what) == "hyperv" ]; then
    yum -y install hyperv-daemons
    systemctl enable hypervvssd
    systemctl enable hypervkvpd
fi
```

**Comment by invisibleaxm** [comment] 2017-05-04 19:27
Sweet! I'll spend some cycles testing this, i guess it makes sense that
this will be causing the hyp not talk to built-in lis (which btw i prefer
to use since they are easier to maintain)

Thanks again!!

Alex

**Comment by wickedviking** [comment] 2017-05-05 18:00
@mwhooker I don't think this is really a bug on packer's behalf, more of a nuance for working with Hyper-V. The daemons need to be installed, enabled, and running after the kickstart reboots. This is a RHEL & derivatives specific solution. Ubuntu, for example, is slighty different. And the guest OS must have Hyper-V LIS support, so it's not a global thing as some distro's are not yet supported. If anything, this should just be an addition to the Hyper-V builder docs.

**Comment by taliesins** [comment] 2017-07-01 06:25
This is more an issue with running OSes on hypervisors that do not have built in drivers/support for the hypervisor they are running in.

Closing for now.

**Comment by wickedviking** [comment] 2017-07-07 13:53
That's not at all what this is about, the OSes mentioned do in fact have the drivers pre-packaged, in the case of CentOS, and I assume most RHEL derivatives, the daemons are missing and cannot be installed without network connections available to the %POST section of the kickstart.

Two things must accomplished to build RHEL derivatives on Hyper-V, 1st you must ensure the system being built has network in %post, this can be done  via 

```
network --bootproto=dhcp --onboot=on --device=eth0
```

Then in post you need to ensure the daemons are install, but only when using hyper-v, which is done via

```
#hyperv support
if [ $(virt-what) == "hyperv" ]; then
    yum -y install hyperv-daemons
    systemctl enable hypervvssd
    systemctl enable hypervkvpd
fi
```

With out both of these workarounds, hyperv-iso will not build RHEL systems. Before you write this off as a CentOS problem, which is debatable since they have provided the functionality required, you should consider whether this is a matter of documentation or if some hyperv specific functionality should be added to packer to allow these systems to build. CentOS is not a flavor of the month after all.

Packer is the failure point here, not CentOS or Hyper-V.

**Comment by SwampDragons** [comment] 2019-01-04 17:43
Thanks, Ladar! I've reopened until I get a chance to test out your patch.

**Closed** 2019-01-04 20:14 UTC
Labels: builder/hyperv, communicator/ssh, thinking
