### ISSUE TITLE
amazon-ebsvolume fails with `Build 'amazon-ebsvolume' errored: unexpected EOF`

### ISSUE THREAD

**Issue by orontee** [hashicorp/packer#5519] opened 2017-10-26 12:16 UTC
Use of the amazon-ebsvolume fails with  `Build 'amazon-ebsvolume' errored: unexpected EOF` error.

Packer 1.1.1

Windows 10 Pro and Ubuntu 16.04

https://gist.github.com/orontee/9273158f117e090a9cddd8433113eda8

**Comment by orontee** [comment] 2017-10-26 12:18
Note that the provided `userdata.ps1` file is used successfully with the amazon-ebs builder to build AMIs.

**Comment by mwhooker** [comment] 2017-10-26 18:24
Thanks for the report. Here's the stacktrace

```
==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is nil, not ebsvolume.EbsVolumes
2017/10/26 13:38:54 packer.exe:
2017/10/26 13:38:54 packer.exe: goroutine 27 [running]:
2017/10/26 13:38:54 packer.exe: github.com/hashicorp/packer/builder/amazon/ebsvolume.(*Builder).Run(0xc042422400, 0x311a3a0, 0xc042156300, 0x3111740, 0xc0421500f0, 0x3118d00, 0xc04206c020, 0x80000000018, 0x28, 0x28, ...)
2017/10/26 13:38:54 packer.exe:         /Users/mwhooker/go/src/github.com/hashicorp/packer/builder/amazon/ebsvolume/builder.go:204 +0x1bed
2017/10/26 13:38:54 packer.exe: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc042336820, 0x1, 0xc04214e510, 0x0, 0x0)
2017/10/26 13:38:54 packer.exe:         /Users/mwhooker/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:93 +0x1e4
2017/10/26 13:38:54 packer.exe: reflect.Value.call(0xc0420ec660, 0xc042154120, 0x13, 0x2086372, 0x4, 0xc0422d3f20, 0x3, 0x3, 0xc042039078, 0xc0423f4fb8, ...)
2017/10/26 13:38:54 packer.exe:         /usr/local/go/src/reflect/value.go:434 +0x90d
2017/10/26 13:38:54 packer.exe: reflect.Value.Call(0xc0420ec660, 0xc042154120, 0x13, 0xc0422d3f20, 0x3, 0x3, 0xc0422d3f60, 0x716dfc, 0xc0423f4f60)
2017/10/26 13:38:54 packer.exe:         /usr/local/go/src/reflect/value.go:302 +0xab
2017/10/26 13:38:54 packer.exe: net/rpc.(*service).call(0xc04215a480, 0xc042152320, 0xc0423141e0, 0xc04215e280, 0xc0420d8c60, 0x1b080a0, 0xc04214e4cc, 0x18a, 0x1aafe00, 0xc04214e510, ...)
2017/10/26 13:38:54 packer.exe:         /usr/local/go/src/net/rpc/server.go:381 +0x149
2017/10/26 13:38:54 packer.exe: created by net/rpc.(*Server).ServeCodec
2017/10/26 13:38:54 packer.exe:         /usr/local/go/src/net/rpc/server.go:475 +0x372
```

and from that I can tell this is a duplicate of #5486

We'll get this fixed for next release

**Closed by mwhooker** 2017-10-26 18:24 UTC
Labels: builder/amazon, crash
