### ISSUE TITLE
vsphere postprocessor with multiple builders

### ISSUE THREAD

**Issue by nheetesonne** [hashicorp/packer#7083] opened 2018-12-07 15:10 UTC
When using multiple builders in a json file the vsphere post processor has a limitation when uploading to the artifact to a vcenter.

I have two builders in one json, both these builders create a VM on VMware. At the end I need it to upload the created artifacts to a vCenter server.

The required vm_name in the post processor however is the same for both artifacts even though the builder creates two different artifacts. This causes both uploads to have the same destination vm_name.

I feel it would be a better fit if the vm_name in the post processor would be taken from the builder. This would make the name of the uploaded vm unique. 

Packer version: 1.3.2
Host platform: ESXi 6.5

```
{
    "variables": {
        "version": "{{ env `BUILDNUMBER` }}",
        "disksize": "32768",
        "satellite_password": "{{ env `SATELLITE_PASSWORD` }}",
        "artifactory_iso_url": "{{ env `ISO_URL` }}",
        "artifactory_gpg_key_url": "{{ env `GPG_KEY_URL` }}",
        "vsphere_server": "{{ env `PACKER_VSPHERE_SERVER` }}",
        "vsphere_username": "{{ env `PACKER_VSPHERE_USERNAME` }}",
        "vsphere_password": "{{ env `PACKER_VSPHERE_PASSWORD` }}",
        "vsphere_datastore": "{{ env `PACKER_VSPHERE_DATASTORE` }}",
        "vcenter_server": "{{ env `PACKER_VCENTER_SERVER` }}",
        "vcenter_username": "{{ env `PACKER_VCENTER_USERNAME` }}",
        "vcenter_password": "{{ env `PACKER_VCENTER_PASSWORD` }}",
        "vcenter_datacenter": "{{ env `PACKER_VCENTER_DATACENTER` }}",
        "uploadvcenter_server": "{{ env `PACKER_UPLOADVCENTER_SERVER` }}",
        "uploadvcenter_username": "{{ env `PACKER_UPLOADVCENTER_USERNAME` }}",
        "uploadvcenter_password": "{{ env `PACKER_UPLOADVCENTER_PASSWORD` }}",
        "uploadvcenter_datacenter": "{{ env `PACKER_UPLOADVCENTER_DATACENTER` }}"
    },
    "builders": [
        {
            "name": "rhel-6-current-base-vdi",
            "remote_type": "esx5",
            "keep_registered": true,
            "output_directory": "",
            "remote_host": "{{ user `vsphere_server` }}",
            "remote_datastore": "{{ user `vsphere_datastore` }}",
            "remote_username": "{{ user `vsphere_username` }}",
            "remote_password": "{{ user `vsphere_password` }}",
            "remote_cache_datastore": "{{ user `vsphere_datastore` }}",
            "vm_name": "packer-base-current-vdi-{{ user `version` }}",
            "type": "vmware-iso",
            "iso_url": "{{ user `artifactory_iso_url` }}",
            "iso_checksum": "d35fd1af20f6adef9b11b46c2534ae8b6e18de7754889e2b51808b436dff2804",
            "iso_checksum_type": "sha256",
            "vmx_data": {
                "numvcpus": 1,
                "cpuid.coresPerSocket": 1,
                "memsize": 4096,
                "ethernet0.addressType": "generated",
                "ethernet0.present": "TRUE",
                "ethernet0.startConnected": "TRUE",
                "ethernet0.uptCompatibility": "TRUE",
                "ethernet0.virtualDev": "vmxnet3",
                "virtualHW.version": "11"
            },
            "ssh_username": "packer",
            "ssh_password": "<password>",
            "ssh_timeout": "10m",
            "shutdown_command": "echo 'packer' | sudo -S /sbin/shutdown -P now",
            "boot_wait": "20s",
            "disk_size": "{{ user `disksize` }}",
            "headless": "true",
            "guest_os_type": "rhel6-64",
            "http_directory": "http",
            "vnc_port_min": 5900,
            "vnc_disable_password": true,
            "disk_type_id": "thin",
            "floppy_files": [
                "kickstart/rhel6-base-current-vdi-kickstart.cfg"
            ],
            "boot_command": [
                "<tab> text ks=hd:fd0:/rhel6-base-current-vdi-kickstart.cfg <enter><wait>"
            ]
        },
        {
            "name": "rhel-6-frozen-base-vdi",
            "keep_registered": true,
            "output_directory": "",
            "remote_type": "esx5",
            "remote_host": "{{ user `vsphere_server` }}",
            "remote_datastore": "{{ user `vsphere_datastore` }}",
            "remote_username": "{{ user `vsphere_username` }}",
            "remote_password": "{{ user `vsphere_password` }}",
            "remote_cache_datastore": "{{ user `vsphere_datastore` }}",
            "vm_name": "packer-base-frozen-vdi-{{ user `version` }}",
            "type": "vmware-iso",
            "iso_url": "{{ user `artifactory_iso_url` }}",
            "iso_checksum": "d35fd1af20f6adef9b11b46c2534ae8b6e18de7754889e2b51808b436dff2804",
            "iso_checksum_type": "sha256",
            "vmx_data": {
                "numvcpus": 1,
                "cpuid.coresPerSocket": 1,
                "memsize": 4096,
                "ethernet0.addressType": "generated",
                "ethernet0.present": "TRUE",
                "ethernet0.startConnected": "TRUE",
                "ethernet0.uptCompatibility": "TRUE",
                "ethernet0.virtualDev": "vmxnet3",
                "virtualHW.version": "11"
            },
            "ssh_username": "packer",
            "ssh_password": "<password>",
            "ssh_timeout": "10m",
            "shutdown_command": "echo 'packer' | sudo -S /sbin/shutdown -P now",
            "boot_wait": "20s",
            "disk_size": "{{ user `disksize` }}",
            "headless": "true",
            "guest_os_type": "rhel6-64",
            "http_directory": "http",
            "vnc_port_min": 5900,
            "vnc_disable_password": true,
            "disk_type_id": "thin",
            "floppy_files": [
                "kickstart/rhel6-base-frozen-vdi-kickstart.cfg"
            ],
            "boot_command": [
                "<tab> text ks=hd:fd0:/rhel6-base-frozen-vdi-kickstart.cfg <enter><wait>"
            ]
        }
    ],
    "provisioners": [
    "post-processors": [{
        "keep_input_artifact": true,
        "type": "vsphere-template",
        "host": "{{ user `vcenter_server` }}",
        "insecure": true,
        "username": "{{ user `vcenter_username` }}",
        "password": "{{ user `vcenter_password` }}",
        "datacenter": "{{ user `vcenter_datacenter` }}",
        "folder": "/Templates/Packer-base-vdi"
    },
    {
        "type": "vsphere",
        "host": "{{ user `uploadvcenter_server` }}",
        "username": "{{ user `uploadvcenter_username` }}",
        "password": "{{ user `uploadvcenter_password` }}",
        "datacenter": "{{ user `uploadvcenter_datacenter` }}",
        "datastore": "euvvdi_ds02_prd",
        "cluster": "EUV",
        "vm_name": "packer-base-vdi-{{ user `version` }}"
    }]
}
```
In the example above two VM's are created. the last post processor uploads these to a secondary vcenter server. However because of the vm_name both uploads end up having the same destination name:

```
2018/12/07 15:41:44 Flagging to keep original artifact from post-processor 'vsphere-template'
2018/12/07 15:41:44 packer: 2018/12/07 15:41:44 Starting ovftool with parameters: --acceptAllEulas --name=packer-base-vdi-0.0.98 --datastore=vm_ds02_prd --diskMode=thick output-rhel-6-frozen-base-vdi/packer-base-frozen-vdi-0.0.98/packer-base-frozen-vdi-0.0.98.ovf vi://<user>:<password>@vcenter/PRD/host/Cluster
2018/12/07 15:41:52 Flagging to keep original artifact from post-processor 'vsphere-template'
2018/12/07 15:41:52 packer: 2018/12/07 15:41:52 Starting ovftool with parameters: --acceptAllEulas --name=packer-base-vdi-0.0.98 --datastore=vm_ds02_prd --diskMode=thick output-rhel-6-current-base-vdi/packer-base-current-vdi-0.0.98/packer-base-current-vdi-0.0.98.ovf vi://<user>:<password>@vcenter/PRD/host/Cluster
  
```

**Comment by arizvisa** [comment] 2018-12-08 04:04
@nheetesonne, would the vsphere-iso builder plugin (https://github.com/jetbrains-infra/packer-builder-vsphere) resolve this? You can specify the `vm_name` and `folder` for each template properly during deployment and thus shouldn't need a separate post-processor to deploy to the target.

The ESX support in the VMware builders are unfortunately a hack and although it's totally capable of doing some things in your ESX instance, there's a lot of customization/tweaks you'll need to do to get them to work properly.

There's a PR/issue to merge proper support into Packer so it's native instead of a plugin, but it's currently on hold as the Packer's devers have a lot of other things to do and the Vsphere support is a \_large\_ merge.

**Comment by nheetesonne** [comment] 2018-12-08 09:14
No the building itself works perfectly using the packer vmware-iso builder. I want to upload the artifact to a different vcenter after build. This also works well if you have one builder or for the first builder that finishes and calls the post processor. The second run of the post-processor however fails. This is caused by the upload of the first run having the same vmname. 

If the vm_name from the builder would be passed to the post-processor and used as the vm_name this would be resolved as the name in the builder is already unique per builder.

**Comment by arizvisa** [comment] 2018-12-09 03:52
Looks like vsphere-clone will solve it, but as you will.. There isn't really an interface to pass information about artifacts between builders and post-processors which is why `vm_name` is specified in more than one place in the template. This makes it difficult to define the kind of relationship you describe without explicitly parsing the artifact as the vsphere post-processor is essentially just a dumb frontend to `ovftool`. But regardless, PRs are more than welcome!

**Comment by SwampDragons** [comment] 2018-12-10 18:43
Yeah, this may be worked around for now by invoking ovftool on your own in a shell-local post-processor after the manifest postprocessor has run.

**Comment by nheetesonne** [comment] 2018-12-10 18:48
That could indeed be a workaround, what I've done now is split the json file for the packer build up in two separate json files with one builder instead of one file with two builders.

**Comment by SwampDragons** [comment] 2018-12-10 23:06
So looking at this a bit more closely, I think it's expected behavior. vm_name is supposed to be unique, which is why the default vm_name includes the name of the build. The way we expect you to manage this is to have two post-processors, or one for each vm you intend to import. It's a bit of a clunky interface but I don't think we're going to change it until after we do the rewrite for HCL2.  Given that, I'm going to close this since we're unlikely to fix it any time soon.  Sorry.

**Closed by SwampDragons** 2018-12-10 23:06 UTC
Labels: enhancement, post-processor/vsphere
