### ISSUE TITLE
error creating vm: syntax error in pattern

### ISSUE THREAD

**Issue by gig3r** [hashicorp/packer#10765] opened 2021-03-15 14:30 UTC
Hello. 
I use packer for create VM on vmware. And i have an error with vSphere Client version 6.7.0.40000:
When i start packer on this version i see this:
```
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored after 1 second 167 milliseconds: error creating vm: syntax error in pattern

==> Wait completed after 1 second 167 milliseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: syntax error in pattern

==> Builds finished but no artifacts were created.
```

```
:~/packer-master$ ./packer version
Packer v1.7.0
```

my json syntax:
```
{
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server": "{{user `vsphere-server`}}",
      "username": "{{user `vsphere-user`}}",
      "password": "{{user `vsphere-password`}}",
      "insecure_connection": true,

      "ssh_username": "{{user `my_ssh_user`}}",
      "ssh_password": "{{user `my_ssh_psw`}}",

      "vm_name": "{{user `vm-name`}}",
      "notes": "Build via Packer",
      "guest_os_type": "{{user `vm-guest-os-type`}}",

      "CPUs": "{{user `vm-cpu-num`}}",
      "RAM": "{{user `vm-mem-size`}}",
      "RAM_reserve_all": false,

      "cluster": "{{user `vsphere-cluster`}}",
      "datacenter": "{{user `vsphere-datacenter`}}",
      "datastore": "{{user `vsphere-datastore`}}",

      "CPU_hot_plug": true,
      "RAM_hot_plug": true,
      "disk_controller_type": "pvscsi",
      "convert_to_template": false,

      "boot_order": "disk,cdrom,floppy",
      "boot_wait": "10s",
      "floppy_files": [
        "ks.cfg"
      ],
      "boot_command": [
        "<esc><wait>",
        "linux ks=hd:fd0:/ks.cfg<enter>"
      ],
      "iso_paths": [
        "{{user `iso_url`}}"
      ],

      "network_adapters": [
        {
          "network": "{{user `vsphere-network`}}",
          "network_card": "vmxnet3"
        }
      ],

      "storage": [
        {
          "disk_size": "{{user `vm-disk-size`}}",
          "disk_thin_provisioned": true
        }
      ]
    }
  ],

  "provisioners": [
    { "type": "ansible",
      "playbook_file": "./ansible/provision.yml"
    }
  ]
}
```
Can you help me?

**Comment by SwampDragons** [comment] 2021-03-15 23:10
This error is coming from our CreateVM call. This is where Packer tries to reach out to the vmware API to find the folder, resource pool, host, datastore, storage devices, and network. My guess is that one of those variables is bad. I can try to add more logging to the next release to make it easier to narrow down.

**Comment by sylviamoss** [comment] 2021-03-16 16:48
Hello @gig3r, could you provide more detailed logs running your build with the `PACKER_LOG=1` set, please?

**Comment by gig3r** [comment] 2021-03-17 08:05
Hello @sylviamoss 
I try use two iso_paths:
URL: https://mirror.yandex.ru/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
Storage: [gcu-storage2] iso/CentOS-8.3.2011-x86_64-dvd1.iso

[path_with_storage.txt](https://github.com/hashicorp/packer/files/6154650/path_with_storage.txt)
[path_with_url.txt](https://github.com/hashicorp/packer/files/6154651/path_with_url.txt)

**Comment by sylviamoss** [comment] 2021-03-17 10:27
Did you try using the URL in the `iso_paths` config? If that's so, it won't work. You should use the [`iso_url`](https://www.packer.io/docs/builders/vmware/vsphere-iso#iso_url). Could you try this one and let me know the result? 

Anyways, I would expect it to work with `[gcu-storage2] iso/CentOS-8.3.2011-x86_64-dvd1.iso` 🤔

**Comment by gig3r** [comment] 2021-03-17 14:01
I changed config and used iso_urls. 
And now installation is still progress, about 3 hours, but i think that the problem on our side:
`vsphere-iso: output will be in this color.

==> vsphere-iso: Retrieving ISO
==> vsphere-iso: Trying https://mirror.yandex.ru/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
==> vsphere-iso: Trying https://mirror.yandex.ru/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
    vsphere-iso: CentOS-7-x86_64-Minimal-2009.iso 973.00 MiB / 973.00 MiB [===========================] 100.00% 27m35s
==> vsphere-iso: https://mirror.yandex.ru/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a => /home/gig3r/Downloads/packer-master/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso
==> vsphere-iso: Uploading e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso to packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso
`

**Comment by gig3r** [comment] 2021-03-30 16:20
Sorry, but why you closed that issue? Cause I still have problem with storage from vsphere. Or need I waiting for new release ?

**Comment by sylviamoss** [comment] 2021-03-30 16:37
Can you set the path value without using variables and run again the build, please? 

```json
      "iso_paths": [
        "[gcu-storage2] iso/CentOS-8.3.2011-x86_64-dvd1.iso"
      ],
```

Like I said, the specific error message is a golang path validation error. That's makes sense for the url one but not for this one.

**Comment by gig3r** [comment] 2021-03-31 13:31
Hi @sylviamoss 
I did it without using variables
[error.txt](https://github.com/hashicorp/packer/files/6236894/error.txt)

`{
  "builders": [
    {
      "type": "vsphere-iso",
      "vcenter_server": "ip_vsphere",
      "username": "login",
      "password": "password",
      "insecure_connection": true,
      "ssh_username": "root",
      "ssh_password": "pass_for_root",
      "vm_name": "centos7",
      "notes": "Build via Packer",
      "guest_os_type": "rhel7-64",
      "CPUs": 4,
      "RAM": 8192,
      "RAM_reserve_all": false,
      "datacenter": "dcu-datacenter",	  
      "cluster": "gcu-cluster",
      "datastore": "gcu-storage2",
      "CPU_hot_plug": true,
      "RAM_hot_plug": true,
      "disk_controller_type": "pvscsi",
      "convert_to_template": false,
      "boot_order": "disk,cdrom,floppy",
      "boot_wait": "10s",
      "floppy_files": ["./ks.cfg"],
      "boot_command": "<tab> inst.linux inst.ks=hd:fd0:/ks.cfg <enter><wait>",
      "iso_paths": ["[gcu-storage2] ISO/CentOS-7-x86_64-Minimal-2009.iso"],
      "network_adapters": [
	  {
          "network": "[192.168.2.64/26]vm5-pg",
          "network_card": "vmxnet3"
        }
		],
      "storage": [
	  {
          "disk_size": 51200,
          "disk_thin_provisioned": true
        }
		]
    }
  ],
  "provisioners": [
  { 
	  "type": "ansible-local",
      "playbook_file": "./ansible/provision.yml"
    }
	]
}`

**Comment by sylviamoss** [comment] 2021-03-31 14:42
So, the problem is with your `network` path.  The syntax there is not correct and I believe is related to the `[...]`. I was able to reproduce it using their simulator to write a test. The error is coming from the govmomi path validation.

**Comment by gig3r** [comment] 2021-04-01 10:58
Hi. You are right. I renamed network name and deleted these symbols - [ ]. And after that packer created VM. 
But, how i can use [ ], because we have a lot of network names with these symbols.

**Comment by sylviamoss** [comment] 2021-04-01 12:21
In this case, there's not much we can do. Like I said, this a validation that happens in the official VMware sdk we use. 
FIY the path validation happens because it contains the `/` in the middle. When it tries to parse the IP the result is `[192.168.2.64` and this is not valid. 

This a great thing to ask the community. I'll leave here our [discuss forum](https://discuss.hashicorp.com/c/packer/23) and close the issue. 
Thanks for working throughout this and providing more information.

**Closed by sylviamoss** 2021-04-01 12:21 UTC
Labels: builder/vsphere, track-internal
