### ISSUE TITLE
Packer hangs while running chef-solo provisioners

### ISSUE THREAD

**Issue by tapasmishra** [hashicorp/packer#4639] opened 2017-03-08 07:04 UTC
When I am trying to create a Docker image using packer it hangs for indefinite time after saying `docker: Creating directory: /tmp/packer-chef-solo`. 

- Packer Version 
`Packer v0.12.3`
- Host Info
```
$ uname -r
2.6.32-642.11.1.el6.x86_64
```
- Debug log output from `PACKER_LOG=1 packer build template.json`.
```
==> docker: Provisioning with chef-solo
    docker: Creating directory: /tmp/packer-chef-solo
```

**Comment by mwhooker** [comment] 2017-03-08 19:18
please post a json config that reproduces this and the full debug log

**Comment by cheeseplus** [comment] 2017-03-30 01:38
I am seeing this as well with the chef-solo provisioner. I've included the entire config but it's effectively just a hacked up version of chef/bento's ubuntu-14.04 with chef-solo set as provisioner instead. I've tried it with a custom execute_command as well but the results are the same.

packer: 0.12.3

```
{
  "builders": [
    {
      "boot_command": [
        "<esc><wait>",
        "<esc><wait>",
        "<enter><wait>",
        "/install/vmlinuz<wait>",
        " auto<wait>",
        " console-setup/ask_detect=false<wait>",
        " console-setup/layoutcode=us<wait>",
        " console-setup/modelcode=pc105<wait>",
        " debconf/frontend=noninteractive<wait>",
        " debian-installer=en_US.UTF-8<wait>",
        " fb=false<wait>",
        " initrd=/install/initrd.gz<wait>",
        " kbd-chooser/method=us<wait>",
        " keyboard-configuration/layout=USA<wait>",
        " keyboard-configuration/variant=USA<wait>",
        " locale=en_US.UTF-8<wait>",
        " netcfg/get_domain=vm<wait>",
        " netcfg/get_hostname=vagrant<wait>",
        " noapic<wait>",
        " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{user `preseed_path`}}<wait>",
        " -- <wait>",
        "<enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_size": "{{user `disk_size`}}",
      "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
      "guest_os_type": "Ubuntu_64",
      "hard_drive_interface": "sata",
      "headless": "{{ user `headless` }}",
      "http_directory": "http",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "packer-{{user `template`}}-virtualbox",
      "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_pty" : "true",
      "ssh_username": "vagrant",
      "ssh_wait_timeout": "10000s",
      "type": "virtualbox-iso",
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "{{ user `memory` }}"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "{{ user `cpus` }}"
        ]
      ],
      "virtualbox_version_file": ".vbox_version",
      "vm_name": "{{ user `template` }}"
    },
    {
      "boot_command": [
        "<esc><wait>",
        "<esc><wait>",
        "<enter><wait>",
        "/install/vmlinuz<wait>",
        " auto<wait>",
        " console-setup/ask_detect=false<wait>",
        " console-setup/layoutcode=us<wait>",
        " console-setup/modelcode=pc105<wait>",
        " debconf/frontend=noninteractive<wait>",
        " debian-installer=en_US.UTF-8<wait>",
        " fb=false<wait>",
        " initrd=/install/initrd.gz<wait>",
        " kbd-chooser/method=us<wait>",
        " keyboard-configuration/layout=USA<wait>",
        " keyboard-configuration/variant=USA<wait>",
        " locale=en_US.UTF-8<wait>",
        " netcfg/get_domain=vm<wait>",
        " netcfg/get_hostname=vagrant<wait>",
        " noapic<wait>",
        " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{user `preseed_path`}}<wait>",
        " -- <wait>",
        "<enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_size": "{{user `disk_size`}}",
      "guest_os_type": "ubuntu-64",
      "headless": "{{ user `headless` }}",
      "http_directory": "http",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "packer-{{user `template`}}-vmware",
      "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "ssh_wait_timeout": "10000s",
      "tools_upload_flavor": "linux",
      "type": "vmware-iso",
      "vm_name": "{{ user `template` }}",
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "{{ user `memory` }}",
        "numvcpus": "{{ user `cpus` }}"
      }
    },
    {
      "boot_command": [
        "<esc><wait>",
        "<esc><wait>",
        "<enter><wait>",
        "/install/vmlinuz<wait>",
        " auto<wait>",
        " console-setup/ask_detect=false<wait>",
        " console-setup/layoutcode=us<wait>",
        " console-setup/modelcode=pc105<wait>",
        " debconf/frontend=noninteractive<wait>",
        " debian-installer=en_US.UTF-8<wait>",
        " fb=false<wait>",
        " initrd=/install/initrd.gz<wait>",
        " kbd-chooser/method=us<wait>",
        " keyboard-configuration/layout=USA<wait>",
        " keyboard-configuration/variant=USA<wait>",
        " locale=en_US.UTF-8<wait>",
        " netcfg/get_domain=vm<wait>",
        " netcfg/get_hostname=vagrant<wait>",
        " noapic<wait>",
        " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{user `preseed_path`}}<wait>",
        " -- <wait>",
        "<enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_size": "{{user `disk_size`}}",
      "guest_os_type": "ubuntu",
      "http_directory": "http",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "packer-{{user `template`}}-parallels",
      "parallels_tools_flavor": "lin",
      "prlctl": [
        [
          "set",
          "{{.Name}}",
          "--memsize",
          "{{ user `memory` }}"
        ],
        [
          "set",
          "{{.Name}}",
          "--cpus",
          "{{ user `cpus` }}"
        ]
      ],
      "prlctl_version_file": ".prlctl_version",
      "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "ssh_wait_timeout": "10000s",
      "type": "parallels-iso",
      "vm_name": "{{ user `template` }}"
    },
    {
      "boot_command": [
        "<esc><wait>",
        "<esc><wait>",
        "<enter><wait>",
        "/install/vmlinuz<wait>",
        " auto<wait>",
        " console-setup/ask_detect=false<wait>",
        " console-setup/layoutcode=us<wait>",
        " console-setup/modelcode=pc105<wait>",
        " debconf/frontend=noninteractive<wait>",
        " debian-installer=en_US.UTF-8<wait>",
        " fb=false<wait>",
        " initrd=/install/initrd.gz<wait>",
        " kbd-chooser/method=us<wait>",
        " keyboard-configuration/layout=USA<wait>",
        " keyboard-configuration/variant=USA<wait>",
        " locale=en_US.UTF-8<wait>",
        " netcfg/get_domain=vm<wait>",
        " netcfg/get_hostname=vagrant<wait>",
        " noapic<wait>",
        " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{user `preseed_path`}}<wait>",
        " -- <wait>",
        "<enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_size": "{{user `disk_size`}}",
      "headless": "{{ user `headless` }}",
      "http_directory": "http",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "packer-{{user `template`}}-qemu",
      "shutdown_command": "echo 'vagrant'|sudo -S shutdown -P now",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "ssh_wait_timeout": "10000s",
      "type": "qemu",
      "vm_name": "{{ user `template` }}"
    }
  ],
  "post-processors": [
    {
      "output": "builds/{{user `box_basename`}}.{{.Provider}}.box",
      "type": "vagrant"
    }
  ],
  "provisioners": [
    {
      "type": "chef-solo",
      "cookbook_paths": ["../cookbooks"],
      "install_command": "echo 'vagrant' | {{if .Sudo}}sudo -S{{end}} bash -c 'curl -L https://www.opscode.com/chef/install.sh| bash'",
      "run_list": ["recipe[openldap]"]
    }
],
  "variables": {
    "box_basename": "ubuntu-14.04",
    "build_timestamp": "{{isotime \"20060102150405\"}}",
    "cpus": "1",
    "disk_size": "40960",
    "git_revision": "__unknown_git_revision__",
    "headless": "",
    "http_proxy": "{{env `http_proxy`}}",
    "https_proxy": "{{env `https_proxy`}}",
    "iso_checksum": "946a6077af6f5f95a51f82fdc44051c7aa19f9cfc5f737954845a6050543d7c2",
    "iso_checksum_type": "sha256",
    "iso_name": "ubuntu-14.04.1-server-amd64.iso",
    "memory": "512",
    "metadata": "floppy/dummy_metadata.json",
    "mirror": "http://old-releases.ubuntu.com/releases",
    "mirror_directory": "14.04.1",
    "name": "ubuntu-14.04",
    "no_proxy": "{{env `no_proxy`}}",
    "preseed_path": "ubuntu-14.04/preseed.cfg",
    "template": "ubuntu-14.04-amd64",
    "version": "2.1.TIMESTAMP"
  }
}
```

**Comment by mwhooker** [comment] 2017-03-30 07:50
hmm, I was able to reproduce this with the bento box ubuntu-14.04:

```
2017/03/30 00:48:48 ui:     virtualbox-iso: + reboot
    virtualbox-iso: + reboot
2017/03/30 00:48:48 ui:     virtualbox-iso: + sleep 60
    virtualbox-iso: + sleep 60
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 Remote command exited without exit status or exit signal.
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/03/30 00:48:49 [INFO] 78395 bytes written for 'stdout'
2017/03/30 00:48:49 [INFO] 16234 bytes written for 'stderr'
2017/03/30 00:48:49 [INFO] RPC client: Communicator ended with: 2300218
2017/03/30 00:48:49 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 [INFO] 78395 bytes written for 'stdout'
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 [INFO] 16234 bytes written for 'stderr'
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 [INFO] RPC client: Communicator ended with: 2300218
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 opening new ssh session
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 ssh session open error: 'EOF', attempting reconnect
2017/03/30 00:48:49 packer: 2017/03/30 00:48:49 Retryable error: Error removing temporary script at /tmp/script_3261.sh: close tcp 127.0.0.1:56042->127.0.0.1:3899: use of closed network connection
2017/03/30 00:48:51 packer: 2017/03/30 00:48:51 opening new ssh session
2017/03/30 00:48:51 packer: 2017/03/30 00:48:51 ssh session open error: 'EOF', attempting reconnect
2017/03/30 00:48:51 packer: 2017/03/30 00:48:51 Retryable error: Error removing temporary script at /tmp/script_3261.sh: close tcp 127.0.0.1:56042->127.0.0.1:3899: use of closed network connection
```

**Comment by mwhooker** [comment] 2017-03-30 08:24
works with 0.12.2

```
2017/03/30 01:15:50 ui:     virtualbox-iso: + reboot
    virtualbox-iso: + reboot
2017/03/30 01:15:50 ui:     virtualbox-iso: + sleep 60
    virtualbox-iso: + sleep 60
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 Remote command exited without exit status or exit signal.
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/03/30 01:15:51 [INFO] 78395 bytes written for 'stdout'
2017/03/30 01:15:51 [INFO] 16234 bytes written for 'stderr'
2017/03/30 01:15:51 [INFO] RPC client: Communicator ended with: 2300218
2017/03/30 01:15:51 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 [INFO] RPC client: Communicator ended with: 2300218
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 [INFO] 16234 bytes written for 'stderr'
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 [INFO] 78395 bytes written for 'stdout'
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 opening new ssh session
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 ssh session open error: 'EOF', attempting reconnect
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 reconnecting to TCP connection for SSH
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 handshaking with SSH
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 handshake error: ssh: handshake failed: EOF
2017/03/30 01:15:51 packer: 2017/03/30 01:15:51 Retryable error: Error removing temporary script at /tmp/script_8029.sh: ssh: handshake failed: EOF
2017/03/30 01:15:53 packer: 2017/03/30 01:15:53 opening new ssh session
2017/03/30 01:15:53 packer: 2017/03/30 01:15:53 ssh session open error: 'client not available', attempting reconnect
2017/03/30 01:15:53 packer: 2017/03/30 01:15:53 reconnecting to TCP connection for SSH
2017/03/30 01:15:53 packer: 2017/03/30 01:15:53 handshaking with SSH
2017/03/30 01:16:00 packer: 2017/03/30 01:16:00 handshake complete!
2017/03/30 01:16:00 packer: 2017/03/30 01:16:00 opening new ssh session
2017/03/30 01:16:00 packer: 2017/03/30 01:16:00 [INFO] agent forwarding enabled
2017/03/30 01:16:00 packer: 2017/03/30 01:16:00 starting remote command: rm -f /tmp/script_8029.sh
2017/03/30 01:16:00 packer: 2017/03/30 01:16:00 [INFO] RPC endpoint: Communicator ended with: 0
2017/03/30 01:16:00 [INFO] RPC client: Communicator ended with: 0
2017/03/30 01:16:00 [INFO] RPC endpoint: Communicator ended with: 0
2017/03/30 01:16:00 packer: 2017/03/30 01:16:00 [INFO] RPC client: Communicator ended with: 0
2017/03/30 01:16:00 ui: ==> virtualbox-iso: Provisioning with shell script: scripts/common/sshd.sh
```


I assume this is because of https://github.com/mitchellh/packer/pull/4197 which turns a silent failure into a fatal one. I'm not 100% sure this is logic error in packer. It may just be bad default settings. continuing to investigate

**Comment by mwhooker** [comment] 2017-03-30 09:10
deleted my two comments because it was an issue not related to this

**Comment by cheeseplus** [comment] 2017-03-30 15:01
I figured out what was happening in my issue, the hang appears to be related to sudo which wants a password. Altering the provisioner block to prevent the inbuilt sudo and use my own sudo commands removed the hang. I presume because it was waiting for a password.

```
  "provisioners": [
    {
      "type": "chef-solo",
      "prevent_sudo": "true",
      "cookbook_paths": ["../cookbooks"],
      "install_command": "echo 'vagrant' | sudo -S bash -c 'curl -L https://www.opscode.com/chef/install.sh| bash'",
      "execute_command": "echo 'vagrant' | sudo -S chef-solo --no-color -c {{.ConfigPath}} -j {{.JsonPath}}",
      "run_list": ["recipe[ntp]"]
    }
  ],
```

**Comment by mwhooker** [comment] 2017-03-30 19:21
@cheeseplus that makes a lot of sense! Thanks for following up.

@tapasmishra Does the same change work for you?

**Comment by cheeseplus** [comment] 2017-03-31 13:32
@mwhooker happy to do so as this gives folks something to search for and me something to reference for others. I also don't think there is an easy/good way to bubble up an informational message in that case either so I'm thinking of a better way to document sudo needs/interactions for the provisioner

**Comment by SwampDragons** [comment] 2017-09-28 20:12
closing because original poster hasn't commented since opening the ticket, and other user found resolution. If you are still experiencing this, please reopen with steps to reproduce.

**Closed by SwampDragons** 2017-09-28 20:12 UTC
Labels: communicator/ssh, provisioner/chef, provisioner/shell
