### ISSUE TITLE
URL not supported anymore in virtualbox-ovf source_path

### ISSUE THREAD

**Issue by beenje** [hashicorp/packer#7909] opened 2019-07-25 09:07 UTC
- packer version: Packer v1.4.2
- Host platform: OSX
  
Using the following with packer 1.2.4 worked fine:
```
"type": "virtualbox-ovf",
"source_path": "https://artifactory.xxxx.xx/artifactory/swi-pkg/virtualbox/1810.01/esss-centos-7.ova",
```
Full template: https://gist.github.com/beenje/e181ae900aad60d6b7a139d2a39feb75

It doesn't work anymore with packer 1.4.2:
```
packer validate test.json
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox-ovf'. 1 error(s) occurred:

* Source file 'https://artifactory.xxxx.xx/artifactory/swi-pkg/virtualbox/1810.01/esss-centos-7.ova' needs to exist at time of config validation! stat https://artifactory.xxxx.xx/artifactory/swi-pkg/virtualbox/1810.01/esss-centos-7.ova: no such file or directory
```

The documentation mentions "source_path (string) - The path to an OVF or OVA file that acts as the source of this build. This currently must be a local file."

So removing the support for URL in source_path seems to be intentional. Why was that removed? Can it be re-enabled?

**Comment by SwampDragons** [comment] 2019-07-25 16:34
Thanks for reaching out! I think this is a duplicate of #7609 so I'm going to close this and we can track the issue there.

Sorry for the regression. Let me know if you have any more issues.

**Closed by SwampDragons** 2019-07-25 16:34 UTC
