### ISSUE TITLE
Problem uploading iso/floppy to ESX host

### ISSUE THREAD

**Issue by pmanno** [hashicorp/packer#9616] opened 2020-07-20 21:48 UTC
#### Overview of the Issue

Whenever I try to build more than one VM at at time, even on two different build servers, I get an error:
vmware-iso: Error uploading file: Process exited with status 1

#### Reproduction Steps

Attempt to build more than 1 VM at a time.

### Packer version

1.6.0

### Simplified Packer Buildfile

[gist](https://gist.github.com/pmanno/37529faf0bd3006a7c8c285bdc76c1d7)

### Operating system and Environment details

Build Server packer is run on: Ubuntu 18.04.4 LTS

### Log Fragments and crash.log files

[gist](https://gist.github.com/pmanno/e7c2905ceb1d011be8b853913c39f2a8)

**Comment by SwampDragons** [comment] 2020-08-17 15:46
Hi, thanks for reaching out. I'm trying to reproduce this but I'm not able to. Your example packer template only defines one builder. Do you run that template twice from the same machine? Or does your real template have two builders in it? Are they uploading the same floppy files/iso files, or are the files being uploaded by the parallel builds different?

**Comment by SwampDragons** [comment] 2020-08-17 15:48
We did resolve a checksum error in uploading to esx here: https://github.com/hashicorp/packer/pull/9584.  That patch released with v1.6.1. Can you try that version and let me know if this is still a problem?

**Comment by pmanno** [comment] 2020-09-08 19:05
Tested 1.6.1. Still getting that same error.

**Comment by pmanno** [comment] 2020-09-08 19:07
> Hi, thanks for reaching out. I'm trying to reproduce this but I'm not able to. Your example packer template only defines one builder. Do you run that template twice from the same machine? Or does your real template have two builders in it? Are they uploading the same floppy files/iso files, or are the files being uploaded by the parallel builds different?

Hello,
I have a jenkins server with two build servers that have packer installed.  I have a throttle rule setup in Jenkins to only run one packer build per worker node but allow two total concurrent builds (one from each node).  When I queue one build, then queue another, the first build succeeds, but the second one (started just a few milliseconds after the first) fails with this error.

**Comment by pmanno** [comment] 2020-09-14 17:16
So this is only an issue when setting the datastore (or probably packer_cache) dir to be a location on shared storage.  If I use discrete datastores on each host, I can build in parallel without error.  So I'm guessing the first process starts uploading to the cache, and the second one tries to do the same but the file is locked by the first process.

**Comment by SwampDragons** [comment] 2020-09-23 17:57
I just took a closer look at this and I believe you're right -- the iso upload is failing because the independent builders are trying to upload at the same time. I could look at implementing a file lock, but that'll probably cause issues in a situation where the builder crashes while trying to upload. The best solution is probably to just run a single builder once to make sure the iso has been uploaded to the cache (making sure that https://www.packer.io/docs/builders/vmware-iso#cleanup_remote_cache is false) and then next time you run your milliseconds-apart-builders the iso is already there so the builders won't race each other trying to upload it.

**Comment by pmanno** [comment] 2020-09-23 20:51
I'm not sure even that would work because I think they would run into an error when multiple VMs try to mount the same iso to build from?

**Comment by SwampDragons** [comment] 2020-09-23 23:49
If that's the case you're going to have to just run the builds sequentially or from different datastores; is there a reason you're running identical builds at the same time? There may be a better pipeline for you.

**Closed** 2021-04-19 12:20 UTC
Labels: bug, builder/vmware-esxi, remote-plugin/vmware, track-internal
