### ISSUE TITLE
packer build CLI option -only does not work as documented

### ISSUE THREAD

**Issue by askb** [hashicorp/packer#10495] opened 2021-01-16 05:12 UTC
As per the packer documentation: [2.]

"
-only=foo,bar,baz - Only run the builds with the given comma-separated names. Build names by default are their type, unless a specific name attribute is specified within the configuration. -only does not apply to post-processors.

"
The `packer build -only=` does not work as expected for version: 1.4.2. Our packer templates build images for the OpenStack cloud type/provider. However, using the option `-only=openstack` does not trigger the builder `type: openstack` or `name: openstack`.  

example:
```
$ OS_CLOUD=odlci packer.io build -debug -only=openstack -var-file=common-packer/vars/cloud-env.json -var-file=common-packer/vars/centos-7.json templates/builder.json 
Debug mode enabled. Builds will not be parallelized.

==> Builds finished but no artifacts were created.

```
From the output above build exited without returning any info

[1.] https://github.com/lfit/releng-common-packer/blob/master/templates/builder.json#L19-L23
[2.] https://www.packer.io/docs/commands/build

**Comment by azr** [comment] 2021-01-18 14:32
Hey @askb ! Thanks for opening, are you able to upgrade to a more [recent version of Packer](https://www.packer.io/downloads) ( currently 1.6.6 ) ? And if so does the issue still happen ?

**Comment by askb** [comment] 2021-01-18 22:59
> Hey @askb ! Thanks for opening, are you able to upgrade to a more [recent version of Packer](https://www.packer.io/downloads) ( currently 1.6.6 ) ? And if so does the issue still happen?

@azr This is reproducible with packer version 1.6.6. 

```

08:55:09 Packer binary not available, installing Packer version 1.6.6.
08:55:09 /w/workspace/builder-packer-merge-centos-7-devstack /w/workspace/builder-packer-merge-centos-7-devstack
08:55:10 2021-01-18 22:55:10 URL:https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip [29081121/29081121] -> "packer_1.6.6_linux_amd64.zip" [1]
08:55:10 Archive:  packer_1.6.6_linux_amd64.zip
08:55:10   inflating: /w/workspace/builder-packer-merge-centos-7-devstack/bin/packer  
08:55:11 /w/workspace/builder-packer-merge-centos-7-devstack
08:55:11 ---> packer-build.sh
08:55:13 + [[ -n https://git.opendaylight.org/gerrit ]]
08:55:13 + [[ -n '' ]]
08:55:13 + [[ git://devvexx.opendaylight.org/mirror/releng/builder =~ https://github.com ]]
08:55:13 + set +x
08:55:14 
08:55:14 ==> Wait completed after 22 microseconds

```

**Comment by SwampDragons** [comment] 2021-01-22 00:35
Hi, thanks for reaching out. 

Looking at your linked config, it appears that you've set "name" and "type" using user variables.   The "name" can be a variable, but the "type" needs to be hard-coded for our parser to be able to decode the rest of the config properly. That could be part of your problem, though I would expect Packer to error, rather than run without actually printing anything. Your output looks an awful lot like you used a build name that doesn't actually exist in the template at all. Check your spelling and check that the variable you're using is actually set in the environment.

Here's an example of a template using null builders that you can play with to figure out what is allowed in the only/except paradigm:

```
{
  "variables": {
    "name1": "firstbuilder",
    "name2": "secondbuilder"
  },
  "builders": [
    {
      "type": "null",
      "communicator": "none",
      "name": "{{user `name1`}}"
    },
    {
      "type": "null",
      "communicator": "none",
      "name": "{{user `name2`}}"
    }
  ],
  "provisioners": [
    {
      "type": "shell-local",
      "inline": ["echo printing name of running builder: {{build_name}}"]
    }
  ]
}
```

To run them both, either leave out the "only" flag or to test that the only flag is working inclusively we can call 

```sh
PACKER_LOG=0 packer build -only=firstbuilder,secondbuilder onlyexcept.json
```

and we'll see output like 

```
firstbuilder: output will be in this color.
secondbuilder: output will be in this color.

==> secondbuilder: Running local shell script: /var/folders/8t/0yb5q0_x6mb2jldqq_vjn3lr0000gn/T/packer-shell400504134
==> firstbuilder: Running local shell script: /var/folders/8t/0yb5q0_x6mb2jldqq_vjn3lr0000gn/T/packer-shell283664542
    secondbuilder: printing name of running builder: secondbuilder
Build 'secondbuilder' finished after 67 milliseconds 704 microseconds.
    firstbuilder: printing name of running builder: firstbuilder
Build 'firstbuilder' finished after 102 milliseconds 801 microseconds.

==> Wait completed after 102 milliseconds 847 microseconds

==> Builds finished. The artifacts of successful builds are:
--> secondbuilder: Did not export anything. This is the null builder
--> firstbuilder: Did not export anything. This is the null builder
```

But if I only run one: 

```sh
PACKER_LOG=0 packer build -only=firstbuilder onlyexcept.json
firstbuilder: output will be in this color.
```

we can see in the output that sure enough, only "firstbuilder" ran.

```
==> firstbuilder: Running local shell script: /var/folders/8t/0yb5q0_x6mb2jldqq_vjn3lr0000gn/T/packer-shell738670254
    firstbuilder: printing name of running builder: firstbuilder
Build 'firstbuilder' finished after 68 milliseconds 511 microseconds.

==> Wait completed after 68 milliseconds 557 microseconds

==> Builds finished. The artifacts of successful builds are:
--> firstbuilder: Did not export anything. This is the null builder
```

If you want to reproduce the behavior you're seeing in this template, you can call build with a nonexistant name in the `only` arg:

```sh
PACKER_LOG=0 packer build -only=wrongname onlyexcept.json
```

which produces

```
==> Wait completed after 2 microseconds

==> Builds finished but no artifacts were created.
```

Please note that if you're using a "name" field in your builder definition, then supplying the "type" to the only or except flags will produce the same result as "wrongname" above. The only/except flags operate on the "name" of the build, which only defaults to the "type" if the "name" is not set.

I'm pretty convinced this is a usage issue not an underlying flaw with the only/except logic, so I'm going to close this. But please let me know if this is enough to un-stick you, and if it isn't we can try to update docs to make things clearer.

**Closed** 2021-01-22 00:37 UTC
Labels: bug, core, track-internal

**Comment by askb** [comment] 2021-01-23 01:20
@SwampDragons Thanks for the prompt reply. 

Why not allow the builder type/name to be set either by an environment variable or through the `-only` CLI flag. This would ease the deployments and also help to avoid coping entire templates just to run on a diff cloud provider. It would be easier to generalizing templates and use these common templates across clouds (openstack, aws etc) if this was allowed.

**Comment by SwampDragons** [comment] 2021-01-23 06:32
like I said, the _name_ can be set via a variable.  The _type_ cannot be.  This is because each builder is matched to the underlying API for its respective cloud. Therefore, each builder has very different configuration options. They simply aren't interchangeable except in the simplest of cases. To allow users to swap out "type" as though it were any other variable would imply that _any_ builder would work with the provided customizations, which just isn't true.
