### ISSUE TITLE
`region_kms_key_ids` doesn't overwrite the `kms_key_id` correctly

### ISSUE THREAD

**Issue by goloobev** [hashicorp/packer#9427] opened 2020-06-16 09:24 UTC
#### Overview of the Issue

According to the documentation `region_kms_key_ids` overwrite the `kms_key_id`
https://www.packer.io/docs/builders/amazon-ebssurrogate.html#region_kms_key_ids
"This option supersedes the kms_key_id option -- if you set both, and they are different, Packer will respect the value in region_kms_key_ids for your build region and silently disregard the value provided in kms_key_id"

But when I run packer with `region_kms_key_ids` and without `kms_key_id` it fails with error
`Cannot share AMI encrypted with default KMS key`

#### Reproduction Steps
Run packer with defined `region_kms_key_ids` and KMS key for the main region in it but without `kms_key_id` option

### Packer version

1.5.5

### Simplified Packer Buildfile
```
source "amazon-ebs" "example" {
    ...
    region = "us-east-1"
    ami_regions = ["us-east-1","eu-central-1"]
    region_kms_key_ids{
      us-east-1 = "alias/us-east-1-kms"
      eu-central-1 = "alias/eu-central-1-kms"
    }
```
With this code, it will fail
If add 
`kms_key_id = "alias/us-east-1-kms" `
it will work fine

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files
```
2020/06/16 09:18:22 packer-builder-amazon-ebs plugin: Waiting for connection...
2020/06/16 09:18:22 packer-builder-amazon-ebs plugin: Serving a plugin connection...
2020/06/16 09:18:22 packer-builder-amazon-ebs plugin: Cannot copy AMI to AWS session region 'us-east-1', deleting it from `ami_regions`.

Error: 1 error(s) occurred:

* Cannot share AMI encrypted with default KMS key
```

**Comment by SwampDragons** [comment] 2020-06-16 18:16
Hi, thanks for opening. 

I can't reproduce this; when I run, the value from the region_kms_key_ids map overrides the default value. Are you sure that `alias/us-east-1-kms` isn't the default key?

**Comment by SwampDragons** [comment] 2020-08-13 18:59
Closing since I never heard back. I think this was probably a config error. We can reopen if it turns out that isn't the case.

**Closed by SwampDragons** 2020-08-13 18:59 UTC
Labels: bug, builder/amazon, hcl2, waiting-reply
