### ISSUE TITLE
Proposal: pre-processors

### ISSUE THREAD

**Issue by dyferx** [hashicorp/packer#10594] opened 2021-02-09 11:05 UTC
I'm using packer for azure VM image gallery templates creation. 
There is a problem because we cannot create new image if "image definition" in gallery doesn't exist.

I have tried to use shell-local  and az cli script to check if image definition is already defined and if not to create it but this doesnt work -> packer is checking if image definition exist in initial phase.

Adding pre-processor should resolve this issue.

**Comment by SwampDragons** [comment] 2021-02-09 18:19
This has been proposed in the past; probably the most relevant link is the conversation on this PR:

https://github.com/hashicorp/packer/pull/7184

The tl;dr is that we've talked about this before and it feels like the wrong solution to the use cases it's been proposed for. For example, instead of using shell-local and the az-cli, you can write your shell check as a wrapping script that runs before Packer is launched at all. This check doesn't need the instance to be launched in order to run. 

If it must be part of Packer, and I agree that it would be a more seamless user experience if we did that, it seems to me that your use case would better be solved with some kind of specific option _within the Azure builder_ that creates the image definition if it doesn't exist, as part of normal Azure builder checks -- rather than an entire new framework for pre-processors.

**Comment by SwampDragons** [comment] 2021-02-09 18:21
It feels like this is probably a duplicate of https://github.com/hashicorp/packer/issues/8803 -- can we close this and link it there, to track in the same place?

**Closed** 2021-02-10 16:52 UTC
Labels: builder/azure, enhancement
