### ISSUE TITLE
Allow to stop a build after a download

### ISSUE THREAD

**Issue by azr** [hashicorp/packer#7132] opened 2018-12-19 14:47 UTC
Note: I am creating this issue on behalf of @ladar as I couldn't find anything mentioning it; to give pointers and for us to be able to reference it. It is **not** a priority right now mainly because it is possible emulate this behaviour with a script or a buildfile that only downloads.

This could be done by adding a specific packer command ex: `packer cache` like @SwampDragons said in https://github.com/hashicorp/packer/issues/5613#issuecomment-348010142 or may be by adding an option: `packer build -cache buildfile`.

**Comment by azr** [comment] 2018-12-19 14:50
I like the idea of `packer build -cache buildfile` because then we would just have to pass a boolean to StepDownload:

https://github.com/hashicorp/packer/blob/e666b60d166db7b4c6185d8b9a5417c6622d68c7/builder/vmware/iso/builder.go#L75-L83

Say: `StopAfterCompletion: true` which can halt packer execution after `Run` executed successfully.

**Comment by ladar** [comment] 2018-12-19 18:14
Me like.

**Comment by SwampDragons** [comment] 2019-07-23 22:30
Was doing some cleanup -- turns out this is actually a duplicate of #6472, so I'm going to close this and let us track it there.

**Closed by SwampDragons** 2019-07-23 22:30 UTC
Labels: core, enhancement
