### ISSUE TITLE
Add support to select most recent source image when name is provided

### ISSUE THREAD

**Issue by haxorof** [hashicorp/packer#6464] opened 2018-07-07 10:08 UTC
Hi,

I have some automated build pipeline where I currently use the `openstack` builder of Packer. In this pipeline I use the `source_image_name` parameter of the `openstack` builder which fails for me. The reason is that this image name is not unique because in my CI/CD setup this image is also built automatically:
```
...
==> openstack: Launching server...
==> openstack: Error launching source server: Found 2 images matching ubuntu-artful
==> openstack: Terminating the source server:  ...
...
```

The feature I am looking for is very similar to what in a way already exists in Terraform where you can fetch the most recent image from the image service by doing some simple filtering. In the `openstack` builder it would be possible to do something similar. Then parameter `most_recent_source_image` or similar could be introduced. For example if parameter `source_image_name` is defined and the image service returns more than one image then select the most recent and provide that to Gophercloud as `ImageRef`, provided that `source_image` is not set.
https://github.com/hashicorp/packer/blob/v1.2.4/builder/openstack/step_run_source_server.go#L61-L62

References:
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/data_source_openstack_images_image_v2.go#L234

**Comment by rickard-von-essen** [comment] 2018-07-07 10:38
Similar to `amazon-ebs` `source_ami_filter`.

**Comment by rickard-von-essen** [comment] 2018-07-07 10:42
[API list images](https://developer.openstack.org/api-ref/image/v2/index.html#list-images) we should support the available filters and `most_recent`.

**Comment by haxorof** [comment] 2018-07-07 20:41
Sounds good! So if I understand you correctly you think something like this shall be possible in openstack builder:
```json
...
  "source_image_filter": {
    "filters": {
	"tag": "mytag"
    },
    "owner": "d1a588cf4b0743344508dc145649372d1",
    "most_recent": true
  }
...
```

**Comment by rickard-von-essen** [comment] 2018-07-07 20:42
Yes something like that.

**Comment by tcarrio** [comment] 2018-07-09 23:58
I'm only looking into this code today, so please correct me where I'm wrong.

It seems that [gophercloud](http://gophercloud.io/) is Packer's main method of interacting with the OpenStack API. The issue is encountered when Packer first retrieves the list of images. It will, rightly so, return an error here if the image list contains more than 1 (we can only use one image). 

The OpenStack API allows for extra parameters to be included that modify the resulting set from the query. The documentation for that is [here](https://developer.openstack.org/api-ref/compute/#servers-servers). Using a combination of the `limit=1`, `sort_key=created_at`, and `sort_dir=desc`, the query will return only the most recent image (`created_at` was chosen to follow suit with the Amazon provider).

The configuration file should include a `source_image_filter` attribute that allows dynamically generating the query, similarly to how `source_ami_filter` works. Within here, a "most_recent_image" attribute that defaults to `false`. The filter, if present, should be parsed to the internal image config. Then, with functionality added to logically handle this attribute, Packer should create the query by concatenating gophercloud's `getUrl()` to the sort/limit arguments. 

I believe this accomplishes what you're looking for. I forked the project to take a look through myself.

**Comment by tcarrio** [comment] 2018-07-10 00:06
Furthermore, the filters seem to be handled by the AWS SDK (`aws_sdk_go` is imported and invoked with the `DescribeImages()` method, given the full parameters including filters). 

It may be worthwhile to simply add only a `most_recent_image` attribute to the config, and submit an issue requesting filter capabilities from `gophercloud`.

**Comment by tcarrio** [comment] 2018-07-10 02:50
To follow up:

It seems that the exposed functions which are responsible for calling the OpenStack API from gophercloud do not allow the functionality we need. 

I have opened an issue and have a WIP branch for gophercloud to add `GET /images?{filters}` functionality to enable this enhancement. 

I also have a WIP branch for Packer with the added functionality. Until gophercloud merges those changes this functionality will not be possible.

**Comment by haxorof** [comment] 2018-07-10 05:05
Hi @tcarrio,
It is something similar what I am looking for but you will have to go via the [image service](https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/requests.go) instead in gophercloud. The reason is that in the way of fetching images via the compute service is [deprecated](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/images/doc.go#L5-L6) and you should instead call the image service directly and then provide the ID of the image as `ImageRef` in the compute service in gophercloud.

Please have a look at the [list options](https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/requests.go#L24-L91) in the image service and you will find what you are looking for.

Cheers!

**Comment by rickard-von-essen** [comment] 2018-07-10 07:41
@haxorof is correct, all image related operations should be done through the image v2 API, not the compute API. I believe everything in is already in gophercloud that we need for this.

**Comment by tcarrio** [comment] 2018-07-10 11:54
Yes it seems so. Good too, there's no blocker.

I will refactor my work to utilize the existing image service in `gophercloud`. Thanks for the heads up!

**Comment by tcarrio** [comment] 2018-07-11 23:01
Should this mimic the same layout as `source_ami_filter`? That's not an issue, but I want to confirm this first. To review the implementation for AWS:

```
{
  "source_ami_filter": {
    "filters": {
      "virtualization-type": "hvm",
      "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
      "root-device-type": "ebs"
    },
    "owners": ["099720109477"],
    "most_recent": true
  }
}
```

We can duplicate this structure and underneath parse to a ListOpt for the imageservice. It will accept tags as they are given in the [OpenStack documentation](https://developer.openstack.org/api-ref/image/v2/). For example:

```
"source_image_filter": {
    "filters": {
	"name": "ubuntu-16.04*",
	"visibility": "protected",
        "owner": "d1a588cf4b0743344508dc145649372d1",
	"tag": "prod"
    },
    "most_recent": true
  }
```

However to satisfy this issue and allowing the most recent image by name to be pulled, we would only need another field `most_recent_image` to be specified. As it is now, Packer's required fields are either

- `source_image` (ID or full URL)
- `source_image_name`

The `most_recent_image` will be checked in the scenario where `source_image_name` is provided but `source_image` is not. 

Thus the alternative solution would have the following OpenStack configuration (example bogus nonsense fields):

```
{
  "type": "openstack",
  "identity_endpoint": "http://<destack-ip>:5000/v3",
  "tenant_name": "admin",
  "domain_name": "Default",
  "username": "admin",
  "region": "RegionOne",
  "ssh_username": "root",
  "image_name": "Test image",
  "source_image_name": "packer_ubuntu_16.04_image",
  "most_recent_image": "true"
  "flavor": "m1.tiny",
  "insecure": "true"
}
```

vs

```
{
  "type": "openstack",
  "identity_endpoint": "http://<destack-ip>:5000/v3",
  "tenant_name": "admin",
  "domain_name": "Default",
  "username": "admin",
  "region": "RegionOne",
  "ssh_username": "root",
  "image_name": "Test image",
  "source_image_name": "packer_ubuntu_16.04_image",
  "source_image_filter": {
    "filters": {
	"name": "ubuntu-16.04*",
	"visibility": "protected",
        "owner": "d1a588cf4b0743344508dc145649372d1",
	"tag": "prod"
    },
    "most_recent": true
  },
  "flavor": "m1.tiny",
  "insecure": "true"
}
```

I'm interesting in knowing which is preferred.

**Comment by tcarrio** [comment] 2018-07-15 19:49
The work on this is nearly finished. Writing up unit tests and getting it to all pass, but out of town so it has been slow progress until the week. 

I went the route of #2 and allow all fields of ListOpts to be parsed from the config. 

Looking forward to feedback after my submission. I will link back to this issue when I make the PR.

**Closed** 2018-08-23 10:41 UTC
Labels: builder/openstack, enhancement
