### ISSUE TITLE
vmware-iso buider fails with communicator: none

### ISSUE THREAD

**Issue by abbbi** [hashicorp/packer#5816] opened 2018-01-25 14:16 UTC
- Packer version from `1.1.3`
- debian

I have no need for a communicator as all my customizations are getting applied within the kickstart file i preseed. Setting communicator: none has worked flawlessly with the qemu builder, the vmware-iso builder bails out.

example config:

```
{
  "builders": [
     {
      "name": "centos-74",
      "type": "vmware-iso",
      "iso_checksum_type": "none",
      "iso_url": "/install/iso_images/linux/centos7/CentOS-7-x86_64-DVD-1708.iso",
      "disk_size": 10140,
      "headless": false,
      "http_directory": "http",
      "http_port_min": 10082,
      "http_port_max": 10082,
      "communicator": "none",
      "skip_compaction": "true",
      "shutdown_command": "none",
      "shutdown_timeout": "20m",
      "boot_command": [ "<up><tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>" ],
      "vmx_data": { "memsize": "2024", "numvcpus": "2" },
      "format": "ova"
    }
  ]
}
```

reported crash:

```
==> centos-74: Typing the boot command over VNC...
==> centos-74: Stopping virtual machine...
Build 'centos-74' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> centos-74: unexpected EOF

==> Builds finished but no artifacts were created.
panic: interface conversion: *none.comm is not packer.Communicator: missing method DownloadDir
2018/01/25 15:13:57 packer-old: 
2018/01/25 15:13:57 packer-old: goroutine 21 [running]:
2018/01/25 15:13:57 packer-old: panic(0x11b4100, 0xc82039d200)
2018/01/25 15:13:57 packer-old:         /usr/local/go/src/runtime/panic.go:464 +0x3e6
2018/01/25 15:13:57 packer-old: github.com/mitchellh/packer/builder/vmware/common.(*StepShutdown).Run(0xc820262f20, 0x7f4b4be62a20, 0xc82035c090, 0x0)
2018/01/25 15:13:57 packer-old:         /Users/cbednarski/go/src/github.com/mitchellh/packer/builder/vmware/common/step_shutdown.go:37 +0xb4
2018/01/25 15:13:57 packer-old: github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc820159b80, 0x7f4b4be62a20, 0xc82035c090)
2018/01/25 15:13:57 packer-old:         /Users/cbednarski/go/src/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x330
2018/01/25 15:13:57 packer-old: github.com/mitchellh/packer/builder/vmware/iso.(*Builder).Run(0xc82022ad80, 0x7f4b4bea1118, 0xc8200db700, 0x7f4b4bea1160, 0xc820342010, 0x7f4b4bea1190, 0xc820080080, 0x0, 0x0, 0x0, ...)
2018/01/25 15:13:57 packer-old:         /Users/cbednarski/go/src/github.com/mitchellh/packer/builder/vmware/iso/builder.go:315 +0x1a0c
2018/01/25 15:13:57 packer-old: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc8202aa100, 0x1, 0xc82006ff60, 0x0, 0x0)
2018/01/25 15:13:57 packer-old:         /Users/cbednarski/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x3b9
2018/01/25 15:13:57 packer-old: reflect.Value.call(0x10c1460, 0x1210038, 0x13, 0x13c8af8, 0x4, 0xc8200efed8, 0x3, 0x3, 0x0, 0x0, ...)
2018/01/25 15:13:57 packer-old:         /usr/local/go/src/reflect/value.go:435 +0x120d
2018/01/25 15:13:57 packer-old: reflect.Value.Call(0x10c1460, 0x1210038, 0x13, 0xc8200efed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2018/01/25 15:13:57 packer-old:         /usr/local/go/src/reflect/value.go:303 +0xb1
2018/01/25 15:13:57 packer-old: net/rpc.(*service).call(0xc8202b2080, 0xc8202b2040, 0xc82006ff20, 0xc8202a4200, 0xc820012340, 0xf301a0, 0xc82006ff2c, 0x18a, 0xefba80, 0xc82006ff60, ...)
2018/01/25 15:13:57 packer-old:         /usr/local/go/src/net/rpc/server.go:383 +0x1c2
2018/01/25 15:13:57 packer-old: created by net/rpc.(*Server).ServeCodec
2018/01/25 15:13:57 packer-old:         /usr/local/go/src/net/rpc/server.go:477 +0x49d
2018/01/25 15:13:57 ui error: Build 'centos-74' errored: unexpected EOF
2018/01/25 15:13:57 Builds completed. Waiting on interrupt barrier...
2018/01/25 15:13:57 machine readable: error-count []string{"1"}
2018/01/25 15:13:57 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/01/25 15:13:57 machine readable: centos-74,error []string{"unexpected EOF"}
2018/01/25 15:13:57 ui error: --> centos-74: unexpected EOF
2018/01/25 15:13:57 ui: 
==> Builds finished but no artifacts were created.
2018/01/25 15:13:57 waiting for all plugin processes to complete...
2018/01/25 15:13:57 /cache/appliance/packer-old: plugin process exited
```

any hints for how to workaround this are appreciated, thank you!

**Comment by rickard-von-essen** [comment] 2018-01-25 15:40
As a work around try to setting `shutdown_command` to `""`.

**Comment by abbbi** [comment] 2018-01-25 15:43
that doesnt work sadly ...

**Comment by abbbi** [comment] 2018-01-25 15:52
in an hackish attempt i now changed vmware/common/step_shutdown.go to allways wait for the VM to shutdown by itself, but i think the correct solution would be somewhere in iso/builder.go to set the communicator to nil, but i lack the necessary go skills to to so :)

**Comment by rickard-von-essen** [comment] 2018-01-25 15:56
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by abbbi** [comment] 2018-01-25 16:07
hi,
apparently it works if shutdown_command has a random value:
"shutdown_command": "foo"
resumes with operation.

**Comment by SwampDragons** [comment] 2019-02-27 00:18
I can't reproduce this on the master branch, so I think it has been fixed. I'm going to close this issue.

**Closed by SwampDragons** 2019-02-27 00:18 UTC
Labels: bug, builder/vmware
