### ISSUE TITLE
CentOS Packer installation error

### ISSUE THREAD

**Issue by nicholasleeeee** [hashicorp/packer#11422] opened 2021-11-30 08:06 UTC
Hi,

I am trying to download Packer on CentOS.
We have followed the installation and commands from the website.
https://learn.hashicorp.com/tutorials/packer/get-started-install-cli

Config manager and the repo has been added.
However when it comes to`sudo yum -y install packer`, there is an error retrieving.
**`https://rpm.releases.hashicorp.com/RHEL/2.2/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`**

Is there any error in the link? Any way for me to download packer?

Thank you,
Nicholas

**Comment by nywilken** [comment] 2021-12-01 21:09
Hi @nicholasleeeee this looks like a repo URL issue. I see that the release version in the repo URL is 2.2, which I would expect to be 7 or 8 for Centos. 

By chance are you using Amazon Linux?

For Redhat based distributions there are three different repo URLs: RHEL/Centos, Fedora, and Amazon Linux. I am able to reproduce this issue by using the RHEL/Centos repo URL on an Amazon linux instance. 

```
==> amazon-ebs.basic-example: failure: repodata/repomd.xml from hashicorp: [Errno 256] No more mirrors to try.
==> amazon-ebs.basic-example: https://rpm.releases.hashicorp.com/RHEL/2/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

If you are using an Amazon Linux variant of Redhat please use the repo URL for Amazon - shown below

```
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
```

An alternative to installing Packer, if you are unable to resolve the yum installation process, is the binary downloads at https://www.packer.io/downloads

I'm going to close this issue as I suspect it will get resolved once you update the repo URL for Amazon Linux. But if I made a mistake and it does not resolve your issue please feel free to drop a comment and I will try to help out. Cheers!

**Closed by nywilken** 2021-12-01 21:09 UTC
Labels: question

**Comment by nicholasleeeee** [comment] 2021-12-02 03:34
Hi @nywilken thank you for your reply.
However, I am using CentOs Linux. I have tried the Amazon Linux url, just to try and got the same error.
`https://rpm.releases.hashicorp.com/RHEL/2.2/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`
` One of the configured repositories failed (Hashicorp Stable - x86_64)`

**Comment by nywilken** [comment] 2021-12-02 19:14
Hi @nicholasleeeee thanks for the follow up here. The HashiCorp rpm repositories only provide binaries for Centos 7 and 8 , with their respective URLs being `https://rpm.releases.hashicorp.com/RHEL/7/x86_64/stable/repodata/repomd.xml` and `https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable/repodata/repomd.xml`.  The reason why you are getting the 404 is because there is no repodata for version 2.2.

I'm not too familiar with the versioning of Centos  but it looks like the 2.x version is an old release of the distribution. If you are using a version prior to Centos 7 or 8 then you will need to install Packer manually by downloading the binary from https://www.packer.io/downloads. 

If you are using a later version of centos, I would check '/etc/yum.conf or maybe the contents of `/etc/redhat-release` and ensure that the correct $releasever is being set. An alternative is to manually modify the file `/etc/yum.repos.d/hashicorp.repo` to use the correct version. For example for Centos 7

```
baseurl=https://rpm.releases.hashicorp.com/RHEL/7/$basearch/stable
enabled=0
gpgcheck=1
```

I hope this helps.

**Comment by nicholasleeeee** [comment] 2021-12-06 03:18
@nywilken Thank you for your reply.

Looks like I am not using CentOs 7 or 8. I have move forward with just downloading from the binary and it works on my CentOs version. 

Thanks for the help.
