### ISSUE TITLE
Azure Builder SIG Support Setting the Storage Account Type

### ISSUE THREAD

**Issue by jzuchora87** [hashicorp/packer#7892] opened 2019-07-21 18:23 UTC
Hello,
This is a feature request for the Azure Build and Shared Image Gallery. Currently, we can set the replication regions but not the replica count or storage account type. Or perhaps the doc just needs to be updated to include information on what those variables are actually called. I'm pretty sure these were only available in the latest shared gallery arm template api so I understand if it's not possible. It's just unfortunate that the storage account type cannot be updated so I'm left with a nasty work around using Azure PowerShell.

`			"shared_image_gallery_destination": {
				"resource_group": "{{user `gallery_resource_group_name`}}",
				"gallery_name": "{{user `gallery_name`}}",
				"image_name": "{{user `image_def_name`}}",
				"image_version": "{{user `image_version`}}",
				"replication_regions": [
					"eastus"
				]
			},`

 I've tried setting my managed image variables with no success:

`			"managed_image_zone_resilient": true,
			"managed_image_storage_account_type": "Premium_LRS",`

![image](https://user-images.githubusercontent.com/34356109/61595259-da8a1b80-abc2-11e9-91fa-d9591563887e.png)

Thanks!

**Comment by SwampDragons** [comment] 2019-07-23 20:55
This may be a duplicate of https://github.com/hashicorp/packer/issues/7304

**Comment by nywilken** [comment] 2021-06-30 18:58
I believe this was resolved by #10863. I'm going to close this issue as this should now be fixed. If you run into issues using the latest version of Packer please feel free to comment on this issue and we will gladly reopen.

**Closed by nywilken** 2021-06-30 18:58 UTC
Labels: builder/azure, duplicate, enhancement, remote-plugin/azure
