### ISSUE TITLE
Packer build error 

### ISSUE THREAD

**Issue by rayen32** [hashicorp/packer#11471] opened 2021-12-23 13:35 UTC
2021-12-23T10:31:12.1966406Z ==> azure-arm: Getting the certificate's URL ...
2021-12-23T10:31:12.1967078Z ==> azure-arm:  -> Key Vault Name        : 'pkrkv7me8z5x2f8'
2021-12-23T10:31:12.1971645Z ==> azure-arm:  -> Key Vault Secret Name : 'packerKeyVaultSecret'
2021-12-23T10:31:12.4232710Z ==> azure-arm:  -> Certificate URL       : 'https://pkrkv7me8z5x2f8.vault.azure.net/secrets/packerKeyVaultSecret/887c431a20574c2794b83013d6a96720'
2021-12-23T10:31:12.4233700Z ==> azure-arm: Setting the certificate's URL ...
2021-12-23T10:31:12.4239001Z ==> azure-arm: Validating deployment template ...
2021-12-23T10:31:12.4260262Z ==> azure-arm:  -> ResourceGroupName : 'pkr-Resource-Group-7me8z5x2f8'
2021-12-23T10:31:12.4263885Z ==> azure-arm:  -> DeploymentName    : 'pkrdp7me8z5x2f8'
2021-12-23T10:31:13.1831083Z ==> azure-arm: Deploying deployment template ...
2021-12-23T10:31:13.1832414Z ==> azure-arm:  -> ResourceGroupName : 'pkr-Resource-Group-7me8z5x2f8'
2021-12-23T10:31:13.1835905Z ==> azure-arm:  -> DeploymentName    : 'pkrdp7me8z5x2f8'
2021-12-23T10:35:14.3894826Z ==> azure-arm:
2021-12-23T10:35:14.3897261Z ==> azure-arm: Getting the VM's IP address ...
2021-12-23T10:35:14.3898340Z ==> azure-arm:  -> ResourceGroupName   : 'pkr-Resource-Group-7me8z5x2f8'
2021-12-23T10:35:14.3902240Z ==> azure-arm:  -> PublicIPAddressName : 'pkrip7me8z5x2f8'
2021-12-23T10:35:14.3906033Z ==> azure-arm:  -> NicName             : 'pkrni7me8z5x2f8'
2021-12-23T10:35:14.3908417Z ==> azure-arm:  -> Network Connection  : 'PublicEndpoint'
2021-12-23T10:35:14.5501676Z ==> azure-arm:  -> IP Address          : '51.145.234.178'
2021-12-23T10:35:14.6718547Z ==> azure-arm: Waiting for WinRM to become available...
2021-12-23T10:35:27.9729186Z     azure-arm: WinRM connected.
2021-12-23T10:35:27.9744537Z ==> azure-arm: Connected to WinRM!
2021-12-23T10:35:28.0267351Z ==> azure-arm: Uploading ./files/ => C:\Windows\Temp\
2021-12-23T11:52:14.5590993Z ==> azure-arm: Provisioning with Powershell...
2021-12-23T11:52:14.5618310Z ==> azure-arm: Provisioning with powershell script: C:\Users\VSSADM~1\AppData\Local\Temp\powershell-provisioner1787732058
2021-12-23T11:52:19.8449509Z ==> azure-arm: At C:\Windows\Temp\script-61c44fce-4e57-ea95-d24f-938d06998c43.ps1:189 char:196
2021-12-23T11:52:19.8454426Z ==> azure-arm: + ... SEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s  ...
2021-12-23T11:52:19.8463174Z ==> azure-arm: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-23T11:52:19.8467920Z ==> azure-arm: The string is missing the terminator: '.
2021-12-23T11:52:19.8481845Z ==> azure-arm:     + CategoryInfo          : ParserError: (:) [], ParseException
2021-12-23T11:52:19.8482594Z ==> azure-arm:     + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
2021-12-23T11:52:19.8497618Z ==> azure-arm:

**Comment by MademoiselleVictoire** [comment] 2021-12-31 21:59
Solution might be here:
https://www.packer.io/docs/builders/virtualbox/ovf

When exporting from VirtualBox make sure to choose OVF Version 2, since Version 1 is not compatible and will generate errors like this.

**Comment by nywilken** [comment] 2022-01-19 20:58
Hi there and thanks for reaching out. This looks like an error generated by the Azure ARM builder when trying to run a powershell provisioner script. Quickly looking at the error I would guess that there is an error with the script or inline command being passed to the provisioner. Without details around the script or template to reproduce it is hard to figure out what might be the issue. 

Have you tried running the provisioner command manually? 

You can use Packer build with the `--debug` flag or the `provisioner breakpoint {}` to stop the before executing the provisioner. I am going to close this issue but if you are still running into issues here and suspect that you are running into a bug please open a new issue on the [packer-plugin-azure](https://github.com/hashicorp/packer-plugin-azure) repo.

**Closed by nywilken** 2022-01-19 20:58 UTC
