### ISSUE TITLE
1.0.3 ansible provisioner never connects

### ISSUE THREAD

**Issue by nwalke** [hashicorp/packer#5150] opened 2017-07-20 19:34 UTC
Packer version: 1.0.3
Host: MacOS
Remote host: Ubuntu 16.04

The ansible provisioner can't seem to connect, it gets stuck at "Gathering Facts".  I tried SSH'ing manually using the SSH server packer sets up (using the details from the ansible command it runs):
```
ssh -i #/var/folders/nk/kbpl_2yj1hz19vt6zbfv_0y40000gn/T/ansible-key111111111 ubuntu@127.0.0.1 -p 59552
```
I'm not sure what user it's supposed to be using, but when I try to connect with `ubuntu`, I got a `shell request failed on channel 0` error.  When I try to connect with `nwalke`, I just get a permission denied error.

If I look at the inventory file it tried to pass to ansible, it tells ansible to use `nwalke` instead of `ubuntu`.  I added the `user` parameter to the ansible provisioner and set it to `ubuntu` and still saw the same issue.

I switched back to 1.0.2 and left everything else the same and it connected.  

My ansible provisioner configuration block:
```
    {
      "type": "ansible",
      "playbook_file": "../ansible/site.yml",
      "groups": [
        "{{ user `server_type` }}",
        "{{ user `environment` }}"
      ],
      "user": "{{ user `ansible_user` }}",
      "extra_arguments": [
        "--become"
      ]
    }
```

**Comment by SwampDragons** [comment] 2017-07-20 19:58
thanks for reporting this -- I believe this is a duplicate of https://github.com/hashicorp/packer/issues/5142 and solved by https://github.com/hashicorp/packer/pull/5146

Let me know if this patch doesn't solve the issue for you (and apologies for the regression)

**Closed** 2017-07-20 19:58 UTC

**Comment by nwalke** [comment] 2017-07-20 20:02
Awesome, thanks.
