### ISSUE TITLE
Feature Request - Provisioner timeouts

### ISSUE THREAD

**Issue by wayneworkman** [hashicorp/packer#4819] opened 2017-04-21 19:07 UTC
As a packer user who relies heavily on bash and powershell scripts to build AMIs in Amazon Web Services, I would like to add a timeout to shell script provisioners via packer.

What I would like is to be able to use something like this:
```
"provisioners": [
      {
          "type": "shell",
          "execute_command": "chmod +x {{ .Path }}; sudo '{{ .Path }}' {{ user `aws_account_nickname` }}",
          "script": "/home/ec2-user/amis/scripts/provision.sh",
          "script_timeout": "60m"
      }
]
}
```
If the script fails to complete within the specified timeout, I want packer to consider the build a failure, cleanup the temporary keys, instances, security groups, temporary subnets, routes - the works - just as it would if it encountered an error.

This would prevent packer running infinitely because of a powershell script or bash script hanging.

I would like the default `script_timeout` to be one hour.

Also, thanks in advance to a highly responsive packer dev team! :-)

**Comment by SwampDragons** [comment] 2017-09-28 21:13
This is a really interesting idea.  A quick glance at the code tells me that this would probably have to be implemented inside the communicatior's StartWithUi function, which would have a pretty broad touch across the packer code.  I still think it might be worth doing, since there seem to be plenty of odd edge-case situations where packer hangs indefinitely.  What do you think @mwhooker?

**Comment by mwhooker** [comment] 2017-09-28 23:46
thinking maybe we can solve this with https://github.com/hashicorp/packer/pull/4709 which is only partially done

**Comment by wayneworkman** [comment] 2017-09-28 23:55
4709 is for ssh. I opened 4819 because of a powershell problem.

**Comment by mwhooker** [comment] 2017-09-29 00:08
That wasn't obvious. Perhaps the same solution in #4709 can be adapted to winrm

**Comment by mwhooker** [comment] 2017-09-29 00:15
Looks like we can add a Timeout to the winrm endpoint https://github.com/masterzen/winrm/blob/b09cde26d67bcb0c7cbf02b16bb26b7f8fb0171e/endpoint.go#L27-L29

**Comment by jurajseffer** [comment] 2017-12-18 11:37
I could use this feature right now as I have a build that appears to be stuck and we only print the output from the provisioner at the end of it so as it is now it will run forever.

**Comment by SwampDragons** [comment] 2018-07-20 17:37
I definitely agree it's a good idea -- the issue is still open because I'd like to see it implemented.  That said, it isn't currently top of my list.  I can probably slate it for a few releases from now, but if you want to see it sooner you may need to make your own PR. :-/

**Comment by SwampDragons** [comment] 2019-04-11 20:17
This was closed by https://github.com/hashicorp/packer/pull/7466 :D

**Closed by SwampDragons** 2019-04-11 20:17 UTC
Labels: communicator/ssh, communicator/winrm, enhancement
