### ISSUE TITLE
Allow Vagrant box import for VirtualBox builder

### ISSUE THREAD

**Issue by gvenzl** [hashicorp/packer#5571] opened 2017-11-09 21:32 UTC
It would be great if the VirtualBox builder (and probably also others) would allow to use a Vagrant box as source image, alongside with the `virtualbox-iso` and `virtualbox-ovf`. This would further improve cross-usability of both products. Today Packer already allows the creation of [Vagrant boxes in the post processor step](https://www.packer.io/intro/getting-started/vagrant.html) so this is already there one-way. If we were to add having Vagrant box images as import sources too, vendors will only have to provide a Vagrant box image once and people will be able to use it for both, Vagrant and Packer.

**Comment by rickard-von-essen** [comment] 2017-11-10 12:07
Thanks for reporting this. This is a duplicate of #869, for more info see that issue.

**Closed by rickard-von-essen** 2017-11-10 12:07 UTC
Labels: builder/virtualbox, duplicate, enhancement

**Comment by peterlindstrom234** [comment] 2017-11-18 15:54
> This is a duplicate of #869, for more info see that issue.

What more information do we get there? 

It's been like three years since the issue was opened, right? I skimmed through the whole thread, but don't remember seeing any responses from HashiCorp.

I've been getting to grips with Packer, and thought I'd be using it to add things on top of "base images", producing derivative, more fully featured images. I'd imagine this is exactly what most people would expect.

But my current understanding is that I could only do that with AMI images, but not with VMWare/VirtualBox images. 

I may be missing something again, but right now I'm just seeing another red flag, especially with the silence from HashiCorp.

**Comment by rickard-von-essen** [comment] 2017-11-19 06:49
This [comment](https://github.com/hashicorp/packer/issues/869#issuecomment-343559068) shows a script that can take care of this. 

Vagrant boxes are not inputs for `vmware-vmx`/`virtualbox-ova` they would require preprocessing . Adding that to packer would require significant changes to the core architecture.

**Comment by peterlindstrom234** [comment] 2017-11-19 14:04
@rickard-von-essen 

Well, could you tell me how I would use Packer to:

  1) Install an OS from an ISO, using VMWare
  2) Save the results into a VMWare "base image"
  3) Build derivative images from the base image, still with VMWare.

My current understanding is that I can't, mostly because Packer doesn't support that kind of workflows for VMWare (nor even for VirtualBox?)

**Comment by SwampDragons** [comment] 2017-11-20 17:22
Probably the source of confusion here is that there are two different vmware builders.  The first, vmware-iso, builds an image from scratch from an iso. https://www.packer.io/docs/builders/vmware-iso.html . The second, https://www.packer.io/docs/builders/vmware-vmx.html, uses a vmware image as its source, which allows iteration.

**Comment by SwampDragons** [comment] 2017-11-20 17:23
Probably the source of confusion here is that there are two different vmware builders.  The first, [vmware-iso](https://www.packer.io/docs/builders/vmware-iso.html), builds an image from scratch from an iso. 
 

The second,[ vmware-vmx](https://www.packer.io/docs/builders/vmware-vmx.html), uses a vmware VM as its source, which allows iteration off a "base" or "golden" image.

**Comment by SwampDragons** [comment] 2017-11-20 17:26
So what you'd do is have two different packer configs, one that generates the base image and another that generates the derivative.  These configs would use different builders entirely, and the only thing they'd have in common is that the output from one would be the input to another.  At $LAST_JOB I used two packer configs in conjunction with a CI system (in my case Jenkins) to string them together and pass the artifact from one build to another.

**Comment by peterlindstrom234** [comment] 2017-11-21 04:16
@SwampDragons thanks for the tip!
