### ISSUE TITLE
download progress bar is not refreshing but sending newlines

### ISSUE THREAD

**Issue by azr** [hashicorp/packer#6625] opened 2018-08-24 14:53 UTC
Howdy 🙂 ,

I think this is not the intended behavior.

Here's a screenshot:
![screen shot 2018-08-24 at 16 42 59](https://user-images.githubusercontent.com/1024852/44591219-6fbb3f00-a7bd-11e8-96d7-79c47a2f09c6.png)

I ran a `packer build ` on master and using zsh

#5851

**Comment by SwampDragons** [comment] 2018-08-24 16:07
I knew this when I merged it.

The root cause is [here](https://github.com/hashicorp/packer/blob/master/common/progress.go#L141-L142): essentially, the progress bar output is piped through our ui using ui.Message(). That UI method appends a newline to every message sent to it. I did some tinkering and found that we could work around it in posix systems with some ANSI escape sequences set using the progress bar's prefix method, but that caused the output to be wacky if we had two downloads running at once. 

Ultimately I decided it was worth merging as-is and coming back to the UI later, because the behavior is essentially the same as it used to be before we added the progress bar-- we'd just print a % complete to the UI instead of a graphic.

If we want it to be exactly the same amount of "spamminess" as it was before, we can decrease the progress bar's refresh rate to 5s.

**Comment by SwampDragons** [comment] 2018-08-24 16:15
The relevant ANSI prefix for our message would be: 

```
- Move the cursor up N lines:
  \033[<N>A
```

source: http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html

**Comment by azr** [comment] 2018-08-27 07:52
Ah gotcha I thought this was not expected 🙂 .

Will definitely look into the code to see if I can do something !! Sounds like something fun to play with.

The progress bar library says that it is experimental and unstable: https://github.com/cheggaaa/pb#multiple-progress-bars-experimental-and-unstable

> Do not print to terminal while pool is active.

random thought: May be we could buffer any logs/outputs while progress bar is running.
Will also look at what docker does 🙂

**Comment by azr** [comment] 2018-08-30 14:01
Okay I made it 5s for now, will now check if I can do something nice with the bar.

**Comment by arizvisa** [comment] 2018-08-31 01:48
This might be hacky, but in the `bar.Callback` closure in `common/progress.go` we can probably cache the previous message in an lvar (for the function). That way we can check if the previous value of `message` has changed then only emit the progress-bar if so.

Although maybe we should add a timer so that if the message hasn't changed and it has been over 5s or something, emit the progress-bar and then reset the timer.

Thoughts?

**Comment by azr** [comment] 2018-09-03 13:46
@arizvisa, this should work but sounds a bit hack; I don't really have thought on this yet.

I'm just starting to think on this and I believe adding a `ProgressBar` func to `packer.Ui` should be a good way, will try to play with code a bit.

**Comment by arizvisa** [comment] 2018-09-03 21:01
@azr, check out the commit history or the conversation in the PR.

One of the places for the progressBar was in `packer.UI`, but due to some limitations of `ugorji/go/codec` (used by packer/rpc) we were unable to serialize the structure due to some of its members being private or some of them being closures. `ugorji/go/codec` lets you describe custom serializers/deserializers, but it needs the codec handle to be exposed. These were some of the reasons why this PR stayed a long time in development before merging.

Check out commit 0f10032b3d64c040910156621667a6abcdd8b787, if you want to see its state moved into packer.Ui. There's some tests you can run in packer/rpc as well to verify whether you're serializing it correctly.

**Comment by arizvisa** [comment] 2018-09-03 21:04
@azr, relevant comments demonstrating the wall we encountered with serialization/deserialization: 
https://github.com/hashicorp/packer/pull/5851#issuecomment-412213053
https://github.com/hashicorp/packer/pull/5851#issuecomment-412772354

There were about ~50 commits, but we squashed it into this 7 chapter history that's in the revision log.

**Comment by arizvisa** [comment] 2018-09-03 21:12
fd2fef87386228aa9b6541c99dd6332a2d5511e7 This is the other prior commit which modifies packer.UI to expose only the length of the prefix that is needed to avoid emitting multiple newlines due to terminal width.

good luck in your avoidance of re-implementation/hacks, tho. ;-)

**Comment by azr** [comment] 2018-09-04 10:15
Ah, there is a lot of history there, sorry I did not take the time to read that PR before as I just expected to understand everything from code/testing. Which is in general faster than words/history for me 🤖.
I can feel your pain now🔥.

Yet, I still think this should work. RPC is a communication protocol; and instead of trying to send the progress bar over the wire; I would try to send what the progress bar should be doing over the wire.

Behold ! The all mighty remote progress bar. ( I hope this is doable ! )

**Comment by azr** [comment] 2018-09-04 14:27
Yes, I confirm; I have a self refreshing progress bar working locally !
Okay, I'll try to have it look good for a review 🙂 bear with me !

**Comment by azr** [comment] 2018-09-07 15:18
Hey @arizvisa, I'm interested to hear your opinion about this PR #6673 if you have time 🙂

**Comment by arizvisa** [comment] 2018-09-07 20:18
kk.

**Comment by arizvisa** [comment] 2018-09-07 20:53
ok lol. i took more time to look at the pr, felt guilty that i was being selfish with my time for my regular job. anyways..

**Comment by SwampDragons** [comment] 2018-09-10 19:06
I've merged the associated PR so I'm gonna close this.

**Closed by SwampDragons** 2018-09-10 19:06 UTC
