### ISSUE TITLE
Packer Crash - 08122019

### ISSUE THREAD

**Issue by gloverc** [hashicorp/packer#7976] opened 2019-08-12 19:04 UTC
Packer Crash

Describe the problem and include the following information:

- Packer version 1.4.2
- Host platform RHEL7
- Debug log output from `PACKER_LOG=1 packer build 2016ahv.json`.
  with packerlog and crash.log

https://gist.github.com/gloverc/c4eebd6ca77224f61dea9175225e3f40

**Comment by SwampDragons** [comment] 2019-08-19 23:17
I don't think I'll be able to reproduce this without the autounattend file and knowing which iso you were using.

**Comment by SwampDragons** [comment] 2019-09-26 23:54
Closing because it's been a month and I've never heard back. We can reopen if we get more info.

**Closed by SwampDragons** 2019-09-26 23:54 UTC
Labels: need-more-info, need-repro
