### ISSUE TITLE
ena_support doesn't work as expected on some imported AMIs

### ISSUE THREAD

**Issue by pavel-voinov** [hashicorp/packer#7369] opened 2019-03-04 20:47 UTC
## Environment
- Packer v1.3.3
- Host platform is AmazonLinux 2018.03
- packer is running as part of the Jenkins job.

## Description of the problem
I have AMI imported previously from official Oracle Linux 6.10 ISO by packer amazon-import post-provisioner. AMI itself is ok. I built many other AMIs based on it and launched instances.
I tried to build new AMI based on this AMI with UEK and with "ENA" support. Provisioning steps made sure that all is set according to AWS documentation (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html). "ena" kernel module is present (it's shown at the end of the packer log). I was calling packer with `-var ena_support=true`, but packer didn't modify the temporary instances and didn't set `EnaSupport` attribute of the AMI to `true` as it should do. The same documented method works fine with other AMI based on AmazonLinux 2018.03.

`packer build` command (vars purpose should be clear without real values):
```
PACKER_LOG=1 packer build \
  -machine-readable \
  -var hvm_amiid=<AMI of imported Oracle Linux 6.10 ISO> \
...
  -var os_version=6.10 \
  -var vpc_id=$VPC_ID \
  -var security_group_id=$SECURITY_GROUP_ID \
  -var subnet_id=$SUBNET_ID \
  -var region=$REGION \
  -var instance_type=$INSTANCE_TYPE \
  -var iam_instance_profile=$IAM_ROLE \
  -var root_volume_size=12 \
  -var ena_support=true \
  oracle_linux.json \
  | tee oracle-linux-6.10.log
```

* Packer template - [oracle_linux.json.zip](https://github.com/hashicorp/packer/files/2928031/oracle_linux.json.zip)
* Packer buld log - [oracle-linux-6.10.log.zip](https://github.com/hashicorp/packer/files/2928115/oracle-linux-6.10.log.zip)

## Workaround I had to use
Because packer in my case didn’t modify temporary instance attributes before create the image, it was needed to do this in the “provisioner”. Modification of the instance attributes requires that ec2 is stopped, so the only method was to use “shell-local” provisioner. I couldn’t find how to get Instance Id of the temporary instance running by `packer` built-in functions.
So, I let packer to output to the log file on the host system with `tee` command:
`packer build .... | tee <logfile.log>`
and then called grep the same <logfile.log> in the "shell-local" provisioner in the packer's template:
`INSTANCE_ID=$(grep -E -o 'hvm_builder: Instance ID: i-.*$' \"logfile.log\" | grep -E -o 'i-[a-z0-9]+$')"`
Then it was used several standard AWS CLI calls to modify the temporary instance:
```
aws ec2 stop-instances --instance-ids $INSTANCE_ID
aws ec2 wait instance-stopped --instance-ids $INSTANCE_ID
aws ec2 modify-instance-attribute --instance-id $INSTANCE_ID --ena-support
```
These commands are last in the "provisioners" list.
`packer` is calling with `disable_stop_instance=true` because EC2 instance is stopped normally by the commands above and it's not needed to do this again by default behaviour of the `packer`.

**Comment by SwampDragons** [comment] 2019-03-05 18:26
ena_support isn't a variable, it's a template option. Setting a variable won't work unless you're also setting the option inside the builder section. 

Example:

```
{
	"variables": {
		"ena_support": true # this is what you're creating via the command line
	},
	"builders": {
		"type": "amazon-ebs",
		"ena_support": {{ user `ena_support`}} ## this is what you'd need to add in your template
	}
}
```

Or, to modify your example template:

```
{
  "variables": {
    "build": "",
    "ami_profile": "",
    "release": "",
    "os_version": "",
    "hvm_amiid": "",
    "date": "",
    "security_group_id": "",
    "subnet_id": "",
    "region": "",
    "vpc_id": "",
    "instance_type": "",
    "iam_instance_profile": "",
    "ami_regions": "",
    "root_volume_size": ""
  },
  "builders": [
    {
      "name": "hvm_builder",
      "ami_virtualization_type": "hvm",
      "type": "amazon-ebs",
      "user_data_file": "sudoers/sudoers",
      "source_ami": "{{user `hvm_amiid`}}",
      "ssh_username": "ec2-user",
      "associate_public_ip_address": "true",
      "subnet_id": "{{user `subnet_id`}}",
      "instance_type": "{{user `instance_type`}}",
      "security_group_id": "{{user `security_group_id`}}",
      "ssh_timeout": "5m",
      "ssh_interface": "private_ip",
      "vpc_id": "{{user `vpc_id`}}",
      "ami_name": "{{user `ami_profile`}}-{{user `os_version`}}-b{{user `build`}}-{{user `release`}}_Source-{{user `hvm_amiid`}}_Built-{{user `date`}}",
      "ami_description": "Standard Oracle Linux {{user `os_version`}} ISO imported into AWS and extended with base roles (similar to base AMI)",
      "region": "{{user `region`}}",
      "iam_instance_profile": "{{user `iam_instance_profile`}}",
      "ena_support": true,
      "run_tags": {
        "Name": "packer-build-{{user `ami_profile`}}-{{user `os_version`}}-{{user `release`}}-b{{user `build`}}",
        "tr:appName": "build"
      },
      "tags": {
        "Name": "{{user `ami_profile`}}-{{user `os_version`}}-{{user `build`}}",
        "source": "{{user `hvm_amiid`}}",
        "virtualization_type": "hvm",
        "build": "{{user `build`}}",
        "release": "{{user `release`}}",
        "profile": "{{user `ami_profile`}}-{{user `os_version`}}",
        "creator": "packer",
        "creation_time": "{{user `date`}}"
      },
      "ami_users": [
      ],
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": "{{user `root_volume_size`}}",
          "volume_type": "gp2",
          "delete_on_termination": true
        }
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [ "sleep 120" ]
    },
    {
      "type": "file",
      "source": "bin/switch_oracle_linux_to_uek.sh",
      "destination": "/tmp/switch.sh"
    },
    {
      "type": "shell",
      "expect_disconnect": true,
      "start_retry_timeout": "10m",
      "inline_shebang": "/bin/bash -e",
      "inline": [
        "chmod +x /tmp/switch.sh",
        "sudo -n /tmp/switch.sh switch"
      ]
    },
    {
      "type": "shell",
      "pause_before": "10m",
      "inline_shebang": "/bin/bash -e",
      "inline": [
         "sudo -n /tmp/switch.sh cleanup",
         "rm -f /tmp/switch.sh"
      ]
    },
    {
      "type": "shell",
      "inline_shebang": "/bin/bash",
      "inline": [
        "uname -a",
        "# checks that ena kernel module is present",
        "sudo modinfo ena"
      ]
    }
  ]
}

```

**Comment by SwampDragons** [comment] 2019-03-05 18:27
I'm closing this because it's a question and not a bug/feature request, but if you still have trouble setting this up feel free to respond or reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool)

**Closed by SwampDragons** 2019-03-05 18:27 UTC
Labels: question

**Comment by pavel-voinov** [comment] 2019-03-06 12:23
Thanks a lot, @SwampDragons.
I did hope that I missed something obvious and I did. It's clear now.

**Comment by SwampDragons** [comment] 2019-03-06 18:00
No problem! Reach out if you have any more questions :)
