### ISSUE TITLE
Don't shutdown the vSphere VM once the build finishes

### ISSUE THREAD

**Issue by amitbhadra** [hashicorp/packer#9362] opened 2020-06-04 16:55 UTC
Using the vsphere-iso, we can create a new VM and boot it up, etc. But after it finishes, it sends a shut down command. I need it to be booted up after this. Can we skip the shut down and finish successfully?

```
[1;32m==> vsphere-iso: Waiting for SSH to become available...[0m
[1;32m==> vsphere-iso: Connected to SSH![0m
[1;32m==> vsphere-iso: Shutting down VM...[0m
```

When I have "disable_shutdown":"true", by default it waits for 5 minutes and the build fails because I didn't have a script in place to shut down the machine.

```
[1;32m==> vsphere-iso: Connected to SSH![0m
[1;32m==> vsphere-iso: Automatic shutdown disabled. Please shutdown virtual machine.[0m
[1;32m==> vsphere-iso: Provisioning step had errors: Running the cleanup provisioner, if present...[0m
[1;32m==> vsphere-iso: Clear boot order...[0m
[1;32m==> vsphere-iso: Power off VM...[0m
[1;32m==> vsphere-iso: Destroying VM...[0m
[1;31mBuild 'vsphere-iso' errored: Timeout while waiting for machine to shut down.[0m
```

**Comment by nywilken** [comment] 2020-06-04 21:21
Hello @amitbhadra thanks for reaching out. There is a `disable_shutdown` configuration option that you can use to do exactly what you are asking. It looks like it is missing from the Vsphere-iso builder docs. But there was a recent documentation update to add in the missing sections that will be published in the next release. 

In the meantime you can refer to the documentation at https://github.com/hashicorp/packer/blob/master/website/pages/partials/builder/vsphere/common/ShutdownConfig-not-required.mdx for details on the `disable_shutdown` option. I'm going to keep this issue open in case you run into any problems with using the option. Otherwise feel free to close this issue.

**Comment by SwampDragons** [comment] 2020-06-04 23:30
We don't currently have code that will allow this, though I agree it would be nice to implement it. 

We could probably get away with not even adding a new flag, just telling users to set the shutdown_timeout to a negative value in order to disable the timeout altogether, and then exit the build if both shutdown_timeout is negative and the disable_shutdown value is true. 

In the meantime, you can set the timeout to a very high value, which won't cause Packer to exit but will leave the VM up for you to tinker with and shut down at your leisure.

**Comment by SwampDragons** [comment] 2020-06-04 23:42
Can I ask why you need to leave the VM running, though? This isn't really what packer was designed for, and there may be a better way to achieve what you need to do.

**Comment by amitbhadra** [comment] 2020-06-05 16:59
Hi @nywilken so, I know of the `disable_shutdown` option, but it just halts the shutdown for the `shutdown_timeout` period and then it fails the build if it hasn't been shut down in that time.

@SwampDragons You're correct, there are other tools to do this and if that is the case then this issue is not required. The reason I need this is because I need it to keep running so that I can trigger other configurations on top of it after the initial provisioning is done. And I need it to keep running forever(or until I shut it down manually) so that I can incorporate this into our list of servers for a particular purpose. If it doesn't shut down, I can potentially ssh into it and do config changes, otherwise I'll have to use tools like say Ansible to first switch it on and then do config changes. 

I read the Terraform vSphere doc and turns out there isn't an option like this there either.

**Comment by SwampDragons** [comment] 2020-06-05 18:31
My first recommendation would be to make sure you don't have to do any manual config changes ;) but knowing that may be easier said than done, my second recommendation would be to let Packer shut down the VM, and then turn the vm back on when you're ready to do the manual config steps -- otherwise you don't get all the benefits of the Packer vsphere cleanup like optionally exporting the VM and removing floppy drives and all of that. 

If you don't want those benefits until after the VM is already tinkered with, then it makes sense to just set the timeout to something absurd like 1 year and give yourself ample time to add configuration and then shut down the vm manually, at which point Packer can resume cleanup. 

Another hack you could perform today is to set the command line flag "on-error=abort" and then intentionally trigger an error  (for example, run a shell provisioner whose only code is "exit 1") to force Packer to exit, while leaving the VM running. This will mean that you have to manually perform any cleanup yourself, though.

**Comment by SwampDragons** [comment] 2020-06-11 21:57
On further thought about this issue, I don't want to allow the user to skip all the shutdown/clean up operations. This isn't what Packer is for, and would make the disable_shutdown option not match the way it is implemented in other builders. I'm going to close, but I wish you luck figuring out a workflow that works for you.

**Closed by SwampDragons** 2020-06-11 21:57 UTC
Labels: builder/vsphere, question
