### ISSUE TITLE
vmware-vmx - ESXi, cloned VM doesn't show up in vSphere.

### ISSUE THREAD

**Issue by e-mow** [hashicorp/packer#7141] opened 2018-12-21 20:43 UTC
If you keep the vmware-iso or another vmware-vmx build registered in ESXi and then go to clone it for another stage in a multi stage build process vSphere treats the pervious VM and the new VM as the same one. This means that your newly cloned VM will not show up in vSphere.

When cloning the VM and VMX file if the following items are wiped out in VMX Data then vSphere will acknowledge the newly cloned VM and will generate new IDs for these items.

`
"vmx_data": {
    "uuid.bios": "",
    "vc.uuid": "",
    "uuid.location": ""
}
`

**Comment by SwampDragons** [comment] 2019-01-03 22:14
Thanks for reporting. Hopefully this can be solved by wiping out the values you're overriding in vmx_data here: 

https://github.com/hashicorp/packer/blob/624c58c67810ec77448f85792c203c28e8716d97/builder/vmware/common/step_configure_vmx.go#L48

I'll try to get on this soon but I suspect it may take me a while to test it enough to be confident I'm not breaking things for other users.

**Comment by e-mow** [comment] 2019-01-09 22:54
Thank you for following up, I will gladly run a test against 6.7 when you need help testing.

**Comment by SwampDragons** [comment] 2020-08-18 20:10
I can't reproduce this. Even without overriding these values, my vSphere instance is able to distinguish the two vms as separate. I'm going to close this and assume that sometime in the last two years VMWare fixed this upstream.

**Closed by SwampDragons** 2020-08-18 20:10 UTC
Labels: bug, builder/vmware-esxi, track-internal
