### ISSUE TITLE
Feature request: for the googlecompute-export post-processor, set the network to use

### ISSUE THREAD

**Issue by Zatarna** [hashicorp/packer#6605] opened 2018-08-20 11:36 UTC
### Use Case

I'm working in GCP. I want to create an image and then use the googlecompute-export post-processor to create a tarball. To not interfere with my set up I have created a separate VPC for Packer to work in, giving the name in the 'network' and 'subnetwork' options in the 'builders' stanza.

The problem is that the post-processor will try to use the 'default' network in the instance creation to zip the image, which fails because of security (bastion, firewall rules). Could we add an option to specify the network to use, or a flag to use the same network as the builder?

The line in question is 79 in packer/post-processor/googlecompute-export/post-processor.go

### System Info
Packer v1.2.5
On Centos 7

**Comment by rickard-von-essen** [comment] 2018-11-17 08:39
Closing this as a duplicate of #6953 (even though this was created before that).

**Closed by rickard-von-essen** 2018-11-17 08:39 UTC
Labels: enhancement, post-processor/googlecompute-export
