### ISSUE TITLE
Segfault while cancelling amazon-ebs builds

### ISSUE THREAD

**Issue by Cireo** [hashicorp/packer#12023] opened 2022-10-03 17:42 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Immediately cancelled a parallel build with multiple `ctrl-C`, got segfault.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`
```
Packer v1.6.6
```

### Simplified Packer Template

Omitted.

### Operating system and Environment details

OSX
```
20.3.0 Darwin Kernel Version 20.3.0
```

### Log Fragments and crash.log files

Blindly removed some lines that I didn't want included

https://gist.github.com/Cireo/f05a906140296f9f0f43bc34cb43de6f

**Comment by nywilken** [comment] 2022-10-04 20:44
Hi there, thanks for opening up this issue. It looks like there were multiple builds happening and a security group dependency error that occurred right before the crash. I can't reproduce this simply by cancelling the build, even with sending multiple cancellation signals. 

Have you tried to reproduce this issue with the latest version of Packer and Amazon Plugin? 

It looks like more information is needed here to better understand what might be happening that is causing the panic. If you can reproduce with the latest release please provide us with a redacted configuration template to reproduce the issue, along with any specific environment setup that might help in reproducing the issue.

**Comment by Cireo** [comment] 2022-10-07 00:17
Thanks for trying to reproduce.  This isn't blocking anything at the moment, I don't intend to run multiple builds simultaneously in the near future.  We may be migrating to the latest packer eventually, once we finish making the hcl compatible with json.  If we do, I will try to revisit this bug and see if I can reproduce as well.

**Comment by nywilken** [comment] 2022-10-19 00:31
@Cireo I'm going to close this issue for now. If you can reproduce when you are able to try again drop a comment on this issue and we will gladly reopen. Cheers!

**Closed by nywilken** 2022-10-19 00:31 UTC
Labels: need-repro, not-reproducible
