### ISSUE TITLE
Allow HTTPIP, HTTPPort, Name to be referenced from user variables

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5749] opened 2017-12-31 19:16 UTC
I would like to move my `boot_command` value up into my packer user variables section, but I need to be able to reference `{{ .HTTPIP }}`, `{{ .HTTPPort }}`, and `{{ .Name }}` within the `boot_command` string. Could packer make these pre-defined variables able to be inserted into strings during user variable declaration?

**Comment by rickard-von-essen** [comment] 2018-01-01 08:50
Thanks for reporting this. This is a duplicate of #4387, closing this in favor of that.

**Closed by rickard-von-essen** 2018-01-01 08:50 UTC

**Comment by akutz** [comment] 2019-05-19 18:14
I'm not sure this is a duplicate. Trying to use the above variables in a user variables section causes an exception with Packer 1.4.1:

```

**Comment by akutz** [comment] 2019-05-19 18:25
Hi all,

I think I have a work-around that appears to be working:

```json
      "boot_command": [
        "{{user `boot_command_prefix`}}",
        "http://{{ .HTTPIP }}:{{ .HTTPPort }}",
        "{{user `boot_command_suffix`}}"
      ],
```

I just have to define any prefix and suffix data for the boot command as part of the user variables, and formatting the above like so in the proper `packer.json` results in the correct interpolation.
