### ISSUE TITLE
vmware builder only tries to use the first network interface (eth0) for SSH connections

### ISSUE THREAD

**Issue by borzwazie** [hashicorp/packer#2530] opened 2015-07-30 14:18 UTC
I am using packer 0.8.2 on Ubuntu 14.04, with VMWare workstation 11. I am attempting to create an Ubuntu 12.04 VM using the stock Ubuntu ISO image, a boot command that includes "interface=eth2", and a preseed file. I have three interfaces set up in my .json file:

```
    "vmx_data": {
            "memsize": "4096",
            "numvcpus": "1",
            "cpuid.coresPerSocket": "2",
            "ethernet0.networkName": "Remote Network",
            "ethernet0.present": "TRUE",
            "ethernet0.startConnected": "FALSE",
            "ethernet0.virtualDev": "e1000",
            "ethernet0.addressType": "generated",
            "ethernet0.generatedAddressOffset": "0",
            "ethernet0.wakeOnPcktRcv": "FALSE",
            "ethernet1.networkName": "Local Network",
            "ethernet1.present": "TRUE",
            "ethernet1.startConnected": "FALSE",
            "ethernet1.virtualDev": "e1000",
            "ethernet1.addressType": "generated",
            "ethernet1.generatedAddressOffset": "0",
            "ethernet1.wakeOnPcktRcv": "FALSE",
            "ethernet2.connectiontype": "nat",
            "ethernet2.present": "TRUE",
            "ethernet2.startConnected": "TRUE",
            "ethernet2.virtualDev": "e1000",
            "ethernet2.addressType": "generated",
            "ethernet2.generatedAddressOffset": "0",
            "ethernet2.wakeOnPcktRcv": "FALSE"
    },
```

Packer starts up correctly. Using vncviewer, I can confirm that the guest gets a DHCP address and Ubuntu installs. However, when the machine reboots post-install, Packer cannot connect via ssh, and fails.

I note the following in the debug logs:

2015/07/30 10:11:09 packer-builder-vmware-iso: 2015/07/30 10:11:09 Lookup up IP information...
2015/07/30 10:11:09 packer-builder-vmware-iso: 2015/07/30 10:11:09 DHCP leases path: /etc/vmware/vmnet8/dhcpd/dhcpd.leases
2015/07/30 10:11:09 packer-builder-vmware-iso: 2015/07/30 10:11:09 Detected IP: 172.16.74.129
2015/07/30 10:11:12 packer-builder-vmware-iso: 2015/07/30 10:11:12 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.16.74.129:22: no route to host

On the guest (via vncviewer), I can see that eth0 and eth1 have no IP address, which is what I expect. The eth2 interface does have an address, but it's 172.16.74.130, not 172.16.74.129. So, Packer will never connect to it.

**Comment by borzwazie** [comment] 2015-07-30 14:37
It looks like the file builder/vmware/common/ssh.go is hard-coded to look for ethernet0:

                if macAddress, ok = vmxData["ethernet0.address"]; !ok || macAddress == "" {
                        if macAddress, ok = vmxData["ethernet0.generatedaddress"]; !ok || macAddress == "" {
                                return "", errors.New("couldn't find MAC address in VMX")
                        }
                }

I'm not a Go expert, so I may be misreading this, however.

**Comment by borzwazie** [comment] 2015-07-30 15:26
The problem is even a little stranger - it turns out that the config, as I posted it, won't get an ip address on anything at all unless I first try to create a Packer image without customizing the vmx_data section at all. This puts an entry in the /etc/vmware/vmnet8/dhcpd/dhcpd.leases file. After this, I can go back, modify the Packer json file, add the vmx_data entries as above, and then eth2 (or whatever non-eth0 interface) will get an address. I found this because I wiped out the dhcpd.leases file to troubleshoot this issue. After I did this, I couldn't get any dhcp address at all until  I removed *all* interface entries from the vmx_data section.

**Comment by cbednarski** [comment] 2015-07-30 21:12
Thanks for the bug report. As you've found with your exploration this logic is a bit complicated because we can't ask the VM what it's IP is. We have to poke around and guess by looking at the lease table.

As you've pointed out, you can have multiple interfaces which may or may not have SSH running on them, though I think this is fairly uncommon. The fix is probably for us to try each interface and use the first one that works.

As a workaround until we can look at this, can you try switching your interfaces so SSH is running on  `eth0`? If this works we can document the work around for the time being.

**Comment by borzwazie** [comment] 2015-07-30 22:13
Yeah, I had wondered about the IP address guess. I would guess that in most
cases the most recent lease in the dhcpd.leases file (for vmware builders)
is the correct one. However, if there were a way (in general) to tell
Packer which network interface it should try first, that would be nice. I
guess it would be different for each builder. I have also run into this
same sort of issue in the Virtualbox builder, so I know it's probably not
an easy problem.

**Comment by cbednarski** [comment] 2015-08-01 23:33
I just ran across this code for vmware here: `builder/vmware/common/ssh.go`

I think it should be reasonably uncomplicated to make this check each interface, or accept a configuration, or both. I don't know what's involved with making this work for all builders. This is not high priority for me but if you want to take a stab I think the code for this is pretty self-contained.

**Comment by arizvisa** [comment] 2016-04-02 06:00
Try this branch I wrote some time ago : https://github.com/arizvisa/packer/tree/vmware-iso-extraconfig
I mentioned it in #3373 as I'm certain it fixes that issue as well.

It properly parses vmnetdhcp.conf, netmap.conf, and the dhcpd leases. This way builder/vmware/common/ssh.go and anything else in builder/vmware will get the correct address.

If it works, I can turn it into a PR and work at getting it merged.

**Comment by mwhooker** [comment] 2017-02-10 07:06
I believe this was solved in #3347

Please open a new issue with a json that reproduces this issue if I'm incorrect

**Comment by arizvisa** [comment] 2017-02-13 00:26
#3347 appears to only work on VMware ESX and not a local VMware Workstation instance.

**Comment by rickard-von-essen** [comment] 2017-02-13 11:38
@arizvisa yes the fix in #3347 is only for ESXi, local VMware builders handles network completely differently.  If you want help with that post on the [mailing list](https://groups.google.com/group/packer-tool).

See https://www.packer.io/community/

**Comment by mwhooker** [comment] 2017-02-13 19:06
okay, looks like I misunderstood. I tried to look at your pr @arizvisa but it's so diverged from master it's hard to tell if it would still work. Would be happy to work with you on getting it updated and see if it can be merged. It looks like a substantial change

**Comment by arizvisa** [comment] 2017-02-27 20:12
Hi mwhooker, I rebased #3417 on top of master. Not sure if you have a chance to continue discussion on this since your comment here is 14 days old. I'll mention details about what it does in the comments over there.

**Comment by arizvisa** [comment] 2017-02-27 20:28
The main changes that are made to the vmware builder are that it removes the .HostIP and .GuestIP address-finder hacks which happen before calling the driver's versions and replaces them with a proper parser for each vmware driver to grab them out of VMware's configuration.

It also does this per-driver, so if someone wants to add another driver they only need to implement .HostIP and .GuestIP. If the driver they're implementing is unable to determine addressing information from the configuration, then they can implement an IPfinder/InterfaceFinder for that particular driver.

This means in ssh.go (or anything really), all one needs to do is get ahold of the driver for their vm and then call .GuestIP or .HostIP to determine the correct address for the interface (or network-mapping) the user desires. If one isn't specified by the user, then ip/interface-finding can be applied.

**Comment by icnocop** [comment] 2017-06-16 19:27
@arizvisa, thank you for the pull request. It looks like it needs to be rebased again.

**Comment by arizvisa** [comment] 2017-06-17 20:13
@icnocop, kk. i'm on it.

**Comment by arizvisa** [comment] 2017-06-17 20:42
Squashed. Just some documentation fixes. 

I also added another commit that turned the tests that expliclty rely on the existence of the VMware binaries into acceptance tests.

**Closed** 2018-02-09 21:01 UTC
Labels: bug, builder/vmware
