### ISSUE TITLE
boot_wait ignored in 1.2.3 for QEMU provider

### ISSUE THREAD

**Issue by sfinlayson-bt** [hashicorp/packer#6225] opened 2018-05-01 18:07 UTC
After upgrading to 1.2.3, boot_wait (even the default) is ignored for QEMU provider--I only use the QEMU provider, so I am not sure if it is affecting the other providers as well.  This is running on Ubuntu 16.04.4 LTS x86_64.  Logs of 1.2.2 and 1.2.3 processing the same config: https://gist.github.com/sfinlayson-bt/44adaef2ff50804c7d8ed5b0a80c3ac4

**Comment by mwhooker** [comment] 2018-05-01 18:12
Thanks, will take a look

**Comment by mwhooker** [comment] 2018-05-01 18:38
@jen20 I'm guessing this was probably introduced in #6129

**Comment by jen20** [comment] 2018-05-01 18:42
@mwhooker I think it might be simpler than that, I'm running a test now.

**Comment by jen20** [comment] 2018-05-01 19:09
Well, it's not the simple fix I was hoping for. Doing further investigation now.

**Comment by jen20** [comment] 2018-05-01 19:40
@mwhooker The issue is that RawBootWait is not being parsed correctly any more - it used to accept "2m" to mean "2 minutes", or "45s" to mean "45 seconds". `config.BootConfig.BootWait` is returning `0` regardless of input value in the QEMU builder at the moment, hence no delay.

**Comment by mwhooker** [comment] 2018-05-01 19:41
@sfinlayson-bt Thanks again for the report. This will be fixed in the next release. In the meantime, I think you should be able to add a `<wait20s>` at the beginning of your boot command to get the same effect.

**Closed** 2018-05-01 19:41 UTC
Labels: bug, builder/qemu

**Comment by jen20** [comment] 2018-05-01 19:54
That fixes it - didn't think of adding `<wait20>` though!
