### ISSUE TITLE
SSH handshake err:  unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by sathish331977** [hashicorp/packer#10994] opened 2021-05-05 12:27 UTC
#### Overview of the Issue

While building a ubuntu 18.04-LTS image with azure-arm i am running into SSH Handshake error.

#### Reproduction Steps

The image needs to be created with in a virtual network in Azure.Attached files will provide details of the builder and provider options i have used.
the ssh_username used is "packer" and password is autogenerated
### Packer version

1.7.2 [go1.16.3 linux amd64]

### Simplified Packer Buildfile
```
{
  "variables": {
    "client_key": "",
    "client_id": "",
    "subscription_id": "",
    "tenant_id": ""
  },
  "builders": [
    {
      "type": "azure-arm",
      "client_id": "{{user `client_id`}}",
      "client_secret": "{{user `client_key`}}",
      "tenant_id": "{{user `tenant_id`}}",
      "subscription_id": "{{user `subscription_id`}}",
      "build_resource_group_name": "mygroup",
      "managed_image_resource_group_name": "mygroup",
      "managed_image_name": "ocrPackerImage",
      "virtual_network_name": "dev-vnet",
      "virtual_network_subnet_name":"default",
      "virtual_network_resource_group_name":"mygroup",
	    "os_disk_size_gb": "50",
      "os_type": "Linux",
      "image_publisher": "Canonical",
      "image_offer": "UbuntuServer",
      "image_sku": "18.04-LTS",
      "ssh_username": "packer",
      "communicator": "ssh",
      "ssh_pty":"true",
      "azure_tags": {
        "App_Code1":"aabb"
      },     
      "vm_size": "standard_f2s_v2"

    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "inline": [
          "echo '%sudo    ALL=(ALL)  NOPASSWD:ALL' >> /etc/sudoers"
        ]
    },
    {
      "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E -H sh '{{ .Path }}'",
      "inline": [
        "apt-get update;apt-get install curl -y ",
        "apt-get upgrade -y -q",
		"curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash",
        "apt-get install python3-pip -y -q",
        "apt-get update",
        "pip3 install azure-batch==9.0.0 azure-keyvault-certificates azure-identity azure-keyvault-secrets azure-storage-blob==12.4.0",
		"pip3 install azure-mgmt-batch==9.0.0",
		"pip3 install six==1.12.0 pem",
        "apt-get install tesseract-ocr libtiff-tools python3-opencv zip unzip -y -q",
        "apt-get install docker.io -y -q",
        "rm -rf /var/lib/apt/lists/*",
		"/usr/sbin/waagent -force -deprovision && export HISTSIZE=0 && sync"
      ],
      "inline_shebang": "/bin/sh -x",
      "type": "shell"
    },
    {
      "type": "file",
      "source": "./scripts/",
      "destination": "/tmp"
    },
    {
      "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
      "inline": [
        "mkdir -m777 -p /home/APP/scripts",
        "cp -a /tmp/*.py /home/APP/scripts",
        "chmod -R 777 /home/APP/scripts"
        
      ],
      "inline_shebang": "/bin/sh -x",
      "type": "shell"
    }
  ]
}
```
### Operating system and Environment details

Azure Pipelines for building images using packer with a Linux 18.04 OS

### Log Fragments and crash.log files
[13.txt](https://github.com/hashicorp/packer/files/6427026/13.txt)

**Comment by SwampDragons** [comment] 2021-05-07 16:56
Hi, thanks for reaching out. If you want Packer to connect via a password you need to provide the ssh_password to the Packer config.

Hope this helps. Here's a full set of ssh communicator configuration options you can set: https://www.packer.io/docs/communicators/ssh

Since it is likely this is a getting-started issue and not a bug, I'm going to close this issue but you can try to ask on our [community forum](https://discuss.hashicorp.com/c/packer) for help if you're still stuck.

**Closed by SwampDragons** 2021-05-07 16:56 UTC
Labels: question
