### ISSUE TITLE
Waiting for instance i-xxx to become ready... 4-5 minutes

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/packer#5710] opened 2017-12-15 17:43 UTC
Packer 1.1.3
A pretty standard template for ec2

When it launches an instance in us-east-1, waiting times exceeds 4-5 minutes, even if port 22 is already available. 

Where do I look to make it connect faster?

Thanks!
Roman

**Comment by SwampDragons** [comment] 2017-12-15 17:56
This looks like a duplicate of https://github.com/hashicorp/packer/issues/5705

**Closed by SwampDragons** 2017-12-15 17:56 UTC
Labels: builder/amazon, duplicate, regression
