### ISSUE TITLE
Shell provisioner not working with ESX remote

### ISSUE THREAD

**Issue by murph571** [hashicorp/packer#6121] opened 2018-04-09 20:19 UTC
When building a Centos 7 template with remote ESX host the shell provisioner doesn't successfully upload the script to be run and eventually times out. The specific error is "scp output: scp: broken pipe"

- Packer v. 1.2.2
- Windows 10 and ESXi 6.5
- Debug log in [Gist](https://gist.github.com/murph571/4ec17ac4df912c362aac564d25256681)

**Comment by rickard-von-essen** [comment] 2018-04-10 06:35
Please supply the information requested in the issue template:
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

Please attach your Kickstart file.

**Comment by sredne** [comment] 2018-04-16 20:31
I'm getting something very similar.  However, I'm creating an Ubuntu 16.04 template with Hyper-V as my builder.

- Packer 1.2.2
- Windows 10 1607 as my builder

[Gist](https://gist.github.com/sredne/8ddb49710f1b12b501acfb097b51ee42)

Any idea?  I've setup OpenSSH on my builder box, but I'm not sure if that's the SCP it's trying to use.  I can manually copy the files over with SCP.

**Comment by fretboarder** [comment] 2018-04-17 08:27
I'm seeing exactly the same effects as @sredne when trying to build a CentOS based AMI. Build host is running Amazon Linux.

- Packer 1.2.2

**Comment by SwampDragons** [comment] 2018-05-08 18:15
Sounds like this may have been a duplicate of #6135 and was hopefully resolved with the 1.2.3 release;  please upgrade and if that doesn't resolve your issues, we'll reopen.

**Closed by SwampDragons** 2018-05-08 18:15 UTC
Labels: builder/vmware-esxi, duplicate, need-more-info, question, waiting-reply
