### ISSUE TITLE
Build 'amazon-ebs' errored: error validating regions: RequestError: send request failed caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.com on 172.31.0.2:53: no such host

### ISSUE THREAD

**Issue by yomesky2000** [hashicorp/packer#8808] opened 2020-02-28 00:05 UTC
I'm new to packer, I am trying to build a new AMI but when i run "packer build template.json" i get that error

**Comment by SwampDragons** [comment] 2020-02-28 16:33
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

Thanks!

**Comment by yomesky2000** [comment] 2020-02-29 01:26
Packer version from packer version : 1.5.4
Host platform : AWS EC2 (t2.micro)
Full debug log output from PACKER_LOG=1 packer build template.json.


2020/02/29 01:24:24 Build debug mode: false
2020/02/29 01:24:24 Force build: false
2020/02/29 01:24:24 On error:
2020/02/29 01:24:24 Preparing build: amazon-ebs
2020/02/29 01:24:24 Waiting on builds to complete...
2020/02/29 01:24:24 Starting build run: amazon-ebs
2020/02/29 01:24:24 Running builder: amazon-ebs
2020/02/29 01:24:24 [INFO] (telemetry) Starting builder amazon-ebs
2020/02/29 01:24:24 packer-builder-amazon-ebs plugin: Found region us−east−1
2020/02/29 01:24:24 packer-builder-amazon-ebs plugin: [INFO] AWS Auth provider used: "StaticProvider"
2020/02/29 01:24:24 packer-builder-amazon-ebs plugin: [INFO] (aws): No AWS timeout and polling overrides have been set.                                                                  Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between re                                                                 tries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_AT                                                                 TEMPTS to your desired values.
Build 'amazon-ebs' errored: error validating regions: RequestError: send request failed
caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.c                                                                 om on 172.31.0.2:53: no such host

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: error validating regions: RequestError: send request failed
caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.c                                                                 om on 172.31.0.2:53: no such host

==> Builds finished but no artifacts were created.
2020/02/29 01:24:24 [INFO] (telemetry) ending amazon-ebs
caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.c                                                                 om on 172.31.0.2:53: no such host
2020/02/29 01:24:24 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/02/29 01:24:24 machine readable: amazon-ebs,error []string{"error validating regions: RequestError: send request fa                                                                 iled\ncaused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazo                                                                 naws.com on 172.31.0.2:53: no such host"}

packer script:


{
"variables": {
    "aws_access_key": "xxxxxx",
    "aws_secret_key": "xxxxxxxxxxxxxx"
},
"builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us−east−1",
    "source_ami": "ami-0c322300a1dd5dc79",
    "instance_type": "t2.micro",
    "ssh_username": "RHEL 8.1",
    "ami_name": "packer"
}]
}

**Comment by SwampDragons** [comment] 2020-03-02 22:43
So just to clarify -- you're running Packer from inside an EC2 instance?  The only way I was able to reproduce this error was when I set https://packer.io/docs/builders/amazon-ebs.html#custom_endpoint_ec2. Is it possible you have some sort of config var or environment variable declaring a custom endpoint?

**Comment by nywilken** [comment] 2020-04-30 17:38
Hi @yomesky2000 I'm closing this issue since there have been no updates in the past 30 days. If this is still an problem please open a new [bug report](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) with the information requested in the template. Cheers!

**Closed by nywilken** 2020-04-30 17:38 UTC
Labels: bug, builder/amazon, need-more-info, waiting-reply
