### ISSUE TITLE
Named Builds in HCL2

### ISSUE THREAD

**Issue by AdrienneCohea** [hashicorp/packer#9246] opened 2020-05-18 05:37 UTC
#### Feature Description

The HCL2 Packer 1.5 configuration language appears not to support named builds. I would like to have that when all of my builds use the same builder, and I want to be able to differentiate between them. I would like to support a `name` field in the schema of a build, which would be an optional string. When `name` is not set by the user, the logs will show the name of the builder; for example, `googlecompute` or `amazon-ebs`. When the field is set, then logs relating to the chosen build would be labeled with that name. In this way, a user could differentiate between logs from each build without resorting to remembering colors.

#### Use Case(s)

A build could look like [this](https://gitlab.com/adriennes-runes/hashicorp/-/blob/master/build.compute.pkr.hcl):

```
build {
  name = "compute"

  sources = [
    "source.googlecompute.compute",
  ]

  provisioner "shell" {

    scripts = [
    ...
    ]
  }
}
```
And the logs in Packer would look like this:
```
compute: output will be in this color.
configuration-store: output will be in this color.
scheduler: output will be in this color.
vault_standalone: output will be in this color.
```

I have an open pull request for this with a unit test.

**Comment by sylviamoss** [comment] 2020-05-18 12:34
I believe this is a duplicate from this one https://github.com/hashicorp/packer/issues/9167.

**Comment by azr** [comment] 2020-05-19 15:29
@sylviamoss, I think they 2 different issues, the #9167 is more about allowing to change the details of a source in a build.

**Comment by azr** [comment] 2020-05-19 15:31
But it is a duplicate of https://github.com/hashicorp/packer/issues/9157 ! Anyways @AdrienneCohea I have opened #9257 to do this.

**Comment by SwampDragons** [comment] 2020-05-20 18:56
This was closed by https://github.com/hashicorp/packer/pull/9257 and will be part of the 1.6.0 release 🎉

**Closed by SwampDragons** 2020-05-20 18:56 UTC
Labels: duplicate, enhancement, hcl2
