### ISSUE TITLE
http response error: 401 - invalid content type while copying file on Azure Cloud Platform

### ISSUE THREAD

**Issue by mansing2** [hashicorp/packer#8962] opened 2020-03-27 09:58 UTC
Hi,

I'm using Builder and Provisioner to create Windows Image with a software install on it on Azure Cloud however build is getting failed while copying the file to VM being created. Error Message is: Build 'azure-arm' errored: Error uploading file to $env:TEMP\winrmcp-c3168c08-eeb0-4d5d-6130-6e0d16d68147.tmp: Couldn't create shell: http response error: 401 - invalid content type. Any help would appreciate.

```{
"builders": [{

    "type": "azure-arm",   
    "subscription_id": "<sub-id>",
    "managed_image_resource_group_name": "test-mansing",
    "managed_image_name": "New-Image-Create-By-Packer-Windows-withsoftware",    
    "os_type": "Windows",
    "image_publisher": "MicrosoftWindowsServer",
    "image_offer": "WindowsServer",
    "image_sku": "2016-Datacenter",

    "azure_tags": {
      "dept": "engineering"
    },
    "location": "West US",
    "vm_size": "Standard_A2",

    "communicator": "winrm",
    "winrm_use_ssl": "true",
    "winrm_insecure": "true",
    "winrm_timeout": "25m",
    "winrm_username": "packer"
}],
"provisioners": [{
  "type": "powershell",
    "inline": [
      " # NOTE: the following *3* lines are only needed if the you have installed the Guest Agent.",
      "  while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "  while ((Get-Service WindowsAzureTelemetryService).Status -ne 'Running') { Start-Sleep -s 5 }",
      "  while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",

      "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; Write-Output $imageState.ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Start-Sleep -s 10 } else { break } }"
  ]
},
{  "type": "file",
  "source": "StorageExplorer.exe",
  "destination": "C:/Temp/"
},
{  "type": "powershell",
  "inline": ["C:/Temp/StorageExplorer.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART"]
}]}```

**Comment by sylviamoss** [comment] 2020-03-27 13:47
Hello there! Thanks for reaching out. 
Could you please provide us a full output log when you run your build with `PACKER_LOG=1`?

**Comment by mansing2** [comment] 2020-03-27 15:42
Hi @sylviamoss - You can find the full output log as below. Thank you. 
```
C:\Terraform\Windows-Test>packer build Azure-Image.JSON
azure-arm: output will be in this color.

==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using device flow
==> azure-arm: Getting token for https://management.azure.com/
==> azure-arm: Loading auth token from file: C:\Users\shinde_mn\.azure\packer\oauth-a86abccc-7218-8899-b087-0133e8bffc53mgmt.json
==> azure-arm: Auth token found in file: C:\Users\shinde_mn\.azure\packer\oauth-a86abccc-7218-4882-b074-0133e8bffc53mgmt.json
==> azure-arm: Azure token expired. Saving the refreshed token...
==> azure-arm: Getting tokens using device flow
==> azure-arm: Getting token for Vault resource
==> azure-arm: Loading auth token from file: C:\Users\shinde_mn\.azure\packer\oauth-a86abccc-7218-4882-b087-0133e8bffc53vault.json
==> azure-arm: Auth token found in file: C:\Users\shinde_mn\.azure\packer\oauth-a86abccc-7218-4882-b087-0133e8bffc53vault.json
==> azure-arm: Azure token expired. Saving the refreshed token...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: WARNING: Zone resiliency may not be supported in West US, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2gw9c5fk8g'
==> azure-arm:  -> Location          : 'West US'
==> azure-arm:  -> Tags              :
==> azure-arm:  ->> dept : engineering
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2gw9c5fk8g'
==> azure-arm:  -> DeploymentName    : 'pkrdp2gw9c5fk8g'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2gw9c5fk8g'
==> azure-arm:  -> DeploymentName    : 'kvpkrdp2gw9c5fk8g'
==> azure-arm: Getting the certificate's URL ...
==> azure-arm:  -> Key Vault Name        : 'pkrkv2gw9c5fk8g'
==> azure-arm:  -> Key Vault Secret Name : 'packerKeyVaultSecret'
==> azure-arm:  -> Certificate URL       : 'https://pkrkv2gw9c5fk8g.vault.azure.net/secrets/packerKeyVaultSecret/7eb94c07be5b4307940cf30184c873c4'
==> azure-arm: Setting the certificate's URL ...
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2gw9c5fk8g'
==> azure-arm:  -> DeploymentName    : 'pkrdp2gw9c5fk8g'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2gw9c5fk8g'
==> azure-arm:  -> DeploymentName    : 'pkrdp2gw9c5fk8g'
==> azure-arm: Getting the VM's IP address ...
==> azure-arm:  -> ResourceGroupName   : 'packer-Resource-Group-2gw9c5fk8g'
==> azure-arm:  -> PublicIPAddressName : 'pkrip2gw9c5fk8g'
==> azure-arm:  -> NicName             : 'pkrni2gw9c5fk8g'
==> azure-arm:  -> Network Connection  : 'PublicEndpoint'
==> azure-arm:  -> IP Address          : '138.91.165.162'
==> azure-arm: Waiting for WinRM to become available...
    azure-arm: WinRM connected.
==> azure-arm: #< CLIXML
==> azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Connected to WinRM!
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: C:\Users\SHINDE~1\AppData\Local\Temp\powershell-provisioner057865367
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE
==> azure-arm: Uploading StorageExplorer.exe => C:/Temp/
==> azure-arm: Upload failed: Error uploading file to $env:TEMP\winrmcp-3c82a482-9eec-4442-7437-906cc507efa9.tmp: Couldn't create shell: http response error: 401 - invalid content type
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: Removing the created Deployment object: 'pkrdp2gw9c5fk8g'
==> azure-arm: Removing the created Deployment object: 'kvpkrdp2gw9c5fk8g'
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Error deleting resource group.  Please delete it manually.
==> azure-arm:
==> azure-arm: Name: packer-Resource-Group-2gw9c5fk8g
==> azure-arm: Error: Future#WaitForCompletion: context has been cancelled: StatusCode=202 -- Original Error: context deadline exceeded
Build 'azure-arm' errored: Error uploading file to $env:TEMP\winrmcp-3c82a482-9eec-4442-7437-906cc507efa9.tmp: Couldn't create shell: http response error: 401 - invalid content type

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Error uploading file to $env:TEMP\winrmcp-3c82a482-9eec-4442-7437-906cc507efa9.tmp: Couldn't create shell: http response error: 401 - invalid content type

==> Builds finished but no artifacts were created.
```

**Comment by goldstar611** [comment] 2020-03-27 18:45
I'm not sure if this is related but I was receiving 401 Invalid Content Type (using VMWare Workstation locally) until I configured autologon in my Autounattend.xml file. I'm following to see if there's a better way than autologon.

**Comment by SwampDragons** [comment] 2020-03-27 20:29
Hi, thanks for reaching out.

This looks to me like an issue with the powershell command you are running; I think you are kicking off a sysprep that causes reboots, and then the machine is rebooting when you try to upload the file. Deleting the powershell command causes the upload to work again. 

We have a windows-restart provisioner that you can use to wait for reboots to complete. I suspect that you'll need to set the "check_registry" and "timeout" options. 

Since losing connectivity is something being caused by your own provisioning and isn't the result of a bug in Packer, I'm going to close this. If you need help getting sysprep to work I suggest you reach out to the https://groups.google.com/forum/#!forum/packer-tool google group or the HashiCorp discuss platform for help. 

Thanks!

**Closed by SwampDragons** 2020-03-27 20:29 UTC
Labels: bug, builder/azure
