### ISSUE TITLE
unknown configuration key: "floppy_dirs"

### ISSUE THREAD

**Issue by jamiesonbc** [hashicorp/packer#5598] opened 2017-11-17 16:28 UTC
[root@packer-qa ~/opt/packer/bin]# ./windows_test.sh
sod-windows_server_standard_core_2016-bcb4d478-week46-17-1055 output will be in this color.

1 error(s) occurred:

* unknown configuration key: "floppy_dirs"

THIS WORKS ON WINDOWS server running 1.1 with same json file

root@packer-qa ~/opt/packer/bin]# packer -v
1.1.2

[root@packer-qa ~/opt/packer/packer-templates-nxs]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

https://gist.github.com/jamiesonbc/3a9a5e2cb6229e8ffb38227545194348

**Comment by SwampDragons** [comment] 2017-11-17 16:57
Sorry 'bout this -- the good news is this ticket is a duplicate and the root cause is already fixed on master.  If you want to use other features in packer 1.1.2 please try out the dev binary I uploaded here https://github.com/hashicorp/packer/issues/5589#issuecomment-345035161; otherwise you can downgrade until we release the fix.

**Comment by jamiesonbc** [comment] 2017-11-17 18:57
That dev binary is for windows only .  the problem I’m having is building a windows template on packer running on centos ( pasted that in my original issue ).  Do you have a “fixed” binary for linux?
[cid:image001.png@01D35FA3.889F0FF0]
[cid:image002.png@01D35FA3.889F0FF0]

 Bryan C. Jamieson
 Senior Systems Engineer
 THD Austin Technology Center North
 13011 McCallen Pass
  Austin, Tx 78753
  W:  737-931-8627   C:  512-221-8906
  Email:  Bryan_Jamieson@homedepot.com<mailto:Bryan_Jamieson@homedepot.com>

**Comment by jamiesonbc** [comment] 2017-11-17 20:43
Please reopen.   the dev binary you mentioned was for windows.  I needed one for linux.  I believe you said the fix was in master.   I downloaded and recompiled a new version
[root@packer-qa ~/opt/packer/bin]# ./packer -v
1.1.3
[root@packer-qa ~/opt/packer/bin]# /usr/sbin/packer -v
1.1.3

[root@packer-qa ~/opt/packer/bin]# ./windows_server_standard_core_2016_build.sh
From https://oses.homedepot.com/ose-build/packer-templates-nxs
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
Already on 'windows'
Your branch is ahead of 'origin/windows' by 9 commits.
  (use "git push" to publish your local commits)
From https://oses.homedepot.com/ose-build/packer-templates-nxs
 * branch            windows    -> FETCH_HEAD
Already up-to-date.
# On branch windows
# Your branch is ahead of 'origin/windows' by 9 commits.
#   (use "git push" to publish your local commits)
#
nothing to commit, working directory clean
sod-windows_server_standard_core_2016-71e01b70-week46-17-1543 output will be in this color.

1 error(s) occurred:

* unknown configuration key: "floppy_dirs"

**Comment by jamiesonbc** [comment] 2017-11-17 20:46
I have added a new comment to the issue which was closed, can you reopen it.

Please reopen. the dev binary you mentioned was for windows. I needed one for linux. I believe you said the fix was in master. I downloaded and recompiled a new version
[root@packer-qa ~/opt/packer/bin]# ./packer -v
1.1.3
[root@packer-qa ~/opt/packer/bin]# /usr/sbin/packer -v
1.1.3
[root@packer-qa ~/opt/packer/bin]# ./windows_server_standard_core_2016_build.sh
From https://oses.homedepot.com/ose-build/packer-templates-nxs

  *   branch HEAD -> FETCH_HEAD
Already up-to-date.
Already on 'windows'
Your branch is ahead of 'origin/windows' by 9 commits.
(use "git push" to publish your local commits)
From https://oses.homedepot.com/ose-build/packer-templates-nxs
  *   branch windows -> FETCH_HEAD
Already up-to-date.
On branch windows
Your branch is ahead of 'origin/windows' by 9 commits.
(use "git push" to publish your local commits)
nothing to commit, working directory clean
sod-windows_server_standard_core_2016-71e01b70-week46-17-1543 output will be in this color.
1 error(s) occurred:



[cid:image001.png@01D35FB2.D8A22A00]
[cid:image002.png@01D35FB2.D8A22A00]

 Bryan C. Jamieson
 Senior Systems Engineer
 THD Austin Technology Center North
 13011 McCallen Pass
  Austin, Tx 78753
  W:  737-931-8627   C:  512-221-8906
  Email:  Bryan_Jamieson@homedepot.com<mailto:Bryan_Jamieson@homedepot.com>


From: Bryan Jamieson <BRYAN_JAMIESON@homedepot.com>
Date: Friday, November 17, 2017 at 12:56 PM
To: hashicorp/packer <reply@reply.github.com>
Cc: Author <author@noreply.github.com>, "Lane, Larry" <LARRY_LANE@homedepot.com>
Subject: Re: [EXTERNAL] Re: [hashicorp/packer] unknown configuration key: "floppy_dirs" (#5598)

That dev binary is for windows only .  the problem I’m having is building a windows template on packer running on centos ( pasted that in my original issue ).  Do you have a “fixed” binary for linux?
[cid:image003.png@01D35FB2.D8A22A00]
[cid:image004.png@01D35FB2.D8A22A00]

 Bryan C. Jamieson
 Senior Systems Engineer
 THD Austin Technology Center North
 13011 McCallen Pass
  Austin, Tx 78753
  W:  737-931-8627   C:  512-221-8906
  Email:  Bryan_Jamieson@homedepot.com<mailto:Bryan_Jamieson@homedepot.com>

**Comment by SwampDragons** [comment] 2017-11-20 17:41
Sure -- here's the linux version, uploaded as a zipfile because github won't allow binaries.
[packer.zip](https://github.com/hashicorp/packer/files/1488574/packer.zip)

**Comment by SwampDragons** [comment] 2017-11-20 17:43
BTW -- I edited your comments a little to remove the email gobbledygook from the issue on github.

**Comment by jamiesonbc** [comment] 2017-11-22 14:27
I had downloaded the master branch and recompiled for linux.  It still had the same error.   Should the fix have been in the master branch?  Is the packer.zip file you sent me from a development branch?

[cid:image001.png@01D3636B.BE208890]
[cid:image002.png@01D3636B.BE208890]

 Bryan C. Jamieson
 Senior Systems Engineer
 THD Austin Technology Center North
 13011 McCallen Pass
  Austin, Tx 78753
  W:  737-931-8627   C:  512-221-8906
  Email:  Bryan_Jamieson@homedepot.com<mailto:Bryan_Jamieson@homedepot.com>

**Comment by jamiesonbc** [comment] 2017-11-22 15:29
STILL GET SAME ERROR WITH PROVIDED LINUX BINARY.

@thd_bryanj
[root@packer-qa ~/opt/packer/bin]# cksum packer
203618676 85233216 packer

[root@packer-qa ~/opt/packer/bin]# cksum /tmp/swampdragons/packer
3180486763 82900905 /tmp/swampdragons/packer

[root@packer-qa ~/opt/packer/bin]# cp /tmp/swampdragons/packer ./packer_1.1.3_swampdragons

[root@packer-qa ~/opt/packer/bin]# rm packer

[root@packer-qa ~/opt/packer/bin]# ln -s /opt/packer/bin/packer_1.1.3_swampdragons packer

[root@packer-qa ~/opt/packer/bin]# cksum packer
3180486763 82900905 packer

[root@packer-qa ~/opt/packer/bin]# grep json /tmp/windows_server_standard_core_2016_build.sh
JSON_TEMPLATE="packer-templates-nxs/windows_server_standard_core_2016/templates/ServerBase2016-QA.json"

[root@packer-qa ~/opt/packer/bin]# grep floppy ../packer-templates-nxs/windows_server_standard_core_2016/templates/ServerBase2016-QA.json
        "floppy_dirs": [
            "{{user `path` }}/floppy/*"
        ],

STILL GET SAME ERROR

[root@packer-qa ~/opt/packer/bin]# /tmp/windows_server_standard_core_2016_build.sh
sod-windows_server_standard_core_2016-c04addae-week47-22-1023 output will be in this color.
1 error(s) occurred:

  *   unknown configuration key: "floppy_dirs"


[cid:image001.png@01D36374.721AEE00]
[cid:image002.png@01D36374.721AEE00]

 Bryan C. Jamieson
 Senior Systems Engineer
 THD Austin Technology Center North
 13011 McCallen Pass
  Austin, Tx 78753
  W:  737-931-8627   C:  512-221-8906
  Email:  Bryan_Jamieson@homedepot.com<mailto:Bryan_Jamieson@homedepot.com>

**Comment by SwampDragons** [comment] 2017-11-28 01:19
Can you share a gist of the entire log with `PACKER_LOG=1` set in your environment?

**Comment by SwampDragons** [comment] 2017-11-28 01:21
That error looks like it's occurring in the decode section, which is strange -- I don't remember it changing any time recently.  Will investigate more.

**Comment by jamiesonbc** [comment] 2017-11-28 14:28
new gist for log file created  "log file for unknown configuration key: "floppy_dirs" #5598" https://gist.github.com/jamiesonbc/157f2a6a9ceb2a59c2ba4482315d094d

**Comment by jamiesonbc** [comment] 2017-11-28 14:29
new gist for log file created "log file for unknown configuration key: "floppy_dirs" #5598<https://github.com/hashicorp/packer/issues/5598>" https://gist.github.com/jamiesonbc/157f2a6a9ceb2a59c2ba4482315d094d


[cid:image001.png@01D36822.F8CA4A60]
[cid:image002.png@01D36822.F8CA4A60]

 Bryan C. Jamieson
 Senior Systems Engineer
 THD Austin Technology Center North
 13011 McCallen Pass
  Austin, Tx 78753
  W:  737-931-8627   C:  512-221-8906
  Email:  Bryan_Jamieson@homedepot.com<mailto:Bryan_Jamieson@homedepot.com>

**Comment by rickard-von-essen** [comment] 2017-11-28 14:52
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the [**note** about upgrading from < 0.9.0.](https://github.com/hashicorp/packer/commit/1994793126f948dd99c8acdd35f999df0c6ab342)_

**Closed by rickard-von-essen** 2017-11-28 14:52 UTC
Labels: regression, windows-host
