### ISSUE TITLE
Packer crash

### ISSUE THREAD

**Issue by groupvrg** [hashicorp/packer#7876] opened 2019-07-16 00:16 UTC
Packer crash when i added an azure cli command as a shell inline command in the post-processor section. Oddly, the crash did not happen when i added the same command in the provisioner section. I cannot keep it in the provisioner section due to some dependencies with the image being built.

I am not uploading the full crash.log file, since it shows subscription values in plain test. I have however put up the crash info at the end of the log, in the gist link given below.

- Packer version from `packer version`
1.4.2
Host platform - 
 uname -a
Linux jenkins-01 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

https://gist.github.com/groupvrg/30b47828e91a554a629546a18c22e865

When i run the same inline commands in the provisioners section, i see this -:

Part of the json that triggered the issue -: 
```
"post-processors":[
        {
            "inline": [
               "echo az sig image-version create --resource-group {{user `az_shrd_resource_group`}}  --gallery-name {{user `az_shrd_gallery_name`}}  --gallery-image-definition {{user `az_shrd_gallery_img_dfn`}}    --gallery-image-version 0.0.{{user `build_number`}} --target-regions eastasia southeastasia centralus eastus eastus2 westus northcentralus southcentralus northeurope westeurope japanwest japaneast brazilsouth australiaeast australiasoutheast southindia centralindia westindia canadacentral canadaeast uksouth ukwest westcentralus westus2 koreacentral koreasouth francecentral southafricanorth southafricawest --replica-count 1 --managed-image \/subscriptions\/{{user `az_subscription_id`}}\/resourceGroups\/{{user `az_resource_group`}}\/providers\/Microsoft.Compute\/images\/test-cbn-base-image-{{user `build_number`}} -l westus2",

               "az sig image-version create --resource-group {{user `az_shrd_resource_group`}}  --gallery-name {{user `az_shrd_gallery_name`}}  --gallery-image-definition {{user `az_shrd_gallery_img_dfn`}}    --gallery-image-version 0.0.{{user `build_number`}} --target-regions eastasia southeastasia centralus eastus eastus2 westus northcentralus southcentralus northeurope westeurope japanwest japaneast brazilsouth australiaeast australiasoutheast southindia centralindia westindia canadacentral canadaeast uksouth ukwest westcentralus westus2 koreacentral koreasouth francecentral  --replica-count 1 --managed-image \/subscriptions\/{{user `az_subscription_id`}}\/resourceGroups\/{{user `az_resource_group`}}\/providers\/Microsoft.Compute\/images\/test-cbn-base-image-{{user `build_number`}} -l westus2"
            ],

            "type": "shell-local",
            "inline_shebang": "/bin/bash -e",
            "only":["azure"]
        }
]
```

**Comment by SwampDragons** [comment] 2019-07-16 17:28
Is your Packer host platform running inside of Azure?

**Comment by SwampDragons** [comment] 2019-07-16 17:35
We ask for full logs because the crash info by itself isn't very useful unless we know where the crash happened. Can you at least share a couple of log lines preceeding the crash with any sensitive information removed?

**Comment by groupvrg** [comment] 2019-07-16 18:43
The Packer host Platform is running inside GCP.

Logs from the jenkins console. Will this do ?

+ packer build jenkins/packer/azure_only.json
[1;32mazure output will be in this color.[0m

[1;32m==> azure: Running builder ...[0m
[1;32m==> azure: Getting tokens using client secret[0m
[0;32m    azure: Creating Azure Resource Manager (ARM) client ...[0m
[1;32m==> azure: WARNING: Zone resiliency may not be supported in West US 2, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/[0m
[1;32m==> azure: Creating resource group ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> Location          : 'West US 2'[0m
[1;32m==> azure:  -> Tags              :[0m
[1;32m==> azure: Validating deployment template ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> DeploymentName    : 'pkrdp9owu76drpw'[0m
[1;32m==> azure: Deploying deployment template ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> DeploymentName    : 'pkrdp9owu76drpw'[0m
[1;32m==> azure: Getting the VM's IP address ...[0m
[1;32m==> azure:  -> ResourceGroupName   : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> PublicIPAddressName : 'pkrip9owu76drpw'[0m
[1;32m==> azure:  -> NicName             : 'pkrni9owu76drpw'[0m
[1;32m==> azure:  -> Network Connection  : 'PublicEndpoint'[0m
[1;32m==> azure:  -> IP Address          : '51.141.164.209'[0m
[1;32m==> azure: Waiting for SSH to become available...[0m
[1;32m==> azure: Connected to SSH![0m
[1;32m==> azure: Provisioning with shell script: /tmp/packer-shell491919124[0m
[0;32m    azure: doing something...[0m
[1;32m==> azure: Provisioning with shell script: /tmp/packer-shell518173864[0m
[0;32m    azure: lrwxrwxrwx 1 root root 39 May 22  2018 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf[0m
[0;32m    azure: WARNING! The waagent service will be stopped.[0m
[0;32m    azure: WARNING! Cached DHCP leases will be deleted.[0m
[0;32m    azure: WARNING! root password will be disabled. You will not be able to login as root.[0m
[0;32m    azure: WARNING! /etc/resolv.conf will be deleted.[0m
[0;32m    azure: WARNING! packer account and entire home directory will be deleted.[0m
[0;32m    azure: /etc[0m
[1;31m==> azure: sudo: unable to resolve host localhost.localdomain: Resource temporarily unavailable[0m
[0;32m    azure: lrwxrwxrwx 1 root root 39 Jul 15 22:27 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf[0m
[1;32m==> azure: Running local shell script: /tmp/packer-shell153641273[0m
[1;32m==> azure: Querying the machine's properties ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> ComputeName       : 'cbn-img-235'[0m
[1;32m==> azure:  -> Managed OS Disk   : '/subscriptions/****/resourceGroups/temp-image-resource-group-235/providers/Microsoft.Compute/disks/pkros9owu76drpw'[0m
[1;32m==> azure: Querying the machine's additional disks properties ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> ComputeName       : 'cbn-img-235'[0m
[1;32m==> azure: Powering off machine ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> ComputeName       : 'cbn-img-235'[0m
[1;32m==> azure: Capturing image ...[0m
[1;32m==> azure:  -> Compute ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure:  -> Compute Name              : 'cbn-img-235'[0m
[1;32m==> azure:  -> Compute Location          : 'West US 2'[0m
[1;32m==> azure:  -> Image ResourceGroupName   : 'cbn-base-image'[0m
[1;32m==> azure:  -> Image Name                : 'test-cbn-base-image-235'[0m
[1;32m==> azure:  -> Image Location            : 'westus'[0m
[1;32m==> azure: Deleting resource group ...[0m
[1;32m==> azure:  -> ResourceGroupName : 'temp-image-resource-group-235'[0m
[1;32m==> azure: 
==> azure: The resource group was created by Packer, deleting ...[0m
[1;32m==> azure: Deleting the temporary OS disk ...[0m
[1;32m==> azure:  -> OS Disk : skipping, managed disk was used...[0m
[1;32m==> azure: Deleting the temporary Additional disk ...[0m
[1;32m==> azure:  -> Additional Disk : skipping, managed disk was used...[0m
[1;31mBuild 'azure' errored: unexpected EOF[0m

==> Some builds didn't complete successfully and had errors:
--> azure: unexpected EOF

==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is nil, not string
2019/07/15 22:38:31 packer: 
2019/07/15 22:38:31 packer: goroutine 113 [running]:
2019/07/15 22:38:31 packer: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc000320600, 0x3c5b160, 0xc000094440, 0x3c732a0, 0xc000443f80, 0x3bfaf00, 0xc0003d6570, 0x0, 0x0, 0x0, ...)
2019/07/15 22:38:31 packer: 	/Users/mmarsh/Projects/packer/builder/azure/arm/builder.go:305 +0x4384
2019/07/15 22:38:31 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc0003c82d0, 0x1, 0xc000384070, 0x0, 0x0)
2019/07/15 22:38:31 packer: 	/Users/mmarsh/Projects/packer/packer/rpc/builder.go:109 +0x231
2019/07/15 22:38:31 packer: reflect.Value.call(0xc000426240, 0xc0003680f0, 0x13, 0x36aa961, 0x4, 0xc0000bef18, 0x3, 0x3, 0xc000094480, 0xc0000256e8, ...)
2019/07/15 22:38:31 packer: 	/usr/local/go/src/reflect/value.go:447 +0x461
2019/07/15 22:38:31 packer: reflect.Value.Call(0xc000426240, 0xc0003680f0, 0x13, 0xc000025718, 0x3, 0x3, 0xc0002242a0, 0xc000025730, 0x404e35)
2019/07/15 22:38:31 packer: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2019/07/15 22:38:31 packer: net/rpc.(*service).call(0xc00033cf00, 0xc0004540f0, 0xc000384be8, 0xc000384bf0, 0xc000418180, 0xc00000cc40, 0x2c84720, 0xc00038406c, 0x18a, 0x2be05c0, ...)
2019/07/15 22:38:31 packer: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2019/07/15 22:38:31 packer: created by net/rpc.(*Server).ServeCodec
2019/07/15 22:38:31 packer: 	/usr/local/go/src/net/rpc/server.go:481 +0x42b
2019/07/15 22:38:31 /opt/packer/1.4.2/packer: plugin process exited
2019/07/15 22:38:31 [INFO] (telemetry) ending azure-arm
2019/07/15 22:38:31 ui error: [1;31mBuild 'azure' errored: unexpected EOF[0m
2019/07/15 22:38:31 machine readable: error-count []string{"1"}
2019/07/15 22:38:31 ui error: 
==> Some builds didn't complete successfully and had errors:
2019/07/15 22:38:31 machine readable: azure,error []string{"unexpected EOF"}
2019/07/15 22:38:31 ui error: --> azure: unexpected EOF
2019/07/15 22:38:31 ui: 
==> Builds finished but no artifacts were created.
2019/07/15 22:38:31 [INFO] (telemetry) Finalizing.
2019/07/15 22:38:31 waiting for all plugin processes to complete...
2019/07/15 22:38:31 /opt/packer/1.4.2/packer: plugin process exited
2019/07/15 22:38:31 /opt/packer/1.4.2/packer: plugin process exited
2019/07/15 22:38:31 /opt/packer/1.4.2/packer: plugin process exited
2019/07/15 22:38:31 /opt/packer/1.4.2/packer: plugin process exited
2019/07/15 22:38:31 /opt/packer/1.4.2/packer: plugin process exited

**Comment by SwampDragons** [comment] 2019-07-16 20:16
Yes, thanks for supplying that. Based on the context of where the crash is occurring, and the form it's taking, I'm pretty sure this is a duplicate of https://github.com/hashicorp/packer/issues/7816, solved in https://github.com/hashicorp/packer/pull/7837 and already merged with the master branch.

Binaries containing the patch that solved this can be found here: https://circleci.com/gh/hashicorp/packer/6821#artifacts/containers/0

I'm going to close this issue since I believe it has already been fixed, but if the above binaries still contain an issue for you, we can reopen and continue to investigate.  Thanks for reaching out!

**Closed by SwampDragons** 2019-07-16 20:16 UTC
Labels: bug, builder/azure, post-processor/shell-local

**Comment by groupvrg** [comment] 2019-07-17 01:55
FYI, i tried out the binary with the patch and it solved the crash issue i saw. Thanks.
