### ISSUE TITLE
Packer 1.4.0 hangs while installing ansible-2.7.10 into a python virtualenv using pip

### ISSUE THREAD

**Issue by AndrewCi** [hashicorp/packer#7529] opened 2019-04-18 18:24 UTC
**SUMMARY:**
Packer 1.4.0 hangs while installing ansible-2.7.10 into a python virtualenv using pip, the Packer EBS builder, and shell provisioner. The same template and builder works on Packer 1.3.5. This is on Windows 10 64-bit. 

**SAMPLE TEMPLATE/LOGS:**
https://gist.github.com/AndrewCi/3d768238412885a8e48cf4f4a58e56ea

**Comment by SwampDragons** [comment] 2019-04-18 20:22
Thanks!

**Comment by SwampDragons** [comment] 2019-04-18 21:20
I can't reproduce from my osx machine; the download takes a couple of seconds and then succeeds. Gonna try in my windows VM.

**Comment by SwampDragons** [comment] 2019-04-18 21:41
Can't reproduce on my 64 bit windows vm either.

**Comment by SwampDragons** [comment] 2019-04-18 21:47
In the logs you shared, you're sending an interrupt about a minute after the last timestamp Packer logs. What behavior do you see if you don't send the interrupt? does it hang for minutes/hours/more?  Does it return with an EOF error?

**Comment by AndrewCi** [comment] 2019-04-18 21:55
It hung for 30 minutes before I exited. I've tried multiple times for 10-15 minutes to no avail. It doesn't crash when I exit. When I manually logged into the server while the build was hanging I was able to verify that ansible was downloaded and installed properly. For some reason it's not sending a signal back to packer. 

On 1.3.5 it takes less than a minute to run successfully. 

Is anyone able to replicate on a physical windows 10 machine?

**Comment by SwampDragons** [comment] 2019-04-18 21:59
I'll ask around and see if I can get someone to run the repro on a physical box. 

Meanwhile, is there anything special about your source ami?  I'm just using the default centos7 one provided by centos.

**Comment by AndrewCi** [comment] 2019-04-18 22:44
Amazon Linux 1 AMI

**Comment by SwampDragons** [comment] 2019-04-18 22:46
okay lemme try with that one instead.

**Comment by SwampDragons** [comment] 2019-04-18 23:22
That didn't do it. Gonna read some code and see if I can come at this from a different angle without repro, for now.

**Comment by iwanchiyou** [comment] 2019-04-22 11:28
> It hung for 30 minutes before I exited. I've tried multiple times for 10-15 minutes to no avail. It doesn't crash when I exit. When I manually logged into the server while the build was hanging I was able to verify that ansible was downloaded and installed properly. For some reason it's not sending a signal back to packer.
> 
> On 1.3.5 it takes less than a minute to run successfully.
> 
> Is anyone able to replicate on a physical windows 10 machine?

Hangs for hours with v1.4.0, works fine with v1.3.5 .

MacOS
Amazon Linux 2 AMI
EBS
shell builder : pip install ansible==2.7.10 or 2.5.0

**Comment by SwampDragons** [comment] 2019-04-22 19:14
Thanks for the secondary confirmation. That fact that it's happening for you on MacOS means that it isn't because of the windows host, which is hopefully good news for getting a repro. It's interesting to me that both of you are experiencing this on Amazon Linux AMIs.

**Comment by azr** [comment] 2019-04-23 16:36
Hello there I tried to repro on my windows machine but couldn't.
Just to check could you please try it without the `--progress-bar pretty` option ???

Also, are you using a specific terminal ? Or a CI term ?

**Comment by AndrewCi** [comment] 2019-04-23 17:07
I tried without `--progress-bar pretty` and it still did not work. I am using cmder with admin privileges on Windows 10.

**Comment by eak12913** [comment] 2019-04-23 17:39
I'm having a similar issue but not related to ansible.

Packer template is building an AMI based on Amazon Linux
Packer version: `1.4.0`
OS: MacOS (locally) or Linux (running in CircleCI)

In my case the packer build is executing a shell script that's running a maven command to package a bunch of jars into a "fat jar".  Re-running this halts at the same point each time.

The same packer build completes without issues on an earlier version of packer (in my case I had a local install of `1.2.3`).

One thing that I've noticed is that with packer `1.4.0` the handling of the log output has changed such that now _all_ updates to the screen are being printed. Before, certain progress updates would update in place.

See at the end for log samples from `1.2.3` vs `1.4.0`. Note that `\r` character is now printed where as before it was used in formatting.

I'm not sure if this difference in logging is relevant here or not, but it's a difference that I've observed.  If you think this requires its own issue I'll be happy to re-post this separately but it seemed related.

======Example Logs Below======
For example before: (`v1.2.3`) 
```
    amazon-linux-ami: Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/lucene/lucene-core/3.6.0/lucene-core-3.6.0.jar (1.5 MB at 1.1 MB/s)
    amazon-linux-ami: Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-route53/1.11.128/aws-java-sdk-route53-1.11.128.jar
    amazon-linux-ami: Downloaded from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-servicecatalog/1.11.128/aws-java-sdk-servicecatalog-1.11.128.jar (604 kB at 402 kB/s)
    amazon-linux-ami: Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-s3/1.11.128/aws-java-sdk-s3-1.11.128.jar
```

After (`v1.4.0`):
```
aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (212/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (217/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (221/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (225/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (229/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (233/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (237/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (114/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\rProgress (5): aws-java-sdk-servicecatalog-1.11.128.jar (237/604 kB) | aws-java-sdk-servermigration-1.11.128.jar (173 kB) | aws-java-sdk-route53-1.11.128.jar (122/912 kB) | aws-java-sdk-storagegateway-1.11.128.jar (77/760 kB) | aws-java-sdk-simpleworkflow-1.11.128.jar (171/848 kB)\r
```

**Comment by SwampDragons** [comment] 2019-04-23 17:47
@eak12913 would you be willing to download Packer [v1.3.5](https://releases.hashicorp.com/packer/1.3.5/) and let us know if you're seeing the same behavior there as you were in 1.2.3?

**Comment by eak12913** [comment] 2019-04-23 17:53
@SwampDragons, sure thing. Running with `1.3.5` right now. Update shortly.

**Comment by eak12913** [comment] 2019-04-23 18:00
I'm able to build the template successfully `1.3.5`.  I'm also not seeing any of the formatting issues I described above with `1.3.5`.

**Comment by SwampDragons** [comment] 2019-04-23 18:07
Awesome, that helps confirm this may be the same issue. Thanks.

**Comment by SwampDragons** [comment] 2019-04-23 18:47
I'm still struggling to reproduce any of your cases, which is a big bummer. That said, my gut instinct is that this is related to the tty changes we made between v1.3.5 and v1.4.0.  @azr has already made some changes that need to be merged with the master branch.  It's not a direct correlation because those were made to prevent panics, and it's a bit of a shot in the dark, but could any of you test to see if your bug has already been resolved in that patch?

You can find some builds here: https://github.com/hashicorp/packer/pull/7517#issuecomment-485927827

If that doesn't work, I'll see if I can create a binary with some extra logging that you can use in your environments to help us narrow things down.

**Comment by eak12913** [comment] 2019-04-23 19:03
I just tried with the `1.4.1` patch build that you recommended above and I'm sorry to say that it halts just like `1.4.0` :-/

Happy to try a version with extra debugging info turned on if that will help narrow things down.

**Comment by SwampDragons** [comment] 2019-04-23 19:39
😭 

Thanks. I'll try to come up with something today.

**Comment by blackophelia** [comment] 2019-04-24 01:45
I've just come across exactly the same issue, but on centos 7.

**Comment by SwampDragons** [comment] 2019-04-24 18:31
@eak12913 I want to dig into some of those formatting issues; can you share the bit of your packer config that's creating those jars and producing the malformed logs?

**Comment by eak12913** [comment] 2019-04-25 12:54
@SwampDragons I will try to share the essence below - the reason I haven't shared already is because we essentially have a shell executor that's calling other scripts and _those_ scripts are pulling yet more scripts from private GitHub repos. All that machinery isn't where we're hanging but it's making it tricky to come up with a simple, stand-alone example :-(

Here's the high level that you can try to throw into a packer template and see if you can repro:
1. I specified the filter for base AMI in another comment above.
1. I have one shell provisioner that does some routine installation of packages/cleaning
```
{
    "type": "shell",
    "only": ["amazon-linux-ami"],
    "inline": "sudo yum update -y && sudo yum install -y jq curl nc && sudo yum clean all && sudo rm -rf /var/cache/yum/*",
    "pause_before": "30s"
  }
```
3. [Install Maven](https://gist.github.com/eak12913/6aaf525326182b2be592f0724dbcb3d2)
1. Here's the [POM file](https://gist.github.com/eak12913/beaa3c458945615c9069ca566209c193) that's packaging up the JARs (Note: replace __EXHIBITOR_VERSION__ with some actual version that they have): 
1. Run: `mvn clean package -X -e -f "$maven_pom_path"` <--- I experience a hang somewhere mid way through and this is where I start seeing the weird console output.

You may have to do a little bit of massaging of the instructions above, but I believe that's the distilled information.

**Comment by glucas** [comment] 2019-04-25 19:27
I'm also seeing a shell provisioner hang with packer 1.4.0 that does not happen with 1.3.5 -- seems similar to situation described above:

 - I'm running packer on Windows, building an Amazon Linux AMI.
 - We have two shell provisioners with inline scripts. The first does some yum install stuff; the second extracts some zips and runs some additional scripts to configure some software.
 - The second provisioner completes its script and then everything hangs for as long as I've been willing to wait. 
 - Rolling back to packer 1.3.5 and re-running, things work fine.

**Comment by SwampDragons** [comment] 2019-04-26 23:31
I think this is fixed in #7579, and I've attached binaries to that PR for folks to test. Would love feedback!

**Comment by AndrewCi** [comment] 2019-04-28 20:19
Your PR fixes this issue for me on Windows 10.

**Comment by alecrajeev** [comment] 2019-04-29 02:20
Thanks @SwampDragons! I was running into a similar issue with packer 1.4.0. I'm going to give your PR a try and will report back

**Closed** 2019-04-29 18:03 UTC
Labels: provisioner/shell, regression

**Comment by SteveClement** [comment] 2019-05-09 06:49
+1 on this issue when installing other pip packages. 1.4.1 fixes that too.
