### ISSUE TITLE
RFE: Support running a 'cleanup' script on VMs/Instances prior to shutdown

### ISSUE THREAD

**Issue by tremble** [hashicorp/packer#7383] opened 2019-03-07 08:22 UTC
We would like to *always* (think finally from the try/catch/finally pattern) try to run a "final" provisioner step on our instances prior to running the shutdown / cleanup steps.

As part of our image build process we register/subscribe our Instances/VMs to Satellite so that we can install packages.  When a build fails for some reason this can then result in 'subscribed' instances which no longer exist.  We would like to be able to run a final provisioner step which we can then use to unregister prior to shutting down and destroying the Instance/VM.  The image build should still count as 'failed' if a previous provisioner failed, and failure of this provisioner would be no different to any other provisioner failing, but would give us a way to cleanly fail instead of eating up entitlements that have to be manually cleaned up.

**Comment by SwampDragons** [comment] 2019-03-07 17:57
Thanks for opening. I _think_ this is a duplicate of #6760, so I'm going to close this to keep the conversation there. I'll add your post comment to that issue so that we have a clear record of your use case.

**Closed by SwampDragons** 2019-03-07 17:57 UTC
