### ISSUE TITLE
Packer Crash

### ISSUE THREAD

**Issue by ErikEvenson** [hashicorp/packer#7535] opened 2019-04-19 17:27 UTC
crash.log: https://gist.github.com/ErikEvenson/e55439740f44d8ef590e41877e976732

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SwampDragons** [comment] 2019-04-19 17:40
Thanks for reaching out! Sorry for this regression. I believe this is a duplicate of https://github.com/hashicorp/packer/issues/7505, and fixed in https://github.com/hashicorp/packer/pull/7509.  If you'd like binaries that include that patch, you can find them on the issue in 7509.

**Comment by ErikEvenson** [comment] 2019-04-19 17:42
Thank-you!

**Closed** 2019-04-22 23:53 UTC
Labels: crash, duplicate
