### ISSUE TITLE
Improve error message for bad SSH credentials

### ISSUE THREAD

**Issue by cocowalla** [hashicorp/packer#8161] opened 2019-09-26 19:28 UTC
#### Feature Description
I just spent 2 days tearing my hair out, wondering why I couldn't get Packer to SSH into a kickstarted CentOS VM - turned out to be my fault, as I'd transposed the `ssh_username` and `ssh_password`!

The log produced by Packer said this:

```
[DEBUG] handshaking with SSH
[DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

Because it mentions a handshake failure, I presumed it was some kind of ciphersuite negotiation issue, or perhaps a networking problem. While the issue was entirely my fault, it would be nice it Packer gave me a meaningful error message.

The request I'm making is for Packer to output a more relevant error message, such as `access denied for {USERNAME}`, or `server at 192.168.0.63 didn't access password for {USERNAME}`, or `SSH server at 192.168.0.63 rejected Password credential for {USERNAME}`.

**Comment by SwampDragons** [comment] 2019-09-26 23:24
Thanks for reaching out! I think this is a duplicate of #5107, which has had a WIP PR open for almost a year but hasn't gotten much love recently. I'll see if I can make some time to pick up that PR over in the next few weeks, but in the meantime I'm going to close this issue as a duplicate and track the issue on the original one.

**Comment by cocowalla** [comment] 2019-09-27 07:00
@SwampDragons the feature being asked for in #5107 sounds useful, but isn't the same as what I've requested, and the 2 are not mutually exclusive - it would be really helpful to get a **meaningful** error message for bad credentials regardless of #5107. 

Hope you'll consider reopening this :smile:

**Comment by SwampDragons** [comment] 2019-09-27 16:42
I understand that they're not exactly the same, but the error message you don't like is being surfaced directly from the golang ssh library. All Packer knows is that the config you provided didn't work. We'd have to update the golang crypto library if we wanted more details, and I have a strong feeling any such PR would be rejected for security reasons.

However, a feature like the one described in #5107 would have helped you figure out your mistake, because when you run with the debug flag it would have printed out the info you've entered and you could have seen that you transposed the two. 

I get that from a user perspective it's frustrating that Packer can't tell you "there's an error and it's because your password was rejected" but there's also a security element to this, which is that we don't want to go around leaking credentials unless you specifically tell us you're debugging.

**Comment by cocowalla** [comment] 2019-09-27 17:23
@SwampDragons I wasn't suggesting that you "go around leaking credentials" :smile:

The messages I suggested were only meant to be examples of something helpful, and at worst would emit the username. But even "access denied" would be preferable to the confusing error message that exists today.

Rather than updating the external library, perhaps a different approach is possible, where it be Packer detects that it's received the particular error code/exception in question, and outputs a meaningful error message?

I get that #5107 *might* have helped me here, but TBH I wouldn't necessarily have even tried it, since the current error message had me thinking it was related to a ciphersuite negotiation error.

Also, just want to say that I love Packer and find it super-useful (not trying to sway you, just saying :)

**Comment by SwampDragons** [comment] 2019-09-27 18:11
Okay, how about this: when the handshake fails with an authentication error, we can surface a message saying that sometimes this occurs because of an invalid username/password, so please verify that they're correct. E.g. the big red error message at the end of the build run will read: 

```==> amazon-ebs: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. Original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain```

**Comment by cocowalla** [comment] 2019-09-27 18:16
Sounds good - this would have been really useful in my case.

**Closed** 2019-09-27 21:08 UTC
Labels: communicator/ssh, duplicate, enhancement

**Comment by cocowalla** [comment] 2019-09-27 21:36
Wow, that was fast, thanks!
