### ISSUE TITLE
Provide option to faill all builds immediately if one build fails --fail-fast

### ISSUE THREAD

**Issue by queglay** [hashicorp/packer#11823] opened 2022-05-29 10:44 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description

For parallel builds, that may involve use of many instances, and a failure of one will still mean other builds continue, wasting time and cost.  It would be helpful to have a flag like --fail-fast to kill all builds if one build fails.  This would also help spot the error in the log as well as save time.  To not fail fast is costly of human and machine time.

**Comment by nywilken** [comment] 2022-06-14 23:56
Duplicate of #11735

**Closed by nywilken** 2022-06-14 23:56 UTC
Labels: enhancement
