### ISSUE TITLE
shell-local post-processor results in errors on Windows

### ISSUE THREAD

**Issue by mrled** [hashicorp/packer#4140] opened 2016-11-09 22:17 UTC
When I try to use the `shell-local` post-processor in Windows, it fails with an empty error message.

Is this working under Windows? Have I done something wrong?

- Packer version: 0.11.0
- Host platform: Windows
- Simplest example template and scripts: https://gist.github.com/mrled/a6454b8432fc20b043ee70d64d6fd552

**Comment by mwhooker** [comment] 2016-11-10 00:26
confirmed this.

the problem seems to be that powershell.exe won't run any file that doesn't end in ".ps1" and we write the script to something like packer-shell123456

**Comment by mrled** [comment] 2016-11-10 00:33
Hmm. That might be a problem, but I'm also seeing it when trying to run a Python script, and Python isn't constrained to only running files with certain extensions. I've updated my gist with a Python script and its output. It has the same empty error message.

**Comment by mwhooker** [comment] 2016-11-10 00:57
alright I think the problem is that the post-processor communicator uses `exec.Command("sh", "-c", cmd.Command)`.

I manually changed it to use `exec.Command("Powershell.exe", "-command", cmd.Command)` and made the `execute_command` something like `Move-Item {{.Script}} {{.Script}}.ps1; Powershell.exe -File {{.Script}}.ps1` and it worked. Need to figure out how to abstract this for the windows host

**Comment by rickard-von-essen** [comment] 2016-11-10 05:31
Maybe we should have a `powershell-local` post-processor. But on the other
hand we have our doubts about the `shell-local` since it ties the
configuration tighter to the setup/type of host running the build.

On Nov 10, 2016 01:57, "Matthew Hooker" <notifications@github.com> wrote:

alright I think the problem is that the post-processor communicator
uses exec.Command("sh",
"-c", cmd.Command).

I manually changed it to use exec.Command("Powershell.exe", "-command",
cmd.Command) and made the execute_command something like Move-Item
{{.Script}} {{.Script}}.ps1; Powershell.exe -File {{.Script}}.ps1 and it
worked. Need to figure out how to abstract this for the windows host

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mitchellh/packer/issues/4140#issuecomment-259571726>,
or mute the thread

**Comment by mrled** [comment] 2016-11-11 04:12
Hmm. Well I hope it, or something like it, stays around, because I've found it to be very useful. A powershell-local (or cmd-local, which I could use to invoke Powershell or any other scripting language myself) would definitely solve my problem too.

**Comment by vtolstov** [comment] 2016-11-21 13:55
I thinks we can change default for each builder....

**Comment by damphyr** [comment] 2016-12-21 21:57
I've stumbled on this trying to get .msu files to execute.

Basically I'm trying to get a Vagrant Win7 basebox without the dreaded 100% CPU windows update bug and that involves installing three .msu files with in-between reboots just so we can run windows update again. But wusa.exe does not allow .msu execution over winRM so I thought I would do it locally - hence my landing here.

I switched back to
```
{
      "type": "shell-local",
      "execute_command": ["cmd.exe","{{.Command}}"],
      "command": "echo Boo"
}
```
as a workaround.

**Comment by SwampDragons** [comment] 2017-07-06 23:26
It seems to me that the point of having an "execute_command" option is to allow the entire command to be configurable.  So why not wait until we can make a backwards-breaking change, and then entirely remove the assumption of a shell command?  This seems to me to be the way the feature is documented, anyway.

example provisioner in this case:   

```
> "post-processors": [
>     {
>       "type": "shell-local",
>       "execute_command": "Powershell.exe Move-Item {{.Script}} {{.Script}}.ps1; Powershell.exe -File {{.Script}}.ps1",
>       "inline": ["write-output HIIIIIIIII"]
>     }
```

**Comment by SwampDragons** [comment] 2017-09-19 21:10
Closing because we have decided to deprecate this post-processor instead of fixing it; https://github.com/hashicorp/packer/issues/5330

**Closed by SwampDragons** 2017-09-19 21:10 UTC
Labels: bug, post-processor/shell-local, windows-host
