### ISSUE TITLE
Windows 2016 EC2 Ephemeral volumes being added

### ISSUE THREAD

**Issue by lgooch** [hashicorp/packer#6797] opened 2018-10-03 19:19 UTC
When creating a Windows 2016 AMI there are ephemeral volumes being created however none have been specified to be attached on the template. When launching an EC2 instance manually and running the command `(Invoke-WebRequest -Uri http://169.254.169.254/latest/meta-data/block-device-mapping/).Content` the output is 
>     amazon-ebs: ami
>     amazon-ebs: root
however when running the same command on an instance that packer has spun up the following is shown
>    amazon-ebs: ami
>    amazon-ebs: ephemeral0
>    amazon-ebs: ephemeral1
>    amazon-ebs: ephemeral10
>    amazon-ebs: ephemeral11
>    amazon-ebs: ephemeral12
>    amazon-ebs: ephemeral13
>    amazon-ebs: ephemeral14
>    amazon-ebs: ephemeral15
>    amazon-ebs: ephemeral16
>    amazon-ebs: ephemeral17
>    amazon-ebs: ephemeral18
>    amazon-ebs: ephemeral19
>    amazon-ebs: ephemeral2
>    amazon-ebs: ephemeral20
>    amazon-ebs: ephemeral21
>    amazon-ebs: ephemeral22
>    amazon-ebs: ephemeral23
>    amazon-ebs: ephemeral24
>    amazon-ebs: ephemeral25
>    amazon-ebs: ephemeral3
>    amazon-ebs: ephemeral4
>    amazon-ebs: ephemeral5
>    amazon-ebs: ephemeral6
>    amazon-ebs: ephemeral7
>    amazon-ebs: ephemeral8
>    amazon-ebs: ephemeral9
>    amazon-ebs: root

This issue can be replicated by creating an AMI using the latest Windows 2016 AMI available from Amazon in the eu-west-1 or eu-west-2 regions.

**Packer Version Tested** - 1.3.1

**Comment by lgooch** [comment] 2018-10-08 19:55
Hi @SwampDragons ,

Sample JSON file https://gist.github.com/lgooch/5e8099dd174371e7a19a1a565c0aa5b1 and corresponding bootstrap file https://gist.github.com/lgooch/930a65f8bebdd91c15ab559bfd914dae

**Comment by lgooch** [comment] 2018-10-08 19:56
<img width="558" alt="screenshot 2018-10-08 at 20 55 50" src="https://user-images.githubusercontent.com/28927458/46630601-969abe00-cb3c-11e8-9f92-ee13dc21c6d5.png">
example output from the AWS console showing the block devices attached

**Comment by lgooch** [comment] 2018-11-13 14:54
Is there any update on this please?

**Comment by SwampDragons** [comment] 2018-11-13 18:11
No update; we've not had a chance to look into this.

**Comment by aidancasey1** [comment] 2019-01-21 22:43
Hi,

We're also seeing the creation of ephemeral devices when using the AWS provided base 2016 GUI AMI in us-west-2
xvdca=ephemeral0, xvdcb=ephemeral1, xvdcc=ephemeral2, xvdcd=ephemeral3, xvdce=ephemeral4, xvdcf=ephemeral5, xvdcg=ephemeral6, xvdch=ephemeral7, xvdci=ephemeral8, xvdcj=ephemeral9, xvdck=ephemeral10, xvdcl=ephemeral11, xvdcm=ephemeral12, xvdcn=ephemeral13, xvdco=ephemeral14, xvdcp=ephemeral15, xvdcq=ephemeral16, xvdcr=ephemeral17, xvdcs=ephemeral18, xvdct=ephemeral19, xvdcu=ephemeral20, xvdcv=ephemeral21, xvdcw=ephemeral22, xvdcx=ephemeral23, xvdcy=ephemeral24, xvdcz=ephemeral25

Json:
"launch_block_device_mappings": [{
        "device_name": "/dev/sda1",
        "volume_size": "50",
        "delete_on_termination": true
      }],

**Comment by aidancasey1** [comment] 2019-01-25 20:37
Adding the below code for each device removed the devices from the final AMI
       {
          "device_name": "xvdca",
          "no_device": true
        },

**Comment by avanbecelaere** [comment] 2019-05-01 17:28
I'm seeing this as well from the Windows Server (2016 & 2019) base ami's in us-east-1.

**Comment by piettovasco** [comment] 2019-09-17 18:21
Hi I have also come across this issue. In my case I haven't specified any ephemeral drives in my build
yet its giving me 25 ephemeral drives in the block devices in AWS.  Is this issue still being worked on?

**Comment by jsleuth** [comment] 2019-09-27 16:22
This is happening for us too with packer on AWS starting from Windows Server 2016 base.  One ephemeral device for each letter of the alphabet (xvdca - xvdcz), 25 in total.

**Comment by SwampDragons** [comment] 2019-10-14 23:40
I'm sorry, all... I still can't reproduce this. I've tried the provided template, and I've tried various things like calling the initialization script. I've tried multiple different instance types. I'm at a loss. Nothing I do is causing those ephemeral volumes to show up either in the aws console or in the awscli using `aws ec2 describe-instances --filters "Name=instance-id,Values=$INSTANCENAME" --query "Reservations[].Instances[].BlockDeviceMappings`

I did find this blog post which seems similar to what y'all are seeing: https://aws.amazon.com/blogs/developer/stripe-windows-ephemeral-disks-at-launch/

But I'm out of ideas here and I'm not sure what else to try to reproduce this. In the end, I don't think it's Packer creating these volumes. If someone can suggest a different API call that won't create them I'm happy to look at implementing it, but given that this is an annoyance rather than something that seems to be associated with extra costs or unwanted final image configuration, I'm not sure it's worth digging into further.

**Comment by avanbecelaere** [comment] 2019-10-14 23:45
It’s not creating the volumes. For some reason the AWS console displays them with zero size, but when an instance is created from the ami, the volumes do not exist. To me, it seems more like a bug in the ec2 console. 

Andy
avanbecelaere@gmail.com

> On Oct 14, 2019, at 6:41 PM, Megan Marsh <notifications@github.com> wrote:
> 

﻿
I'm sorry, all... I still can't reproduce this. I've tried the provided template, and I've tried various things like calling the initialization script. I've tried multiple different instance types. I'm at a loss. Nothing I do is causing those ephemeral volumes to show up either in the aws console or in the awscli using aws ec2 describe-instances --filters "Name=instance-id,Values=$INSTANCENAME" --query "Reservations[].Instances[].BlockDeviceMappings

I did find this blog post which seems similar to what y'all are seeing: https://aws.amazon.com/blogs/developer/stripe-windows-ephemeral-disks-at-launch/

But I'm out of ideas here and I'm not sure what else to try to reproduce this. In the end, I don't think it's Packer creating these volumes. If someone can suggest a different API call that won't create them I'm happy to look at implementing it, but given that this is an annoyance rather than something that seems to be associated with extra costs or unwanted final image configuration, I'm not sure it's worth digging into further.

**Comment by SwampDragons** [comment] 2019-10-15 17:29
I am inclined to agree. Since I don't think there's anything Packer can do to prevent AWS from displaying these disks, and since they don't end up in the saved instance, I'm going to close as wontfix. If it turns out to be more than just a visual annoyance, we can revisit.

**Closed by SwampDragons** 2019-10-15 17:29 UTC
Labels: builder/amazon

**Comment by j-i-m-s-t-e-r** [comment] 2019-11-08 09:40
I am seeing this in our current Windows Server 2016 builds.  I am creating a server image with 6 drives for SQL.  I need to provision code and apps across these six drives.  

I am watching packer create the drives and bring them online in the image with the correct drive letters, but the drive letter mappings are screwed in the EC2 instances that we create off the AMI.

The packer code to build these drives is here:
`        "launch_block_device_mappings": [{
                "device_name": "/dev/sda1",
                "volume_size": 50,
                "volume_type": "gp2",
                "delete_on_termination": true,
                "encrypted": true,
                "kms_key_id": "a5d8c50b-558a-41cd-ab8a-f0f9f1cee864"
            },
            {
                "device_name": "xvdb",
                "volume_size": 50,
                "volume_type": "gp2",
                "delete_on_termination": true,
                "encrypted": true,
                "kms_key_id": "a5d8c50b-558a-41cd-ab8a-f0f9f1cee864"  
            },
            {
                "device_name": "xvdc",
                "volume_size": 40,
                "volume_type": "gp2",
                "delete_on_termination": true,
                "encrypted": true,
                "kms_key_id": "a5d8c50b-558a-41cd-ab8a-f0f9f1cee864"   
            },
            {
                "device_name": "xvdd",
                "volume_size": 20,
                "volume_type": "gp2",
                "delete_on_termination": true,
                "encrypted": true,
                "kms_key_id": "a5d8c50b-558a-41cd-ab8a-f0f9f1cee864"  
            },
            {
                "device_name": "xvde",
                "volume_size": 40,
                "volume_type": "gp2",
                "delete_on_termination": true,
                "encrypted": true,
                "kms_key_id": "a5d8c50b-558a-41cd-ab8a-f0f9f1cee864"  
            },
            {
                "device_name": "xvdf",
                "volume_size": 5,
                "volume_type": "gp2",
                "delete_on_termination": true,
                "encrypted": true,
                "kms_key_id": "a5d8c50b-558a-41cd-ab8a-f0f9f1cee864"  
            }]`

In packer, I then use Powershell to mount, format and label these as C,D,E,L,T and X.  (C is already done for me as it's /dev/sda1).  This works fine and in the image I can confirm these are the correct labels for all six disks.

I **am** then using the specified AWS method of putting a .json file into the image with the correct drive letter mappings above, as SYSPREP (the final step in our build) helpfully wipes the drive letters.  This generally works for our 4-drive boxes - they come online with the correct mapping - but I noticed some inconsistencies which I can't explain over the last few weeks.  I think this is the ephemeral drive bs.

This is the code for that .json download (as per https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html#ec2launch-mapping)

```
# Downloaded relevant mapping .json from s3 to c:\temp
Copy-Item "c:\temp\DriveLetterMappingConfig.json" -Destination "C:\ProgramData\Amazon\EC2-Windows\Launch\Config\DriveLetterMappingConfig.json" -Force
Write-Host "Set Initialze Disks to run on every boot..."
C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeDisks.ps1 -Schedule
```

Now on these 6-drive boxes, the EC2 instances **never** get the correct drive mappings.  SO frustrating.  I've checked the instanced and the .json file above is always present and correct.

All the AMIs I get have 20+ ephemeral drives.   I am sure this is messing up the drive mappings.  When I check the block devices of our AMIs they are all listing:
`/dev/sda1=snap-038cbdd45022646a0:30:true:gp2, xvdca=ephemeral0, xvdcb=ephemeral1, xvdcc=ephemeral2, xvdcd=ephemeral3, xvdce=ephemeral4, xvdcf=ephemeral5, xvdcg=ephemeral6, xvdch=ephemeral7, xvdci=ephemeral8, xvdcj=ephemeral9, xvdck=ephemeral10, xvdcl=ephemeral11, xvdcm=ephemeral12, xvdcn=ephemeral13, xvdco=ephemeral14, xvdcp=ephemeral15, xvdcq=ephemeral16, xvdcr=ephemeral17, xvdcs=ephemeral18, xvdct=ephemeral19, xvdcu=ephemeral20, xvdcv=ephemeral21, xvdcw=ephemeral22, xvdcx=ephemeral23, xvdcy=ephemeral24, xvdcz=ephemeral25`

**Comment by SwampDragons** [comment] 2019-11-08 17:12
@j-i-m-s-t-e-r can your share your Packer template .json file?

**Comment by j-i-m-s-t-e-r** [comment] 2019-11-11 10:22
Hi Megan,

Packer .json is:

> {
>     "builders": [{
>         "type":                 "amazon-ebs",
>         "vpc_id":               "{{ user `packer_build_vpc_id`}}",  
>         "subnet_id":            "{{ user `packer_build_subnet_id`}}",
>         "security_group_id":    "{{ user `packer_build_security_group_id`}}",
>         "region":               "{{ user `packer_build_region`}}",
>         "source_ami":           "{{ user `web_server_source_ami`}}",
>         "ami_name":             "SQL Image Packer_W2016_6_drives_cdeltx-{{timestamp}}",
>         "iam_instance_profile": "{{ user `web_server_iam_instance_profile`}}", 
>         "user_data_file":       "{{ user `packer_build_user_data_file`}}",
>         "communicator":         "winrm",
>         "winrm_username":       "Administrator",
>         "instance_type":        "m5.xlarge",
>         "winrm_use_ssl":        true,
>         "winrm_insecure":       true,
>         "run_volume_tags": {
>             "CostCentre":       "{{ user `CostCentre`}}",
>             "BusinessUnit":     "{{ user `BusinessUnit`}}",
>             "Project":          "{{ user `Project`}}"
>         },
> 
>         "launch_block_device_mappings": [{
>                 "device_name": "/dev/sda1",
>                 "volume_size": 50,
>                 "volume_type": "gp2",
>                 "delete_on_termination": true,
>                 "encrypted": false                
>             },
>             {
>                 "device_name": "xvdb",
>                 "volume_size": 50,
>                 "volume_type": "gp2",
>                 "delete_on_termination": true,
>                 "encrypted": false                  
>             },
>             {
>                 "device_name": "xvdc",
>                 "volume_size": 40,
>                 "volume_type": "gp2",
>                 "delete_on_termination": true,
>                 "encrypted": false                   
>             },
>             {
>                 "device_name": "xvdd",
>                 "volume_size": 20,
>                 "volume_type": "gp2",
>                 "delete_on_termination": true,
>                 "encrypted": false                  
>             },
>             {
>                 "device_name": "xvde",
>                 "volume_size": 40,
>                 "volume_type": "gp2",
>                 "delete_on_termination": true,
>                 "encrypted": false                  
>             },
>             {
>                 "device_name": "xvdf",
>                 "volume_size": 5,
>                 "volume_type": "gp2",
>                 "delete_on_termination": true,
>                 "encrypted": false                  
>             }]
>     }],
> 
>     "provisioners": [
>         {
>             "type":         "powershell",
>             "inline": [
>                 "Set-ExecutionPolicy unrestricted -force",
>                 "Set-ExecutionPolicy Bypass -Scope Process",
>                 "Disable-ScheduledTask -TaskName \"chef-client\""
> 
>             ]
>         },
>         {
>             "type":         "powershell",
>             "script":       "./setup_6_drives_cdeltx.ps1"      
>         },
>         {
>             "type":         "windows-restart"
>         },
>         {
>             "type":         "powershell",
>             "script":       "./install_chocolately.ps1"      
>         },
>         {
>             "type":         "powershell",
>             "script":       "./install_s3_dotnet_3.5.ps1"      
>         },
>         {
>             "type":         "windows-restart"
>         },
>         {
>             "type":         "powershell",
>             "script":       "./install_s3_dotnet_4.7.1.ps1"      
>         },
>         {
>             "type":         "windows-restart"
>         },
>         {
>             "type":         "powershell",
>             "script":       "./install_IIS_Features.ps1"      
>         },  
>         {
>             "type":         "powershell",
>             "script":       "./install_utils.ps1"   
>         },   
>         {
>             "type":         "powershell",
>             "inline": [
>                 "Remove-Item c:\\temp\\* -Recurse -Force"
>             ]
>         },
> 
>         {
>             "type":         "powershell",
>             "inline": [
>                 "choco install undo-winrmconfig-during-shutdown "
>             ]
>         },
>         {
>             "type":         "powershell",
>             "inline": [
>                 "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule",
>                 "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/SysprepInstance.ps1 -NoShutdown"
>             ]
>         }
> 
>     ]
> }
> 
> 
> 

Key provisioners are setup_6_drives_cdeltx.ps1 :
`# Do volume config of the two drives
write-host "Setting up drives..."
# Disk number 0 is the default EC2 C: so no Initialize-Disk on this disk needed
Initialize-Disk -Number 1 -PartitionStyle "MBR"
Initialize-Disk -Number 2 -PartitionStyle "MBR"
Initialize-Disk -Number 3 -PartitionStyle "MBR"
Initialize-Disk -Number 4 -PartitionStyle "MBR"
Initialize-Disk -Number 5 -PartitionStyle "MBR"

New-Partition -DiskNumber 1 -UseMaximumSize -IsActive -DriveLetter D
New-Partition -DiskNumber 2 -UseMaximumSize -IsActive -DriveLetter E
New-Partition -DiskNumber 3 -UseMaximumSize -IsActive -DriveLetter L
New-Partition -DiskNumber 4 -UseMaximumSize -IsActive -DriveLetter T
New-Partition -DiskNumber 5 -UseMaximumSize -IsActive -DriveLetter X

Format-Volume -DriveLetter D -Confirm:$FALSE
Format-Volume -DriveLetter E -Confirm:$FALSE
Format-Volume -DriveLetter L -Confirm:$FALSE
Format-Volume -DriveLetter T -Confirm:$FALSE
Format-Volume -DriveLetter X -Confirm:$FALSE

label C: "volume1"
label D: "volume2"
label E: "volume3"
label L: "volume4"
label T: "volume5"
label X: "volume6"

Write-Host "Drive Mappings Are:"
Get-Partition | sort {$_.DriveLetter}


# Now insert DriveLetterMappingConfig.json file into C:\ProgramData\Amazon\EC2-Windows\Launch\Config to ensure instance starts with correct drive mappings
Write-Host "S3 Download: DriveLetterMappingConfig.json"
Read-S3Object -BucketName usis-rm-tribe-dev-plato-media-bucket -Key CDELTX_DriveLetterMappingConfig.json -File 'c:\temp\DriveLetterMappingConfig.json'
Write-Host "Copying DriveLetterMappingConfig.json to C:\ProgramData\Amazon\EC2-Windows\Launch\Config..."
Copy-Item "c:\temp\DriveLetterMappingConfig.json" -Destination "C:\ProgramData\Amazon\EC2-Windows\Launch\Config\DriveLetterMappingConfig.json" -Force
Write-Host "Set Initialze Disks to run on every boot..."
C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeDisks.ps1 -Schedule`

vars file is:
```
{
    "packer_build_region":              "us-east-1",
    "packer_build_vpc_id":              "vpc-011fedf62fe1a2fdd",
    "packer_build_subnet_id":           "subnet-02f7eb90e91ddcf30",
    "packer_build_security_group_id":   "sg-02ef147d7048be1e0",
    "comment_item":                     "current dev source ami below is the client standard w2016 image",
    "web_server_source_ami":            "ami-014961401c6bd2955",
    "web_server_iam_instance_profile":  "efx-cloud-ec2-s3-access-role-profile",
    "packer_build_user_data_file":      "./USERDATA2.0.txt",
    "CostCentre":                       "0300 3246",
    "BusinessUnit":                     "AppServices",
    "Project":                          "Plato Migration to AWS"
}

**Comment by SwampDragons** [comment] 2019-11-11 19:06
Looking at the code, I think the issue may be that the docs are wrong; launch block device mappings don't look like they persist into the final image. For that, I think you may need to set ami_block_device_mappings as well.

**Comment by j-i-m-s-t-e-r** [comment] 2019-11-11 21:02
Megan,

Thanks for the reply.

The docco states:

> **ami_block_device_mappings (awscommon.BlockDevices)** - Add one or more block device mappings to the AMI. These will be attached when booting a new instance from your AMI. To add a block device during the Packer build see launch_block_device_mappings below. Your options here may vary depending on the type of VM you use. See the BlockDevices documentation for fields.
> 
> **launch_block_device_mappings (awscommon.BlockDevices)** - Add one or more block devices before the Packer build starts. If you add instance store volumes or EBS volumes in addition to the root device volume, the created AMI will contain block device mapping information for those volumes. Amazon creates snapshots of the source instance's root volume and any other EBS volumes described here. When you launch an instance from this new AMI, the instance automatically launches with these additional volumes, and will restore them from snapshots taken from the source instance. See the BlockDevices documentation for fields.

So what do I need to declare to achieve:
5 extra volumes in the image being provisioned - to which I then provision my SQL setup - which then generates an AMI that I can spin EC2 instances from that will also have 5 NEW volumes (NOT the same volumes the AMI used) that start out with file content cloned from the AMI's volumes?

Or am I being a bit, y'know, slow... and not understanding that _"When you launch an instance from this new AMI, the instance automatically launches with these additional volumes"_ means the instances get to share THEEE-EXACT-**SAME**-VOLUMES that the AMI used.  I mean, how is that gonna work... right?

**Comment by SwampDragons** [comment] 2019-11-12 00:02
> and not understanding that "When you launch an instance from this new AMI, the instance automatically launches with these additional volumes"  

Yeah, that's the part of the docs I think may be wrong. 

I'm not convinced the ephemerals are the reason for this... the mis-mapped drive may be their own separate issue... whether with documentation or implementation I'm not quite sure yet.  Can you open a new issue so I can track it separately?

**Comment by j-i-m-s-t-e-r** [comment] 2019-11-12 08:47
Thanks again Megan.  Opened the following new issue:
https://github.com/hashicorp/packer/issues/8362

**Comment by j-i-m-s-t-e-r** [comment] 2019-11-12 09:06
In the meantime, I'm moving to 1.4.5 and using ami_block instead of launch_block today.  I'll see what comes of it.

**Comment by j-i-m-s-t-e-r** [comment] 2019-11-12 13:58
Same thing.

**Comment by SwampDragons** [comment] 2019-11-12 16:52
Good to know. We'll try to investigate before the 1.5.0 release.

**Comment by SwampDragons** [comment] 2019-11-18 19:57
Ah, nevermind -- looks like you provided them on the original issue thread; I'll use those.
