### ISSUE TITLE
vagrant-cloud post-processor not working as expected

### ISSUE THREAD

**Issue by nadarashwin** [hashicorp/packer#8327] opened 2019-11-05 14:40 UTC
I have been trying to set up an in-house repository for vagrant boxes. However, have comes across some issues.
I am using the packer's vagrant-cloud post-processor for uploading the box file to our Artifactory server hosted in house.

`  "post-processors": [
    [
        {
          "type": "vagrant",
          "output": "ubuntu-16.box",
          "only": ["virtualbox"]
        },
        {
          "type": "vagrant-cloud",
          "vagrant_cloud_url": "http://xyz/artifactory/api/vagrant/packer-virtualboxes",
          "version": "{{user `image_version`}}",
          "box_tag": "ubuntu16"
        }
    ]`

The packer process fails with 404 for the following:
`2019/11/01 16:59:09 packer: 2019/11/01 16:59:09 Post-Processor Vagrant Cloud API GET: http://xyz/artifactory/api/vagrant/packer-virtualboxes/box/ubuntu16`

The actual URL listed under "vagrant_cloud_url" in packer.json is "http://xyz/artifactory/api/vagrant/packer-virtualboxes".
However, when the packer build runs it tries to do a GET call on http://xyz/artifactory/api/vagrant/packer-virtualboxes/box/ubuntu16.
Not sure why *box* keyword is added after the actual URL due to which the query fails.
I tried to do a curl call on http://xyz/artifactory/api/vagrant/packer-virtualboxes/ubuntu16 which works fine.

### Packer version

Tested in packer 1.1.1 and packer 1.4.5

### Operating system and Environment details

OS - Ubuntu 16.04
Architecture - x86_64

**Comment by nadarashwin** [comment] 2019-11-08 11:47
@SwampDragons As per our discussion in https://groups.google.com/forum/#!topic/packer-tool/dQhyxqzMeyY .. Kindly check once free

**Comment by SwampDragons** [comment] 2019-11-08 17:17
Thanks! I'll take a look before the next release.

**Comment by SwampDragons** [comment] 2019-11-11 19:28
Can you please share debug logs (set env PACKER_LOG=1 and run the build so I can see where specifically it is failing)

**Comment by SwampDragons** [comment] 2019-11-11 19:45
Are you using Vagrant Private Cloud, or just trying to upload your vagrant box to artifactory? The "box" prefix looks like it's a typical part of the Vagrant Cloud API.

**Comment by SwampDragons** [comment] 2019-11-11 19:55
I checked in with the Vagrant team, and they say that the box prefix is an appropriate part of the Vagrant Cloud API. This looks like a bug with Artifactory's vagrant repository, or a use of their Vagrant Repository that they don't actually support. I'm closing this because I don't think it's within the scope of the vagrant cloud post-processor to support Artifactory.  Thanks for understanding.

**Closed by SwampDragons** 2019-11-11 19:55 UTC
Labels: bug, post-processor/vagrant-cloud

**Comment by nadarashwin** [comment] 2019-11-12 13:02
@SwampDragons I have created a vagrant repository as mentioned here. https://www.jfrog.com/confluence/display/RTF/Vagrant+Repositories

I see that a GET call is made on the internal Aritfactory site with *box* keyword in the URL
```
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 stdout: Successfully exported 1 machine(s).
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 failed to unlock port lockfile: close tcp 127.0.0.1:2592: use of closed network connection
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 failed to unlock port lockfile: close tcp 127.0.0.1:5974: use of closed network connection
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 Executing VBoxManage: []string{"storageattach", "packer-virtualbox-1572962591", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 stdout:
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 stderr: VBoxManage: error: No storage device attached to device slot 1 on port 0 of controller 'IDE Controller'
2019/11/01 14:27:41 packer: VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
2019/11/01 14:27:41 packer: VBoxManage: error: Context: "DetachDevice(Bstr(pszCtl).raw(), port, device)" at line 403 of file VBoxManageStorageController.cpp
[1;32m==> virtualbox: Deregistering and deleting VM...[0m
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 Executing VBoxManage: []string{"unregistervm", "packer-virtualbox-1572962591", "--delete"}
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 stdout:
2019/11/01 14:27:41 packer: 2019/11/01 14:27:41 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2019/11/01 14:27:41 [INFO] (telemetry) ending virtualbox-iso
2019/11/01 14:27:41 [INFO] (telemetry) Starting post-processor vagrant
[1;32m==> virtualbox: Running post-processor: vagrant[0m
[1;32m==> virtualbox (vagrant): Creating Vagrant box for 'virtualbox' provider[0m
[0;32m    virtualbox (vagrant): Copying from artifact: output-virtualbox/packer-virtualbox-1572962591-disk001.vmdk[0m
[0;32m    virtualbox (vagrant): Copying from artifact: output-virtualbox/packer-virtualbox-1572962591.ovf[0m
[0;32m    virtualbox (vagrant): Renaming the OVF to box.ovf...[0m
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Looking for OVF to rename...
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Looking for OVF in artifact...
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Renaming: '/tmp/packer365367004/packer-virtualbox-1572962591.ovf' => box.ovf
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Looking for OVF for base mac address...
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Looking for OVF in artifact...
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Base mac address: 08002716ED5F
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Turning dir into box: /tmp/packer365367004 => ubuntu-16.box
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Compressing with gzip compression level: -1
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Skipping directory '/tmp/packer365367004' for box 'ubuntu-16.box'
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Box add: '/tmp/packer365367004/Vagrantfile' to 'ubuntu-16.box'
[0;32m    virtualbox (vagrant): Compressing: Vagrantfile[0m
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Box add: '/tmp/packer365367004/box.ovf' to 'ubuntu-16.box'
[0;32m    virtualbox (vagrant): Compressing: box.ovf[0m
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Box add: '/tmp/packer365367004/metadata.json' to 'ubuntu-16.box'
[0;32m    virtualbox (vagrant): Compressing: metadata.json[0m
2019/11/01 14:27:43 packer: 2019/11/01 14:27:43 Box add: '/tmp/packer365367004/packer-virtualbox-1572962591-disk001.vmdk' to 'ubuntu-16.box'
[0;32m    virtualbox (vagrant): Compressing: packer-virtualbox-1572962591-disk001.vmdk[0m
[1;32m==> virtualbox: Running post-processor: vagrant-cloud[0m
2019/11/01 14:27:49 [INFO] (telemetry) ending vagrant
2019/11/01 14:27:49 [INFO] (telemetry) Starting post-processor vagrant-cloud
[1;32m==> virtualbox (vagrant-cloud): Verifying box is accessible: ubuntu18.04[0m
2019/11/01 14:27:49 packer: 2019/11/01 14:27:49 Post-Processor Vagrant Cloud API GET: http://xyz/artifactory/api/vagrant/packer-virtualboxes/box/ubuntu16
2019/11/01 14:27:49 packer: 2019/11/01 14:27:49 Post-Processor Vagrant Cloud API Response:
2019/11/01 14:27:49 packer: 
2019/11/01 14:27:49 packer: &{Status:404 Not Found StatusCode:404 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1
```

From the above logs it's clear that vagrant cloud post-processor is trying to add the keyword *box*

**Comment by nadarashwin** [comment] 2019-11-12 13:07
As I mentioned before when I make a GET call directly to the URL without the *box* keyword it works.

**Comment by SwampDragons** [comment] 2019-11-12 16:58
Yes, I understand that. But the Vagrant Repository created by Artifactory is not Vagrant Cloud, and this is the Vagrant Cloud post-processor; I don't think it's within the scope of this post-processor to support uploading to an entirely different service than the post-processor was designed for, just because the thing being uploaded is a Vagrant box. If you want to upload a box to that repository, you can use the shell-local provisioner to send the request directly, or you can [create your own](https://www.packer.io/docs/extending/custom-post-processors.html) post-processor that does what you want.

**Comment by nadarashwin** [comment] 2019-11-13 06:19
Makes sense, thanks @SwampDragons
