### ISSUE TITLE
Build 'vmware-iso' errored: unexpected EOF 

### ISSUE THREAD

**Issue by nareshkumar23736** [hashicorp/packer#7555] opened 2019-04-24 05:35 UTC
packer version:1.4.0
Platforms : packer installed on RHEL 7 VM and trying to create ova files using esxi vm(remote )
/opt/packer/packer build /opt/packer/json/test.json
OUTPUT:
      vmware-iso output will be in this color.

Warnings for build 'vmware-iso':

* Your vmx data contains the following variable(s), which Packer normally sets when it generates its own default vmx template. This may cause your build to fail or behave unpredictably: numvcpus, memsize
```
==> vmware-iso: Retrieving ISO
==> vmware-iso: Trying /opt/packer/iso/rhel-server-7.6-x86_64-dvd.iso
==> vmware-iso: Trying /opt/packer/iso/rhel-server-7.6-x86_64-dvd.iso?checksum=sha1%3A9d2a1c31a8ff19201d06673b57c5eef0f9860005
==> vmware-iso: /opt/packer/iso/rhel-server-7.6-x86_64-dvd.iso?checksum=sha1%3A9d2a1c31a8ff19201d06673b57c5eef0f9860005 => /opt/packer/packer_cache/97b1b09f82dc730646ac494ed0c0750b544242eb.iso
==> vmware-iso: leaving retrieve loop for ISO
==> vmware-iso: Creating floppy disk...
    vmware-iso: Copying files flatly from floppy_files
    vmware-iso: Copying file: http/ks.cfg
    vmware-iso: Done copying files from floppy_files
    vmware-iso: Collecting paths from floppy_dirs
    vmware-iso: Resulting paths from floppy_dirs : []
    vmware-iso: Done copying paths from floppy_dirs
==> vmware-iso: Uploading Floppy to remote machine...
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Creating required virtual machine disks
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8880
Build 'vmware-iso' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: unexpected EOF

==> Builds finished but no artifacts were created.
 ```
same thing is working with 1.3.5
json file content:
``` json
 "builders" : [
    { "type": "vmware-iso",
      
      "iso_url": "/var/packer/rhel-server-7.6-x86_64-dvd.iso",
      "iso_checksum": "9d2a1c31a8ff19201d06673b57c5eef0f9860005",
      "iso_checksum_type": "sha1",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_password": "{{user `ssh_password`}}",
      "ssh_wait_timeout": "100m",
      "shutdown_command": "shutdown -P now",
      "headless": "false",
      "vnc_port_max": 10000,
      

      "output_directory": "{{user `output_directory`}}",
      "vm_name": "{{ user `vm_name`}}",
      "guest_os_type": "{{user `guest_os_type`}}",
      "disk_size": "{{user `disk_size`}}",
      "vmx_data": {
	  "numvcpus": 2,
	  "memsize": 2048,
      "ethernet0.networkName": "VM Network SB"
	},

      "remote_type": "esx5",
      "remote_username": "{{user `remote_username`}}",
      "remote_host": "{{user `remote_host`}}",
      "remote_datastore": "{{user `remote_datastore`}}",
      "remote_password": "{{user `remote_password`}}",
      "keep_registered": true,
      "skip_export": true,
      "http_directory": "{{user `http_directory`}}",
      "boot_wait": "5s",
      "boot_key_interval": "100ms",
      "floppy_files": ["http/ks.cfg"],
      "boot_command": ["<wait10><esc>","<wait>linux inst.ks=hd:/dev/fd0:ks.cfg","<enter><wait>"],      
      "tools_upload_flavor": "linux"
    }
]
```

**Comment by nikobo** [comment] 2019-04-29 18:57
same issue on buster/sid

**Comment by nikobo** [comment] 2019-04-29 19:04
duplicate of https://github.com/hashicorp/packer/issues/7505

**Comment by azr** [comment] 2019-04-30 09:38
Hello there, thanks for opening and sorry for the trouble, this has been fixed in https://github.com/hashicorp/packer/pull/7509 and is a dupe of #7505

Here's a build of the master branch in case you want to try it out :

[linux_amd64.zip](https://github.com/hashicorp/packer/files/3130629/linux_amd64.zip)
[windows_amd64.zip](https://github.com/hashicorp/packer/files/3130630/windows_amd64.zip)

( sorry I can't upload the mac os one as github seems to not like it as it's too big ?! )

**Comment by azr** [comment] 2019-04-30 09:52
Leaving this issue open until the 1.4.1 release

**Comment by nareshkumar23736** [comment] 2019-05-02 03:40
Thanks for the build will try with uploaded one

**Closed** 2019-05-15 20:15 UTC
Labels: crash, duplicate

**Comment by markchristopherwest** [comment] 2019-07-03 05:24
This looks like a permissions issue within the VMX directory.
