### ISSUE TITLE
Is there a way to set a specific cipher in ssh communicator? 

### ISSUE THREAD

**Issue by reysmerwvr** [hashicorp/packer#8461] opened 2019-12-06 16:39 UTC
Issues on GitHub are intended to be related to bugs or feature requests, so we
recommend using our other community resources instead of asking here if you
have a question.

- Packer Guides: https://www.packer.io/guides/index.html
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community.html

**Comment by SwampDragons** [comment] 2019-12-06 18:39
Oops, looks like you opened the same issue twice. I'm closing this as a duplicate of #8460

**Closed by SwampDragons** 2019-12-06 18:39 UTC
Labels: question
