### ISSUE TITLE
-on-error doesn't affect post-processor failures

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#6901] opened 2018-10-23 16:46 UTC
Currently running with `-on-error=ask` doesn't halt and ask what to do when a post-processor failed. 

This should either be fixed or clarified in the docs as intended behaviour.

Example:

```json
{
  "builders": [
    {
      "type": "docker",
      "image": "alpine",
      "run_command": ["-d", "-i", "-t", "{{.Image}}", "/bin/ash"],
      "commit": true
    }
  ],
  "post-processors": [
    [
      {
        "type": "docker-tag",
        "repository": "####965990659467.dkr.ecr.eu-central-1.amazonaws.com/packer-test",
        "tag": "latest",
        "force": true
      }
    ]
  ]
}
```
```
$ packer build -on-error=ask docker-tag2.json
docker output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: alpine
    docker: Using default tag: latest
    docker: latest: Pulling from library/alpine
    docker: Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
    docker: Status: Image is up to date for alpine:latest
==> docker: Starting docker container...
    docker: Run command: docker run -v /Users/rickard/.packer.d/tmp/packer-docker047656536:/packer-files -d -i -t alpine /bin/ash
    docker: Container ID: b71f8df10868fce23121a5515bebc7201e04c0760778f6557286c2de24084af4
==> docker: Using docker communicator to connect: 172.17.0.2
==> docker: Committing the container
    docker: Image ID: sha256:eb9d52da9a9dcf01798ed91267e9980479538e2a171f9c334dedcc5b529ddf4c
==> docker: Killing the container: b71f8df10868fce23121a5515bebc7201e04c0760778f6557286c2de24084af4
==> docker: Running post-processor: docker-tag
    docker (docker-tag): Tagging image: sha256:eb9d52da9a9dcf01798ed91267e9980479538e2a171f9c334dedcc5b529ddf4c
    docker (docker-tag): Repository: ####965990659467.dkr.ecr.eu-central-1.amazonaws.com/packer-test:latest
Build 'docker' errored: 1 error(s) occurred:

* Post-processor failed: Error tagging image: exit status 1
Stderr: Error parsing reference: "####965990659467.dkr.ecr.eu-central-1.amazonaws.com/packer-test:latest" is not a valid repository/tag: invalid reference format


==> Some builds didn't complete successfully and had errors:
--> docker: 1 error(s) occurred:

* Post-processor failed: Error tagging image: exit status 1
Stderr: Error parsing reference: "####965990659467.dkr.ecr.eu-central-1.amazonaws.com/packer-test:latest" is not a valid repository/tag: invalid reference format


==> Builds finished but no artifacts were created.
```

**Comment by SwampDragons** [comment] 2020-08-10 17:52
This is a duplicate of #5497; I only just realized this while doing a "docs" issue audit. I'm going to close this so it's only tracked in one place.

**Closed by SwampDragons** 2020-08-10 17:52 UTC
Labels: bug, core, docs, duplicate
