### ISSUE TITLE
Ansible provisioner hangs on initial ssh connection

### ISSUE THREAD

**Issue by ydubreuil** [hashicorp/packer#5236] opened 2017-08-10 09:29 UTC
* Packer version: 1.0.2 and 1.0.3 (it is a regression, it works with Packer 1.0.0)
* Host: Archlinux with 4.12 Linux kernel, openssh 7.5p1-2
* Debug log: https://gist.github.com/ydubreuil/2392c80b05856d7e9d1e5108039d16db

When trying to build an AMI with amazon-ebs builder and Ansible provisioner, Ansible gets stuck on `TASK [Gathering Facts]`. Running Ansible with `-vvv` shows that Ansible is stuck on this SSH command:

```
amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: dudu
amazon-ebs: <127.0.0.1> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=38061 -o 'IdentityFile="/tmp/ansible-key973622379"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=dudu -o ConnectTimeout=10 -o ControlPath=/home/dudu/.ansible/cp/a889695871 127.0.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
```

This ssh command hangs indefinitely. When I run it on a terminal after removing the end part to get an interactive shell, I can successfully open up the SSH session and run commands (it feels weird without a TTY but it works). When I quit the shell using `exit`, the SSH command session is closed (ie, I can't run any command anymore) but SSH doesn't release stdin until I send EOF with CTRL-D. So Ansible is waiting on nothing and hangs, indefinitely.

This makes me think there's an issue in the SSH proxy that doesn't close up proxied SSH sessions properly under certain circumstances.

**Comment by rickard-von-essen** [comment] 2017-08-10 12:10
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2 where this really should work.

**Closed by rickard-von-essen** 2017-08-10 12:10 UTC

**Comment by ydubreuil** [comment] 2017-08-10 12:50
Sigh! I didn't see the duplicate issue. I noticed that it is also failing with 1.0.2.

I'll try a build from master and tell how it goes.

**Comment by ydubreuil** [comment] 2017-08-10 13:45
Works fine on latest master. Sorry for the duplicate issue. I'll  be more careful next time.

**Comment by rickard-von-essen** [comment] 2017-08-10 15:23
No worries. And it should also work on 1.0.2.
