### ISSUE TITLE
Packer AWS Windows WinRM fails to connect after Hardening

### ISSUE THREAD

**Issue by dhruv-malik-ptc** [hashicorp/packer#10432] opened 2020-12-30 00:10 UTC
I am able to harden the Windows 2019 Standard Image using packer using LGPO.exe
However, immediately after hardening it, the packer fails to connect to the EC2, I presume its due to CIS hardening itself.
I have googled everywhere, but could not find a get around.
below is the error message

Error:
```
==> amazon-ebs: Provisioning with windows-shell...
2020/12/29 05:52:11 packer-provisioner-windows-shell plugin: Found command: C:\Users\Administrator\AppData\Local\Temp\cis-benchmark-gpos\LGPO.exe /g C:\Users\Administrator\AppData\Local\Temp\cis-benchmark-gpos\cis\USER-L1\{DD55FCFF-4FC0-4FA0-9ABC-9D8402B8089E}
==> amazon-ebs: Provisioning with shell script: /tmp/windows-shell-provisioner364133423
2020/12/29 05:52:11 packer-provisioner-windows-shell plugin: Opening /tmp/windows-shell-provisioner364133423 for reading
2020/12/29 05:52:11 packer-provisioner-windows-shell plugin: [INFO] 185 bytes written for 'uploadData'
2020/12/29 05:52:11 [INFO] 185 bytes written for 'uploadData'
2020/12/29 05:52:11 packer-builder-amazon-ebs plugin: Uploading file to 'c:/Windows/Temp/script.bat'
2020/12/29 05:52:12 packer-provisioner-windows-shell plugin: Retryable error: Error uploading script: Error uploading file to $env:TEMP\winrmcp-045c91af-61af-451d-7bf1-daf1bb11e107.tmp: Couldn't create shell: http response error: 401 - invalid content type
2020/12/29 05:52:14 packer-provisioner-windows-shell plugin: [INFO] 185 bytes written for 'uploadData'
2020/12/29 05:52:14 [INFO] 185 bytes written for 'uploadData'
2020/12/29 05:52:14 packer-builder-amazon-ebs plugin: Uploading file to 'c:/Windows/Temp/script.bat'
2020/12/29 05:52:44 packer-provisioner-windows-shell plugin: Retryable error: Error uploading script: Error uploading file to $env:TEMP\winrmcp-2024a9bd-4e71-42c1-481c-ad7221d86d92.tmp: Couldn't create shell: unknown error Post "https://10.0.1.118:5986/wsman": dial tcp 10.0.1.118:5986: i/o timeout
```

```
{
    "builders": [
      {
        "type": "amazon-ebs",
        "region": "ap-southeast-2",
        "source_ami": "AMI_ID",
        "instance_type": "t3a.micro",
        "ami_name": "windows-2019-s-cis-l1-{{timestamp}}",
        "communicator": "winrm",
        "ssh_interface": "private_ip",
        "winrm_username": "Administrator",
        "winrm_timeout": "15m",
        "winrm_insecure": true,
        "winrm_use_ntlm": true,
        "winrm_use_ssl": true,
        "iam_instance_profile": "ami-factory-SSMStack",
        "vpc_id": "vpc-3231",
        "subnet_id": "subnet-1312",
        "security_group_id": "sg-213123",
        "associate_public_ip_address": true,
        "user_data_file": "setup-winrm.txt",
        "launch_block_device_mappings": [
          {
             "device_name": "/dev/xvda",
             "volume_size": 50,
             "delete_on_termination": true,
             "volume_type": "gp2"
          }
        ],
        "run_volume_tags": {
          "Name": "windows-2019-s-cis-level1-ami-{{timestamp}}",
          "CostCentre": "38367695/20005"
        },        
        "run_tags": {
          "Name": "windows-2019-s-cis-level1-ami-{{timestamp}}",
          "CostCentre": "38367695/20005"
        },
        "tags": {
          "Name": "windows-2019-s-cis-level1-ami-{{timestamp}}",
          "CostCentre": "38367695/20005"
        }
      }
    ],
  "provisioners": [
    {
      "type": "file",
      "source": "builder/cis-benchmark-gpos",
      "destination": "C:\\Users\\Administrator\\AppData\\Local\\Temp",
      "direction": "upload"
    },
    {
      "type": "windows-shell",
      "inline": ["certutil -decode \"C:\\Users\\Administrator\\AppData\\Local\\Temp\\cis-benchmark-gpos\\LGPO.exe.txt\" \"C:\\Users\\Administrator\\AppData\\Local\\Temp\\cis-benchmark-gpos\\LGPO.exe\""]
    },
    {
      "type": "windows-shell",
      "inline": ["C:\\Users\\Administrator\\AppData\\Local\\Temp\\cis-benchmark-gpos\\LGPO.exe  /g C:\\Users\\Administrator\\AppData\\Local\\Temp\\cis-benchmark-gpos\\cis\\MS-L1\\{6B8FB17A-45D6-456D-9099-EB04F0100DE2}"]
    },
    {
      "type": "windows-shell",
      "inline": ["C:\\Users\\Administrator\\AppData\\Local\\Temp\\cis-benchmark-gpos\\LGPO.exe /g C:\\Users\\Administrator\\AppData\\Local\\Temp\\cis-benchmark-gpos\\cis\\USER-L1\\{DD55FCFF-4FC0-4FA0-9ABC-9D8402B8089E}"]
    },  
    {
      "type": "windows-shell",
      "remote_path": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\script.vbs",
      "execute_command": "cscript C:\\Users\\Administrator\\AppData\\Local\\Temp\\script.vbs",
      "scripts": [
        "./builder/setup-scripts/updates.vbs"
      ]
    }
  ]
}
```

Userdata:

```
<powershell>
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
write-output "Running User Data Script"

Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction Ignore

# Don't set this before Set-ExecutionPolicy as it throws an error
$ErrorActionPreference = "stop"

# Remove HTTP listener
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse

# Create a self-signed certificate to let ssl work
$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force

# WinRM
write-output "Setting up WinRM"
write-host "(host) setting up WinRM"

cmd.exe /c winrm quickconfig -q
cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
cmd.exe /c winrm set winrm/config/winrs '@{MaxShellsPerUser="100"}'
cmd.exe /c winrm set winrm/config/winrs '@{MaxConcurrentUsers="30"}'
cmd.exe /c winrm set winrm/config/winrs '@{MaxProcessesPerShell="100"}'
cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTPS" "@{Port=`"5986`";Hostname=`"packer`";CertificateThumbprint=`"$($Cert.Thumbprint)`"}"
cmd.exe /c netsh advfirewall firewall set rule group="remote administration" new enable=yes
cmd.exe /c netsh firewall add portopening TCP 5986 "Port 5986"
cmd.exe /c net stop winrm
cmd.exe /c sc config winrm start=auto
cmd.exe /c net start winrm
# Configure UAC to allow privilege elevation in remote shells
$Key = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
$Setting = 'LocalAccountTokenFilterPolicy'
Set-ItemProperty -Path $Key -Name $Setting -Value 1 -Force
Install-Module -Name PolicyFileEditor -RequiredVersion 3.0.0
</powershell>
```

**Comment by SwampDragons** [comment] 2021-02-18 18:14
Since this is a question and not a bug, it isn't super actionable, but I can give some advice before closing. 

The first thing I'd suggest is to check that you're able to manually connect via winrm after the hardening; e.g. after the hardening has run and while Packer is confused, can you actually connect to the instance outside of Packer?  You can use the --debug flag when calling Packer to cause it to freeze between steps, the --on-error=ask flag to cause it to pause when the connection fails, or the [breakpoint](https://www.packer.io/docs/provisioners/breakpoint) provisioner to freeze between provisioners, any one of which should prevent Packer from timing out and cleaning up the instance.

If you can't connect via WinRM manually, this is a configuration/hardening issue, not a Packer issue, and you need to figure out how to open you VM back up so you can still connect to it. Maybe save the hardening until the very last step in the Packer build so you don't have to reconnect to the VM. 

But if you can connect manually, then maybe something has changed about _how_ you need to connect to winrm. For example, domain joins often mess the Packer communicator up. See if you can shut down the VM and save it there, then launch a new packer build. These multi-stage builds can help work around connectivity changes. We have a little guide with a basic walkthrough of the concept of pipelining builds [here](https://www.packer.io/guides/packer-on-cicd/pipelineing-builds)

Anyway, that's my thoughts. I'm going to close this since I think this is Packer working as designed, and CIS hardening also working as designed.

**Closed by SwampDragons** 2021-02-18 18:14 UTC
Labels: communicator/winrm, question
