### ISSUE TITLE
azure-arm: elevated_user and elevated_password with powershell get "user name or password is incorrect"

### ISSUE THREAD

**Issue by r3dlin3** [hashicorp/packer#6169] opened 2018-04-20 15:33 UTC
- Packer v1.2.2
- Host platform: Windows

I cannot have an elevated session with powershell
I have tested 2 scenarios:
1. Setting the password in the communicator ("winrm_password": "...") and reusing this value in elevated_password 
2. Using the variable {{.WinRMPassword}}

None are working.
Note: I had to "ctrl-c" packer otherwise it was hanging

in the gist ( https://gist.github.com/r3dlin3/4af4a45d1cf62e19e51fa3a2550d63e7 ):
- The 2 packer file (scenario 1 or 2)
- The silly powershell script 
- The logs for scenario 1 (the error is the same in the

**Comment by SwampDragons** [comment] 2018-04-20 18:32
Thanks for opening this issue! I believe this is a duplicate of https://github.com/hashicorp/packer/issues/4818, so I'm going to close this and we can continue to track the issue there.

**Closed by SwampDragons** 2018-04-20 18:32 UTC
