### ISSUE TITLE
no_proxy for winrm

### ISSUE THREAD

**Issue by trevorndodds** [hashicorp/packer#5725] opened 2017-12-20 23:38 UTC
- Packer version from 1.1.3
- Host platform: Linux and Windows
- Guest: Windows
- Waiting to connect to WinRM...
   Sometimes it connects (see below), sometimes it throws back a Proxy error. 

ssh_interface (private) helps a little but still causes problems.

The issue I have is that we do not use the AWS DNS so adding .internal to our no_proxy doesn't help. However I can work around this by having a script update my hosts file with the IP/FQDN when using private_dns with the ssh_interface flag. While using the no_proxy=".internal", this works for the most part but it's not 100% reliable.  

When using private_ip Adding every IP to no_proxy doesn't help either as sometimes the IP given is at the end of the range which doesn't appear to work - probably due to an environment variable limitation. 

Is it possible to have packer automatically add the IP to no_proxy or append to it with the Private IP it gets as part of the boot sequence?

Thoughts?

**Comment by mwhooker** [comment] 2017-12-21 00:03
Thanks for the issue. I think this is very likely what was being reported in #5630.

seems like we have 3 options

1. add a flag to automatically add remote IP to no_proxy list
2. add a flag to disable `ProxyFromEnvironment` in the winrm communicator
3. make our own transport that supports CIDR notation in `NO_PROXY` (until this is added to go 1.11 https://github.com/golang/go/issues/16704)

#1 seems like the best way forward, but I can't help but feel it's extra special-casey. #3 seems most complete, but not sure it's worth it.

To reiterate the issue, so I understand: You are trying to build a windows AMI, and you want all aws API calls to go through a proxy, but for some reason you can't have connections to the source instance going through the same proxy?

I must admit I'm surprised this is such a common scenario.

**Comment by trevorndodds** [comment] 2017-12-21 00:32
Corporate Firewall and proxy cause lots of problems. Access to the AWS API calls have to go over the proxy to get to the internet, but ec2 instances are only accessible on a private AWS subnet. Given winrm uses HTTPS the connection is made over the proxy which is what we need to avoid since it should all be routed internally. 

no_proxy not supporting CIDR is a huge limitation. Thanks for the link!

#2 could be a cleaner solution than #1 for these edge cases. 

Thanks for helping with this issue!

**Comment by riponbanik** [comment] 2017-12-21 22:28
@trevorndodds @mwhooker what is the issue of allowing private_ip for winrm along with private_dns as it is for ssh?

**Comment by mwhooker** [comment] 2017-12-21 23:18
@riponbanik You can use `"ssh_interface": "private_ip"` when using winrm. Unfortunately we use the terms `ssh` and `winrm` interchangeably on that page. The problem is there's no way right now to set NO_PROXY to the private_ip. That's what this ticket is trying to resolve.

Do you have a proxy? Does setting `"ssh_interface": "private_ip"` resolve this for you?

**Comment by trevorndodds** [comment] 2017-12-21 23:47
@riponbanik  we have the same issue if I look at your #5629 ticket . This is what the ticket is for, to disable the proxy when making a winrm call when using "private_*" either through a flag or adding the private_ip to no_proxy when packer determines the ec2 IP. Whichever is the best approach.

If you use private_dns then no_proxy=.internal would work if you use AWS DNS as the FQDN is resolvable. In our case we use private DNS which is not able to resolve AWS hostnames so we have to workaround this by using the hosts file.

If you use private_ip then no_proxy would have to list out every IP in your VPC Subnet, this unfortunately doesn't really work. Well in my case it would only work if the IP of the ec2 instance was near the front of the list.

**Comment by riponbanik** [comment] 2017-12-28 23:37
@mwhooker  I tried with that and it does not work. @trevorndodds my no_proxy setting is like below, it works for other cases but not when I use private_ip for packer. private_dns works when I use host file like yours.

localhost,127.0.0.1,169.254.169.253,169.254.169.254,10.0.0.0/8,.internal

**Comment by gigawatts** [comment] 2018-01-24 22:15
I'm having the exact same issue as @trevorndodds , related to corporate proxies. I was able to get a work around to function by using a combination of "no_proxy" env variable and "ssh_interface": "private_dns" setting in the packer json (thank you all for those suggestions, by the way). 

Adding the ability to tell winrm communicator (via a flag) not to use the proxy so I can continue to just use IP addresses would make life / automation a lot easier.

**Comment by mwkaufman** [comment] 2018-01-31 20:10
I also have the same problem. Our AWS instances use on-premises DNS so can't use private_dns and all internet traffic has to go through the proxy so have to set that in order to talk to AWS. Completely blocked and can't use WinRM communicator at all unless I build the instances with public IPs which our security organization would never allow.

**Comment by mwhooker** [comment] 2018-02-08 05:00
Hi folks, curious if anyone can help me test the patchin https://github.com/hashicorp/packer/pull/5870

**Comment by gigawatts** [comment] 2018-02-08 14:22
I can try to help test it. Is there a compiled version already? If not, I
can try to setup the go requirements, it's just something I haven't done
before.

**Comment by mwkaufman** [comment] 2018-02-08 16:45
@mwhooker Trying it out, so far it hangs at "Waiting for WinRM to become available...". I can interact with WinRM over 5986 addressing by the private IP address. Here is some of my machine.json:

            "communicator": "winrm",
            "winrm_username": "user",
            "winrm_password": "pass",
            "winrm_use_ssl": true,
            "winrm_no_proxy": true,
            "ssh_interface": "private_ip",

I tried with and without the ssh_interface line and hit the same behavior. http_proxy, https_proxy, and no_proxy are set as environment variables providing access to the internet proxy which is working, but I don't know what's happening when it tries to reach out via WinRM.

**Comment by trevorndodds** [comment] 2018-02-08 16:50
Unfortuantly no luck on my side.

Packer v1.1.4-dev
            "winrm_no_proxy": true,
```
WinRMInsecure:true WinRMNoProxy:true WinRMPassword: WinRMPort:5986 WinRMTimeout:30m0s WinRMUseNTLM:false WinRMUseSSL:true WinRMUser:Administrator

2018/02/08 11:45:13 packer: 2018/02/08 11:45:13 [INFO] Attempting WinRM connection...
2018/02/08 11:45:13 packer: 2018/02/08 11:45:13 [DEBUG] connecting to remote shell using WinRM
2018/02/08 11:46:28 packer: 2018/02/08 11:46:28 [ERROR] connection error: http response error: 503 - invalid content type
2018/02/08 11:46:28 packer: 2018/02/08 11:46:28 [ERROR] WinRM connection err: http response error: 503 - invalid content type
```

**Comment by mwhooker** [comment] 2018-02-08 17:48
thanks for the testing all. Will see if I can reproduce on my own to see what's going on

**Comment by gigawatts** [comment] 2018-03-07 15:19
Any update on another patch we can test out for this? If you don't have a good way to replicate this issue, I certainly do!

**Comment by casey-robertson** [comment] 2018-03-15 19:12
Anybody having this issue on vSphere?  Similar in that autounattend.xml works fine, updates install etc but Packer gets to the winrm connection phase and sits forever until timing out.

**Comment by SwampDragons** [comment] 2018-04-24 18:26
Just an update: this is going to be fixed in golang in a few months; we're unlikely to find the bandwidth to create a temporary workaround before then; if someone else wants to tackle it we'll review a patch, but otherwise I think we're gonna move this to "watchful waiting".  Apologies for how long this has taken.  

See https://github.com/golang/go/issues/16704 for full context on the golang issue. Golang 1.11 is supposed to be released in July 2018.

**Comment by SwampDragons** [comment] 2018-09-04 22:41
With golang 1.11 out, this is should be fixed. I'm gonna attach a few builds of the master branch on golang 1.11 for y'all to sanity test if you want something ahead of the next release; please let me know if anyone is still seeing issues: 

linux build: 
[packer.zip](https://github.com/hashicorp/packer/files/2350483/packer.zip)

osx build: 
[packer.zip](https://github.com/hashicorp/packer/files/2350487/packer.zip)

windows build: 
[packer.zip](https://github.com/hashicorp/packer/files/2350501/packer.zip)

**Closed by SwampDragons** 2018-09-04 22:41 UTC
Labels: bug, builder/amazon, communicator/winrm, upstream-bug

**Comment by theemptyone** [comment] 2018-09-19 18:16
Is there an active thread for winrm_no_proxy? I'd like to track that.. thanks.

**Comment by SwampDragons** [comment] 2018-09-19 22:29
I don't think there is. If there is something still not working for you, can you please open a new ticket with detailed steps to reproduce?

**Comment by gigawatts** [comment] 2018-09-19 22:35
Which released version # contains the fix?

**Comment by SwampDragons** [comment] 2018-09-19 22:37
1.3.0, but there were a couple of rough bugs in that release so I'd recommend trying 1.3.1 instead. the "fix" was updating golang to v1.11 and 1.3.0 is the first release we did on that version of golang.

**Comment by theemptyone** [comment] 2018-09-26 13:29
Still not seeing this option available:

```
$ packer build --var-file vars/win2016.json win_base.json
win2016-vmware output will be in this color.

1 error(s) occurred:

* unknown configuration key: "winrm_no_proxy"
$ packer --version
1.3.1
$ grep winrm win_base.json
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "winrm_no_proxy": true,
```

I'm sorry if i'm missing something obvious.

**Comment by azr** [comment] 2018-09-26 13:46
Hello @theemptyone, does setting the `NO_PROXY` or the `no_proxy` env var works for you ?

i.e: `export NO_PROXY=s3.amazonaws.com,localhost,127.0.0.1,169.254.169.254,10.0.0.0/8"`

**Comment by theemptyone** [comment] 2018-09-26 13:52
My situation is using vmware workstation on a local linux machine.  The VMWare Workstation builder uses dhcp for the host build, and never exposes the IP.  I've not seen any way to set the IP in packer, so there is no way to predict what IP will be in use in order to add it to the no_proxy preemptively.

I've been able to continue my testing because vmware will re-use an ip more often then not in rebuilds, so i've been able to wrap packer in a bash shell that sets the no_proxy, but this is not a workable solution outside of my test space.

I'm concurrently trying to determine if i hard code an IP in the VMX if packer will consume it.

Unless I'm able to set the ip specifically, or disable winrm's use of a proxy.. i'm not quite sure what I'm going to do from an automation standpoint.

**Comment by theemptyone** [comment] 2018-09-26 15:14
I do not believe this ip range thing works with curl (which is how winrm validation works).  At least not on CentOS/RHEL.  I researched it a bit to try to solve this problem a week ago or so.  The documentation says that it cannot understand ip ranges or cidr, only wildcards in domains.

My testing at the time proved this out.

See: https://github.com/curl/curl/issues/1208

**Comment by azr** [comment] 2018-09-27 09:51
So, when Packer is configured for an outbound proxy but the WinRM traffic should be direct, this is where the `NO_PROXY` setting is useful and this is what this issue is about.

I believe your issue is a totally different issue @theemptyone, can you please open a new ticket with some context and what you need ?
Even better would be a contribution 🙂 

Thanks!

**Comment by theemptyone** [comment] 2018-09-27 15:07
I can open a new issue, but really all i need is the winrm_no_proxy flag that's mentioned in this thread.  Maybe I misunderstood the thread, and that option was to fix something (and then reverted) that was fixed by an underlying go issue.

I"d love to contribute :( but sadly i do not know go.  You would not appreciate anything that i contributed :)
