### ISSUE TITLE
Packer doesn't run provisioning script

### ISSUE THREAD

**Issue by thehhugg** [hashicorp/packer#7949] opened 2019-08-05 17:01 UTC
Packer erroneously thinks it's running a provisioning script, but it's not. I know that's a really simplistic explanation, but there's not much info in the output to elaborate further. I've tried with both an actual provisioning script as well as a hello world script, and both run with 0 output to stdout and stderr, and no changes to the builder host. 

```
(⎈ |dev:dev)➜  packer-image git:(packer-image) ✗ packer version
Packer v1.4.1
```

```
Oracle Enterprise Linux 7.6
```

Debug output:
https://gist.github.com/thehhugg/7230b48b2bb2c12b882ac8316798678e

image.json:
https://gist.github.com/thehhugg/f92ae3008ad46b4ccd9208b1052ad758

As I mentioned, this behavior occurs with both a longer provisioning script as well as a simple hello world:

```
#!/usr/bin/env bash
echo "hello world"
```

I've tried the following formats for `execute_command`, all with the same results:

```
sudo bash -c -E {{ .Vars }} {{ .Path }}
sudo bash -c {{ .Vars }} {{ .Path }}
sudo sh -c {{ .Vars }} {{ .Path }}
```

**Comment by rickard-von-essen** [comment] 2019-08-05 20:17
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by thehhugg** [comment] 2019-08-12 18:13
Sure. I included what seems to be the relevant section in the gist I linked above, but the full output is here: https://gist.github.com/thehhugg/3a43da7a71ab5345f10229f904885fc4

**Comment by SwampDragons** [comment] 2019-08-12 22:16
Update: Sorry for the late response; I was on vacation. I am able to reproduce using your template. I'll try to investigate further as soon as possible.

**Comment by SwampDragons** [comment] 2019-08-15 23:58
Thanks for your patience on this. I think this is an issue with the execute_command you're using. Try wrapping the command itself in single quotes so that they get called together.

`"execute_command": "sudo bash -c -E '{{ .Vars }} {{ .Path }}'"`

**Comment by SwampDragons** [comment] 2019-10-17 23:37
Closing because I never heard back. We can reopen if the above execute_command didn't solve the issue.

**Closed by SwampDragons** 2019-10-17 23:37 UTC
Labels: builder/oracle-oci, provisioner/shell
