### ISSUE TITLE
vsphere-iso provisioner "format" default incorrectly documented

### ISSUE THREAD

**Issue by tthayer** [hashicorp/packer#6147] opened 2018-04-17 15:34 UTC
https://github.com/hashicorp/packer/blame/master/website/source/docs/builders/vmware-iso.html.md#L588 states that the default format is 'ovf', but it looks like it actually defaults to something else in Packer 1.2.1. I was running into problems chaining the vsphere and vsphere-template post-provisioners because packer was deleting the built image before the post-provisioners could actually process them: 

```bash
==> vmware-iso: Skipping export of virtual machine...
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 opening new ssh session
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 starting remote command: vim-cmd vmsvc/power.getstate 14
2018/04/17 07:45:35 ui: ==> vmware-iso: Unregistering virtual machine...
==> vmware-iso: Unregistering virtual machine...
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 opening new ssh session
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 starting remote command: vim-cmd vmsvc/unregister 14
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 Deleting floppy disk: /tmp/packer521460602
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 opening new ssh session
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 starting remote command: ls -1p /vmfs/volumes/datastore1/output-vmware-iso
2018/04/17 07:45:35 [INFO] (telemetry) ending vmware-iso
2018/04/17 07:45:35 ui: ==> vmware-iso: Running post-processor: vsphere
2018/04/17 07:45:35 [INFO] (telemetry) Starting post-processor vsphere
==> vmware-iso: Running post-processor: vsphere
2018/04/17 07:45:35 ui:     vmware-iso (vsphere): Uploading /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx to vSphere
    vmware-iso (vsphere): Uploading /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx to vSphere
2018/04/17 07:45:35 packer: 2018/04/17 07:45:35 Starting ovftool with parameters: --acceptAllEulas --name=rhel-7.4.0.5 --datastore=datastore1 --noSSLVerify=true --diskMode=thin --vmFolder=PackerTemplates --network=**** --ove
rwrite /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx vi://****:<password>@****/test/host/****
2018/04/17 07:45:36 [INFO] (telemetry) ending vsphere
2018/04/17 07:45:36 Deleting original artifact for build 'vmware-iso'
2018/04/17 07:45:36 packer: 2018/04/17 07:45:36 opening new ssh session
2018/04/17 07:45:36 packer: 2018/04/17 07:45:36 starting remote command: rm -rf /vmfs/volumes/datastore1/output-vmware-iso
Build 'vmware-iso' errored: 1 error(s) occurred:
2018/04/17 07:45:37 ui error: Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Error: Failed to open file: /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx
Completed with errors


2018/04/17 07:45:37 Builds completed. Waiting on interrupt barrier...
2018/04/17 07:45:37 machine readable: error-count []string{"1"}
2018/04/17 07:45:37 ui error:
==> Some builds didn't complete successfully and had errors:
2018/04/17 07:45:37 machine readable: vmware-iso,error []string{"1 error(s) occurred:\n\n* Post-processor failed: Failed: exit status 1\nError: Failed to open file: /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx\nCompleted with
 errors\n\n"}
2018/04/17 07:45:37 ui error: --> vmware-iso: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Error: Failed to open file: /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx
Completed with errors

2018/04/17 07:45:37 ui:
==> Builds finished but no artifacts were created.
2018/04/17 07:45:37 [INFO] (telemetry) Finalizing.

* Post-processor failed: Failed: exit status 1
Error: Failed to open file: /vmfs/volumes/datastore1/output-vmware-iso/rhel-7.vmx
Completed with errors
```

Simply setting `"format": "ovf",` in my vmware-iso builders section resolved the problem.

- Packer version from `packer version`: `1.2.1`
- Host platform: `rhel7-64`

**Comment by tthayer** [comment] 2018-04-17 15:39
On review, it doesn't look like any default is set. Shouldn't this error out? https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/builder.go#L212

**Comment by SwampDragons** [comment] 2018-04-23 16:18
@mwhooker this looks related to an old unmerged PR of yours -- https://github.com/hashicorp/packer/pull/4538 Any thoughts on this?

**Comment by mwhooker** [comment] 2018-04-23 17:25
Yeah, going to mark this as a dupe of #3385.

@tthayer If you can help me test #4538, I can merge it in

**Closed** 2018-04-23 17:26 UTC
Labels: bug, builder/vmware
