### ISSUE TITLE
Build 'amazon-ebs' errored: Error waiting for AMI. Reason <nil>

### ISSUE THREAD

**Issue by LazzariPaolo** [hashicorp/packer#8792] opened 2020-02-24 11:03 UTC
## Overview of the Issue
I am running Packer builds for an amazon-ebs. The Packer build is driven by a .pom file execution, which runs the docker-maven-plugin from **hashicorp/packer:1.5.4**

This issue happens pretty frequently, but not always. 

### Maven .pom file 
```
<plugin>
    <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
            <version>0.31.0</version>
            <executions>
            <!-- Packer -->
             <execution>
                 <id>Packer build</id>
             <goals>
                 <goal>start</goal>
                 <goal>stop</goal>
             </goals>
             <phase>generate-resources</phase>
              <configuration>
              <images>
                  <image>
                      <name>hashicorp/packer:1.5.4</name>
...
...
```

### Packer .json file

```
{
    "variables": {
        "AWS_INSTANCE_PROFILE": "",
        "MANIFEST_OUTPUT_FILE": "manifest.json"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "region": "us-east-1",
            "iam_instance_profile": "{{user `AWS_INSTANCE_PROFILE`}}",
            "source_ami": "ami-0a313d6098716f372",
            "instance_type": "t3.2xlarge",
            "ssh_username": "ubuntu",
            "launch_block_device_mappings": [
                {
                    "device_name": "/dev/sdb",
                    "volume_size": 128,
                    "volume_type": "gp2",
                    "delete_on_termination": true
                  },
                  {
                    "device_name": "/dev/sda1",
                    "volume_size": 128,
                    "volume_type": "gp2",
                    "delete_on_termination": true
                  }
            ],
            "ami_block_device_mappings": [
                {
                  "device_name": "/dev/sdb",
                  "no_device": true
            }
            ],
        }
    ],
    "provisioners": [
       {
            "script": "install.sh",
            "expect_disconnect": false
        },
    ],
    "post-processors": [
        {
          "type": "manifest",
          "output": "{{user `MANIFEST_OUTPUT_FILE`}}",
          "strip_path": true
        }
      ]
}
```

### Packer version

1.5.4

### Operating system and Environment details

Packer execution runs inside Docker container.

### Log Fragments and crash.log files

> cf3bf6> ==> amazon-ebs: Stopping the source instance...
> cf3bf6>     amazon-ebs: Stopping instance
> cf3bf6> ==> amazon-ebs: Waiting for the instance to stop...
> cf3bf6> ==> amazon-ebs: Creating AMI xxx from instance i-xxx
> cf3bf6>     amazon-ebs: AMI: ami-xxx
> cf3bf6> ==> amazon-ebs: Waiting for AMI to become ready...
> cf3bf6> ==> amazon-ebs: Error waiting for AMI. Reason: <nil>
> cf3bf6> ==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
> cf3bf6> ==> amazon-ebs: Terminating the source AWS instance...
> cf3bf6> ==> amazon-ebs: Cleaning up any extra volumes...
> cf3bf6> ==> amazon-ebs: Deleting temporary security group...
> cf3bf6> ==> amazon-ebs: Deleting temporary keypair...
> cf3bf6> Build 'amazon-ebs' errored: Error waiting for AMI. Reason: <nil>
> cf3bf6>
> cf3bf6> ==> Some builds didn't complete successfully and had errors:
> cf3bf6> --> amazon-ebs: Error waiting for AMI. Reason: <nil>
> cf3bf6>
> cf3bf6> ==> Builds finished but no artifacts were created.

As you can see, the Packer execution fails which means that the "manifest.json" file is never created. I depend on a 0 error code from Packer, as well as the creation of the "manifest.json" file for the next stages of my automated build.

What is curious however, is that the AMI is actually successfully created and I can see it in the list of AMIs in the AWS console.

How can I resolve this error, so that the process ends with exit code 0 and the "manifest.json" file is created correctly?

**Comment by sylviamoss** [comment] 2020-02-25 12:56
Hi @LazzariPaolo, thanks for reaching out! 
I haven't tried to reproduce this but I realized your provisioner is missing the type definition. Could add it and try building again? I think you're using the shell provisioner so that will be like:
```
 "provisioners": [
       {
            "type": "shell",
            "script": "install.sh",
            "expect_disconnect": false
        },
    ]
```
Since the build is failing in the provision par, maybe this can be the reason 🤔

**Comment by LazzariPaolo** [comment] 2020-02-25 13:01
Hi @sylviamoss ,

Thanks for the comment. I indeed have the type definition in the Packer config file, I just missed adding it to my first post.

**Comment by SwampDragons** [comment] 2020-02-28 19:40
I would normally expect a value in that error if it's timeout related, but you could try the suggestions here to see if they also resolve a "nil" error value: https://packer.io/docs/builders/amazon.html#resourcenotready-error

you may get more useful information if you set PACKER_LOG=1 in your environment.

**Comment by SwampDragons** [comment] 2020-03-23 22:17
Is this still an issue for you? If so, can you please share the verbose debug logs from a build (set env var PACKER_LOT=1)? Thanks.

**Comment by nywilken** [comment] 2020-04-30 17:40
Hi @LazzariPaolo  I'm closing this issue since there have been no updates in the past 30 days. If this is still an problem please open a new [bug report](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) with the information requested in the template. Cheers!

**Closed by nywilken** 2020-04-30 17:40 UTC
Labels: bug, builder/amazon, waiting-reply
