### ISSUE TITLE
amazon-ebs: When copying ami to one or more regions in ami_regions packer should check the ami names in ami_regions not the one listed in region

### ISSUE THREAD

**Issue by JoeyG1973** [hashicorp/packer#7198] opened 2019-01-15 01:29 UTC
We are using ami_regions to propagate encrypted AMIs.  

**Run 1:**

```
"ami_name": "my_ami_name"
"region": "us-east-1"
"ami_regions": ["us-east-1"]
region_kms_key_ids: {"us-east-1: "my_region_kms_key"}
```

Everything works as expected, creates a temporary unencrypted ami that then creates the final encrypted ami in the same region.

**Run 2:**
```
"ami_name": "my_ami_name"
"region": "us-east-1"
"ami_regions": ["us-west-2"]
region_kms_key_ids: {"us-west-2: "my_region_kms_key"}
```
Packer fails as there is already an AMI in us-east-1 named "my_ami_name".

Packer should not be checking if an AMI name exists in the "region" string.  Instead it should check if an AMI name exists in each item in the "ami_regions" list.

I cannot use the force_deregister argument as that will delete the existing ami deployed in Run 1. 

- Packer version: 1.3.1
- Host platform: Linux

**Comment by SwampDragons** [comment] 2019-05-15 21:58
I'm closing this as a duplicate of #7199

**Closed by SwampDragons** 2019-05-15 21:58 UTC
Labels: builder/amazon, duplicate, enhancement
