### ISSUE TITLE
Shell provisioner failing to run

### ISSUE THREAD

**Issue by uberjew666** [hashicorp/packer#6241] opened 2018-05-04 10:58 UTC
When provisioning an Ubuntu 16.04 VM, it hangs at running shell scripts. I've tried both scripts and script parameter and it fails on both.
If I ssh to the host before Packer destroys the VM, the script file does exist in /tmp however it's empty.

I've tried version 1.2.3, 1.2.2 and finally 1.1.3.
This issue doesn't happen in 1.1.3, it executes correctly.

- Packer version 1.2.2 + 1.2.3
- Windows 10 1703 15063.0
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/uberjew666/68020ca2aea991b71bda2ed94dfecbfd
- The _simplest example template and scripts_ needed to reproduce the bug.
  https://gist.github.com/uberjew666/68020ca2aea991b71bda2ed94dfecbfd

**Comment by SwampDragons** [comment] 2018-05-04 16:13
Thanks for opening a ticket; I believe this is a duplicate of #6151.  You can find a patched build in the discussion on that ticket.  I'm going to close this as a duplicate, but please let me know on #6151 if the patch doesn't solve your issue.

**Closed by SwampDragons** 2018-05-04 16:13 UTC
