### ISSUE TITLE
vagrant builder ssh connection error

### ISSUE THREAD

**Issue by acikogun** [hashicorp/packer#8818] opened 2020-03-02 02:46 UTC
Hi all,

I'm trying to build a custom vagrant box based on "ubuntu/bionic64" box.
My configuration is here:

> 
    "provisioners": [
        {
          "type": "shell",
          "script": "install.sh"
        }
      ],

    "builders": [
        {
          "ssh_username": "vagrant",
          "ssh_password": "vagrant",
          "ssh_port": 22,
          "source_path": "ubuntu/bionic64",
          "provider": "virtualbox",
          "add_force": true,
          "type": "vagrant"
        }
      ],

    "post-processors": [
        {
          "type": "vagrant-cloud",
          "box_tag": "acik/winit",
          "access_token": "{{user `cloud_token`}}",
          "version": "{{user `version`}}"
        }
      ]

It gives the error:

> ==> vagrant: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

It can't login to source box. But the documentation remarks [here](https://packer.io/docs/builders/vagrant.html):

> A note on SSH connections
Currently this builder only works for SSH connections, and automatically fills in all information needed for the ssh communicator using vagrant's ssh-config.

I understand that it will login as default "vagrant" user.

I'm not sure is it a bug or missing configuration by me.

Packer version: **1.5.4**
Host: Windows **1909**
VirtualBox version: **6.1.4**

Thank you!

**Comment by joshuadoss** [comment] 2020-03-02 18:22
@acikogun Try removing the ssh_* directives from your configuration, add "communicator": "ssh", to the builder block, and try again.

**Comment by acikogun** [comment] 2020-03-02 19:11
I've already tried that before this configuration. It throws the same error.

**Comment by dougschremp** [comment] 2020-03-02 23:18
I have this same basic issue. I can login to the source box with 
vagrant ssh source with in the output-vagrant directory and the vagrant ssh-config source command outputs the correct information for the login process. 

This seems to be a packer here are my version:

Packer: 1.5.4 
Host: Mac OS : Darwin Kernel Version 17.7.0
Virtual Box: 6.1.4


Here is the output of vagrant ssh-config source

vagrant ssh-config source
Host source
  HostName 127.0.0.1
  User vagrant
  Port 2201
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/XXX/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

**Comment by SwampDragons** [comment] 2020-03-02 23:20
I can confirm that this is a regression in v1.5.2 and higher. Working on a fix now.

**Comment by SwampDragons** [comment] 2020-03-03 00:30
I've got a PR open with a fix -- @joshuadoss's suggestion is correct and will work after this PR is merged. Binaries of that branch can be found at https://circleci.com/gh/hashicorp/packer/36144#artifacts/containers/0

**Comment by acikogun** [comment] 2020-03-03 01:07
It works now. Thank you!

**Closed** 2020-03-03 01:07 UTC
Labels: builder/vagrant, question

**Comment by dougschremp** [comment] 2020-03-03 01:32
Fixed for Darwin/Mac OS as well. thank you for the very quick fix on this.
