### ISSUE TITLE
GCP: requested default disk size is smaller than provided disk size

### ISSUE THREAD

**Issue by loibpet** [hashicorp/packer#9033] opened 2020-04-09 12:52 UTC
#### Overview of the Issue

Using a configuration which does not define the disk size for GCP, i.e. we are using the default disk size as provided by Google.

### Packer version

1.5.4

### Issue

As of today, GCP seems to use default disk sizes larger than 10GB. This results in errors, e.g for RedHat 7 or CentOS 7.

`Build 'googlecompute' errored: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.diskSizeGb': '10'. Requested disk size cannot be smaller than the image size (20 GB), invalid
`

Adding the "disk_size": "20" definition to the configuration solves the issue.

**Comment by SwampDragons** [comment] 2020-04-09 21:49
Hi, thanks for reporting this. I think this is a duplicate of #9033, so I'm going to close and we can track the work there.

**Closed by SwampDragons** 2020-04-09 21:49 UTC
Labels: bug, builder/google, duplicate
