### ISSUE TITLE
why,ansible-playbook，error, on windows 

### ISSUE THREAD

**Issue by aftree** [hashicorp/packer#8402] opened 2019-11-22 01:44 UTC
alicloud-ecs: ansible-playbook 2.9.1
    alicloud-ecs:   config file = /etc/ansible/ansible.cfg
    alicloud-ecs:   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
    alicloud-ecs:   ansible python module location = /usr/lib/python2.7/site-packages/ansible
    alicloud-ecs:   executable location = /usr/bin/ansible-playbook
    alicloud-ecs:   python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
    alicloud-ecs: Using /etc/ansible/ansible.cfg as config file
    alicloud-ecs: host_list declined parsing /tmp/packer-provisioner-ansible575023347 as it did not pass its verify_file() method
    alicloud-ecs: script declined parsing /tmp/packer-provisioner-ansible575023347 as it did not pass its verify_file() method
    alicloud-ecs: auto declined parsing /tmp/packer-provisioner-ansible575023347 as it did not pass its verify_file() method
    alicloud-ecs: Parsed /tmp/packer-provisioner-ansible575023347 inventory source with ini plugin
    alicloud-ecs:
    alicloud-ecs: PLAYBOOK:analytics.yml *********************************
    alicloud-ecs: 1 plays in /ppp/scripts/ansible/playbooks/production/analytics.yml
    alicloud-ecs: [WARNING]: Could not match supplied host pattern, ignoring: windows
    alicloud-ecs:
    alicloud-ecs: PLAY [windows] *****************************************************************
    alicloud-ecs: skipping: no hosts matched
    alicloud-ecs:
    alicloud-ecs: PLAY RECAP *********************************************************************
    alicloud-ecs:

**Comment by nywilken** [comment] 2019-11-25 18:08
Hi, thanks for reaching out. 

The Ansible provisioner is community-supported, so this may be a situation where you get a better experience asking the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help, since issues are mostly only read by maintainers. 

I'm going to close this issue as this appears to be more of an Ansible playbook related issue, than a provisioner related issue. If I made a mistake and you believe this is a Packer issue please create a new issue using the [Bug Report](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) template with the requested reproduction steps and debug logs. Cheers :smile:

**Closed by nywilken** 2019-11-25 18:08 UTC
Labels: question
