### ISSUE TITLE
Issues with handling reboots

### ISSUE THREAD

**Issue by b00ga** [hashicorp/packer#3487] opened 2016-05-02 01:39 UTC
I'm using the templates and scripts from the [Bento project](https://github.com/chef/bento) to build baseboxes for internal use at work. Since the last time I spun images in January, Bento has added a reboot after performing a dist-upgrade on Ubuntu platforms using the suggested method in the [Packer docs](https://www.packer.io/docs/provisioners/shell.html) (reboot + sleep). [Bento Ubuntu 16.04 packer template](https://github.com/chef/bento/blob/master/ubuntu-16.04-amd64.json) - [Bento Ubuntu update script](https://github.com/chef/bento/blob/master/scripts/ubuntu/update.sh)

I observed three issues relating to the rebooting. First, not all the commands in the update.sh run (looking at the update.sh linked above, teh /etc/init/refresh-apt.conf file never gets created. I think this is a Bento bug that they should have the reboot as the last thing in the script and plan on reporting this up to them). 

Second, intermittently, the Packer run hangs. I only saw this on 16.04 (not on 12.04 or 14.04) and always seemed to happen during the wget of the insecure ssh key during bento's vagrant.sh script.

Lastly, in all cases (at least for 12.04, 14.04, 16.04 Ubuntu) observing with headless=false, even with the reboot/sleep, once the reboot command initiated, more scripts from the packer template started running, despite the reboot having not actually happened yet. I suspect this is what was causing my hangs above.

I have a theory on what is happening and have tested a fix that appears to work and this GH issue is to request so discussion and perhaps changing the "Handling Reboots" documentation for the shell provisioner.

What I believe is happening is, once the reboot command is issue, the sleep immediately after starts. However, as part of the reboot process, the OS starts killing user processes. I speculate that the reboot actually kills the sleep as part of the shutdown process, BUT sshd is still running, so packer detects termination of the script that ran the sleep, and happily starts running the next scripts specified as shell provisioners, even though the system hasn't rebooted yet. Then you get a reboot in some non-deterministic point in shell provisioning.

Here's what I tried instead and observed behaves more like one expects (execute reboot, next shell provisioners don't run until reboot is complete).  Most OpenSSH start/stop scripts will only stop the port 22 listener when you stop the ssh service (not any user-session sshd's that get spawned on a login). Since sshd is no longer running *until started up again on startup), packer cannot login to run more scripts, and patiently waits for ssh to become available again. Instead of sleeping or trying to stop the network interface, I suggest stopping sshd prior to reboot. So instead of:
reboot
sleep 60
Something like:
service ssh stop
reboot

Observing a packer run with headless=false showed me more what I was expecting and appeared much more deterministic than the current recommended way of handling reboots.

Please let me know if this makes sense, if you have any questions, and if I can provide any additional information.  I think the note about "sleep 60" and about "/etc/init.d/net.eth0 stop" in the shell provisioner docs may both be unnecessary with this approach and I can generate a PR for the docs with such if my approach seems reasonable. Would love to hear other people's opinions and further testing/debugging to see if I'm on point with what is happening.

Thanks,
-Shawn

**Comment by kwilczynski** [comment] 2016-05-06 19:20
@b00ga have you tried bringing the network interface down just before the reboot? It would force SSH communicator to try to reconnect, instead of hanging waiting.

**Comment by cbednarski** [comment] 2016-05-07 04:16
`dist-upgrade` is a convenience feature but it is super unreliable and non-deterministic and we do not support this. I'm not sure Canonical does either -- the rule of thumb is always to do a fresh install in these cases, and with packer that is easy!

When you run `dist-upgrade` you may notice a large disclaimer printed that ssh connections may not work reliably and you may lose your connection to the host at some point. Since you can tell packer to use the latest release ISO I don't see why you wouldn't do this, since it's much easier. I think we should add a note to the docs explaining that you should not expect `dist-upgrade` to work with packer or even at all, and there's probably a better way to do whatever it is you're trying to do there.

> reboot
> sleep 60
> Something like:
> service ssh stop
> reboot

If you find this works for you, please use this. However this is OS-specific and there are a wide range of linux flavors that have different (and possibly non-deterministic) behavior in this regard, so this is not really something we can fix or prescribe in packer.

I'd be happy to include some non-prescriptive recommendations in the documentation for this: For example, "You may encounter a race condition in which your ssh session is evicted before openssh is shutdown, resulting in packer thinking the box has restarted prematurely. To work around this try..."

It might make sense to add a `wait_before` type of parameter to the shell provisioner to make packer wait an arbitrary amount of time before continuing to the next provisioner, which may help alleviate these types of race conditions. This is agnostic to whatever weirdness might be happening inside the VM and will be more reliable than a sleep, which relies on the VM cooperating with you. I've created a new ticket for this here: https://github.com/mitchellh/packer/issues/3508

I'm not sure what headless=false has to do with the above, but if there's something I missed in your original issue please point it out.

**Comment by kwilczynski** [comment] 2016-05-07 09:11
@cbednarski I had similar issues with CentOS 7, which obviously does not have the "dist-upgrade" problem (which isn't really a problem - for 12.04 in the past I was upgrading OpenSSH server from a PPA, so that I have 6.x, and the same problem can manifest itself once the sshd is restarted).It would be nice to fix this somehow by a virtue of SSH communicator having a probe-alike facility (just an idea), where if certain number of probes would fail, then it would make an attempt to recover. Might not be an easy fix, albeit I am not sure how "wait_before" would solve this problem where it seem that the resiliency of the SSH communicator would benefit from being improved. What do you think?

**Comment by cbednarski** [comment] 2016-05-10 07:29
As @vtolstov kindly pointed out in #3508 there is already a [`pause_before` option](https://www.packer.io/docs/templates/provisioners.html) documented on the provisioners page, which I think should help with the reboot issue.

> where if certain number of probes would fail, then it would make an attempt to recover.

I may not be understanding what you mean by "probe" but we do attempt to reconnect if SSH is not available. The problem here is not about reconnecting, it's about packer being unable to introspect very specific states and transition events of multiple processes inside the VM, which frankly is quite complicated. We could have any of these scenarios:

- machine is rebooted
- machine is powered off
- openssh stopped
- openssh restarted
- connection was lost because of network failure
- connection was terminated by killing the process
- connection was terminated by a firewall
- possibly a dozen other strange scenarios I haven't thought of

Even if we could differentiate between these types of events it doesn't really make sense to expose all of these things to end users because A. they may not be using ssh anyway, B. the configuration gets extremely complicated, and C. most of the time it doesn't actually matter.

> I am not sure how "wait_before" would solve this problem where it seem that the resiliency of the SSH communicator would benefit from being improved.

The original post describes this scenario:

> What I believe is happening is, once the reboot command is issue, the sleep immediately after starts. However, as part of the reboot process, the OS starts killing user processes. I speculate that the reboot actually kills the sleep as part of the shutdown process, BUT sshd is still running, so packer detects termination of the script that ran the sleep, and happily starts running the next scripts specified as shell provisioners, even though the system hasn't rebooted yet.

In this case, `pause_before` will help because it introduces an arbitrary delay between the commands, which should give the OS time to shut down and restart properly without packer trying to reconnect.

**Comment by kwilczynski** [comment] 2016-05-10 07:52
@cbednarski I did try to use `pause_before` as it is indeed in the documentation, but it didn't worked for me, as when the provisioner would ender this frozen-alike state (after a reboot, or anything happening to the SSH connection), it would never progress beyond it, sadly, it would sit there for a quite some time...

The "probe" (for lack of better analog, apologies) would be something that could check if there was any activity on the session/channel/whatnot in/out from the remote node, or perhaps an attempt to establish a new session within the same connection on a periodic basis to see if the remote end is responding, if not then try to reconnect. Basically, something to periodically check if the other side is still alive. It would be agnostic to the root cause. I am not sure if something like this would be feasible or not.

We had something very similar to deal with in the past: https://github.com/mitchellh/packer/issues/200

For the time being, the only thing that seemed to solve the issue for me, for both the CentOS 7 and Ubuntu 16.04, is the following in the `reboot.sh`:

```
if ifconfig &>/dev/null; then
    ifconfig eth0 down
    ifconfig eth0 up
else
    ip link set eth0 down
    ip link set eth0 up
fi

shutdown -r now
sleep 60
```

This seem consistently allows for provisioner to continue after a reboot and eventually finish.

**Comment by vtolstov** [comment] 2016-05-10 08:51
Yes, some OS have this strange things. I'm prefer to run script in background with nohup.
This script kill sshd and shutdown interface, after that sync and reboot -f .
In this case reboot -f forcebly reboot machine.

**Comment by cbednarski** [comment] 2016-05-10 18:41
> The "probe" (for a lack of better analogy, apologies) would be something that could check if there was any activity on the session/channel/whatnot in/out from the remote node, or perhaps an attempt to establish a new session within the same connection on a periodic basis to see if the remote end is responding, if not then try to reconnect. Basically, something to periodically check if the other side is still alive. It would be agnostic to the root cause. I am not sure if something like this would be feasible or not.

@kwilczynski I see. I think we could potentially track the pid for the spawned process and use another SSH connection to see if it is still alive. Possibly there's something we can do over a single connection, too (perhaps multiplexing or tunneling) but these things are quite complicated! I am by no means an expert in SSH so there may be some approaches here I don't know about.

For this issue, though, I'm not sure how I would inspect (essentially debug) the VM given this is all happening during the shutdown process and the SSH connection is going to be terminated, and new ones will not work (and this is expected).

If the problem is that openssh does not do a clean shutdown and/or the OS kills it or the network first, these are different failure modes that we likely cannot inspect at the OS level. We can observe some things from outside but we don't really have insight into or control over what a specific OS is doing during shutdown, and honestly I don't want Packer to take on that responsibility because it is going to be very particular to the OS / Distro / Version.

_Maybe_ we can inspect e.g. power status of the VM at the hypervisor level for VBox and VMware but for AWS, Google, etc. we don't have that capability, so I'm not sure that's a real solution either.

> the provisioner would ender this frozen-alike state (after a reboot, or anything happening to the SSH connection), it would never progress beyond it, sadly, it would sit there for a quite some time...

It sounds like packer is waiting for something to timeout. Maybe that is a TCP connection or maybe it is attempting to reconnect and failing. I think it is best to make packer resilient to these types of issues, as you noted in #200 perhaps we are not properly detecting when the connection is dropped. If packer continues after the timeout then I think it is already working correctly, and if we can detect this type of expected failure sooner then we can continue sooner and thus improve things.

I am sure things could be improved here, but given the complexity and my lack of familiarity I think this will take quite some time, and so for me the cost / value tradeoff here is pretty low relative to other work in my pipeline. I am open to new ideas and information on this topic but I don't think I have more to add without doing a deep dive into this for a few days, which I don't have time to do right now.

@b00ga I realize there's a lot of chatter in this issue but if anything has helped so far, or if you are still having problems, or if we are all off-base, please feel free to leave a note.

**Comment by b00ga** [comment] 2016-05-11 14:42
@cbednarski No problem with the chatter.  I have a few more thoughts on this but I  was pulled away from my packer work shortly after i posted this issue. I'll be working on this again in the next week and have an opportunity to test some things that have come up in this discussion. I'll report back soon.

**Comment by sprd-bena** [comment] 2016-06-28 18:31
As I encountered similar problems with Ubuntu 16.04, and looking for the reason I stumbled over `libpam-systemd` and `dbus`, and that they would solve this, but they do not and are in the meantime included in the Ubuntu Server images, anyway. 
I found some tickets from systemd and debian, and found out that systemd has surprisingly it's own `poweroff` and `reboot` command: `systemctl poweroff` and `systemctl reboot`, but in the end they just stop all running services and then trigger `halt`.

=> I have tested the behavior with a provisioned vagrant box: `systemctl reboot` closes the ssh connection immediately. So i.e. with `while true; do vagrant ssh --command 'systemctl reboot'; done`, `vagrant ssh` it "waits" till the connection is possible, again.

=> However, In my tests with `packer`, the "next" script in the queue starts directly afterwards, so the process will "stop"/"freeze" after a few seconds later (as we notice this issue before). 
The "pause_before" config statement is only valid once, so if "scripts" is an array of scripts, only before the first script it pauses/wait. This can maybe fixed easily within `packer`, so that "pause_before" is used for all elements of the array...

But for now my workaround is a `nohup shutdown --reboot now </dev/null >/dev/null 2>&1 &` (just to make sure...). `shutdown` also comes from systemd, but from the man-page is it not clear to me if the services are ended as with `systemctl reboot`, but it seams so.

A reboot of a VM running on top of `qemu` is much faster then with `virtualbox`, but at least with both it works. So maybe others can test the `nohup shutdown --reboot now </dev/null >/dev/null 2>&1 &` in their scripts, too.

Are there some other workarounds at the moment I may have missed?

**Comment by kwilczynski** [comment] 2016-06-28 18:35
@sprd-bena no, your work around is pretty much what most of the people (myself included) usually resort to. Nice detective work, by the way.

**Comment by rickard-von-essen** [comment] 2016-11-17 18:14
See my [comment here](https://github.com/mitchellh/packer/issues/4137#issuecomment-261324083).

**Comment by SwampDragons** [comment] 2017-09-27 23:59
Based on the conversation here https://github.com/hashicorp/packer/issues/4137#issuecomment-261324083 and some testing of my own, I think this was likely resolved by https://github.com/hashicorp/packer/pull/4197; if anyone has further problems with the above, please reopen.

**Closed by SwampDragons** 2017-09-27 23:59 UTC
Labels: provisioner/shell, question
