### ISSUE TITLE
Packer stuck while building windows gcp image.

### ISSUE THREAD

**Issue by mthegreat83** [hashicorp/packer#7611] opened 2019-05-06 15:32 UTC
Hello,

I have a jenkins job that builds Windows GCP images using packer, I haven't changed anything in the packer json build file, and this job was always working fine, I have upgraded jenkins to the latest version Jenkins ver. 2.164.2, and since then the job is stuck !

Te debug logs are not showing me anything, it is just stuck and showing these messages

2019/05/06 11:00:54 packer: 2019/05/06 11:00:54 [INFO] RPC endpoint: Communicator ended with: 0
2019/05/06 11:00:54 [INFO] 1805 bytes written for 'stderr'
2019/05/06 11:00:54 [INFO] 221112 bytes written for 'stdout'
2019/05/06 11:00:54 [INFO] RPC client: Communicator ended with: 0
2019/05/06 11:00:54 [INFO] RPC endpoint: Communicator ended with: 0
2019/05/06 11:00:54 packer: 2019/05/06 11:00:54 [INFO] 1805 bytes written for 'stderr'

Any ideas on what should I do to tackle this ? it is quite blocking

**Comment by SwampDragons** [comment] 2019-05-06 17:55
Did you upgrade the version of Packer?

**Comment by mthegreat83** [comment] 2019-05-06 20:04
Yes it is at 1.4.0

It is just I am not sure what is it waiting for.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SwampDragons** [comment] 2019-05-06 21:54
Sorry, a clearer is -- did this only start happening after you upgraded? (Is it a regression?)  We did see a similar-looking hang caused by a regression that we fixed in https://github.com/hashicorp/packer/pull/7579, so if this only happens in 1.4.0 my guess is you're looking at a duplicate of that.  

Here's a linux build of the master branch of Packer, which has that patch applied:
[packer.zip](https://github.com/hashicorp/packer/files/3149966/packer.zip)

Can you let me know if you still see the issue with that build?

**Comment by mthegreat83** [comment] 2019-05-07 16:42
Yes !! the patch you gave solved the issue

thank you for the save.

**Comment by SwampDragons** [comment] 2019-05-07 16:55
Awesome, glad that was it.

**Closed by SwampDragons** 2019-05-07 16:55 UTC
Labels: duplicate, question
