### ISSUE TITLE
Packer 1.4.0'use of go-getter for local ISO downloads fails for vmware-iso builder

### ISSUE THREAD

**Issue by ulrichbayer** [hashicorp/packer#7534] opened 2019-04-19 06:39 UTC
I am using packer 1.4.0 on Windows and the vmx-builder with VMWare Workstation 15 Pro 15.0.4 build-12990004.
The switch to hashicorp/go-getter for downloading ISO files leads to the creation of symlinks for local ISO files (e.g, file:///C:/VMs/Microsoft Windows 10 Enterprise x64 EN-US LTSB 2019/SW_DVD5_WIN_ENT_LTSC_2019_64-bit_English_MLF_X21-96425.iso).
VMWare Workstation does not seem to support symlinks when loading ISO-files for a CD. This can be easily reproduced by creating a symbolic link to an ISO file with mklink and trying to attach this symlinked file as a DVD-drive:
```
mklink test.iso SW_DVD5_WIN_ENT_LTSC_2019_64-bit_English_MLF_X21-96425.ISO
symbolic link created for test <<===>> SW_DVD5_WIN_ENT_LTSC_2019_64-bit_English_MLF_X21-96425.ISO

C:\VMs\Microsoft Windows 10 Enterprise x64 EN-US LTSB 2019>dir
 Volume in drive C is Windows
 Volume Serial Number is 2EEF-EFB1

 Directory of C:\VMs\Microsoft Windows 10 Enterprise x64 EN-US LTSB 2019

19.04.2019  07:32    <DIR>          .
19.04.2019  07:32    <DIR>          ..
22.11.2018  15:35     4.056.717.312 SW_DVD5_WIN_ENT_LTSC_2019_64-bit_English_MLF_X21-96425.ISO
19.04.2019  07:29    <SYMLINK>      test.iso [SW_DVD5_WIN_ENT_LTSC_2019_64-bit_English_MLF_X21-96425.ISO]
```
![VMware Workstation](https://user-images.githubusercontent.com/23665923/56409105-c529ec00-6277-11e9-93e9-b3c2e0a8d0d6.png)

I have also created a minimal packer.json and posted it together with its log output, the dir listing of the packer_cache directory and the relevant portions of the vmware log file here:
https://gist.github.com/ulrichbayer/e467c0217f448743a96638564712830d
One can see in the vmware log file that the symlinked ISO cannot be mounted.

Potential Fix: It would be good to give the user a way to force a copy of the ISO file. The VMX-builder could automatically turn on this force copy option.

**Comment by SwampDragons** [comment] 2019-04-19 16:13
Thanks for reaching out; sorry for the regression.  I believe this is a duplicate of #7496; there are some builds on that issue which contain a patch that should solve this for you.

**Comment by SwampDragons** [comment] 2019-04-19 16:15
Actually on closer read this looks unique. Looking at this now.

**Comment by azr** [comment] 2019-04-23 09:52
Hello @ulrichbayer, thanks for reporting, this is an issue with the layout of the go-getter. Sorry I didn't foresee this issues. I initially wanted to introduce a breaking change to the go-getter in order to fix this but I think this can be done without. Trying something.

**Comment by azr** [comment] 2019-04-23 10:11
Turns out there is no simple way to do this without breaking the checksumming.

**Comment by azr** [comment] 2019-04-25 10:14
Update, I couldn't come up with a worthy quick fix for this, so we are going for the longer approach. It's  well in progress though 🙂

**Comment by azr** [comment] 2019-04-26 08:39
Scratch my last comment, for now we will have packer copy local files instead of symlinking them.

This was done in #7575.

@ulrichbayer, here is a windows binary, please tell me if that worked for you: [windows_amd64.zip](https://github.com/hashicorp/packer/files/3120457/windows_amd64.zip)

**Closed** 2019-04-29 19:35 UTC
Labels: builder/vmware, regression
