### ISSUE TITLE
Unable to download iso required to build virtual-box using iso

### ISSUE THREAD

**Issue by subbu05** [hashicorp/packer#5352] opened 2017-09-15 19:40 UTC
packer version
Packer v0.8.3

OS : Mac X EL Capiton 10.11.6

   vbox: Downloading or copying: https://user:password@test.com/CentOS-7-x86_64-Minimal-1511.iso
    vbox: Error downloading: Get https://user:password@test.com/CentOS-7-x86_64-Minimal-1511.iso: x509: certificate signed by unknown authority
==> vbox: ISO download failed.
Build 'vbox' errored: ISO download failed.

How to ignore certificate check in packer?

**Comment by mwhooker** [comment] 2017-09-15 19:47
This is a duplicate of #4969

We don't support bypassing certificate checks. If you want to download an insecure iso, I recommend either not using tls (use http://...), or download the iso first with curl and then set the iso_url as `file:///path/to/downloaded/iso`.

Unless there's a reason any of the above won't work, I'm going to close this. Thanks!

**Closed by mwhooker** 2017-09-15 19:47 UTC
