### ISSUE TITLE
Fix boot_command key signals for Windows guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5843] opened 2018-02-04 01:06 UTC
When packing Windows guest boxes, packer appears to submit the wrong keyboard scancodes, sending IBM/Linux codes instead of Windows codes, resulting in corruption of the `boot_command`, breaking the build. Instead, packer should use a more appropriate scancode translation table for Windows guests:

https://msdn.microsoft.com/en-us/library/aa299374(v=vs.60).aspx

- Packer v1.1.2-dev
- Host: macOS High Sierra 10.13

Some of the scancodes match up well enough, helping the build limp along past a few install wizard screens. However, entry of the `vagrant`/`vagrant` username/password combination fails.

Example:

```json
{
  "variables": {
    "vm_name": "windows",
    "iso_url": "http://care.dlservice.microsoft.com/dl/download/6/5/D/65D18931-F626-4A35-AD5B-F5DA41FE6B76/16299.15.170928-1534.rs3_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso",
    "iso_checksum_type": "sha512",
    "iso_checksum": "d0f26073fedb71119f47a0d3c61491d44d59425e9ae1f10c29146a58416598fb5623f4cebc324b634e9c3c90d856853cfd94af75ba1f42f9f7288b8cb427e082",
    "winrm_username": "vagrant",
    "winrm_password": "vagrant",
    "winrm_timeout": "1800s",
    "disk_size_MB": "20000",
    "ram_MiB": "1024",
    "http_directory": "http",
    "shutdown_command": "shutdown /s /t 0 /f"
  },
  "post-processors": [
    {
      "type": "vagrant",
      "output": "{{ user `vm_name` }}-{{.Provider}}.box",
      "compression_level": "9"
    }
  ],
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "Windows10_64",
      "vm_name": "{{ user `vm_name` }}",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum_type": "{{ user `iso_checksum_type` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "communicator": "winrm",
      "winrm_username": "{{ user `winrm_username` }}",
      "winrm_password": "{{ user `winrm_password` }}",
      "winrm_timeout": "{{ user `winrm_timeout` }}",
      "disk_size": "{{ user `disk_size_MB` }}",
      "guest_additions_mode": "attach",
      "virtualbox_version_file": "",
      "vboxmanage": [ ["modifyvm", "{{.Name}}", "--memory", "{{ user `ram_MiB` }}"] ],
      "http_directory": "{{ user `http_directory` }}",
      "boot_command": [
        "<wait10><wait10><wait10>",
        "<tab><tab><tab><enter><wait5>",
        "<enter><wait10><wait10><wait10>",
        "<space><tab><enter><wait5>",
        "<tab><enter><wait5>",
        "<tab><tab><enter><tab><enter><wait>",
        "<enter><wait5>",
        "<tab><tab><tab><tab><tab><enter><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<tab><enter><wait10>",
        "<tab><enter><wait5>",
        "<enter>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<tab><tab><enter><wait5>",
        "vagrant<enter><wait>",
        "vagrant<enter><wait>",
        "vagrant<enter><wait>",
        "hint<enter><wait10>",
        "<tab><tab><tab><enter><wait10>",
        "<tab><tab><tab><tab><spacebar><tab><spacebar><tab><spacebar><tab><spacebar><tab><spacebar><tab><tab><enter>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<wait10><wait10><wait10><wait10><wait10><wait10>",
        "<leftSuperOn>x<leftSuperOff><wait>a<wait5>",
        "<left><enter><wait5>",
        "New-Item -Path \"HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Network\\NewNetworkWindowOff\" -Force<enter><wait5>",
        "Set-NetConnectionProfile -InterfaceIndex (Get-NetConnectionProfile).InterfaceIndex -NetworkCategory Private<enter><wait5>",
        "Set-WSManQuickConfig -Force<enter><wait5>",
        "Set-Item WSMan:\\localhost\\Service\\AllowUnencrypted -Value True<enter><wait5>",
        "Set-Item WSMan:\\localhost\\Service\\Auth\\Basic -Value True<enter><wait5>",
        "Set-Service WinRM -StartupType Automatic<enter><wait5>",
        "Restart-Service winrm<enter>"
      ],
      "shutdown_command": "{{ user `shutdown_command` }}"
    }
  ]
}
```

As a workaround, most packer configurations for Windows guests use virtual floppy diskettes with preseed Autounattend.xml files. But it would be more flexible in the long run for packer to match the right scancodes to the right guest operating system type.

**Comment by rickard-von-essen** [comment] 2018-02-04 06:50
In general `boot_command` is very error prone and should be keep as short as possible, that is why the well working Windows templates mostly rely on `Autounattend.xml`.

**Comment by SwampDragons** [comment] 2019-03-05 20:31
Looks like we were never able to reproduce this, so I'm closing for now.

**Closed by SwampDragons** 2019-03-05 20:31 UTC
Labels: need-more-info, question, waiting-reply
