### ISSUE TITLE
Packer - Ansible local blocked and don't return the prompt

### ISSUE THREAD

**Issue by Tioborto** [hashicorp/packer#5208] opened 2017-08-02 12:59 UTC
- Packer version : 1.0.3
- Host platform : Centos 7 on ESXI 5.5
- Debug log output : https://gist.github.com/Tioborto/096335cea4f58838027beb80485c67e6
- Template : https://gist.github.com/Tioborto/80dd28e4adc77a355fda9bfaf8ba2a5e

Hello everyone, 
I need your help. I would like to use Ansible like provisioner to install some softwares but Ansible don't return the prompt & he's blocked (cf debug log) on : 
    `2017/08/02 14:38:45 [INFO] 7 bytes written for 'stdout'`
    `2017/08/02 14:38:45 [INFO] 0 bytes written for 'stderr'`
Do you have an idea ?

**Comment by rickard-von-essen** [comment] 2017-08-02 13:13
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Closed** 2017-08-02 13:15 UTC
Labels: bug, duplicate, provisioner/ansible-remote
