### ISSUE TITLE
hyperv-iso handles iso_url path values incorrectly (regression from v1.1.1)

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#5620] opened 2017-11-21 22:39 UTC
Packer appears to have developed a regressive arthropod. The issue is with packer's handling of relative path values, specifically the iso_url field, when using the hyperv-iso builder. The offending JSON value:

```
"iso_url": "res/media/rhel-server-7.4-x86_64-dvd.iso"
```

The path value is correct, and works properly with v1.1.1, but failed to find the ISO while attempting to build the same JSON file using packer v1.1.2. It may be worth noting this same value works properly with qemu-iso, vmware-iso, and virtualbox-iso builders.

**packer v1.1.2**
```
==> generic-rhel7-hyperv: Creating temporary directory...
==> generic-rhel7-hyperv: Downloading or copying ISO
    generic-rhel7-hyperv: Downloading or copying: file://C:/Users/ladar/Desktop/packer/res/media/rhel-server-7.4-x86_64-dvd.iso
    generic-rhel7-hyperv: Error downloading: CreateFile Users/ladar/Desktop/packer/res/media/rhel-server-7.4-x86_64-dvd.iso: The system cannot find the path specified.
==> generic-rhel7-hyperv: ISO download failed.
==> generic-rhel7-hyperv: Deleting output directory...
==> generic-rhel7-hyperv: Deleting temporary directory...
Build 'generic-rhel7-hyperv' errored: ISO download failed.
```

**packer v1.1.1**
```
==> generic-rhel7-hyperv: Creating temporary directory...
==> generic-rhel7-hyperv: Downloading or copying ISO
    generic-rhel7-hyperv: Downloading or copying: file:///C:/Users/ladar/Desktop/packer/res/media/rhel-server-7.4-x86_64-dvd.iso
==> generic-rhel7-hyperv: Starting HTTP server on port 8367
==> generic-rhel7-hyperv: Creating switch 'Switch' if required...
==> generic-rhel7-hyperv:     switch 'Switch' already exists. Will not delete on cleanup...
==> generic-rhel7-hyperv: Creating virtual machine...
==> generic-rhel7-hyperv: Enabling Integration Service...
==> generic-rhel7-hyperv: Setting boot drive to os dvd drive C:/Users/ladar/Desktop/packer/res/media/rhel-server-7.4-x86_64-dvd.iso ...
==> generic-rhel7-hyperv: Mounting os dvd drive C:/Users/ladar/Desktop/packer/res/media/rhel-server-7.4-x86_64-dvd.iso ...
==> generic-rhel7-hyperv: Skipping mounting Integration Services Setup Disk...
==> generic-rhel7-hyperv: Mounting secondary DVD images...
==> generic-rhel7-hyperv: Configuring vlan...
==> generic-rhel7-hyperv: Starting the virtual machine...
```

In this case the host was running a fully patched version of Windows 10.

**Comment by SwampDragons** [comment] 2017-11-21 22:44
This is likely a duplicate of #5589 and it's been fixed on master; if you want to use the dev binary provided on the other ticket, you can, or else you can downgrade until we can release the next version. Apologies for the regression.  I'm going to leave this ticket open for now, because it's been reported enough times that I want people to be able to find an open ticket for it, until we release the fix.

**Comment by ladar** [comment] 2017-11-21 23:19
Yes it does appear to be the same issue. Silly me, I looked for references to this issue in relation to the hyperv-iso builder. I didn't think to try searching for the references with other builders (like vmware-iso) because, at least for me, that builder worked just fine (albeit Linux)... 

I'm setup to build the dev tree on Linux, but haven't done the same for Windows yet... so I can't test the fix. (I have a thing about grabbing random binaries off the internet.) 

I'll just build my RHEL 7 boxes using v1.1.1 for now... as it's my only config that uses a path in the iso_url field.

**Comment by SwampDragons** [comment] 2017-11-21 23:22
You should be able to build yourself a windows binary from a linux machine by running `XC_ARCH=amd64 XC_OS=windows ./scripts/build.sh` from the project root, FWIW :)

**Closed** 2017-11-28 01:28 UTC
Labels: bug, regression, windows-host

**Comment by pvandervelde** [comment] 2017-12-10 02:15
@SwampDragons did the fix for this make it into 1.1.3? I just downloaded that version and I still see that problem.

**Comment by SwampDragons** [comment] 2017-12-11 20:42
@pvandervelde It should have, yes.  Can you open a new issue with a debug log and full steps to reproduce please?

**Comment by pvandervelde** [comment] 2017-12-11 21:03
Yeah will have to do that tonight. Don't have access to my home computer from work

**Comment by pvandervelde** [comment] 2017-12-13 07:28
@SwampDragons grabbed the logs and reported it as #5700
