### ISSUE TITLE
Packer 1.0.3 build hangs during ansible provisioning

### ISSUE THREAD

**Issue by annaken** [hashicorp/packer#5189] opened 2017-07-28 12:04 UTC
Ubuntu 16.04
Packer v1.0.3
Ansible 2.3.1.0
Output: https://gist.github.com/annaken/e6b9cdcf0758d5f7f86505e25a5fcda8
Packer file: https://gist.github.com/annaken/fc07089ad285bc007033c25eb7245230

I'm trying to build an AMI with Packer, but when I come to provision it with Ansible it just hangs at 

amazon-ebs: PLAY [all] *********************************************************************
amazon-ebs: TASK [Gathering Facts] **********************************************

This only happens with Packer 1.0.3 - I can downgrade to 0.12 and it runs just fine.

I've included the gist of the debug output but there's not a lot of information in there unfortunately. I see no other output in any other logs.

**Comment by rickard-von-essen** [comment] 2017-07-28 12:06
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Comment by annaken** [comment] 2017-07-28 12:07
Apologies, I searched but didn't find anything. Thanks for getting back to me so quickly.

**Closed** 2017-07-28 12:07 UTC
Labels: bug, duplicate, provisioner/ansible-remote

**Comment by rickard-von-essen** [comment] 2017-07-28 12:14
No worries, it's not easy to know how others describe a bug.
