### ISSUE TITLE
Error starting VM: VMware error: VERIFY bora/lib/misc/hostinfoPosix.c:2455

### ISSUE THREAD

**Issue by BenjaminWinks** [hashicorp/packer#8794] opened 2020-02-25 15:17 UTC
Been trying to get vmware-iso images to build on CentOS 7.7.1908 and Ubuntu 18.04 LTS to no avail. 

`'vmware-iso' errored: Error starting VM: VMware error: VERIFY bora/lib/misc/hostinfoPosix.c:2455` 

This is what the error is, and I don't know what to do with this. I have VMWare Workstation 15.5.1 installed on both Ubuntu and CentOS, but the same packer build config works on OSX 10.15.3 via vmware fusion, so I am at a loss. 

Has anyone ran into this issue?

Here's the log output from the failed build:

```txt
2020-02-25T15:11:27.284Z| vix| I125: Log for Vix pid=5821 version=-1 build=build-15018445 option=Release
2020-02-25T15:11:27.284Z| vix| I125: The process is 64-bit.
2020-02-25T15:11:27.284Z| vix| I125: Host codepage=UTF-8 encoding=UTF-8
2020-02-25T15:11:27.284Z| vix| I125: Host is Linux 4.19.76-linuxkit Ubuntu 18.04.4 LTS
2020-02-25T15:11:27.272Z| vix| I125: DictionaryLoad: Cannot open file "/usr/lib/vmware/settings": No such file or directory.
2020-02-25T15:11:27.272Z| vix| I125: [msg.dictionary.load.openFailed] Cannot open file "/usr/lib/vmware/settings": No such file or directory.
2020-02-25T15:11:27.272Z| vix| I125: PREF Optional preferences file not found at /usr/lib/vmware/settings. Using default values.
2020-02-25T15:11:27.272Z| vix| I125: DictionaryLoad: Cannot open file "/root/.vmware/config": No such file or directory.
2020-02-25T15:11:27.272Z| vix| I125: [msg.dictionary.load.openFailed] Cannot open file "/root/.vmware/config": No such file or directory.
2020-02-25T15:11:27.272Z| vix| I125: PREF Optional preferences file not found at /root/.vmware/config. Using default values.
2020-02-25T15:11:27.272Z| vix| I125: DictionaryLoad: Cannot open file "/root/.vmware/preferences": No such file or directory.
2020-02-25T15:11:27.272Z| vix| I125: [msg.dictionary.load.openFailed] Cannot open file "/root/.vmware/preferences": No such file or directory.
2020-02-25T15:11:27.272Z| vix| I125: PREF Optional preferences file not found at /root/.vmware/preferences. Using default values.
2020-02-25T15:11:27.280Z| vix| I125: lib/ssl: OpenSSL using FIPS_drbg for RAND
2020-02-25T15:11:27.280Z| vix| I125: lib/ssl: protocol list tls1.2
2020-02-25T15:11:27.280Z| vix| I125: lib/ssl: protocol list tls1.2 (openssl flags 0x17000000)
2020-02-25T15:11:27.280Z| vix| I125: lib/ssl: cipher list ECDHE+AESGCM:RSA+AESGCM:ECDHE+AES:RSA+AES
2020-02-25T15:11:27.280Z| vix| I125: lib/ssl: curves list prime256v1:secp384r1:secp521r1
2020-02-25T15:11:27.385Z| vix| I125: OBJLIB-LIB: Objlib initialized.
2020-02-25T15:11:27.385Z| vix| I125: Foundry Init: setting up global state (1 poll threads, 0 worker threads).
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: vixLogLevel = 0
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: vixApiTraceLevel = 0
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: vixDebugPanicOnVixAssert = 0
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: vixLogRefcountOnFinalRelease = 0
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: asyncOpWarningThreshold = 1000000
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: enableSyncOpSelection = FALSE
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: enableExternalThreadInterface = TRUE
2020-02-25T15:11:27.385Z| vix| I125: Vix_InitializeGlobalState: enableVigor = FALSE
2020-02-25T15:11:27.385Z| vix| I125: VixHost_ConnectEx: version -1, hostType 4, hostName (null), hostPort 0, options 0
2020-02-25T15:11:27.386Z| vix-poll| I125: Vix: [foundryAsyncOps.c:1975]: FoundryAsyncOp_ThreadMainLoop: Vix poll thread started.
2020-02-25T15:11:27.403Z| vix| I125: WQPoolAllocPoll : pollIx = 1, signalHandle = 22
2020-02-25T15:11:27.403Z| vix| I125: UUID: Unable to open /sys/firmware/efi/systab: No such file or directory
2020-02-25T15:11:27.403Z| vix| I125: UUID: Unable to open /dev/mem: No such file or directory
2020-02-25T15:11:27.404Z| vix| I125: UUID: Valid gethostid routine. Value = 11AC0300.
2020-02-25T15:11:27.404Z| vix| I125: vmxFilePath="/usr/lib/vmware/bin/vmware-vmx"
2020-02-25T15:11:27.404Z| vix| I125: vmxFilePathDebug="/usr/lib/vmware/bin/vmware-vmx-debug"
2020-02-25T15:11:27.404Z| vix| I125: vmxFilePathStats="/usr/lib/vmware/bin/vmware-vmx-stats"
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfo_FindHostCDROMs: enumerating IDE CDROMs
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfoFindHostIDECDROMs: /proc/ide could not be explored. Unable to enumerate host IDE cdroms.
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfo_FindHostCDROMs: IDE CDROM enumerating completed
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfo_FindHostCDROMs: enumerating SCSI CDROMs
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfoCheckDevCDROM: can't stat /dev/cdrom: No such file or directory
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfo_FindHostCDROMs: SCSI CDROM enumerating completed
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfo_FindHostCDROMs: enumerating CDROMs in VSI
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfo_FindHostCDROMs: VSI CDROM enumerating completed
2020-02-25T15:11:27.405Z| vix| I125: HostDeviceInfoFindHostAlsaSoundDevices: Not loading ALSA library to detect sound devices: not for VixWorkstationHost
2020-02-25T15:11:27.406Z| vix| I125: HostDeviceInfo_FindHostParallelPorts: /proc/sys/dev/parport could not be explored. Unable to enumerate host parallel ports.
2020-02-25T15:11:27.406Z| vix| I125: SMBIOS: can't open /dev/mem: Could not find the file
2020-02-25T15:11:27.406Z| vix| I125: VmhsHostInfoPopulateSystem:  Could not get information from smbios to populate VMDB.
2020-02-25T15:11:27.497Z| vix| W115: Ignoring subsequent product state set
2020-02-25T15:11:27.500Z| vix| I125: Vix: [foundryHandleProperties.c:3359]: Error VIX_E_NOT_FOUND in Vix_GetPropertiesImpl(): Unable to get bool property 107.
2020-02-25T15:11:27.500Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: Reloading config state.
2020-02-25T15:11:27.504Z| vix-poll| I125: SNAPSHOT: SnapshotConfigInfoOpenVmsd: Creating new snapshot dictionary, '/packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmsd'.
2020-02-25T15:11:27.504Z| vix-poll| I125: VMHS: Transitioned vmx/execState/val to poweredOff
2020-02-25T15:11:27.507Z| vix-poll| I125: VMHSVMCbPower: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx, Setting state of VM to powerOn with option default
2020-02-25T15:11:27.507Z| vix-poll| I125: Found vmx as /usr/lib/vmware/bin/vmware-vmx
2020-02-25T15:11:27.507Z| vix-poll| I125: Starting vmx as /usr/lib/vmware/bin/vmware-vmx
2020-02-25T15:11:27.507Z| vix-poll| I125: VigorExecVMXExCommon: VM /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx in directory /packer/centos/build/centos-7-minimal-base-image
2020-02-25T15:11:27.507Z| vix-poll| I125: VigorExecVMXExCommon: Exec()'ing /usr/lib/vmware/bin/vmware-vmx /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx.
2020-02-25T15:11:27.967Z| vix-poll| I125: VmdbAddConnection: cnxPath=/db/connection/#3/, cnxIx=1
2020-02-25T15:11:27.967Z| vix-poll| I125: VmdbPipeStreamsOvlError: write failed, draining reads
2020-02-25T15:11:27.967Z| vix-poll| I125: VmdbPipeStreamsOvlError Couldn't read: OVL_STATUS_EOF (remote disconnect)
2020-02-25T15:11:27.967Z| vix-poll| I125: VmdbPipeStreamsOvlError Couldn't initiate write: (32) Broken pipe.
2020-02-25T15:11:27.967Z| vix-poll| I125: VmdbCnxDisconnect: Disconnect: closed pipe for sub cnx '/db/connection/#3/' (-31)
2020-02-25T15:11:27.967Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: VMX did not report err via stderr
2020-02-25T15:11:27.967Z| vix-poll| I125: VmdbDbRemoveCnx: Removing Cnx from Db for '/db/connection/#3/'
2020-02-25T15:11:27.967Z| vix-poll| I125: VersionAsyncSendRecv: VmdbCnxAsyncSend() failed, cnx = /db/connection/#3/type/sub/, ret = Pipe: Write failed
2020-02-25T15:11:27.967Z| vix-poll| I125: Vmdb_AddConnectionAsync_Secure: registered VERSION completion callback, cnx = /db/connection/#3/
2020-02-25T15:11:27.968Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: Pending power op found, completing.
2020-02-25T15:11:27.968Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: Clearing execReqPath
2020-02-25T15:11:27.968Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: Reloading config state.
2020-02-25T15:11:27.973Z| vix-poll| I125: VMHS: Transitioned vmx/execState/val to poweredOff
2020-02-25T15:11:27.975Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: VMHSStartVmxVigorCb: vmPath=/vm/#cda545af9a224e85/ status=error
2020-02-25T15:11:27.975Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: VMHSStartVmxVigorCb: error vmdb=-45 msg=Failed to power on '/packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx'.
2020-02-25T15:11:27.975Z| vix-poll| I125+ 
2020-02-25T15:11:27.975Z| vix-poll| I125: /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx: Reloading config state.
2020-02-25T15:11:27.981Z| vix-poll| I125: VMHS: Transitioned vmx/execState/val to poweredOff
2020-02-25T15:11:27.982Z| vix-poll| I125: FoundryVMDBPowerOpCallback: VMDB reports power op failed for VM /packer/centos/build/centos-7-minimal-base-image/centos-7-minimal-base-image.vmx with error msg = "VMDB failure" and error code -1.
```

Sorry if I've done this poorly - not used to doing this. If more information is needed, please comment.

Cheers.

**Comment by SwampDragons** [comment] 2020-03-02 21:09
I haven't seen this message before, but it's bubbling up from VMware rather than being internal to Packer. Those logs look like VMware logs too, not Packer logs. 

My recommendation is that you try to launch the vm manually via VMware and see if it works that way, then try again with Packer if it does work. 

To help you more than that recommendation though, I really do need the things requested in the issue template: 

- Full debug log output from `PACKER_LOG=1 packer build template.json` -- make sure you set the PACKER_LOG=1 env var to turn on verbose logging.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by SwampDragons** [comment] 2020-07-01 18:05
Closing since I haven't gotten more information. If this is still a problem, we can reopen if you can provide further logs and a repro case.

**Closed by SwampDragons** 2020-07-01 18:05 UTC
Labels: builder/vmware, need-more-info, need-repro
