### ISSUE TITLE
Packer 1.4.1 stucks on "Waiting for AMI to become ready..."

### ISSUE THREAD

**Issue by YogeshKumarMehta** [hashicorp/packer#7719] opened 2019-06-06 04:22 UTC
- Packer version from `packer version 1.4.1`

- Host platform RHEL 6

- Debug log output from `PACKER_LOG=1 packer build template.json`.

  Please 2019/06/06 13:10:26 ui:     CENTOS7: Stopping instance
2019/06/06 13:10:27 ui: ==> CENTOS7: Waiting for the instance to stop...
2019/06/06 13:10:57 ui: ==> CENTOS7: Enabling Enhanced Networking (ENA)...
2019/06/06 13:10:57 ui: ==> CENTOS7: Creating AMI XXXXX-CENT7.6HVM-XX from instance i-05XXXXXXXXXXXXXXX
2019/06/06 13:10:58 ui:     CENTOS7: AMI: ami-XXXXXXXXXXXX
2019/06/06 13:10:58 ui: ==> CENTOS7: Waiting for AMI to become ready...
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 ui error: Cancelling build after receiving interrupt
2019/06/06 13:26:12 Cancelling builder after context cancellation context canceled
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.
2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Error waiting for AMI: RequestCanceled: waiter context canceled
2019/06/06 13:26:12 packer: caused by: context canceled
2019/06/06 13:26:13 packer: 2019/06/06 13:26:13 Unable to determine reason waiting for AMI failed: RequestExpired: Request has expired.
2019/06/06 13:26:13 packer:     status code: 400, request id: c97c4f36-401c-44d3-bfa8-147a89a7149b
2019/06/06 13:26:13 ui error: ==> CENTOS7: Unknown error waiting for AMI.
2019/06/06 13:26:13 ui: ==> CENTOS7: Terminating the source AWS instance...

 With packer version 1.2.0, I am able to pack the AMIs without any issue.

**Comment by SwampDragons** [comment] 2019-06-06 22:11
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by YogeshKumarMehta** [comment] 2019-06-06 23:40
thanks, I have updated the sample build template here .. https://gist.github.com/YogeshKumarMehta/8246d2d086ee3e7fc5585f6252d7b294

We run series of Ansible and Shell provisioner tasks and they takes around 10 mins. AWS authentication sis via Proxy and Access tokens. Tokens have 5 min expiry. 

Before Packer Kicks AMI pack job , provisoner refreshes the credentials. 
2019/06/06 13:10:57 ui: ==> CENTOS7: Creating AMI XXXXX-CENT7.6HVM-XX from instance i-05XXXXXXXXXXXXXXX
 2019/06/06 13:10:58 ui: CENTOS7: AMI: ami-XXXXXXXXXXXX
 2019/06/06 13:10:58 ui: ==> CENTOS7: Waiting for AMI to become ready...

Here packer stops communicating with AWS and hangs indefinitely. with Packer 1.2.0 this step goes fine.

 2019/06/06 13:26:12 packer: 2019/06/06 13:26:12 Received interrupt signal (count: 1). Ignoring.

**Comment by quater** [comment] 2019-06-07 14:01
Same problem here with packer version 1.4.1 on MacOS.

**Comment by SwampDragons** [comment] 2019-06-13 22:02
Which version of Packer did this stop working with?  I know you said it worked with 1.2.0 but did it work with any of the versions in between?

In version 1.2.5, we replaced Packer's home-built waiters with those provided by Amazon in the golang aws sdk.  I'm not sure why this would have broken things for you, but it may be possible given your very short credential rotation time. Have you tried increasing the expiry on your tokens to give your build a better chance of succeeding?

**Comment by YogeshKumarMehta** [comment] 2019-06-17 01:25
@SwampDeagons thanks.. 

I tried version 1.3.x and facing same issue as of with version 1.4.1. I will check if I can get the token expiry time extended.

Is there any workaround if by any chance I can't get token expiry extended ?

**Comment by SwampDragons** [comment] 2019-06-17 16:45
I don't think so. 5 minutes is an extremely short time to expire tokens for this kind of thing. It often takes longer than that to perform single snapshot or copy operations.

**Comment by Kishorep81** [comment] 2019-06-21 13:21
@SwampDragons 

I have a similar kind of issue where it completed installing and provisioning required software, it stopped the source instance and creating a temporary AMI. At this stage, it is stuck "Waiting for AMI to become ready..." It is waiting a long time and after an hour it times out and getting the following error

===================================================================
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error waiting for AMI. Reason: <nil>

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error waiting for AMI. Reason: <nil>

==> Builds finished but no artifacts were created.
===================================================================

I have set the following env variables in PowerShell as I am running the packer build from PowerShell.
$env:PACKER_LOG=1
$env:PACKER_LOG_PATH="C:\Packer\packerlog.txt"
$Env:AWS_MAX_ATTEMPTS=400
$Env:AWS_POLL_DELAY_SECONDS=10
[Scripts.zip](https://github.com/hashicorp/packer/files/3314625/Scripts.zip)


Is there any workaround or fix for this, please?

Thanks
Kishore

**Comment by YogeshKumarMehta** [comment] 2019-06-27 06:59
I have tried with 15 mins token expiry, same issue. Will plan to use IAM profile instead of using tokens,.

**Comment by SwampDragons** [comment] 2019-07-23 18:10
Did using the IAM profile resolve this issue for you?

**Comment by fatemehhosseini** [comment] 2019-07-30 22:18
I have similar issue with packer 1.4.1
Output:

2019/07/30 15:24:54 [INFO] (telemetry) Starting builder amazon-ebs
2019/07/30 15:24:54 packer: 2019/07/30 15:24:54 Found region ......
2019/07/30 15:24:54 packer: 2019/07/30 15:24:54 [INFO] AWS Auth provider used: "EC2RoleProvider"
[1;32m==> amazon-ebs: Prevalidating AMI Name: PACKER-TEST 1564521894[0m
2019/07/30 15:24:55 packer: 2019/07/30 15:24:55 Using AMI Filters {
2019/07/30 15:24:55 packer:   Filters: [{
2019/07/30 15:24:55 packer:       Name: "name",
2019/07/30 15:24:55 packer:       Values: ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server*"]
2019/07/30 15:24:55 packer:     },{
2019/07/30 15:24:55 packer:       Name: "root-device-type",
2019/07/30 15:24:55 packer:       Values: ["ebs"]
2019/07/30 15:24:55 packer:     },{
2019/07/30 15:24:55 packer:       Name: "virtualization-type",
2019/07/30 15:24:55 packer:       Values: ["hvm"]
2019/07/30 15:24:55 packer:     }],
2019/07/30 15:24:55 packer:   Owners: ["......"]
2019/07/30 15:24:55 packer: }
[0;32m    amazon-ebs: Found Image ID: ami-.....[0m
2019/07/30 15:24:55 packer: 2019/07/30 15:24:55 [INFO] Finding AZ and VpcId for the given subnet 'subnet-.....'
2019/07/30 15:24:55 packer: 2019/07/30 15:24:55 [INFO] AvailabilityZone found: '.....'
[1;32m==> amazon-ebs: Creating temporary keypair: packer_....[0m
[1;32m==> amazon-ebs: Creating temporary security group for this instance: packer_....[0m
2019/07/30 15:24:55 packer: 2019/07/30 15:24:55 [DEBUG] Waiting for temporary security group: sg-.....
2019/07/30 15:24:55 packer: 2019/07/30 15:24:55 [DEBUG] Found security group sg-......
[1;32m==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...[0m
[1;32m==> amazon-ebs: Launching a source AWS instance...[0m
[1;32m==> amazon-ebs: Adding tags to source instance[0m
[0;32m    amazon-ebs: Adding tag: "Name": "Packer Builder"[0m
[0;32m    amazon-ebs: Instance ID: .....[0m
[1;32m==> amazon-ebs: Waiting for instance (.....) to become ready...[0m
2019/07/30 15:25:12 ui error: [1;31m==> amazon-ebs: Error waiting for instance (....) to become ready: ResourceNotReady: failed waiting for successful resource state[0m
[1;31m==> amazon-ebs: Error waiting for instance (....) to become ready: ResourceNotReady: failed waiting for successful resource state[0m
[1;32m==> amazon-ebs: Terminating the source AWS instance...[0m
[1;32m==> amazon-ebs: No volumes to clean up, skipping[0m
[1;32m==> amazon-ebs: Deleting temporary security group...[0m
[1;32m==> amazon-ebs: Deleting temporary keypair...[0m
2019/07/30 15:25:12 [INFO] (telemetry) ending amazon-ebs
2019/07/30 15:25:12 ui error: [1;31mBuild 'amazon-ebs' errored: Error waiting for instance (....) to become ready: ResourceNotReady: failed waiting for successful resource state[0m
2019/07/30 15:25:12 machine readable: error-count []string{"1"}
2019/07/30 15:25:12 ui error: 
==> Some builds didn't complete successfully and had errors:
2019/07/30 15:25:12 machine readable: amazon-ebs,error []string{"Error waiting for instance (....) to become ready: ResourceNotReady: failed waiting for successful resource state"}
2019/07/30 15:25:12 ui error: --> amazon-ebs: Error waiting for instance (....) to become ready: ResourceNotReady: failed waiting for successful resource state
==> Builds finished but no artifacts were created.
[1;31mBuild 'amazon-ebs' errored: Error waiting for instance (....) to become ready: ResourceNotReady: failed waiting for successful resource state[0m
2019/07/30 15:25:12 Cancelling builder after context cancellation context canceled
2019/07/30 15:25:12 [INFO] (telemetry) Finalizing.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error waiting for instance (...) to become ready: ResourceNotReady: failed waiting for successful resource state

**Comment by samof76** [comment] 2019-08-01 04:44
Same issue with 1.4.2 as well.

```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: eks-ami-sample-1564588398
==> amazon-ebs: Pausing after run of step 'StepPreValidate'. Press enter to continue. 
    amazon-ebs: Found Image ID: ami-0f2e8e5663e16b436
==> amazon-ebs: Pausing after run of step 'StepSourceAMIInfo'. Press enter to continue. 
==> amazon-ebs: Pausing after run of step 'StepNetworkInfo'. Press enter to continue. 
==> amazon-ebs: Creating temporary keypair: packer_5d41b96e-9521-410e-719d-f30c1ac58fc6
    amazon-ebs: Saving key for debug purposes: ec2_amazon-ebs.pem
==> amazon-ebs: Pausing after run of step 'StepKeyPair'. Press enter to continue. 
==> amazon-ebs: Creating temporary security group for this instance: packer_5d41b984-359c-c451-05d4-80014959425b
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Pausing after run of step 'StepSecurityGroup'. Press enter to continue. 
==> amazon-ebs: Pausing after run of step 'StepCleanupVolumes'. Press enter to continue. 
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-05ab7b6563f0ac10b
==> amazon-ebs: Waiting for instance (i-05ab7b6563f0ac10b) to become ready...
    amazon-ebs: Private IP: 172.16.23.237

==> amazon-ebs: Pausing after run of step 'StepRunSourceInstance'. Press enter to continue. ==> amazon-ebs: Pausing after run of step 'StepGetPassword'. Press enter to continue. 
==> amazon-ebs: Using ssh communicator to connect: 172.16.23.237
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Pausing after run of step 'StepConnect'. Press enter to continue. 
==> amazon-ebs: Pausing before the next provisioner . Press enter to continue. 
==> amazon-ebs: Provisioning with shell script: ./scripts/touch_it.sh
==> amazon-ebs: Pausing after run of step 'StepProvision'. Press enter to continue. 
==> amazon-ebs: Pausing after run of step 'StepCleanupTempKeys'. Press enter to continue. 
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
[O[I[==> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: failed waiting for successful resource state
O==> amazon-ebs: Pausing before cleanup of step 'StepCleanupTempKeys'. Press enter to continue. [I
==> amazon-ebs: Pausing before cleanup of step 'StepProvision'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepConnect'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepGetPassword'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepRunSourceInstance'. Press enter to continue. 
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Pausing before cleanup of step 'StepCleanupVolumes'. Press enter to continue. 
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Pausing before cleanup of step 'StepSecurityGroup'. Press enter to continue. 
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue. 
==> amazon-ebs: Deleting temporary keypair...
==> amazon-ebs: Pausing before cleanup of step 'StepNetworkInfo'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepSourceAMIInfo'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepPreValidate'. Press enter to continue. 
Build 'amazon-ebs' errored: Error waiting for instance to stop: ResourceNotReady: failed waiting for successful resource state

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: failed waiting for successful resource state

==> Builds finished but no artifacts were created.
```

**Comment by SwampDragons** [comment] 2019-08-01 16:38
@samof76 do you also have a short token expiry time?

I've also seen this `ResourceNotReady: failed waiting for successful resource state` when trying to encrypt with an invalid kms key id, either because it had a typo or because it was a valid key but I set it for the wrong region.

**Comment by SwampDragons** [comment] 2019-08-01 16:46
@samof76 actually looking at your logs, I don't think you're facing the same issue here. Your build is failing earlier, with a different error.

**Comment by SwampDragons** [comment] 2019-08-01 20:42
@YogeshKumarMehta did moving to an iam role solve this for you?

**Comment by lmeyerov** [comment] 2019-08-04 08:36
We've been seeing this randomly, maybe 50% of the time. Our images are ~large (5GB compressed of docker containers). With debug logs, gets stuck at:

```
2019/08/04 08:22:32 packer: 2019/08/04 08:22:32 [DEBUG] Opening new ssh session
2019/08/04 08:22:32 packer: 2019/08/04 08:22:32 [DEBUG] starting remote command: rm -f
2019/08/04 08:22:32 packer: 2019/08/04 08:22:32 [INFO] RPC endpoint: Communicator ended with: 0
2019/08/04 08:22:32 [INFO] RPC client: Communicator ended with: 0
2019/08/04 08:22:32 [INFO] RPC endpoint: Communicator ended with: 0
2019/08/04 08:22:32 packer: 2019/08/04 08:22:32 [INFO] RPC client: Communicator ended with: 0
2019/08/04 08:22:32 [INFO] (telemetry) ending shell
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating AMI zzz-2019-08-04T08-12-19Z from instance i-01e54020b105ac66e
    amazon-ebs: AMI: ami-yyy
==> amazon-ebs: Waiting for AMI to become ready...
```

**Comment by samof76** [comment] 2019-08-05 13:19
@SwampDragons sorry for the late reply, the error got fixed, I was using a `micro` instances to boot, but I have changed that a`xlarge` and it works! Thanks.

**Comment by SwampDragons** [comment] 2019-08-12 17:40
Glad to hear it.

**Closed** 2019-08-12 17:40 UTC
Labels: builder/amazon, regression, waiting-reply

**Comment by YogeshKumarMehta** [comment] 2019-08-13 06:50
Hey @SwampDragons , thanks for your support and my apologies for late response.

I can confirm by using IAM profile, I don't see timeout issues. Also, tested with this version 1.4.2, all seems good.
