### ISSUE TITLE
[VirtualBox] Unable to cleanup

### ISSUE THREAD

**Issue by eric-aldinger** [hashicorp/packer#4933] opened 2017-05-26 02:22 UTC
Seeing a regression of the failed build cleanup failure.

==> virtualbox-ovf: Unregistering and deleting imported VM...
==> virtualbox-ovf: Error deleting VM: VBoxManage error: VBoxManage.exe: error: Cannot unregister the 
[Full Error Log](https://gist.github.com/eric-aldinger/57cfacbd7f79f57cf80833d9eef11fdc)

[PRIOR REFERENCE](https://github.com/hashicorp/packer/commit/2c3)
Packer v1.0.0
Windows 10

**Comment by rickard-von-essen** [comment] 2017-05-26 04:26
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by mwhooker** [comment] 2017-05-26 18:13
your "PRIOR REFERENCE" link is broken, I'm not really sure what the context for this is

**Comment by vmadman** [comment] 2017-08-01 17:13
I'm having this issue, or a similar one, myself.  (see also #165 , #5094)

**Full Packer Log:**
https://gist.github.com/vmadman/f6686e9e16f99297d7c00e9b73645bf4

**Host Platform:**
Windows 10

**Packer Version:**
1.0.3

I don't know how to create a minimal example, since my source OVF is private, but this has happened with nearly every packer failure and has happened every time when the SSH connection times out.

For what it's worth, though, I have included my template config json in the same Gist that contains my log: https://gist.github.com/vmadman/f6686e9e16f99297d7c00e9b73645bf4

Thanks,

**Comment by mwhooker** [comment] 2017-10-25 17:30
This is great, thanks. I know you opened yours first, but I started looking at #5501 earlier today, and I think they are the same issue. Going to close this one and work off the other ticket. thanks again for the report!

**Comment by mwhooker** [comment] 2017-10-25 17:30
also I have a patch for this in #5512 if you'd like to rest

**Closed by mwhooker** 2017-10-25 17:30 UTC
Labels: builder/virtualbox, need-more-info, waiting-reply
