### ISSUE TITLE
`packer fmt` does not align `=` signs when there are arrays or comments between the lines

### ISSUE THREAD

**Issue by ChristoWolf** [hashicorp/packer#12353] opened 2023-04-07 09:23 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

Calling `packer fmt` fails to align `=` signs when there are arrays or comments between the lines.
Even when formatting such occurrences which are already aligned, the get reformatted to be unaligned.
Found 

#### Reproduction Steps

Use e.g. the following in your template:
```hcl
variable "test_variable" {
  type     = string
  # This is a comment to provoke the behavior.
  default = "test string"
}
```
and 
```hcl
provisioner "powershell" {
    elevated_password = "pw"
    elevated_user          = "user"
    scripts                     = [
      "./scripts/Invoke-Example.ps1" 
    ]
}
```
and
```hcl
error-cleanup-provisioner "powershell" {
    environment_vars = [
      "ERROR_MESSAGE=Packer encountered an error during building!"
    ]
    script                    = "./scripts/Write-PackerError.ps1"
}
```
Then, run `packer fmt .` in the folder which contains such templates.

The results are
```hcl
variable "test_variable" {
  type = string
  # This is a comment to provoke the behavior.
  default = "test string"
}
```
and 
```hcl
provisioner "powershell" {
    elevated_password = "pw"
    elevated_user          = "user"
    scripts = [
      "./scripts/Invoke-Example.ps1" 
    ]
}
```
and
```hcl
error-cleanup-provisioner "powershell" {
    environment_vars = [
      "ERROR_MESSAGE=Packer encountered an error during building!"
    ]
    script = "./scripts/Write-PackerError.ps1"
}
```

### Packer version

Packer v1.8.6

### Simplified Packer Template

See above.

### Operating system and Environment details

Windows version 20H2 (OS Build 19042.2728), 64-bit

### Log Fragments and crash.log files

The names of the files which were formatted are logged out.

**Comment by nywilken** [comment] 2023-04-07 16:58
Hi @ChristoWolf this is intended behavior. Like`terraform fmt` the intended behavior for `packer fmt` is to align the equals signs only for consecutive single-line arguments, and so anything other than a single-line argument will interrupt the alignment group and cause each group to be separately aligned.  The comment in the first example is essentially a new line with no HCL code therefore the next line is considered a new group with no prior HCL to match. The same is true for the example where the list type is spread across multiple lines. 

When you remove all the new lines you will find that the fmt command aligns all the equals signs for each individual group

```
~>  packer fmt -diff /tmp/source.pkr.hcl
/tmp/source.pkr.hcl
--- old//tmp/source.pkr.hcl
+++ new//tmp/source.pkr.hcl
@@ -1,5 +1,5 @@
 variable "test_variable" {
-  type = string # This is a comment to provoke the behavior.
+  type    = string # This is a comment to provoke the behavior.
   default = "test string"
 }

@@ -7,6 +7,6 @@
   provisioner "powershell" {
     elevated_password = "pw"
     elevated_user     = "user"
-    scripts  = ["./scripts/Invoke-Example.ps1"]
+    scripts           = ["./scripts/Invoke-Example.ps1"]
   }
 }
```

I'm going to close this issue as it is intended behavior. More details on this exact issue as described by the Terraform can be found [here](https://github.com/hashicorp/terraform/issues/30278#issuecomment-1004457593)

**Closed by nywilken** 2023-04-07 16:58 UTC
Labels: bug

**Comment by ChristoWolf** [comment] 2023-04-08 04:45
Thanks for clarifying, @nywilken!
