### ISSUE TITLE
File provisioner failing to download from Azure Windows VM

### ISSUE THREAD

**Issue by lokesh755** [hashicorp/packer#5837] opened 2018-02-01 20:01 UTC
Packer is failing to download file from Azure Windows VM. 

Provisioner Details: 

`        {
            "type": "file",
            "source": "C:\\InstalledSoftware.md",
            "destination": "InstalledSoftware.md",
            "direction": "download"
        },`

Packer output: 

`1517514553,,ui,say,==> vhd: Downloading C:\InstalledSoftware.md => InstalledSoftware.md
1517514553,,ui,error,==> vhd: Download failed: http response error: 401 - invalid content type`

Packer Debug Log: 

`2018/02/01 14:49:13 [INFO] (telemetry) Starting provisioner file
2018/02/01 14:49:13 [INFO] 0 bytes written for 'downloadWriter'
2018/02/01 14:49:13 packer.exe: 2018/02/01 14:49:13 [INFO] 0 bytes written for 'downloadWriter'
2018/02/01 14:49:13 [INFO] (telemetry) ending file
2018/02/01 14:49:13 [INFO] (telemetry) found error: http response error: 401 - invalid content type`

**Comment by mwhooker** [comment] 2018-02-01 20:20
please post your complete packer.json file and complete debug log.

**Comment by lokesh755** [comment] 2018-02-01 20:29
I'm running packer again to collect the debug logs.. You can have a look into packer.json https://github.com/Microsoft/vsts-image-generation/blob/users/lokesh/markdown/images/win/vs2017-Server2016-Azure.json#L77-L80

**Comment by lokesh755** [comment] 2018-02-01 20:50
[packerlog.txt](https://github.com/hashicorp/packer/files/1687170/packerlog.txt)
Debug log attached..

**Comment by lokesh755** [comment] 2018-02-02 16:23
Did you get a chance to look into the logs ?

**Comment by lokesh755** [comment] 2018-02-06 18:02
Do you still need more info ?

**Comment by mwhooker** [comment] 2018-02-06 19:24
this is an issue with your winrm set up I think. I don't know what the issue is, but you could try looking at examples of winrm configs here: https://www.packer.io/community-tools.html. You should also make sure you have basic auth enabled. 

Sorry you're having issues with this. If you're still having trouble, I would recommend bringing this to the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk). The mailing list has a lot more eyeballs on it than the github issue tracker, so I think you're more likely to find help there.

If you discover that this is a bug in packer, you should definitely open an issue. However, after a brief glance at this it's not obvious that there's a bug, so I'm going to close this.

**Comment by mwhooker** [comment] 2018-02-07 00:57
@lokesh755 we have a PR we want to test to see if it fixes this. Would you mind testing? It's #5858

**Closed** 2018-02-07 01:18 UTC
Labels: builder/azure, communicator/winrm, need-more-info

**Comment by lokesh755** [comment] 2018-02-14 17:06
Thanks providing link to Mailing list. I am able to resolve it by running below command on the VM 

winrm set winrm/config/service/auth @{Basic="true"}
