### ISSUE TITLE
Packer 1.0.3 hangs during ansible provisioning

### ISSUE THREAD

**Issue by jonesetc** [hashicorp/packer#5215] opened 2017-08-03 15:31 UTC
# Overview

While attempting to provision with ansible a new EBS AMI based off of a GitHub enterprise image, packer hangs and can't complete. This is only an issue on `1.0.3` as far as I can tell, and it works with `1.0.2`. 

# Bullet points

- packer version
    - hangs on `1.0.3`
    - works on `1.0.2`
- host platform
    - System Version: macOS 10.12.4 (16E195)
    - Kernel Version: Darwin 16.5.0
- logs and code
    - https://gist.github.com/jonesetc/bf581d1b3561373263f749faa0d551a2
- other details
    - base AMI requires using port `122` and user `admin`
    - tested sshing into this builder image manually while packer is hanging and it works just fine
    - built with these exact same parameters on `1.0.2` and it worked, so I'm confident that this is all parameterized correctly

**Comment by rickard-von-essen** [comment] 2017-08-03 15:37
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Closed** 2017-08-03 15:43 UTC
Labels: bug, duplicate, provisioner/ansible-remote

**Comment by jonesetc** [comment] 2017-08-03 15:45
Looks like my issue search skills are weak. Already been using 1.0.2 since I saw this, was just trying to get notice in case is was a bug in the unusual port/username mappings in the communicator.

Thanks
