### ISSUE TITLE
Packer crash deploying Azure image 1.4.2

### ISSUE THREAD

**Issue by jzuchora87** [hashicorp/packer#7896] opened 2019-07-22 13:44 UTC
Build process fails with error: **Build 'azure-arm' errored: unexpected EOF**

It actually completed the process of creating the managed image but reports failure. The full crash log and template are below. 

- Packer version : 1.4.2
- Host platform : Windows 2016 Server 64
- Crash.log  https://gist.github.com/jzuchora87/7440db2b70e092d76ec2242000e5c42c
- Template : https://gist.github.com/jzuchora87/5d449ccf83f5c2ab2a409635a6d05ed1

Here is a snippet of the error:

==> azure-arm:  -> Additional Disk : skipping, managed disk was used...
Build 'azure-arm' errored: unexpected EOF
==> Some builds didn't complete successfully and had errors:
--> azure-arm: unexpected EOF
==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is nil, not string
2019/07/22 13:13:40 packer.exe: 
2019/07/22 13:13:40 packer.exe: goroutine 52 [running]:
2019/07/22 13:13:40 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc00045e390, 0x3d01f80, 0xc000094380, 0x3d1a040, 0xc00008e820, 0x3ca1600, 0xc000084b60, 0x0, 0x0, 0x0, ...)
2019/07/22 13:13:40 packer.exe: 	/Users/mmarsh/Projects/packer/builder/azure/arm/builder.go:305 +0x438b
2019/07/22 13:13:40 packer.exe: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00045f2c0, 0x1, 0xc0004fa480, 0x0, 0x0)
2019/07/22 13:13:40 packer.exe: 	/Users/mmarsh/Projects/packer/packer/rpc/builder.go:109 +0x238
2019/07/22 13:13:40 packer.exe: reflect.Value.call(0xc000110960, 0xc0000060b8, 0x13, 0x374d0d9, 0x4, 0xc0005c7f18, 0x3, 0x3, 0xc000344000, 0x3, ...)
2019/07/22 13:13:40 packer.exe: 	/usr/local/go/src/reflect/value.go:447 +0x468
2019/07/22 13:13:40 packer.exe: reflect.Value.Call(0xc000110960, 0xc0000060b8, 0x13, 0xc0005c7f18, 0x3, 0x3, 0xc00023d9e0, 0xc0005c7f30, 0x404c55)
2019/07/22 13:13:40 packer.exe: 	/usr/local/go/src/reflect/value.go:308 +0xab
2019/07/22 13:13:40 packer.exe: net/rpc.(*service).call(0xc000344a00, 0xc0000ca190, 0xc000424368, 0xc000424370, 0xc00047e380, 0xc00008fbc0, 0x2d283e0, 0xc0004fa47c, 0x18a, 0x2c84600, ...)
2019/07/22 13:13:40 packer.exe: 	/usr/local/go/src/net/rpc/server.go:384 +0x155
2019/07/22 13:13:40 packer.exe: created by net/rpc.(*Server).ServeCodec
2019/07/22 13:13:40 packer.exe: 	/usr/local/go/src/net/rpc/server.go:481 +0x432
2019/07/22 13:13:40 [INFO] (telemetry) ending azure-arm
2019/07/22 13:13:40 ui error: Build 'azure-arm' errored: unexpected EOF
2019/07/22 13:13:40 [ERR] Error decoding response stream 58: EOF
2019/07/22 13:13:40 [ERR] Error decoding response stream 41: EOF
2019/07/22 13:13:40 machine readable: error-count []string{"1"}
2019/07/22 13:13:40 ui error: 
==> Some builds didn't complete successfully and had errors:
2019/07/22 13:13:40 machine readable: azure-arm,error []string{"unexpected EOF"}
2019/07/22 13:13:40 ui error: --> azure-arm: unexpected EOF
2019/07/22 13:13:40 ui: 
==> Builds finished but no artifacts were created.
2019/07/22 13:13:40 [INFO] (telemetry) Finalizing.
2019/07/22 13:13:40 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited
2019/07/22 13:13:40 waiting for all plugin processes to complete...
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer-provisioner-dsc.exe: plugin process exited
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited
2019/07/22 13:13:41 C:\agent\_work\4\s\packer\bin\packer.exe: plugin process exited

**Comment by SwampDragons** [comment] 2019-07-22 17:31
This may be a duplicate of #7816 -- can you take a look at the solution described there and let me know if it resolves this?

**Closed** 2019-07-22 21:38 UTC
Labels: bug, builder/azure, crash, duplicate
