### ISSUE TITLE
Error archiving symlink with packer push

### ISSUE THREAD

**Issue by mvermaes** [hashicorp/packer#2433] opened 2015-07-13 07:18 UTC
Hi, I receive an error when trying to use packer push to Atlas, when there is a symlink in the directory. The use case is somewhat similar to #2215 (although using Ansible), but here's a basic config that shows the issue:

```
$ cat push-test.json 
{
  "variables": {
    "atlas_user": "{{ env `ATLAS_USER` }}",
    "atlas_token": "{{ env `ATLAS_TOKEN` }}",
    "aws_access_key": "{{ env `AWS_ACCESS_KEY_ID` }}",
    "aws_secret_key": "{{ env `AWS_SECRET_ACCESS_KEY` }}"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{ user `aws_access_key` }}",
      "secret_key": "{{ user `aws_secret_key` }}",
      "region": "us-east-1",
      "source_ami": "ami-de0d9eb7",
      "instance_type": "t1.micro",
      "ssh_username": "ubuntu",
      "ami_name": "packer-example {{ timestamp }}"
    }
  ],
  "push": {
    "name": "{{ user `atlas_user` }}/push-test",
    "token": "{{ user `atlas_token` }}"
  }
}
```

Directory structure:

```
$ ls -l
total 4
-rw-rw-r--. 1 michaelv michaelv 682 Jul 13 14:56 push-test.json
lrwxrwxrwx. 1 michaelv michaelv  14 Jul 13 14:48 symlink -> push-test.json
$
```

Output:

```
PACKER_LOG=1 packer push push-test.json
2015/07/13 15:06:48 [INFO] Packer version: 0.8.1  872e78d5b0a387eb3b87ddeef210264c3199d178
2015/07/13 15:06:48 Packer Target OS/Arch: linux amd64
2015/07/13 15:06:48 Built with Go Version: go1.4.2
...
2015/07/13 15:06:48 ui error: Error archiving: failed copying file to archive: /tmp/packer-push-test/symlink
2015/07/13 15:06:48 waiting for all plugin processes to complete...
Error archiving: failed copying file to archive: /tmp/packer-push-test/symlink
```

This is with Packer version 0.8.1.

Thanks for your help.

**Comment by mvermaes** [comment] 2015-07-13 07:45
I might have oversimplified the example a bit - I'm actually symlinking ansible.cfg to a subdirectory, and using 'vcs: true' in the packer push config. Unfortunately, just adding these options back to the example above doesn't seem to reproduce my error.

If necessary, I'll provide more detail about my full scenario, but will wait for feedback on the original issue first.

**Comment by cbednarski** [comment] 2015-07-13 19:41
@mvermaes Thanks for the report. I suspect this is an issue with atlas-go so I've created an additional issue there to track it.

**Comment by iroller** [comment] 2016-09-16 20:43
Any updates on this?

**Comment by malaikah** [comment] 2016-11-23 13:50
I also am seeing issues with packer push and symlinks. My issue is that symlinks are not being dereferenced correctly. I'm seeing the issue in packer 0.10.1 and 0.12.0. The file structure is the result of composer-installed dependencies. I can't run the composer install as part of the packer build, as it needs to be able to access an internal scm system.

The structure of the files I am trying to push looks like:

build_root/
|-build_dir/
| |-bin/
| | |- lib1 -> ../vendor/author/lib1/bin/lib
| |
| |- vendor/
| | |- author/
| | | |- lib1/
| | | | |- bin/
| | | | | |- lib
When I packer push, I see:

2016/11/23 12:33:00 [INFO] creating archive from /build_root/build_dir
2016/11/23 12:33:01 ui error: Error archiving: lstat /build_root/build_dir/vendor/author/lib1/bin/lib: no such file or directory
2016/11/23 12:33:01 waiting for all plugin processes to complete...
Error archiving: lstat /build_root/build_dir/vendor/author/lib1/bin/lib

I should be able to work around this with some extra scripting to write out the symlinks to a file, remove them, push the file up and recreate them as a packer step, but that's quite involved and gives me another reason to move functionality back out of Atlas and onto Jenkins.

**Comment by mwhooker** [comment] 2017-01-28 00:57
Here's a PR from @cbednarski's branch: https://github.com/hashicorp/atlas-go/pull/62

There's also a PR here that I understand not as well. https://github.com/hashicorp/atlas-go/pull/59

In order to move this along, it would be helpful if someone who's experienced this issue could test with both PRs and post the results. If we can confirm that one of them works, we can move ahead with closing this out

You'd need to update packer with govendor to use the branch from those PRs and rebuild.

**Comment by SwampDragons** [comment] 2017-08-03 21:51
I've reproduced the issue by putting a symlink to the packer config in the packer push folder 

> ` ✘ mmarsh@Megans-MacBook-Pro  ~/dev/push_test_dir  ll
> lrwxr-xr-x  1 root    staff    14B Jul  7 16:31 linkylink -> test_push.json
> -rw-r--r--  1 mmarsh  staff   1.0K Jun 20 12:00 test_push.json`

but I neither PR seems to fix it.

**Comment by cbednarski** [comment] 2017-08-03 22:33
@SwampDragons To be clear the PR I opened on atlas-go was just to add failing tests, not to fix the bug. I did not already fix the bug.

It's been some time but IIRC what I was planning to do was change from a walk to a set+filter implementation which I think is easier to test. Can chat more about this.

**Closed** 2017-08-08 18:49 UTC
Labels: bug, push, upstream-bug
