### ISSUE TITLE
Error in creating image with qemu.

### ISSUE THREAD

**Issue by c0DeR2020** [hashicorp/packer#9631] opened 2020-07-22 18:59 UTC
Hi,
I'm trying to build a vmware-esxi image with packer-automation tool. I'm seeing issues related to qemu "Failed to shutdown", with an error message "failed to unlock port lockfile: close tcp 127.0.0.1:5990: use of closed network connection".
Can you guys help me with this and the possible fix to it?

Below are the log entries:
-----------------------------------------------------------------------------------
root@NY1EDGPACKER01:/home/schatterjee/maas-esxi# PACKER_LOG=1 ./packer build -var 'vmware_esxi_iso_path=/home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso' /home/schatterjee/maas-esxi/packer-maas/vmware-esxi/vmware-esxi-fixed.json
2020/07/22 11:08:36 [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/07/22 11:08:36 Checking 'PACKER_CONFIG' for a config file path
2020/07/22 11:08:36 'PACKER_CONFIG' not set; checking the default config file path
2020/07/22 11:08:36 Attempting to open config file: /root/.packerconfig
2020/07/22 11:08:36 [WARN] Config file doesn't exist: /root/.packerconfig
2020/07/22 11:08:36 Setting cache directory: /home/schatterjee/maas-esxi/packer_cache
2020/07/22 11:08:36 Creating plugin client for path: /home/schatterjee/maas-esxi/packer
2020/07/22 11:08:36 Starting plugin: /home/schatterjee/maas-esxi/packer []string{"/home/schatterjee/maas-esxi/packer", "plugin", "packer-builder-qemu"}
2020/07/22 11:08:36 Waiting for RPC address for: /home/schatterjee/maas-esxi/packer
2020/07/22 11:08:36 packer-builder-qemu plugin: [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/07/22 11:08:36 packer-builder-qemu plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/22 11:08:36 packer-builder-qemu plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/22 11:08:36 packer-builder-qemu plugin: Attempting to open config file: /root/.packerconfig
2020/07/22 11:08:36 packer-builder-qemu plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2020/07/22 11:08:36 packer-builder-qemu plugin: Setting cache directory: /home/schatterjee/maas-esxi/packer_cache
2020/07/22 11:08:36 packer-builder-qemu plugin: args: []string{"packer-builder-qemu"}
2020/07/22 11:08:36 packer-builder-qemu plugin: Plugin address: unix /tmp/packer-plugin578955587
2020/07/22 11:08:36 packer-builder-qemu plugin: Waiting for connection...
2020/07/22 11:08:36 Received unix RPC address for /home/schatterjee/maas-esxi/packer: addr is /tmp/packer-plugin578955587
2020/07/22 11:08:36 packer-builder-qemu plugin: Serving a plugin connection...
2020/07/22 11:08:36 Creating plugin client for path: /home/schatterjee/maas-esxi/packer
2020/07/22 11:08:36 Starting plugin: /home/schatterjee/maas-esxi/packer []string{"/home/schatterjee/maas-esxi/packer", "plugin", "packer-post-processor-shell-local"}
2020/07/22 11:08:36 Waiting for RPC address for: /home/schatterjee/maas-esxi/packer
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: Attempting to open config file: /root/.packerconfig
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: Setting cache directory: /home/schatterjee/maas-esxi/packer_cache
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: args: []string{"packer-post-processor-shell-local"}
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: Plugin address: unix /tmp/packer-plugin786984718
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: Waiting for connection...
2020/07/22 11:08:36 Received unix RPC address for /home/schatterjee/maas-esxi/packer: addr is /tmp/packer-plugin786984718
2020/07/22 11:08:36 packer-post-processor-shell-local plugin: Serving a plugin connection...
2020/07/22 11:08:36 Creating plugin client for path: /home/schatterjee/maas-esxi/packer
2020/07/22 11:08:36 Starting plugin: /home/schatterjee/maas-esxi/packer []string{"/home/schatterjee/maas-esxi/packer", "plugin", "packer-post-processor-compress"}
2020/07/22 11:08:36 Waiting for RPC address for: /home/schatterjee/maas-esxi/packer
2020/07/22 11:08:36 packer-post-processor-compress plugin: [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/07/22 11:08:36 packer-post-processor-compress plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/22 11:08:36 packer-post-processor-compress plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/22 11:08:36 packer-post-processor-compress plugin: Attempting to open config file: /root/.packerconfig
2020/07/22 11:08:36 packer-post-processor-compress plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2020/07/22 11:08:36 packer-post-processor-compress plugin: Setting cache directory: /home/schatterjee/maas-esxi/packer_cache
2020/07/22 11:08:36 packer-post-processor-compress plugin: args: []string{"packer-post-processor-compress"}
2020/07/22 11:08:36 packer-post-processor-compress plugin: Plugin address: unix /tmp/packer-plugin421215070
2020/07/22 11:08:36 packer-post-processor-compress plugin: Waiting for connection...
2020/07/22 11:08:36 Received unix RPC address for /home/schatterjee/maas-esxi/packer: addr is /tmp/packer-plugin421215070
2020/07/22 11:08:36 packer-post-processor-compress plugin: Serving a plugin connection...
2020/07/22 11:08:36 Preparing build: qemu
2020/07/22 11:08:36 packer-builder-qemu plugin: use detected accelerator: kvm
2020/07/22 11:08:36 packer-builder-qemu plugin: CpuCount 0 too small, using default: 1

A checksum of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

2020/07/22 11:08:36 Build debug mode: false
2020/07/22 11:08:36 Force build: false
2020/07/22 11:08:36 On error:
2020/07/22 11:08:36 Waiting on builds to complete...
Warning: Warning when preparing build: "qemu"
2020/07/22 11:08:36 Starting build run: qemu

2020/07/22 11:08:36 Running builder: qemu
2020/07/22 11:08:36 [INFO] (telemetry) Starting builder qemu
A checksum of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

qemu: output will be in this color.

2020/07/22 11:08:36 packer-builder-qemu plugin: Qemu path: /usr/bin/qemu-system-x86_64, Qemu Image page: /usr/bin/qemu-img
==> qemu: Retrieving ISO
==> qemu: Trying /home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso
2020/07/22 11:08:36 packer-builder-qemu plugin: Acquiring lock for: /home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso (/home/schatterjee/maas-esxi/packer_cache/8e10e605dc23f799ecad94beede8fe2ac0e4b91b.iso.lock)
==> qemu: Trying /home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso
2020/07/22 11:08:36 packer-builder-qemu plugin: Leaving retrieve loop for ISO
2020/07/22 11:08:36 packer-builder-qemu plugin: No floppy files specified. Floppy disk will not be made.
==> qemu: /home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso => /home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso
==> qemu: Creating required virtual machine disks
2020/07/22 11:08:36 packer-builder-qemu plugin: [INFO] Creating disk with Path: output-qemu/packer-qemu and Size: 10G
2020/07/22 11:08:36 packer-builder-qemu plugin: Executing qemu-img: []string{"create", "-f", "raw", "output-qemu/packer-qemu", "10G"}
2020/07/22 11:08:36 packer-builder-qemu plugin: stdout: Formatting 'output-qemu/packer-qemu', fmt=raw size=10737418240
2020/07/22 11:08:36 packer-builder-qemu plugin: stderr:
2020/07/22 11:08:36 packer-builder-qemu plugin: Found available port: 8956 on IP: 0.0.0.0
==> qemu: Starting HTTP server on port 8956
2020/07/22 11:08:36 packer-builder-qemu plugin: Looking for available port between 5900 and 6000 on 127.0.0.1
==> qemu: Looking for available port between 5900 and 6000 on 127.0.0.1
2020/07/22 11:08:36 packer-builder-qemu plugin: Found available port: 5990 on IP: 127.0.0.1
2020/07/22 11:08:36 packer-builder-qemu plugin: Found available VNC port: 5990 on IP: 127.0.0.1
==> qemu: Starting VM, booting from CD-ROM
2020/07/22 11:08:36 packer-builder-qemu plugin: Qemu --version output: QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.28)
2020/07/22 11:08:36 packer-builder-qemu plugin: Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
2020/07/22 11:08:36 packer-builder-qemu plugin: Qemu version: 2.11.1
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: vnc://127.0.0.1:5990
2020/07/22 11:08:36 packer-builder-qemu plugin: Qemu Builder has no floppy files, not attaching a floppy.
    qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: vnc://127.0.0.1:5990
==> qemu: Overriding defaults Qemu arguments with QemuArgs...
2020/07/22 11:08:36 packer-builder-qemu plugin: Executing /usr/bin/qemu-system-x86_64: []string{"-cpu", "host", "-vnc", "127.0.0.1:90", "-netdev", "user,id=user.0", "-device", "e1000,netdev=user.0", "-cdrom", "/home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso", "-name", "packer-qemu", "-machine", "type=pc,accel=kvm", "-smp", "2,sockets=2,cores=1,threads=1", "-boot", "once=d", "-drive", "file=output-qemu/packer-qemu,if=ide,cache=writeback,discard=ignore,format=raw", "-m", "4096M"}
2020/07/22 11:08:36 packer-builder-qemu plugin: Started Qemu. Pid: 9766
==> qemu: Waiting 3s for boot...
==> qemu: Connecting to VM via VNC (127.0.0.1:5990)
2020/07/22 11:08:41 packer-builder-qemu plugin: Connected to VNC desktop: QEMU (packer-qemu)
==> qemu: Typing the boot command over VNC...
2020/07/22 11:08:41 packer-builder-qemu plugin: Special code '<enter>' found, replacing with: 0xFF0D
2020/07/22 11:08:42 packer-builder-qemu plugin: [INFO] Waiting 1s
2020/07/22 11:08:43 packer-builder-qemu plugin: Special code '<leftshift>' found, replacing with: 0xFFE1
2020/07/22 11:08:43 packer-builder-qemu plugin: Sending char 'O', code 0x4F, shift true
2020/07/22 11:08:43 packer-builder-qemu plugin: Sending char ' ', code 0x20, shift false
2020/07/22 11:08:43 packer-builder-qemu plugin: Sending char 'k', code 0x6B, shift false
2020/07/22 11:08:44 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2020/07/22 11:08:44 packer-builder-qemu plugin: Sending char '=', code 0x3D, shift false
2020/07/22 11:08:44 packer-builder-qemu plugin: Sending char 'h', code 0x68, shift false
2020/07/22 11:08:44 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2020/07/22 11:08:44 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2020/07/22 11:08:45 packer-builder-qemu plugin: Sending char 'p', code 0x70, shift false
2020/07/22 11:08:45 packer-builder-qemu plugin: Sending char ':', code 0x3A, shift true
2020/07/22 11:08:45 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2020/07/22 11:08:45 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2020/07/22 11:08:46 packer-builder-qemu plugin: Sending char '1', code 0x31, shift false
2020/07/22 11:08:46 packer-builder-qemu plugin: Sending char '0', code 0x30, shift false
2020/07/22 11:08:46 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2020/07/22 11:08:46 packer-builder-qemu plugin: Sending char '0', code 0x30, shift false
2020/07/22 11:08:46 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2020/07/22 11:08:47 packer-builder-qemu plugin: Sending char '2', code 0x32, shift false
2020/07/22 11:08:47 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2020/07/22 11:08:47 packer-builder-qemu plugin: Sending char '2', code 0x32, shift false
2020/07/22 11:08:47 packer-builder-qemu plugin: Sending char ':', code 0x3A, shift true
2020/07/22 11:08:48 packer-builder-qemu plugin: Sending char '8', code 0x38, shift false
2020/07/22 11:08:48 packer-builder-qemu plugin: Sending char '9', code 0x39, shift false
2020/07/22 11:08:48 packer-builder-qemu plugin: Sending char '5', code 0x35, shift false
2020/07/22 11:08:48 packer-builder-qemu plugin: Sending char '6', code 0x36, shift false
2020/07/22 11:08:48 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2020/07/22 11:08:49 packer-builder-qemu plugin: Sending char 'v', code 0x76, shift false
2020/07/22 11:08:49 packer-builder-qemu plugin: Sending char 'm', code 0x6D, shift false
2020/07/22 11:08:49 packer-builder-qemu plugin: Sending char 'w', code 0x77, shift false
2020/07/22 11:08:49 packer-builder-qemu plugin: Sending char 'a', code 0x61, shift false
2020/07/22 11:08:49 packer-builder-qemu plugin: Sending char 'r', code 0x72, shift false
2020/07/22 11:08:50 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2020/07/22 11:08:50 packer-builder-qemu plugin: Sending char '-', code 0x2D, shift false
2020/07/22 11:08:50 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2020/07/22 11:08:50 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2020/07/22 11:08:50 packer-builder-qemu plugin: Sending char 'x', code 0x78, shift false
2020/07/22 11:08:51 packer-builder-qemu plugin: Sending char 'i', code 0x69, shift false
2020/07/22 11:08:51 packer-builder-qemu plugin: Sending char '-', code 0x2D, shift false
2020/07/22 11:08:51 packer-builder-qemu plugin: Sending char 'k', code 0x6B, shift false
2020/07/22 11:08:51 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2020/07/22 11:08:51 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2020/07/22 11:08:52 packer-builder-qemu plugin: Sending char 'c', code 0x63, shift false
2020/07/22 11:08:52 packer-builder-qemu plugin: Sending char 'f', code 0x66, shift false
2020/07/22 11:08:52 packer-builder-qemu plugin: Sending char 'g', code 0x67, shift false
2020/07/22 11:08:52 packer-builder-qemu plugin: Special code '<enter>' found, replacing with: 0xFF0D
2020/07/22 11:08:52 packer-builder-qemu plugin: Unable to load communicator config from state to populate provisionHookData
2020/07/22 11:08:52 packer-builder-qemu plugin: Running the provision hook
==> qemu: Waiting for shutdown...
==> qemu: Failed to shutdown
**2020/07/22 11:28:52 packer-builder-qemu plugin: Unable to load communicator config from state to populate provisionHookData**
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
2020/07/22 11:28:52 **packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5990: use of closed network connection**
==> qemu: Deleting output directory...
2020/07/22 11:28:52 [INFO] (telemetry) ending qemu
2020/07/22 11:28:52 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/07/22 11:28:52 machine readable: qemu,error []string{"Failed to shutdown"}
==> Builds finished but no artifacts were created.
Build 'qemu' errored: Failed to shutdown

2020/07/22 11:28:52 [INFO] (telemetry) Finalizing.
==> Some builds didn't complete successfully and had errors:
--> qemu: Failed to shutdown

==> Builds finished but no artifacts were created.
2020/07/22 11:28:52 waiting for all plugin processes to complete...
2020/07/22 11:28:52 /home/schatterjee/maas-esxi/packer: plugin process exited
2020/07/22 11:28:52 /home/schatterjee/maas-esxi/packer: plugin process exited
2020/07/22 11:28:52 /home/schatterjee/maas-esxi/packer: plugin process exited

**Comment by SwampDragons** [comment] 2020-07-23 20:51
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- The _simplest complete example template and scripts_ needed to reproduce the bug.  (Include these in your gist)

**Comment by c0DeR2020** [comment] 2020-07-23 22:10
Packer version - 1.6.0
Host platform - Ubuntu 18.04
Here's the CLI:   
PACKER_LOG=1 ./packer build -var 'vmware_esxi_iso_path=/home/schatterjee/OS/VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso' /home/schatterjee/maas-esxi/packer-maas/vmware-esxi/vmware-esxi-fixed.json

Followed the steps mentioned in doc: https://maas.io/tutorials/maas-esxi-quickstart#3-creating-your-image

**Comment by SwampDragons** [comment] 2020-08-05 20:08
Hi, just took a look at this. The issue isn't either of the bolded log lines, it's `Failed to shutdown`. Make sure that your [shutdown_command](https://www.packer.io/docs/builders/qemu#shutdown_command) is valid and actually shuts down the VM, and then increase the [shutdown_timeout](https://www.packer.io/docs/builders/qemu#shutdown_timeout). 

I can't download your template without registering for that product, so that's the best I can do for you without having a template shared in a gist.

**Comment by nywilken** [comment] 2020-08-26 18:17
Hi there, I'm going to mark this as closed as this appears to be a Packer configuration issue and not an actual Packer bug. If I've made a mistake and you think this is a bug in Packer please open a new  [Bug report](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) with the provided information requested in the template so that we can re-investigate. Cheers!

**Closed by nywilken** 2020-08-26 18:17 UTC
Labels: builder/qemu, need-more-info, need-repro, question, waiting-reply
