### ISSUE TITLE
Hyper-V ISO builder fails to download ISO file from local drive

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/packer#5700] opened 2017-12-13 07:27 UTC
Packer version: 1.1.3

Host platform: Win 10.  
Version:  1709. 
OS build: 16299.98

Trying to build a Ubuntu VM on Hyper-V with Packer 1.1.3 fails when Packer tries to download the Ubuntu ISO file from a local disk (but a different disk than where the packer configuration lives). The command line output is:

    & packer.exe build -var-file="E:\documents\Petrik\documents\operations\calvinverse\base.linux\build\temp\build\packer_variables.json" "E:\documents\Petrik\documents\operations\calvinverse\base.linux\build\temp\build\packer.json"
    hyperv-iso output will be in this color

    ==> hyperv-iso: Creating temporary directory...
    ==> hyperv-iso: Downloading or copying ISO
        hyperv-iso: Downloading or copying: file://F:/iso/linux/ubuntu-16.04.1-server-amd64.iso
        hyperv-iso: Error downloading: CreateFile /iso/linux/ubuntu-16.04.1-server-amd64.iso: The system cannot find the path specified.
    ==> hyperv-iso: ISO download failed.
    ==> hyperv-iso: Deleting output directory...
    ==> hyperv-iso: Deleting temporary directory...
    Build 'hyperv-iso' errored: ISO download failed.

    ==> Some builds didn't complete successfully and had errors:
    --> hyperv-iso: ISO download failed.

    ==> Builds finished but no artifacts were created.

The build log and the configurations can be found in this [gist](https://gist.github.com/pvandervelde/67e69235470a2168f52b20863340f146).

This might potentially be related to #5620

**Comment by SwampDragons** [comment] 2017-12-13 19:24
Thanks for this!  Will look into this as soon as I can.

**Comment by arizvisa** [comment] 2017-12-21 07:19
Btw..likely already fixed by #2906 which converts local platform-specific paths to an rfc-compliant uri (file://) in `common/config.go`, and then uses the protocol's interface implementation (LocalDownloader in `common/download.go`) to determine whether it can be converted to a local path. This fixes the '\\' issue with net/url introduced in golang 1.6 and allows for one to specify UNC-paths on Windows without needing to use the `runtime.GOOS == "windows"` which are spotted everywhere.

**Comment by PatrickLang** [comment] 2018-01-01 02:49
Seems to be working for me in v1.1.3

```none
PS C:\Users\patrick\Source\packer-windows> packer build -only=hyperv-iso -var 'iso_url=C:\Users\patrick\Downloads\Windows_InsiderPreview_Server_17035.iso' .\windows_server_insider.json

hyperv-iso output will be in this color.

Warnings for build 'hyperv-iso':

* For nested virtualization, when virtualization extension is enabled, mac spoofing should be allowed.
* For nested virtualization, when virtualization extension is enabled, there should be 4GB or more memory set for the vm, otherwise Hyper-V may fail to start any nested VMs.

==> hyperv-iso: Creating temporary directory...
==> hyperv-iso: Downloading or copying ISO
    hyperv-iso: Downloading or copying: file://C:/Users/patrick/Downloads/Windows_InsiderPreview_Server_17035.iso
==> hyperv-iso: Creating switch 'External' if required...
==> hyperv-iso:     switch 'External' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive /Users/patrick/Downloads/Windows_InsiderPreview_Server_17035.iso ...
==> hyperv-iso: Mounting os dvd drive /Users/patrick/Downloads/Windows_InsiderPreview_Server_17035.iso ...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Mounting secondary dvd drive ./iso/windows_server_insider_unattend.iso ...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Starting the virtual machine...
```

Source (work in progress): https://github.com/PatrickLang/packer-windows/blob/hyperv-insider-gen2/windows_server_insider.json

**Comment by SwampDragons** [comment] 2018-01-03 23:59
I suspect this is a duplicate of https://github.com/hashicorp/packer/issues/5713; I have a PR that I'm just cleaning up tests for, and intend to have this fixed for the next release.

**Comment by kaluznyt** [comment] 2018-01-05 16:05
I cannot get it to work with not relative path it always fails when I put something like: 
```

"variables": {
		"iso_url": "c:/software/iso/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",
```

`"iso_url": "file://c:/software/iso/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",`

in the json, but it works straight away when it's just:

`"iso_url": "./iso/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",`

in the first 2 cases it's throwing:

```
 virtualbox-iso: Downloading or copying: file://c:/software/iso/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso
    virtualbox-iso: Error downloading: CreateFile /software/iso/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso: The system cannot find the path specified.
```

**Comment by SwampDragons** [comment] 2018-01-06 00:14
Yep, this is definitely a duplicate of 5713; closing so we can track all in one place.

**Closed by SwampDragons** 2018-01-06 00:14 UTC
Labels: bug, builder/hyperv, duplicate
