### ISSUE TITLE
Feature request: Amazon clean up non-encrypted snapshot

### ISSUE THREAD

**Issue by allyunion** [hashicorp/packer#6690] opened 2018-09-11 15:01 UTC
It would be nice when creating encrypted AMIs that packer cleans up the not encrypted snap volume after the encrypted snap volume is complete

**Comment by SwampDragons** [comment] 2018-09-11 21:46
Hmm. That should be the default behavior. Do you have an example config that reproduces this?

**Comment by natefox** [comment] 2018-09-14 19:59
Make sure to have `encrypt_boot: true`. I had this issue when encrypting with `ami_block_device_mappings` -> `encrypted:true` but without `encrypt_boot: true`

**Comment by azr** [comment] 2018-10-05 09:03
#6787 will do that cleanup !

**Comment by SwampDragons** [comment] 2018-10-12 18:54
Changing the milestone to v1.4.0 since the solution will contain some backwards incompatibility for edge cases.

**Comment by rickard-von-essen** [comment] 2019-03-02 08:17
@azr is this closed by #6787?

**Comment by azr** [comment] 2019-03-04 10:02
@rickard-von-essen Yes thanks for the ping 🙂

**Closed by azr** 2019-03-04 10:02 UTC
Labels: bug, builder/amazon
