### ISSUE TITLE
Crash - 1.4.2 Unexpected EOF + interface {} is nil, not string

### ISSUE THREAD

**Issue by DavidR91** [hashicorp/packer#7937] opened 2019-08-01 13:45 UTC
hashicorp/packer:light 1.4.2 on Docker (Ubuntu 1604 LTS)

This problem is not deterministic/consistent as far as I can tell so I haven't re-run with DEBUG 
  
Circumstances:
* Two parallel builds, both building Azure images
* One VHD, the other an Azure managed image
* Both reach the phase of saying ` The resource group was created by Packer, deleting`
* The managed builder subsequently fails with this error

Relevant output: (note the console control codes are garbled because this is being run headless)

```
[1;31mBuild 'managed' errored: unexpected EOF[0m

==> Some builds didn't complete successfully and had errors:
--> managed: unexpected EOF

panic: interface conversion: interface {} is nil, not string
2019/08/01 13:22:06 packer: 
2019/08/01 13:22:06 packer: goroutine 34 [running]:
2019/08/01 13:22:06 packer: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc000498f30, 0x3c5b160, 0xc00008c0c0, 0x3c732a0, 0xc000622900, 0x3bfaf00, 0xc0005a49a0, 0x0, 0x0, 0x0, ...)
2019/08/01 13:22:06 packer: 	/Users/mmarsh/Projects/packer/builder/azure/arm/builder.go:305 +0x4384
2019/08/01 13:22:06 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc000333da0, 0x1, 0xc00062a020, 0x0, 0x0)
2019/08/01 13:22:06 packer: 	/Users/mmarsh/Projects/packer/packer/rpc/builder.go:109 +0x231
2019/08/01 13:22:06 packer: reflect.Value.call(0xc000090ae0, 0xc00000e2b0, 0x13, 0x36aa961, 0x4, 0xc0000b8f18, 0x3, 0x3, 0xc000352ec0, 0x3, ...)
2019/08/01 13:22:06 packer: 	/usr/local/go/src/reflect/value.go:447 +0x461
2019/08/01 13:22:06 packer: reflect.Value.Call(0xc000090ae0, 0xc00000e2b0, 0x13, 0xc00076ef18, 0x3, 0x3, 0xc000758540, 0xc00076ef30, 0x404e35)
2019/08/01 13:22:06 packer: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2019/08/01 13:22:06 packer: net/rpc.(*service).call(0xc000353100, 0xc00037e230, 0xc000057418, 0xc000057420, 0xc000372700, 0xc0000199a0, 0x2c84720, 0xc00062a01c, 0x18a, 0x2be05c0, ...)
2019/08/01 13:22:06 packer: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2019/08/01 13:22:06 packer: created by net/rpc.(*Server).ServeCodec
2019/08/01 13:22:06 packer: 	/usr/local/go/src/net/rpc/server.go:481 +0x42b
2019/08/01 13:22:06 [INFO] (telemetry) ending azure-arm
2019/08/01 13:22:06 ui error: [1;31mBuild 'managed' errored: unexpected EOF[0m
2019/08/01 13:22:06 machine readable: error-count []string{"1"}
2019/08/01 13:22:06 ui error: 
==> Some builds didn't complete successfully and had errors:
2019/08/01 13:22:06 machine readable: managed,error []string{"unexpected EOF"}
2019/08/01 13:22:06 ui error: --> managed: unexpected EOF
2019/08/01 13:22:06 ui: 
==> Builds finished. The artifacts of successful builds are:
2019/08/01 13:22:06 machine readable: vhd,artifact-count []string{"1"}
2019/08/01 13:22:06 [ERR] Error decoding response stream 23: EOF
2019/08/01 13:22:06 /bin/packer: plugin process exited
2019/08/01 13:22:06 machine readable: vhd,artifact []string{"0", "builder-id", "Azure.ResourceManagement.VMImage"}
2019/08/01 13:22:06 machine readable: vhd,artifact []string{"0", "id", "https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-osDisk.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.vhd"}
2019/08/01 13:22:06 machine readable: vhd,artifact []string{"0", "string", "Azure.ResourceManagement.VMImage:\n\nOSType: Windows\nStorageAccountLocation: westeurope\nOSDiskUri: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-osDisk.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.vhd\nOSDiskUriReadOnlySas: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-osDisk.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.vhd?se=2019-09-01T13%!A(MISSING)21%!A(MISSING)35Z&sig=xYrFTUu9i6XOQeAXd%!F(MISSING)dDkzwou835V6iCp7ON5lZQTBY%!D(MISSING)&sp=r&sr=b&sv=2016-05-31\nTemplateUri: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-vmTemplate.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.json\nTemplateUriReadOnlySas: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-vmTemplate.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.json?se=2019-09-01T13%!A(MISSING)21%!A(MISSING)35Z&sig=hEyoLhIk7nXPv14dqTMu7zvzE40Jn3%!F(MISSING)AxF2iSr9qG6Q%!D(MISSING)&sp=r&sr=b&sv=2016-05-31\n"}
2019/08/01 13:22:06 machine readable: vhd,artifact []string{"0", "files-count", "0"}
2019/08/01 13:22:06 machine readable: vhd,artifact []string{"0", "end"}
2019/08/01 13:22:06 ui: --> vhd: Azure.ResourceManagement.VMImage:

OSType: Windows
StorageAccountLocation: westeurope
OSDiskUri: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-osDisk.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.vhd
OSDiskUriReadOnlySas: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-osDisk.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.vhd?se=2019-09-01T13%!A(MISSING)21%!A(MISSING)35Z&sig=xYrFTUu9i6XOQeAXd%!F(MISSING)dDkzwou835V6iCp7ON5lZQTBY%!D(MISSING)&sp=r&sr=b&sv=2016-05-31
TemplateUri: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-vmTemplate.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.json
TemplateUriReadOnlySas: https://****.blob.core.windows.net/system/Microsoft.Compute/Images/****/****-vmTemplate.a1a11fa7-f2e8-4f1c-9172-ab1040b41f0b.json?se=2019-09-01T13%!A(MISSING)21%!A(MISSING)35Z&sig=hEyoLhIk7nXPv14dqTMu7zvzE40Jn3%!F(MISSING)AxF2iSr9qG6Q%!D(MISSING)&sp=r&sr=b&sv=2016-05-31
2019/08/01 13:22:06 [INFO] (telemetry) Finalizing.
2019/08/01 13:22:07 waiting for all plugin processes to complete...
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 [ERR] Error decoding response stream 23: EOF
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited
2019/08/01 13:22:07 /bin/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Unfortunately  the crash log would have been written to temporary volume storage which has been lost** (due to the nature of this being executed by an automatic job)

**Comment by SwampDragons** [comment] 2019-08-01 16:35
This may be a duplicate of #7816 -- can you take a look at the solution described there and let me know if it resolves this?

**Comment by DavidR91** [comment] 2019-08-05 09:19
Unfortunately I can't use an arbitrary build in this particular case - but I _can_ confirm that downgrading to 1.3.2 resolves the problem 

I'm happy for this to be considered a duplicate as stated since it seems likely

**Comment by jonesbusy** [comment] 2019-08-05 21:11
Same issue. Works with packer 1.4.0

**Comment by bmunsen** [comment] 2019-08-28 21:52
I'm getting what appears to be the same error with Packer 1.4.3 on Windows 10 64-bit, trying to build a simple Windows Server 2016 managed image in Azure.  Also of note is that at the moment, I'm manually authenticating to the tenant subscription using Partner Center admin account credentials, rather than specifying a client ID and secret.  I tried downgrading to 1.4.0 per the last comment, but that did not resolve the issue.

Relevant log output citing the same "interface {} is nil, not string" error when trying to build the ARM client:

> 2019/08/28 16:27:26 ui:     azure-arm: Creating Azure Resource Manager (ARM) client ...
2019/08/28 16:27:26 packer.exe: panic: interface conversion: interface {} is nil, not string
2019/08/28 16:27:26 packer.exe: 
2019/08/28 16:27:26 packer.exe: goroutine 98 [running]:
2019/08/28 16:27:26 packer.exe: github.com/hashicorp/packer/builder/azure/arm.getObjectIdFromToken(0x4063520, 0xc0003440c0, 0xc0001a8c00, 0x0, 0x0)
2019/08/28 16:27:26 packer.exe: 	/Users/mmarsh/Projects/packer/builder/azure/arm/builder.go:442 +0x1ed
2019/08/28 16:27:26 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc000016300, 0x4047b40, 0xc00033e8c0, 0x4063520, 0xc0003440c0, 0x3fe0f80, 0xc00024e060, 0x0, 0x0, 0x0, ...)
2019/08/28 16:27:26 packer.exe: 	/Users/mmarsh/Projects/packer/builder/azure/arm/builder.go:106 +0x5e3
2019/08/28 16:27:26 packer.exe: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00027c4b0, 0x1, 0xc000468040, 0x0, 0x0)
2019/08/28 16:27:26 packer.exe: 	/Users/mmarsh/Projects/packer/packer/rpc/builder.go:109 +0x238
2019/08/28 16:27:26 packer.exe: reflect.Value.call(0xc000074960, 0xc000354088, 0x13, 0x3a31e6b, 0x4, 0xc0004a9f18, 0x3, 0x3, 0xc000072d80, 0xc0004683e0, ...)
2019/08/28 16:27:26 packer.exe: 	/usr/local/go/src/reflect/value.go:447 +0x468
2019/08/28 16:27:26 packer.exe: reflect.Value.Call(0xc000074960, 0xc000354088, 0x13, 0xc0004a9f18, 0x3, 0x3, 0xc000514150, 0x0, 0x0)
2019/08/28 16:27:26 packer.exe: 	/usr/local/go/src/reflect/value.go:308 +0xab
2019/08/28 16:27:26 packer.exe: net/rpc.(*service).call(0xc00033e980, 0xc00035c190, 0xc0004683d0, 0xc0004683e0, 0xc00001e280, 0xc00027aae0, 0x2f68c20, 0xc00046802c, 0x18a, 0x2ebbae0, ...)
2019/08/28 16:27:26 packer.exe: 	/usr/local/go/src/net/rpc/server.go:384 +0x155
2019/08/28 16:27:26 packer.exe: created by net/rpc.(*Server).ServeCodec
2019/08/28 16:27:26 packer.exe: 	/usr/local/go/src/net/rpc/server.go:481 +0x432
2019/08/28 16:27:26 [INFO] (telemetry) ending azure-arm
2019/08/28 16:27:26 ui error: Build 'azure-arm' errored: unexpected EOF
2019/08/28 16:27:26 machine readable: error-count []string{"1"}

**Comment by azr** [comment] 2019-08-29 08:38
Hello @bmunsen, I think you issue is a little different but that the crash should have been fixed in  #8047; can you please try a binary in : https://circleci.com/gh/hashicorp/packer/9947#artifacts/containers/0 and tell me if it was fixed ?

**Comment by bmunsen** [comment] 2019-08-29 17:53
That binary gets past that nil error, but after authenticating with my Partner Center account, now I get an error stating "could not determine the ObjectID for the user, which is required for Windows builds".  Not sure if that's a completely unrelated issue or not.

**Comment by azr** [comment] 2019-08-30 10:09
Hey @bmunsen, yes now I think this should be a configuration issue and I would recommend asking for help in packer's [discussion list](https://www.packer.io/community.html).

**Comment by SwampDragons** [comment] 2019-09-03 17:52
That's an unrelated issue and probably means you aren't setting your authentication variables properly. I'm closing this because the original issue is resolved; if you find something else that you believe is a bug, please open a new issue with steps to reproduce :)

**Closed by SwampDragons** 2019-09-03 17:52 UTC
Labels: builder/azure, duplicate
