### ISSUE TITLE
Using Vagrant builder, authentication error when trying to connect via SSH

### ISSUE THREAD

**Issue by rhanneken** [hashicorp/packer#8797] opened 2020-02-25 20:03 UTC
#### Overview of the Issue

I'm trying to build a Vagrant box with the Vagrant builder. The build fails consistently with the message "Packer experienced an authentication error when trying to connect via SSH." I have attempted the build with two different Vagrant base boxes (`freebsd/FreeBSD-12.1-STABLE` and `hashicorp/bionic64`, in both cases using the `virtualbox` provider).

Possibly this is related to [issue 8750](https://github.com/hashicorp/packer/issues/8750).

#### Reproduction Steps

Using the template mentioned below, with the filename `example.pkr.hcl`, enter the following command:

``` sh
PACKER_LOG=1 packer build -debug example.pkr.hcl
```

**EXPECTED RESULT**: The build succeeds. An artifact is generated.

**ACTUAL RESULT**: The build fails. No artifact is generated. The following error message is emitted: "Packer experienced an authentication error when trying to connect via SSH."

### Packer version

Packer v1.5.4

### Simplified Packer Buildfile

``` hcl
source "vagrant" "example" {
    source_path = "freebsd/FreeBSD-12.1-STABLE"
    provider = "virtualbox"
    communicator = "ssh"
}

build {
    sources = [
        "source.vagrant.example"
    ]

    provisioner "shell" {
        inline = ["echo 'hi'"]
    }
}
```

### Operating system and Environment details

I am using macOS 10.14.6 on a MacBook Pro (Retina, 15-inch, Mid 2015). I used Homebrew to install Packer. Vagrant is version 2.2.7, and VirtualBox is version 6.1.4.

### Log Fragments and crash.log files

The build log is [here](https://gist.github.com/rhanneken/f2ec70f75885890a40215b3e5283c367).

**Comment by nmusatti** [comment] 2020-02-25 22:28
Same problem for me with a CentOS 7 host running VirtualBox 6.1.4, using the Vagrant builder with a locally built CentOS 7 base box.

**Comment by rhanneken** [comment] 2020-02-26 19:29
These lines in the log look like they could be important:

```
2020/02/26 11:22:57 packer-builder-vagrant plugin: identity file is /Users/example_user/.vagrant.d/insecure_private_key
2020/02/26 11:22:57 packer-builder-vagrant plugin: Removing quotes from identity file
2020/02/26 11:22:57 packer-builder-vagrant plugin: Error unquoting identity file: invalid syntax
```

**Comment by rhanneken** [comment] 2020-02-26 23:01
I think the problem is due to [this change](https://github.com/hashicorp/packer/pull/8605). When the code parses [the line for `IdentityFile`](https://man.openbsd.org/ssh_config#IdentityFile) in the SSH config (in the case of the Vagrant builder, the output of running `vagrant ssh-config`), [the Packer code now filters the value through `strconv.Unquote`](https://github.com/hashicorp/packer/pull/8605/files#diff-2543393cb88e8bb6538e34266a26e91dR59). However, [the documentation for `strconv.Unquote`](https://golang.org/pkg/strconv/#Unquote) says that if its input isn't quoted, that results in an error (expand the "Example" section to see what I mean). In the context of the Packer code, I think that means `sshConfig.IdentityFile` doesn't get set, which means the SSH client can't connect to the server.

**Comment by nywilken** [comment] 2020-02-27 19:59
Thanks for reaching out. This issue is a duplicate of #8736 . I’m going to close this issue and ask that all additional comments be tracked on the original issue. 

If you think this issue is different please let me know and I will gladly reopen this issue.

**Closed by nywilken** 2020-02-27 19:59 UTC
Labels: bug
