### ISSUE TITLE
amazon-ebs: Validation error when sharing AMI with encrypted boot volume

### ISSUE THREAD

**Issue by amphied** [hashicorp/packer#7346] opened 2019-02-26 08:25 UTC
In `func Prepare` of `ami_config.go` packer seems to validate that AMIs with encrypted boot volumes cannot be shared.
This validation is only correct for the specific case of using the default KMS key `aws/ebs`, but generally AWS allows sharing AMIs when using a CMK.

error message:

    1 error(s) occurred:
    
    * Cannot share AMI with encrypted boot volume

packer version: 1.3.4
host: Ubuntu 18.04
  
minimal example:

    {
      "builders": [
        {
          "type": "amazon-ebs",
          "region": "eu-west-1",
          "source_ami_filter": {
            ...
          },
          "ami_regions": [
            "us-west-1"
          ],
          "encrypt_boot": true,
          "kms_key_id": "arn:aws:kms:eu-west-1:123456789012:alias/xx-ami",
          "region_kms_key_ids": {
            "us-west-1": "arn:aws:kms:us-west-1:123456789012:alias/xx-ami",
          },
          "ami_users": [
            "234567890123"
          ]
        }
      ],
      "provisioners": [
        ...
      ]
    }

**Comment by rickard-von-essen** [comment] 2019-02-26 12:25
You can't share an AMI with encrypted EBS volumes, you can only share the EBS snapshots with CMK.

**Comment by amphied** [comment] 2019-02-27 00:24
Maybe this was just added or enabled recently, since the [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html) supports your claim, @rickard-von-essen

However, it works as expected: following what is outlined in [this gist](https://gist.github.com/amphied/040d9601b5aaa67af4d577e17dcf6c2f), I am able to launch an instance from the shared AMI in the secondary AWS account.

Some notes:
* as you can see in the gist, the AMI has `launchPermission` set, while the snapshot has no `createVolumePermission` set
* the secondary account obviously must have access to the CMK
* the secondary account _can_ view the details of the AMI
* the secondary account _cannot_ view the details of the snapshot (for details see comment on the same gist)

**Comment by bwn-a** [comment] 2019-04-19 07:19
I am encountering the same issue, is there a workaround to allow sharing the generated AMIs?  I have verified that sharing works with AMIs that have been encrypted with CMKs in a similar manner as @amphied 

Thanks!

**Comment by minusdavid** [comment] 2019-04-26 05:01
I can also confirm that it is possible to share an AMI with an encrypted boot volume, but only within a single region. 

If you re-read https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html, you'll note that it says that "AMIs are a regional resource". 

That's why the documentation gets into copying encrypted snapshots to other regions, re-encrypting the snapshots, and creating AMIs (in the new region) using the encrypted snapshots. (This really threw me for a loop the first time I was reading/experimenting with it.)

So... it seems to me that Packer should let you use ami_users for sharing AMIs with encrypted boot volumes, but only when "ami_regions" exactly matches "region"? Otherwise, Packer will probably get errors from AWS when it tries to copy an encrypted AMI to other regions?

Just adding my 2 cents.

I'm just working within a single region, so I'm finding this validation error kind of annoying. I'm managing a small number of AMIs though, so it's not a big deal for me to update the AMI permissions via the AWS Console...

**Comment by minusdavid** [comment] 2019-04-26 05:17
Although looking at how Packer seems to copy the AMI to other regions... it looks like it actually copies the snapshots and then creates a new AMI? I'm not 100% sure what's going on there. 

Either way, at the "Modifying attributes on AMI" stage, I think you should be able to use ami_users even when using encrypted boot volumes... as you can do it manually?

**Comment by awiddersheim** [comment] 2019-06-07 19:42
https://aws.amazon.com/about-aws/whats-new/2019/05/share-encrypted-amis-across-accounts-to-launch-instances-in-a-single-step/

**Comment by awiddersheim** [comment] 2019-06-07 19:48
Seems to be fixed in https://github.com/hashicorp/packer/pull/7707 and related to https://github.com/hashicorp/packer/issues/7681.

**Comment by SwampDragons** [comment] 2019-07-11 21:56
Ah yes I think this was a duplicate of #7681 and can be closed now. Thanks.

**Closed by SwampDragons** 2019-07-11 21:56 UTC
Labels: builder/amazon, invalid
