### ISSUE TITLE
Stuck at azure-arm: IMAGE_STATE_SPECIALIZE_RESEAL_TO_OOBE

### ISSUE THREAD

**Issue by mickeyoc76** [hashicorp/packer#9818] opened 2020-08-25 07:29 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Running a packer build of Windows 10 using Azure Devops, the final step is to sysprep the image.
It's stuck on azure-arm: IMAGE_STATE_SPECIALIZE_RESEAL_TO_OOBE,  I've put in a step to reboot the machine before the sysprep but this makes no difference.

#### Reproduction Steps

Steps to reproduce this issue

I can reproduce this every time I kick off the build pipeline

### Packer version
1.5.2

### Simplified Packer Buildfile
      "communicator": "winrm",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "winrm_timeout": "5m",
      "winrm_username": "packer",
      "managed_image_storage_account_type": "Premium_LRS",
      "virtual_network_name": "",
      "virtual_network_subnet_name": "",
      "private_virtual_network_with_public_ip": "False",
      "virtual_network_resource_group_name": "",
  
      "azure_tags": {
          "dept": "Engineering",
          "task": "SchedTask"
      },
  
      "vm_size": "Standard_F4s_v2"
    }
    ],
    
    "provisioners": [
      {
          "type": "powershell",
          "timeout": "5m",
          "script": "./BuildFiles/Production/Scripts/Set-Env.ps1"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/TransmitForWinLogon_1.04",
        "destination": "C:\\"
      },
      {
        "type": "windows-shell",
        "inline": [
            "set install_mode=ins&&cmd /k C:/Control.cmd"
        ]
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/Certs",
        "destination": "C:\\"
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "script": "./BuildFiles/Production/Scripts/Install-Certs.ps1"
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "script": "./BuildFiles/Production/Scripts/Install-Chrome.ps1"
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "script": "./BuildFilesProduction/Scripts/Install-Chromium.ps1"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/FSLogix",
        "destination": "C:\\"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/WindowsDefenderATPOnboardingPackage",
        "destination": "C:\\"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/UserConfig",
        "destination": "C:\\"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/Windows_10_VDI_Optimize",
        "destination": "C:\\"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/BGInfo",
        "destination": "C:\\"
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "script": "./BuildFiles/Production/Scripts/System-Conf.ps1"
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "script": "./BuildFiles/Production/Scripts/Install-FSLogix.ps1"
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "inline": [
          "$currentfolder=$pwd;cd C:/FSLogix/;.\\RegisterScheduledTaskAtLogon.ps1;cd $currentfolder"
        ]
       },
       {
        "type": "powershell",
        "timeout": "5m",
        "inline": [
          "$currentfolder=$pwd;cd C:/BGInfo/;.\\RegisterScheduled.ps1;cd $currentfolder"
        ]
       },
       {
        "type": "powershell",
        "timeout": "5m",
        "inline": [
          "$currentfolder=$pwd;cd C://UserConfig/;.\\RegisterUserConf.ps1;cd $currentfolder"
        ]
       },
      {
        "type": "powershell",
        "timeout": "30m",
        "script": "./BuildFiles/Production/Windows_10_VDI_Optimize/Win10_1909_VDI_Optimize.ps1"
      },
      {
        "type": "file",
        "source": "./BuildFiles/Production/PWBE_Security_Hardening_1.2",
        "destination": "C:\\"
      },
      {
        "type": "windows-shell",
        "inline": [
          "powershell.exe -ExecutionPolicy Bypass -File C:/Wrapper.ps1 -Features Install-Users,Create-ScheduledTask-Users"
        ]
      },
      {
        "type": "windows-shell",
        "inline": [
            "powershell.exe -ExecutionPolicy Bypass -File C:/Wrapper.ps1 -Features Enable-TLS12,InternetExplorer-TLS,Disable-SSL2,DotNet-TLS"
        ]
      },
      {
        "type": "powershell",
        "timeout": "5m",
        "script": "./BuildFiles/Production/Scripts/Disable-NLA.ps1"
      },
      {
        "type": "powershell",
        "inline": [
            "Add-WindowsCapability -Online -Name `\"NetFX3~~~~`\" "
        ]
      },
      {
        "type": "windows-restart",
        "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
      },
      {
        "type": "powershell",
        "inline": [
          "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
          "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
          "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
        ]
       }
      ]
    }

### Operating system and Environment details

Windows 10 Enterprise

### Log Fragments and crash.log files

Continuous loop

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by sylviamoss** [comment] 2020-08-25 08:27
Thanks for reaching out! Could you please provide us the build logs when running with `PACKER_LOG=1`? This will help us understand better what's going on here.

**Comment by sylviamoss** [comment] 2020-08-25 08:32
This issue seems to be the same https://github.com/hashicorp/packer/issues/8428#issuecomment-592701831 
Have you tried the solution they found?

**Comment by mickeyoc76** [comment] 2020-08-25 08:35
Hi,

I added the restart provisioner before sysprep to no avail.  Need to figure out how to set the packer_log=1 in Azure devops pipeline yaml first. any idea on that?

Thanks.

**Comment by sylviamoss** [comment] 2020-08-25 08:43
I never used the Azure pipeline! PACKER_LOG is an environment variable, so I found this tutorial https://colinsalmcorner.com/azure-pipeline-variables/ it might help 🤔

**Comment by mickeyoc76** [comment] 2020-08-26 12:06
Looking like a problem with the image from market place. Opening a call with MS, can we keep the issue open until I hear back from MS please?

https://support.microsoft.com/en-gb/help/929828/an-error-message-occurs-when-you-run-sysprep-generalize-in-windows-vis

2020-08-26 12:01:39, Info       [0x0f00ac] SYSPRP WinMain:Processing 'cleanup' external provider request.
2020-08-26 12:01:39, Info       [0x0f006c] SYSPRP RunDlls:Running DLLs listed in registry for phase 3
2020-08-26 12:01:39, Info       [0x0f008a] SYSPRP RunRegistryDlls:Retrieved section name for this phase as Cleanup
2020-08-26 12:01:39, Info       [0x0f008b] SYSPRP RunRegistryDlls:Found entrypoint in registry at SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\SysPrepExternal\Cleanup\D2F06342-E788-11EA-948C-0022489A5DF4; will try to launch 'DscCore.dll,SysPrep_Cleanup'
2020-08-26 12:01:39, Info       [0x0f0080] SYSPRP LaunchDll:Found 'DscCore.dll,SysPrep_Cleanup'; executing it
2020-08-26 12:01:39, Error      [0x0f0082] SYSPRP LaunchDll:Failure occurred while executing 'DscCore.dll,SysPrep_Cleanup', returned error code 0x2
2020-08-26 12:01:39, Error      [0x0f0070] SYSPRP RunDlls:An error occurred while running registry sysprep DLLs, halting sysprep execution. dwRet = 0x2[gle=0x00000006]
2020-08-26 12:01:39, Error      [0x0f00ae] SYSPRP WinMain:Hit failure while processing sysprep cleanup external providers; hr = 0x80070002[gle=0x00000006]
2020-08-26 12:01:39, Info       [0x0f004c] SYSPRP WaitThread:Exiting spawned waiting thread
2020-08-26 12:01:39, Info       [0x0f0052] SYSPRP Shutting down SysPrep log

**Comment by mickeyoc76** [comment] 2020-08-28 12:50
Still waiting for the reason for this issue from Microsoft, but the fix is to add the reg keys below, I placed it in a provisioner just before sysprep.  Now the machine syspreps successfully.  Will update once I get an RCA from Microsoft.

 {
    "type": "powershell",
    "inline": [
      "New-Item -Path HKLM:\\Software\\Microsoft\\DesiredStateConfiguration",
      "New-ItemProperty -Path HKLM:\\Software\\Microsoft\\DesiredStateConfiguration -Name 'AgentId' -PropertyType STRING -Force"
    ]
   },

**Comment by jtracey93** [comment] 2020-09-04 16:52
I've had the same issue with a Windows 10 2004 Multi-Session image and the above Registry keys seemed to have fixed my issue also. Did you get a reply as to the root cause? @mickeyoc76

**Comment by SwampDragons** [comment] 2020-10-07 23:23
Closing this issue since it is on the Microsoft side of things and we never heard back.

**Closed by SwampDragons** 2020-10-07 23:23 UTC
Labels: bug, builder/azure, upstream-bug, waiting-reply
