### ISSUE TITLE
google-compute windows timeouts on base-image change

### ISSUE THREAD

**Issue by rhoughton-pivot** [hashicorp/packer#9109] opened 2020-04-23 17:25 UTC
Apache Geode uses Packer to customize a GCP windows-server-2016 image for CI testing. We re-build the image whenever Google updates their base image. As of the 21 April change, Packer cannot connect to the started instance, and CI times out after 30 minutes.

[Packer yml](https://github.com/apache/geode/blob/develop/ci/images/google-windows-geode-builder/windows-packer.json)
[Build log](https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-images/jobs/build-google-windows-geode-builder/builds/58#L5e38787b:335)

Other than rolling back to a previous base image from GCP, is there any guidance or fix for establishing this connection?

**Comment by SwampDragons** [comment] 2020-04-23 18:34
Hi, thanks for reaching out. 

My guess is that some default relating to setting up WinRM on the instance has changed and that your windows-startup-script-cmd is no longer sufficient.

In general in this situation I suggest people connect to the instance via a console and tinker around inside the instance until Packer can connect. 

It looks like since we have SSL set we are trying to connect via HTTPS which makes sense; I wonder whether something has changed on the system so the quickconfig is not setting up an HTTPS listener on port 5986; based on the i/o timeout I don't think anything's listening there. I'd suggest getting on the windows instance and seeing whether there's anything listening on that port. Docs suggest that if you want to connect with HTTPS you need to pass the -transport:https option to winrm quickconfig: `winrm quickconfig -transport:https`. Maybe try this and see if that unsticks things. There may also be a need to generate your own self-signed cert before running the config. 

Anyway, those are my first thoughts. Since this probably has implications for our documentation I'll leave this issue opened until someone can figure it out but I probably won't have time to try to reproduce this week.

**Comment by rhoughton-pivot** [comment] 2020-04-23 19:46
I tried adding `-transport:https` and no change in behavior. I can inspect the instance tomorrow.

**Comment by nywilken** [comment] 2020-05-05 17:52
Hi @rhoughton-pivot just wanted to circle back here. Are you still running into issues?

**Comment by rhoughton-pivot** [comment] 2020-05-05 18:41
We are successful at this time, with the windows-server-2016-dc-v20200424 base image.

**Comment by SwampDragons** [comment] 2020-05-05 22:28
Glad to hear it! I'm going to close this issue, then.

**Closed by SwampDragons** 2020-05-05 22:28 UTC
Labels: builder/google, communicator/winrm, docs, question, windows-guest
