### ISSUE TITLE
The special symbol for ssh_password is not supported 

### ISSUE THREAD

**Issue by meteorlad** [hashicorp/packer#5302] opened 2017-09-05 05:40 UTC
As follows
```
      "ssh_username": "root",
      "ssh_password": "qsx@yui?S",
```
Is this format unable to resolve?

**Comment by rickard-von-essen** [comment] 2017-09-05 06:20
That should work. (Verify that you can manually login with those credentials, run with `packer build -on-error=ask ...` to get time to test it before it's shutdown)

If you verified that please supply information to reproduce this.

-----

Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by meteorlad** [comment] 2017-09-05 06:31
I used Jenkins to build the following versions and exception information：

- packer 1.0.0
- Linux jenkins-docker 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

error log：

```
[1;32m==> qemu: Waiting 10s for boot...[0m
[1;32m==> qemu: Connecting to VM via VNC[0m
[1;32m==> qemu: Typing the boot command over VNC...[0m
[1;32m==> qemu: Waiting for SSH to become available...[0m
[1;31m==> qemu: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain[0m
[1;32m==> qemu: Deleting output directory...[0m
[1;31mBuild 'qemu' errored: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain[0m

==> Some builds didn't complete successfully and had errors:
--> qemu: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

==> Builds finished but no artifacts were created.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

```

If I use a combination of letter Numbers, there is no problem, for example, "Lo13cqpW"

**Comment by rickard-von-essen** [comment] 2018-10-26 07:48
Closing this since this is very old and don't have a repro case.

**Closed by rickard-von-essen** 2018-10-26 07:48 UTC
Labels: communicator/ssh, need-more-info, waiting-reply
