### ISSUE TITLE
DigitalOcean Builder Crash

### ISSUE THREAD

**Issue by rickw** [hashicorp/packer#6748] opened 2018-09-20 20:06 UTC
Packer v1.3.1
macOS 10.13.6

```go
 packer: panic: interface conversion: interface {} is digitalocean.Config, not *digitalocean.Config
...
packer:     /private/tmp/packer-20180915-14392-156ozr5/src/github.com/hashicorp/packer/builder/digitalocean/step_create_ssh_key.go:31 +0xac7
```
The occurs with any build on digitalocean. I have a gist of the crash.log that was produced but those seem to be the relevant parts.

**Comment by SwampDragons** [comment] 2018-09-20 20:09
Thanks for opening; this is a dupe of #6715

**Closed by SwampDragons** 2018-09-20 20:09 UTC
Labels: builder/digitalocean, duplicate
