### ISSUE TITLE
"strconv.ParseUint: parsing "0 0": invalid syntax" when Hyper-V VM with same name is already running

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#5149] opened 2017-07-20 13:16 UTC
Packer v1.0.2 on Windows Server 2016.

The error in the title occurs if a VM with the same name is already running. I expect Packer to overwrite the VM and successfully continue.

Retrying the operation succeeds - the build that errors out does get rid of the conflicting VM.

Template:

```
{
  "builders": [
    {
      "name": "Windows2016-HyperV",
      "type": "hyperv-iso",
      "iso_url": "{{ user `windows2016_iso_url` }}",
      "iso_checksum_type": "none",
      "ram_size": 1536,
      "cpu": 4,
      "vm_name": "Packer-Asdp-Host-Windows2016",
      "switch_name": "{{ user `network_name` }}",
      "generation": 2,
      "enable_secure_boot": true,
      "boot_wait": "0s",
      "boot_command": [
        "a<enter><wait>a<enter><wait>a<enter><wait>a<enter>"
      ],
      "communicator": "winrm",
      "winrm_username": "axinom",
      "winrm_password": "xxx"
    }
  ],
  "variables": {
    "windows2016_iso_url": "c:/Tmp/eval_14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO",
    "network_name": "Internal"
  }
}
```

Command: `Packer.exe build --force xxx.json`

Log: https://gist.github.com/sandersaares/b74576bfdd796b63da241e380d77c5bb

**Comment by evancox10** [comment] 2018-03-25 05:14
I believe that this is a duplicate of https://github.com/hashicorp/packer/issues/4573 . I disagree that default behavior should be to delete the running VM. It may actually be important! At least give the user a choice.

As I mentioned previously, it would be possible to track the VM's via their UUIDs, which Windows already assigns to them. (Windows has no problem with two VM's of the same name running at the same time.) This would be a significant rewrite of the Hyper-V Power Shell driver code though.

**Closed** 2021-04-21 14:20 UTC
Labels: bug, builder/hyperv, crash, remote-plugin/hyperv
