### ISSUE TITLE
Run a data source only when the connected builder is invoked

### ISSUE THREAD

**Issue by LKHN** [hashicorp/packer#12434] opened 2023-05-22 21:00 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I am using the `amazon-ami` data source with `amazon-ebssurrogate` builder in a separate HCL2 file.

When I use different builders like `qemu` and `virtualbox-iso`, the `amazon-ami` data source is being executed and gives the authentication error because I didn't configure any AWS authentication.

#### Reproduction Steps

Clone the repo:

```sh
git clone https://github.com/AlmaLinux/cloud-images.git
```

Go the change where the amazon-ami data source used:

```sh
git checkout 57de2de
```

Install or Upgrade plugins

```sh
packer init -upgrade .
```

Use README to do any build except AWS one and don't have any AWS credentials configured.

for example build a Vagrant box for VirtualBox provider:

```sh
packer build -only=virtualbox-iso.almalinux-9 .
```

### Packer version

From `packer version`

```sh
Packer v1.8.7
```

### Simplified Packer Template

https://github.com/AlmaLinux/cloud-images.git

### Operating system and Environment details

Any OS and Architecture

### Log Fragments and crash.log files

```sh
Error: Datasource.Execute failed: no valid credential sources for  found.

Please see
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors


  on almalinux-8-aws-aarch64.pkr.hcl line 5:
  (source code not available)
  ```

**Comment by nywilken** [comment] 2023-05-23 15:23
Duplicate of https://github.com/hashicorp/packer/issues/11037

**Closed by nywilken** 2023-05-23 15:23 UTC
Labels: bug
