### ISSUE TITLE
Packer v1.0.3 problem with ansible as provisioner

### ISSUE THREAD

**Issue by ashevch** [hashicorp/packer#5183] opened 2017-07-27 12:35 UTC
Packer v1.0.3 don't allow ansible to connect to remote machine with the key, and ansible hangs on gathering information. Older version v1.0.0 works fine.

Version:
   Packer v1.0.3
Platform:   
      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/ashevch/e3d9bccd9ea0da2ed0d620fb6075e80d

**Comment by rickard-von-essen** [comment] 2017-07-27 13:23
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Closed** 2017-07-27 13:24 UTC
Labels: bug, duplicate, provisioner/ansible-remote
