### ISSUE TITLE
[azure-arm] OS disk preserves after packer build in versions 1.6.2 and above

### ISSUE THREAD

**Issue by miketimofeev** [hashicorp/packer#10416] opened 2020-12-22 11:49 UTC
#### Overview of the Issue
Since this PR https://github.com/hashicorp/packer/pull/9559 the OS disk created during packer build is not deleted at the end of the build yet according to the documentation it should be deleted https://www.packer.io/docs/builders/azure/arm
![image](https://user-images.githubusercontent.com/48208649/102884728-31a0b980-4463-11eb-81d6-5d03c33b974e.png)

That unexpected behavior causes additional storage account maintenance costs, which we were not aware of. As a result, we have 60Tb (!) used storage for such temporary OS disks vhd.

#### Reproduction Steps
**Build with packer 1.5.5:**
```
2020-12-22T11:31:52.6025731Z   ==> azure-arm: Deleting resource group ...
2020-12-22T11:31:52.6029348Z  ==> azure-arm:  -> ResourceGroupName : '15465_imagname.ubuntu20.0'
2020-12-22T11:31:52.6046953Z  ==> azure-arm: 
2020-12-22T11:31:52.6048315Z  ==> azure-arm: The resource group was created by Packer, deleting ...
2020-12-22T11:33:37.8882125Z  ==> azure-arm: Deleting the temporary OS disk ...
2020-12-22T11:33:37.8887434Z  ==> azure-arm:  -> OS Disk : 'https://storagname.blob.core.windows.net/images/pkrosecc9u3h1uh.vhd'
2020-12-22T11:33:38.0285142Z  ==> azure-arm: Deleting the temporary Additional disk ...
2020-12-22T11:33:38.0288142Z  ==> azure-arm: Removing the created Deployment object: 'pkrdpecc9u3h1uh'
```

**Build with packer 1.6.2 and above:**
```
2020-12-17T06:23:11.9415718Z  ==> azure-arm: Deleting the temporary Additional disk ...
2020-12-17T06:23:11.9432558Z ==> azure-arm: Removing the created Deployment object: 'pkrdpeakhr4d0gh'
2020-12-17T06:23:27.2082893Z ==> azure-arm: 
2020-12-17T06:23:27.2099119Z   ==> azure-arm: Cleanup requested, deleting resource group ...
2020-12-17T06:25:12.4393886Z  ==> azure-arm: Resource group has been deleted.
```

### Packer version

1.6.2 and above

### Simplified Packer Buildfile

https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json

### Operating system and Environment details

Any

### Log Fragments and crash.log files

Provided in the Reproduction Steps

**Comment by miketimofeev** [comment] 2020-12-22 11:49
cc @nywilken @SwampDragons

**Comment by maxim-lobanov** [comment] 2020-12-24 07:52
Looks like this clean up logic was removed intentionally in https://github.com/hashicorp/packer/pull/9559 😢

**Comment by nywilken** [comment] 2020-12-24 16:08
Hi there we are aware of this issue and will be working on the fix in time for the next release. The persistence of the os disk was not intentional. 

Apologies for any inconvenience this has caused. 

Related to #10268

**Comment by nywilken** [comment] 2021-03-05 22:15
Hi :wave: there's an open PR #10713 with a potential fix for this issue. Would you mind pulling down one of the test binaries and confirming that the patch fixes the reported issue?

The test binaries can be downloaded from https://app.circleci.com/pipelines/github/hashicorp/packer/9492/workflows/fb3a2460-88f5-4788-affb-089a5a3ddd87/jobs/113627/artifacts

Cheers!

**Comment by miketimofeev** [comment] 2021-03-08 21:09
@nywilken thanks for the update! We'll give it a try and come back with the results

**Comment by alexeldeib** [comment] 2021-03-10 14:24
Interesting :/

I’d only tested the Linux ones so far, guess something must be off in the windows flow. I’ll try that today and see what’s up.

**Comment by alexeldeib** [comment] 2021-03-11 01:05
@miketimofeev on an initial attempt to repro on a successful windows vhd, cleanup seems to work for me. did you verify the RG contents, besides the difference in log output? we did change the logic slightly from what was done before #9559, so the logs won't match.

It looks like your configuration uses temporary resource groups -- shouldn't the whole group be deleted? The disk deletion will be skipped in that case anyway per the logic in my PR, so don't expect a separate step to be executed. I'm trying to repro using your config but the temporary RG seems to be deleted fine.

**Comment by miketimofeev** [comment] 2021-03-11 09:27
@alexeldeib you're right, we use a temporary resource group during the image generation (all our configurations can be found here https://github.com/actions/virtual-environments/tree/main/images), and this group deletes successfully, with no issues at all. But since we use an unmanaged disk — it stores not in the resource group, but in the specified storage account and isn't deleted after the build

**Comment by alexeldeib** [comment] 2021-03-12 01:42
Thanks for clarifying, apologies I'm a little rusty on unmanaged disks. I understand and got a repro, but it took a little time to figure out an appropriate place to fix. I think the latest version of #10713 should work, albeit with some changes cleanup. Can continue discussion over there, I think the artifacts from the latest build should bring back the expected behavior: https://app.circleci.com/pipelines/github/hashicorp/packer/9590/workflows/20d6a967-0256-4960-9b32-c5d2d6d6b46b/jobs/115009/artifacts

**Comment by miketimofeev** [comment] 2021-03-12 14:19
@alexeldeib Thank you! I'll try the new binaries and get back with the results.

**Comment by miketimofeev** [comment] 2021-03-12 15:37
@alexeldeib tested windows binary on both cases — successful and failed, and everything worked like a charm! The disk was deleted along with the RG 🥳

**Closed** 2021-03-18 16:09 UTC
Labels: bug, builder/azure, regression, track-internal
