### ISSUE TITLE
Newest version of Packer 1.0.3 hangs on local Ansible step

### ISSUE THREAD

**Issue by ldelossa** [hashicorp/packer#5190] opened 2017-07-28 17:00 UTC
Describe the problem and include the following information:

My team has been using packer v0.12.1. Our packer setup uses Ansible for all provisioning steps. We have a build step which calls Ansible and Ansible performs some actions on the ```localhost```. When we switched to v1.0.3, these local host calls broke. I cannot see this being a problem with Ansible due to the fact that the ansible version never changes. We swap out v1.0.3 to v.0.12.1 and it works fine. Ansible version between both situations is 2.3.1.0

Here is the packer file we are currently using. 

```
{
  "variables": {
    "fresnel_branch": "master",
    "fresneldeploy_branch": "master",
    "prism_branch": "master"
  },
  "description" : "Fresnel Image {{timestamp}}",
  "builders" : [{
    "type": "googlecompute",
    "tags": ["branch-fresnel-{{user `fresnel_branch`}}", "branch-fresneldeploy-{{user `fresneldeploy_branch`}}",
             "branch-prism-{{user `prism_branch`}}"],
    "project_id": "vimeo-logs",
    "image_name": "fresnel-{{user `fresnel_branch`}}-{{timestamp}}",
    "source_image": "centos-7-v20170227",
    "zone": "us-east1-b",
    "disk_type": "pd-ssd",
    "image_description": "fresnel",
    "image_family": "fresnel",
    "network": "vimeo-logs",
    "subnetwork": "us-east1-b",
    "communicator" : "ssh",
    "ssh_username": "terraform"
    }],
    "provisioners": [
      {
        "type": "ansible",
        "playbook_file": "../plays/build_fresnel_binaries_local.yml",
        "extra_arguments": [ "--extra-vars", "variable_host=default",
                             "--extra-vars", "fresnel_branch={{user `fresnel_branch`}}",
                             "--extra-vars", "fresneldeploy_branch={{user `fresneldeploy_branch`}}",
                             "--extra-vars", "prism_branch={{user `prism_branch`}}" ]
      },
      {
        "type": "ansible",
        "playbook_file": "../plays/install_consul_client.yml",
        "extra_arguments": ["--extra-vars", "variable_host=default", "--extra-vars", "variable_checks=fresnel"]
      },
      {
        "type": "ansible",
        "playbook_file": "../plays/install_netdata.yml",
        "extra_arguments": [ "--extra-vars", "variable_host=default" ]
      },
      {
        "type": "ansible",
        "playbook_file": "../plays/install_fresnel.yml",
        "extra_arguments": [ "--extra-vars", "variable_host=default" ]
      },
      {
        "type": "ansible",
        "playbook_file": "../plays/install_prism.yml",
        "extra_arguments": [ "--extra-vars", "variable_host=default" ]
      },
      {
        "type": "shell-local",
        "command": "rm -rf ../tmp"
      }
    ]
}
```

Here is the run of packer 1.0.3: 

```
❯ packer1.0.3 build -debug fresnel.json
Debug mode enabled. Builds will not be parallelized.
googlecompute output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Pausing after run of step 'StepCheckExistingImage'. Press enter to continue.
==> googlecompute: Creating temporary SSH key for instance...
    googlecompute: Saving key for debug purposes: gce_googlecompute.pem
==> googlecompute: Pausing after run of step 'StepCreateSSHKey'. Press enter to continue.
==> googlecompute: Using image: centos-7-v20170227
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-east1-b
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Loading network: vimeo-logs
    googlecompute: Loading subnetwork: us-east1-b for region: us-east1
    googlecompute: Requesting instance creation...
    googlecompute: Waiting for creation operation to complete...
    googlecompute: Instance has been created!
    googlecompute: Instance: packer-597b6b5d-1eb4-6996-b66f-d956d043d178 started in us-east1-b
==> googlecompute: Pausing after run of step 'StepCreateInstance'. Press enter to continue.
==> googlecompute: Pausing after run of step 'StepCreateWindowsPassword'. Press enter to continue.
==> googlecompute: Waiting for the instance to become running...
    googlecompute: Public IP: 35.196.25.125
    googlecompute: IP: 35.196.25.125
==> googlecompute: Pausing after run of step 'StepInstanceInfo'. Press enter to continue.
==> googlecompute: Waiting for SSH to become available...

==> googlecompute: Connected to SSH!
==> googlecompute: Pausing after run of step 'StepConnect'. Press enter to continue. ==> googlecompute: Provisioning with Ansible...
==> googlecompute: Executing Ansible: ansible-playbook --extra-vars packer_build_name=googlecompute packer_builder_type=googlecompute -i /var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/packer-provisioner-ansible404323502 /Users/louis/git/vimeo/MooseESCluster/plays/build_fresnel_binaries_local.yml --private-key /var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key872518603 --extra-vars variable_host=default -vvv --extra-vars fresnel_branch=master --extra-vars fresneldeploy_branch=master --extra-vars prism_branch=master
    googlecompute: Using /Users/louis/.ansible.cfg as config file
    googlecompute:
    googlecompute: PLAYBOOK: build_fresnel_binaries_local.yml *************************************
    googlecompute: 1 plays in /Users/louis/git/vimeo/MooseESCluster/plays/build_fresnel_binaries_local.yml
    googlecompute:
    googlecompute: PLAY [default] *****************************************************************
    googlecompute:
    googlecompute: TASK [Gathering Facts] *********************************************************
    googlecompute: Using module file /Library/Python/2.7/site-packages/ansible/modules/system/setup.py
    googlecompute: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: louis
    googlecompute: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=64751 -o 'IdentityFile="/private/var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key872518603"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=louis -o ConnectTimeout=10 -o ControlPath=/Users/louis/.ansible/cp/9f4bc8448a 127.0.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
```
It will just hang here I must send it a ctrl-c to kill it. 

And the run of packer v0.12.1 ( omitting any information after showing that it moves past where 1.0.3 hangs)

```
googlecompute output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Pausing after run of step 'StepCheckExistingImage'. Press enter to continue.
==> googlecompute: Creating temporary SSH key for instance...
    googlecompute: Saving key for debug purposes: gce_googlecompute.pem
==> googlecompute: Pausing after run of step 'StepCreateSSHKey'. Press enter to continue.
==> googlecompute: Using image: centos-7-v20170227
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-east1-b
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Loading network: vimeo-logs
    googlecompute: Loading subnetwork: us-east1-b for region: us-east1
    googlecompute: Requesting instance creation...
    googlecompute: Waiting for creation operation to complete...
    googlecompute: Instance has been created!
    googlecompute: Instance: packer-597b6ccd-5325-5b8e-c08a-b8704f5118c5 started in us-east1-b
==> googlecompute: Pausing after run of step 'StepCreateInstance'. Press enter to continue.
==> googlecompute: Pausing after run of step 'StepCreateWindowsPassword'. Press enter to continue.
==> googlecompute: Waiting for the instance to become running...
    googlecompute: Public IP: 104.196.111.219
    googlecompute: IP: 104.196.111.219
==> googlecompute: Pausing after run of step 'StepInstanceInfo'. Press enter to continue.
==> googlecompute: Waiting for SSH to become available...
==> googlecompute: Connected to SSH!
==> googlecompute: Pausing after run of step 'StepConnect'. Press enter to continue.
==> googlecompute: Provisioning with Ansible...
    googlecompute: Using /Users/louis/.ansible.cfg as config file
    googlecompute:
    googlecompute: PLAYBOOK: build_fresnel_binaries_local.yml *************************************
    googlecompute: 1 plays in /Users/louis/git/vimeo/MooseESCluster/plays/build_fresnel_binaries_local.yml
    googlecompute:
    googlecompute: PLAY [default] *****************************************************************
    googlecompute:
    googlecompute: TASK [Gathering Facts] *********************************************************
    googlecompute: Using module file /Library/Python/2.7/site-packages/ansible/modules/system/setup.py
    googlecompute: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: louis
    googlecompute: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=64853 -o 'IdentityFile="/private/var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key127768014"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=louis -o ConnectTimeout=10 -o ControlPath=/Users/louis/.ansible/cp/4029609232 127.0.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
    googlecompute: <127.0.0.1> (0, '/home/terraform\n', "Warning: Permanently added '[127.0.0.1]:64853' (RSA) to the list of known hosts.\r\n")
    googlecompute: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: louis
    googlecompute: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=64853 -o 'IdentityFile="/private/var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key127768014"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=louis -o ConnectTimeout=10 -o ControlPath=/Users/louis/.ansible/cp/4029609232 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637 `" && echo ansible-tmp-1501261044.45-191225200128637="` echo /home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637 `" ) && sleep 0'"'"''
    googlecompute: <127.0.0.1> (0, 'ansible-tmp-1501261044.45-191225200128637=/home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637\n', '')
    googlecompute: <127.0.0.1> PUT /var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/tmpKxaKSB TO /home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637/setup.py
    googlecompute: <127.0.0.1> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=64853 -o 'IdentityFile="/private/var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key127768014"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=louis -o ConnectTimeout=10 -o ControlPath=/Users/louis/.ansible/cp/4029609232 /var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/tmpKxaKSB '[127.0.0.1]:/home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637/setup.py'
    googlecompute: <127.0.0.1> (0, '', '')
    googlecompute: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: louis
    googlecompute: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=64853 -o 'IdentityFile="/private/var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key127768014"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=louis -o ConnectTimeout=10 -o ControlPath=/Users/louis/.ansible/cp/4029609232 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637/ /home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637/setup.py && sleep 0'"'"''
    googlecompute: <127.0.0.1> (0, '', '')
    googlecompute: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: louis
    googlecompute: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=64853 -o 'IdentityFile="/private/var/folders/rn/dgz6dd8d0sg57vc8_81wgrjw0000gn/T/ansible-key127768014"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=louis -o ConnectTimeout=10 -o ControlPath=/Users/louis/.ansible/cp/4029609232 -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-nwwusdderpxrgmbsnvmwdmfrnzvxrvij; /usr/bin/python /home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637/setup.py; rm -rf "/home/terraform/.ansible/tmp/ansible-tmp-1501261044.45-191225200128637/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
    googlecompute: <127.0.0.1> (0, '\n{"invocation": {"module_args": {"filter": "*", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d",
```

- Works on 0.12.1, breaks on latest 1.0.3
- This is consistent both on macOS Sierra and Centos7

**Comment by mwhooker** [comment] 2017-07-28 17:43
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.

**Closed by mwhooker** 2017-07-28 17:43 UTC
