### ISSUE TITLE
Unusable vagrant box stuck waiting for SSH

### ISSUE THREAD

**Issue by pcapdevila** [hashicorp/packer#7651] opened 2019-05-17 00:01 UTC
After building a box with vagrant (libvirt), when trying to bring it up, the resulting VM gets stuck at:

> Waiting for SSH to become available...

If you enter the VM via virsh console you can see that there is a problem with the SSHd configuration in the auth.log:

> May 16 23:41:17 localhost sshd[819]: error: Could not load host key: /etc/ssh/ssh_host_rsa_key
> May 16 23:41:17 localhost sshd[819]: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
> May 16 23:41:17 localhost sshd[819]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
> May 16 23:41:17 localhost sshd[819]: fatal: No supported key exchange algorithms [preauth]

And the missing SSH host keys:

> frr@stretch:~$ sudo ls -la /etc/ssh
> total 560
> drwxr-xr-x  2 root root   4096 May 16 23:34 .
> drwxr-xr-x 70 root root   4096 May 16 23:39 ..
> -rw-r--r--  1 root root 553122 Mar  1 16:19 moduli
> -rw-r--r--  1 root root   1723 Mar  1 16:19 ssh_config
> -rw-r--r--  1 root root   3334 May  1 08:45 sshd_config

- Packer version from `packer version`
Packer v1.4.1-dev (cc78ac2da)

- Host platform
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/pcapdevila/bc3e0911c8ad159d1ecc8422ebb0a630

- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/pcapdevila/56b4c1660444fd3716ba74bc6c98e927

**Comment by SwampDragons** [comment] 2019-05-17 21:22
Looking at your template, I'm not seeing where you're adding any authentication methods. At a minimum, you need to supply an [ssh_username](https://www.packer.io/docs/templates/communicator.html#ssh_username)

if you want to use a key instead of a password, you need to provide an `ssh_private_key_file`

**Comment by marcosdiez** [comment] 2019-06-17 21:48
Hi ! I had a similar problem. Maybe my workaround can help you: https://github.com/hashicorp/packer/issues/7758

**Comment by SwampDragons** [comment] 2019-06-17 22:50
Since I never got a response on this one, I'll close it as a dupe of #7651 and we can continue the conversation there.

**Closed by SwampDragons** 2019-06-17 22:50 UTC
Labels: builder/vagrant, question
