### ISSUE TITLE
support for ap-east-1

### ISSUE THREAD

**Issue by Deshke** [hashicorp/packer#7590] opened 2019-04-30 15:41 UTC
aws launched ap-east-1 Hong Kong
 
* https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-hong-kong-region/ 

how does one add new region support to packer ?

**Comment by azr** [comment] 2019-04-30 15:59
Hi @Deshke, I think it should just work if you are using a not too old version of Packer, have you tried ?

**Comment by SwampDragons** [comment] 2019-04-30 21:17
If you're on v. 1.3.2 or later, this should "just work", but you need to explicitly enable the region first, as mentioned in that blog post.

Also note that ap-east-1 does not support t2 instances, so our example configs will not work unless you change the instance type.

**Comment by Deshke** [comment] 2019-05-07 14:54
with packer 1.4 one can not copy the image to ap-east-1 if it where build in another region

> Build 'aws-builds' errored: error validating regions: Invalid region(s): [ap-east-1], available regions: [eu-north-1 ap-south-1 eu-west-3 eu-west-2 eu-west-1 ap-northeast-2 ap-northeast-1 sa-east-1 ca-central-1 ap-southeast-1 ap-southeast-2 eu-central-1 us-east-1 us-east-2 us-west-1 us-west-2]


so one would have to build specificity for ap-east-1 or any other new aws region. so `ami_regions` will only work for the "legacy" aws regions

**Comment by azr** [comment] 2019-05-07 15:14
Hello @Deshke, Internally packer uses describe-region to know available regions to copy to: ( [doc here](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html) ). If your region is not in this list, then it cannot be in packer's. 🙂

**Comment by azr** [comment] 2019-05-07 15:15
Code is here: https://github.com/hashicorp/packer/blob/a6bb06c04e8c7fda77d0a43b0482c3e3207cf017/builder/amazon/common/regions.go#L11

**Comment by SwampDragons** [comment] 2019-05-07 16:28
You must manually enable this region before you can build in it: https://aws.amazon.com/blogs/security/setting-permissions-to-enable-accounts-for-upcoming-aws-regions/

**Comment by Deshke** [comment] 2019-05-07 16:55
to quote the AWS Business support


> Currently the API call will only return the Hong Kong region when you specify the "ap-south-1" endpoint and yes this is the intended behaviour of the API call. However as this is a new region this may be subject to change but please rest assured it will not be added to the normal describe region (i.e. if you query another endpoint) without warning. 
> 
> The service team have also recommended to use the describe regions API call with the "--region ap-east-1" flag set so that you are querying the endpoint directly as a solution if you require the Hong Kong region to be returned. 
> 
> For example if you require all regions to be returned then you can use the following command:
>  $ aws ec2 describe-regions --query "Regions[].{Name:RegionName}" --output text --region ap-east-1 
> | eu-north-1 
> | ap-south-1 
> | eu-west-3 
> | eu-west-2 
> | eu-west-1 
> | ap-northeast-2 
> | ap-northeast-1 
> | sa-east-1 
> | ca-central-1 
> | ap-east-1 =====>> Hong Kong here :-) 
> | ap-southeast-1 
> | ap-southeast-2 
> | eu-central-1 
> | us-east-1 
> | us-east-2 
> | us-west-1 
> | us-west-2

**Comment by SwampDragons** [comment] 2019-05-07 17:06
We do the query with the region included in the session, so it should work. I tested this the other day when you opened the ticket, and was able to run a packer build.

If all else fails, set "skip_region_validation": true in your config.

**Comment by Deshke** [comment] 2019-05-07 17:10
strange because the account has access to ap-east-1 but packer build with ami_regions fails with the unknown region ap-east-1. 

will try ` "skip_region_validation": true`

**Comment by Deshke** [comment] 2019-05-07 17:19
@azr https://github.com/hashicorp/packer/blob/master/builder/amazon/common/regions.go#L11 will only return ap-east-1 as a region if queried from ap-east-1 

```

~ # aws --region eu-west-1 ec2 describe-regions  --filter "Name=region-name,Values=*" --query 'Regions[*]' | jq .[].RegionName -r
eu-north-1
ap-south-1
eu-west-3
eu-west-2
eu-west-1
ap-northeast-2
ap-northeast-1
sa-east-1
ca-central-1
ap-southeast-1
ap-southeast-2
eu-central-1
us-east-1
us-east-2
us-west-1
us-west-2
~ # aws --region ap-east-1 ec2 describe-regions  --filter "Name=region-name,Values=*" --query 'Regions[*]' | jq .[].RegionName -r
eu-north-1
ap-south-1
eu-west-3
eu-west-2
eu-west-1
ap-northeast-2
ap-northeast-1
sa-east-1
ca-central-1
ap-east-1  <---- 
ap-southeast-1
ap-southeast-2
eu-central-1
us-east-1
us-east-2
us-west-1
us-west-2
```

**Comment by jsanders67** [comment] 2019-05-21 00:13
@SwampDragons Can you please provide links to your template.json file and command used to build the image(s) that worked for "ap-east-1"? My guess is that the region you specified was "ap-east-1", but one of the asks here is to enable building an image in a different region (say "us-west-2") and copying that image to "ap-east-1". I am also getting region validation errors when trying to do exactly this.

From my own experimentation, it seem that what @Deshke is saying is true: You must specify the region of "ap-east-1" in the "DescribeRegions" if you wish to have these new regions returned. Packer is doing this implicitly, but using the region supplied in the "region" variable when executing the build. This is why Im guessing you made the "region" parameter "ap-east-1" and it worked for you.

**Comment by Deshke** [comment] 2019-05-21 07:15
@jsanders67 i've talked to the AWS support in a lengthy ticket about this, there is a internal beta that they can add your account to so the `describe-regions` cmd returns ap-east-1 even from other aws regions

**Comment by jsanders67** [comment] 2019-05-21 16:56
@Deshke Thanks for replying. Do you know if EC2 is adding this behavior for just "ap-east-1" or for all upcoming new regions? If it's all new regions, then maybe Packer can just wait for this beta behavior to be production behavior for everyone. If not (or maybe even still if so), Packer may need to perform region validation in a different way. AWS is likely saying the current behavior is intended so they may never make the beta behavior the default behavior. 

@SwampDragons I think that regardless this issue should remain open as it's now confirmed by AWS that the way Packer is doing its region validation wont work when trying to build an image in non "ap-east-1" regions and then subsequently trying and copy to "ap-east-1" region.

**Comment by SwampDragons** [comment] 2019-05-21 17:10
I see. I didn't test the copy mechanism. I'll try to investigate when

**Comment by Deshke** [comment] 2019-05-21 17:13
> AWS is likely saying the current behavior is intended so they may never make the beta behavior the default behavior.

no idea, if they change the behavior at some point. But running `describe-regions` and only getting the region back where you executed the cmd seems somewhat half-baked

**Comment by SwampDragons** [comment] 2019-07-11 21:55
I just revisited this to check, and I'm able to copy an image from us-west-2 to ap-east-1 with no issues; I think Amazon must have fixed this on their end. Closing for now; if people are still experiencing this bug, let me know in a comment, with a simple config that reproduces the error, and I will reopen :)

**Closed by SwampDragons** 2019-07-11 21:55 UTC
Labels: builder/amazon
