### ISSUE TITLE
packer script upload connection timeout bug

### ISSUE THREAD

**Issue by pivotalgeorge** [hashicorp/packer#7901] opened 2019-07-23 19:41 UTC
Hello!

We use packer to provision Windows VMs across several IaaSes, and have been seeing repeat issues around uploading an inline powershell script after a restart in our provisioners.

- Packer version: `1.4.1`
- Host platform: Windows 1803
- Log output at: https://gist.github.com/pivotalgeorge/6908b6b9c1b58d05de421cc0b171c88e

We first started seeing this in a previous version of Packer. Issues #6173 and #7768 seemed related, so we upgraded to 1.4.1.

We don't think we have our `PACKER_LOG` set to 1, however, we haven't reproduced this issue in vitro. Please see Gist for our most-recent log after the last successful provisioner step that succeeds.

**Comment by SwampDragons** [comment] 2019-07-23 20:44
Hi, thanks for reaching out!

Those two issues have a different error than you: `Couldn't determine whether destination was a folder or file`

Yours is `read tcp OTHERHOST:48552->HOST:5985: read: connection timed out`

Without seeing the packer template you're using, I can't be sure but my guesses are that either:

- Your WinRM listener on the guest isn't coming back up properly after a restart, or 
- Your machine is actually restarting multiple times in a row as a result of some kind of update, and it isn't actually fully booted when the provisioner tries to connect. You could try using the [check_registry](https://www.packer.io/docs/provisioners/windows-restart.html#check_registry) option to make sure that the queued reboots are all completed.

You could try adding a breakpoint provisioner to the spot where this is failing so that you can check the WinRM connection and reboot status from outside of Packer, to determine where the issue is.

I think it's highly likely that this is a configuration issue and not a bug, so I'm going to close this issue and suggest you reach out to our [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or the [community forum](https://discuss.hashicorp.com/c/packer).

If you believe this is a bug or regression, we can open a new issue but I'll need the actual debug logs and a minimal template that can reproduce the issue in order to investigate it for you.

Thanks!

**Closed by SwampDragons** 2019-07-23 20:44 UTC

**Comment by jfeeny** [comment] 2019-07-30 18:18
Hey @SwampDragons,

Thanks for the leads here.

We've gone ahead and added the `check_registry` option to the restarts, and we're now running into a new issue where it hangs on the restart.

When we set `PACKER_LOG=1`, we see the following:

```
2019/07/26 12:26:04 packer: 2019/07/26 12:26:04 [INFO] starting remote command: powershell.exe -EncodedCommand VABlAHMAdAAtAFAAYQB0AGgAIAAiAEgASwBMAE0AOgBTAE8ARgBUAFcAQQBSAEUAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAXABDAHUAcgByAGUAbgB0AFYAZQByAHMAaQBvAG4AXABDAG8AbQBwAG8AbgBlAG4AdAAgAEIAYQBzAGUAZAAgAFMAZQByAHYAaQBjAGkAbgBnAFwAUgBlAGIAbwBvAHQAUABlAG4AZABpAG4AZwAiAA==
2019/07/26 12:26:04 packer: 2019/07/26 12:26:04 [WARN] Failed to read stderr for command 'powershell.exe -EncodedCommand VABlAHMAdAAtAFAAYQB0AGgAIAAiAEgASwBMAE0AOgBTAE8ARgBUAFcAQQBSAEUAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAXABDAHUAcgByAGUAbgB0AFYAZQByAHMAaQBvAG4AXABDAG8AbQBwAG8AbgBlAG4AdAAgAEIAYQBzAGUAZAAgAFMAZQByAHYAaQBjAGkAbgBnAFwAUgBlAGIAbwBvAHQAUABlAG4AZABpAG4AZwAiAA=='
```

which we believe is occurring [here](https://www.packer.io/docs/provisioners/windows-restart.html#check_registry).

We're not sure whether this is a bug in `check_registry` (which we know is in beta) -- if you're hunch is that it's still a config issue we'll take this to the mailing list.

Thanks for your help!

**Comment by SwampDragons** [comment] 2019-07-30 18:50
It could definitely be a bug in check_registry; I can take a look and see if I can reproduce but I'll need the simplest possibly packer template required to reproduce the issue and full logs with PACKER_DEBUG=1 in order to investigate this further.

**Comment by simonjjones** [comment] 2019-08-13 21:26
The issue appears to have been related to the stderr writer for the check registry command not being set. I've raised #7983 to resolve. Awaiting confirmation on signing the CLA
