### ISSUE TITLE
env() should implicitly convert to number without validate warning.

### ISSUE THREAD

**Issue by selfscrum** [hashicorp/packer#11918] opened 2022-08-01 18:38 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description

When declaring a variable of type number and setting the default value from an environment variable with env(), `packer validate` issues a warning of incompatible data types. Technically this is true since environment variables are always strings, but I think protecting the interface's semantic is more important than insisting on a type.

The feature request is about to remove the warning, so I see these options
1. remove the warning for that constellation
2. Allow a nested use of convert in the parameter: `default = env(convert("MYVAR", number))`
3. Allow the use of format in the assignment: `default = format("%d", env("MYVAR"))`

#### Use Case(s)

All cases where packer is controlled by environment variables.

#### Potential configuration

```
```

**Comment by nywilken** [comment] 2022-10-14 18:56
Hi there @selfscrum thanks for opening up this request. The `env` function was added for providing parity with the Env function available to legacy JSON templates. In fact, I believe the `env` function is the sole expression that can be used for setting default values in a variable block, as variables generated from an expression are really meant to be defined as locals. This is the reason why other functions such as `format` or `convert` within the `env` function don't work.

 It is unlikely that we will change the `env` function behavior to support other expressions. So I am interested in seeing if there is anything that can be done if this is not working properly.

All that aside, using the HCL snippet below I'm am unable to reproduce this issue with the latest version of Packer with a variable block that explicitly defines the type constraint for the variable.  Please let me know if your variable blocks look differently so I can adjust and retest. 

<details>
<summary> Example Snippet and Output </summary>

```hcl
variable "mynum" {
 type = number
 default = env("MYNUM")
}

locals {
  numTest = "${var.mynum} * 10"
}
source "null" "ubuntu" {
communicator = "none"
}

build {
  sources = ["source.null.ubuntu"]
	  provisioner "shell-local" {
		inline = ["echo mynum ${var.mynum}"]
	  } 
	  provisioner "shell-local" {
        name = "mynumTest"
		inline = ["echo numTest=${local.numTest}"]
	  } 
}
```

Here are a few command line executions
```
~>  MYNUM=2 packer build /tmp/source.pkr.hcl
null.ubuntu: output will be in this color.

==> null.ubuntu: Running local shell script: /var/folders/k_/m9qky03d1g5bk7z3s5qr9yg00000gp/T/packer-shell1683524394
    null.ubuntu: mynum 2
==> null.ubuntu: Running local shell script: /var/folders/k_/m9qky03d1g5bk7z3s5qr9yg00000gp/T/packer-shell1172686016
    null.ubuntu: numTest=20
Build 'null.ubuntu' finished after 92 milliseconds 627 microseconds.

==> Wait completed after 92 milliseconds 676 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.ubuntu: Did not export anything. This is the null builder


~>  MYNUM="30" packer build /tmp/source.pkr.hcl
null.ubuntu: output will be in this color.

==> null.ubuntu: Running local shell script: /var/folders/k_/m9qky03d1g5bk7z3s5qr9yg00000gp/T/packer-shell4142613351
    null.ubuntu: mynum 30
==> null.ubuntu: Running local shell script: /var/folders/k_/m9qky03d1g5bk7z3s5qr9yg00000gp/T/packer-shell580100140
    null.ubuntu: numTest=300
Build 'null.ubuntu' finished after 119 milliseconds 377 microseconds.

==> Wait completed after 119 milliseconds 417 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.ubuntu: Did not export anything. This is the null builder

~>  MYNUM="NOTNUMBERSTRING" packer build /tmp/source.pkr.hcl
Error: Invalid default value for variable

  on /tmp/source.pkr.hcl line 3, in variable "mynum":
   3:  default = env("MYNUM")

This default value is not compatible with the variable's type constraint: a
number is required.

```

Validation Examples

```
~>  MYNUM="NOTNUMBERSTRING" packer validate /tmp/source.pkr.hcl
Error: Invalid default value for variable

  on /tmp/source.pkr.hcl line 3, in variable "mynum":
   3:  default = env("MYNUM")

This default value is not compatible with the variable's type constraint: a
number is required.

~>  MYNUM=2 packer validate /tmp/source.pkr.hcl
The configuration is valid.

~>  MYNUM="30.6" packer validate /tmp/source.pkr.hcl
The configuration is valid.
```

</details>


As an alternative, HCL has native support for assigning values to variables, which may work a little different than the `env` function. I have to test and validate. 

Have you tried using [`PKR_VAR_*` environment variables](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/variables#environment-variables) for setting the default values for your variables?

**Comment by selfscrum** [comment] 2022-10-15 20:57
Thanks @nywilken for your explanations. 

I can confirm your findings, and PK_VAR_* showa the same behaviour. 

However I would have expected that a syntax validation (`-syntax-only`) doesn't complain about an unset environment variable. My plan was to run validations as part of an automated test suite, in an environment that does not have the variables set at that point. 

It's a minor nuisance, of course, so I changed already my testing environment.

**Comment by nywilken** [comment] 2023-02-01 19:08
@selfscrum I'm going to close this issue. But I've marked it as a reference for internal review when revisiting variable definitions and assignments in HCL2 templates.

**Closed by nywilken** 2023-02-01 19:08 UTC
Labels: enhancement, need-repro, hcl2
