### ISSUE TITLE
alicloud doesn't recognise resource_group_id field

### ISSUE THREAD

**Issue by michaelw730** [hashicorp/packer#12025] opened 2022-10-04 14:27 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

I'm trying to create a VM on alicloud and into a particular resource group.  I'm using using the alicloud-ecs module but it fails with a problem with the resource_group_id. According to the docs this is an acceptable optional field.

https://developer.hashicorp.com/packer/plugins/builders/alicloud

Without the resource_group_id field it runs fine.

Hope someone can help with this.  Thanks

#### Reproduction Steps

"packer.pkr.hcl" packer file (note that I've excluded the ansible provisioner from this issue)

https://gist.github.com/michaelw730/45453a0e775d8d303961d3d542cba580

"aliyun.pkrvars.hcl" vars file (values are from alicloud)
```
vpc_id = ""
security_group_id = ""
vswitch_id = ""
vpc_cidr_block = "172.16.0.0/24"
resource_group_id = ""

```

run using
```
packer build -var "build_number=mw" -var "access_key=$ACCESS_KEY" -var "secret_key=$SECRET_KEY" -var "image_name=debian_10_11_x64_20G_alibase_20220208.vhd" -var-file="aliyun.pkrvars.hcl" "packer.pkr.hcl"
```
### Packer version

Packer v1.8.0

### Operating system and Environment details

Ubuntu 20.04 devcontainer on Mac M1

### Log Fragments and crash.log files

logs here: https://gist.github.com/michaelw730/31b70268e29da4dd5dbd7e8b435b3371

**Comment by michaelw730** [comment] 2022-10-04 18:59
Looks like the version with the resource_group_id is v1.0.4

**Comment by nywilken** [comment] 2022-10-04 20:35
Hi @michaelw730 from your last comment it looks like you were able to get this all squared away. To help ensure the proper version is used with your configuration I recommend pinning the required version of the AliCloud plugin in your template. You can do so by adding the required_plugins block to your configuration. 

```hcl
packer {
  required_plugins {
    alicloud = {
      version = ">= 1.0.4"
      source  = "github.com/hashicorp/alicloud"
    }
  }
}
```

I'm going to close this issue seeing as it not a bug. If you I missed something and you think this is a bug please feel free to drop a comment on the issue.

**Closed by nywilken** 2022-10-04 20:35 UTC
Labels: invalid
