### ISSUE TITLE
arm binary for new osx M1

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/packer#10826] opened 2021-03-25 15:34 UTC
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I noticed that I cannot simply do a `brew install packer` on my m1 mac and this is because there is no arm binary available to download.

It would be nice to have an m1 arm binary so I don't have to compile it manually. Compiling from source returned these errors.

```bash
✗ brew install --build-from-source packer
==> Cloning https://github.com/hashicorp/packer.git
Cloning into '/Users/user/Library/Caches/Homebrew/packer--git'...
Updating files: 100% (11104/11104), done.
==> Checking out tag v1.7.0
HEAD is now at 7ea4a77 Cut version 1.7.0
==> go build
Last 15 lines from /Users/user/Library/Logs/Homebrew/packer/01.go:
go: downloading go.opencensus.io v0.22.4
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/kr/fs v0.1.0
go: downloading github.com/dylanmei/iso8601 v0.1.0
go: downloading github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d
go: downloading github.com/golang/snappy v0.0.1
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading github.com/hashicorp/go-immutable-radix v1.1.0
go: downloading github.com/hashicorp/golang-lru v0.5.3
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
# github.com/shirou/gopsutil/process
/Users/user/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:567:34: undefined: KinfoProc
/Users/user/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:568:8: undefined: KinfoProc
/Users/user/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:581:32: undefined: KinfoProc
/Users/user/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:585:62: undefined: KinfoProc

Do not report this issue to Homebrew/brew or Homebrew/core!
```

#### Use Case(s)

Using packer on the m1

#### Potential configuration

N/A

#### Potential References

N/A

**Comment by sylviamoss** [comment] 2021-03-29 09:35
Hey there! Thanks for reporting. This a duplicate of https://github.com/hashicorp/packer/issues/10708 so I'll close it. We are using the other to keep track of it.

**Closed by sylviamoss** 2021-03-29 09:35 UTC
Labels: enhancement
