### ISSUE TITLE
Cross account AMI sharing not working as expected

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#5919] opened 2018-02-17 21:01 UTC
I have an AWS AMI in one account _(call it Acme Inc)_, that I have given access to a secondary account _(Foobar LLC)_ via AMI permissions and the account ID. I am using the following in Packer to grab the latest version of that AMI:

```
"source_ami_filter": {
    "filters": {
        "tag:Family": "base-ubuntu-1604-lts"
    },
    "most_recent": true
}
```

However when I run this in the secondary account _(Foobar LLC)_ Packer is unable to get the AMI.

```
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No AMI was found matching filters: {
  Filters: [{
      Name: "tag:Family",
      Values: ["base-ubuntu-1604-lts"]
    }]
}
```

This should be working correct?

**Comment by rickard-von-essen** [comment] 2018-02-17 21:05
Could you please provide more details. Otherwise it's hard to understand if you set this up correctly.

**Comment by nodesocket** [comment] 2018-02-17 21:13
Sure. In one AWS account _(Acme Inc_) I have the following AMI:

```
Name | base-ubuntu-1604-lts-7103fb83-c20
Family | base-ubuntu-1604-lts
```

I modified the permissions of this AMI and gave it access to the second AWS account _(Foobar LLC)_:

<img width="705" alt="screen shot 2018-02-17 at 3 12 24 pm" src="https://user-images.githubusercontent.com/523312/36345654-087a673c-13f5-11e8-9553-7735282d9445.png">

When running packer under the _(Foobar LLC)_ account, I am getting:

```
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No AMI was found matching filters: {
  Filters: [{
      Name: "tag:Family",
      Values: ["base-ubuntu-1604-lts"]
    }]
}
```

**Comment by rickard-von-essen** [comment] 2018-02-17 21:22
Ok, if you start by hardcoding the AMI ID to see that you have access, (I expect that it should work).

But the problem is in fact that the Tags are in the first account, and those can't be seen from the second one. (Try it with the cli) 

Instead of using tags I suggest that you filter on name and description. Also be sure to always add an owners account otherwise you have no control of what you are launching.

**Comment by nodesocket** [comment] 2018-02-17 21:26
Hard coding the `ami-id` worked.

**Comment by rickard-von-essen** [comment] 2018-02-18 07:50
Closing this since Packer seems to work as it should.

**Closed** 2018-02-18 07:50 UTC
Labels: builder/amazon, need-more-info, waiting-reply

**Comment by vimalma1093** [comment] 2018-10-09 18:55
Tags are seen in the first account but not in the second account. Is it an issue with packer not propagating the tags between accounts?

**Comment by rickard-von-essen** [comment] 2018-10-09 19:43
@vimalma1093 tags are their own object in AWS and cannot be shared to other accounts.

**Comment by vimalma1093** [comment] 2018-10-09 19:56
Yes Rickard. I verified that my creating an AMI with tags in AWS console and shared it with other account but still tags were not shared. That makes sense. Thanks
