### ISSUE TITLE
Feature Request: support ssh agent on docker provisioner with ansible

### ISSUE THREAD

**Issue by awalker125** [hashicorp/packer#5370] opened 2017-09-21 13:46 UTC
Hi,

I'm using the docker builder with the ansible provisioner to create a container image. I'd like to use the anisble git module to pull into the container a private git repo. This doesnt work as it doesnt seem like the ssh proxy support agent forwarding. When ansible makes the request to forward the agent you get (I think)

2017/09/21 13:12:47 packer: 2017/09/21 13:12:47 rejecting auth-agent-req@openssh.com request

Is it possible to support this given the proxy is converting the ssh commands into docker exec commands?

I've seen some people mounting their SSH_AUTH_SOCK as a volume inside the container but I guess that would need to be done by the docker builder when it starts the container.

If not it might be worth mentioning in the documentation that this will not work.

**Comment by awalker125** [comment] 2017-09-22 07:35
For anyone else interested in doing something similar. I've worked around this with the following. 

#group_vars/all/main.yml
repos:
  - repo: 'git@somegiturl:somegroup/someproject.git'
    version: master
    dest: /deploy
    workspace: "{{ playbook_dir }}/../stage"
    name: someproject

#tasks/main.yml
---
# tasks file for ansible-role-git-deploy
- name: ensure workspace(s) exists
  connection: local
  file:
    path: "{{ item.workspace }}/{{ item.name }}"
    state: directory
  with_items: "{{ repos }}"
  become_user: root  
  become: true

- name: clone git repo(s)
  connection: local
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.workspace }}/{{ item.name }}"
    archive: "{{ item.workspace }}/{{ item.name }}.zip"
    version: "{{ item.version | default('HEAD') }}"
    accept_hostkey: true
  with_items: "{{ repos }}"

  
- name: ensure destination(s) exists
  file:
    path: "{{ item.dest }}/{{ item.name }}"
    state: directory
  with_items: "{{ repos }}"
  become_user: root  
  become: true
  
- name: extract repo(s) on remote
  unarchive:
    src: "{{ item.workspace }}/{{ item.name }}.zip"
    dest: "{{ item.dest }}/{{ item.name }}"
  with_items: "{{ repos }}"

**Comment by mwhooker** [comment] 2017-09-25 21:40
Agreed that this should be added to the docs. I'm not surprised that ansible and docker have some issues. 

It's worth mentioning that you can use the [`volumes`](https://www.packer.io/docs/builders/docker.html#volumes) option in the docker builder to mount your ssh socket. You'll need to somehow set the `SSH_AUTH_SOCK` envvar in the context of your provisioner as well

something like this should work (untested)

```
{
    "type": "docker",
    "volumes": {
        "{{env `SSH_AUTH_SOCK`}}": "{{env `SSH_AUTH_SOCK`}}"
    }
}
```

**Comment by ed-flanagan** [comment] 2018-01-30 08:47
There's possibly a similar situation with Chef.
I've been using something like this:

```json
{
  "variables": {
    "host_ssh_auth_sock": "{{env `SSH_AUTH_SOCK`}}",
    "guest_ssh_auth_sock": "/mounted-ssh-agent"
  },
  "builders": [
    {
      "type": "docker",
      "volumes": {
	"{{user `host_ssh_auth_sock`}}": "{{user `guest_ssh_auth_sock`}}"
      }
    }
  ],
  "provisioners": [
    "type": "chef-solo",
    "execute_command": "{{if .Sudo}}sudo {{end}}SSH_AUTH_SOCK={{user `guest_ssh_auth_sock`}} chef-solo --no-color -c {{.ConfigPath}} -j {{.JsonPath}}"
  ]
}
```

Same [`volumes`](https://www.packer.io/docs/builders/docker.html#volumes) idea already mentioned above.
Extends it by setting the `SSH_AUTH_SOCK` variable for the Chef `execute_command`.

You could probably accomplish similar behavior, without modifiying `execute_command`, by passing the `SSH_AUTH_SOCK` value as an attribute to the [`json`](https://www.packer.io/docs/provisioners/chef-solo.html#json) config and set/use it as a [env var](https://docs.chef.io/environment_variables.html) in your recipe(s). E.g.

```json
{
  "type": "chef-solo",
  "json": {
    "exampleorg": {
      "ssh_auth_sock": "{{user `client_ssh_auth_sock`}}"
    }
  }
}
```
```ruby
ENV['SSH_AUTH_SOCK'] = node['exampleorg']['ssh_auth_sock']

# OR

execute "some command" do
  environment {
    'SSH_AUTH_SOCK' => node['exampleorg']['ssh_auth_sock']
  }
end
```

**Comment by SwampDragons** [comment] 2018-12-13 00:32
I'm going to close this as a duplicate of 5287

**Closed by SwampDragons** 2018-12-13 00:32 UTC
Labels: builder/docker, community-supported plugin, docs, duplicate, enhancement, provisioner/ansible-remote
