### ISSUE TITLE
Packer WinRM connection Ansible 2.7.10 

### ISSUE THREAD

**Issue by dfoley84** [hashicorp/packer#7561] opened 2019-04-24 23:54 UTC
Packer version 1.4.0
Ansible version 2.7.10 

 ```
amazon-ebs: PLAYBOOK: win.yml **************************************************************
    amazon-ebs: 1 plays in /home/ubuntu/packer/win.yml
    amazon-ebs:
    amazon-ebs: PLAY [all] *********************************************************************
    amazon-ebs:
    amazon-ebs: TASK [Gathering Facts] *********************************************************
    amazon-ebs: task path: /home/ubuntu/packer/win.yml:3
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "msg": "Requested option use_tty was not defined in configuration"
    amazon-ebs: }
    amazon-ebs:         to retry, use: --limit @/home/ubuntu/packer/win.retry
    amazon-ebs:
    amazon-ebs: PLAY RECAP *********************************************************************
    amazon-ebs: default                    : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by SwampDragons** [comment] 2019-04-25 18:07
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

I'm closing this for now because there's nothing I can do without the above details, but if you can provide the necessary info I'll reopen.

**Closed by SwampDragons** 2019-04-25 18:07 UTC
Labels: community-supported plugin, need-more-info, provisioner/ansible-remote
