### ISSUE TITLE
Packer fails to spin-up a Windows vsphere VM using ansible 2.9.1

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [hashicorp/packer#8455] opened 2019-12-06 04:47 UTC
Hi,

I am running packer with ansible to spin-up a windows VM and successfully able to spin-up the VM's on ansible version 2.6. Once we updated the ansible version to 2.9.1,  I am having issues executing the packer script and it fails while gathering the facts.

Here is the error while running the packer script. Please let me know if you need more details.

==> vsphere-clone: Provisioning with Ansible...
==> vsphere-clone: Executing Ansible: ansible-playbook --extra-vars packer_build_name=vsphere-clone packer_builder_type=vsphere-clone -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible304636709 /scratch/isyed/windows_packer/ansible/provisioning/site.yml -e ansible_ssh_private_key_file=/tmp/ansible-key257014622 --connection packer --extra-vars ansible_shell_type=powershell ansible_shell_executable=None oe_version=122 -vvv
    vsphere-clone:
    vsphere-clone: PLAY [windows] *****************************************************************
    vsphere-clone:
    vsphere-clone: TASK [Gathering Facts] *********************************************************
    vsphere-clone: fatal: [windows]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"failed": true, "module_stderr": "Warning: Permanently added '[127.0.0.1]:44324' (RSA) to the list of known hosts.\r\nParameter format not correct - ;\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}

**Comment by SwampDragons** [comment] 2019-12-06 21:18
Hi, thanks for reaching out. 

I think this is probably a duplicate of #7667 -- workarounds can be found on that issue. I'm going to close this as a duplicate so that we can track progress on the issue in a single place.  

Thanks!

**Closed by SwampDragons** 2019-12-06 21:18 UTC

**Comment by IrfanSyed-PSC** [comment] 2019-12-08 04:00
Hi,

I am not sure if that is true. I added the workaround, but I still see the problem.

==> vsphere-clone: Executing Ansible: ansible-playbook --extra-vars packer_build_name=vsphere-clone packer_builder_type=vsphere-clone -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible757941491 /scratch/isyed/windows_packer/ansible/provisioning/site.yml -e ansible_ssh_private_key_file=/tmp/ansible-key892291300 --connection packer --extra-vars ansible_shell_type=powershell ansible_shell_executable=None ansible_python_interpreter=/usr/bin/python -vvv
    vsphere-clone:
    vsphere-clone: PLAY [windows] *****************************************************************
    vsphere-clone:
    vsphere-clone: TASK [Gathering Facts] *********************************************************
    vsphere-clone: fatal: [windows]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"failed": true, "module_stderr": "Warning: Permanently added '[127.0.0.1]:46346' (RSA) to the list of known hosts.\r\nParameter format not correct - ;\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}

**Comment by SwampDragons** [comment] 2019-12-09 17:10
Looking at your logs -- `.\r\nParameter format not correct - ;\r\n",`

To investigate further, we need all the details requested in the issue template.

**Comment by IrfanSyed-PSC** [comment] 2019-12-12 17:45
Please find the details below

Here is the builder

"builders": [
    {
      "type": "vsphere-clone",
      "vcenter_server": "mydbcenter.com",
      "username": "{{user `username`}}",
      "password": "{{user `password`}}",
      "insecure_connection": "true",
      "vm_name": "{{user `vmname`}}",
      "datacenter": "DatacenterESX",
      "cluster": "IAC/USB00123",
      "resource_pool": "PASOE",
      "host": "qavmhost34.pasoe.com",
      "datastore": "DS-BED-DEVSTORE-02",
      "template": "IAC-windows10-ltsc-1809",
      "folder": "DevelopmentVMs/QPE/Automation/PASOE",
      "communicator": "winrm",
      "winrm_username": "progress",
      "winrm_password": "P@ssword",
      "CPUs": "{{user `CPUs`}}",
      "RAM": "{{user `RAM`}}",
      "linked_clone": true,
      "create_snapshot": true,
      "RAM_reserve_all": "{{user `RAM_reserve_all`}}"
    }
  ]

Provisioner script is as below

"provisioners": [
     {

      "type": "powershell",
      "elevated_user": "SYSTEM",
      "elevated_password": "",
      "script": "setup/copyinstall.ps1",
      "environment_vars": [
        "oe_user={{user `OE_USER`}}",
        "oe_password={{user `OE_PASSWORD`}}",
        "oe_version={{user `oe_version`}}"
      ]
    },
    {
      "type": "ansible",
      "user": "root",
      "host_alias": "windows",
      "playbook_file": "ansible/provisioning/site.yml",
      "extra_arguments": [
        "--connection", "packer",
        "--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None oe_version={{user `oe_version`}} ansible_python_interpreter=/usr/bin/python -vvv"
      ]
    }
  ]

Here is my packer output


==> vsphere-clone: Customizing hardware...
==> vsphere-clone: Power on VM...
==> vsphere-clone: Waiting for IP...
==> vsphere-clone: IP address: 10.128.54.161
==> vsphere-clone: Using winrm communicator to connect: 10.128.54.161
==> vsphere-clone: Waiting for WinRM to become available...
    vsphere-clone: #< CLIXML
    vsphere-clone: WinRM connected.
    vsphere-clone: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vsphere-clone: Connected to WinRM!
==> vsphere-clone: Provisioning with Powershell...
==> vsphere-clone: Provisioning with powershell script: setup/copyoeinstall.ps1
    vsphere-clone:
    vsphere-clone: Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
    vsphere-clone: ----           ---------     --------- --------      ----                                               ---------------
    vsphere-clone: Z                1992.26       1054.14 FileSystem    \\remoteserver\f11\n...
    vsphere-clone:
    vsphere-clone: LocalName       : Z:
    vsphere-clone: RemoteName      : \\remoteserver\f11\nt64\tested
    vsphere-clone: ConnectionState : Disconnected
    vsphere-clone: Status          : Unavailable
    vsphere-clone:

▽
    vsphere-clone: Copying the cdimage
==> vsphere-clone: Provisioning with Ansible...
==> vsphere-clone: Executing Ansible: ansible-playbook --extra-vars packer_build_name=vsphere-clone packer_builder_type=vsphere-clone -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible391331966 /scratch/isyed/windows_packer/ansible/provisioning/site.yml -e ansible_ssh_private_key_file=/tmp/ansible-key496797403 --connection packer --extra-vars ansible_shell_type=powershell ansible_shell_executable=None oe_version=122 ansible_python_interpreter=/usr/bin/python -vvv
    vsphere-clone:
    vsphere-clone: PLAY [windows] *****************************************************************
    vsphere-clone:
    vsphere-clone: TASK [Gathering Facts] *********************************************************
    vsphere-clone: fatal: [windows]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"failed": true, "module_stderr": "Warning: Permanently added '[127.0.0.1]:39395' (RSA) to the list of known hosts.\r\nParameter format not correct - ;\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
    vsphere-clone:
    vsphere-clone: PLAY RECAP *********************************************************************
    vsphere-clone: windows                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    vsphere-clone:
==> vsphere-clone: Power off VM...

▽
==> vsphere-clone: Destroying VM...

**Comment by mtarral** [comment] 2020-01-09 17:34
Hi,

I can confirm this issue at least since `Ansible 2.8`.
Adding `ansible_python_interpreter=auto_silent` didn't fix the issue for me.

@SwampDragons I believe Windows and `WinRM` needs a different workaround than the one given in https://github.com/hashicorp/packer/issues/7667

I have no clue how to solve this, since very little debug info is available from Ansible, apart from the `setup` module failing.

Thanks.
