### ISSUE TITLE
Using "packer build -only" still parses sources not included by -only, generating errors

### ISSUE THREAD

**Issue by hawko2600** [hashicorp/packer#11365] opened 2021-10-29 02:39 UTC
I have a hcl template which uses hyperv-iso to create a base image, and hyperv-vmcx to then use that image to customise other builds. I use packer build -only xxx to select a build target.

When the iso source artefact hasn't been created yet, the run of packer build (to create it) will also complain with an error for each of the other sources that the vmcx image doesn't exist, despite none of those builds being selected via -only.

My expected behaviour is that using -only will only worry about the only build that I selected, not have a sook about unrelated and unselected builds. The template parser should ignore configuration variables in sections that do not match the names specified in -only.

The workaround is to use two templates, which then means two places to maintain the same build variables.

**Comment by nywilken** [comment] 2022-05-18 15:44
Duplicate of #11037

**Closed by nywilken** 2022-05-18 15:44 UTC
Labels: core, hcl2, hcl2-dag
