### ISSUE TITLE
I am getting the following error while building image from packer 

### ISSUE THREAD

**Issue by vikranthsuravarapu** [hashicorp/packer#7523] opened 2019-04-18 06:03 UTC
I am getting the following error while building an image through packer :
errored: Error processing command: Retryable error: Error uploading ps script containing env vars: Error uploading file to $env:TEMP\winrmcp-bf4b7bec-470b-4273-5487-ec6776ed8314.tmp: Couldn't create shell: http response error: 401 - invalid content type

**Comment by SwampDragons** [comment] 2019-04-18 18:12
Hi, thanks for reaching out!  In order to help you, we need the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by SwampDragons** [comment] 2019-04-19 18:40
I'm closing now because of insufficient information, but if you can share the info I asked for, we can reopen.

**Closed by SwampDragons** 2019-04-19 18:40 UTC
Labels: bug, need-more-info, provisioner/powershell
