### ISSUE TITLE
DigitalOcean builder validates snapshot regions using a wrong list

### ISSUE THREAD

**Issue by legal90** [hashicorp/packer#5948] opened 2018-02-26 12:20 UTC
I'm not sure, is it a bug of `godo` lib, or the packer builder's one.
When DigitalOcean builder validates the value of `snapshot_regions` param, seems like it expects only those regions, which are available for the droplet creation:
https://github.com/hashicorp/packer/blob/7f4112ba229309cfc0ebaa10ded2abdfaf1b22c8/builder/digitalocean/builder.go#L55

Template example:
```json
{
  "builders": [
    {
      "type": "digitalocean",
      "api_token": "{{user `api_token`}}",
      "snapshot_name": "base-debian-7_{{isotime \"2006-01-02_15-04-05\"}}",
      "image": "debian-7-x64",
      "region": "nyc1",
      "size": "s-1vcpu-1gb",
      "ssh_username": "root",
      "snapshot_regions": [
        "nyc1",
        "nyc2",
        "nyc3"
      ]
    }
  ],
<...>
}
```

Error message on `packer build`:
```
$ packer build ./base-debian-7.json

digitalocean output will be in this color.

Build 'digitalocean' errored: DigitalOcean: Invalid region, nyc2

==> Some builds didn't complete successfully and had errors:
--> digitalocean: DigitalOcean: Invalid region, nyc2

==> Builds finished but no artifacts were created.
```

Debug output: https://gist.github.com/legal90/209110ef25d61a4725ace046588eff2d

Actually, NYC2 is not available for droplet creation, however it is still possible to copy the result image there when the image is ready. At least, I can do that via DigitalOcean Web UI.
So, seems like that needs to be fixed for packer builder.

## Details
- Packer v1.2.0
- Host platform: OS X 10.13.3
- Debug output with the template json: https://gist.github.com/legal90/209110ef25d61a4725ace046588eff2d

**Comment by lfarnell** [comment] 2018-03-22 20:58
So I believe this is a packer issue. It looks like it doesn't check the whether the region is available. Once we filter the regions to only include available one, this should be good.

**Comment by rickard-von-essen** [comment] 2018-06-03 14:32
The problem is that `nyc2` is not listed in the API as a region:

```shell
$ curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Beare
r $TOKEN" "https://api.digitalocean.com/v2/regions" | jq '.regions[].slug'
"nyc1"
"sgp1"
"lon1"
"nyc3"
"ams3"
"fra1"
"tor1"
"sfo2"
"blr1"
```

But you can add snapshots there. I'll close this as _won't fix_ until DigitalOcean adds `nyc2` to their API. If that happens we can reopen this.

**Closed by rickard-von-essen** 2018-06-03 14:32 UTC
Labels: bug, builder/digitalocean
