### ISSUE TITLE
Wrong packer version

### ISSUE THREAD

**Issue by G3ph4z** [hashicorp/packer#7596] opened 2019-05-02 09:41 UTC
I downloaded the packer 1.4.0 for linux x64 from this url:
`https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip`

but If I check` packer version` its say I have 1.3.5 version, and not the 1.4.0.

```
denes@toaster:[~/Documents/packer]: packer version
Packer v1.3.5

Your version of Packer is out of date! The latest version
is 1.4.0. You can update by downloading from www.packer.io/downloads.html
 
```

**Comment by azr** [comment] 2019-05-02 10:01
Hello @G3ph4z, thanks for opening !
I could not reproduce your issue, are you sure your path is pointing to the right packer binary ? running `which packer` will help you in that case.

In a clean docker env I ran :
``` bash
wget https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip && unzip packer_1.4.0_linux_amd64.zip && ./packer version
[.........]
Packer v1.4.0
```

Closing this issue for now, we will re-open if it turns out there's a problem !

**Closed by azr** 2019-05-02 10:01 UTC
