### ISSUE TITLE
Used bridge networking  to provide ip to qemu kvm guest vm through packer, but getting SSH ip/port failed: dial tcp 10.0.0.8:22: connect: connection 

### ISSUE THREAD

**Issue by pravinjec** [hashicorp/packer#12625] opened 2023-09-15 06:47 UTC
Used net_bridge: br0 in json file to connect with br0 bridge , with nat it is working fine, but want to create multiple guest vm through packer and with default nat all the guest vm getting same ip. But i want different ip for all the guest vm.
If there is way with nat network to provide different ip to guest vm's then please let me know that  as well, else please help me to fix this issue. There is not much information on internet about bridge networking issue

Also when build starts tap interfaces are getting created for bridge.

==> qemu.aux-node: Waiting for the guest address to become available in the br0 network bridge...
2023/09/15 06:39:11 packer-builder-qemu plugin: Found guest address 10.0.0.8
==> qemu.aux-node: Using SSH communicator to connect: 10.0.0.8
2023/09/15 06:39:11 packer-builder-qemu plugin: [INFO] Waiting for SSH, up to timeout: 20m0s
==> qemu.aux-node: Waiting for SSH to become available...
2023/09/15 06:39:11 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.0.0.8:22: connect: connection 
refused
2023/09/15 06:39:16 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.0.0.8:22: connect: connection 
refused

After sometime in place of connection refused getting no route to host

2023/09/15 07:17:11 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.0.0.8:22: connect: no route to
 host
2023/09/15 07:17:14 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.0.0.8:22: connect: no route to
 host
2023/09/15 07:17:17 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.0.0.8:22: connect: no route to
 host

**Comment by pravinjec** [comment] 2023-09-25 05:32
I have tried using nats to provide different ip to different vm by adding mac address with static ip in the default.xml file. But still same ip is getting assigned, Can anyone please help me into it

**Comment by lbajolet-hashicorp** [comment] 2023-10-13 19:58
Hi @pravinjec,

This issue tracker is for us maintainers to keep track of the community-reported shortcomings with Packer itself, for asking more general usage questions, please use our [Discuss](https://discuss.hashicorp.com/c/packer/23) forum, where other members of the community tend to be active and may help you with your issue.

Since this issue is a usage question and not a bug or a feature request with Packer, I'll close this now, feel free to reopen if I misinterpreted the issue at hand.

Thanks

**Closed by lbajolet-hashicorp** 2023-10-13 19:58 UTC
