### ISSUE TITLE
VMWare ISO Builder Crashes when specifying https iso_url

### ISSUE THREAD

**Issue by jcsmith** [hashicorp/packer#6431] opened 2018-06-27 16:04 UTC
When specifying an https url for the iso_url parameter packer crashes.

- Packer version from `packer version`
Packer v1.2.4
- Host platform
OSX
uname: Darwin WFPSYSSC3CGG8WP 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64- Debug log output from `PACKER_LOG=1 packer build template.json`.

https://gist.github.com/jcsmith/9e726ab779aa8ca80fe9ea3714c057af

In addition I am including a gist containing the crash.log
https://gist.github.com/jcsmith/601022b356d979071e3fbaef6b093276

**Comment by jcsmith** [comment] 2018-06-27 18:30
Digging into this a little further and the issue seems to be related to having `SSLVerifyClient optional_no_ca`  in our https config.  At this point I'm not sure if this is a problem with packer proper or the golfing http libraries.

**Comment by jcsmith** [comment] 2018-06-27 22:51
No problem. Please let me know if I can provide any additional information to help you guys with this. 

--
Josh

**Comment by arizvisa** [comment] 2018-07-24 20:37
@SwampDragons, I can probably take care of this one sometime next week (since I did a bunch of the original re-working of the DownloadClient). 

The issue is due to my misunderstanding of when `http.Response` gets populated by `http.Client.Do`. If an http error occurs, `resp` will be initialized so you can grab the status code. However, if a connection error occurs (such as with SSL), `resp` can be nil. I apparently made an assumption that you could still check the response for information about what failed regardless of the issue.

So both `resp` and `err` will just need to be checked for `nil` at lines 293 and 303.

**Comment by SwampDragons** [comment] 2018-07-24 23:07
That's awesome.  I'd love it if you could take it on, and if you can't get to it before we're ready to do the next release then I can try to pick it up based on your advice.  Thanks!

**Comment by arizvisa** [comment] 2018-08-01 03:57
PR #6557 should fix this crash.

**Closed** 2018-08-02 18:32 UTC
Labels: crash
