### ISSUE TITLE
Unexpected EOF building Azure images

### ISSUE THREAD

**Issue by mbrouwer** [hashicorp/packer#6475] opened 2018-07-11 12:40 UTC
- Packer version from 1.2.4
- Host platform : Windows 2016/Ubuntu 16.04 LTS
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/mbrouwer/47af35bfe0df60184ca554ebd6c16a1e
- The _simplest example template and scripts_ needed to reproduce the bug.
windows2016.json:
https://gist.github.com/mbrouwer/7dae1b3373adab9928feda8b3329e5e9
sysprep.ps1:
https://gist.github.com/mbrouwer/7b6c4eac7449793cba613658a58e46a5

Starting Packer version 1.2.4 we get an error building custom images on Azure. The build finished correctly, a custom image is created but lots of resources arent cleaned up because packer fails with an error:
```
2018/07/11 11:32:57 [ERR] yamux: keepalive failed: i/o deadline reached
2018/07/11 11:32:57 [INFO] (telemetry) ending azure-arm
2018/07/11 11:32:57 ui error: Build 'azure-arm' errored: unexpected EOF
2018/07/11 11:32:57 Builds completed. Waiting on interrupt barrier...
2018/07/11 11:32:57 machine readable: error-count []string{"1"}
2018/07/11 11:32:57 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/07/11 11:32:57 machine readable: azure-arm,error []string{"unexpected EOF"}
2018/07/11 11:32:57 ui error: --> azure-arm: unexpected EOF
2018/07/11 11:32:57 ui: 
==> Builds finished but no artifacts were created.
```

We do not have this problem with 1.2.3

I found some issues with older versions where this was fixed and some people who mentioned they saw this in this 1.2.4 version also but I cannot find any issues that have been created.

**Comment by boumenot** [comment] 2018-07-11 17:38
This is a dupe of #6410 based on my reading.

**Closed by boumenot** 2018-07-11 17:38 UTC
Labels: duplicate
