### ISSUE TITLE
Build  'vmware-iso' errored: unexpected EOF using packer 1.2.0 on  ubuntu 16.04 , But when I use packer 1.1.3  it is works without issues 

### ISSUE THREAD

**Issue by naseemaljaradi** [hashicorp/packer#5911] opened 2018-02-15 16:51 UTC
{
  "builders": [
    {
      "type": "vmware-iso",
      "version": 11,
      "vm_name":"{{user `vm_name`}}",
      "iso_url": "{{user `iso_url`}}",
      "iso_checksum_type": "none",
      "headless": "{{user `headless`}}",
      "boot_wait": "2m",
      "winrm_username": "{{user `username`}}",
      "winrm_password": "{{user `password`}}",
      "winrm_timeout": "{{user `winrm_out`}}",,
      "winrm_port": ""{{user `winrm_port`}}",
      "winrm_host":"{{user `winrm_host`}}",
      "winrm_use_ntlm":true,
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "shutdown_timeout": "3h",
      "communicator": "winrm",
      "remote_type": "esx5",
      "remote_host": "{{user `esxi_host`}}",
      "remote_datastore": "{{user `esxi_datastore`}}",
      "remote_username": "{{user `esxi_username`}}",
      "remote_password": "{{user `esxi_password`}}",
      "keep_registered": true,
      "guest_os_type": "{{user `guest_os_type`}}",
      "tools_upload_flavor": "windows",
      "disk_size": "{{user `disk_size`}}",
      "floppy_files":[
       "{{user `autounattend`}}",
        "./scripts/winrm.ps1"
                      ],
      "vmx_data": {
         "ethernet0.networkName": "{{user `VM_Network`}}",
         "memsize": "{{user `memory_size`}}",
         "numvcpus": "{{user `cpus`}}",
         "scsi0.virtualDev": "lsisas1068"
                   }
    }
  ]
}

**Comment by jkleppinger** [comment] 2018-02-15 18:23
I see the same problem with vmware-iso, remote_type esx5, running packer 1.2.0 on SLES11.  Same thing works fine with 1.1.3.

**Comment by chaddrum** [comment] 2018-02-15 18:41
Same as above with vmware-iso, remote_type esx5, running packer 1.2.0 on RHEL7.  Working fine with 1.1.3.

**Comment by mwhooker** [comment] 2018-02-15 20:11
Thanks all for the report! I believe this is a duplicate of #5904 and has been fixed in master. packer 1.2.1 will be released soon with the fix. In the meantime, you can build from master or continue to use 1.1.3

If you don't think this is a duplicate, please open a new issue with a debug log

**Closed by mwhooker** 2018-02-15 20:11 UTC
