### ISSUE TITLE
Feature request - Oracle OCI build support user-data-file

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#5866] opened 2018-02-07 21:41 UTC
When you are Building windows server machines using the images Oracle supplies you currently have to log onto them enable winRM/firewalls and other setup feature before creating a custom image that can then be used by packer.  

If the user-data-feature was supported then you would be able to use standard Oracle images sending along a "setup.ps1" file as the user-datafile would then allow us to ensure that all the initial boot configuration could be completed before packer starts provisioning the build.

From the OCI launch help text.
--user-data-file [filename]
---------------------------

A file containing data that Cloud-Init can use to run custom scripts
or provide custom Cloud-Init configuration. This parameter is a
convenience wrapper around the 'user_data' field of the --metadata
parameter.  Populating both values in the same call will result in an
error. For more info see Cloud-Init documentation:
https://cloudinit.readthedocs.org/en/latest/topics/format.html.

**Comment by mwhooker** [comment] 2018-02-07 21:43
thanks for the issue. we'll see if we can add this in before the release on Friday. Seems good. Happy to accept PRs as well. I think it'll involve adding `attributes` and/or `attributes_file` fields to the builder, and setting the attributes in `step_create_instance`. Let us know if you want to take a stab at it, otherwise we'll see what we can do

**Comment by SwampDragons** [comment] 2018-02-07 22:00
Looks like you configure this feature through the API by adding the "attributes" field to the launch plan json. https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsg/creating-instances-using-launch-plans.html. This seems fairly trivial to add if we allow the user to add their own attributes json and add it in; it is probably impractical to do much by way of validation though. I'm going to try to get an MVP today.

**Comment by scross01** [comment] 2018-02-08 12:34
For **OCI Classic** the `userdata` is configured as describe in the doc links above. Adding an `attributes` attribute to the `oracle-classic` builder config would definitely be a useful addition 

However, I believe the context for @Marcus-James-Adams request may be for **OCI** (not Classic) - which would be an enhancement to the other builder
 https://github.com/hashicorp/packer/blob/master/builder/oracle/oci/driver_oci.go#L27 to pass the `userdata` as an additional attribute in the Metadata config.

- https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/Instance/LaunchInstance
- https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/LaunchInstanceDetails

**Comment by SwampDragons** [comment] 2018-02-08 21:14
I've added an `attributes` and an `attributes_file` field to the builder and docs, following the same pattern we use for user data in the aws builders. tested sending a pre-bootstrap script via both of these fields and was successful, and added an example of `attributes` to the example in the docs.  I also added an immediate fail saying that winrm is not supported in this builder yet, because it appears to me that this attributes file is necessary but not sufficient for successfully provisioning a windows instance. I haven't yet tried to reproduce all of the steps I found (here)[https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsg/accessing-your-windows-instance-using-rdp.html#GUID-E066B838-61E6-4C28-8A5F-315671E94AB1] in the builder, and I'm not clear on whether the vNICset requirement is just for connecting via RDP or whether I need to follow this for connecting via winRM as well.

**Comment by scross01** [comment] 2018-02-09 12:32
@SwampDragons as the packer builder is using shared networks for the public IP the section of the doc link for setting up WinRM access is "Accessing a Windows Instance on Shared Network Using RDP".  vNICSet are for the IPNetworks configuration, so not needed.

Similar the the way to builder creates Security List / Security Rule for for SSH access, all you should need is to create a rule for RDP access. 

f.y.i as reference, an equivalent Terraform config for launching a Windows instance can be found [here](https://github.com/oracle/terraform-provider-compute/blob/master/examples/opc/windows-instance-with-rdp/windows-server.tf)

**Comment by SwampDragons** [comment] 2018-02-09 17:10
Oh thanks @scross01.  I tried the security list/ security rule thing first and it didn't work so I assumed there was some other configuration needed.  Must have been PEBKAC though.

**Comment by SwampDragons** [comment] 2018-02-16 20:08
Closing because the oracle-classic builder now has support for the "attributes" file; remaining TODO is to allow winrm to connect, but that should be a separate ticket: https://github.com/hashicorp/packer/issues/5918

**Comment by Marcus-James-Adams** [comment] 2018-02-16 20:11
Hi,
This feature request was for Oracle OCI not classic builder.



Regards
Marcus


________________________________

**Comment by SwampDragons** [comment] 2018-02-16 20:26
Sorry about that; was assuming it was for classic because of your comment on the original oracle-classic PR

**Comment by SwampDragons** [comment] 2018-03-28 22:01
@scross01 should I be able to encode the contents of a ps1 script and send it as "user_data" and have it work out of the box, or am I missing something?

**Comment by scross01** [comment] 2018-03-28 22:24
It looks like the default Windows images don't support `userdata`, see end of page [here](https://docs.us-phoenix-1.oraclecloud.com/Content/Compute/Concepts/computeoverview.htm) 

> user_data has a maximum size of 16KB. For Linux instances with cloud-init configured, you can populate the user_data field with a Base64-encoded string of cloud-init user data. For more information on formats that cloud-init accepts, see cloud-init formats. **On Windows instances, the user_data field can be provided but isn't used by Oracle-provided images**.

However, I'd assume is possible to "manually" create new Custom Image from the default Windows image with cloudbase-init or something similar installed, and then use the custom image as the source for the Packer configuration, in which case passing in the user_data should work as expected.

**Comment by SwampDragons** [comment] 2018-03-28 22:26
Ah, thanks.

**Comment by SwampDragons** [comment] 2018-03-28 23:05
@Marcus-James-Adams I've implemented the user_data_file feature, but Packer is not going to be able to make winRM work out of the box on the oracle-provided windows images, since OCI does not support cloud-init on their provided windows images. 

However, as scross01 said, it should work if you do a small amount of legwork first to enable cloud-init. If you'd like me to build you a binary of PR #6079 give me your system architecture and you can give it a whirl.

**Comment by Marcus-James-Adams** [comment] 2018-03-29 06:31
AHH why is OCI so good but so no straightforward at the same time.

We have some contacts within oracle what do I need to tell them to enable userinit in their core image builds.

Thank you for the offer.  We a running it win x64.

Regards
Marcus


________________________________

**Closed** 2018-04-02 23:48 UTC
Labels: builder/oracle-oci, enhancement
