### ISSUE TITLE
Allow tagging volumes on amazon-ebs builder

### ISSUE THREAD

**Issue by lc-nyovchev** [hashicorp/packer#6337] opened 2018-06-04 11:21 UTC
We have the following use case:

1. we use Packer to create some AMIs in a BUILD account
2. we use Terraform to distribute the AMI to other accounts

The problem is, in step 1, we use the **"amazon-ebs"** builder, and we want to tag not only the AMI, but also the volumes that'd be created by the "ami_block_device_mappings".

For example, we have a Cassandra AMI which has 4 volumes attached (root and 3 auxiliary ones) and we'd like to tag the volumes but it seems it currently not possible.

This is **different** from the `run_volume_tags` config option as we are not interested in tagging the build volume's volumes, but more into the resulting AMI's volumes so we can find them easier.

Now we have stuff like this:

```
      "ami_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": "{{ user `xvda_size` }}",
          "delete_on_termination": true,
          "volume_type": "gp2"
        },
        {
          "device_name": "/dev/xvdf",
          "volume_size": "{{ user `var_size` }}",
          "delete_on_termination": true,
          "volume_type": "gp2"
        },
        {
          "device_name": "/dev/xvdg",
          "volume_size": "{{ user `data_size` }}",
          "delete_on_termination": false,
          "volume_type": "gp2"
        },
        {
          "device_name": "/dev/xvdh",
          "volume_size": "{{ user `commitlog_size` }}",
          "delete_on_termination": false,
          "volume_type": "gp2"
        }
      ]
```

It'd be good to be able to do something like:
```
 "ami_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": "{{ user `xvda_size` }}",
          "delete_on_termination": true,
          "volume_type": "gp2",
          "volume_tags": {
                "so_tag": "much_wow",
                "even_more_tags": "good_stuff"
           }
        },
       .......
      ]
```

**Comment by rickard-von-essen** [comment] 2018-06-04 11:40
>  [...] as we are not interested in tagging the build volume's volumes, but more into the resulting AMI's volumes so we can find them easier.

I'm not sure I understand what you want? AMI's doesn't have volumes. Could you elaborate.

**Comment by lc-nyovchev** [comment] 2018-06-04 12:53
Hey @rickard-von-essen I edited the answer:

ami_block_device_mappings creares some volumes, and we'd like to have those tagged, the same way we can tag launch_block_device_mappings.

**Comment by rickard-von-essen** [comment] 2018-06-05 06:55
> `ami_block_device_mappings` creates some volumes, and we'd like to have those tagged

So if I understand this correctly you would like to have some tags on the devices that the AMI creates when it is used to launch a EC2 instance? Unfortunately that is no support for that on AWS. _AMI's_ and _EBS Snapshots_ non of them carry over to the launched _EC2 Instance_ and _EBS Volumes_ from them. I'll close this as we can't implement it.

For more information see: 
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html

_If I misunderstood the request add a more detailed description._

**Closed by rickard-von-essen** 2018-06-05 06:55 UTC
Labels: builder/amazon, enhancement, need-more-info, waiting-reply

**Comment by s0undt3ch** [comment] 2019-06-22 07:13
I know the issue is closed, but my question is similar though not the same.

The resulting AMI will have EBS snapshots which are to be copied and used when booting the AMI.

Can those snapshots be tagged?

**Comment by s0undt3ch** [comment] 2019-06-22 07:19
I guess yes, https://www.packer.io/docs/builders/amazon-ebs.html#snapshot_tags
