### ISSUE TITLE
Unable to pack AMI after upgrading to Packer 1.1.3

### ISSUE THREAD

**Issue by guessi** [hashicorp/packer#5783] opened 2018-01-11 03:04 UTC
Describe the problem and include the following information:

- Packer version from `packer version`
    ```
    $ packer --version
    1.1.3
    ```
- Host platform
macOS, and Ubuntu Server 16.04.3 LTS

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/guessi/8d1381d93289214d89b43d410dfa6529

- The _simplest example template and scripts_ needed to reproduce the bug.
please refer to debug log in gist
  
Additional information for you, with same configuration,
* Test Passed with 1.1.0 ~ 1.1.2
* Test Failed with 1.1.3

**Comment by guessi** [comment] 2018-01-11 03:10
Hi Maintainers,

An extra information for you,
during my tests, I also try to capture network packet with `tcpdump`
`$ sudo tcpdump -i any -n host <ec2-ipaddr>`

I can capture SSH network packet while debug log shown (with 1.1.0 ~ 1.1.2)
`==> amazon-ebs: Waiting for instance (i-033cb8f73febed5e2) to become ready...`

but after upgrade to 1.1.3, I can't see SSH network packet anymore.


hope these information would help

**Comment by mwhooker** [comment] 2018-01-11 03:28
Thanks for the report. This looks like it's timing out while waiting for the instance to become ready, before it's tried to connect over SSH.

Unfortunately I'm having trouble reproducing this, possibly because of network differences.

I think this might be solved by the patch at https://github.com/hashicorp/packer/pull/5773
since it deals with this part of the code. Would you be able to build that branch and report back if it fixes the issue for you?

**Comment by guessi** [comment] 2018-01-11 06:11
@mwhooker I will try #5733 on my end later, will update result here, please hold on for my test result.

**Comment by guessi** [comment] 2018-01-11 06:27
@mwhooker Hi, I've tried #5733, build packer locally, and ran the same test, but still hanging
`==> amazon-ebs: Waiting for instance (i-xxxxxx) to become ready...`

at the same time, I created another terminal for watching `sudo tcpdump -i any -n host <ec2-ip>`, but doesn't get any SSH network traffic.

**Comment by mwhooker** [comment] 2018-01-11 09:04
Interesting. If you post debug output where your build was calling the homebrew packer I can try to see what's going on. It should be calling the same binary that's already running https://github.com/hashicorp/packer/blob/master/config.go#L200

for now I'm going to close it because it looks like we found the issue.

**Closed by mwhooker** 2018-01-11 09:04 UTC
Labels: bug, builder/amazon, waiting-reply

**Comment by guessi** [comment] 2018-01-11 09:13
@mwhooker sure, please close this issue report
as for the `$PATH` resolution, it's unrelated to original bug report, will update later. 👍
