### ISSUE TITLE
Executing packer from Windows gives EOF error

### ISSUE THREAD

**Issue by kishorramanan** [hashicorp/packer#5999] opened 2018-03-09 08:17 UTC
- Packer version: 1.2.1
- Host platform: Windows 10 Enterprise
- Debug Output:
   [Debug Output](https://gist.github.com/kishorramanan/5ae6cf01e0fbcb12dc1f8d824a73d1e5)
- Reproduce: Template
   [Template](https://gist.github.com/kishorramanan/c643a87f551486a6d241cd73857314a8)

**Comment by rickard-von-essen** [comment] 2018-03-09 09:57
Can you fix the links. Thanks

**Comment by kishorramanan** [comment] 2018-03-09 18:43
@rickard-von-essen  links have been updated

**Comment by mwhooker** [comment] 2018-03-09 19:38
Can you run the build again the the env var `PACKER_LOG` set?

**Comment by kishorramanan** [comment] 2018-03-10 14:03
Find the below gist for the log

[Log](https://gist.github.com/kishorramanan/e647372e8e70a3a020cf15bd8523ce5f)

**Comment by kishorramanan** [comment] 2018-04-01 08:17
Any updates?

**Comment by OwenGr** [comment] 2018-06-01 15:49
I'm receiving a similar error running packer in the hashicorp/packer docker image through Concourse targeting Azure, not AWS. I'm only building a Windows VM, not building from a Windows VM. Also, this pipeline functioned fine before the 1.2.4 update. It is still creating the Image in Azure, just failing during the resource cleanup.

I will get more logs. I'm not sure if this is the same issue or I should post a new one.

```
==> azure-arm: Deleting resource group ...
==> azure-arm:  -> ResourceGroupName : 'WTW-ESIE-CICD-DEV'
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, only deleting individual resources ...
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'BuildAgent'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrnirgjgq35zwn'
Build 'azure-arm' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> azure-arm: unexpected EOF

==> Builds finished but no artifacts were created.
```

**Comment by SwampDragons** [comment] 2018-06-01 17:43
@OwenGr if you're experiencing a regression since 1.2.4 it's probably not the same as this ticket, which has been open since well before that release.  Can you open a new ticket with your issue and steps to reproduce?

@kishorramanan no updates yet, sorry. I haven't had a chance to look at your logs.

**Comment by OwenGr** [comment] 2018-06-01 18:08
Confirmed it's a regression (at least, it works fine retargeting 1.2.3). I'll open another issue.

**Comment by harijayms** [comment] 2018-06-05 05:37
@OwenGr let me know the new issue and would appreciate if you can provide your template details . Also can you confirm if its a consistent repro ?  Typically unexpected EOF indicates failure down in SDK. I just pulled the latests source and I dont see the issue repro for me yet.

**Comment by mwhooker** [comment] 2018-06-05 05:47
@kishorramanan Can you still reproduce on the latest packer? There's not much we can do about an older version

**Comment by mariuszdotnet** [comment] 2018-06-18 04:07
Same issue as @OwenGr and same environment.  Packer container in concourse with Azure.

Template is here: https://github.com/mariuszdotnet/image-rhel7/blob/master/template.json

Error:

==> azure-arm: The resource group was not created by Packer, only deleting individual resources ...
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvmc2hx13bnnc'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrnic2hx13bnnc'
==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkripc2hx13bnnc'
Build 'azure-arm' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> azure-arm: unexpected EOF

==> Builds finished but no artifacts were created.

**Comment by SwampDragons** [comment] 2018-08-17 22:54
Closing since we never got acknowledgment of whether the Amazon issue is fixed in a recent packer. Looks like a fix has been merged for the commenters who say the Azure issue.

**Closed by SwampDragons** 2018-08-17 22:54 UTC
Labels: builder/amazon, windows-host
