### ISSUE TITLE
AWS EBS Builder Returns 0 on Failure Without Credentials

### ISSUE THREAD

**Issue by naftulikay** [hashicorp/packer#7382] opened 2019-03-06 19:07 UTC
I use Packer in automated, CI/CD workloads for automating the building of machine images. My primary builder is the EBS builder for AWS. I am on latest 1.3.5.

When I run Packer from my CI server, if I don't include credentials, the build obviously fails, but Packer returns a 0 exit status, so my CI server sees it as a build passed.

Can we correct Packer to return a non-zero exit code when EBS builds fail without credentials?

**Comment by naftulikay** [comment] 2019-03-06 20:06
I am attempting to find the source of this issue. Here are my findings:

 - Common AWS Credential Session: [builder/amazon/common/access_config.go#108 AccessConfig.Session(...)](https://github.com/naftulikay/packer/blob/ec3b0a51383f16ec522c5ed391ce3fe79232046e/builder/amazon/common/access_config.go#L108)
 - EBS Builder Credential Acquisition: [builder/amazon/ebs/builder.go#90 Builder.Run(...)](https://github.com/naftulikay/packer/blob/ec3b0a51383f16ec522c5ed391ce3fe79232046e/builder/amazon/ebs/builder.go#L90)
 - Builder Command: [command/bulid.go#183 BuildCommand.run(...)](https://github.com/naftulikay/packer/blob/ec3b0a51383f16ec522c5ed391ce3fe79232046e/command/build.go#L183)

The specific issue seems to be triggered here:

 - [command/builder.go#284](https://github.com/naftulikay/packer/blob/ec3b0a51383f16ec522c5ed391ce3fe79232046e/command/build.go#L284)

```go
if len(artifacts.m) > 0 {
  // ...
} else {
  c.Ui.Say("\n==> Builds finished but no artifacts were created.")
}

// ...

if len(errors) > 0 {
  // If any errors occurred, exit with a non-zero exit status
  return 1
}
```

It seems that at this point, the error handling isn't catching the error for some reason.

**Comment by naftulikay** [comment] 2019-03-06 22:27
I have not been successful getting an environment up to experiment with the source code. I've been able to build the binary but it seems to be ignoring my files on disk; if I enter garbage that should break Go compilation, `go build` still seems to succeed.

**Comment by SwampDragons** [comment] 2019-03-06 22:42
Do you have debug logs (produced with PACKER_LOG=1)?  If I can see logs and what error is getting thrown it may help us understand why it isn't being picked up.

As far as your build issues -- try using the makefile to build instead and see if that helps.  e.g. call `make dev` instead of `go build` and use the packer produced in ~/go/bin

**Comment by naftulikay** [comment] 2019-03-06 22:51
So I have done the following to try to stimulate more output to detect what's happening:

```diff
diff --git a/command/build.go b/command/build.go
index 57d8c4038..a5aa79700 100644
--- a/command/build.go
+++ b/command/build.go
@@ -154,6 +154,8 @@ func (c *BuildCommand) Run(args []string) int {
 		wg.Add(1)
 		// buildCtx, cancelCtx := ctx.WithCancel()
 
+		fmt.Printf("THE FUCKING HELL ARE YOU DOING MAN") aeodualrceuaoeus
+
 		// Handle interrupts for this build
 		sigCh := make(chan os.Signal, 1)
 		signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
@@ -182,6 +184,10 @@ func (c *BuildCommand) Run(args []string) int {
 			if err != nil {
 				ui.Error(fmt.Sprintf("Build '%s' errored: %s", name, err))
 				errors[name] = err
+
+				log.Printf("\n-----------------------------------------------------------")
+				log.Printf("\n A BUILD HAS FAILED")
+				log.Printf("\n-----------------------------------------------------------")
 			} else {
 				ui.Say(fmt.Sprintf("Build '%s' finished.", name))
 				artifacts.Lock()
@@ -220,6 +226,10 @@ func (c *BuildCommand) Run(args []string) int {
 	}
 
 	if len(errors) > 0 {
+		c.Ui.Say("\n--------------------------------------------------------")
+		c.Ui.Say("\n THERE WERE ERRORS")
+		c.Ui.Say("\n--------------------------------------------------------")
+
 		c.Ui.Machine("error-count", strconv.FormatInt(int64(len(errors)), 10))
 
 		c.Ui.Error("\n==> Some builds didn't complete successfully and had errors:")
@@ -280,6 +290,10 @@ func (c *BuildCommand) Run(args []string) int {
 				c.Ui.Say(message.String())
 			}
 		}
+
+		c.Ui.Say("\n--------------------------------------------------")
+		c.Ui.Say("\n ARTIFACTS WERE CREATED AND MISTAKES WERE MADE")
+		c.Ui.Say("\n--------------------------------------------------")
 	} else {
 		c.Ui.Say("\n==> Builds finished but no artifacts were created.")
 	}
```

However, when I `go build` or `make dev`, this code still compiles, though it shouldn't. Git shows the file as changed because it is, but my changes aren't getting into the binary.

Here is the `PACKER_LOG=1` output:

```
2019/03/06 22:36:09 Preparing build: amazon-ebs
2019/03/06 22:36:09 packer: 2019/03/06 22:36:09 Cannot copy AMI to AWS session region 'us-west-2', deleting it from `ami_regions`.
2019/03/06 22:36:10 packer: 2019/03/06 22:36:10 ansible-playbook version: 2.7.8
2019/03/06 22:36:10 Waiting on builds to complete...
2019/03/06 22:36:10 Starting build run: amazon-ebs
2019/03/06 22:36:10 Running builder: amazon-ebs
2019/03/06 22:36:10 [INFO] (telemetry) Starting builder amazon-ebs
2019/03/06 22:36:10 packer: 2019/03/06 22:36:10 Found region us-west-2
2019/03/06 22:36:13 [INFO] (telemetry) ending amazon-ebs
2019/03/06 22:36:13 ui error: Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.
2019/03/06 22:36:13 Builds completed. Waiting on interrupt barrier...
2019/03/06 22:36:13 machine readable: error-count []string{"1"}
2019/03/06 22:36:13 ui error:
==> Some builds didn't complete successfully and had errors:
2019/03/06 22:36:13 machine readable: amazon-ebs,error []string{"No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder."}
2019/03/06 22:36:13 ui error: --> amazon-ebs: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.
==> Builds finished but no artifacts were created.
2019/03/06 22:36:13 [INFO] (telemetry) Finalizing.
Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Builds finished but no artifacts were created.
2019/03/06 22:36:13 waiting for all plugin processes to complete...
2019/03/06 22:36:13 /vagrant/bin/packer: plugin process exited
2019/03/06 22:36:13 /vagrant/bin/packer: plugin process exited
2019/03/06 22:36:13 /vagrant/bin/packer: plugin process exited
```

I'm not sure if this output is helpful, but what am I missing when compiling? It should definitely fail to compile, and I don't see the messages I hardcoded in.

**Comment by SwampDragons** [comment] 2019-03-06 23:02
What's the output from `make dev`? Does it also return 0? When you run `which packer` and `packer version` what packer what do you get?

As for my guess about what's happening here... it looks like we need to instantiate the state bag before we call 

```
	session, err := b.config.Session()
	if err != nil {
		return nil, err
	}
``` 

and then put the error into the state. Let me do a quick repro and build and I'll give you a binary to try out.

**Comment by naftulikay** [comment] 2019-03-06 23:03
Output is:

```
naftuli@axel:~/devel/src/github.com/naftulikay/packer$ make dev
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'
```

Go is 1.12.

**Comment by SwampDragons** [comment] 2019-03-06 23:12
You can suppress that annoying gomodule output by setting `GO111MODULE=off` but hmm. You're completely right that this should not be building.

**Comment by SwampDragons** [comment] 2019-03-06 23:20
This is very strange; on my machine, packer exits 1 as expected:  

```
2019/03/06 15:14:28 Preparing build: amazon-ebs
2019/03/06 15:14:28 Waiting on builds to complete...
2019/03/06 15:14:28 Starting build run: amazon-ebs
2019/03/06 15:14:28 Running builder: amazon-ebs
2019/03/06 15:14:28 packer: 2019/03/06 15:14:28 Found region us-east-1
2019/03/06 15:14:33 ui error: Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.
2019/03/06 15:14:33 Builds completed. Waiting on interrupt barrier...
2019/03/06 15:14:33 machine readable: error-count []string{"1"}
2019/03/06 15:14:33 ui error:
==> Some builds didn't complete successfully and had errors:
2019/03/06 15:14:33 machine readable: amazon-ebs,error []string{"No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder."}
2019/03/06 15:14:33 ui error: --> amazon-ebs: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.
==> Builds finished but no artifacts were created.
2019/03/06 15:14:33 waiting for all plugin processes to complete...
Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Builds finished but no artifacts were created.
2019/03/06 15:14:33 /Users/mmarsh/go/bin/packer: plugin process exited
2019/03/06 15:14:33 /Users/mmarsh/go/bin/packer: plugin process exited
2019/03/06 15:14:33 /Users/mmarsh/go/bin/packer: plugin process exited
 ✘ mmarsh@Megans-MBP  ~/dev/repro_cases  echo $?
1
```

I can't reproduce on my linux vm either.  I still get an exit code of 1.  Are you sure there's not a wrapping script that is eating your exit code?

**Comment by naftulikay** [comment] 2019-03-06 23:28
I'm executing my Packer builds from a Makefile:

```make
build-test-xenial: init
	@$(PACKER) build \
			-var 'ami_regions=us-west-2' \
			-var 'datadog_api_key=$(DATADOG_API_KEY)' \
			-var 'git_branch=$(GIT_BRANCH)' \
			-var 'git_commit=$(GIT_COMMIT)' \
			-var 'git_commit_short=$(GIT_COMMIT_SHORT)' \
			-var 'release_type=unstable' \
			-var 'test=true' \
			$(DEBUG_FLAG) \
			$(COLOR_FLAG) \
		packer.json | tee logs/xenial/test/build.log
	@bin/disassemble-amis
```

Because #4558 won't ever happen, I stream my output to a file and parse that file to extract the built region to AMI ID mappings and then disassemble the AMIs manually.

`tee` is swallowing the return code and returning 0 always. TIL. Prefixing the command with `set -o pipefail; ...` fixes the issue. Sorry for the trouble!

Any idea why I'm not seeing build changes though?

**Comment by SwampDragons** [comment] 2019-03-07 00:17
> tee is swallowing the return code and returning 0 always. TIL. Prefixing the command with set -o pipefail; ... fixes the issue. 

Huh, I didn't know that either!  Glad you've found the solution.

I'm not sure why you're seeing that behavior with build. I'm going to guess that there's something going on with your vendoring situation that's causing go install to short circuit rather than rebuild Packer... but without sitting down at your terminal I'm pretty sure I'll be terrible at helping you debug.  

Are you doing this outside of a go workspace? It could be failing if you aren't on your gopath: 

> Second, if you are compiling a Go program not in a work space, you can use a relative path in an import statement in that program to refer to nearby code also not in a work space. This makes it easy to experiment with small multipackage programs outside of the usual work spaces, but such programs cannot be installed with "go install" (there is no work space in which to install them), so they are rebuilt from scratch each time they are built. To avoid ambiguity, Go programs cannot use relative import paths within a work space.

**Comment by SwampDragons** [comment] 2019-03-07 00:18
I'm going to close this issue since we've figured out your original problem, but if you still can't get this to build can you reach out to the mailing list?  https://groups.google.com/forum/#!forum/packer-tool

**Closed by SwampDragons** 2019-03-07 00:18 UTC

**Comment by naftulikay** [comment] 2019-03-07 00:46
Will do, thanks!
