### ISSUE TITLE
Packer 1.5.0 and 1.5.1 cannot start vpshere-iso

### ISSUE THREAD

**Issue by DevOpsJunior** [hashicorp/packer#8532] opened 2019-12-23 07:09 UTC
#### Overview of the Issue

Newest versions of Packer - 1.5.0 and 1.5.1 don't work with vsphere-iso builder

#### Reproduction Steps

1. Trying to build Ubuntu 18.04 template with Packer 1.5.0 and 1.5.1 using vsphere-iso 2.3 - error
2. Installed earlier version 1.4.5 - issues with uploading the ISO
3. Installed earlier version 1.3.5 - managed to build the template successfully. However, preseeding file did not load properly, so I had to manually configure the Ubuntu OS.

### Packer version
1.5.0
1.5.1

### Simplified Packer Build-file

"builders": [
    {
      "type": "vsphere-iso",

### Operating system and Environment details

Windows 10

### Log Fragments and crash.log files

Failed to initialize build 'vsphere-iso': error initializing builder 'vsphere-iso': exec: "C:\\Packer": file does not exist

==> Builds finished but no artifacts were created.

**Comment by drewbowering** [comment] 2019-12-30 16:22
I get the same result with "vsphere-clone", also on Windows 10.

**Comment by nilic** [comment] 2020-01-03 13:32
Same issue with Packer 1.5.1 on CentOS 7.

**Comment by SwampDragons** [comment] 2020-01-06 20:12
v1.5.0 contains an API change which requires third party plugins to be updated. My understanding is that the vSphere iso plugin is essentially unmaintained at the moment. We're working on taking over ownership of the plugin, but until then, you'll have to just use v 1.4.5 or lower.

**Comment by jefftp** [comment] 2020-01-13 15:07
Pull https://github.com/hashicorp/packer/pull/8480 is where vsphere builders are being merged into packer for those following this bug.

**Comment by SwampDragons** [comment] 2020-01-13 23:58
Do the builds at https://circleci.com/gh/hashicorp/packer/26799#artifacts/containers/0 work for y'all?  (this is the build of the branch that @jefftp linked above)

**Comment by drewbowering** [comment] 2020-01-14 16:22
Hi,

I'm still seeing a similar result with this new build (Windows version). Using the same JSON specifications that work under 1.4.5 I see:

PS C:\local\dev\images\windows\stage1> C:\local\app\packer.exe version
Packer v1.5.2-dev
PS C:\local\dev\images\windows\stage1> c:\local\app\packer.exe validate -var-file='..\..\env-dev.json' -var-file='.\win10-ltsc.json' .\windows.json
Failed to initialize build 'vsphere-iso': error initializing builder 'vsphere-iso': exec: "C:\\local\\app": file does not exist

Thanks for all of your work on this! Please let me know if there's anything else I can do to help.

**Comment by SwampDragons** [comment] 2020-01-14 18:23
@drewbowering have you removed the vsphere-iso third party plugin from your .plugins folder or wherever you have it stored? This new build has it built right into the Packer core but if it's still installed on your computer separately Packer will give the non-built-in one preference.

**Comment by drewbowering** [comment] 2020-01-14 19:38
@SwampDragons: No, I hadn't. That was the problem. However now that I have, I'm seeing this:

    PS C:\local\dev\images\windows\stage1> c:\local\app\packer.exe validate -var-file='..\..\env-dev.json' -var-file='.\win10-ltsc.json' .\windows.json
    Failed to initialize build 'vsphere-iso': error initializing builder 'vsphere-iso': Unknown builder vsphere-iso

Is there anything else I should be doing?

Thanks!

**Comment by SwampDragons** [comment] 2020-01-15 18:54
That's very odd. I can't reproduce. I don't think the issue is a .packerconfig that's still pointing to the third party plugin, since we have a bug in config loading now that would be causing a different error. What do you get if you set env var `PACKER_LOG=1`?

**Comment by drewbowering** [comment] 2020-01-15 21:58
I see what happened. The artifact linked above was for PR #8551, not #8480. Earlier today I actually pulled down the repository and compiled the merge-vsphere-builder branch myself, and that worked perfectly.

Thanks!

**Comment by SwampDragons** [comment] 2020-01-15 22:11
Wonderful!

**Closed** 2020-01-15 22:11 UTC
Labels: bug

**Comment by mschoenly** [comment] 2020-01-17 16:49
I compiled and this is working perfectly (vphsere-iso), thanks to everyone!

**Comment by SwampDragons** [comment] 2020-01-17 20:43
This is also available as a nightly build, for those of you who don't want to have to compile your own binary: https://github.com/hashicorp/packer/releases/tag/nightly

**Comment by andyfisher100** [comment] 2020-02-12 11:28
When is the nightly going to be released into an actual version?

**Comment by azr** [comment] 2020-02-12 15:30
@andyfisher100, soon ! We are freezing the merges and this should happen soon-ish.
