### ISSUE TITLE
VMWare Workstation provisiones limits floppy size to 1.4MB

### ISSUE THREAD

**Issue by molant** [hashicorp/packer#5789] opened 2018-01-12 18:31 UTC
I have the following in my VMWare template: 

```json
"floppy_files": [
        "answer_files/7/autounattend.xml",
        "floppy/common/preprovisioner.cmd",
        "floppy/bginfo/bgconfig.bgi",
        "floppy/eula/win7/eula.txt",
        "floppy/common/setautologon.ps1",
        "floppy/build.cfg",
        "floppy/openssh/openssh.ps1",
        "floppy/updates/win-updates.ps1",
        "floppy/common/post-win-updates.ps1",
        "floppy/common/finish-actions.ps1",
        "floppy/updates/microsoft-updates.bat",
        "floppy/common/preprovisioner.ps1",
        "floppy/bginfo/install.vbs",
        "floppy/bginfo/background.jpg",
        "floppy/homepage/browser-homepage.ps1",
        "floppy/winrm/start-winrm.ps1",
        "floppy/winrm/config-winrm.cmd",
        "floppy/bginfo/Bginfo.exe"
      ]
```

And a floppy disk was created with all the files even if the size was bigger than 1.4MB. This actually works for other provisiones like VBox, HyperV and Parallels.
With VMWare we are limited to a maximum of 1.4MB. Once the floppy reaches this size the remaining files will not be added.

This was working before, although I don't know if the problem is because I updated to VMWare Workstation 14 or a regression in Packer (I updated both recently :( )

**Comment by molant** [comment] 2018-01-16 17:04
@mwhooker do you want me to share the full template and the files? Most of the things should be in https://github.com/MicrosoftEdge/dev.microsoftedge.com-vms but getting all the dependencies installed can take a bit.

**Comment by SwampDragons** [comment] 2018-01-16 17:48
Yeah, if you want us to look into this, we first need a full repro case that we can launch and run ourselves without a ton of guesswork on our side.  Preferably as simple as possible while still being able to reproduce the original issue.

**Comment by arizvisa** [comment] 2018-01-19 20:04
Hi @molant, I worked on some of those parts that you're using. When you run packer, you can set some environment variables to see exactly what's going on. You'll want `PACKER_LOG=1` and `PACKER_LOG_PATH=/path/where/you/want/to/save/log` to be set before you run packer. That log will greatly assist troubleshooting things.

Do you mind checking that adding files that total larger than 1.44mb really works on Virtualbox again? And if so, can you send that floppy disk file to me? You can find the path to that floppy disk in the log, right after the `iso_url` is transferred.

Testing against Virtualbox seems to not reproduce the issue for me (it fails silently), but that's because there's always been a hard limit of 1.44mb on the floppy disk due to the way the floppy disk step sets it up. [common/step_create_floppy.go:55](../blob/master/common/step_create_floppy.go#L55)

**Comment by arizvisa** [comment] 2018-01-19 20:05
Also, PR #5802 ensures that failure to add a file to the floppy as a result of disk size will fail hard instead of silently as it had been doing before.

**Comment by molant** [comment] 2018-01-23 00:00
I'm testing with VirtualBox with the same files and for whatever reason the floppy file gets created with all the contents while with VMWare is not the case anymore.

[template-and-floppies.zip](https://github.com/hashicorp/packer/files/1653999/template-and-floppies.zip)

In the zip file you'll find:
* the template I've used for VMWare and VirtualBox
* the floppy for VMWare
* the floppy for VirtualBox.

The output of VMWare when I start the process is:
```text
==> vmware-iso: Creating floppy disk...
    vmware-iso: Copying files flatly from floppy_files
    vmware-iso: Copying file: answer_files/7/autounattend.xml
    vmware-iso: Copying file: floppy/common/preprovisioner.cmd
    vmware-iso: Copying file: floppy/bginfo/bgconfig.bgi
    vmware-iso: Copying file: floppy/eula/win7/eula.txt
    vmware-iso: Copying file: floppy/common/setautologon.ps1
    vmware-iso: Copying file: floppy/build.cfg
    vmware-iso: Copying file: floppy/openssh/openssh.ps1
    vmware-iso: Copying file: floppy/updates/win-updates.ps1
    vmware-iso: Copying file: floppy/common/post-win-updates.ps1
    vmware-iso: Copying file: floppy/common/finish-actions.ps1
    vmware-iso: Copying file: floppy/updates/microsoft-updates.bat
    vmware-iso: Copying file: floppy/common/preprovisioner.ps1
    vmware-iso: Copying file: floppy/bginfo/Bginfo.exe
    vmware-iso: Copying file: floppy/bginfo/install.vbs
    vmware-iso: Copying file: floppy/bginfo/background.jpg
    vmware-iso: Copying file: floppy/homepage/browser-homepage.ps1
    vmware-iso: Copying file: floppy/winrm/start-winrm.ps1
    vmware-iso: Copying file: floppy/winrm/config-winrm.cmd
    vmware-iso: Done copying files from floppy_files
    vmware-iso: Collecting paths from floppy_dirs
    vmware-iso: Resulting paths from floppy_dirs : []
    vmware-iso: Done copying paths from floppy_dirs
```

And for VirtualBox: 
```text
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: floppy/common/setautologon.ps1
    virtualbox-iso: Copying file: floppy/build.cfg
    virtualbox-iso: Copying file: floppy/openssh/openssh.ps1
    virtualbox-iso: Copying file: floppy/updates/win-updates.ps1
    virtualbox-iso: Copying file: floppy/common/post-win-updates.ps1
    virtualbox-iso: Copying file: floppy/common/finish-actions.ps1
    virtualbox-iso: Copying file: floppy/updates/microsoft-updates.bat
    virtualbox-iso: Copying file: floppy/common/preprovisioner.ps1
    virtualbox-iso: Copying file: floppy/bginfo/Bginfo.exe
    virtualbox-iso: Copying file: floppy/bginfo/install.vbs
    virtualbox-iso: Copying file: floppy/bginfo/background.jpg
    virtualbox-iso: Copying file: floppy/homepage/browser-homepage.ps1
    virtualbox-iso: Copying file: floppy/winrm/start-winrm.ps1
    virtualbox-iso: Copying file: floppy/winrm/config-winrm.cmd
    virtualbox-iso: Copying file: answer_files/7/autounattend.xml
    virtualbox-iso: Copying file: floppy/common/preprovisioner.cmd
    virtualbox-iso: Copying file: floppy/bginfo/bgconfig.bgi
    virtualbox-iso: Copying file: floppy/eula/win7/eula.txt
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
```

In the output there are already more files even though the template has the same one for both.

We've been using for a while these templates to create IE and Edge VMs in https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/. And floppy size hasn't been a problem until now. Maybe the other platforms do some type of compression or something has changed in the latest VMWare version?

In any case, please let me know if there's something else I can do to help.

Thanks!

**Comment by arizvisa** [comment] 2018-01-23 22:10
Hiya @molant, I took a look at those floppy images. Other than both of them having the same image file size of `1.44mb`, a lot of the files appear different. The total size of all the files on the VirtualBox floppy are `966k` which isn't larger than `1.44mb` as you had described in this issue. However, the VMware floppy is `1.5mb` which is what is expected. (This was done with both `du` and `dir /w`.)

One of the things that stands out is that SysInternals' `BGINFO.EXE` is about `828k` on the VirtualBox floppy, but significantly larger on the VMware floppy. Are both of these files intended to be the same contents/size? (btw, sha256 for vbox `bginfo.exe` is `0362cd6e7b318ab9a4c74daf229f11bb795a2ce553ea024cb49143456c27c41d`, and latest `bginfo.exe` from SysInternals should be ~`3mb`).

Do you have any floppy disk images (made with packer under parallels, hyper-v, etc) that're larger than `1.44mb` and the checksums match?

Prior to the PR #5802, any filesystem-full errors weren't being notified to the user and so packer was failing silently while trying to write any files that'd fit. This'd result in it appearing as if files were written correctly to the floppy once the disk size was met, but in all actuality it hasn't.

I'd double-check the hashes of the files to see if they're truly the same between the VM types. The floppy-disk step in packer has had the maximum size of the floppy disk image set to `1.44mb` since 2013, and due to the way the fat filesystem works, this size is used to calculate the number of clusters avail on the disk which is needed in order to identify where the fs needs to write file contents.

**Comment by molant** [comment] 2018-01-23 22:24
The size of `bginfo.exe` could be the problem. For whatever reason I though I was using the same in both machines but it looks the bigger one is the latest. I'm starting the process again and let you know what happens.

Thanks!

**Comment by arizvisa** [comment] 2018-01-23 22:33
Yea, both the builders use the exact same code. So, one builder treating the floppy disk image differently from another builder would be completely unintentional functionality.

**Comment by mwhooker** [comment] 2018-01-23 22:48
Gonna close this for now. @molant if you do some further investigating and discover a bug, I'll reopen it.

Thanks for digging in @arizvisa

**Closed by mwhooker** 2018-01-23 22:48 UTC
Labels: builder/vmware, need-repro
