### ISSUE TITLE
amazon-ebs builder timeout error for AWS API endpoints

### ISSUE THREAD

**Issue by ranjb** [hashicorp/packer#6162] opened 2018-04-19 13:38 UTC
The amazon-ebs builder randomly times out when interacting with the AWS API. This can happen at any stage during the build, either at the beginning or at the end after the AMI is created and packer is trying to shut down the instance or sometimes when attempting to tag the AMI etc. The build script runs more than one packer build in sequence and sometimes the first one builds fine while it times out on the second or sometimes it fails right at the beginning of the first.

Example:
--> amazon-ebs: Error stopping instance: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp 54.239.28.176:443: i/o timeout

- Packer version 1.2.2
- Host platform: AWS Ubuntu 14.04 Docker container running on AWS via AWS CodeBuild
- Debug log using PACKER_LOG=1
https://gist.github.com/ranjb/cf8bd0d93242d4a935854acf2c4514de

**Comment by SwampDragons** [comment] 2018-06-08 22:30
Can you test out the build linked above in #6365 and let me know if it improves this timeout situation?

**Comment by daxgames** [comment] 2018-06-15 07:12
I am seeing this pretty frequently also.

**Comment by SwampDragons** [comment] 2018-06-15 16:10
@daxgames would love your input on whether the linked build solves your issues.

**Comment by daxgames** [comment] 2018-06-15 18:02
I will try it and report back.

**Comment by daxgames** [comment] 2018-06-15 18:37
I only did this one time but I get the below as its tagging the AMI snapshot using the linked version.  All was OK up until then.  This particular build had never had any issues.  

```
==> AMI Build: Creating snapshot tags
==> AMI Build: Terminating the source AWS instance...
==> AMI Build: Cleaning up any extra volumes...
==> AMI Build: Destroying volume (vol-0ffbe49dff093a2f3)...
==> AMI Build: Deleting temporary security group...
Build 'AMI Build' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> AMI Build: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2018/06/15 18:28:33 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc45b88]
2018/06/15 18:28:33 packer: 
2018/06/15 18:28:33 packer: goroutine 51 [running]:
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/builder/amazon/common.(*StepCreateTags).Run.func1(0x0, 0x0, 0xc42040a000, 0x6)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/builder/amazon/common/step_create_tags.go:104 +0x378
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/common.Retry(0x3fc999999999999a, 0x403e000000000000, 0xb, 0xc420136b00, 0xc42057a0e0, 0x0)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/common/retry.go:38 +0xb7
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/builder/amazon/common.(*StepCreateTags).Run(0xc4201f2070, 0x2478820, 0xc4201934c0, 0x2476920, 0xc42068a990, 0xc42057c080)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/builder/amazon/common/step_create_tags.go:93 +0x930
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/common.abortStep.Run(0x246b460, 0xc4201f2070, 0x247b420, 0xc42057a0e0, 0x2478820, 0xc4201934c0, 0x2476920, 0xc42068a990, 0xc42068a998)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/common/multistep_runner.go:70 +0x59
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc420193480, 0x2476920, 0xc42068a990)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/helper/multistep/basic_runner.go:72 +0x22f
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/builder/amazon/ebs.(*Builder).Run(0xc4200e8b00, 0x247b420, 0xc42057a0e0, 0x246efa0, 0xc420578090, 0x2478ba0, 0xc42000c030, 0x4b9d2c, 0x1bd8ac0, 0x1bd8ac0, ...)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/builder/amazon/ebs/builder.go:260 +0x15ec
2018/06/15 18:28:33 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc4202554e0, 0x1, 0xc4200421e0, 0x0, 0x0)
2018/06/15 18:28:33 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:94 +0x1ce
2018/06/15 18:28:33 packer: reflect.Value.call(0xc42009d5c0, 0xc42000c738, 0x13, 0x2270a74, 0x4, 0xc42008af18, 0x3, 0x3, 0xc420192540, 0xc420528f88, ...)
2018/06/15 18:28:33 packer: 	/usr/local/go/src/reflect/value.go:447 +0x969
2018/06/15 18:28:33 packer: reflect.Value.Call(0xc42009d5c0, 0xc42000c738, 0x13, 0xc420521718, 0x3, 0x3, 0x1, 0x70409e, 0x1)
2018/06/15 18:28:33 packer: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2018/06/15 18:28:33 packer: net/rpc.(*service).call(0xc4201eee00, 0xc4200a9590, 0xc4202c6468, 0xc4202c6470, 0xc420137080, 0xc42018e8a0, 0x1c3d420, 0xc4200421bc, 0x18a, 0x1bd8ac0, ...)
2018/06/15 18:28:33 packer: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2018/06/15 18:28:33 packer: created by net/rpc.(*Server).ServeCodec
2018/06/15 18:28:33 packer: 	/usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/06/15 18:28:33 [INFO] (telemetry) ending amazon-ebs
2018/06/15 18:28:33 ui error: Build 'AMI Build' errored: unexpected EOF
2018/06/15 18:28:33 Builds completed. Waiting on interrupt barrier...
2018/06/15 18:28:33 machine readable: error-count []string{"1"}
2018/06/15 18:28:33 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/06/15 18:28:33 machine readable: AMI Build,error []string{"unexpected EOF"}
2018/06/15 18:28:33 ui error: --> AMI Build: unexpected EOF
2018/06/15 18:28:33 ui: 
==> Builds finished but no artifacts were created.
2018/06/15 18:28:33 /var/jenkins_home/userContent/packerfiles/packer_1.2.4.1/packer: plugin process exited
2018/06/15 18:28:33 [INFO] (telemetry) Finalizing.
2018/06/15 18:28:33 waiting for all plugin processes to complete...
2018/06/15 18:28:33 /var/jenkins_home/userContent/packerfiles/packer_1.2.4.1/packer: plugin process exited
2018/06/15 18:28:33 /var/jenkins_home/userContent/packerfiles/packer_1.2.4.1/packer: plugin process exited
2018/06/15 18:28:33 /var/jenkins_home/userContent/packerfiles/packer_1.2.4.1/packer: plugin process exited
2018/06/15 18:28:33 /var/jenkins_home/userContent/packerfiles/packer_1.2.4.1/packer: plugin process exited
2018/06/15 18:28:33 /var/jenkins_home/userContent/packerfiles/packer_1.2.4.1/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by SwampDragons** [comment] 2018-06-15 21:56
bummer. I'll take a closer look when I get a chance. Thanks for trying it out.

**Comment by SwampDragons** [comment] 2019-07-30 18:36
Is this still an issue?

**Comment by ranjb** [comment] 2019-07-30 19:41
I have not had a chance to test this again, it was on a client environment.
Has something changed specifically in Packer/AWS that would address this? I
can try later in the week as I need to replicate setup.

**Comment by SwampDragons** [comment] 2019-07-30 20:07
We've made a fair number of changes; nothing I know would explicitly address this but I just realized it's been a year since I looked at this and you never know.

**Comment by GregorySWI** [comment] 2019-08-03 00:34
I am still seeing this on packer 1.4.2:

`2019-08-02T20:20:06-04:00: ==> amazon-ebs: Stopping the source instance...
2019-08-02T20:20:06-04:00:     amazon-ebs: Stopping instance
2019-08-02T20:20:07-04:00: ==> amazon-ebs: Waiting for the instance to stop...
2019-08-02T20:20:23-04:00: ==> amazon-ebs: Enabling Enhanced Networking (SR-IOV)...
2019-08-02T20:20:23-04:00: ==> amazon-ebs: Enabling Enhanced Networking (ENA)...
2019-08-02T20:20:44-04:00: ==> amazon-ebs: Error describing AMI: RequestError: send request failed
==> amazon-ebs: caused by: Post https://ec2.ap-east-1.amazonaws.com/: dial tcp 13.248.36.100:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2019-08-02T20:20:44-04:00: ==> amazon-ebs: Terminating the source AWS instance...
2019-08-02T20:21:00-04:00: ==> amazon-ebs: Cleaning up any extra volumes...
2019-08-02T20:21:00-04:00: ==> amazon-ebs: No volumes to clean up, skipping
2019-08-02T20:21:00-04:00: Build 'amazon-ebs' errored: Error describing AMI: RequestError: send request failed
caused by: Post https://ec2.ap-east-1.amazonaws.com/: dial tcp 13.248.36.100:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error describing AMI: RequestError: send request failed
caused by: Post https://ec2.ap-east-1.amazonaws.com/: dial tcp 13.248.36.100:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

==> Builds finished but no artifacts were created.`

Everything up to this point worked. I ran the QA version of this build yesterday and had no issues:

`2019-08-01T17:08:06-04:00: ==> amazon-ebs: Stopping the source instance...
2019-08-01T17:08:06-04:00:     amazon-ebs: Stopping instance
2019-08-01T17:08:07-04:00: ==> amazon-ebs: Waiting for the instance to stop...
2019-08-01T17:08:22-04:00: ==> amazon-ebs: Enabling Enhanced Networking (SR-IOV)...
2019-08-01T17:08:22-04:00: ==> amazon-ebs: Enabling Enhanced Networking (ENA)...
2019-08-01T17:08:23-04:00: ==> amazon-ebs: Creating AMI My Awesome AMI from instance i-xxxxxxxxxxxxxxxx
2019-08-01T17:08:23-04:00:     amazon-ebs: AMI: ami-xxxxxxxxxxxxxxxxxxxx`


The only change I can think of, was due to an earlier failure of the release AMI build (due to querying AWS for the region list before passing it to packer), I added access to the new ap-east-1 region in AWS.

**Comment by GregorySWI** [comment] 2019-08-04 02:20
Filtering ap-east-1 from the regions list fixes this issue.

**Comment by lmeyerov** [comment] 2019-10-22 20:23
Seeing something similar during otherwise-ok stopping sequence:

```
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Error stopping instance: RequestError: send request failed
==> amazon-ebs: caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout
==> amazon-ebs: caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error stopping instance: RequestError: send request failed
2019/10/22 20:08:30 [INFO] (telemetry) ending amazon-ebs

caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout
2019/10/22 20:08:30 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2019/10/22 20:08:30 machine readable: amazon-ebs,error []string{"Error stopping instance: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout"}
caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout
==> Builds finished but no artifacts were created.
caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error stopping instance: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 168.63.129.16:53: read udp 10.1.0.4:45443->168.63.129.16:53: i/o timeout

==> Builds finished but no artifacts were created.
2019/10/22 20:08:30 [INFO] (telemetry) Finalizing.
2019/10/22 20:08:31 waiting for all plugin processes to complete...
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
2019/10/22 20:08:31 /usr/local/bin/packer: plugin process exited
+ echo exit code 1
+ grep 'exit code 0'
+ echo 'ERROR: PACKER FAIL'
+ exit 1
ERROR: PACKER FAIL

```

Builder:

```
            "instance_type": "p3.2xlarge",
            "region": "us-east-1",
            "ebs_optimized": true,
```

Seems to be `udp` instead of `tcp` though

**Comment by lmeyerov** [comment] 2019-10-23 05:09
Ah ^^^ may be on our side of azure->aws (or just ->aws) connectivity. May be useful to have packer provide helpful messages around networking issues.

**Comment by yomesky2000** [comment] 2020-02-27 23:59
packer build  template.json
amazon-ebs: output will be in this color.

Build 'amazon-ebs' errored: error validating regions: RequestError: send request failed
caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.com on 172.31.0.2:53: no such host

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: error validating regions: RequestError: send request failed
caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.com on 172.31.0.2:53: no such host



i need help resolving this error

**Comment by GregorySWI** [comment] 2020-02-28 14:17
> 
> 
> packer build template.json
> amazon-ebs: output will be in this color.
> 
> Build 'amazon-ebs' errored: error validating regions: RequestError: send request failed
> caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.com on 172.31.0.2:53: no such host
> 
> ==> Some builds didn't complete successfully and had errors:
> --> amazon-ebs: error validating regions: RequestError: send request failed
> caused by: Post https://ec2.us%E2%88%92east%E2%88%921.amazonaws.com/: dial tcp: lookup ec2.xn--useast1-oe0de.amazonaws.com on 172.31.0.2:53: no such host
> 
> i need help resolving this error

--> ec2.xn--useast1-oe0de.amazonaws.com on 172.31.0.2:53: no such host
I don't believe the extended domain names are supported for Packer, or many other tools. Can you use an ASCII url? it's the "xn--useast1-oe0de" part it is choking on I believe.

**Closed** 2021-03-29 11:20 UTC
Labels: bug, builder/amazon, remote-plugin/amazon
