### ISSUE TITLE
AMI Created by packer encountering DNS/Networking issues with T2 instances. 

### ISSUE THREAD

**Issue by athmacharan** [hashicorp/packer#10618] opened 2021-02-12 12:28 UTC
Environment Details:

Packer 1.5.6
CentOS 7.8
AWS Cloud Enviornment.
Oracle Virtual Box

I've create an AMI using Centos 7.8 ISO and virtualbox-iso builder. If I create an EC2 instance with T3 and above type I can resolve the external hosts, however if I use T2 type it can't resolve the external hosts.

$curl google.com
curl: (6) Could not resolve host: google.com; Unknown error

If I restart the newtork maganer service I am able to resolve the external hosts, but If I reboot the EC2 then the issue comes back.

Thanks,
charan

**Comment by SwampDragons** [comment] 2021-02-17 22:25
Hi, thanks for reaching out. 

If nothing changes between the working and failing instances other than the instance type, this doesn't sound like a Packer issue to me. It sounds like something about your image is causing your T2 instance to bump against its CPU or other limitations.

This docs page may be relevant to you, also: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/

Since I don't think there's anything the Packer team can do, I'm going to close this. If you think I'm wrong, please share the minimal Packer template and other steps required to reproduce so we can investigate, and we can reopen.

**Closed by SwampDragons** 2021-02-17 22:25 UTC
Labels: bug
