### ISSUE TITLE
puppet-server provision

### ISSUE THREAD

**Issue by gangadhar01a** [hashicorp/packer#4951] opened 2017-06-01 18:10 UTC
I am running packer on CentOS and using "puppet server" provision to connect to the puppet master

"{
    "type": "puppet-server",
    "client_cert_path": "/home/parallels/Desktop/public-key",
    "client_private_key_path": "/home/parallels/Desktop/private-key",
    "puppet_server": "devops-puppet1.hautelook.com",
    "puppet_bin_dir": "C:\\Program Files\\Puppet Labs\\Puppet\\bin"
  }"

Packer build shows the following error

"==> azure-arm: Provisioning with Puppet...
    azure-arm: Creating Puppet staging directory...
    azure-arm: The syntax of the command is incorrect."

I haven't provided the staging directory path in my code and the documentation says the default path with for the Staging directory will be /tmp/packer-puppet-server. I am trying to create an image with windows OS. 
Is this an internal bug? or anything wrong with my code?

Packer version: 1.0.0
OS:CentOS 7

**Comment by mwhooker** [comment] 2017-06-01 18:21
this is a dupe of #2566 

I'm sorry this isn't working, puppet on windows is not well supported. You can try setting your `staging_dir` to a windows path, but this may not work because the provisioner tries to call `mkdir` on it.

If you're unable to get this to work, I would suggest using the file and powershell provisioners to upload your puppet files and then run puppet client

**Closed by mwhooker** 2017-06-01 18:21 UTC
