### ISSUE TITLE
Packer crashes with SIGSEGV Error

### ISSUE THREAD

**Issue by Wasapl** [hashicorp/packer#6847] opened 2018-10-14 18:20 UTC
Describe the problem and include the following information:
During provisioning powershell script in Azure Windows VM Packer crashes with signal SIGSEGV: segmentation violation  error:

```
==> vhd: Provisioning with powershell script: /home/appveyor/projects/packer-windows/scripts/add_ssh_known_hosts.ps1
Build 'vhd' errored: unexpected EOF
==> Some builds didn't complete successfully and had errors:
--> vhd: unexpected EOF
==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2018/10/13 20:00:49 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x65a1a6]
```

It could be any script

- Packer v1.3.1
- Host platform - MacOS 10.13.6
- Debug log output and JSON can be found here https://gist.github.com/Wasapl/c1839cb0755b30faf64481e9129d11ff

**Comment by SwampDragons** [comment] 2018-10-15 18:55
I'm not able to reproduce by just running an Azure build with multiple Powershell provisioners. I know you've said that it could be any script, but in the provisioner before it fails are you running something that forces a windows update or something like that?

**Comment by Wasapl** [comment] 2018-10-16 19:24
Oh, I think you're right - there is a couple warnings in log saying VM needs to restart. Let me double check that and I'll close issue soon.

BTW, dont you think that packer should handle such sudden reboots more nicely? Maybe error message can contain a suggestion that VM rebooting.

**Comment by SwampDragons** [comment] 2018-10-16 20:28
Unexpected reboots like this could interfere with actual provisioning scripts and prevent them from being run reliably. Packer's primary goal is to make sure that and VM you build is exactly what you wanted to build, which means it would rather fail than have an unknown outcome.

**Comment by Wasapl** [comment] 2018-10-16 21:34
Yes, but from my perspective, this failure looks like packer crash but not as a failure of VM or my provision scripts.

**Comment by SwampDragons** [comment] 2018-10-17 17:29
You know what, that's totally true, and Packer should error out more gracefully, rather than just crashing or panicing.

**Comment by SwampDragons** [comment] 2018-10-22 22:43
Looked back at this; Packer isn't crashing. If it did you'd see a big 

`!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!`
 
Instead, Packer catches the EOF, reports it, and closes down:

```
==> Some builds didn't complete successfully and had errors:
2018/10/12 12:29:40 machine readable: vhd,error []string{"unexpected EOF"}
2018/10/12 12:29:40 ui error: --> vhd: unexpected EOF
2018/10/12 12:29:40 ui: 
```

I know this looks like a crash but the EOF is outside of Packer's control. Re-closing.

**Closed by SwampDragons** 2018-10-22 22:43 UTC
Labels: builder/azure, crash, provisioner/powershell
