### ISSUE TITLE
salt-masterless provisioner failing with local_state_tree and local_pillar_roots

### ISSUE THREAD

**Issue by jim-raney-physiq** [hashicorp/packer#5292] opened 2017-08-29 17:19 UTC
Packer version: 1.0.4
Host platform: Ubuntu 16.04.3

When running the salt-masterless provisoner on a docker container using "local_state_tree" and "local_pillar_roots" the step 'salt-call --local state.highstate' is failing due to a missing top.sls file.  Inspecting the container's /srv/salt and /srv/pillar directories I see directories named "dirupload<random_number>" containing the contents of of local_pillar_roots and local_state_tree.  It appears that the contents are getting uploaded to /tmp/salt/pillar and /tmp/salt/states in some intermediate directories and those are getting moved to /srv/salt and /srv/pillar rather than the contents of those directories.

Issue isn't present in packer 1.0.3.

**Comment by SwampDragons** [comment] 2017-08-29 20:50
This is a duplicate of https://github.com/hashicorp/packer/issues/5243, and fixed on master. Apologies for the regression.

**Closed** 2017-08-29 20:51 UTC
Labels: builder/docker, duplicate, regression
