### ISSUE TITLE
packer ansible aws_s3 playbook fails during bucket_check but works in ansible

### ISSUE THREAD

**Issue by tkokev** [hashicorp/packer#8076] opened 2019-09-05 13:09 UTC
I have an Ansible `aws_s3` playbook task that works when run within ansible `ansible-playbook` command. The same playbook fails when using packer ansible provisioner with the error `"msg": "Failed while looking up bucket (during bucket_check) FOOBUCKET.: Unable to locate credentials"`.
```
$ packer --version
1.3.5
$ ansible --version
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/USER/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

```

- working in ansbile
```
$ ansible-playbook -i "x.x.x.x", -u centos playbooks/commonsoftware.yml playbooks/playbook.yml  --extra-vars 'BUCKET=FOOBUCKET'

PLAY [Add scripts] **********************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [x.x.x.x]

TASK [GET FOO.sh from S3] ***************************************************************************
changed: [x.x.x.x]

...
```
- Failing in packer
```
 $ packer build -var-file=./packer-variables.json ./packer.json
amazon-ebs output will be in this color.
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: FOO-candidate-1567688314
    amazon-ebs: Found Image ID: ami-02eac2c0129f6376b
==> amazon-ebs: Creating temporary keypair: packer_5d71067a-fedd-2b03-f5d5-8218ba6f43c1
==> amazon-ebs: Creating temporary security group for this instance: packer_5d71067c-8c50-1aae-faa5-144420508420
==> amazon-ebs: Authorizing access to port 22 from 0.0.0.0/0 in the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-08c4171bb63b21883
==> amazon-ebs: Waiting for instance (i-08c4171bb63b21883) to become ready...
==> amazon-ebs: Using ssh communicator to connect: 18.209.1.225
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with shell script: /tmp/packer-shell740194911
    amazon-ebs: Loaded plugins: fastestmirror
    amazon-ebs: Determining fastest mirrors
    amazon-ebs:  * base: mirrors.advancedhosters.com
    amazon-ebs:  * extras: mirrors.advancedhosters.com
    amazon-ebs:  * updates: mirrors.advancedhosters.com
    amazon-ebs: Resolving Dependencies
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package python-boto3.noarch 0:1.4.6-5.el7 will be installed
    amazon-ebs: --> Processing Dependency: python-s3transfer >= 0.1.10 for package: python-boto3-1.4.6-5.el7.noarch
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package python-s3transfer.noarch 0:0.1.13-1.el7.0.1 will be installed
    amazon-ebs: --> Processing Dependency: python-docutils >= 0.10 for package: python-s3transfer-0.1.13-1.el7.0.1.noarch
    amazon-ebs: --> Processing Dependency: python-dateutil >= 1.4 for package: python-s3transfer-0.1.13-1.el7.0.1.noarch
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package python-dateutil.noarch 0:1.5-7.el7 will be installed
    amazon-ebs: ---> Package python-docutils.noarch 0:0.11-0.3.20130715svn7687.el7 will be installed
    amazon-ebs: --> Processing Dependency: python-imaging for package: python-docutils-0.11-0.3.20130715svn7687.el7.noarch
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package python-pillow.x86_64 0:2.0.0-19.gitd1c6db8.el7 will be installed
    amazon-ebs: --> Processing Dependency: libtiff.so.5(LIBTIFF_4.0)(64bit) for package: python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64
    amazon-ebs: --> Processing Dependency: libjpeg.so.62(LIBJPEG_6.2)(64bit) for package: python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64
    amazon-ebs: --> Processing Dependency: libwebp.so.4()(64bit) for package: python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64
    amazon-ebs: --> Processing Dependency: libtiff.so.5()(64bit) for package: python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64
    amazon-ebs: --> Processing Dependency: libjpeg.so.62()(64bit) for package: python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package libjpeg-turbo.x86_64 0:1.2.90-6.el7 will be installed
    amazon-ebs: ---> Package libtiff.x86_64 0:4.0.3-27.el7_3 will be installed
    amazon-ebs: --> Processing Dependency: libjbig.so.2.0()(64bit) for package: libtiff-4.0.3-27.el7_3.x86_64
    amazon-ebs: ---> Package libwebp.x86_64 0:0.3.0-7.el7 will be installed
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package jbigkit-libs.x86_64 0:2.0-11.el7 will be installed
    amazon-ebs: --> Finished Dependency Resolution
    amazon-ebs:
    amazon-ebs: Dependencies Resolved
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs:  Package             Arch     Version                           Repository
    amazon-ebs:                                                                            Size
    amazon-ebs: ================================================================================
    amazon-ebs: Installing:
    amazon-ebs:  python-boto3        noarch   1.4.6-5.el7                       base      132 k
    amazon-ebs: Installing for dependencies:
    amazon-ebs:  jbigkit-libs        x86_64   2.0-11.el7                        base       46 k
    amazon-ebs:  libjpeg-turbo       x86_64   1.2.90-6.el7                      base      134 k
    amazon-ebs:  libtiff             x86_64   4.0.3-27.el7_3                    base      170 k
    amazon-ebs:  libwebp             x86_64   0.3.0-7.el7                       base      170 k
    amazon-ebs:  python-dateutil     noarch   1.5-7.el7                         base       85 k
    amazon-ebs:  python-docutils     noarch   0.11-0.3.20130715svn7687.el7      base      1.5 M
    amazon-ebs:  python-pillow       x86_64   2.0.0-19.gitd1c6db8.el7           base      438 k
    amazon-ebs:  python-s3transfer   noarch   0.1.13-1.el7.0.1                  updates   2.9 M
    amazon-ebs:
    amazon-ebs: Transaction Summary
    amazon-ebs: ================================================================================
    amazon-ebs: Install  1 Package (+8 Dependent packages)
    amazon-ebs:
    amazon-ebs: Total download size: 5.6 M
    amazon-ebs: Installed size: 38 M
    amazon-ebs: Downloading packages:
    amazon-ebs: warning: /var/cache/yum/x86_64/7/base/packages/jbigkit-libs-2.0-11.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
    amazon-ebs: Public key for jbigkit-libs-2.0-11.el7.x86_64.rpm is not installed
    amazon-ebs: Public key for python-s3transfer-0.1.13-1.el7.0.1.noarch.rpm is not installed
    amazon-ebs: --------------------------------------------------------------------------------
    amazon-ebs: Total                                               23 MB/s | 5.6 MB  00:00
    amazon-ebs: Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    amazon-ebs: Importing GPG key 0xF4A80EB5:
    amazon-ebs:  Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
    amazon-ebs:  Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
    amazon-ebs:  Package    : centos-release-7-6.1810.2.el7.centos.x86_64 (installed)
    amazon-ebs:  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    amazon-ebs: Running transaction check
    amazon-ebs: Running transaction test
    amazon-ebs: Transaction test succeeded
    amazon-ebs: Running transaction
    amazon-ebs:   Installing : libjpeg-turbo-1.2.90-6.el7.x86_64                            1/9
    amazon-ebs:   Installing : jbigkit-libs-2.0-11.el7.x86_64                               2/9
    amazon-ebs:   Installing : libtiff-4.0.3-27.el7_3.x86_64                                3/9
    amazon-ebs:   Installing : python-dateutil-1.5-7.el7.noarch                             4/9
    amazon-ebs:   Installing : libwebp-0.3.0-7.el7.x86_64                                   5/9
    amazon-ebs:   Installing : python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64                 6/9
    amazon-ebs:   Installing : python-docutils-0.11-0.3.20130715svn7687.el7.noarch          7/9
    amazon-ebs:   Installing : python-s3transfer-0.1.13-1.el7.0.1.noarch                    8/9
    amazon-ebs:   Installing : python-boto3-1.4.6-5.el7.noarch                              9/9
    amazon-ebs:   Verifying  : python-docutils-0.11-0.3.20130715svn7687.el7.noarch          1/9
    amazon-ebs:   Verifying  : libwebp-0.3.0-7.el7.x86_64                                   2/9
    amazon-ebs:   Verifying  : libtiff-4.0.3-27.el7_3.x86_64                                3/9
    amazon-ebs:   Verifying  : python-dateutil-1.5-7.el7.noarch                             4/9
    amazon-ebs:   Verifying  : python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64                 5/9
    amazon-ebs:   Verifying  : jbigkit-libs-2.0-11.el7.x86_64                               6/9
    amazon-ebs:   Verifying  : python-boto3-1.4.6-5.el7.noarch                              7/9
    amazon-ebs:   Verifying  : python-s3transfer-0.1.13-1.el7.0.1.noarch                    8/9
    amazon-ebs:   Verifying  : libjpeg-turbo-1.2.90-6.el7.x86_64                            9/9
    amazon-ebs:
    amazon-ebs: Installed:
    amazon-ebs:   python-boto3.noarch 0:1.4.6-5.el7
    amazon-ebs:
    amazon-ebs: Dependency Installed:
    amazon-ebs:   jbigkit-libs.x86_64 0:2.0-11.el7
    amazon-ebs:   libjpeg-turbo.x86_64 0:1.2.90-6.el7
    amazon-ebs:   libtiff.x86_64 0:4.0.3-27.el7_3
    amazon-ebs:   libwebp.x86_64 0:0.3.0-7.el7
    amazon-ebs:   python-dateutil.noarch 0:1.5-7.el7
    amazon-ebs:   python-docutils.noarch 0:0.11-0.3.20130715svn7687.el7
    amazon-ebs:   python-pillow.x86_64 0:2.0.0-19.gitd1c6db8.el7
    amazon-ebs:   python-s3transfer.noarch 0:0.1.13-1.el7.0.1
    amazon-ebs:
    amazon-ebs: Complete!
==> amazon-ebs: Provisioning with Ansible...
==> amazon-ebs: Executing Ansible: ansible-playbook --extra-vars packer_build_name=amazon-ebs packer_builder_type=amazon-ebs -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible386166656 /home/USER/playbooks/playbook.yml -e ansible_ssh_private_key_file=/tmp/ansible-key832661861 --extra-vars BUCKET=FOOBUCKET
    amazon-ebs:
    amazon-ebs: PLAY [Add scripts] *********************************************
    amazon-ebs:
    amazon-ebs: TASK [Gathering Facts] *********************************************************
    amazon-ebs: ok: [default]
    amazon-ebs:
    amazon-ebs: TASK [GET FOO.sh from S3] **************************************************
    amazon-ebs: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoCredentialsError: Unable to locate credentials
    amazon-ebs: fatal: [default]: FAILED! => {"boto3_version": "1.4.6", "botocore_version": "1.8.35", "changed": false, "msg": "Failed while looking up bucket (during bucket_check) FOOBUCKET.: Unable to locate credentials"}
    amazon-ebs:
    amazon-ebs: PLAY RECAP *********************************************************************
    amazon-ebs: default                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    amazon-ebs:
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-06eb50cbaf630742a)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error executing Ansible: Non-zero exit status: exit status 2

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error executing Ansible: Non-zero exit status: exit status 2

==> Builds finished but no artifacts were created.

```
- playbook commonsoftware.yml
```
- name: install common sw
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: yum install
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
# for playbook.yml playbook
        - python-boto3
```
- playbook playbook.yml
```
- name: Add scripts
  hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: GET FOO.sh from S3
    aws_s3:
      bucket: "{{ BUCKET }}"
      object: /FOO.sh
      dest: /root/FOO.sh
      mode: get
      ignore_nonexistent_bucket: true
  - name: make script executable
    file:
      path: /root/FOO.sh
      state: file
      mode: '0540'
  - name: Run script
    command: /root/FOO.sh
    args:
      warn: no
```
- packer file
```
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "aws_vpc_id": "",
    "aws_subnet_id": "",
    "aws_region": "",
    "aws_instance_type": "",
    "aws_user": "",
    "aws_iam_profile": "",
    "aws_ca_bundle": "",
    "aws_bucket": ""
  },
  "provisioners": [
    {
      "type": "ansible",
      "user": "centos",
      "playbook_file": "./playbooks/commonsoftware.yml",
    },
    {
      "type": "ansible",
      "user": "centos",
      "playbook_file": "./playbooks/playbook.yml",
      "extra_arguments": [ "--extra-vars", "BUCKET={{user `aws_bucket`}}"]
    }
  ],
  "builders": [{
    "type": "amazon-ebs",
    "vpc_id": "{{user `aws_vpc_id`}}",
    "subnet_id": "{{user `aws_subnet_id`}}",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "{{ user `aws_region`}}",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-05713873c6794f575.4",
        "root-device-type": "ebs"
      },
      "owners": ["679593333241"],
      "most_recent": true
    },
    "instance_type": "{{user `aws_instance_type`}}",
    "ssh_username": "{{user `aws_user`}}",
    "ami_name": "FOO-candidate-{{timestamp}}"
  }]
}
```
- packer vars file packer-vars.json
```
{
  "aws_vpc_id": "vpc-FOO",
  "aws_subnet_id": "subnet-FOO",
  "aws_region": "us-east-1",
  "aws_instance_type": "t2.medium",
  "aws_user": "centos",
  "aws_ca_bundle": "/etc/pki/tls/certs/ca-bundle.crt",
  "aws_bucket": "FOOBUCKET"
}
```

My employer prevents custom s3 bucket policies (like granting top level bucket list permissions) so was happy [ansible issue #30028](https://github.com/ansible/ansible/issues/30028) addresses that problem but wondering if it isn't being honored by packer. Or maybe this is just a matter of an additional environment variable needing set (or one needing unset) in my packer json?

**Comment by SwampDragons** [comment] 2019-09-05 17:53
Thanks for reaching out -- the ansible provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it; that said, I don't think that Packer does anything with AWS buckets when it comes to using ansible.  I'd recommend trying running with the --debug flag, and then calling the command as logged by packer: 

`ansible-playbook --extra-vars packer_build_name=amazon-ebs packer_builder_type=amazon-ebs -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible386166656 /home/USER/playbooks/playbook.yml -e ansible_ssh_private_key_file=/tmp/ansible-key832661861 --extra-vars BUCKET=FOOBUCKET
    amazon-ebs:` 

It may shed some light on where the issue is.

**Comment by tkokev** [comment] 2019-09-05 18:31
Thanks @SwampDragons! I'll try that and see what tidbits I can learn. Is there another community driven git repo for that provisioner I should have posted this in?

**Comment by SwampDragons** [comment] 2019-09-05 22:41
No, you're in the right place. Changes to the provisioner are made here, we just depend on the community to do it and to make the PRs rather than being likely to dedicate the time to debugging ourselves.

**Comment by rickard-von-essen** [comment] 2019-09-06 18:26
How are the credentials resolved when you run ansible without Packer?

**Comment by tkokev** [comment] 2019-09-06 21:13
@rickard-von-essen A policy condition on the private S3 bucket permits the VPC's entire CIDR to `S3:GetObject` the specific script. Snippet of policy below.
```
...
        {
            "Action": "s3:GetObject",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "X.X.0.0/Y"
                }
            },
            "Effect": "Allow",
            "Principal": "*",
            "Resource": "arn:aws:s3:::FOOBUCKET/FOO.sh",
            "Sid": "GetScript"
        },
...
```

**Comment by rickard-von-essen** [comment] 2019-09-07 07:40
I was more referring to how the secret access key was resolved. If you are using `AWS_` environment variables, `~/.aws/credentials`, EC2 instance profile etc.

**Comment by tkokev** [comment] 2019-09-09 16:18
It is hard to say. If I can rely on the CentOS ami-02eac2c0129f6376b makers to have stock settings for their `centos` user profile in their AMI, then I would expect the AWS CLI should fault to dynamically set the environment variables based on AWS iam ec2 profile creds since I'm not altering `awscli` (or `python-boto3`) package post install.  But in this case we are running the instance without an IAM ec2 profile so wouldn't expect the `AWS_` variables to be set. It still confuses me that when running the playbooks directly by ansible instead of as a packer ansible provisioner this works.

If I have some time soon I suppose I could insert an `aws configure list` in the playbook to get an idea of how the env var's are getting set.

**Comment by SwampDragons** [comment] 2020-04-02 21:03
Another possibility:  I don't think the CLI sets env vars for you. Have you tried setting the "ansible_env_vars" with your AWS credentials? That could definitely be a reason it works for one but not the other; the env you're in when directly running Ansible may have values that the env Packer creates for Ansible doesn't have.

**Comment by SwampDragons** [comment] 2020-08-13 19:27
Closing since I never heard back on this issue. Hopefully the ansible_env_vars solution did the trick. Otherwise, we can reopen and continue to investigate.

**Closed by SwampDragons** 2020-08-13 19:27 UTC
Labels: bug, community-supported plugin, provisioner/ansible-remote, waiting-reply
