### ISSUE TITLE
Packer uses private IP (and fails) when building on C5.* instance

### ISSUE THREAD

**Issue by nyetsche** [hashicorp/packer#5627] opened 2017-11-22 18:50 UTC
I'm unable to launch and provision a `c5.large` instance type in AWS. These were recently released by AWS - https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/ and https://aws.amazon.com/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/ - and are notable that they _require_ `ena` support: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

i.e., `"ena_support": true`

When launching a `c5.large` instance, packer times out trying to SSH to the _private_ IP address in the subnet, despite a public address existing (and `"associate_public_ip_address": true` in the config). I can confirm that the public IP address is set and can connect to it via SSH without packer.

An `i3.large` instance type, also with `"ena_support": true`, is successful.

- `packer version`: 

```
$ packer --version
1.1.3
```
(built from `master`, with `HEAD` at `61d8274096e3af1173850714b7f91afe4878e432`)

- Host platform

OSX Sierra 10.12.6
```
$ go version
go version go1.9.1 darwin/amd64
```

- Gist of *unsuccessful* run - `"instance_type": "c5.large"`: https://gist.github.com/nyetsche/9ad9a667f19c6b251c9bbc1f4461c4e6

- Gist of *successful* run - "instance_type": "i3.large"`:
https://gist.github.com/nyetsche/e6624750ddbadbddd6d6476410299608

Template file that will reproduce:

`ami-c998b6b2` is RHEL7, `RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2 (ami-c998b6b2)` in `us-east-1`

```
{
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "packer-c5-ami",
      "region": "us-east-1",
      "associate_public_ip_address": true,
      "sriov_support": true,
      "ena_support": true,
      "instance_type": "c5.large",
      "ssh_username": "ec2-user",
      "ssh_pty": true,
      "ssh_timeout": "5m",
      "vpc_id": "VPC-id",
      "subnet_id": "VPC-subnet",
      "security_group_id": "SG-with-ssh",
      "source_ami": "ami-c998b6b2"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "echo SSH test successful"
      ]
    }
  ]
}
```

Change `c5.large` to `i3.large` and packer will connect successfully.

**Comment by joonaskaskisola** [comment] 2017-11-30 10:47
Also facing this issue.

**Comment by rickard-von-essen** [comment] 2017-11-30 11:07
Could you provide the output of `aws ec2 decribe-instances --instance-ids <instance-id>` for the running instance.

**Comment by joonaskaskisola** [comment] 2017-11-30 11:36
@rickard-von-essen 

```
{
    "Reservations": [
        {
            "Instances": [
                {
                    "Monitoring": {
                        "State": "disabled"
                    }, 
                    "PublicDnsName": "ec2-54-194-25-116.eu-west-1.compute.amazonaws.com", 
                    "State": {
                        "Code": 16, 
                        "Name": "running"
                    }, 
                    "EbsOptimized": false, 
                    "LaunchTime": "2017-11-30T11:33:38.000Z", 
                    "PublicIpAddress": "54.194.25.116", 
                    "PrivateIpAddress": "10.166.105.77", 
                    "ProductCodes": [], 
                    "VpcId": "vpc-XXX", 
                    "StateTransitionReason": "", 
                    "InstanceId": "i-XXX", 
                    "EnaSupport": true, 
                    "ImageId": "ami-7bd36e02", 
                    "PrivateDnsName": "ip-10-166-105-77.eu-west-1.compute.internal", 
                    "KeyName": "packer 5a1fec8f-b032-2958-12a5-07055da8dec8", 
                    "SecurityGroups": [
                        {
                            "GroupName": "packer 5a1fec91-778f-ec3b-e2e0-a5d47cb4a087", 
                            "GroupId": "sg-fa6c0881"
                        }
                    ], 
                    "ClientToken": "", 
                    "SubnetId": "subnet-XXX", 
                    "InstanceType": "c5.xlarge", 
                    "NetworkInterfaces": [
                        {
                            "Status": "in-use", 
                            "MacAddress": "02:d3:76:d1:61:78", 
                            "SourceDestCheck": true, 
                            "VpcId": "vpc-XXX", 
                            "Description": "", 
                            "NetworkInterfaceId": "eni-80b131af", 
                            "PrivateIpAddresses": [
                                {
                                    "PrivateDnsName": "ip-10-166-105-77.eu-west-1.compute.internal", 
                                    "PrivateIpAddress": "10.166.105.77", 
                                    "Primary": true, 
                                    "Association": {
                                        "PublicIp": "54.194.25.116", 
                                        "PublicDnsName": "ec2-54-194-25-116.eu-west-1.compute.amazonaws.com", 
                                        "IpOwnerId": "amazon"
                                    }
                                }
                            ], 
                            "PrivateDnsName": "ip-10-166-105-77.eu-west-1.compute.internal", 
                            "Attachment": {
                                "Status": "attached", 
                                "DeviceIndex": 0, 
                                "DeleteOnTermination": true, 
                                "AttachmentId": "eni-attach-4fe326af", 
                                "AttachTime": "2017-11-30T11:33:38.000Z"
                            }, 
                            "Groups": [
                                {
                                    "GroupName": "packer 5a1fec91-778f-ec3b-e2e0-a5d47cb4a087", 
                                    "GroupId": "sg-fa6c0881"
                                }
                            ], 
                            "Ipv6Addresses": [], 
                            "OwnerId": "XXX", 
                            "PrivateIpAddress": "10.166.105.77", 
                            "SubnetId": "subnet-XXX", 
                            "Association": {
                                "PublicIp": "54.194.25.116", 
                                "PublicDnsName": "ec2-54-194-25-116.eu-west-1.compute.amazonaws.com", 
                                "IpOwnerId": "amazon"
                            }
                        }
                    ], 
                    "SourceDestCheck": true, 
                    "Placement": {
                        "Tenancy": "default", 
                        "GroupName": "", 
                        "AvailabilityZone": "eu-west-1a"
                    }, 
                    "Hypervisor": "xen", 
                    "BlockDeviceMappings": [
                        {
                            "DeviceName": "/dev/sda1", 
                            "Ebs": {
                                "Status": "attached", 
                                "DeleteOnTermination": true, 
                                "VolumeId": "vol-0467d8f7608281d6b", 
                                "AttachTime": "2017-11-30T11:33:39.000Z"
                            }
                        }
                    ], 
                    "Architecture": "x86_64", 
                    "RootDeviceType": "ebs", 
                    "RootDeviceName": "/dev/sda1", 
                    "VirtualizationType": "hvm", 
                    "Tags": [
                        {
                            "Value": "Packer Builder", 
                            "Key": "Name"
                        }
                    ], 
                    "AmiLaunchIndex": 0
                }
            ], 
            "ReservationId": "r-XXX", 
            "Groups": [], 
            "OwnerId": "XXX"
        }
    ]
}
```

**Comment by rickard-von-essen** [comment] 2017-12-03 07:29
I added some debug printouts and it shows that `PublicIpAddress` is `nil`.

```
2017/12/03 08:22:23 packer: 2017/12/03 08:22:23 PublicIpAddress NULL
2017/12/03 08:22:23 packer: 2017/12/03 08:22:23 Using: 172.31.0.74
2017/12/03 08:22:38 packer: 2017/12/03 08:22:38 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.31.0.74:22: i/o timeout
```

At the same time:

```
aws --region eu-west-1 --profile packer-demo ec2 describe-instances --filter Name=instance-state-name,Values=running --query 'Reservations[0].Instances[0].[PublicIpAddress,PrivateIpA
ddress]'
[
    "34.253.222.31",
    "172.31.0.74"
]
```

**Comment by SwampDragons** [comment] 2017-12-04 20:08
we suspect this might be fixed by https://github.com/hashicorp/packer/pull/5630; if any of you experiencing this issue can build that branch and test we'd be much obliged.

**Comment by mwhooker** [comment] 2017-12-04 20:20
hmm, I wasn't actually able to reproduce this issue with

```
{
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "packer-c5-ami",
      "region": "us-east-1",
      "associate_public_ip_address": true,
      "sriov_support": true,
      "ena_support": true,
      "subnet_id": "subnet-077fde4e",
      "instance_type": "c5.large",
      "ssh_username": "ec2-user",
      "ssh_pty": true,
      "ssh_timeout": "5m",
      "source_ami": "ami-c998b6b2"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "echo SSH test successful"
      ]
    }
  ]
}
```

https://gist.github.com/mwhooker/94c812c248bfdb4e0a109228d110af9e


I _did_ notice that there seems to be an undocumented dependency on there being `subnet_id`. Once I added one it worked


Can anyone help me reproduce this?

**Comment by rickard-von-essen** [comment] 2017-12-05 09:09
I have reproduced it.

**Comment by rickard-von-essen** [comment] 2017-12-07 05:23
A slightly smaller example that repros this.

```json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "packer-c5-ami",
      "region": "eu-west-1",
      "associate_public_ip_address": true,
      "sriov_support": true,
      "ena_support": true,
      "instance_type": "c5.large",
      "ssh_username": "ec2-user",
      "ssh_timeout": "5m",
      "source_ami": "ami-1a962263"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "echo SSH test successful"
      ]
    }
  ]
}
```

It actually succeed something like 1 time out of 5. My hunch tells me that we should try to refresh the instance information and everything will work as it should.

**Comment by mwhooker** [comment] 2017-12-07 19:59
okay I can reproduce now. The problem I see with refreshing the state (like moving the `DescribeInstances` code from builder/amazon/common/ssh.go up to the top of the loop) is that we don't know what we're looking for. I think we probably need to wait for the instance to update in launch source instance or something. Still trying to understand why this instance behaves differently from others

**Comment by rickard-von-essen** [comment] 2017-12-07 20:25
Pretty sure the reason that C5 behaves different is that they are using a different hypervisor. See https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/

**Comment by mwhooker** [comment] 2017-12-07 20:28
I think I have it resolved. removed our custom waiter code and replaced with `WaitUntilInstanceStatusOk` and it seems to work every time. Will push up a patch soon and would love some confirmation

**Closed** 2017-12-07 22:47 UTC
Labels: bug, builder/amazon

**Comment by dnk8n** [comment] 2019-08-09 17:18
I am stll hitting this error with the following template:

```
{
  "builders": [
    {
      "type": "amazon-ebs",
      "spot_price": "auto",
      "spot_price_auto_product": "Linux/UNIX (Amazon VPC)",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "ami_name": "{{user `ami_name`}}",
      "force_deregister": true,
      "force_delete_snapshot": true,
      "iam_instance_profile": "{{user `iam_instance_profile`}}",
      "instance_type": "{{user `instance_type`}}",
      "region": "{{user `region`}}",
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "{{user `ami_name_regex`}}",
          "root-device-type": "ebs"
        },
        "owners": ["{{user `ami_owner`}}"],
        "most_recent": true
      },
      "tags": {"name": "{{user `ami_name`}}"},
      "ssh_username": "{{user `ssh_username`}}"
    }
  ],

  ...

}
```

**Comment by rickard-von-essen** [comment] 2019-08-09 17:30
This issue was closed over a year ago. Please ask on the mailing list if you have any problems or open a new issue if you found a bug.

**Comment by dnk8n** [comment] 2019-08-09 17:30
Aah, note: manually adding:

"ssh_interface": "public_ip"

worked in my case :)
I don't understand, but since explicit is better than implicit I don't care enough to dig deeper.
