### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by rclsilver** [hashicorp/packer#8258] opened 2019-10-22 17:20 UTC
#### Overview of the Issue

When i want to create an image in glance, i've following error with packer 1.4.4: panic: interface conversion: interface {} is nil, not string.

#### Reproduction Steps

```
$ . openrc.sh
$ export OS_NETWORK_EXT_NET=$(openstack network list -f json | jq -r '.[] | select(.Name == "Ext-Net") | .ID')
$ packer build packer.json
```

### Packer version

1.4.4

### Simplified Packer Buildfile

https://gist.github.com/rclsilver/45ca08317b2788913f578228ef9e3cb1

### Operating system and Environment details

Ubuntu 18.04 with packer 1.4.4

### Log Fragments and crash.log files

In previous gist

**Comment by SwampDragons** [comment] 2019-10-22 19:34
Hi, thanks for reaching out! I think this is a duplicate of #8197 -- this crash has been fixed in our current nightly build: https://github.com/hashicorp/packer/releases/tag/nightly. I'm going to close as a duplicate, but if you still experience it with the Nightly build, we can reopen.

**Closed by SwampDragons** 2019-10-22 19:34 UTC
Labels: bug, builder/openstack, crash

**Comment by ppouliot** [comment] 2019-10-28 20:02
You don't have ARM64 Builds in your nightlys and I'm also experiencing this issue.  Any change to get some ARM64 binaries or push a new release upstream?
