### ISSUE TITLE
Packer 1.8.2 and newer disregards ssh_host parameter (checked with qemu builder)

### ISSUE THREAD

**Issue by amaczuga** [hashicorp/packer#11961] opened 2022-08-26 12:32 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Version 1.8.2 and older is disregarding `ssh_host` variable, at least with qemu builder.

#### Reproduction Steps

Just try to force `ssh_host` value and watch it being disregarded.

### Packer version

`1.8.2`, `1.8.3`

### Simplified Packer Template

```
{
  "builders": [
    {
      "name": "mybuild",
      "vm_name": "image.qcow2",
      "type": "qemu",
      "qemuargs": [
        [ "-cpu", "host,pmu=off" ],
        [ "-bios", "/usr/share/OVMF/OVMF_CODE.fd" ],
        [ "-device", "{{user `net_device`}},netdev=user.0" ],
        [ "-netdev", "bridge,id=user.0,br={{user `net_bridge`}}" ],
        [ "-serial", "stdio" ],
        [ "-no-reboot" ]
      ],
      "disk_image": "true",
      "disk_interface": "ide",
      "net_device": "{{user `net_device`}}",
      "disk_size": "150000",
      "cpus": "4",
      "memory": "4096",
      "boot_wait": "9s",
      "format": "qcow2",
      "headless": "true",
      "http_directory": ".",
      "iso_checksum": "none",
      "iso_url": "output-uefi/{{user `image_name`}}.qcow2",
      "ssh_username": "root",
      "ssh_password": "{{user `password`}}",
      "skip_nat_mapping": "true",
      "ssh_host": "192.168.133.2",
      "ssh_port": 22,
      "ssh_pty": true,
      "ssh_wait_timeout": "10000s",
      "vnc_bind_address": "0.0.0.0",
      "shutdown_command": "/sbin/halt"
    }
  ]
}
```
### Operating system and Environment details

ubuntu:jammy amd64
packer_1.8.2_linux_amd64.zip
packer_1.8.3_linux_amd64.zip

### Log Fragments and crash.log files

1. packer 1.8.1
```
+ PACKER_LOG=1
+ packer build -parallel-builds=1 -only=mybuild template.json
2022/08/26 11:54:21 [INFO] Packer version: 1.8.1 [go1.17.8 linux amd64]
(...)
2022/08/26 11:54:37 packer-builder-qemu plugin: Using host value: 192.168.133.2
ESC[0;32m    postconfig-uefi: Not using a NetBridge -- skipping StepWaitGuestAddressESC[0m
ESC[1;32m==> postconfig-uefi: Using SSH communicator to connect: 192.168.133.2ESC[0m
2022/08/26 11:54:37 packer-builder-qemu plugin: [INFO] Waiting for SSH, up to timeout: 2h46m40s
2022/08/26 11:54:37 packer-builder-qemu plugin: Using host value: 192.168.133.2
ESC[1;32m==> postconfig-uefi: Waiting for SSH to become available...ESC[0m
2022/08/26 11:54:38 packer-builder-qemu plugin: Qemu stdout: <4>TCG2 protocol not available: 800000000000000e
2022/08/26 11:54:40 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 192.168.133.2:22: connect: no route to host
2022/08/26 11:54:45 packer-builder-qemu plugin: Using host value: 192.168.133.2
```
2. packer 1.8.2
```
+ PACKER_LOG=1
+ packer build -parallel-builds=1 -only=mybuild template.json
2022/08/25 09:33:09 [INFO] Packer version: 1.8.2 [go1.17.11 linux amd64]
(...)
2022/08/25 09:33:23 packer-builder-qemu plugin: Using host value: 127.0.0.1
ESC[0;32m    postconfig-uefi: Not using a NetBridge -- skipping StepWaitGuestAddressESC[0m
ESC[1;32m==> postconfig-uefi: Using SSH communicator to connect: 127.0.0.1ESC[0m
2022/08/25 09:33:23 packer-builder-qemu plugin: [INFO] Waiting for SSH, up to timeout: 2h46m40s
2022/08/25 09:33:23 packer-builder-qemu plugin: Using host value: 127.0.0.1
ESC[1;32m==> postconfig-uefi: Waiting for SSH to become available...ESC[0m
2022/08/25 09:33:23 packer-builder-qemu plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:22: connect: connection refused
2022/08/25 09:33:24 packer-builder-qemu plugin: Qemu stdout: <4>TCG2 protocol not available: 800000000000000e
2022/08/25 09:33:28 packer-builder-qemu plugin: Using host value: 127.0.0.1
```

**Comment by lbajolet-hashicorp** [comment] 2022-09-22 22:00
Hi @amaczuga,

I am indeed able to reproduce the problem in my local setting, however I'm not certain the problem is emanating from Packer, but from the Qemu plugin.
I wonder why the downgrade fixes the problem to be completely honest, in my local setting with manually built plugin + packer, downgrading Packer does not fix the issue, which corroborates what I see in the code.
My hypothesis is maybe a different version of the plugin is loaded in 1.8.1 vs. 1.8.2? Could you paste the complete logs so we could confirm/infirm this hypothesis?

I'm working on a fix for this, I don't expect to come up with a PR today, but hopefully tomorrow I'll have something to show.

Thanks for reporting this issue

**Comment by lbajolet-hashicorp** [comment] 2022-09-22 22:08
Note: I suspect version 1.0.5 of the Qemu plugin is when it starts failing, commit f65be3cb4b5 changes the logic for resetting the host, which is what is happening here from what I can see.
I don't want to accidentally break the logic for WinRM by fixing SSH, so I still need to investigate, but in the meantime, can you confirm this is indeed what happens in your setup?

Locally, I can confirm that Qemu 1.0.4 does not exhibit this bug, and 1.0.5 does, so it does seem to be introduced in the plugin.

**Closed** 2022-09-23 14:00 UTC
Labels: bug, regression

**Comment by lbajolet-hashicorp** [comment] 2022-09-23 14:41
With this PR on the qemu plugin merged, this should also be fixed, provided you use the right version of the plugin.
If you experience this issue, there's two ways out at the moment:

1) Explicitly specify the communicator type: `ssh` is the default value, but a logic error slipped into the plugin's code, which is the cause for the reset in the host address. If you add a `"communicator": "ssh"` statement to your config, this error will go away.

2) Downgrade plugin to 1.0.4, or when a new version with the fix is released, bump to this version.

Feel free to reopen this issue if the problem persists @amaczuga, I've tried my first suggestion locally, the error does go away in this case, this is probably the easiest fix you can apply in the current state.

Thanks again for bringing this to our attention!

**Comment by amaczuga** [comment] 2022-09-23 15:24
@lbajolet-hashicorp thank you for your attention and care. The workaround is more than enough for now, and then I'll switch to the fixed release, when it comes. You've been a huge help - and timely. Kudos.

**Comment by lbajolet-hashicorp** [comment] 2022-09-23 17:01
So you know @amaczuga, the v1.0.6 of the plugin is now live, with the fix mentioned in this issue!

If you update to the latest version, the workaround will not be necessary anymore.
