### ISSUE TITLE
local-shell post-processor on windows

### ISSUE THREAD

**Issue by TraGicCode** [hashicorp/packer#4955] opened 2017-06-02 10:37 UTC
Does anyone have a working example or know if it's possible to use the local-shell post-processor on windows to

1.) Execute a cmd.exe command
2.) Execute a powershell command

I was unable to get this to work and also was unable to find any examples

**Comment by rickard-von-essen** [comment] 2017-06-02 11:02
Thanks for reporting this. This is a duplicate of #4140.

**Closed by rickard-von-essen** 2017-06-02 11:02 UTC
