### ISSUE TITLE
Powershell Provision Multiple Scripts is not working on Windows 8

### ISSUE THREAD

**Issue by Skarlso** [hashicorp/packer#2484] opened 2015-07-22 14:10 UTC
Hi Guys. 

Powershell provisioner is not working when I'm trying to provision a Windows 8 box. 

This only happens when I have multiple scripts like this: 

``` json
    {
      "type": "powershell",
      "scripts" : [
        "./scripts/install-selenium-server.ps1",
        "./scripts/install-chrome-firefox.ps1"
      ]
    }
```

Here is what it tells me:

```
1437573370,,ui,message,    virtualbox-iso: sh: -c: line 2: syntax error: unexpected end of file
1437573370,,ui,say,==> virtualbox-iso: Provisioning with shell script: ./scripts/install-chrome-firefox.ps1
1437573370,,ui,message,    virtualbox-iso: sh: -c: line 2: syntax error: unexpected end of file
```

I'm guessing the concatenation into one script does not work? 

Ps.: This is not urgent, as I was able to circumvent the problem by putting everything into one script myself for the moment.

Cheers,
Gergely.

**Comment by cbednarski** [comment] 2015-07-25 08:22
Thanks for the bug repot. I'm a little confused because your log looks like it's trying to run through bash rather than powershell (`sh -c`).

However, when multiple scripts are specified like that it should upload each one and execute it by itself in the order you specify. They don't get merged. This looks like a bug to me.

As a work-around you can try specifying the shell block twice:

```
    {
      "type": "powershell",
      "script" : "./scripts/install-selenium-server.ps1"
    },
    {
      "type": "powershell",
      "script" : "./scripts/install-chrome-firefox.ps1"
    }
```

**Comment by Skarlso** [comment] 2015-07-26 21:36
Cheers, I'll try that when I get in tomorrow. :)

**Comment by pecigonzalo** [comment] 2015-07-27 00:49
@Skarlso what communicator are you usign? SSH?

**Comment by Skarlso** [comment] 2015-07-27 04:56
Yes. :-)

**Comment by pecigonzalo** [comment] 2015-07-27 05:16
@Skarlso  Could you set your ```PACKER_LOG=``` variable to true, and past a link to a gist with the output?

**Comment by Skarlso** [comment] 2015-08-06 18:15
Sorry folks, I was on vacation. I'll be looking at this tomorrow earliest, when I'm at work.

**Comment by andrewpwade** [comment] 2015-10-27 15:32
I'm seeing this too. I saw it before, but did something to fix it, then broke it again. Could it have something to do with line endings/file encoding?

Log: https://gist.github.com/andrewpwade/2306cacb146431a703ed

```
        {
            "type": "powershell", 
            "only": [
                "vmware-vmx"
            ], 
            "execute_command": "powershell -ExecutionPolicy Bypass \"& { {{.Path}}; exit $LastExitCode}\"", 
            "scripts": [
                "./scripts/win-updates.ps1"
            ]
        }, 
```

I tested manually scp the file and then ssh'ing and running the same powershell command and it was fine.

**Comment by pecigonzalo** [comment] 2015-10-27 19:08
Can you check if your ps1 files are saved as CRLF or LF?

**Comment by andrewpwade** [comment] 2015-10-28 22:47
(I had a previous comment but deleted it. This is the packer log I posted in that comment exemplifying the issue: https://gist.github.com/andrewpwade/2306cacb146431a703ed)

I tried various combinations of: converting line endings of all scripts to CRLF, LF, ASCII, UTF-8, setting "boolean: true", running one script at a time, using the shell provisioner and using the powershell provisioner.

It was weird that it only affected the .ps1 files and not the .bat scripts. It must be to do with the launching of the powershell command, and some error being raised Windows side. That's all I could conclude

**Comment by pecigonzalo** [comment] 2015-10-29 19:58
If you use the workaround provided does it work?

I think it might have something to do with the way packer creates the execution script when using ssh.
Ill check now.

**Comment by pecigonzalo** [comment] 2015-10-29 20:18
Could you try and grab the file ```./scripts/install-chrome-firefox.ps1``` (ps1) mid provisioning and check the line endings?
Also if you could upload your setup (scripts+packer.json file) i can try and replicate and troubleshoot.

**Comment by Skarlso** [comment] 2015-11-01 21:46
Again, I'm sorry about this delay. 

I created several reminders to check on this once I'm in tomorrow early in the morning. 

I'll have your answer. Though I remember, that I solved this issue in the end... I shall post the result tomorrow.

**Comment by Skarlso** [comment] 2015-11-02 08:24
Yes, so I solved this issue by aggregating my two scripts into one. 

Sure, I'll upload my packer and the scripts.

Though this is the one which is working right now.

If you separate the two, firefox and chrome, into separate files and append them, they'll fail. 

This thing doesn't support Json files. :O

json:
```json
{
      "variables": {
      "vm_name": "win8x64selenium",
      "output_dir": "output_win8_x64_selenium",
      "vagrant_box_output": "box_output",
      "cpu_number": "2",
      "memory_size": "4096",
      "machine_type": "pc-1.2",
      "accelerator": "kvm",
      "disk_format": "qcow2",
      "disk_interface": "virtio",
      "net_device": "virtio-net",
      "cpu_model": "host",
      "disk_cache": "writeback",
      "disk_io": "native"
   },

  "builders": [
    {
      "type": "virtualbox-iso",
      "iso_url": "<bla>",
      "iso_checksum_type": "md5",
      "iso_checksum": "<bla>",
      "headless": true,
      "boot_wait": "2m",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "8h",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "guest_os_type": "Windows81_64",
      "disk_size": 61440,
      "floppy_files": [
        "./answer_files/81-selenium/Autounattend.xml",
        "./scripts/dis-updates.ps1",
        "./scripts/win-updates.ps1",
        "./scripts/microsoft-updates.bat",
        "./scripts/openssh.ps1",
        "./scripts/jdk_inst.ps1",
        "./scripts/7zip_inst.ps1",
        "./scripts/oracle-cert.cer",
        "./scripts/install-dotnet-40.ps1",
        "./scripts/choco_install.ps1"
      ],
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "{{user `memory_size`}}"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "{{user `cpu_number`}}"
        ]
      ]
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "scripts" : [
        "./scripts/install-chrome-firefox-selenium.ps1"
      ]
    },{
      "type": "shell",
      "remote_path": "/tmp/script.bat",
      "execute_command": "{{.Vars}} cmd /c C:/Windows/Temp/script.bat",
      "scripts": [
        "./scripts/vm-guest-tools.bat",
        "./scripts/vagrant-ssh.bat",
        "./scripts/rsync.bat",
        "./scripts/enable-rdp.bat"
      ]
    }
  ],
    "post-processors": [
    {
      "type": "vagrant",
      "keep_input_artifact": false,
      "output": "{{user `vm_name`}}_{{.Provider}}.box",
      "vagrantfile_template": "vagrantfile-template"
    }
    ]
}

```

script:
```powershell
#htttps://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B5E640EF2-B1F4-32F4-CDCD-8A1AABCA32CA%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers/dl/chrome/install/googlechromestandaloneenterprise.msi
#https://download-installer.cdn.mozilla.net/pub/firefox/releases/39.0/win32/hu/Firefox%20Setup%2039.0.exe -ms

function LogWrite {
    Param ([string]$logstring)
    $now = Get-Date -format s
    Add-Content $Logfile -value "$now $logstring"
    Write-Host $logstring
}

function CheckLocation {
    Param ([string]$location)
    if (!(Test-Path  $location)) {
        throw [System.IO.FileNotFoundException] "Could not download to Destination $location."
    }
}

$Logfile = "C:\Windows\Temp\chrome-firefox-install.log"

$chrome_source = "http://dl.google.com/chrome/install/375.126/chrome_installer.exe"
$chrome_destination = "C:\Windows\Temp\chrome_installer.exe"
$firefox_source = "https://download-installer.cdn.mozilla.net/pub/firefox/releases/39.0/win32/hu/Firefox%20Setup%2039.0.exe"
$firefox_destination = "C:\Windows\Temp\firefoxinstaller.exe"


LogWrite 'Starting to download files.'
try {
    LogWrite 'Downloading Chrome...'
    (New-Object System.Net.WebClient).DownloadFile($chrome_source, $chrome_destination)
    CheckLocation $chrome_destination
    LogWrite 'Done...'
    LogWrite 'Downloading Firefox...'
    (New-Object System.Net.WebClient).DownloadFile($firefox_source, $firefox_destination)
    CheckLocation $firefox_destination
} catch [Exception] {
    LogWrite "Exception during download. Probable cause could be that the directory or the file didn't exist."
    LogWrite '$_.Exception is' $_.Exception
}

LogWrite 'Starting firefox install process.'
try {
    Start-Process -FilePath $firefox_destination -ArgumentList "-ms" -Wait -PassThru
} catch [Exception] {
    LogWrite 'Exception during install process.'
    LogWrite '$_.Exception is' $_.Exception
}
LogWrite 'Starting chrome install process.'

try {
    Start-Process -FilePath $chrome_destination -ArgumentList "/silent /install" -Wait -PassThru
} catch [Exception] {
    LogWrite 'Exception during install process.'
    LogWrite '$_.Exception is' $_.Exception
}

LogWrite 'All done.'

LogWrite 'Downloading selenium.'

$Logfile = "C:\Windows\Temp\selenium-install.log"

$SeleniumSource = "http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar"
$SeleniumDestination = "C:\Windows\Temp\selenium-server.jar"
LogWrite 'Starting to download selenium file.'
try {
  (New-Object System.Net.WebClient).DownloadFile($SeleniumSource, $SeleniumDestination)
} catch [Exception] {
  LogWrite "Exception during download. Probable cause could be that the directory or the file didn't exist."
  LogWrite '$_.Exception is' $_.Exception
}
LogWrite 'Download done. Checking if file exists.'
if (!(Test-Path $SeleniumDestination)) {
  LogWrite 'Downloading dotnet Failed!'
} else {
  LogWrite 'Download successful.'
}

LogWrite 'All done. Goodbye.'
# LogWrite "Resarting Computer."
# Restart-Computer -Force

```

**Comment by floradu88** [comment] 2017-10-15 14:31
Still this is an issue on latest packer build.

**Comment by floradu88** [comment] 2017-10-17 10:20
Will try to do this later today. Thanks

**Comment by Skarlso** [comment] 2017-10-17 10:22
Yaay, good luck. :)

**Comment by floradu88** [comment] 2017-10-18 08:43
Looks like one of the scripts(had a shutdown command and did not wait for powershell to finish) and could not reproduce the bugs as described by @SwampDragons. I think this can be closed/resolved.

**Comment by SwampDragons** [comment] 2017-10-18 16:44
Thanks for following up!  Feel free to open a new ticket if something else comes up.

**Closed by SwampDragons** 2017-10-18 16:44 UTC
Labels: bug, provisioner/powershell
