### ISSUE TITLE
Using file provisioner to copy over directory on GNU OS leaves temp directory in destination path

### ISSUE THREAD

**Issue by ewhittick** [hashicorp/packer#5254] opened 2017-08-15 14:47 UTC
When copying over directories into a GNU-host-based container, the temporary `dirupload` directories are copied to the destination directory.

e.g.

**Provisioner:**
```
    {
      "type": "file",
      "source": "../../node_modules",
      "destination": "/app"
    }
```

Results in:
```
root@cd81954e7eb1:/app# ls -al node_modules/
total 40
drwxr-xr-x   3 root root  4096 Aug 15 13:44 .
drwxr-xr-x   6 root root  4096 Aug 15 13:45 ..
drwx------ 765 root root 28672 Aug 15 13:45 dirupload715725899
```

The same behaviour occurs (copying over of the temp directory) regardless of the presence of the trailing slash on source or destination.

Using `cp -RT` as opposed to `cp -R` in this case would produce the expected behaviour.

**Packer version:** 1.0.4
**Host:** macOS 10.12.6

**Provisioning on:**
- Docker builder
- Debian Jesse image (https://github.com/nodejs/docker-node/blob/35dbf01b344f08903574c39ce69866e2e7cb11af/8.3/Dockerfile)

**Debug Log:**
```
==> docker: Uploading ../../node_modules/ => /app/node_modules/
2017/08/15 14:32:27 packer: 2017/08/15 14:32:27 Executing docker exec -i e317e421716ddf52b8d7f7fba251aa7124e405e94736ac0aca24fa9c7ab55411 /bin/sh -c (set -e; mkdir -p /app/node_modules/; command cp -R /packer-files/dirupload994093362/ /app/node_modules/):
2017/08/15 14:33:26 [INFO] (telemetry) ending file
```

**Comment by SwampDragons** [comment] 2017-08-15 17:33
This one's my bad.  See https://github.com/hashicorp/packer/pull/5251.  I'll try to merge a fix soon.

**Comment by SwampDragons** [comment] 2017-08-15 17:41
closing as duplicate of https://github.com/hashicorp/packer/issues/5243

**Closed** 2017-08-15 17:41 UTC

**Comment by flaviogranato** [comment] 2017-09-13 11:27
Don't work yet. Could somebody do a double check?

**Comment by mwhooker** [comment] 2017-09-13 17:26
@flaviogranato why don't you open a new ticket with information to help us reproduce. Make sure you're on 1.1.0

**Comment by mwhooker** [comment] 2017-09-13 19:26
oops, didn't mean to lock this
