### ISSUE TITLE
Show Azure errors when Azure returns errors

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#4928] opened 2017-05-25 10:31 UTC
Right now some azure-arm builder operations simply state that something goes wrong. For example:

```
error: --> azure-arm: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/7b8f7512-4d66-425f-bdc3-c24ebef1b03e/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400
```

However, there is actually a lot of valuable information in the HTTP response body. This information (even in raw form) should be displayed to the user or at the very least logged to the debug log.

Example of HTTP response corresponding to the above message:

```
{"error":"unauthorized_client","error_description":"AADSTS70001: Application with identifier 'daee03d3-xxxx-xxxx-xxxx-daea1e94cc48' was not found in the directory 7b8f7512-xxxx-xxxx-xxxx-c24ebef1b03e\r\nTrace ID: 35096606-xxxx-xxxx-xxxx-22d804035400\r\nCorrelation ID: 059401b6-xxxx-xxxx-xxxx-9caa64b83a2d\r\nTimestamp: 2017-05-25 10:28:42Z","error_codes":[70001],"timestamp":"2017-05-25 10:28:42Z","trace_id":"35096606-xxxx-xxxx-xxxx-22d804035400","correlation_id":"059401b6-xxxx-xxxx-xxxx-9caa64b83a2d"}
```

Similar issue of not reporting enough data exists when the template deployment fails - only the "something is wrong" error is displayed, even though the response actually has much more useful data.

This is what is displayed: 

```
azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

This is what is in the response (the real error message!):

```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"An invalid value was provided for 'accessPolicies'.\"\r\n  }\r\n}"}]}}
```

**Comment by rdonkin** [comment] 2017-06-08 08:45
I'm having exactly this problem.

@boumenot - can you share the workaround to get the real error message in HTTP response?  Did you use a proxy?

**Comment by sandersaares** [comment] 2017-06-08 08:51
The error message in the 2nd example is actually displayed if you show the detailed log (`set PACKER_LOG=1`).

With the first case, I had to use a proxy (Fiddler), directing Packer to use it via `set http_proxy=localhost:8888` and `set https_proxy=localhost:8888`.

**Comment by rdonkin** [comment] 2017-06-08 09:29
I have got `PACKER_LOG=1` enabled, but it doesn't show any more detail than the stdout messages:

```
2017/06/08 08:39:34 ui: ==> azure-arm: Obtained service principal token.
2017/06/08 08:39:34 ui:     azure-arm: Creating Azure Resource Manager (ARM) client ...
2017/06/08 08:39:36 ui: ==> azure-arm: Creating resource group ...
2017/06/08 08:39:36 ui: ==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-qv9fv3d24c'
2017/06/08 08:39:36 ui: ==> azure-arm:  -> Location          : 'UK South'
2017/06/08 08:39:37 ui: ==> azure-arm: Validating deployment template ...
2017/06/08 08:39:37 ui: ==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-qv9fv3d24c'
2017/06/08 08:39:37 ui: ==> azure-arm:  -> DeploymentName    : 'pkrdpqv9fv3d24c'
2017/06/08 08:39:38 ui: ==> azure-arm: Deploying deployment template ...
2017/06/08 08:39:38 ui: ==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-qv9fv3d24c'
2017/06/08 08:39:38 ui: ==> azure-arm:  -> DeploymentName    : 'pkrdpqv9fv3d24c'
2017/06/08 08:40:41 ui error: ==> azure-arm: resources/DeploymentsClient:CreateOrUpdate 200 Failure sending request -- Original Error: Azure Operation Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
2017/06/08 08:40:41 ui error: Build 'azure-arm' errored: resources/DeploymentsClient:CreateOrUpdate 200 Failure sending request -- Original Error: Azure Operation Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

A bit off-topic, but can someone suggest how to "list deployment operations" to get more detail in this case?   I'm using the device login flow in case that's relevant.

**Comment by rdonkin** [comment] 2017-06-08 10:06
For others in same situation with deployment failures in Packer Azure, see Microsoft's [help page for deployment operation errors](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-deployment-operations) - shows how to find the details of deployment error in the Azure portal, which turned out to be that machine type requested is not available in my location.

**Comment by boumenot** [comment] 2017-06-09 00:57
This is a dupe of #3536 IMO.  I am working on a fix for this.  

You are right, there is much better data in the HTTP response that is lost. 

I purposefully triggered an error in the deployment template, and all I got was a message similar to the one above. With my fix, the error message is much more tractable.  (I do not guarantee this is always true.)

```text
ERROR: -> DeploymentFailed : At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
ERROR:   -> BadRequest
ERROR:   -> InvalidRequestFormat : Cannot parse the request.
ERROR:     -> InvalidJson : Error converting value "playground" to type 'Microsoft.WindowsAzure.Networking.Nrp.Frontend.Contract.Csm.Public.IpAllocationMethod'. Path 'properties.publicIPAllocationMethod', line 1, position 130.
```

**Comment by rdonkin** [comment] 2017-06-09 05:19
That error is much nicer!

Please also consider linking to [this Microsoft page](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-deployment-operations) as well as the aka.ms link.  Investigating the error through portal may provide more context as a fallback, if for some reason the error shown is not clear.

**Closed** 2017-06-26 20:23 UTC
Labels: bug, builder/azure

**Comment by shivakumarg06** [comment] 2019-02-20 18:06
Anyone know what causing this 

##[debug]==> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
